### ISSUE TITLE
Remote type visibility

### ISSUE THREAD

**Issue by arcnmx** [serde-rs/serde#1000]
The `#[serde(remote)]` attribute generates `deserialize` and `serialize` methods in an impl for the local type but they're private - this prevents a remote "Def" type in a module from being exported outside of it. There are workarounds (newtype or redefine proxy functions) but would there be any disadvantage to just marking these `pub`?

Or maybe traits could be used?

```rust
trait DeserializeInto<'de> {
    type Output;

    fn deserialize_into<D: Deserializer<'de>>(d: D) -> Result<Self::Output, D::Error>;
}

trait SerializeFrom {
    type Input;

    fn serialize_from<S: Serializer>(value: &Self::Input, s: S) -> Result<S::Ok, S::Error>;
}
```

(something like that, could be named `RemoteDeserialize` instead and I didn't really consider type parameters vs associates types)

**Comment by dtolnay** [comment]
I released the fix in serde_derive 1.0.11.
