### ISSUE TITLE
Is there a way to ser/de a vector of remote type without implementing the trait explicitly?

### ISSUE THREAD

**Issue by BusyJay** [serde-rs/serde#1005]
For example,

```
#[derive(Serialize, Deserialize)]
#[serde(remote = "B")]
struct A;

#[derive(Serialize, Deserialize)]
struct Array {
    bs: Vec<B>
}
```

`#[serde(with = "A")]` works only for singular field. Is there anything like `#[serde(with_item = "A")]`?

**Comment by dtolnay** [comment]
Not currently. We are tracking this in #723. I would love your thoughts on a design!

**Comment by genofire** [comment]
How do i implementing the trait explicitly till #723 is resolved?
