### ISSUE TITLE
Serializer/Deserializer for type using variable length encoding scheme

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#1007]
Moved from https://github.com/serde-rs/bytes/issues/4. @jinyuanxie

---

For example, I have a struct defined as follow:

```rust
pub struct VariableLength(u32);
```

And the field using a variable length encoding scheme, how can I implement Serializer/Deserializer for it?

```text
VariableLength <---> Vec<u8>/&[u8]
```

Thanks a lot.

**Comment by dtolnay** [comment]
Can you say more about your use case? What data format are you using? Are you implementing a new Serde data format from scratch?

**Comment by jinyuanxie** [comment]
@dtolnay emm, I'm want to use serde to ser/de MQTT protocol packet, some basic type, any packet is an combination of those basic type. In the iniaitl implement, I use custom trait `Encode` `Decode` to do this:
``` rust
impl Encode for VariableLength {
    fn encode(&self) -> Vec<u8> {
        ....
    }
    fn encoded_len(&self) -> usize {
        ....
    }
}

impl Decode for VariableLength {
    fn decode(i: &[u8]) -> IResult<&[u8], VariableLength> {
        ....
    }
}

pub struct NewPacket {
    len: VaribaleLength,
    ...
}
```

but I found that serde may do this more flexible, and want to rewrite my code, but didn't know how to start to do this..

**Comment by dtolnay** [comment]
Based on [MQTT specification](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html), I would recommend using [`nom`](https://github.com/Geal/nom) to parse packets. Serde is not a parsing library so if you have a working parser already then Serde would not provide any value.

**Comment by jinyuanxie** [comment]
Thanks a lot, I have to evaluate my needs.
