### ISSUE TITLE
Deserializer expecting a &str can't handle owned strings?

### ISSUE THREAD

**Issue by wfraser** [serde-rs/serde#1009]
(my example uses the serde_json crate, but I don't believe this is JSON specific)

As minimal of an example as I could come up with:
```
extern crate serde;
#[macro_use] extern crate serde_json;
use serde::de::{self, Deserialize, Deserializer, MapAccess, Visitor};

#[derive(Debug)]
struct Thing {
    pub foo: String,
}

impl<'de> Deserialize<'de> for Thing {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        struct MyVisitor;
        impl<'de> Visitor<'de> for MyVisitor {
            type Value = Thing;
            fn expecting(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
                f.write_str("a thing")
            }
            fn visit_map<V: MapAccess<'de>>(self, mut map: V) -> Result<Self::Value, V::Error> {
                let foo = match map.next_key()? {
                    Some("foo") => map.next_value()?,
                    _ => return Err(de::Error::missing_field("foo"))
                };
                Ok(Thing { foo: foo })
            }
        }
        const FIELDS: &'static [&'static str] = &["foo"];
        deserializer.deserialize_struct("Thing", FIELDS, MyVisitor)
    }
}

fn main() {
    // Ok(Thing { foo: "bar" })
    println!("{:?}", serde_json::from_str::<Thing>(r#"{"foo": "bar"}"#));

    let jsonvalue = json!({
        "foo": "bar"
    });
    
    // Err(ErrorImpl { code: Message("invalid type: string \"foo\", expected a borrowed string"), line 0, column 0 })
    println!("{:?}", serde_json::value::from_value::<Thing>(jsonvalue));
}
```

(playground link: https://play.rust-lang.org/?gist=0771979be1753cda7f5f39e631f24e70&version=stable)

I have a deserializer with a map visitor that wants the keys as a `&str`, but when deserializing from a `serde_json::Value` (for example), it gets them as `String`, and the visitor barfs.

How should I write this to indicate that I will take either an owned *or* borrowed string?

Or better yet, can the MapAccess automatically coerce an owned string into a `&str`? Seems to me like an owned string should always be acceptable when a `&str` is wanted.

The only way I've figured out to work around this is to have the visitor read the key as a `serde_json::Value`, and then use `Value::as_str()` to unwrap it. That handles both owned and borrowed strings, but then I have to handle the case where it's some other type myself, and the code gets really boilerplate-y.

**Comment by dtolnay** [comment]
You are seeing an owned string because `serde_json::from_value` cannot hand out &str references to the data in the Value -- the Value is destroyed when `from_value` returns, so those references wouldn't be valid anymore.

This change will make the visitor accept an owned string:

```diff
-                 let foo = match map.next_key()? {
-                     Some("foo") => map.next_value()?,
+                 let foo = match map.next_key::<String>()? {
+                     Some(ref k) if k == "foo" => map.next_value()?,
```

**Comment by wfraser** [comment]
Couldn't it return a `&'de str`?

**Comment by dtolnay** [comment]
Well you have `impl<'de> Visitor<'de> for MyVisitor` which means 'de can be anything. What if 'de is really long or even 'static? You can't get a &'static str out of a Value (`jsonvalue` in this case).
