### ISSUE TITLE
Multiple-value framework upon serde

### ISSUE THREAD

**Issue by crlf0710** [serde-rs/serde#1012]
Hi, currently `serde` provides great support for serialization and deserialization of exactly one value. However, there's actually needs for serialization and deserialization multiple values as a whole. The main differences are:
* There's always some indexing mechanism involved so values can "reference" each other.
* Seeking and deserialization on need, since deserializing everything may take quite some memory.
* Incremental serialization, appending the modified and recently-created values but leaving old values alone.

Formats like hprose , fdf and so on all works this way. 

This may be in the scope of serde, or it may be beyond it. Just want to hear that what do others think, though...

**Comment by dtolnay** [comment]
> Formats like hprose , fdf and so on all works this way.

What are some other ones?

What are the main differences between how hprose, fdf, and the other formats handle multiple-value?

**Comment by crlf0710** [comment]
Hprose ([docs.rs/hprose](http://docs.rs/hprose)) is intended for rpc use cases. it gives unsigned integer indexes to the "reference type" values occurred in the sequence (doesn't have to be top-level value), and later can use such indexes to reference those values mentioned earlier. The value sequences can be used as arguments of rpc functions.

FDF is a storage format intended to save and distribute "form data" from pdf files. The underlying storage format is general and used by serveral formats ([docs.rs/lopdf](http://docs.rs/lopdf)). It gives (object number, generation number) pairs to top-level values, and use those pairs to reference other values, which may come later in the file. There is an un-indexed value near the end the file which is seen as the root value. There's also an optional object number->byte offset directory near the end of the file intended for fast seeking within the file.

**Comment by Marwes** [comment]
@crlf0710 For the moment it should be possible to use [serde_state](https://github.com/marwes/serde_state) to handle shared values (using it in https://github.com/gluon-lang/gluon/pull/279)

**Comment by dtolnay** [comment]
Those sound different enough that I expect it will be quite challenging to generalize into one framework in a comprehensive way.

I would recommend prototyping something outside of Serde and once there is something working, we can revisit what parts are in scope for Serde.
