### ISSUE TITLE
Allow de/serialize_with on enum variants

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#1013]
This still needs to be fleshed out some more, but the idea would be to support things like empty_struct from https://github.com/serde-rs/serde/pull/1008 implemented in user code rather than in Serde.

```rust
#[derive(Serialize)]
#[serde(tag = "t", content = "c")]
enum E {
    Hello { foo: String },

    // serialize as `{ "t": "World", "c": {} }`
    #[serde(serialize_with = "empty_struct")]
    World,
}

fn empty_struct<signature TBD> { /* ... */ }
```

**Comment by dtolnay** [comment]
@spinda may be interested in working on a design.

**Comment by spinda** [comment]
I would like to propose the following ("design A"):

```rust
#[derive(Serialize)]
#[serde(tag = "t", content = "c")]
enum E {
    // normal variant (de)serialization
    Hello { world: String },

    // (de)serialize_with can be used to add special behavior to variants;
    // for tuple structs, each inner value is passed in order to the serialize
    // function, and the deserialize function produces a tuple (see below)
    #[serde(serialize_with = "my_special_serializer")]
    #[serde(deserialize_with = "my_special_deserializer")]
    Quux(String, u8),

    // struct variants are also supported, and are treated in the same way as
    // tuple variants, with inner values ordered by how they appear in the
    // definition
    #[serde(serialize_with = "my_special_serializer")]
    #[serde(deserialize_with = "my_special_deserializer")]
    Xyzzy {
        foo: String,
        bar: u8,
    },

    // for unit variants, the serialize function is passed only the serializer,
    // and the deserialize function is expected to produce ()
    #[serde(serialize_with = "serialize_empty_struct")]
    #[serde(deserialize_with = "deserialize_empty_struct")]
    Baz,
}

fn my_special_serializer<S>(foo: &String, bar: &u8, serializer: S) -> Result<S::Ok, S::Error>
    where S: Serializer,
{
    unimplemented!()
}

fn my_special_deserializer<'de, D>(deserializer: D) -> Result<(String, u8), D::Error>
    where D: Deserializer<'de>,
{
    unimplemented!()
}

fn serialize_empty_struct<S>(serializer: S) -> Result<S::Ok, S::Error>
    where S: Serializer,
{
    unimplemented!()
}

fn deserialize_empty_struct<'de, D>(deserializer: D) -> Result<(), D::Error>
    where D: Deserializer<'de>,
{
    unimplemented!()
}
```

The alternative, I believe, would be to pass the enumeration type in as a single argument to the serialize function and expect it as the output of the deserialize function ("design B"). Compared:

- Design A has the drawback of requiring long type signatures for variants with a lot of fields/inner types, while design B couldn't result in that situation. This could be avoided under design A by turning such a variant into a newtype variant wrapping around a separately-defined freestanding struct type. One might call this good practice in general, as variants that are so long they easily be pattern-matched are harder to manipulate elsewhere.

- If your (de)serialize functions only need to apply to one variant in an enum, Design B requires matching on the enum type and then either panicking or emitting an error on the alternate cases to make the totality checker happy. Design A avoids this.

- The simple fact that Design B would allow for producing a *different* variant of the enum type than the one which was annotated with `deserialize_with` seems ripe for confusion in my mind.

- Design A is more flexible with regard to reusability of the (de)serialize functions. For example, a single implementation of (de)serialize_empty_struct could be reused across multiple variants and multiple enum types. Design B requires that such functions be tied to a specific enum type and, in the case of deserializing, a specific variant of that enum: if multiple variants of your enum need the empty_struct behavior, a single deserialize function couldn't know which variant to produce.

**Comment by dtolnay** [comment]
Sounds good to me. I agree with all of your points and design A seems like a good path forward.
