### ISSUE TITLE
Stringish enum de/serialization

### ISSUE THREAD

**Issue by remexre** [serde-rs/serde#1019]
```rust
enum Enum {
    Foo,
    Bar,
    Quux,
    Other(String),
}
```

I want the de/serialization relation to be:

```
"foo" <-> Enum::Foo
"bar" <-> Enum::Bar
"quux" <-> Enum::Quux
"other thing" <-> Enum::Other("other thing")
```

**Comment by dtolnay** [comment]
There isn't an attribute for it but something like this could work:

```rust
impl Serialize for Enum {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
        where S: Serializer
    {
        serializer.serialize_str(match *self {
            Enum::Foo => "foo",
            Enum::Bar => "bar",
            Enum::Quux => "quux",
            Enum::Other(ref other) => other,
        })
    }
}

impl<'de> Deserialize<'de> for Enum {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
        where D: Deserializer<'de>
    {
        let s = String::deserialize(deserializer)?;
        Ok(match s.as_str() {
            "foo" => Enum::Foo,
            "bar" => Enum::Bar,
            "quux" => Enum::Quux,
            _ => Enum::Other(s),
        })
    }
}
```

**Comment by remexre** [comment]
Yeah, treat this as a feature request for an attribute.

**Comment by NeoLegends** [comment]
Any progress on this? Its very common to use a string as an enum within JSON APIs (for example), and you'd like to work with a strongly typed enum in rust land.

**Comment by dtolnay** [comment]
I would prefer to see this implemented as a separate derive macro in a different crate:

```rust
#[derive(Serialize_str, Deserialize_str)]
enum Enum {
    Foo,
    Bar,
    Quux,
    Other(String),
}
```

**Comment by godofdream** [comment]
for people searching a solution @dtolnay actually programmed a solution:
https://github.com/dtolnay/serde-repr

**Comment by kevlarr** [comment]
I wish there was an attribute for this (`pg_catalog` tables in Postgres have a variety of 'magic string' values that translate nicely to enums) but your custom `impl Deserialize` approach still works really @dtolnay - thanks for the great example!

**Comment by smbpndk** [comment]
Is this happening?

**Comment by danielo515** [comment]
@dtolnay your example is wonderful. Do you mind explaining me how it would look if the string were the first element of a single element array ? I have it almost working, but I have problems with lifetimes
