### ISSUE TITLE
`Wrapping` support

### ISSUE THREAD

**Issue by dhardy** [serde-rs/serde#1020]
Please consider adding support for [`std::num::Wrapping`](https://doc.rust-lang.org/std/num/struct.Wrapping.html).

Use-case: using `#[derive(Serialize, Deserialize)]` on RNGs like [`ChaChaRng`](https://github.com/rust-lang-nursery/rand/blob/master/src/chacha.rs#L30).

Of course, a work-around is possible, but `derive` won't work without support for `Wrapping`.

**Comment by dtolnay** [comment]
Added in #1072, released in 1.0.17.
