### ISSUE TITLE
Get a list of unknown fields

### ISSUE THREAD

**Issue by BenjaminGill-Metaswitch** [serde-rs/serde#1024]
Since #201 (#44 for the corresponding issue), we've had the choice of either (silently) allowing or denying unknown fields.

It would be useful when allowing unknown fields to be able to get a list of the unknown fields. This would allow us to be able to issue a warning about the extra fields without returning a full-blown error.

**Comment by dtolnay** [comment]
Check out [`serde-ignored`](https://github.com/dtolnay/serde-ignored).

**Comment by BenjaminGill-Metaswitch** [comment]
Awesome, thanks - that looks like exactly what I was seeking.

**Comment by rusty-snake** [comment]
FWIW, you can add a catch-all field to structs
```rust
#[derive(Debug, Deserialize, Serialize)]
pub struct Server {
    ip: String,
    hostname: String,

    #[serde(default)]
    #[serde(flatten)]
    _unknow_fields_: Option<HashMap<String, toml::Value>>,
}
```
