### ISSUE TITLE
#[serde(default="false")] failed to parse path: "false"

### ISSUE THREAD

**Issue by spease** [serde-rs/serde#1030]
Code:
```
#[macro_use]
extern crate serde_derive;
extern crate serde;

#[derive(Deserialize)]
struct A {
  #[serde(default="false")]
  a: bool,
}

fn main() {
    println!("Hello, world!");
}
```

Link to playground:
https://play.rust-lang.org/?gist=8792a9fd44c0fff060f54e8f3b5281c3&version=stable

**Comment by spease** [comment]
It seems you can work around it by creating a constant that is set to false.

**Comment by dtolnay** [comment]
Thanks! We are tracking this in #368.

**Comment by erichschroeter** [comment]
For anyone coming across this and #368 has not been merged, a workaround can be:

    #[macro_use]
    extern crate serde_derive;
    extern crate serde;
    
    fn default_as_false() -> bool {
        false
    }
    
    #[derive(Deserialize)]
    struct A {
      #[serde(default="default_as_false")]
      a: bool,
    }
    
    fn main() {
        println!("Hello, world!");
    }

Link to playground:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=12e58011d3cb46ba08e849e8a20592d5

**Comment by mcobzarenco** [comment]
@erichschroeter FWIW you can use `bool::default` which is `false` -- no need to roll your own function

```rust
#[derive(Deserialize)]
struct A {
  #[serde(default="bool::default")]
  a: bool,
}
```

**Comment by spencergilbert** [comment]
Also noting this seems to work:

```rust
#[derive(Deserialize)]
struct A {
  #[serde(default)]
  a: bool,
}
```

**Comment by alekspickle** [comment]
for anyone craving a more or less clean solution it can be achieved with const generics
[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=6ea499e1b47e9a65173a49db9ba9a1af)

The behavior is a bit off, but deterministic
Should I add a PR with those?
