### ISSUE TITLE
Add impls for (A)rc<str> and (A)rc<[T]>

### ISSUE THREAD

**Issue by alexbool** [serde-rs/serde#1037]
https://github.com/rust-lang/rfcs/blob/master/text/1845-shared-from-slice.md added more support for reference-counted slices and strings, and their usage is expected to grow. I think `serde_derive` should support them as well by providing relevant `Serialize` and `Deserialize` impls.

**Comment by dtolnay** [comment]
I released 1.0.12 with Serialize impls for any T: ?Sized and Deserialize impls for any T for which Box\<T>: Deseriarlize, which includes CStr.

**Comment by alexbool** [comment]
Thanks!
