### ISSUE TITLE
Enum-Tuple-Variant with single element should not be a sequence

### ISSUE THREAD

**Issue by oli-obk** [serde-rs/serde#104]
```rust
#[Deserialize]
enum A {
    B(i32),
    C(Vec<i32>),
}
```

The json for this requires additional square brackets for another array layer.

```json
{"C":[[5, 6, 7]]}

or

{"B":[42]}
```

Unit variants are already handles specially. I propose to also handle single element variants specially, so the following would be legal:

```json
{"C":[5, 6, 7]}

or

{"B":42}
```

Anyone that wishes to have the previous behavior, could use an explicit tuple.

```rust
#[Deserialize]
enum A {
    B((i32,)),
    C((Vec<i32>,)),
}
```

Alternatively deserialization might accept both, but that might be more of a mess than it's worth

**Comment by oli-obk** [comment]
The use-case is the pandoc ast

http://hackage.haskell.org/package/pandoc-types-1.12.4.4/docs/Text-Pandoc-Definition.html

**Comment by tomprogrammer** [comment]
That is interesting, because "normal" single element variants serialize directly as their inner type.

**Comment by oli-obk** [comment]
O_o, i need to investigate further then... maybe a newtype might come to my rescue

**Comment by tomprogrammer** [comment]
My claim isn't true, it was in a faulty version I wrote some time ago. Sorry for the rush.

**Comment by erickt** [comment]
That's an interesting idea. Way back in the early days of rustc-serialize, we used to serialize unit variants as a string, but someone from mozilla (maybe @pcwalton?) mentioned that JIT engines working with an array of enums really prefer those serialized enums to be of the same "shape". So this:

```rust
["a", {"b":[1]}, , {"c":[1, 2]}]
```

Is slower to work with than this:

```rust
[{"a": []}, {"b":[1]}, , {"c":[1, 2]}]
```

I wonder if the speed is worth it. @pcwalton: do you have an opinion on this?

**Comment by oli-obk** [comment]
That would be the obvious conclusion of my simplification. Serde could trivially deserialize from old-style unit enum variants in it's current setup, so both could be allowed. Serialization is a different issue though...

**Comment by pcwalton** [comment]
I guess that's true, but I wouldn't contort serde's JSON output to try to be JS JIT-friendly.
