### ISSUE TITLE
Annoying pattern in Elasticsearch JSON makes serde_derive less useful.

### ISSUE THREAD

**Issue by bitemyapp** [serde-rs/serde#1040]
I wasn't sure exactly where to file this as it cuts across serde, serde_derive, and serde_json.

I ran into a problem that required writing a custom `Serialize` impl for my type and it's a fairly common pattern in some JSON APIs and particularly Elasticsearch so I wanted to check I wasn't missing a nicer way of handling this.

The Elasticsearch Query type I was implementing was [Term Query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-term-query.html).

The problem is that rather than the document field being in a key-value pair like `field: "user"`, it's lifted into a key which them has the term value as the value. So this,

```
{
  "query": {
    "term" : { "user" : "Kimchy" } 
  }
}
```

Represents a query which returns documents which contain the term "Kimchy" in the document field "user". This is a somewhat common pattern in the ES API. My (working) attempt is below:

https://github.com/bitemyapp/duke/blob/master/src/lib.rs#L42-L78

I'd rather not have to do this over-and-over-and-over ad infinitum. Did I do the right thing? Is there an easier option? Should I make my own macro?

Sorry for bothering you but seemed like it'd be best to ask the devs.

**Comment by dtolnay** [comment]
I would factor out that logic into a single serialize function, maybe something like this.

```rust
extern crate serde;
#[macro_use]
extern crate serde_derive; 
#[macro_use]
extern crate serde_json;

#[derive(Serialize)]
#[serde(rename_all = "snake_case")]
enum Query {
    Term(#[serde(with = "query")] TermQuery),
    Range(#[serde(with = "query")] RangeQuery),
}

#[derive(Serialize)]
struct TermQuery {
    field: String,
    value: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    boost: Option<Boost>,
}

#[derive(Serialize)]
struct RangeQuery {
    field: String,
    gte: u64,
    lte: u64,
}

#[derive(Serialize)]
struct Boost(f64);

mod query {
    use serde::ser::{Serialize, Serializer, Error};
    use serde_json::{self, Value};

    pub fn serialize<T, S>(query: &T, serializer: S) -> Result<S::Ok, S::Error>
        where T: Serialize,
              S: Serializer
    {
        let value = serde_json::to_value(query).map_err(Error::custom)?;

        let mut map = match value {
            Value::Object(map) => map,
            _ => panic!("bug: query must be a JSON object"),
        };

        let field = match map.remove("field") {
            Some(field) => field,
            None => panic!("bug: query must have a field called `field`"),
        };

        let k = match field {
            Value::String(s) => s,
            _ => panic!("bug: `field` in query must be a string"),
        };

        json!({ k: map }).serialize(serializer)
    }
}

fn main() {
    let query = Query::Term(TermQuery {
        field: "status".to_owned(),
        value: "urgent".to_owned(),
        boost: Some(Boost(2.0)),
    });
    println!("{}", serde_json::to_string(&query).unwrap());
}
```
