### ISSUE TITLE
Implement serialization and deserialization for raw pointers

### ISSUE THREAD

**Issue by thomas-jeepe** [serde-rs/serde#1046]
Hey, so I'm working with emscripten and web assembly, and the only way to transfer data between JS and WASM is integers. So if I want to transfer something like a vector or something else, I need to pass a pointer to that vector.

Along with the data I want to send other information, so I end up sending a json object with pointers and other necessary information. If I want to encode the pointer, I convert it to an i32 rather than just using `*mut JsBytes` (a struct I built to send a `Uint8Array` or `Vec<u8>` between JS and WASM).

Anyways, this is how it would look like:

```rust
#[derive(Serialize, Deserialize, Debug)]
struct InitRes {
    ws_data: *mut JsBytes,
}
```

Instead of:

```rust
#[derive(Serialize, Deserialize, Debug)]
struct InitRes {
    ws_data: i32,
}
```
In 99.99% of scenarios this is completely unnecessary for normal use cases, but it is unfortunately necessary to send data between JS and WASM. The change really ends up being a visual change, as someone will then look at the code and it will be very clear what that `i32` means.

**Comment by dtolnay** [comment]
If you want to serialize the integer value of pointers, I would recommend implementing that logic yourself.

```rust
#[macro_use]
extern crate serde_derive;

extern crate serde;
extern crate serde_json;

struct JsBytes;

#[derive(Serialize, Deserialize, Debug)]
struct InitRes {
    #[serde(with = "wasm_pointer")]
    ws_data: *mut JsBytes,
}

mod wasm_pointer {
    use serde::ser::{Serialize, Serializer};
    use serde::de::{Deserialize, Deserializer};

    pub fn serialize<T, S>(ptr: &*mut T, serializer: S) -> Result<S::Ok, S::Error>
        where S: Serializer
    {
        (*ptr as usize).serialize(serializer)
    }

    pub fn deserialize<'de, T, D>(deserializer: D) -> Result<*mut T, D::Error>
        where D: Deserializer<'de>
    {
        <usize>::deserialize(deserializer).map(|u| u as *mut T)
    }
}

fn main() {
    let mut ws_data = JsBytes;
    let init_res = InitRes { ws_data: &mut ws_data };
    println!("{}", serde_json::to_string(&init_res).unwrap());
}
```

**Comment by thomas-jeepe** [comment]
Oh wow, I wasn't familiar enough with serde to know this, thanks for showing me how!
