### ISSUE TITLE
Is there a way to express this deserialization using only attributes?

### ISSUE THREAD

**Issue by golddranks** [serde-rs/serde#1056]
I have a the following enum:
```
#[serde(rename_all = "snake_case")]
pub enum FieldType {
    Noop,
    Hash,
    MaskHost,
    MaskAgent,
    DropField,
    Plugin(String),
}
```

I'd like to be able to deserialize JSON values like `"noop"` `"mask_host"` and such into corresponding variants. This far everything works, but I recently added a variant `Plugin(String)`, which should be the fallout case, in case none of the other variants match. The inner string should contain the value as text.

Is it possible to express this currently, or does this need some new attribute?

**Comment by golddranks** [comment]
Btw. I expected from the documentation that `#[serde(untagged)]` would support this case, but it didn't.

**Comment by oli-obk** [comment]
This is essentially #912

We don't support this yet, but are very interested in supporting it

**Comment by crsov** [comment]
There is a [workaround](https://www.rustexplorer.com/b#%2F*%0A%5Bdependencies%5D%0Aserde%20%3D%20%7Bversion%3D%22*%22%2Cfeatures%3D%5B%22derive%22%5D%7D%0Aserde_json%20%3D%20%22*%22%0A*%2F%0A%0Ause%20serde%3A%3ADeserialize%3B%0A%0A%23%5Bderive(Deserialize%2C%20Clone%2C%20Debug)%5D%0A%23%5Bserde(rename_all%20%3D%20%22snake_case%22)%5D%0Apub%20enum%20Noop%20%7B%0A%20%20%20%20Noop%2C%0A%7D%0A%0A%23%5Bderive(Deserialize%2C%20Clone%2C%20Debug)%5D%0A%23%5Bserde(rename_all%20%3D%20%22snake_case%22)%5D%0Apub%20enum%20Hash%20%7B%0A%20%20%20%20Hash%2C%0A%7D%0A%0A%23%5Bderive(Deserialize%2C%20Clone%2C%20Debug)%5D%0A%23%5Bserde(rename_all%20%3D%20%22snake_case%22)%5D%0Apub%20enum%20MaskHost%20%7B%0A%20%20%20%20MaskHost%2C%0A%7D%0A%0A%23%5Bderive(Deserialize%2C%20Clone%2C%20Debug)%5D%0A%23%5Bserde(rename_all%20%3D%20%22snake_case%22)%5D%0Apub%20enum%20MaskAgent%20%7B%0A%20%20%20%20MaskAgent%2C%0A%7D%0A%0A%23%5Bderive(Deserialize%2C%20Clone%2C%20Debug)%5D%0A%23%5Bserde(rename_all%20%3D%20%22snake_case%22)%5D%0Apub%20enum%20DropField%20%7B%0A%20%20%20%20DropField%2C%0A%7D%0A%0A%23%5Bderive(Deserialize%2C%20Clone%2C%20Debug)%5D%0A%23%5Bserde(rename_all%20%3D%20%22snake_case%22%2C%20untagged)%5D%0Apub%20enum%20FieldType%20%7B%0A%20%20%20%20Noop(Noop)%2C%0A%20%20%20%20Hash(Hash)%2C%0A%20%20%20%20MaskHost(MaskHost)%2C%0A%20%20%20%20MaskAgent(MaskAgent)%2C%0A%20%20%20%20DropField(DropField)%2C%0A%20%20%20%20Plugin(String)%2C%0A%7D%0A%0Afn%20main()%20%7B%0A%20%20%20%20println!(%0A%20%20%20%20%20%20%20%20%22R%3A%20%7B%3A%23%3F%7D%22%2C%0A%20%20%20%20%20%20%20%20serde_json%3A%3Afrom_str%3A%3A%3CVec%3CFieldType%3E%3E(%26%22%5B%20%5C%22noop%5C%22%2C%20%5C%22hash%5C%22%2C%20%5C%22mask_host%5C%22%2C%20%5C%22mask_agent%5C%22%2C%20%5C%22drop_field%5C%22%2C%20%5C%220475vb362087wysoivfadhfPLUGINosaiudfhoqsiudfh%5C%22%5D%20%22).unwrap()%0A%20%20%20%20)%3B%0A%7D%0A)
