### ISSUE TITLE
JSON keys and RFC 5646 (language tags)

### ISSUE THREAD

**Issue by bradleybeddoes** [serde-rs/serde#1057]
I was hoping someone may be able to point me in the direction of some documentation or example code for using Serde with JSON keys that have been formatted according to [RFC 5646](https://tools.ietf.org/html/rfc5646). Here is an example piece of JSON I expect to receive (this is set by a public specification so altering it isn't possible):

```
{
  "key", "value",
  ...
  "client_name": "My Example",
  "client_name#ja-Jpan-JP": "クライアント名",
}
```

What I'd like to be able to do is deserialise every `client_name#tag` pair into a vec of structs that has everything after the `#` stored as a tag and the value as, well, a value ;-).

This would take the following sort of format:

```
pub struct Client {
    pub key: String,
    ...
    pub client_names: Vec<ClientName>,
}

pub struct ClientName {
    /// Provides support for multiple languages and scripts.
    pub tag: Option<String>,

    /// The value of this name instance.
    pub value: String,
}
```

I've not been able to find anything about hacking about with keys in this manner during deserialization so any pointers would be fantastic.

**Comment by dtolnay** [comment]
Here is an outline to get you started. If you need this behavior across lots of different structs, you could factor it into a deserialize_with attribute that deserializes a Value, transforms it in the way that you want, and turns it into a generic type T that already implements Deserialize. Or you could even put together a procedural macro to generate the right Deserialize code directly.

```rust
use std::fmt;
use serde::de::{Deserialize, Deserializer, Visitor, MapAccess};

impl<'de> Deserialize<'de> for Client {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
        where D: Deserializer<'de>
    {
        struct ClientVisitor;

        impl<'de> Visitor<'de> for ClientVisitor {
            type Value = Client;

            fn expecting(&self, formatter: &mut fmt::Formatter) -> fmt::Result {
                formatter.write_str("struct Client with RFC 5646 language tags")
            }

            fn visit_map<M>(self, mut map: M) -> Result<Self::Value, M::Error>
                where M: MapAccess<'de>
            {
                /* local variables */

                while let Some(key) = map.next_key::<String>()? {
                    let value = map.next_value::<whatever>()?;

                    /* logic to parse keys */
                }

                /* check for missing fields */

                Ok(Client {
                    /* fields of the result */
                })
            }
        }

        deserializer.deserialize_map(ClientVisitor)
    }
}
```

**Comment by bradleybeddoes** [comment]
Thank you very much for the help @dtolnay.
