### ISSUE TITLE
Serde equivalent of python pickle?

### ISSUE THREAD

**Issue by ckaran** [serde-rs/serde#1064]
I'm very new to rust, so if I'm asking for something that cannot be implemented, please forgive me.

I'm currently trying to implement a simple event-based simulator.  The main event queue will be a minimum priority queue sorted by simulation time.  Events are objects that all implement my custom `Event` trait, which means that the queue is a heterogeneous collection of objects.  I want to be able to serialize and deserialize the queue so I can freeze a simulation at any time (makes it easy to take snapshots, and rerun simulations from shortly before anything interesting happens).  I can see how I can serialize the objects in the queue, but my issue is how do I deserialize them?  I don't have a complete list of event types, so I can't enumerate all of them, and there is no way I can tell what the type is when I try to deserialize them, so I'm at a loss as to what I'm supposed to do within rust/serde.  In python, I'd just [pickle/unpickle](https://docs.python.org/3/library/pickle.html) the objects, and know that the type information is correct, but how do I do that within Serde?

**Comment by hcpl** [comment]
@ckaran have a look at all possible data formats here: https://serde.rs/#data-formats. Among many available formats there is [pickle](https://crates.io/crates/serde-pickle) itself too!

If you need to implement yourself a `Deserializer` which can deserialize arbitrary data, you can use the [`deserialize_any`](https://docs.rs/serde/1.0.15/serde/trait.Deserializer.html#tymethod.deserialize_any) method from `Deserializer` trait.

**Comment by Marwes** [comment]
@hcpl Actually, that is not what @ckaran is asking for. @ckaran wants to serialize/deserialize *trait objects* which means that something like https://github.com/dtolnay/erased-serde needs to be used and probably in addition to https://github.com/chris-morgan/mopa.

@ckaran Deserializing and serializing trait objects can be rather complicated so if you are new to Rust I recommend you take another look at the event and see if they cannot be represented by `enum`s instead, in which case it would be easy to "pickle/unpickle". I actually need to serialize/deserialize traits myself for a project but I am afraid I haven't attempted to do it yet but maybe someone else has an example for you.

**Comment by ckaran** [comment]
@hcpl  I actually don't want to serialize to pickle, I want it's ability to determine the correct types at runtime.  Basically, when I deserialize to my priority queue, I want all the types to come back correctly as well.  Does that make sense? 

The only things that I currently see that may be headed in the right direction are [serialize_newtype_struct](https://docs.rs/serde/1.0.15/serde/trait.Serializer.html#tymethod.serialize_newtype_struct) and [deserialize_newtype_struct](https://docs.rs/serde/1.0.15/serde/trait.Deserializer.html#tymethod.deserialize_newtype_struct).  They appear to encode the type of the object into the serialized format.  The only problem is that I don't see how you go from a type name to an actual object of that type.

Like I said before, python's pickle does some magic under the hood; when you unpickle something, you get an object of the same type as what was pickled back.  You don't need to tell pickle about the type you were expecting.

**Comment by ckaran** [comment]
@Marwes I think you're right about trait objects, but I'm so new to rust that I'm afraid I may be using the wrong terminology.  But I'll look into the links you provided; thank you!
