### ISSUE TITLE
Advanced sources (ex:Bytes/Tendril)

### ISSUE THREAD

**Issue by arthurprs** [serde-rs/serde#1066]
I use the Bytes type extensively in a project due to its cheap clone/owned_slice semantics.
I was wondering if there's any way/plans to achieve something like the following in the future

```
struct S(a: Bytes, b: Bytes)

let source = Bytes::from(b"#123#456");
let d_s = BangDeserializer::deserialize_from::<Bytes>(source);
// here a and b fields share the source Bytes buffer
```

**Comment by dtolnay** [comment]
I don't know of plans to achieve something like that. Would you be interested in proposing an API that would handle this case?

**Comment by arthurprs** [comment]
I can't think of an api that could support this, other than making the entire stack aware of it (which is a non-started I guess). Hard stuff.

**Comment by dtolnay** [comment]
Closing because I don't plan to pursue deep integration of bytes/tendril through the entire stack, but I would be interested to see a prototype if someone figures out a less invasive way to support this better.
