### ISSUE TITLE
README instructions result in compile error

### ISSUE THREAD

**Issue by mpdehaan** [serde-rs/serde#1074]
I'm trying to compile an empty rust project (just a Cargo.toml and a main.rs that contains nothing more than the code in the README) and I'm getting a compile error.

llamaforge:mmdb michaeldehaan$ cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading serde v1.0.17
   Compiling serde v1.0.17
   Compiling mmdb v0.1.0 (file:///Users/michaeldehaan/Devel/mmdb)
error[E0463]: can't find crate for `serde_derive`
 --> src/main.rs:2:1
  |
2 | extern crate serde_derive;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error(s)

**Comment by hcpl** [comment]
You need to have this in Cargo.toml:
```toml
[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
```

I think this should be addressed in README, cc @dtolnay.
