### ISSUE TITLE
How to #[serde(rename = "type")] ?

### ISSUE THREAD

**Issue by Boscop** [serde-rs/serde#1076]
I want to (de)serialize messages with different content types, e.g.
`<Message><ARTSCommonHeader MessageType="Request"/><SystemTransaction ActionCode="Update"><DeviceTime>2017-10-11T12:53:00</DeviceTime></SystemTransaction></Message>`
and
`<Message><ARTSCommonHeader MessageType="Request"/><ItemTransaction ActionCode="ReadFirst"><Item/></ItemTransaction></Message>`

If I only wanted to use the first one, the message type would be:
```rust
#[derive(Default, Debug, Clone, PartialEq, Serialize)]
pub struct Message<'a, T> {
	#[serde(rename = "ARTSCommonHeader")]
	pub arts_common_header: ArtsCommonHeader<'a>,
	#[serde(rename = "SystemTransaction")]
	pub system_transaction: SystemTransaction<'a>,
}
```
And the others would be:
```rust
#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ArtsCommonHeader<'a> {
	#[serde(rename = "MessageType")]
	pub message_type: &'a str,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SystemTransaction<'a> {
	#[serde(rename = "DeviceTime")]
	pub device_time: &'a str,
	#[serde(rename = "ActionCode")]
	pub action_code: &'a str,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ItemTransaction<'a> {
	#[serde(rename = "Item")]
	pub item: &'a str,
	#[serde(rename = "ActionCode")]
	pub action_code: &'a str,
}
```

But I would like to use the same Message type for both (and many more), so I made the content generic:
```rust
#[derive(Default, Debug, Clone, PartialEq, Serialize)]
pub struct Message<'a, T> {
	#[serde(rename = "ARTSCommonHeader")]
	pub arts_common_header: ArtsCommonHeader<'a>,
	#[serde(rename = "what?")]
	pub content: T,
}
```

But now it won't be renamed to its type. Is there a way to make serde rename the field to the name of its type? 
(So if `T` is `SystemTransaction`, `content` will be renamed to `"SystemTransaction"`, and if `T` is `ItemTransaction`, it will be renamed to `"ItemTransaction"`.)
If not, could it be introduced with `#[serde(rename = "type")]` or something similar?

If not, which workaround would you recommend to achieve this?

**Comment by dtolnay** [comment]
Something like this could work. [[playground]](https://play.rust-lang.org/?gist=2132504802e6a0c4f42b41dcf0ada90f)

```rust
pub trait ContentName {
    const NAME: &'static str;
}

impl<'a> ContentName for SystemTransaction<'a> {
    const NAME: &'static str = "SystemTransaction";
}

impl<'a> ContentName for ItemTransaction<'a> {
    const NAME: &'static str = "ItemTransaction";
}

impl<'a, T> Serialize for Message<'a, T>
    where T: Serialize + ContentName
```

**Comment by Boscop** [comment]
Thanks, it works for my use case.
Can you please also give an example `Deserialize` impl for Message? :)

**Comment by dtolnay** [comment]
Deserialize impls are trickier to write but there is an example [here](https://serde.rs/deserialize-struct.html). Yours would look pretty similar except it would use T::NAME for one of the field names. Let me know if you get stuck and I can help you get it working.
