### ISSUE TITLE
Question about Zero-Copy Deserialization lifetime error

### ISSUE THREAD

**Issue by Boscop** [serde-rs/serde#1077]
Why am I getting this lifetime error?

![](https://image.prntscr.com/image/saBdvJ_lQCSELZwB5uXiYw.png)

Thanks!

**Comment by dtolnay** [comment]
Check out https://serde.rs/lifetimes.html and https://serde.rs/borrow.html.

**Comment by Boscop** [comment]
Thanks, I got it working for structs with `#[serde(borrow)]` but how can I make it work for enums?
```rust
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum Msg<'a> {
	#[serde(borrow)]
	System(SystemTransaction<'a>),
	#[serde(borrow)]
	Item(ItemTransaction<'a>),
}
```
```
error: proc-macro derive panicked
help: message: 2 errors:
	# unknown serde variant attribute `borrow`
	# unknown serde variant attribute `borrow`
```

**Comment by hcpl** [comment]
@Boscop this is a field attribute, not a variant one:
```rust
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum Msg<'a> {
	System(#[serde(borrow)] SystemTransaction<'a>),
	Item(#[serde(borrow)] ItemTransaction<'a>),
}
```

**Comment by dtolnay** [comment]
#929 tracks making it work for newtype variants. I would love a PR if anyone has time to implement it.
