### ISSUE TITLE
Security: is Serde safe when deserializing untrusted input?

### ISSUE THREAD

**Issue by DemiMarie** [serde-rs/serde#1087]
Is it safe to deserialize untrusted input using Serde?  Given, of course, that the subsequent code validates the fields of the deserialized objects.  That is, does Serde guarantee that for *any* input – including malicious input – there will either be a deserialization error, or the object will be a well-formed object of the correct type?

Also, is it possible to cause the deserialization process to produce an excessively large object, to panic, or to loop forever due to cycles?

**Comment by dtolnay** [comment]
Serde itself makes practically no guarantees about anything. Serde is a framework that other libraries use to implement data formats. By analogy, [Iron](http://ironframework.io) is a web framework -- an application built on Iron could decide to read untrusted network requests and execute them as a shell command, just like a data format built on Serde could decide to read untrusted bytes and execute them as a shell command.

Individual data formats may make stronger guarantees. For example serde_json does make the guarantee you quoted: "for *any* input – including malicious input – there will either be a deserialization error, or the object will be a well-formed object of the correct type."

Keep in mind that Deserialize impls are arbitrary Rust code in general. If you handwrite a Deserialize impl (i.e. not using serde_derive) in which you allocate a ton of memory and then loop forever, obviously we won't save you there.

**Comment by oli-obk** [comment]
Additionally you need to be careful when (de-)serializing private fields if the private field has invariants. These invariants can be trivially broken if not checked during deserialization.
