### ISSUE TITLE
Deriving Deserialize for a simple struct witha a reference

### ISSUE THREAD

**Issue by ferranpujolcamins** [serde-rs/serde#1092]
Hello, I tried to derive Deserialize implementations for two simple related structs:
```
#[macro_use]
extern crate serde_derive;

#[derive(Serialize, Deserialize, Debug)]
struct Entity<'a> {
	entity_type: &'a EntityType
}

#[derive(Serialize, Deserialize, Debug)]
struct EntityType {
	id: i32
}

fn main() {
    println!("Hello, world!");
}
```

I get this error:
```
error[E0277]: the trait bound `&'a EntityType: _IMPL_DESERIALIZE_FOR_Entity::_serde::Deserialize<'_>` is not satisfied
 --> main.rs:4:21
  |
4 | #[derive(Serialize, Deserialize, Debug)]
  |                     ^^^^^^^^^^^ the trait `_IMPL_DESERIALIZE_FOR_Entity::_serde::Deserialize<'_>` is not implemented for `&'a EntityType`
  |
  = help: the following implementations were found:
            <EntityType as _IMPL_DESERIALIZE_FOR_Entity::_serde::Deserialize<'de>>
  = note: required by `_IMPL_DESERIALIZE_FOR_Entity::_serde::de::SeqAccess::next_element`

```

AFAIK, EntityType could well implement Deserialize<'_> because it won't borrow any data, since it holds no reference, just an integer. I've read [Borrowing data](https://serde.rs/borrow.html) but I don't see it has anything to do here since EntityType borrows no data.

On the other hand I don't see why EntityType can't just implement Deserialize<'de>. As long as EntityType outlives Entity ('a lifetime) everything should be fine. I've read [Handwritten generic type bounds](https://serde.rs/attr-bound.html) but I don't see how it would fit here, since I have no type parameters.

Is something I'm doing wrong or I did not understand correctly? Do I need to implement Deserialize trait for some of the structs?
I'm a Rust  newbie. Lifetimes is something I'm still learning and I would highly appreciate some guidance of what's wrong / what I need to do / what I need to read.

**Comment by dtolnay** [comment]
Check out [What is Ownership](https://doc.rust-lang.org/book/second-edition/ch04-01-what-is-ownership.html) and [References & Borrowing](https://doc.rust-lang.org/book/second-edition/ch04-02-references-and-borrowing.html) if you haven't mastered those yet.

I think you will see what is going wrong if you try to fill in the body of this function with what you think Serde should be doing to deserialize an entity.

```rust
#[derive(Debug)]
struct Entity<'a> {
    entity_type: &'a EntityType,
}

#[derive(Debug)]
struct EntityType {
    id: i32,
}

fn deserialize_entity<'a>(id: i32) -> Entity<'a> {
    /* what could Serde possibly write here? fill in the implementation */
}

fn main() {
    let entity = deserialize_entity(100);
    // expected: entity with id=100
    println!("{:?}", entity);
}
```

**Comment by ferranpujolcamins** [comment]
Ok I think I've got what's wrong! Also, I extended the example to show what was confusing me:
```
#[derive(Debug)]
struct Entity<'a> {
    /* A: Why I CAN'T do this?... */
    entity_type: &'a EntityType,
}

#[derive(Debug)]
struct EntityType {
    id: i32,
}

#[derive(Debug)]
struct Title<'a> {
    /* B: ...While I CAN do this? */
    title: &'a str
}

/*
fn deserialize_entity<'a>(id: i32) -> Entity<'a> {
    // Who's going to take ownership of this EntityType?
    let entityType = EntityType {id: id};
    
    let entity = Entity {entity_type: &entityType};
    return entity;
}
* */

fn deserialize_title<'a>(title: &'a str) -> Title<'a> {
    return Title {title: title};
}

fn main() {
    /*
    let entity = deserialize_entity(100);
    expected: entity with id=100
    println!("{:?}", entity);
    */
    
    let title = deserialize_title("Today I learnt something.");
    println!("{:?}", title);
}

```

Questions A and B were confusing me.
The answer to A is: nobody can own the EntityType created on the deserialize method.
But then, why I can do B? Because title &str is owned by the deserializer.

Thank you very much.
