### ISSUE TITLE
proc-macro derive panics if lifetime is written before the trait

### ISSUE THREAD

**Issue by jonasbb** [serde-rs/serde#1099]
I could trigger the following error message:

```text
error: proc-macro derive panicked
 --> src/bin/serde-test.rs:7:10
  |
7 | #[derive(Serialize)]
  |          ^^^^^^^^^
  |
  = help: message: called `Result::unwrap()` on an `Err` value: "failed to parse derive input: \"struct Test<\\\'a, F> where F: Fn() -> Box< \\\'a + Iterator<Item = usize>> {\\n    __data: PhantomData<F>,\\n}\""

error: Could not compile `genetic_resolver_finding`.
```

This code panics:
```rust
#[derive(Serialize)]
struct Test<'a, F>
where
    F: Fn() -> Box<'a + Iterator<Item = usize>>,
{
    __data: PhantomData<F>,
}
```

while this one doesn't
```rust
#[derive(Serialize)]
struct Test<'a, F>
where
    F: Fn() -> Box<Iterator<Item = usize> + 'a>,
{
    __data: PhantomData<F>,
}
```

Notice how in the first case the lifetime is written before the trait but in the second case it is not.

I use serde_derive in version 1.0.21.
rustc 1.23.0-nightly (45594d5de 2017-11-22)
cargo 0.24.0-nightly (abd137ad1 2017-11-12)

However, both variants compile without problem, if the derive is commented out.

**Comment by dtolnay** [comment]
Thanks for reporting this! The syntax with lifetime before trait was not allowed before July 2017, and the parser we are using in serde_derive is from April 2017. I filed https://github.com/dtolnay/syn/issues/259 to fix it. For now stick to writing the lifetime after the trait.
