### ISSUE TITLE
Make enum variants generic

### ISSUE THREAD

**Issue by dswd** [serde-rs/serde#110]
The current implementation forces serializers to represent enum variants as strings. However the deserializer API already uses generic types for enum variants.
I am working on a msgpack backend for serde which should represent enum variants as numbers rather than strings.
I tried to do the changes on my own and create a pull request but I got stuck as the assumption that enum variants are strings is all over the code, especially the json part and the codegen part.
You can see my approach at https://github.com/dswd/serde/tree/patch-2

**Comment by erickt** [comment]
I've also got a patch I'm working on that adds support for this that I'm hoping to land pretty soon.

**Comment by dswd** [comment]
Oh that is great news cause I got stuck implementing it. Strings seem the right choice for human readable formats bit numbers make much more sense for all binary formats.

**Comment by dswd** [comment]
On second thought, maybe generic enum keys is too much. Maybe all methods should just accept both strings and numbers. I can't think of any other useful type for enum keys.
