### ISSUE TITLE
Deserialization of seperated sequences

### ISSUE THREAD

**Issue by Binero** [serde-rs/serde#1113]
In some formats, it's common for a sequence to be interrupted. Take for example the following XML:

```xml
<interface>
    <request>sync</request>
    <request>get_registry</request>
    <event>error</event>
    <enum name="error">
        <entry name="invalid_object"/>
        <entry name="invalid_method"/>
        <entry name="no_memory"/>
    </enum>
    <event>delete_id</event>
</interface>
```

The structure that most closely resembles this is:

```rust
#[derive(Debug, Deserialize)]
struct Interface {
    #[serde(rename = "request")] request: Vec<Request>,
    #[serde(rename = "event")] events: Vec<Event>,
    #[serde(rename = "enum")] enums: Vec<Enum>,
}
```

This is impossible for serde to parse though. Serde expects all array elements to be given in a sequence. (After all, `Vistitor::visit_seq` expects an iterator.)

**Is there a way around this? Will this be fixed in serde or is it considered to be an edge-case that doesn't need to be supported?**

**Comment by Binero** [comment]
I determined the error occurs [here](https://github.com/serde-rs/serde/blob/0c34e06e518c81315ec738584db0cffba6f5677a/serde_derive/src/de.rs#L1605). There should be an option for types like `Vec` to allow taking additional values.

What would be the best way to design this? Maybe add a new function to `Deserialize`? 

```rust
fn combine(self, new_values: Self) -> Self;
```

**Comment by Binero** [comment]
Whoops, pressed the wrong button there.

**Comment by dtolnay** [comment]
I believe this is already supported by Serde. The toml crate has no trouble supporting interleaved sequences ([playground](https://play.rust-lang.org/?gist=a0577482845602c9a154f631876d1ef7)). Please file an issue against the xml crate you are using and they may be able to improve how they handle this case. Thanks!

**Comment by Binero** [comment]
@dtolnay I am having some trouble figuring out how exactly the TOML parser works, but it appears it works around the problem by first [parsing the entire file into](https://github.com/alexcrichton/toml-rs/blob/master/src/de.rs#L184) a DOM-like structure. That would also confirm why it doesn't allow to parse a stream of data, but only complete strings.

**Comment by Binero** [comment]
I made a commit to prove that in fact this case is not handled by serde. 

https://github.com/Binero/serde/commit/9055a0399b59a00c99dd23d63d60b1e764f3d9d6

**Comment by dtolnay** [comment]
It is up to the format whether to buffer and/or read ahead to combine separated sequences of the same field. The toml format does this because that is what makes sense in toml. The serde_test crate does not. JSON also does not, because implicitly handling `{"a":[0,1],"b":2,"a":[3,4]}` as a concatenated array is not typically how JSON works (though a custom Deserialize impl can handle it that way if it wants).
