### ISSUE TITLE
Make it possible to "de-cautious" heap-allocated container sizes

### ISSUE THREAD

**Issue by khuey** [serde-rs/serde#1114]
Serde passes sizes of of arrays and other heap-allocated containers through `size_hint::cautious` before deciding how much to allocate via `with_capacity`.  This presumably exists to prevent denial of service attacks.  Some `Deserializer` implementations already have their own DOS mitigations (e.g. bincode), and some inputs are trusted.  In those cases `size_hint::cautious` ends up forcing unnecessary reallocs.

I propose to add the following to `Deserializer` to replace `size_hint::cautious`.

```rust
#[inline]
fn limit_alloc<T: Sized>(&self, size_hint: Option<usize>) -> usize {
    cmp::min(hint.unwrap_or(0), 4096)
}
```

Then `Deserializer` implementations can choose to override it if desired.  e.g. bincode could choose to limit the alloc size for `Bounded` `SizeLimit`s but not `Infinite` ones.  One slightly tricky thing here is that bincode limits the number of bytes deserialized from the source, not the number allocated, and the number allocated may be larger than the number deserialized.  That means it can't just do `cmp::min(S::limit(), hint.unwrap_or(4096) * sizeof(T))` to calculate a `limit_alloc`.  On the other hand, allocated (but not yet filled) container space isn't counted against bincode's limits at all today.

Thoughts?

Cc @TyOverby

**Comment by dtolnay** [comment]
The size hint capping is performed by the Deserialize impls we provide for standard library types. For use cases in which the realloc is a bottleneck, I would prefer that those fields use `serde(deserialize_with = "...")` to replace our provided Deserialize impl with one that does not cap the size hint -- I don't think it is necessary to control this with a new Deserializer method. Thanks anyway for the idea!

**Comment by khuey** [comment]
Deciding whether to cap the size hint when deserializing variable length data seems like a function of the provenance of the data to be deserialized (and whether the deserializer has other mitigations in place), not of the structure of the data itself though.

**Comment by rocallahan** [comment]
Not only does this cause unnecessary reallocations, it's causing us to waste gigabytes of memory :-(.
