### ISSUE TITLE
Bincode support

### ISSUE THREAD

**Issue by erickt** [serde-rs/serde#112]
[bincode](https://github.com/TyOverby/bincode) is a lightweight serialization format that's built on rustc-serialize. I've got it mostly ported over, so this is more of a notice in case anyone else was planning on working on it.

**Comment by pcwalton** [comment]
@erickt Ping. I think the infrastructural work for this landed? Do you have an ETA on when this will be merged?

**Comment by erickt** [comment]
This has landed in bincode!
