### ISSUE TITLE
More efficient try!() alternative

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#1121]
Our generated code uses the standard `try!` macro heavily. 

```rust
match $expr {
    Ok(val) => val,
    Err(err) => {
        return Err(From::from(err))
    }
}
```

I think practically none of our uses of `try!` rely on the From::from conversion (i.e. it resolves to the `impl From<T> for T`). Let's experiment with generating code that omits the conversion and see whether that improves the compile times of the generated code.

**Comment by oli-obk** [comment]
Do you want a(n allow-by-default) lint for that?

**Comment by dtolnay** [comment]
Thanks! Let's wait until we find out that this helps compile time measurably.

(Or do you mean as a way to help me find all the `try!` that need to be changed? I'm not worried about that, I can just replace them all and then change back the few that fail to compile.)

**Comment by oli-obk** [comment]
I meant more to not regress in the future

**Comment by dtolnay** [comment]
Testing against our [json-benchmark](https://github.com/serde-rs/json-benchmark) with `--bin json-benchmark --no-default-features --features parse-struct,all-files,lib-serde` it looks like the more efficient try!() results in 15% faster "item-bodies checking", 25% faster "borrow checking", 2% faster debug compile overall, 0.6% smaller debug binary, and 0.2% small release binary.
