### ISSUE TITLE
Is deserialize_from really more like into

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#1122]
Insightful comment from @nox in #servo:

> **\<nox>** Yeah but I’m curious about the name.
> **\<nox>** The idea I heard was more like deserialize_into than deserialize_from.

**Comment by dtolnay** [comment]
The naming is meant to align with the relatively obscure Clone::clone_from --

```rust
trait Clone {
    fn clone(&self) -> Self;
    fn clone_from(&mut self, source: &Self);
}
```

```rust
trait Deserialize<'de> {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>;
    fn deserialize_from<D>(&mut self, deserializer: D) -> Result<(), D::Error>;
}
```

These follow a pretty similar pattern. The non-`from` method takes 1 argument which is the source of data. The `from` method takes 2, a &mut destination and a source of data.

That said, I do think the `_from` naming seems to work better for Clone.

```rust
let mut x = v1.clone();
x.clone_from(&v2);

// They both clearly deserialize "from" the one argument. Neither
// seems any more "from" than the other.
let mut x = T::deserialize(de1)?;
x.deserialize_from(de2)?;
```

**Comment by nox** [comment]
My original idea for this feature was:

```rust
trait Deserialize<'de> {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>;
    fn deserialize_into<D>(dest: &mut Self, deserializer: D) -> Result<(), D::Error>;
}
```

**Comment by Gankro** [comment]
I agree deserialize_from is a bad name. deserialize_into might be better? I have also considered "redeserialize" as a possible thing.

**Comment by dtolnay** [comment]
Transcribing a discussion from IRC: I think `clone_from` is not necessarily named correctly and is not a great model to name `deserialize_from` after unless we have other compelling reasons.

I find it easier to see that `clone_from` is wrong when written in Swift argument label syntax, but I believe the same conclusion applies to Rust naming.

```swift
// Clones x.
x.clone()

// Clones v, not x. You would not want this method to be called x.clone.
x.clone(from: v)
```

In comparison:

```swift
// Both of these clone x.
// The destination is different (return value vs existing value).
x.clone()
x.clone(into: v)
```

**Comment by dtolnay** [comment]
I believe these are the constraints:

- For technical reasons, given that we don't want specialization involved, this functionality must be provided by a method on the Deserialize trait.
- The method must take one argument of type `D: Deserializer<'de>`.
- The method must take one argument of type `&mut Self`, which may be the receiver.
- The two arguments may be in either order.
- The method must be a public API so that data types can provide more efficient implementations.

That is not a lot of flexibility. However I realized that we don't necessarily need this method to be the main way that this functionality is exposed, except to data types. We could keep the method on Deserialize hidden and expose it through a different trait. Something like this is possible, if not the best design:

```rust
trait DeserializeInto<'de>: Deserializer<'de> {
    fn deserialize_into<T>(self, into: &mut T) -> Result<(), Self::Error>
        where T: Deserialize<'de>
    {
        Deserialize::deserialize_from(into, self)
    }
}

impl<'de, D> DeserializeInto<'de> for D where D: Deserializer<'de> {}
```

```rust
let mut i = 0i32;
let mut de = serde_json::Deserializer::from_str("2");

// Pretty clear code.
de.deserialize_into(&mut i)?;

println!("{}", i);
```

**Comment by Gankro** [comment]
Oh sorry forgot to follow up: I tried to ask some of the libs team members about it this week at the mozilla all hands and like basically no one cares. So no need to try to mirror clone_from.

Not sure why DeserializeInto: Deserializer is desirable?

**Comment by dtolnay** [comment]
- If the method on Deserialize has a receiver, then it must behave like `deserialize_from` which we were not happy with.

    ```rust
    v.deserialize_from(&mut de)?;
    ```

    This may still be the best choice with the right name. I think your idea of `redeserialize` is in the right direction.

- If the method on Deserialize does not have a receiver, then it takes two arguments and the argument order is arbitrary which is a shame. It also necessitates stating the type redundantly or using `Deserialize::` or `<_>::`.

    ```rust
    i32::deserialize_into(&mut de, &mut v)?;
    i32::deserialize_into(&mut v, &mut de)?;
    Deserialize::deserialize_into(&mut de, &mut v)?;
    <_>::deserialize_into(&mut de, &mut v)?;
    ```

- An extension trait addresses all of those things.

    ```rust
    de.deserialize_into(&mut v)?;
    ```

**Comment by dtolnay** [comment]
Another possibility: have a DeserializeSeed be the primary API for this.

```rust
InPlace(&mut v).deserialize(&mut de)?;
```

**Comment by Gankro** [comment]
There ultimately needs to be a method on Deserialize for this. As such I would suggest redeserialize with no other frills. It also better explains why you’d use it.

**Comment by dtolnay** [comment]
I like `redeserialize` better than `deserialize_from` but I find it a bit misleading -- to me "redeserialize" would mean same data -> different object. For example you might "deserialize" some JSON to `serde_json::Value` and then "redeserialize" all or part of that Value to some struct. Instead the method we have here is different data -> same object.

**Comment by dtolnay** [comment]
What do people think of `fn deserialize_in_place<D>(deserializer: D, place: &mut Self)`? Too much conflict with [placement-in](https://github.com/rust-lang/rust/issues/27779) and [`std::ops::InPlace`](https://doc.rust-lang.org/std/ops/trait.InPlace.html)? Or just similar enough in principle that it makes sense?

**Comment by hcpl** [comment]
`fn deserialize_assign<D>(&mut self, deserializer: D)` may also make sense as a binary operation that modifies one of its arguments in-place, mirroring `OpAssign` family of traits in `std::ops`.
