### ISSUE TITLE
Allow Duration on libcore once it's stable

### ISSUE THREAD

**Issue by clarcharr** [serde-rs/serde#1123]
There's currently an accepted issue (rust-lang/rust#46520) to move the `std::time::Duration` type to `core::time::Duration`. Once this is stable, there should be a change to `serde/src/lib.rs` to change the import of `Duration` so that it's allowed on `no_std` builds.

**Comment by dtolnay** [comment]
Tagging breaking change because this would involve raising the minimum supported Rust version.
