### ISSUE TITLE
Borrowed value with IoRead

### ISSUE THREAD

**Issue by antoyo** [serde-rs/serde#1126]
Hello.
I stumbled on the issue #906, but using an `IoRead` instead of a `String`:
```rust
#[macro_use]
extern crate serde_derive;

extern crate serde;
extern crate serde_json;

use std::fs::File;

use serde::Deserialize;
use serde_json::Deserializer;
use serde_json::de::IoRead;

#[derive(Deserialize, Debug)]
#[serde(tag = "type")]
pub enum Input<'a> {
    Package { name: &'a str },
}

fn main() {
    let j = include_str!("../file.json");
    println!("{:?}", serde_json::from_str::<Input>(j).unwrap());

    let filename = "file.json";
    let reader = File::open(filename).unwrap();
    let mut deserializer = Deserializer::new(IoRead::new(reader));
    let _strct: Input = Deserialize::deserialize(&mut deserializer).unwrap();
}
```
I get the following error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorImpl { code: Message("invalid type: string \"\", expected a borrowed string"), line: 0, column: 0
```
Is it the normal behaviour because we don't have the `String` but we have a `File` instead?
Or would it be possible to tie the lifetime of the content of the file to the one in the struct?
Thanks for your help.

**Comment by dtolnay** [comment]
This is expected because it isn't possible to borrow data from an io stream. You can tell because [`std::io::Read`](https://doc.rust-lang.org/std/io/trait.Read.html) has no zero-copy methods. Everything it does involves copying bytes into a buffer provided by the caller. This is also why [`serde_json::from_reader`](https://docs.serde.rs/serde_json/fn.from_reader.html) requires a bound of `T: DeserializeOwned`.

**Comment by antoyo** [comment]
Ok, thank you.

**Comment by townsen** [comment]
@dtolnay I'm getting this trying to deserialize from a file using the `serde_json::from_reader` method with the following custom deserializer (that converts a string to a u32):
``` rust
fn u32_from_str<'de, D>(deserializer: D) -> Result<u32, D::Error>
where
    D: Deserializer<'de>,
{
    let s: &str = Deserialize::deserialize(deserializer)?;
    u32::from_str_radix(&s, 10).map_err(D::Error::custom)
}
```
This code works fine when I'm deserializing from a String using `serde_json::from_str`. Also it works fine deserializing from a file (using `from_reader`) when I remove the custom field that is using `#[serde(deserialize_with = "u32_from_str")]`.

So clearly deserializing from a File is possible. I need to deserialize extremely large JSON objects and don't want to have to copy the whole thing into memory first.

Is this a bug?

**Comment by bbqsrc** [comment]
This seems to be causing this issue: https://github.com/rust-analyzer/smol_str/issues/14

@dtolnay, any suggestions?
