### ISSUE TITLE
Can serde be used on stable rust (1.1.0)?

### ISSUE THREAD

**Issue by jimtla** [serde-rs/serde#113]
I can't find any documentation on which versions of rust serde targets, and it currently seems to be broken on stable 1.1.0. Simply `use serde::json` results in:

```
~/.cargo/registry/src/github.com-1ecc6299db9ec823/quasi-0.3.1/src/lib.rs:11:43: 11:66 error: unstable feature
~/.cargo/registry/src/github.com-1ecc6299db9ec823/quasi-0.3.1/src/lib.rs:11 #![cfg_attr(not(feature = "with-syntex"), feature(rustc_private))]
```

If you can point me in the right direction on how to use serde with stable I'd be happy to write up the docs and contribute them back here.

**Comment by erickt** [comment]
It can! Check out this [blog post]http://erickt.github.io/blog/2015/05/18/serde-0-dot-4-0-now-supports-macros-in-stable-rust/) that goes into details on how to do it.

**Comment by erickt** [comment]
Added some docs for this to the readme too.
