### ISSUE TITLE
Question: merging multiple (2) fields into one during deserialization

### ISSUE THREAD

**Issue by idubrov** [serde-rs/serde#1134]
I need some guidance & advices to solve the following problem I am facing.

Basically, I have a need to "transcode" between two formats.

In one format, certain fields are represented by composite values, like this:
```
...
<url value="http://example.com">
  <extension>
    <valueString value="extvalue"/>
   </extension>
</url>
...
```

For that, I have generated "struct"s, which look like the following:
```
#[derive(Deserialize)]
struct Data {
...
  pub url: CompositeValue, // CompositeValue has fields "value": String and "extension": Vec<Extension>
...
}
```

No controversy so far, everything works smoothly.

Now, in JSON, designers of the format I need to parse (and, potentially, serialize), decided that using something like `{"value": "http://example.com", "extension": [...]}` would be too long (most of the time the whole <extension> thing is missing. So, instead, they represent that data in JSON as following:
```
...
  "value": "http://example.com",
  "_value": [{
    "valueString": "extvalue"
  }]
...
```

Note that if extension is missing, those fields will be encoded as primitive JSON values -- which is nice and short.

What I'm currently struggling with is that I want to have same set of types used for both XML and JSON. It looks to me that if I somehow transcode the original format from "fieldX": "primitive value" + "_fieldX": [...extensions...] into "fieldX": {"value": "primitive value", extensions: [...extensions...]}, the remaining deserialization will work as expected.

Any advices where would be the best way to "plug in"?

I certainly want to avoid writing custom deserializers for my structs: there are a lot of them. Also, I don't want to have two copies: one for XML and another for JSON. 

Currently I'm trying to create a wrapper type `Transcoder`, which will wrap my types and do necessary transformations. However, it looks like a suboptimal solution:

1) transcoding will only happen in context of my struct types -- converting from XML to JSON (and other way around) would not be possible without going through those structs.
2) so I wrapped my types with `Transcoder` type, then I had to wrap `de::Visitor` with `TranscoderVisitor` and it looks that I will need to wrap `de::MapAccess` also! Too much work!

On the other hand, wrapping JSON `serde_json::de::Deserializer` to do that is tricky: it is designed for "streaming" data through it, to do that kind of transcoding I will have to collect all the intermediate data, which is not great.

It looks to me that the best place would be to do that in the derived implementation of Deserialize for structs: it already collects all of the data in the fields, so it should be matter of having "virtual" fields to collect extensions + code to combine value itself with list of extensions to get `CompositeValue` for the field. However, the "derive" algorithm is not extensible (and it also not clear how to distinguish XML vs JSON, plus #1 issue is still there)...

**Comment by idubrov** [comment]
For the context, this is the summary on representation of primitive elements which I try to implement: https://www.hl7.org/fhir/json.html#primitive

**Comment by dtolnay** [comment]
I would recommend preprocessing the JSON object recursively to convert all pairs of keys of the form `"value"` + `"_value"` into the form expected by your CompositeValue, with nested keys `"value"` and `"extension"`. [**Playground**](https://play.rust-lang.org/?gist=6c9d29ec854ea916e7c8c987f3cb7d62)

This approach avoids all the code involved in wrapping a `Deserializer`, `Visitor`, `MapAccess`, etc.

```rust
#[macro_use]
extern crate serde_derive;
#[macro_use]
extern crate serde_json;
extern crate serde;

use std::collections::BTreeMap as Map;
use serde::de::DeserializeOwned;
use serde_json::Value;

#[derive(Deserialize, Debug)]
struct Data {
    url: CompositeValue,
}

#[derive(Deserialize, Debug)]
struct CompositeValue {
    value: String,
    extension: Vec<Extension>,
}

type Extension = Map<String, String>;

fn preprocess_object(j: &mut Value) {
    let object = match j.as_object_mut() {
        Some(object) => object,
        None => return,
    };

    // Recurse on all map entries.
    for (_, v) in &mut *object {
        preprocess_object(v);
    }

    // Find pairs of keys of the form `"value"` + `"_value"`.
    let mut extended = Vec::new();
    for k in object.keys() {
        if k.starts_with('_') && object.contains_key(&k[1..]) {
            extended.push(k.clone());
        }
    }

    // Combine into nested object with keys "value" and "extension".
    for mut k in extended {
        let value = object.remove(&k[1..]).unwrap();
        let extension = object.remove(&k);
        k.remove(0); // remove underscore
        object.insert(k, json!({ "value": value, "extension": extension }));
    }
}

fn from_extended_json<T>(j: &str) -> Result<T, serde_json::Error>
    where T: DeserializeOwned
{
    let mut v: Value = serde_json::from_str(j)?;
    preprocess_object(&mut v);
    serde_json::from_value(v)
}

fn main() {
    let j = r#"
      {
        "url": "http://example.com",
        "_url": [{
          "valueString": "extvalue"
        }]
      }"#;

    let data: Data = from_extended_json(j).unwrap();
    println!("{:#?}", data);
}
```
