### ISSUE TITLE
Is that possible to create a format that compact two enums into one byte?

### ISSUE THREAD

**Issue by Xtricman** [serde-rs/serde#1141]
When implementing `Serializer` , methods are called by each field in the data model. Is that possible to get the number of cases of an unit_variant field so that this field can be serialized as less than 8-bit? If that can can be done, a 128-cases unit_variant field followed by another can be serialized using just 1 byte.

I know this can be achieved by mapping two such enums into one `u8` in the data model by manually implementing `Serialize` but that would need  work for every such type, so maybe the better solution should be done on `Serializer` side.

**Comment by dtolnay** [comment]
Yes it is possible! The number of variants is not exposed to the Serializer but you can use any variable-width encoding to pack a small variant index into fewer than 8 bits. Then your Serializer can keep track of the number of unoccupied bits in the most recently written byte and can pack subsequent fields into those bits.

That said, if you are doing this to optimize for size of the serialized data then I expect you will see better results from using a real compression algorithm applied to the entire serialized data. And if you are running things through a real compression algorithm anyway then packing bits yourself tends to be a waste of time.

**Comment by Xtricman** [comment]
@dtolnay I don't want variable-length encoding to encode the index. The variant index still needs to be fix-length encoded and I'm not doing optimizing for size of the serialized data. Since the number of variants is not exposed to `Serializer`, I think this might be a case serde is not proper library for me.
