### ISSUE TITLE
Serialize newtype structs as just their .0 field

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#1143]
Question by email:

---

I am trying to implement some sort of primative types. so I have some object like so:

```rust
pub struct Foo {
    a: u8,
    b: SomePrimative,
}
```

where as SomePrimative I define like so:

```rust
pub struct SomePrimative(pub string);
```

Now I am writting parser that decodes a JSON representation of Foo:

```rust
json::from_value::<Foo>(obj)
```

It seems serde will always decode b as [value] and not value.

To remedy this I have written my own serializer but this becomes a choir as I would have to write a serializer for every type.

I was wodnering if serde had some way to force certain empty structs to always return the .0 repr of it?

**Comment by dtolnay** [comment]
Can you help me reproduce this? I tried the types you said and it serializes the way it sounds like you wanted. The following code prints field `b` as `"s"` not `["s"]`.

```rust
#[macro_use]
extern crate serde_derive;

extern crate serde;
extern crate serde_json;

#[derive(Serialize)]
struct Foo {
    a: u8,
    b: SomePrimitive,
}

#[derive(Serialize)]
struct SomePrimitive(String);

fn main() {
    let foo = Foo { a: 0, b: SomePrimitive("s".to_owned()) };
    println!("{}", serde_json::to_string_pretty(&foo).unwrap());
}
```

```json
{
  "a": 0,
  "b": "s"
}
```

**Comment by dtolnay** [comment]
`serde_json::from_value::<Foo>(obj)` seems like it works too:

```rust
#[macro_use]
extern crate serde_derive;

#[macro_use]
extern crate serde_json;

extern crate serde;

#[derive(Deserialize, Debug)]
struct Foo {
    a: u8,
    b: SomePrimitive,
}

#[derive(Deserialize, Debug)]
struct SomePrimitive(String);

fn main() {
    let obj = json!({ "a": 0, "b": "s" });
    let foo = serde_json::from_value::<Foo>(obj).unwrap();
    println!("{:?}", foo);
}
```

**Comment by justmike2000** [comment]
I believe my issue is with msg_pack serde actually.  Here is some code below:

**Comment by justmike2000** [comment]
#[macro_use]
extern crate serde_derive;
extern crate serde;
extern crate serde_json;
extern crate serde_bytes;

pub extern crate rmp as msgpack;
pub extern crate rmp_serde as msgpack_serde;

use std::convert::From;
use serde::{Serialize};

use std::io;

#[derive(Debug)]
pub enum SomeError {
    IoError(io::Error),
    ParseError(serde_json::Error),
    DecodeHeaderError(serde_json::Error),
    EncodeError(msgpack_serde::encode::Error),
}

impl From<msgpack_serde::encode::Error> for SomeError {
    fn from(err: msgpack_serde::encode::Error) -> SomeError {
        SomeError::EncodeError(err)
    }
}

#[derive(Debug, PartialEq, Serialize, Deserialize)]
struct Foo {
    a: u8,
    b: SomePrimitive,
}

#[derive(Debug, Clone, Serialize)]
struct SomeMessage<T: ?Sized + Serialize> {
    event: T,
}

#[derive(Debug, PartialEq, Clone, Serialize, Deserialize)]
struct SomePrimitive(pub String);


impl<T: ?Sized + Serialize> SomeMessage<T> {

    fn encode_event(&self) -> Result<Vec<u8>, SomeError> {
        let mut buf: Vec<u8> = Vec::new();
        self.serialize(&mut msgpack_serde::Serializer::new(&mut buf))?;
        Ok(buf)
    }
}

fn main() {

    let line = "{\"a\": 2, \"b\": \"Test\"}";

    let obj: serde_json::Value = serde_json::from_str(&line).unwrap();
    serde_json::from_value::<Foo>(obj).map(|e| {
       println!("{:?}", e);
       SomeMessage {
           event: e
       }
    }).and_then(|msg| {
        println!("{:?}", msg);
        let mut buf = Vec::new();
        msg.serialize(&mut msgpack_serde::Serializer::new(&mut buf)).unwrap();
        println!("{:?}", buf);
        Ok(buf)
    });
}

**Comment by justmike2000** [comment]
Outputs: Foo { a: 2, b: SomePrimitive("Test") }
SomeMessage { event: Foo { a: 2, b: SomePrimitive("Test") } }
[145, 146, 2, 145, 164, 84, 101, 115, 116]

**Comment by justmike2000** [comment]
[145, 146, 2, 145, 164, 84, 101, 115, 116] unpacked is: 

[
  [
    2,
    [
      "Test"
    ]
  ]
]

**Comment by justmike2000** [comment]
[[2,["Test"]]] when I really want [[2,"Test"]]

**Comment by justmike2000** [comment]
However writting custom serializes like so seemed to help:

`
668 impl Deref for SomePrimative {
669     type Target = String;
670 
671     fn deref(&self) -> &String {
672         let &SomePrimative(ref value) = self;
673         value
674     }
675 }
676 
677 impl Serialize for SomePrimative {
678     fn serialize<S>(&self, serializer: S) -> std::result::Result<<S as Serializer>::Ok, <S as Serializer>::Error>
679         where S: Serializer
680     {
681         serializer.serialize_str(&self.to_string())
682     }
683 }
`

**Comment by dtolnay** [comment]
I believe the messagepack folks are tracking this in https://github.com/3Hren/msgpack-rust/issues/129. They have a fix in master already but it has not been released yet.

```toml
[dependencies]
rmp-serde = { git = "https://github.com/3Hren/msgpack-rust" }
```

Output of the same program but using rmp-serde master branch:

```diff
  Foo { a: 2, b: SomePrimitive("Test") }
  SomeMessage { event: Foo { a: 2, b: SomePrimitive("Test") } }
- [145, 146, 2, 145, 164, 84, 101, 115, 116]
+ [145, 146, 2, 164, 84, 101, 115, 116]
```

**Comment by justmike2000** [comment]
Thanks for the help, I have verified this is fixed in msgpack-rust master.

**Comment by dtolnay** [comment]
Great! This may be a good time to check with them when they plan to publish the next release.
