### ISSUE TITLE
Best practices for manually implementing (de)serialization

### ISSUE THREAD

**Issue by stbuehler** [serde-rs/serde#1150]
I have some custom types in my crate and was asked to provide `Serialize` and `Deserialize`.

I didn't want to pull in `serde-derive`, but I also didn't want to use it: my structs have private members, and deriving `Serialize` and `Deserialize` would make that part of a public API.

I managed to implement something similar to what `serde-derive` would have done, but in a way that would stay independent of my actual types.

I.e. I used newtype wrappers, variant wrappers, struct fields with names, ... - quite heavy.  Given that a format can skip most of the information a compact representation should still be possible.

But the original requester asked me to optimize the representation.  And I'm not against it, especially as it simplifies my code a lot :)

So, are there any best practices what should be done when implementing `Serialize` and `Deserialize`?

(For reference: https://github.com/stbuehler/rust-cidr/issues/2)

**Comment by dtolnay** [comment]
The best practice for representing compound data types is do what serde_derive would do. I think you got it right the first time -- that approach is consistent with how the standard library IpAddr and SocketAddr are handled. Hilariously, as you pointed out, your representation is substantially more compact than what the commenter was pushing for that they imagined would be more compact.

In any case, it doesn't matter for two reasons:

- The non-human-readable representation is not intended to be human readable. As long as all the information is represented and there is no useless information represented, there are lots of possible choices that are effectively equivalent.

- If a user is optimizing for compactness, they should be applying some compression algorithm to the serialized bytes anyway which makes it irrelevant whether the implementation does any intelligent packing of bits.

**Comment by stbuehler** [comment]
(I forgot to mention above that this is about the non-human-readable representation.  If I'd be using structs for the human-readable part I'd use the same for non-human-readable - but in this case I'm using `Display` and `FromStr` for human readable.)

Does it matter whether I'm using newtype wrappers?  Do some formats actually benefit from it?

**Comment by dtolnay** [comment]
Can you clarify what you mean by newtype wrappers and what alternative you are considering? I did not notice `serialize_newtype` in https://github.com/stbuehler/rust-cidr/commit/2554e66b0cce063c360a8dcbdcf22ea82cc31e71.

**Comment by stbuehler** [comment]
I used `serialize_struct` (which takes a name and imho acts similar to `newtype`) and `serialize_newtype_variant`.  The second variant https://github.com/stbuehler/rust-cidr/commit/626a808cbdf65515411c3a84c3964e3faefc5aa5 (which I'm now using) uses `serialize_newtype_struct`.

The way I see it this helps formats providing a better "type safety" if they want, and also might help in other languages to select custom decoders in specific places.

In the first commit there is no real alternative (I probably could use empty names...), in the second I could simply use the inner values directly.

**Comment by dtolnay** [comment]
I don't know of a non-human-readable format that needs struct names. One human-readable example is [RON](https://docs.rs/ron/0.1/ron/) where they prefer to display struct names for aesthetic reasons. It should be okay to serialize the inner values directly without a struct name if that simplifies the implementation.
