### ISSUE TITLE
Advanced #[serde(rename="", target="xml")] impl

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [serde-rs/serde#1152]
We figure an issue regarding xml serialisation/deserialisation, who can be relevant for other serialized formats.

As XML can represent values using attributes, value and namespace, each field can be associated to one of them.
So we discuss already [here](https://github.com/RReverser/serde-xml-rs/issues/62) about potential definitions, but for that we need to support the feature in SerDe project.

Our question is to know the feasibility to extend the structure [Field](https://github.com/serde-rs/serde/blob/9317bc5afa38a989af95828acab324bd33e960b1/serde_derive_internals/src/attr.rs#L714) and add an attribute `target ` which can be filtered by serializers/deserializers.

If an another solution can be relevant, please share your point of view.

Marc-Antoine

**Comment by dtolnay** [comment]
XML is an unusual format with unusual requirements. I believe it is time for someone to write a custom derive that handles XML serialization and deserialization in full generality rather than continuing to rely on Serde's derives with magic rename strings like `rename = "$xml:path:Container"`.

**Comment by MarcAntoine-Arnaud** [comment]
Yes, but is it really safe to do that with all others serialisations ?
This also means an XML wi provide a json like:
```json
{
    "$xml:path:Reply/Container/Item" : [ "value1", "value2" ]
}
```
Which was not the most elegant representation.
And for that a specific rename per serialiser can be a good way. What do you think ?

**Comment by dtolnay** [comment]
I am proposing not to use Serde for XML.

With a custom derive specifically for XML serialization, you don't run into the problem of what happens when you serialize an XML struct to JSON.
