### ISSUE TITLE
Deriving serialization traits is too slow

### ISSUE THREAD

**Issue by kvark** [serde-rs/serde#1153]
We are seeing a rapid increase in the [Gecko build times](https://bugzilla.mozilla.org/show_bug.cgi?id=1433910) since we enabled the `capture` feature of WebRender ([read more](http://kvark.github.io/webrender/debug/ron/2018/01/23/wr-capture-infra.html)). TL;DR: lots of internal structs `derive(Serialize, Deserialize)`.

```bash
git clone https://github.com/servo/webrender wr
cd wr/webrender
cargo build --release # took 157 seconds
cargo clean
cargo build --release --features capture # took 320 seconds
```

Is there anything we can do about it? Generate less code, or do it more efficiently perhaps?

**Comment by dtolnay** [comment]
Sounds good. `Serialize` impls typically compile faster than `Deserialize`.

**Comment by dtolnay** [comment]
We are always interested in cutting down compile times but it sounds like the immediate concern has been addressed by https://github.com/servo/webrender/pull/2359.
