### ISSUE TITLE
Partial deserialization

### ISSUE THREAD

**Issue by Freyr666** [serde-rs/serde#1154]
Is it possible to deserialize structure partially (i.e. something like serde_json::Value but generic across formats). For example:

```
struct Partial<'a> {
    name: &'a str,
    val:  &'a str
}

struct A {
    time: i64,
}

struct B<'a> {
    text: &'a str,
    int:  i64
}

fn main () {
    ...
    let v : Partial = serde_json::from_str(&buffer).unwrap();
    if v.name = "A" {
        let a : A = serde_json::from_str(&v.val).unwrap();
        ...
    } else if v.name = "B" {
        let b : B = serde_json::from_str(&v.val).unwrap();
        ...
    }
}
```

**Comment by oli-obk** [comment]
Your code already works: https://play.rust-lang.org/?gist=8bf276590253a98706d0309afbeb9c12&version=stable

What exactly are you missing?

**Comment by Freyr666** [comment]
@oli-obk >Your code already works: https://play.rust-lang.org/?gist=8bf276590253a98706d0309afbeb9c12&version=stable

Not exactly, you use `let a : A = serde_json::from_str(&buffer).unwrap();` instead of `let a : A = serde_json::from_str(&v.val).unwrap();`

I want something like this but format-independent:

```
struct Partial<'a> {
    name: &'a str,
    val:  Value
}

struct A {
    time: i64,
}

struct B<'a> {
    text: &'a str,
    int:  i64
}

fn main () {
    ...
    let v : Partial = serde_json::from_str(&buffer).unwrap();
    if v.name = "A" {
        let a : A = serde_json::from_value(&v.val).unwrap();
        ...
    } else if v.name = "B" {
        let b : B = serde_json::from_value(&v.val).unwrap();
        ...
    }
}
```

**Comment by oli-obk** [comment]
so your json looks like the following?

```json
    {
        "name": "A",
        "val": {
            "time": 42
        }
    }
```

**Comment by yangby-cryptape** [comment]
@oli-obk
If I can do partial parsing, when parsing `val` throws an error, at least I can get a `name`.
I can do better error handling.
