### ISSUE TITLE
Deserialize enum on from same level other struct fields.

### ISSUE THREAD

**Issue by EPashkin** [serde-rs/serde#1155]
I have enum that used in lots structs:
```rust
#[derive(Debug, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Ident {
    Name(String),
    Pattern(String),
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Func {
    ident: Ident,
    typ: String,
    /*
    some other fields
    */
}
```
I where way to deserizalize struct `Func` from string where "name" or "pattern" data is on same level as "typ" and other `Func` fields? Ex. for JSON from `r#"{"name":"func1", "typ":"str"}"#` or `r#"{"pattern":".+", "typ":"str"}"#` ?

I created [repo with tests](https://github.com/EPashkin/serde_enum_in_struct_test)  for this problem.

**Comment by dtolnay** [comment]
Yes I would like to support this! We are tracking this pattern in #119. It may look something like:

```rust
#[derive(Deserialize)]
struct Func {
    #[serde(flatten)]
    ident: Ident,
    typ: String,
}
```

**Comment by EPashkin** [comment]
Thanks for pointing that issue
