### ISSUE TITLE
Is it possible to deserialize string to a enum?

### ISSUE THREAD

**Issue by vityafx** [serde-rs/serde#1156]
Suppose I have a field in json which may have two values: "online" and "offline".
I'd like to use a enum here:

```rust
#[derive(Debug, Copy, Clone, Deserialize)]
pub enum OnlineState {
    Offline,
    Online,
}
```

Is it possible to do this?

**Comment by dtolnay** [comment]
This should work out of the box. [Playground](https://play.rust-lang.org/?gist=cfa63677350fb4dc3daf65f1c16c0cbc)

You would need to use [`rename_all`](https://serde.rs/container-attrs.html#serderenameall--) where the JSON names are different from the enum variant names.

**Comment by vityafx** [comment]
Nice, it works! Thank you :)
