### ISSUE TITLE
expected &mut _, found type parameter errors

### ISSUE THREAD

**Issue by glennpierce** [serde-rs/serde#1157]
Hi I had some old working code that I am trying to update to the latest Serde.

It was something like

```
#[derive(Debug, Serialize, Deserialize)]
pub struct SensorValue {
    #[serde(serialize_with = "dt_as_tuple", deserialize_with = "dt_from_tuple")]
    pub dt: NaiveDateTime,
    pub value: f64
}

#[derive(Debug, Serialize, Deserialize)]
pub struct SensorValueArray {
    //packet_type: PacketType,
    pub id: i32,
    pub values: Vec<SensorValue>
}

// NaiveDateTime serializes in string representation by default; serialize it as
// (seconds, nanos) tuple instead.
fn dt_as_tuple<S>(ndt: &NaiveDateTime, serializer: &mut S) -> Result<(), S::Error>
    where S: Serializer
{
    (ndt.timestamp(), ndt.timestamp_subsec_nanos()).serialize(serializer)
}

// NaiveDateTime deserializes from string representation by default; deserialize
// it from (seconds, nano) tuple instead.
fn dt_from_tuple<'de, D>(deserializer: &mut D) -> Result<NaiveDateTime, D::Error>
    where D: Deserializer<'de>
{
    let (secs, nanos) = Deserialize::deserialize(deserializer)?;
    Ok(NaiveDateTime::from_timestamp(secs, nanos))
}
```

I had lifetime issues with Deserializer that I have tried to fix but I am still getting errors like

#[derive(Debug, Serialize, Deserialize)]
   |                 ^^^^^^^^^ expected &mut _, found type parameter

and

93 | #[derive(Debug, Serialize, Deserialize)]
   |                 ^^^^^^^^^
   |                 |
   |                 expected associated type, found ()
   |                 expected `std::result::Result<<__S as serde::Serializer>::Ok, <__S as serde::Serializer>::Error>` because of return type
   |

Can I have some pointers to what has changed here. 

Thanks

**Comment by oli-obk** [comment]
your `serialize_with` and `deserialize_with` functions do not conform to the API required (see the relevant documentation: https://serde.rs/field-attrs.html#serdeserializewith--path).

The expected signatures are

```rust
fn<S>(&T, S) -> Result<S::Ok, S::Error> where S: Serializer;
fn<'de, D>(D) -> Result<T, D::Error> where D: Deserializer<'de>;
```

See https://play.rust-lang.org/?gist=23b66424fda8756edfb545ab06a0b904&version=stable for a working example

**Comment by glennpierce** [comment]
Awesome. Thanks very much.
