### ISSUE TITLE
Unit variants in untagged enums

### ISSUE THREAD

**Issue by fenhl** [serde-rs/serde#1158]
I have a JSON field I need to deserialize that can be either of the strings `"inf"` or `"-inf"`, or a number. Here's what I wrote to do this: http://play.integer32.com/?gist=41fad89f745ca7600760500aee153e90&version=stable

I was surprised to see that this doesn't work, even without the `rename` attributes, so I asked in IRC and the answer was to implement `Deserialize` manually. I'd like to avoid that if possible, so I'm requesting some way to achieve this as a feature.

**Comment by dtolnay** [comment]
"Untagged" means that we pick a variant based on what data it contains, not based on the name. So renaming the variant with `serde(rename = "...")` wouldn't make a difference. It may seem surprising in your inf example but hopefully not surprising in something like:

```rust
#[derive(Deserialize)]
#[serde(untagged)]
enum Value {
    Null,
    Bool(bool),
    String(String),
    Array(Vec<Value>),
    Object(Map<String, Value>),
}
```

Deserializing the tagged (identified by name) variants as tagged should work:

```rust
#[macro_use]
extern crate serde_derive;

extern crate serde;
use serde::{Deserialize, Deserializer};

#[derive(Deserialize)]
#[serde(untagged)]
enum Foo {
    #[serde(deserialize_with = "inf")]
    Inf,
    Float(f64)
}

fn inf<'de, D>(deserializer: D) -> Result<(), D::Error>
    where D: Deserializer<'de>
{
    #[derive(Deserialize)]
    enum Helper { #[serde(rename = "inf")] Variant }
    Helper::deserialize(deserializer)?;
    Ok(())
}
```
