### ISSUE TITLE
Using a keyword as a key with serde_derive

### ISSUE THREAD

**Issue by LordZane** [serde-rs/serde#1160]
An api I need to interact with via json has a key called "type". However thats also a rust keyword, and serde_derive fails to parse the structure

**Comment by dtolnay** [comment]
You will need to pick a different name for the field and use a `rename` [attribute](https://serde.rs/attributes.html) to get it to deserialize as `type`.

```rust
#[derive(Deserialize)]
struct LordZane {
    #[serde(rename = "type")] 
    t: String
}
```

**Comment by LordZane** [comment]
thank you!

**Comment by ycd** [comment]
Awesome, thanks!
