### ISSUE TITLE
Can not parse enum number

### ISSUE THREAD

**Issue by vityafx** [serde-rs/serde#1162]
I have tried to parse a enum with numbers and it did not work for me ([playground](https://play.rust-lang.org/?gist=8cca9ce5c4eee0b4526beb656a1a0ba5&version=stable)).

```rust
#[macro_use]
extern crate serde_derive;

extern crate serde;
extern crate serde_json;

use std::fmt;
use serde::de::{self, Deserialize, Deserializer, Visitor};

macro_rules! enum_number {
    ($name:ident { $($variant:ident = $value:expr, )* }) => {
        #[derive(Clone, Copy, Debug, Eq, PartialEq)]
        pub enum $name {
            $($variant = $value,)*
        }

        impl<'de> serde::Deserialize<'de> for $name {
            fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
                where D: serde::Deserializer<'de>
            {
                struct Visitor;

                impl<'de> serde::de::Visitor<'de> for Visitor {
                    type Value = $name;

                    fn expecting(&self, formatter: &mut fmt::Formatter) -> fmt::Result {
                        formatter.write_str("integer")
                    }

                    fn visit_i64<E>(self, value: i64) -> Result<$name, E>
                        where E: serde::de::Error
                    {
                        // Rust does not come with a simple way of converting a
                        // number to an enum, so use a big `match`.
                        match value {
                            $( $value => Ok($name::$variant), )*
                            _ => Err(E::custom(
                                format!("unknown {} value: {}",
                                stringify!($name), value))),
                        }
                    }
                }

                // Deserialize the enum from a i64.
                deserializer.deserialize_i64(Visitor)
            }
        }
    }
}

enum_number!(Change {
    Up = 1,
    None = 0,
    Down = -1,
});


fn main() {
    let j = "1";
    println!("{:?}", serde_json::from_str::<Change>(j).unwrap());
}
```

The error is very strange:

> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorImpl { code: Message("invalid type: integer `1`, expected integer"), line: 1, column: 1 }', /checkout/src/libcore/result.rs:916:5

What's wrong?

- serde 1.0

P.S. Even original docs in [`serde.rs`](https://serde.rs/enum-number.html) fail if I change `u64` to `i64` in the deserialize method ([playground](https://play.integer32.com/?gist=b8c7014fee6ebe9b574792d4ebc4ad6e&version=stable)).

**Comment by dtolnay** [comment]
That error message is pretty bad...

I think what you're seeing is JSON does not differentiate between different number types and as a compromise between JSON's notion of numbers and Rust's notion of numbers serde_json treats all nonnegative integers as u64 and all negative integers as i64. It should work if we also provide a `visit_u64` method so that both nonnegative and negative integers end up applying the same `match`.

```rust
fn visit_u64<E>(self, value: u64) -> Result<$name, E>
    where E: serde::de::Error
{
    self.visit_i64(value as i64)
}
```

**Comment by vityafx** [comment]
@dtolnay yes, this works. However, this is ugly and very and very not user-friendly and understandable at a glance. I suggest you comment this behavior on the same `serde.rs` page and even change the reference `macro_rules!` implementation there to work with `i64`.

**Comment by vityafx** [comment]
@dtolnay I am going to check whether it is possible to do this via a procedural macro. If it is so, I'd do this in my `serde_aux` crate for easing the pain.

**Comment by dtolnay** [comment]
Thanks! I filed https://github.com/serde-rs/serde-rs.github.io/issues/69 to follow up on showing how to handle a mix of positive and negative enum values in that example.
