### ISSUE TITLE
Getting ownership of indexed key in Value

### ISSUE THREAD

**Issue by golddranks** [serde-rs/serde#1165]
In the examples of `Value`, there is the following example:

    // "Steal" ownership of a value. Can replace with any valid Value.
    let old_x = value.pointer_mut("/x").map(|x| mem::replace(x, Value::Null)).unwrap();

`mem::replace` is a valid way of getting the ownership of a value, but I think that it would be more discoverable and feel "less hacky" if `serde_json` supported directly an indexing-like method that returned the ownership.

    let my_key = value.take("my_key");

I felt the need for this when trying to deserialize a partially-dynamical object:

    let list: Vec<StronglyTypedObject> = serde_json::from_value(weakly_typed.take("obj_list"))

**Comment by dtolnay** [comment]
Not as concise as `take`, but `weakly_typed.as_object_mut().unwrap().remove("obj_list").unwrap()` could work. It becomes even easier if you deserialize `weakly_typed` as a `serde_json::Map` rather than a `serde_json::Value` -- `weakly_typed.remove("obj_list").unwrap()`.

```rust
#[macro_use]
extern crate serde_json;

use serde_json::Value;

fn main() {
    let mut j = json!({
        "a": [0],
        "b": [1],
    });

    let b: Value = j.as_object_mut().unwrap().remove("b").unwrap();
    println!("j = {}", j);
    println!("b = {}", b);
}
```

**Comment by golddranks** [comment]
Hmm, with `remove`, the most boiler-platey thing is the error handling... Even when `?` on `Option` and `NoneType` becomes usable on stable, the error message is unhelpful, and requires `ok_or` to have a decent error message. In that sense, `take`  would be a nice sugar for that, with an error that tells "missing field *fieldname*". However, there seems to be no precedent, as all the other `get` APIs are using `Option`.

**Comment by dtolnay** [comment]
Is the expectation that `.take(k)` would be equivalent to `.remove(k).unwrap_or_else(|| some helpful message)`?

For now the `serde_json::Map` methods are intended to mirror the methods on HashMap and BTreeMap -- with `get` and `remove` returning Options as you saw. It may be neat to provide an extension trait for `.take(k)` in its own library if you have found that to be commonly useful. The extension trait could be implemented for all types of maps including `serde_json::Map`.
