### ISSUE TITLE
Use compile_error macro to report invalid attribute errors

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#1168]
Currently we use [`Ctxt`](https://github.com/serde-rs/serde/blob/v1.0.27/serde_derive_internals/src/ctxt.rs) in `serde_derive_internals` to batch up errors detected during the attribute parsing step of `serde_derive`, then panic with the resulting message in [`derive_serialize` and `derive_deserialize`](https://github.com/serde-rs/serde/blob/v1.0.27/serde_derive/src/lib.rs).

```rust
#[derive(Serialize)]
struct S {
    #[serde(typo, with = 1)]
    field: String,
}
```

```
error: proc-macro derive panicked
 --> src/main.rs:4:10
  |
4 | #[derive(Serialize)]
  |          ^^^^^^^^^
  |
  = help: message: 2 errors:
              # unknown serde field attribute `typo`
              # expected serde with attribute to be a string: `with = "..."`
```

It would be better to use [`std::compile_error!`](https://doc.rust-lang.org/std/macro.compile_error.html) instead of a panic. The resulting user-visible error message can be rendered more nicely.

The `compile_error!` macro was stabilized in Rust 1.20 and we currently support older Rust versions than that, but it would not be a breaking change to begin using `compile_error!` and I am comfortable doing so. In the worst case somebody's code failed to compile before the change and then fails to compile a slightly different way after the change.

**Comment by nivkner** [comment]
I think there might be a misunderstanding about how `compile_error!` works.

This macro fails to compile *unconditionally* when encountered in the source code. The way it usually works is that it is included in a declarative macro or in a `cfg` attribute. That way the macro never appears in the source code in the first place. 

Procedural macros on the other hand are actual rust code that gets evaluated separately, so when the macro is encountered it doesn't wait for the function to be called on a user provided token stream, just like how every other compile time error doesn't wait for the functions execution (by definition).

Consider the fact that if you where to call `push` on an integer inside a declarative macro that doesn't get called, nothing would happen, but try the same thing in a procedural macro and it will error out. 

This has been proven empirically by including the macro in `derive_deserialize` and having it fail to compile.

To address the problem of distinguishing bugs and user made errors it might be better to prepend the bug produced error messages with `this is a bug : (etc)`, in a way similar to how the compiler deals with its own errors.
