### ISSUE TITLE
Vec<T> is called heterogeneous sequence of values

### ISSUE THREAD

**Issue by pravic** [serde-rs/serde#1169]
But I am sure it is wrong because it contains values of single type. The same for **map**. 

Here: https://serde.rs/data-model.html

Some definitions from the internet: https://wiki.haskell.org/Heterogenous_collections

**Comment by dtolnay** [comment]
I believe this is correct as written. Keep in mind that Serde's type system is different from Rust's type system. For example the Rust value:

```rust
vec![serde_json::Value::Bool(true), serde_json::Value::String("s".into())]
```

is a homogeneous Rust vector containing elements of type `serde_json::Value`, but it is a heterogeneous Serde **seq** containing a Serde **bool** followed by a Serde **string**.

**Comment by pravic** [comment]
Oh, you are right, it was about Serde's type model.

This phrase has confused me: 

> A variably sized heterogeneous sequence of values, for example Vec<T> or HashSet<T>. 

May be it's better to clarify or rewrite it. E.g. "... for example, constructed from Vec <T>" or something like that.

**Comment by dtolnay** [comment]
I added a clarification in https://github.com/serde-rs/serde-rs.github.io/commit/f62f29878627e4f5335ff4f3c010f234b9d7bbb6.
