### ISSUE TITLE
Status of serde_derive with syn 0.12?

### ISSUE THREAD

**Issue by cuviper** [serde-rs/serde#1171]
I see that `serde_derive` has already updated to `quote` 0.4 and `syn` 0.12 in git, but this hasn't been published.  Is it waiting for something?

(We're trying to keep Fedora rawhide updated to the latest version of all packages.)

**Comment by dtolnay** [comment]
Sorry about the delay, I have published 1.0.28 which works with syn 0.12.

**Comment by cuviper** [comment]
Great, thanks!
