### ISSUE TITLE
serde_derive compilation fails on windows gnu with rust nightly

### ISSUE THREAD

**Issue by sagiegurari** [serde-rs/serde#1180]
See example build at:

https://ci.appveyor.com/project/sagiegurari/cargo-make/build/1.0.600/job/tt03ws1pdppwq6u2#L176

I see that you do not run builds on gnu in appveyor so you will not see it.
So I suggest apart of a fix to also add it to the appveyor matrix.

**Comment by dtolnay** [comment]
Thanks, this is being tracked in https://github.com/rust-lang/rust/issues/49044.

**Comment by dtolnay** [comment]
Upstream indicates that this has been fixed. Please leave a comment in https://github.com/rust-lang/rust/issues/49044 if you find it has not been fixed for you as of the most recent nightly.

I filed #1182 to track adding an x86_64-pc-windows-gnu build in AppVeyor.
