### ISSUE TITLE
Internal type tags can still conflict in a newtype variant

### ISSUE THREAD

**Issue by H2CO3** [serde-rs/serde#1181]
Yeah, yeah… apparently I didn't do a comprehensive enough job last time. However, this time I'm not even remotely sure how to tackle the problem.

So, this is what happens:
* Suppose an internally-tagged enum has a newtype variant which itself contains an internally-tagged enum, either…
  * directly, or
  * indirectly, by means of being nested in 1 or more levels of untagged enums with a newtype variant.
* Now:
  * if the containing and contained internally-tagged enums have the same type tag, or
  * if a struct variant of the contained enum has a field with the same name as the type tag,

then they end up being serialized at the same level, generating a conflict.

See the following MVCE:

```
#[macro_use]
extern crate serde_derive;
extern crate serde_json;
extern crate serde;

// internally-tagged top-level enum
#[derive(Serialize)]
#[serde(tag = "same")]
enum Foo {
    Qux(Z), // newtype variant around another internally-tagged enum itself
    Bar(X), // newtype variant around two levels of untagged, then one internally-tagged enum
    New(E), // newtype variant containing an untagged enum containing a struct variant with a conflicting field name
}

#[derive(Serialize)]
#[serde(untagged)]
enum X {
    Y(Y)
}

#[derive(Serialize)]
#[serde(untagged)]
enum Y {
    Z(Z),
}

#[derive(Serialize)]
#[serde(tag = "same")]
enum Z {
    Z,
}

#[derive(Serialize)]
#[serde(untagged)]
enum E {
    F(F),
}

#[derive(Serialize)]
#[serde(tag = "different")]
enum F {
    Struct { same: () },
}

fn main() {
    println!("{}", serde_json::to_string_pretty(&Foo::Bar(X::Y(Y::Z(Z::Z)))).unwrap());
    println!("");
    println!("{}", serde_json::to_string_pretty(&Foo::Qux(Z::Z)).unwrap());
    println!("");
    println!("{}", serde_json::to_string_pretty(&Foo::New(E::F(F::Struct { same: () }))).unwrap());
}
```
Output:

```
{
  "same": "Bar",
  "same": "Z"
}

{
  "same": "Qux",
  "same": "Z"
}

{
  "same": "New",
  "different": "Struct",
  "same": null
}
```

The fundamental barrier in the way of implementing a fix for this bug is, I think, the fact that Serde would need to identify each nested type recursively, then check if they are untagged or internally-tagged enums with newtype or struct variants that cause a name conflict. I *think* this in turn requires proper type checking, at least I couldn't devise a way to determine if a type outside of the current `Context` has certain attributes and variants.

**Comment by dtolnay** [comment]
Thanks for following up! I am closing the issue because I don't think this can be caught by Serde. Derive macros run on one struct/enum at a time in isolation, and the field types may be unknown or may not even exist yet at that point in compilation.

Clippy may be a better place to implement this -- I believe they run with more type information and already have Serde-specific lints.

**Comment by dtolnay** [comment]
That would be great. :+1: Please @mention me on the PR.

**Comment by H2CO3** [comment]
Sure!
