### ISSUE TITLE
should serde provide a trait to standardize text position in errors?

### ISSUE THREAD

**Issue by Geal** [serde-rs/serde#1184]
Hello,
For a bit of context, I've added to one of my projects an error display like rustc, but for toml deserialization: https://twitter.com/gcouprie/status/976117416194428930

The code for this is quite simple ( https://github.com/sozu-proxy/sozu/blob/master/command/src/config.rs#L576-L583 ), but I was surprised that there's no common trait to provide position in errors for text formats parsed with serde.

- toml provides `toml::de::Error` with a `line_col()` method that works for some errors, but not all of them (like, if I put a number instead of a string somewhere, I won't have position info) https://docs.rs/toml/0.4.5/toml/de/struct.Error.html
- `serde_yaml::Error` has a `location()` method https://docs.rs/serde_yaml/0.7.3/serde_yaml/struct.Error.html
- `serde_json::Error` has `line()` and `column()` methods https://docs.rs/serde_json/1.0.12/serde_json/struct.Error.html

Could we have a trait that those crates could implement, that would provide position information for errors? And possibly, not only as a line and column, but as a span (so we can show "the issue is from here to there")

**Comment by dtolnay** [comment]
There would need to be a compelling real use case that benefits from having a trait for this.

I would note that just the opportunity for consistency is not enough reason to have a trait. For example `Vec` and `VecDeque` and `HashMap` all have a `fn reserve(&mut self, additional: usize)` but it doesn't mean there needs to be a trait involved.

**Comment by Marwes** [comment]
> And possibly, not only as a line and column, but as a span (so we can show "the issue is from here to there")

For this you may want to look at https://github.com/brendanzab/codespan (cc @brendanzab)
