### ISSUE TITLE
Converting between T and Json::Value, Toml::Value, etc.

### ISSUE THREAD

**Issue by axos88** [serde-rs/serde#1192]
Hello!

Having  serializable/deserializable value of T, how can one convert between it and Json::Value, Toml::Value, etc? Without serializing to string and deserializing again?

I imagine the deserializing/serializing goes from String to Json / Toml::Value first, and then to T right?

Thanks,
  Akos

**Comment by Marwes** [comment]
I think these functions does what you want?

https://docs.serde.rs/serde_json/fn.to_value.html
https://docs.serde.rs/serde_json/fn.from_value.html

https://docs.rs/toml/0.4.5/toml/value/enum.Value.html#method.try_from
https://docs.rs/toml/0.4.5/toml/value/enum.Value.html#method.try_into

**Comment by axos88** [comment]
@Marwes Yep, that looks like what I'm looking for. I will check it out, thanks!

**Comment by axos88** [comment]
Thank you!
