### ISSUE TITLE
Add take_object, take_array

### ISSUE THREAD

**Issue by botev** [serde-rs/serde#1197]
Currently `Value` has the methods `as_object` and `as_array` which however return references. When parsing some of the JSON further down I need to take these as values so that on some of the elements I can call `from_value` to a specific struct. I know that in certain circumstances one can instead just implement custom deserializer, however, it would be nice together with the `as_X` that there is something like `take_X` which gives back an `Option` with the value, not the reference.

**Comment by dtolnay** [comment]
Are you imagining `fn take_array(self) -> Option<Vec<Value>>` or `fn take_array(&mut self) -> Option<Vec<Value>>`?

By the way you should be able to deserialize from a Value reference without owning the data:

```rust
extern crate serde;
#[macro_use] extern crate serde_derive;
#[macro_use] extern crate serde_json;

use serde::Deserialize;

#[derive(Deserialize, Debug)]
struct Botev {
    method: String,
}

fn main() {
    let j = json!({ "botev": { "method": "take_object" } });
    let b: Botev = Deserialize::deserialize(&j["botev"]).unwrap();
    println!("{:?}", b);
}
```

**Comment by botev** [comment]
I envision more the second one, and similar to take to add null on its place. 
And I agree that deserialization like that is straightforward, but I have an object (map) mapping an identifier to struct fields. However, when I parse it the identifier is actually part of the fields. So I have smth along the lines of:
```
#[derive(Serialize, Deserialize, Debug, Clone)]
struct Market{
#[serde(default="mock_pair")]
pub pair: pair,
#[serde(default="mock_date_time")]
pub server_time: DateTime<Utc>,
// * fields *
}

fn pub method decode(json: Value) {
            let server_time: DateTime<Utc> = Utc::now();
            json.as_object_mut()
            .and_then(|o| o.get_mut("result"))
            .ok_or(ErrorKind::MissingField("result".to_string()))?
            .as_object_mut()
            .and_then(|o| o.remove("trading_pairs"))
            .ok_or(ErrorKind::MissingField("trading_pairs".to_string()))? {
            Value::Object(pairs_map) => {
                // This is the map from pair names to corresponding market
                pairs_map.into_iter().filter_map(|(k, v)| {
                    // If the key is a valid pair
                    Pair::from_str(&k).map(|p| {
                        // Decode values
                        let mut m: Market = from_value(v).unwrap();
                        // Set server time
                        m.server_time = server_time;
                        // Set pair
                        m.pair = p;
                        // Return MarketInfo
                        m
                    }).ok()
                }).collect()
            },
    _ => unimplemented!()
}
```
And basically I don't like the match statement and would prefer to be able to skip it.

**Comment by dtolnay** [comment]
The key is always to use serde_json::Value as little as possible -- only in cases where you know nothing about the shape of the input data. I would write this as:

```rust
fn decode(json: Value) -> Result<Vec<Market>> {
    #[derive(Deserialize)]
    struct Input {
        result: Data,
    }

    #[derive(Deserialize)]
    struct Data {
        trading_pairs: Map<String, Market>,
    }

    let input: Input = serde_json::from_value(json)?;
    let server_time: DateTime<Utc> = Utc::now();

    Ok(input.result.trading_pairs
        .into_iter()
        .filter_map(|(k, m)| {
            // If the key is a valid pair
            let pair = Pair::from_str(&k).ok()?;
            Some(Market { server_time, pair, ..m })
        })
        .collect())
}
```

**Comment by botev** [comment]
I actually did not know we can have such form of structs within functions... guess I have not been doing rust for a while and I came back to do something a few days ago, but yeah that looks like a better solution.
