### ISSUE TITLE
#[serde(bound = "T: MyTrait")] doesn't work

### ISSUE THREAD

**Issue by Boscop** [serde-rs/serde#1200]
How can I make this work? :)

![image](https://user-images.githubusercontent.com/535593/38051851-c95cfec6-32cf-11e8-89bb-4caf054c7216.png)

![image](https://user-images.githubusercontent.com/535593/38051849-c5cf3f6c-32cf-11e8-8321-711f7cf17ffa.png)

**Comment by dtolnay** [comment]
See [C-STRUCT-BOUNDS](https://rust-lang-nursery.github.io/api-guidelines/future-proofing.html#c-struct-bounds), the `T` type parameter of `PitchMap` should not have these bounds.

**Comment by Boscop** [comment]
Thanks! Should only the `Serialize` and `Deserialize` bounds be removed?

This compiles:
```rust
#[serde(bound = "T: Default + Clone + Serialize + DeserializeOwned + 'static")]
#[derive(SmartDefault, Clone, Serialize, Deserialize)]
pub struct PitchMap<T: Default> {
	#[default = "arr![Default::default(); 128*3]"]
	#[serde(with = "a384")]
	pitch_data: [T; 128*3],
}
```
I still need the `Default` bound on `T` for the inner `#[default]` attrib..
