### ISSUE TITLE
Duplicate field error on seemingly valid input without duplicate field

### ISSUE THREAD

**Issue by wezm** [serde-rs/serde#1202]
I was investigating https://github.com/faebser/beautiful-wallpaper-every-day/issues/1 the error being encountered is:

```
JSON parse error ErrorImpl { code: Message("duplicate field `user`"), line: 1, column: 3089 }
```

As far as I can tell the JSON is valid and does not actually contain a duplicate field, "user". I've created a small project to reproduce the issue: https://github.com/wezm/serde-duplicate-field

`cargo run` produces the error for me.

rustc 1.24.1

**Comment by dtolnay** [comment]
As the error message says, you have a duplicate `"user"` field in foto.json. There is one at column 183 and another at column 3084.

**Comment by wezm** [comment]
:facepalm: I searched it with `jq` and `grep` but it obviously just overwrote the first instance with the secong.
