### ISSUE TITLE
Infer correct trait bounds for use of a type parameter associated type

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#1208]
The following expands to `impl<T: Trait> Serialize for Struct<T>` which fails to compile.

```rust
trait Trait {
    type Assoc;
}

#[derive(Serialize)]
struct Struct<T: Trait> {
    assoc: T::Assoc,
}
```

The builtin derives already get this partially right. For example `#[derive(Debug)]` on the above expands to `impl<T: Debug + Trait> Debug for Struct<T> where T::Assoc: Debug`. This is partially right because it has `T::Assoc: Debug`, but wrong because it also has `T: Debug`.

**Comment by Osspial** [comment]
I've taken a stab at implementing this [here](https://github.com/Osspial/serde/tree/assoc_type_derive), which works by explicitly adding a `Serialize`/`Deserialize` requirement to all of the fields in a derived type that go through serialization/deserialization, respectively. It seems to work on the associated types I tried, but it's preventing some of the tests from compiling, and I'm not entirely sure how to go about fixing them. Would you mind looking at my code?

```rust
error[E0275]: overflow evaluating the requirement `test_gen::RecursiveA: serde::Serialize`
   --> test_suite\tests\test_gen.rs:158:14
    |
158 |     #[derive(Serialize, Deserialize)]
    |              ^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0275`.
```

**Comment by dtolnay** [comment]
We would want to add bounds specifically in the case that a field type looks like `T::Assoc` where `T` is one of the type parameters of your data structure and `Assoc` is any ident. There should be no change in any other case.

**Comment by Osspial** [comment]
Alright, updated the code to do that. The new version passes the test suite, and I've put in a PR.
