### ISSUE TITLE
Using SIMD for JSON parsing

### ISSUE THREAD

**Issue by KasMA1990** [serde-rs/serde#1210]
The [pikkr crate](https://github.com/pikkr/pikkr/blob/master/README.md)<sup>1</sup> implements JSON parsing with SIMD, getting some big performance wins over serde seemingly. Might it be worth investigating using SIMD parsing in serde?

I'm not actually able to do the work myself, but maybe it can spark some discussion and lead to an able developer jumping on it :)

------------

<a name="Credit">1</a>: Credit to [this reddit comment](https://www.reddit.com/r/rust/comments/89szbq/this_commit_stabilizes_the_simd_in_rust_for_the/dwtu1x9/?st=jfmipztr&sh=f841d913).

**Comment by dtolnay** [comment]
Thanks, let's continue to track this in https://github.com/serde-rs/json/issues/120.
