### ISSUE TITLE
Distinct rename variants for serialization / deserialization

### ISSUE THREAD

**Issue by kamek-pf** [serde-rs/serde#1214]
Hello,

At my job we do a lot of mapping between data we get from external APIs and our own internal data structures. In many cases, it's just a matter of renaming a few fields and doing some validation, your classic case of data massaging.
Let's say I want to transform this :
```json
{
    "user_id": "xxyyzz",
    "inputoct": 54,
    "outputoct": 156
}
```
Into this :
```json
{
    "userId": "xxyyzz",
    "inputBytes": 54,
    "outputBytes": 156,
    "timestamp": 1523397519
}
```

I usually deal with this by defining two separate structures : one for the data I receive from the outside, and one for the structure I actually want to work with in the rest of the system.
For these cases, I believe it should be possible to do it in a single step, with an ergonomic API. Something along those lines : 

```rust
#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all_serialize = "camelCase")] // doesn't exist
pub struct MyFakeData {
    pub user_id: String,
    #[serde(rename_deserialize = "inputoct")] // same
    pub input_bytes: i64,
    #[serde(rename_deserialize = "outputoct")] // same
    pub output_bytes: i64,
    #[serde(default = "timestamp_now")]
    pub timestamp: u64
}

...
```

Throw in the awesome [validator](https://github.com/Keats/validator) in the mix and the whole process becomes extremely straightforward.

I'd love to hear some thoughts about this.

**Comment by dtolnay** [comment]
I don't think it has been implemented for `rename_all`, but for `rename` you can specify the serialize and deserialize renames independently.

```rust
#[derive(Serialize, Deserialize)]
struct MyFakeData {
    #[serde(rename(serialize = "userId"))]
    user_id: String,
    #[serde(rename(deserialize = "inputoct", serialize = "inputBytes"))]
    input_bytes: i64,
    #[serde(rename(deserialize = "outputoct", serialize = "outputBytes"))]
    output_bytes: i64,
    #[serde(default = "timestamp_now")]
    timestamp: u64,
}
```

**Comment by kamek-pf** [comment]
Looks just like what I needed !
Thanks @dtolnay !
