### ISSUE TITLE
Deserializing untagged enum variants broke/changed between v1.0.38 and v1.0.39

### ISSUE THREAD

**Issue by tecywiz121** [serde-rs/serde#1216]
Still working out the details, but something changed between 1.0.38 and 1.0.39 that's broken my untagged enum.

I'm doing a bisect right now to figure out the commit that introduced the change.

**Comment by dtolnay** [comment]
Can you share the enum that broke? Is there a custom Deserialize impl involved?

**Comment by tecywiz121** [comment]
Sure! Sorry, got a little lost in trying to get cargo to use my local serde.

I wanted a way to reference another file from inside of a TOML file, so I made this. As an aside, if there's a more idiomatic way to do this with serde, I'm all ears.

[Playground](https://play.rust-lang.org/?gist=fcb588e2c7167ee482786fdfe5c05fdf&version=nightly)

[Gist](https://gist.github.com/fcb588e2c7167ee482786fdfe5c05fdf)

**Comment by tecywiz121** [comment]
Thanks for the feedback, very much appreciated! The bound attribute was required when I first wrote this, but I guess that requirement is gone? Weird.

I'd still say this is a bug, since the behavior changed pretty dramatically for a patch version, no?

**Comment by dtolnay** [comment]
Absolutely. Thanks! This is fixed in 3c4961c48e891057ce080e3bd00b66d0f6097683 and released in Serde 1.0.40 so the code in the gist is back to working as before. Really sorry about the breakage.
