### ISSUE TITLE
Serializing a map with non-string keys will silently generate invalid JSON

### ISSUE THREAD

**Issue by Diggsey** [serde-rs/serde#122]
For example, a `HashMap<u32, u32>` will produce invalid JSON when serialized.

At a minimum, the json serializer should error rather than produce invalid JSON.

Ideally however, it would fall back to serializing the map as a list of pairs:
```
[[0, 1], [2, 0], ...]
```

**Comment by oli-obk** [comment]
we had this issue before with rustc-serialize... I wasn't aware we also had it in serde...

probably we just need an intermediate serializer here: https://github.com/serde-rs/serde/blob/master/serde_json/src/ser.rs#L262 that is passed to the MapVisitor, to check for stringable keys and error else. Fallback to serializing the map as a list of pairs isn't really doable. You should be serializing an iterator to get that behavior.

**Comment by erickt** [comment]
Good idea @oli-obk! let me whip that up...
