### ISSUE TITLE
Check invariants when deserializing

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#1220]
Question from IRC:

> **\<tcsc>** if i have a type that has invariants i want to be sure are maintained, can i use this with derive(Serialize, Deserialize)? if so, how can i provide checks that the deserialized data is sane?

**Comment by dtolnay** [comment]
```rust
#[macro_use]
extern crate serde_derive;

extern crate serde;
extern crate serde_json;

use serde::de::{self, Deserialize, Deserializer};

#[derive(Deserialize, Debug)]
#[serde(remote = "Self")]
struct Invariant {
    /// len() >= 3
    s: String,
}

impl<'de> Deserialize<'de> for Invariant {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let unchecked = Invariant::deserialize(deserializer)?;
        if unchecked.s.len() < 3 {
            return Err(de::Error::custom("length of `s` must be >= 3"));
        }
        Ok(unchecked)
    }
}

fn main() {
    let j = r#" {"s": "abc"} "#;
    println!("{:?}", serde_json::from_str::<Invariant>(j).unwrap());
}
```

**Comment by piegamesde** [comment]
Is this done often enough to be worthy of a "proper" implementation? With something like `#[serde(check = "path")]` where "path" points to a function that performs the invariant check? This could be done either as container or field attribute.

**Comment by frivoal** [comment]
This is great, but in this partern, what is the best way to write the serializing part? Unlike deserializing, it needs no invariant checking, so `#[derive(Serialize)]` would do the right job, but `#[serde(remote = "Self")]` seems to inhibit that, and to call for an explicit definition.

Is this the correct approach, or is there something even simpler?
```rust
use serde::{de, Deserialize, Deserializer, Serialize, Serializer};

#[derive(Deserialize, Serialize, Debug)]
#[serde(remote = "Self")]
struct Invariant {
    // …
}

// …
// Deserialization as above
// …

impl Serialize for Invariant {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        Invariant::serialize(self,serializer)
    }
}

```
