### ISSUE TITLE
Does serde offer a type that can be used to hold raw json strings?

### ISSUE THREAD

**Issue by arynhard** [serde-rs/serde#123]
Is it possible to do something like Go's [RawMessage](http://golang.org/pkg/encoding/json/#RawMessage)? I would like to define a struct like so:

````rust
pub struct SomeStruct {
    msg: json::Raw
}
````

This would be nice in a situation when the `msg` field is passed to a [DynamicLibrary](https://doc.rust-lang.org/std/dynamic_lib/struct.DynamicLibrary.html) which then has the proper struct in place.

**Comment by oli-obk** [comment]
kindof... you can use `serde_json::Value`, it's not a string, but it parses ANY valid json.

**Comment by oli-obk** [comment]
You can then, in the other library, deserialize the `Value` to your actual struct. I think there's a `from_value` function

**Comment by oli-obk** [comment]
@arynhard does this solve your issue? If not, please provide more information as to what's troubles you are running into.

**Comment by arynhard** [comment]
Yes. This seems to serve the same purpose.
