### ISSUE TITLE
Manual flattening?

### ISSUE THREAD

**Issue by rushmorem** [serde-rs/serde#1236]
When manually implementing the `Deserialize` and `Serialize` traits, is there any way to know that `#[serde(flatten)]` is set? I would like to apply custom logic when flattening.

**Comment by dtolnay** [comment]
I believe there is no way to tell currently. The flattened representation is always based on what you would get by serializing the flattened value by itself. Can you give an example of the data structure you are dealing with?

**Comment by rushmorem** [comment]
Never mind. I'm exploring an alternative design for XML support. Unlike `serde-xml-rs` which assumes that values are coming from attributes by default and uses `#[serde(rename = "$body")]` to indicate otherwise, I thought it might be better to assume that values are coming from the body by default and then use `#[serde(flatten)]` to mark those that are coming from attributes. I've since read your other comments on the subject.
