### ISSUE TITLE
Trying to use derive with flatten, remote type and field to tuple struct conversion

### ISSUE THREAD

**Issue by 23ua** [serde-rs/serde#1239]
I'm trying to use serde for (de)serializing the following json format:
```json
{
    "batt": 100,
    "lon": 31.123434343,
    "lat": 54.123532323
}
```
Into the following Rust struct:

```rust
pub struct Location {
    pub battery: Option<u8>,
    pub point: PgPoint
}
```

where [PgPoint](https://docs.rs/diesel_geometry/1.2.2/diesel_geometry/pg/data_types/struct.PgPoint.html) is an external type from [diesel_geometry](https://docs.rs/diesel_geometry) crate.

In order to do this, I'm trying to apply multiple serde attributes:
- [`flatten`](https://serde.rs/attr-flatten.html)
- `with` for [remote derive](https://serde.rs/remote-derive.html) of PgPoint

I also need to represent fields `lon` and `lat` as a tuple struct (`PgPoint`) instead of a field struct (e.g. something like `PgPointHelper` in the following code)

I've come up with this solution (which doesn't compile):

```rust
use diesel_geometry::data_types::PgPoint;
use serde::{Serialize, Serializer, Deserialize, Deserializer};

#[derive(Serialize, Deserialize, Debug)]
pub struct Location {
    #[serde(rename = "batt")]
    pub battery: Option<u8>,
    #[serde(with = "PgPointDef")]
    #[serde(flatten)]
    pub point: PgPoint
}

// json conversion hacks begin here

#[derive(Serialize, Deserialize, Debug)]
#[serde(remote = "PgPoint")]
struct PgPointDef(pub f64, pub f64);

#[derive(Serialize, Deserialize, Debug)]
struct PgPointHelper {
    pub lat: f64,
    pub lon: f64
}

impl<'se> Serialize for PgPointDef {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
        where S: Serializer
    {
        PgPointHelper { lat: self.0, lon: self.1 }.serialize(serializer)
    }
}

impl<'de> Deserialize<'de> for PgPointDef {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
        where D: Deserializer<'de>
    {
        Deserialize::deserialize(deserializer)
            .map(|PgPointHelper { lat, lon }| PgPointDef(lat, lon))
    }
}
```

The problem is that serde seems to ignore `#[serde(with = "PgPointDef")]` attribute when I add `#[serde(flatten)]` attribute for the `point` field:

```rust
error[E0277]: the trait bound `diesel_geometry::data_types::PgPoint: serde::Deserialize<'_>` is not satisfied
 --> src/location.rs:5:21
  |
5 | #[derive(Serialize, Deserialize, Debug)]
  |                     ^^^^^^^^^^^ the trait `serde::Deserialize<'_>` is not implemented for `diesel_geometry::data_types::PgPoint`
  |
  = note: required by `serde::Deserialize::deserialize`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
```

If I remove `flatten` attribute, the code compiles successfully.

I'm also not sure if it will work correctly because I'm deriving `Serialize`, `Deserialize` for `PgPointDef` and then implementing them myself (I can't do it for `PgPoint` directly because it's in a remote crate).

Is there a better (working) way to do this?
Or should I just implement `Serializer`/`Deserializer` myself without deriving?

Sorry if I'm doing something stupid, I'm kind of a newbie when it comes to Rust.

Thanks.

**Comment by dtolnay** [comment]
I fixed the bug that was causing `#[serde(flatten, with = "PgPointDef")]` to generate broken code -- #1240. Please update to serde 1.0.44.

I would implement this as:

```rust
#[derive(Serialize, Deserialize, Debug)]
struct Location {
    #[serde(rename = "batt")]
    battery: Option<u8>,
    #[serde(flatten, with = "serde_pg_point")]
    point: PgPoint,
}

mod serde_pg_point {
    use diesel_geometry::data_types::PgPoint;
    use serde::{Serialize, Serializer, Deserialize, Deserializer};

    #[derive(Serialize, Deserialize)]
    struct PgPointHelper {
        lat: f64,
        lon: f64,
    }

    pub fn serialize<S>(point: &PgPoint, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        PgPointHelper { lat: point.0, lon: point.1 }.serialize(serializer)
    }

    pub fn deserialize<'de, D>(deserializer: D) -> Result<PgPoint, D::Error>
    where
        D: Deserializer<'de>,
    {
        let point = PgPointHelper::deserialize(deserializer)?;
        Ok(PgPoint(point.lat, point.lon))
    }
}
```

**Comment by 23ua** [comment]
My code snippet compiles successfully with v1.0.44 and your implementation does exactly what I need.
Thanks!
