### ISSUE TITLE
Support deserializing flattened untagged enum

### ISSUE THREAD

**Issue by r8d8** [serde-rs/serde#1253]
Getting error while flattening enum inside struct:
```
value: Error("can only flatten structs and maps", line: 6, column: 5)'
```
Source code: https://gist.github.com/r8d8/2940b5490a90204e5052809eae9b8868

`serde` version 1.0.51

**Comment by dtolnay** [comment]
I released Serde 1.0.53 with a fix -- after a `cargo update` your code should work as written.
