### ISSUE TITLE
serde_derive additions should be breaking changes

### ISSUE THREAD

**Issue by xfix** [serde-rs/serde#1262]
New versions of `serde_derive` are incompatible with older versions of `serde` which constitutes a backwards compatibility break according to semver. An incompatibility will cause confusing error messages about serde_derive implementing trait methods that don't exist in a trait. If Cargo for some reason decides to use `serde`, say 1.0.23 and `serde_derive` version 1.0.55 (which is perfectly fine if you depend on say, `serde="1.0"` and `serde_derive="1.0"`), things will break - [I had issue like this happening a few times](https://github.com/serde-rs/serde/pull/1080).

Yes, fixing this will cause `serde_derive` to rapidly increase its major version each time it will attempt to implement a new method, I think that's fine. Additionally, it won't be that often - this way it won't be required to release a new version of `serde_derive` each time a new version of `serde` would be released. Version numbers aren't meant to be pretty but meaningful.

**Comment by xfix** [comment]
I mean, you can use `serde = { version = "1.0", features = ["derive"] }` if you like, in this case version of `serde_derive` is unimportant, and the combination of both would be still semver compatible. The issue is when using `serde` and `serde_derive` separately in `Cargo.toml`.

**Comment by dtolnay** [comment]
Thanks for raising this issue! There are advantages and disadvantages in both directions. I believe on balance our current versioning policy is less bad. It would cause more confusion if users need to track down a working major version each time they find a feature on the website that they would like to use. And it would cause untold headaches if large projects end up compiling a dozen separate versions of serde_derive from their various transitive dependencies.

Ultimately I would like to see Cargo handle this use case better. It comes up regularly in procedural macros that we need to constrain a version of a crate that our users depend upon but the macro does not.

I would also be happy to accept improvements to documentation that explains the serde and serde_derive versions should be kept in sync.
