### ISSUE TITLE
Support derive for types with const generics

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#1272]
This has not landed in nightly yet but is being tracked in https://github.com/rust-lang/rust/issues/44580.

It would be good to begin thinking about how to form the right trait bounds for such types.

```rust
#[macro_use]
extern crate serde_derive;

#[derive(Serialize, Deserialize)]
struct S<T, const N: usize> {
    array: [T; N],
}
```

**Comment by JulianKnodt** [comment]
Hi, I hope it's ok that I'm commenting on an older thread, but I was wondering if this was being revisited now that const-generics are available on nightly?

The main use case for const-generics would probably be in numerical applications, so I can see the main use case serving a similar role to numpy's .npy or .npz format.

**Comment by vadixidav** [comment]
I second this as I would like to switch the `hnsw` crate to const generics in preparation for its stabilization. Having a feature that enabled those impls would be beneficial. Alternatively, serde could automatically detect if it is on a compatible nightly rust version using [select-rustc](https://crates.io/crates/select-rustc) and enable the const generics impls in that case.

**Comment by TehPers** [comment]
Const generics are stable now, is there any interest in re-opening this?

**Comment by Kromey** [comment]
Const generics have landed in stable now, and as I noted in the above linked issue I cannot currently derive Serde traits because I use this feature. While I can probably work around it via the `try_from` and `into` attributes, having the ability to derive them instead would greatly simplify the task.

**Comment by TehPers** [comment]
I believe this issue was reopened in #1937. I'm also looking forward to this being implemented in the future.
