### ISSUE TITLE
Differences between the Playground and locally compiled

### ISSUE THREAD

**Issue by hgrecco** [serde-rs/serde#1277]
I am consuming a json service in which certain value are `{}` if an error occurs. In order to deserialize this with SerDe  I created the following helping types:

```rust
#[derive(Serialize, Deserialize)]
pub struct Empty {
}

#[derive(Serialize, Deserialize)]
#[serde(untagged)]
pub enum Maybe<T> {
    Invalid(Empty),
    Valid(T),
}
```

I tested this in the playground and it worked like a charm. However, when I tried to compile it locally in my computer (serde 1.0.56, serde_derive 1.0.56, serde_json 1.0.17) deserialization did not work properly. Basically, everything was deserialized as `Maybe::Invalid`. I finally realized that it was matching first the Invalid and not trying to match valid. Inverting the order fixed (and it makes sense to me).

```rust
#[derive(Serialize, Deserialize)]
#[serde(untagged)]
pub enum Maybe<T> {
    Valid(T),
    Invalid(Empty),
}
```

What bothers me is the difference between the playground (I do not know the serde version there). Because I am afraid that future versions might brake this. Any hint?

**Comment by hcpl** [comment]
When you type `extern crate ` in the playground's editor, it drops a hint/tooltip with a list of crates that match the name you typed after `extern crate `. As you can see, the current `serde` available there is 1.0.55.

![](https://i.imgur.com/4xYH20g.jpg)
