### ISSUE TITLE
Updating to v1.0.62 cause to error "128-bit type is unstable"

### ISSUE THREAD

**Issue by MaxGraey** [serde-rs/serde#1291]
_Compiler:_ 1.28.0-nightly (990d8aa74 2018-05-25)

That happening with any package which depend on serde.

```rust
error[E0658]: 128-bit type is unstable (see issue #35118)
   --> <user>/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.62/src/de/value.rs:242:29
    |
242 |     primitive_deserializer!(i128, "an `i128`.", I128Deserializer, visit_i128);
    |                             ^^^^
    |
    = help: add #![feature(i128_type)] to the crate attributes to enable

error[E0658]: 128-bit type is unstable (see issue #35118)
   --> <user>/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.62/src/de/value.rs:243:29
    |
243 |     primitive_deserializer!(u128, "a `u128`.", U128Deserializer, visit_u128);
    |                             ^^^^
    |
    = help: add #![feature(i128_type)] to the crate attributes to enable

...
```

**Comment by dtolnay** [comment]
Those types are definitely stable in 1.28.0-nightly. They were stabilized back in 1.26.0. Announcement: https://blog.rust-lang.org/2018/05/10/Rust-1.26.html#128-bit-integers. Could you double check what compiler version you are building with?

**Comment by dtolnay** [comment]
A nightly from 2018-03-04 is quite old. The expectation when using nightlies is that you update the compiler every night. Rarely do crates support old nightlies.

Can you give it a try with the most recent nightly?

**Comment by hcpl** [comment]
> ```
> rustc --version
> rustc 1.26.0-nightly (259e4a678 2018-03-04)
> ```

They were stabilized on March 27th: https://github.com/rust-lang/rust/pull/49101#event-1541888052.

**Comment by MaxGraey** [comment]
@dtolnay Hmm, It pretty strange:
In my project directory:
```
rustup run nightly rustc --version
rustc 1.28.0-nightly (990d8aa74 2018-05-25)
```
But command
```
rustc --version
rustc 1.26.0-nightly (259e4a678 2018-03-04)
```
In other directories I got `rustc 1.28.0-nightly (990d8aa74 2018-05-25)`

Sorry for may stupid questions. I'm not advanced user of rust and its toolchain

**Comment by dtolnay** [comment]
I would recommend hopping into the #rust IRC channel on irc.mozilla.org and asking for help removing the old nightly. They are pretty good at sorting this stuff out.

**Comment by MaxGraey** [comment]
Thanks! 👍

**Comment by MaxGraey** [comment]
Ok, I found out by myself how this repair. Solution:
In current directory just run `rustup override unset`.
Anyway thank you for your patience :)
