### ISSUE TITLE
docs failed to render for 1.0.62

### ISSUE THREAD

**Issue by tcr** [serde-rs/serde#1294]
See <https://docs.rs/crate/serde/1.0.62>:

<img width="919" alt="image" src="https://user-images.githubusercontent.com/80639/40635341-8bd03afa-62c7-11e8-8bce-efa827a60fe1.png">

**Comment by dtolnay** [comment]
Thanks, I released 1.0.63 with a workaround until docs.rs picks up a newer compiler (https://github.com/onur/docs.rs/issues/23).
https://docs.rs/serde/1.0.63/serde/
