### ISSUE TITLE
Use auto traits to improve compile-time checking of internally tagged newtype variants

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#1308]
Internally tagged newtype variants containing a value other than a map or struct is an error at runtime:

```rust
#[derive(Serialize)]
#[serde(tag = "type")]
pub enum E {
    // There is no meaningful way to put `"type": "N"` *inside* of the serialized u64.
    N(u64),
}
```

@abonander's idea from #1307: bound the newtype variant data by an auto trait to catch the commonly mistaken cases (primitives, strings, etc).

```rust
// #[cfg(not(feature = "unstable"))]:
#[doc(hidden)]
pub trait InternallyTaggable {}
impl<T> InternallyTaggable for T {}

// #[cfg(feature = "unstable")]:
#[doc(hidden)]
pub auto trait InternallyTaggable {}
impl !InternallyTaggable for u64 {} // etc.
```

Tracking issue for auto traits: https://github.com/rust-lang/rust/issues/13231

**Comment by ahl** [comment]
@dtolnay why would this need to be an auto trait? Could serde simply **not** `impl` this tagging trait for scalar types and then the `Serialize` derive macro could either add that impl or not depending on the characteristics of the type to which it was applied?
