### ISSUE TITLE
A tuple with a single element is not a sequence.

### ISSUE THREAD

**Issue by yangby-cryptape** [serde-rs/serde#1309]
A tuple type with zero, two or more than two elements is sequence.
But a tuple with a single element is not.

It is an odd behavior.

```Rust
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct ZeroElemTuple();

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct OneElemTuple(usize);

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct TwoElemTuple(usize, usize);

/*
[] - ZeroElemTuple
1 - OneElemTuple(1)
[1,2] - TwoElemTuple(1, 2)
*/
```

For example, [click-me-go-to-play-rust](https://play.rust-lang.org/?gist=579a72353389484caeafa9cef8d6bd6b&version=nightly&mode=release).

I am writing a JSON-RPC crate for our project.

According to [JSON-RPC 2.0 Specification](https://www.jsonrpc.org/specification), I need zero element and one element tuple for `params` in [Request object](http://www.jsonrpc.org/specification#request_object).

IMO, one element tuple should be sequence, too.
Keep a uniform rule for the same kind of types.

Now, I have to write like this to solve it temporarily:
```rust
#[derive(Debug, Clone, PartialEq)]
pub struct OneItemTupleTrick {}

impl Default for OneItemTupleTrick {
    fn default() -> Self {
        OneItemTupleTrick {}
    }
}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
pub struct MyParams(#[serde(skip)]OneItemTupleTrick, usize);
```

Reference:
- [Closed-Issue: Enum-Tuple-Variant with single element should not be a sequence](https://github.com/serde-rs/serde/issues/104)
- [Merged PR: tuple enums with single element should not be a json-array](https://github.com/serde-rs/serde/pull/111)

**Comment by Arnavion** [comment]
`pub struct OneElemTuple(usize);` is more commonly a newtype.

If you want a one-element array, you can have `pub struct OneElemTuple([usize; 1]);`

**Comment by yangby-cryptape** [comment]
Thanks for reply.
I'm just confused about those expressions, they have a same pattern but different representations.

**Comment by dtolnay** [comment]
I believe the current behavior around newtype structs is more commonly what people want.

Canonical Serialize and Deserialize impls for representing a newtype struct as an array of size 1 would look like this:

```rust
extern crate serde;
use serde::{Serialize, Deserialize, Serializer, Deserializer};

#[derive(Debug)]
struct MyParams(usize);

impl Serialize for MyParams {
    fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        [&self.0].serialize(serializer)
    }
}

impl<'de> Deserialize<'de> for MyParams {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        <[_; 1]>::deserialize(deserializer).map(|array| MyParams(array[0]))
    }
}
```

**Comment by hazae41** [comment]
Is there a way to force prevent this? using a `#[serde(...)]` or something?
