### ISSUE TITLE
Conditionally enabling tagged enums for non "self-describing" (de)serializers.

### ISSUE THREAD

**Issue by AGausmann** [serde-rs/serde#1310]
Consider the following `enum` declaration which I am using for dynamic typing:

```rust
#[derive(Serialize, Deserialize)]
pub enum Property {
    Boolean(bool),
    Integer(i64),
    Number(f64),
    Text(String),
}
```

This is used in many places in my program, usually within a `Properties` struct which encapsulates a `String` -> `Property` map. I have implemented `Serialize` and `Deserialize` for `Properties` which simply delegates to its inner map. The rest of `Properties` implementation is irrelevant at this time, but I can add it later if needed.

Here are two scenarios where `Properties` is commonly used:

1. **Small configuration or metadata files.** Human-readable and human-editable formats like JSON or TOML would be nice in this scenario. In such formats, using tagged enums would make this less human-friendly and a bit redundant, as each enum variant can get unambiguously (de)serialized as its inner value if I'm using the formats I've previously noted, since they both can reasonably support `Deserializer::deserialize_any`. I can provide my own implementation to convert most types to one of those variants, or even potentially use `#[serde(untagged)]`, though I don't think it will automatically cast other integer/float layouts and would therefore not work in my situation.

2. **Files containing massive arrays where each element contains a `Properties` map.** Since the most reasonable way for users to interact with the elements in the array is through a specialized program, I would like to be space-efficient by serializing these arrays using `Bincode` or another compact binary format. Many of the most efficient binary formats do not support `deserialize_any` because they aren't "self-describing" (the term used in `deserialize_any` documentation); they assume you know the structure of the data, and I do... for the most part. In this scenario, tags are necessary; untagged enums would fail because they don't sufficiently describe their contents. 

Currently, I can not provide a single implementation of `Serialize` and `Deserialize` to cover both cases in the way that I have described, as it is impossible for the traits' functions to determine whether tags are necessary for the given format.

This has implications for situations other than mine. Right now, if you serialize an untagged enum using Bincode, it will actually write the enum values without a tag. Once you try to deserialize it, it won't know what to do because it can't support `deserialize_any`. While this could be written off as a logic error by the user of the library who should know better, this is a reasonable thing that could happen to an unsuspecting user who may not actually know what went wrong.

Now that the problems are documented, here's my potential solution. Take advantage of Rust's strong typing. Deprecate `Deserializer::deserialize_any` and move the function to its own trait which is a child of `Deserializer`. Instead of having to document the fact that it may be unsupported by some deserializers, make the Rust compiler enforce that it is not accidentally called by an unsuspecting user. Add a second method to to `Deserialize` and `Serialize` to handle cases where `deserialize_any` is (or will be) available, with a default implementation that calls the regular function, with the new `Deserialize` function of course accepting the new deserializer trait.

In the particular situation of using the `#[serde(untagged)]` attribute, it would only affect the new functions that indicate that `deserialize_any` would be available, making sure tags are still used in other cases.

**Comment by oli-obk** [comment]
For deserialization you could run `deserialize_any` and if that fails, do the other deserialization. I don't think serialization allows similar tricks though.

We could add something in the spirit of `is_human_readable`. A `is_self_describing` method that has a reasonable default (`false`)  seems totally doable.

**Comment by AGausmann** [comment]
@oli-obk I was aware of the first option you suggest, but I didn't think that was reliable enough. Once a deserializer returns an error, some of them may assume (reasonably) that you're done. You're going to propagate that error and they won't have to properly put back the data they just tried to parse, which means your next deserialize may not be operating on the data that it should. It feels a lot like a hack, and like you say, this doesn't solve the problem for serialization.

Your second suggestion was somewhere along the lines of the idea that I had while writing this. It would work, but taking advantage of the right language features would definitely lead to better design. Adding a method to tell you whether a method is available does exactly the same thing as making a trait to tell you whether a method is available, but it is handled at run-time instead of compile-time.

**Comment by AGausmann** [comment]
Except for the behavior change that I proposed for `#[serde(untagged)]`, I'm not aware of how this could break any existing usages. To me it seems like anything still using the old interface would still compile and run normally as long as that deprecated method exists, so a major version bump wouldn't be required.

**Comment by dtolnay** [comment]
Thanks for the issue. Data structures that behave differently across different formats is something Serde's design has never supported well. Would you be interested in prototyping your suggestion with an any-deserializable separate trait in a PR?

**Comment by AGausmann** [comment]
Sure, it'll be my first time going through the serde source, but I think I can put something together.

**Comment by AGausmann** [comment]
It's been a while and I've been focusing on other things, but I'd eventually like to solve this problem. I don't think this is the right way to do it at this time, and I have another idea. Since this issue is specific to the way enums are (de)serialized, formats should be able to override the serialization method used, for example, if they require enums to be tagged. 

A quick and dirty way would be to make an attribute for such formats to set, but the default provided schemes aren't efficient in many formats (bincode would be a lot better if integer tags can be used). For future portability, the best solution would be to add a provided method, `serialize_enum`, to `Serializer`, which would default to the implementation we currently have. The issue (which I suspect is the reason why we can only derive for enums) is that they can't know about all of the variants at runtime, much less access the internal ordinals or assign a unique key to each one.

**Comment by AGausmann** [comment]
Perhaps there is a way to do that with procedural macros, but that would mean `derive`ing another thing to use enum serialization.

**Comment by AGausmann** [comment]
I think i've been overthinking this a bit too much - I'm going to try to come up with a better solution and propose it later.

**Comment by srithon** [comment]
@agausmann

Sorry to rehash a 3 year-old (closed) issue, but I'm currently running into the exact same problem and from what I've seen there are no documented solutions.

I have an enum that has to be deserialized from TOML for user configuration and also serialized/deserialized using Bincode internally. When I add internal tagging to the enum, Bincode _deserialization_ fails at runtime with the error `Bincode does not support the serde::Deserializer::deserialize_any method`. If I remove internal tagging, I can't use it with TOML.

```rust
#[derive(Serialize, Deserialize, Debug, Clone)]
// #[serde(tag = "type")]
// ^^ need this to (de)serialize the "Specified" variant for TOML
// ... all other ones work by default
pub enum Foo {
    Specified { string_field: String },
    Active,
    All
}
```

This is a table with all the interactions.

|                         | internal tagging | no internal tagging |
| ---                     | ---              | ---                 |
| toml serialization      | yes              | no                  |
| toml deserialization    | yes              | no                  |
| bincode serialization   | yes              | yes                 |
| bincode deserialization | no               | yes                 |

The only "solution" I could think of was duplicating the enum, using internal tagging on one and not the other, and then using `mem::transmute` to convert it into the original type. However, this wouldn't actually work since the stored tag would change the memory layout of the object.

I'm at a loss for other solutions, and would like to avoid writing any custom deserialization code if possible.

Did you end up finding a reasonable solution for your problem?

Thanks

**Comment by srithon** [comment]
> @srithon I would definitely avoid using `transmute`, but if it's trival to convert between the two enums, then I would recommend writing `From` impls in both directions as a safer (albeit more verbose) alternative.

Thanks for the advice! I found [this](https://gitlab.com/mexus/fields-converter/) crate that lets you auto-impl the `From` trait between two structs/enums, and now the code looks like this:

```rust
// NOTE KEEP THESE ENUMS IN SYNC
#[derive(Serialize, Deserialize, Debug, Clone)]
pub enum Foo {
    Specified { string_field: String },
    Active,
    All
}

// NOTE KEEP THESE ENUMS IN SYNC
#[derive(Serialize, Deserialize, Debug, Clone, MoveFields)]
#[destinations("Foo")]
#[serde(tag = "type")]
pub enum FooTOMLCompatible {
    Specified { string_field: String },
    Active,
    All
}
```

The crate also allows you to duplicate the definition with a different name, but unfortunately there was no way to give the duplicate public visibility so I couldn't use it.

The default `Foo` value had to be read into a `Config` struct, so I made this function:
```rust
pub fn parse_default_foo<'de, D>(input: D) -> Result<Foo, D::Error> where D: serde::Deserializer<'de> {
    let foo_toml: FooTOMLCompatible = Deserialize::deserialize(input)?;
    Ok(foo_toml.into())
}
```
and put this in the config struct
```rust
#[derive(Serialize, Deserialize)]
struct Config {
  ...
  #[serde(deserialize_with = "parse_default_foo")]
  pub default_foo: Foo
}
```
