### ISSUE TITLE
wasm-bindgen broken from proc-macro2/serde

### ISSUE THREAD

**Issue by david-yan** [serde-rs/serde#1315]
Hi, I'm not sure if this is an issue with proc-macro2 or serde but there is a bug that is causing the build for wasm-bindgen to break:
rustwasm/wasm-bindgen#263

**Comment by dtolnay** [comment]
Until we know what happened let's keep the discussion in one place: https://github.com/rustwasm/wasm-bindgen/issues/263. Thanks!
