### ISSUE TITLE
Flatten newtype variant

### ISSUE THREAD

**Issue by CAD97** [serde-rs/serde#1321]
For the following pattern:

```rust
pub enum Expression {
    Identifier(Identifier),
    IntegerLiteral(IntegerLiteral),
    ..
}

pub struct Identifier { .. }
pub struct IntegerLiteral { .. }
```

I'd like to be able to de/serialize this pattern as if it were

```rust
pub enum Expression {
    Identifier { .. },
    IntegerLiteral { .. },
    ..
}
```

What's the reasoning between the current prohibition for flattening here?

```
error: #[serde(flatten)] cannot be used on newtype structs
 --> parser\src\ast\expressions.rs:9:10
  |
9 | #[derive(Serialize)]
  |          ^^^^^^^^^
```

Regular flattening already moves the child keys into the parent, so this feels like an artificial restriction. I don't see why this is restricted even in the case of normal newtypes rather than newtype variants.

**Comment by dtolnay** [comment]
> I'd like to be able to de/serialize this pattern as if it were

Those are already serialized the same in most formats ([playground](https://play.rust-lang.org/?gist=e5d6d0bbfe1fc9d589137f939a1451fa)). Are you using one of the formats in which they are represented differently?

**Comment by CAD97** [comment]
I guess I am with [ron](https://github.com/ron-rs/ron). By default newtypes aren't inlined in RON, so this comes out as

```ron
Identifier((s:"S",))
Identifier(s:"S",)
```

There is a setting for unwrapping newtypes which I can use. The purist in me would prefer to flatten in the serde model as well though 😛 and since this serialization is actually just for a nice textual display rather than deserialization I'd then have to strip the marker of the unwrapped newtypes as well.

**Comment by dtolnay** [comment]
I don't know much about RON but the following should be suitable for textual display. You could also make a feature request to them to support the unwrapped newtypes setting for serialization.

---

```rust
#[macro_use]
extern crate serde_derive;

extern crate ron;
extern crate serde;

use ron::ser::PrettyConfig;
use serde::Serialize;

#[derive(Serialize)]
struct Identifier {
    identifier: bool,
}

#[derive(Serialize)]
struct IntegerLiteral {
    integer_literal: bool,
}

#[derive(Serialize)]
#[serde(untagged)]
enum Expression {
    Identifier(Identifier),
    IntegerLiteral(IntegerLiteral),
}

fn main() {
    let expr = Expression::Identifier(Identifier { identifier: true });

    let pretty = PrettyConfig::default();
    let struct_names = true;
    let mut ser = ron::ser::Serializer::new(Some(pretty), struct_names);
    expr.serialize(&mut ser).unwrap();
    println!("{}", ser.into_output_string());
}
```

**Comment by CAD97** [comment]
Given the default suggested behavior of treating newtypes as transparent, I'll consider this closed.

I just got a stewing idea for `#[serde(transparent)]` though, so I might flush that out a bit and suggest it.
