### ISSUE TITLE
proc-macro derive panicked on enum with discriminant

### ISSUE THREAD

**Issue by andrewhickman** [serde-rs/serde#1329]
Slightly contrived MWE:
```
struct Baz {
    val: u8,
}

const VALUE: Baz = Baz { val: 1 };

#[repr(u8)]
#[derive(Deserialize)]
enum Foo {
    Bar = VALUE.val,
}
```
This fails to compile with
```
proc-macro derive panicked

help: message: called `Result::unwrap()` on an `Err` value: ParseError(Some("failed to parse derive input: failed to parse"))
```

**Comment by dtolnay** [comment]
Thanks, I released syn 0.14.3 with a fix. We limit what expressions are allowed in discriminants to save time in compiling the parser, but `VALUE.val` seems common enough and easy to parse that we can allow it.
