### ISSUE TITLE
implement From<io::Error> for serde::Error

### ISSUE THREAD

**Issue by droundy** [serde-rs/serde#1342]
Would it be acceptable to implement From<io::Error> for serde::Error? This would make it easier to combine serde with reading or writing of values, something like:
```
fn read(value: f6, p: &Path) -> Result<f64, serde::Error> {
        let mut f = ::std::fs::File::create(p)?;
        serde_yaml::to_writer(&f, value)
}
```
I know there are crates to enable combining of error types, but for my use case that seems excessive, when a simple `impl` in serde would remove the need for such.

**Comment by dtolnay** [comment]
There is no such thing as `serde::Error`. There are `serde::ser::Error` and `serde::de::Error` but those are traits.

**Comment by droundy** [comment]
My mistake.  I was encountering a `serde_yaml::Error` and failed to note the yaml portion.
