### ISSUE TITLE
Add a #[serde(root = "<something>")] for deserializing Structs under alternate root names

### ISSUE THREAD

**Issue by balajisivaraman** [serde-rs/serde#1345]
I'm not sure if this feature already exists in SerDe, but I couldn't find it after scouring the [Container Attributes](https://serde.rs/container-attrs.html) page and all the provided [examples](https://serde.rs/examples.html) in the docs. So my apologies if I have overlooked something.

I also wasn't sure whether this issue should go in this crate or the JSON crate, but since this crate houses all the SerDe attributes, I thought this would be a better place for it.

This is my use-case. I'm working on implementing the RealWorld Backend API in Rust. The contract for [User registration](https://github.com/gothinkster/realworld/tree/master/api#registration) is this:
```
{
  "user":{
    "username": "Jacob",
    "email": "jake@jake.jake",
    "password": "jakejake"
  }
}
```

This can easily be represented in a Rust struct like this:
```
#[derive(Debug, Deserialize)]
struct RegisterParam {
    username: String,
    email: String,
    password: String,
}
```

Unfortunately, this deserializes only the following:
```
{
  "username": "Jacob",
  "email": "jake@jake.jake",
  "password": "jakejake"
}
```

To deserialize the original contract, we'd have to wrap the RegisterParam struct in another struct unnecessarily. This is what is done in the current Rust [implementation](https://github.com/gothinkster/rust-realworld-example-app/blob/master/src/main.rs#L191) of the RealWorld API.

My suggestion is to allow for something like the following, similar to what Spring provides with its `JsonRootName` annotation, as can be seen [here](https://github.com/gothinkster/spring-boot-realworld-example-app/blob/master/src/main/java/io/spring/api/UsersApi.java#L115).
```
#[derive(Debug, Deserialize)]
#[serde(root = "user")]
struct RegisterParam {
    username: String,
    email: String,
    password: String,
}
```

If this suggestion looks OK, I can even offer to work on implementing this feature.

Thanks in advance.

**Comment by dtolnay** [comment]
I would prefer for this to live in an external crate to begin with, to get some experience with this pattern and evaluate whether it really results in code that is easier to maintain than having one struct per level of nesting in the input.

A possible thirdparty implementation:

```rust
#[doc(hidden)]
pub extern crate serde;

#[doc(hidden)]
pub extern crate core;

#[macro_export]
macro_rules! deserialize_root {
    ($root:ident : $inner:ty) => {
        impl<'de> $crate::serde::Deserialize<'de> for $inner {
            fn deserialize<D>(deserializer: D) -> $crate::core::result::Result<Self, D::Error>
            where
                D: $crate::serde::Deserializer<'de>,
            {
                type Inner = $inner;
                #[derive(Deserialize)]
                struct Wrapper { #[serde(with = "Inner")] $root: Inner }
                Wrapper::deserialize(deserializer).map(|w| w.$root)
            }
        }
    }
}
```

Used as:

```rust
#[derive(Debug, Deserialize)]
#[serde(remote = "Self")]
struct RegisterParam {
    username: String,
    email: String,
    password: String,
}

deserialize_root!(user: RegisterParam);
```

**Comment by balajisivaraman** [comment]
@dtolnay, I agree with your assessment that this can be a separate crate for now. I'll get started on it. 👍

**Comment by balajisivaraman** [comment]
Thanks to @dtolnay's initial implementation, I was able to publish this crate: https://crates.io/crates/serde_struct_wrapper.

I'm closing this issue for now.

**Comment by inferiorhumanorgans** [comment]
This would be a nice feature to have, IMO. As-is it appears the serde_struct_wrapper doesn't seem to compile with Serde 1.0 and it doesn't seem to work with enums that require explicit lifetimes.
