### ISSUE TITLE
Illegal instruction when building Serde

### ISSUE THREAD

**Issue by Cocalus** [serde-rs/serde#1351]
Looks like the serde build script has incorrect CPU feature detection

error: failed to run custom build command for `serde v1.0.70`
process didn't exit successfully: `*removed*/target/release/build/serde-dfa7cb620ca16fdd/build-script-build` (signal: 4, SIGILL: illegal instruction)

This is on a VM machine that doesn't expose all the CPU flags of the underlying hardware. See a piece of /proc/cpuinfo below. For example this CPU has AVX2 but that's not listed in flags. I don't know which instruction it's failing on (maybe if I could run it through gdb). I have some simd code using is is_x86_feature_detected!("avx2") and that correctly returns false here. 

processor	: 11
vendor_id	: GenuineIntel
cpu family	: 6
model		: 45
model name	: Intel(R) Xeon(R) CPU E5-2690 0 @ 2.90GHz
stepping	: 7
microcode	: 0x710
cpu MHz		: 2899.999
cache size	: 20480 KB
physical id	: 22
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 22
initial apicid	: 22
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts nopl xtopology tsc_reliable nonstop_tsc aperfmperf pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt aes xsave avx hypervisor lahf_lm dtherm ida arat pln pts
bugs		:
bogomips	: 5799.99
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management:

**Comment by dtolnay** [comment]
Thanks! I am closing the issue because this is something you will need to debug in your environment. I don't think there is anything I will be able to do to track down what happened. Please send a PR if you figure it out and it turned out to be something that can be fixed in our build script.

**Comment by dtolnay** [comment]
I was able to run the build script like this and see the expected output:

```console
$ git clone https://github.com/serde-rs/serde
$ cd serde
$ cargo build --release --manifest-path serde/Cargo.toml || true
$ RUSTC=$(rustup which rustc) target/release/build/serde-*/build-script-build
cargo:rustc-cfg=de_boxed_c_str
cargo:rustc-cfg=de_rc_dst
cargo:rustc-cfg=core_duration
cargo:rustc-cfg=integer128
cargo:rustc-cfg=range_inclusive
cargo:rustc-cfg=num_nonzero
```

**Comment by Cocalus** [comment]
My apologies looks like this just got fixed in v1.0.71 or something else when I did a cargo update.

**Comment by Cocalus** [comment]
And now it doesn't work again. I'll poke at it some more.

**Comment by Cocalus** [comment]
Only happens when I build the things with a serde dependency with --release. Doesn't happen when building serde. 

When running the build-script-build from my project built with --release the call stack is

#0  0x000055555555c251 in build_script_build::main::hcdf322470e8fe057 ()
#1  0x000055555555b333 in std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::h38e3e82b68aece01 ()
#2  0x0000555555561933 in std::rt::lang_start_internal::_$u7b$$u7b$closure$u7d$$u7d$::h664d976655ba006f ()
    at libstd/rt.rs:59
#3  std::panicking::try::do_call::hac56dcc01f36ef70 () at libstd/panicking.rs:310
#4  0x000055555557e56a in __rust_maybe_catch_panic () at libpanic_unwind/lib.rs:105
#5  0x000055555555d226 in std::panicking::try::hcda2c11533bcd35b () at libstd/panicking.rs:289
#6  std::panic::catch_unwind::h28820092503d86ef () at libstd/panic.rs:392
#7  std::rt::lang_start_internal::h249c3823b1cd2120 () at libstd/rt.rs:58
#8  0x000055555555c404 in main ()

The instruction there is 
andn   %r14d,%ebp,%ebp
Which is a BMI1 instruction (haswell+) and not available on this older CPU.

**Comment by Cocalus** [comment]
I found the issue it was my faultm I had a .cargo/config forcing Haswell compilation.
