### ISSUE TITLE
Please add support for NonZeroU128

### ISSUE THREAD

**Issue by Lokathor** [serde-rs/serde#1352]
It seems that [NonZeroU128](https://doc.rust-lang.org/std/num/struct.NonZeroU128.html) isn't supported, even though `NonZeroU64` is.

**Comment by pickfire** [comment]
@Lokathor Maybe it might be useful to check https://github.com/serde-rs/serde/issues/1136, serde support for rustc minimum version 1.13+ does not have 128 bits integer.

**Comment by Lokathor** [comment]
Yeah, seems they used a special build setup that detects the minimum rustc version and then throws in the extra impl if rustc is high enough version. I guess the same could be done for this type as well.
