### ISSUE TITLE
How to deserialize into enums without failing with 'unknown variant'?

### ISSUE THREAD

**Issue by nicokosi** [serde-rs/serde#1353]
I currently use `serde_json` for a side project in order to parse [GitHub `events` API](https://developer.github.com/v3/activity/events/)'s output.

The GitHub `events` API returns many [event actions](https://developer.github.com/v3/activity/events/types/), such as:
> created
> rerequested
> requested_action
etc.

I am trying to use [serde_json::from_str](https://github.com/nicokosi/pullpito/blob/issue_22_unknown_variant/src/github_events/mod.rs#L101) to parse events for [a subset of event actions](https://github.com/nicokosi/pullpito/blob/issue_22_unknown_variant/src/github_events/mod.rs#L140). I have tried the workaround from issue https://github.com/serde-rs/serde/issues/912#issuecomment-379032835
```rust
#[derive(Debug, Deserialize, Eq, PartialEq)]
pub enum Action {
    #[allow(non_camel_case_types)]
    created,
    #[allow(non_camel_case_types)]
    closed,
    #[allow(non_camel_case_types)]
    opened,
    #[allow(non_camel_case_types)]
    #[serde(skip_deserializing)]
    unknown,
}
use serde::Deserialize;
fn deserialize_field_action<'de, D>(deserializer: D) -> Result<Action, D::Error>
    where
        D: Deserializer<'de>,
{
    Ok(Action::deserialize(deserializer).unwrap_or(Action::unknown))
}
```
But it visibly does not work:
```
$ cargo run --quiet -- --repository nicokosi/pullpito

thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: StringError("Cannot deserialize GitHub API content: missing field `action` at line 1 column 2339") }', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
See the [code diff](https://github.com/nicokosi/pullpito/pull/23/files).

Any idea/recommendation? Thanks in advance.

**Comment by dtolnay** [comment]
> `Cannot deserialize GitHub API content: missing field `action` at line 1 column 2339`

This means that not every `"payload"` has an `"action"`. Check out https://serde.rs/attr-default.html for some ways to provide a default value when there is no action.

**Comment by nicokosi** [comment]
Thank you @dtolnay! I now use default values: https://github.com/nicokosi/pullpito/commits/issue_22_unknown_variant. 🎉 
I close this issue.
