### ISSUE TITLE
Stop deserialization under special circumstances without picking other defaults

### ISSUE THREAD

**Issue by whimboo** [serde-rs/serde#1355]
I have an enum which contains a value wrapped into lets say a `spec` object in the JSON string. If this wrapper has an invalid value eg. `null` the deserialization has to fail. But if `spec` is not present in the JSON string, the alternative enum value should be used for deserialization.

Here is an example which demonstrates the problem:
https://play.rust-lang.org/?gist=9c4ae24726f1052f8bdbcb8892d1fe87&version=stable&mode=debug&edition=2015

I don't know how to get this working so I would appreciate some help.

Thanks!

**Comment by dtolnay** [comment]
"If it has a spec, deserialize the spec, otherwise deserialize as legacy" would be written like this.

```rust
impl<'de> Deserialize<'de> for Parameters {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let value = serde_json::Value::deserialize(deserializer)?;
        if let Some(spec) = value.get("spec") {
            let spec = SpecParameters::deserialize(spec).map_err(de::Error::custom)?;
            return Ok(Parameters::Spec(spec));
        }
        let legacy = LegacyParameters::deserialize(value).map_err(de::Error::custom)?;
        Ok(Parameters::Legacy(legacy))
    }
}
```

[Playground](https://play.rust-lang.org/?gist=9cc1a3166b85f3c2d110e2dce3e66807&version=nightly&mode=debug&edition=2015)

**Comment by whimboo** [comment]
This works like a charm. Looks like that for special cases like this someone can always fallback to deserialize to `Value` first, and then do custom processing. I will remember that.

@dtolnay, thanks a lot! I think we can close this issue now.
