### ISSUE TITLE
Deserializing Vega graphs containing different object types in an array

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#1364]
#### Moved from https://github.com/serde-rs/serde/issues/672#issuecomment-415269953.

---

@dtolnay Unsure if this is entirely related, but I'm working on deserializing JSON data ([Vega graphs](https://vega.github.io/vega/docs/specification/)) where a value may be an array or an object (signal reference or data reference) representing different object types.

Here's a valid example:

``` json
"scales" [
  {
    "domain": [1, 2, 3]
  },
  {
    "domain": {"data": "domain_data", "field": "some_field_name"}
  },
  {
    "domain": {"signal": "height / 3"}
  }
]
```

Which I'd like to represent with a Rust enum like so:
``` rust
struct DataRef {
  data: String,
  field: String, // Or potentially a Field struct representing the input/output pair
}

struct SignalRef {
  name: String
}

enum Domain {
  List(Vec<f64>),
  Data(DataRef),
  Signal(SignalRef),
}
```

My thought process was that the logical approach would be to have the Domain map visitor pass the value to an appropriate deserializer, but I'm not quite sure how to accomplish that.  An alternative is to have the deserializer try each possibility in order, but this is not doable by design (per your comment).

Thoughts?

**Comment by dtolnay** [comment]
@inferiorhumanorgans this looks like an [untagged enum](https://serde.rs/enum-representations.html#untagged).

```rust
#[macro_use]
extern crate serde_derive;

extern crate serde;
extern crate serde_json;

#[derive(Deserialize, Debug)]
struct Graph {
    scales: Vec<Scale>,
}

#[derive(Deserialize, Debug)]
struct Scale {
    domain: Domain,
}

#[derive(Deserialize, Debug)]
#[serde(untagged)]
enum Domain {
    List(Vec<f64>),
    Data(DataRef),
    Signal(SignalRef),
}

#[derive(Deserialize, Debug)]
struct DataRef {
    data: String,
    field: String,
}

#[derive(Deserialize, Debug)]
struct SignalRef {
    signal: String,
}

fn main() {
    let j = r#"
        {
          "scales": [
            {
              "domain": [1, 2, 3]
            },
            {
              "domain": {"data": "domain_data", "field": "some_field_name"}
            },
            {
              "domain": {"signal": "height / 3"}
            }
          ]
        }"#;
    println!("{:#?}", serde_json::from_str::<Graph>(j).unwrap());
}
```

**Comment by inferiorhumanorgans** [comment]
Yep.  I ended up reading through the documentation after I posted my question.  Thanks!
