### ISSUE TITLE
Suggestion: `serialize_with`, `deserialize_with` and `with` but taking conversion functions as args

### ISSUE THREAD

**Issue by Boscop** [serde-rs/serde#1368]
Custom impls of `Serialize`/`Deserialize` require too much code if only one member needs to have a different repr type.

There are `serialize_with`, `deserialize_with` and `with` but they also require more code than should be necessary in most<sup>[*](#footnote)</sup> cases.

I wish there were versions of `serialize_with`, `deserialize_with` and `with` but taking conversion functions as args that convert from the orig type to another type that is its serialized repr.

I've been using this macro:
```rust
/// serializes a type as a different repr type that it can be converted Into and From
#[macro_export]
macro_rules! serde_as {
	($m:ident, $t:ty, $r:ty) => {
		pub mod $m {
			use serde::{Serialize, Serializer, Deserialize, Deserializer};
			use super::*;

			pub fn serialize<S: Serializer>(x: &$t, serializer: S) -> Result<S::Ok, S::Error> {
				let y: $r = (*x).into();
				y.serialize(serializer)
			}

			pub fn deserialize<'de, D: Deserializer<'de>>(deserializer: D) -> Result<$t, D::Error> {
				let y: $r = Deserialize::deserialize(deserializer)?;
				Ok(y.into())
			}
		}
	}
}
```

using it like:
```rust
serde_as!(serde_col, RGB<f32>, (f32, f32, f32));

#[derive(Serialize, Deserialize)]
struct Col(#[serde(with = "serde_col")] RGB<f32>); // RGB from the rgb crate
```

but it only works if there is a `Into` and `From` impl to convert between the type.

So I wrote a different macro:
```rust
/// serializes a type as a different repr type using the given conversion functions
#[macro_export]
macro_rules! serde_conv {
	($m:ident, $t:ty, $ser:expr, $de:expr) => {
		pub mod $m {
			use serde::{Serialize, Serializer, Deserialize, Deserializer};
			use super::*;

			pub fn serialize<S: Serializer>(x: &$t, serializer: S) -> Result<S::Ok, S::Error> {
				let y = $ser(*x);
				y.serialize(serializer)
			}

			pub fn deserialize<'de, D: Deserializer<'de>>(deserializer: D) -> Result<$t, D::Error> {
				let y = Deserialize::deserialize(deserializer)?;
				Ok($de(y))
			}
		}
	}
}
```

using it like:
```rust
serde_conv!(serde_js_timestamp, f64, |x: u64| x as _, |x: f64| x as _);

#[derive(Serialize, Deserialize)]
struct Position { // for Geolocation in wasm apps
	coords: Coordinates,
	#[serde(with = "serde_js_timestamp")]
	timestamp: u64, // if u64 is used directly, it causes: ConversionError { kind: Custom("invalid type: floating point 1535164942454, expected u64") }
}
```

which also works but I wish this functionality could be done with `serde_derive` attributes directly instead of requiring custom macros and invocations of them.

What do you think? :)

---

<a name="footnote">*</a> About 98% of all my needs for `serialize_with`, `deserialize_with` and `with` could be replaced by this.

**Comment by dtolnay** [comment]
I would prefer not to build more attributes into serde_derive to support serialize_with / deserialize_with but with conversion. Using macros to generate the serialize / deserialize functions is a neat idea and seems easy enough to use. Maybe you could publish these macros in a crate in case they are useful to others!
