### ISSUE TITLE
Defining a deserializer for chrono

### ISSUE THREAD

**Issue by savvopoulos** [serde-rs/serde#137]
Hi there,

Our json messages have a time field containing a well-formatted date.
Ideally, we would want to have struct { time: chrono::DateTime<chrono::UTC>, } automatically filled in.

Our first reaction was to do just that, and impl Deserializer for chrono::DateTime<UTC>. However, as far as I understand, only chrono's owner can define that deserializer (due to E0117: the impl does not reference any types defined in this crate; only traits defined in the current crate can be implemented for arbitrary types -- kinda lame).

Thoughts?

**Comment by oli-obk** [comment]
You can wrap the `UTC` type in a newtype, and impl Deserializer for that. (Or modify chrono?)

**Comment by dtolnay** [comment]
Chrono added this themselves in https://github.com/lifthrasiir/rust-chrono/pull/51.
