### ISSUE TITLE
Serde panics when flattening struct and Value

### ISSUE THREAD

**Issue by chrisduerr** [serde-rs/serde#1379]
When trying to deserialize a struct which contains another struct with the `#[serde(flatten)]` annotation and a field with the `#[serde(flatten)]` annotation and the type `toml::Value` (same with `serde_yaml` or `serde_json`), serde will panic.

A minimal example for reproducing this:
```rust
extern crate serde;
#[macro_use]
extern crate serde_derive;
extern crate toml;

#[derive(Debug, Deserialize)]
struct Test {
    text: Option<String>,
    #[serde(flatten)]
    settings: Settings,
    #[serde(flatten)]
    extra: toml::Value,
}

#[derive(Debug, Deserialize)]
struct Settings {
    width: Option<u8>,
}

fn main() {
    let file = "text = \"test\"\nwidth = 8";
    let test: Test = toml::from_str(file).unwrap();
}
```
[playground](https://play.rust-lang.org/?gist=b5fd8d4d24cd319f76c3fa439c36ca8d&version=stable&mode=debug&edition=2015)

This will result in the following error:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value'
```

**Comment by dtolnay** [comment]
Fixed in serde 1.0.78.
