### ISSUE TITLE
How do a setup a Unions?

### ISSUE THREAD

**Issue by Gilgamesh22** [serde-rs/serde#1386]
I have a JSON file in which the value of a variable can be a int, string or object. I was wondering how can I use Serde to define this. 

I used the word Union because I did not know what to call this.

**Comment by dtolnay** [comment]
In Rust this would be represented by an enum. https://doc.rust-lang.org/book/second-edition/ch06-01-defining-an-enum.html

```rust
#[derive(Deserialize)]
#[serde(untagged)]
enum Union {
    Int(i64),
    String(String),
    Object(BTreeMap<String, serde_json::Value>),
}
```

**Comment by dakom** [comment]
I realize this is a bit old - but what if it is a union in the typescript sense?

Is it possible for serde to sortof walk through the possibilities and deserialize to the right one?

For example the data could be this:

```json
{
  "label": "hello"
}
```

or this:

```json
{
  "label": "hello",
  header: true
}
```

and I'd like to deserialize to this:

```rust
#[derive(Deserialize)]
#[serde(untagged)]
enum Union {
    Text(Text),
    Header(Header),
}

#[derive(Deserialize)]
struct Text {
  label: String
}

#[derive(Deserialize)]
struct Header {
  label: String,
  header: bool
}
```

**Comment by jonasbb** [comment]
> Is it possible for serde to sortof walk through the possibilities and deserialize to the right one?

That is what how the code currently works. Quoting from the [documentation](https://serde.rs/enum-representations.html#untagged):

> There is no explicit tag identifying which variant the data contains. Serde will try to match the data against each variant in order and the first one that deserializes successfully is the one returned.
