### ISSUE TITLE
How to dissect on a unknow key?

### ISSUE THREAD

**Issue by Gilgamesh22** [serde-rs/serde#1387]
I have a JSON file format in which there can be dynamic generated keys at the root position. the name of each key is unique and is not know at dissect time. The value of each key is standardized.  I would like to deserialize the JSON so I can both deserialize the value and also keep the key. 

here is a very basic example
```
{
 item1: {
  value: 5
 },
 item99: {
  value: 1
 },
}
```

**Comment by dtolnay** [comment]
If the keys are strings and every value is the same type, I would recommend treating the data as a hash map. https://doc.rust-lang.org/std/collections/struct.HashMap.html

```rust
#[macro_use]
extern crate serde_derive;

extern crate serde;
extern crate serde_json;

use std::collections::HashMap;

#[derive(Deserialize, Debug)]
struct Item {
    value: u64,
}

fn main() -> serde_json::Result<()> {
    let j = r#"
        {
            "item1": { "value": 5 },
            "item99": { "value": 1 }
        }"#;

    let map: HashMap<String, Item> = serde_json::from_str(j)?;
    println!("hash map = {:#?}", map);

    Ok(())
}
```

**Comment by dsherret** [comment]
This is the first result on google, so I just wanted to point out that if you do not know the types of the values, then you can just specify `serde_json::Value` as the hashmap value type:

```rust
let key_values: HashMap<String, serde_json::Value> = serde_json::from_str(&text)?;
```
