### ISSUE TITLE
Forward-compatible Enum deserialization

### ISSUE THREAD

**Issue by tiras-j** [serde-rs/serde#1388]
For tagged enums it would be incredibly nice to have a mechanism for aliasing unknown enum variants to a specific "default" variant (and dropping content) instead of triggering an error. This would allow enums to be an incredibly flexible target for data-model evolution without breaking existing binaries/requiring hard versioning etc. I'm imaging something along these lines:

```rust
struct ModelA {
    a: String,
}

struct ModelB {
    a: String,
    b: u64,
}

#[derive(Deserialize, Serialize)]
#[serde(tag = "variant")]
#[serde(map_unknown = "UnknownVariant")]
enum SomeEnum {
    VariantA(ModelA),
    VariantB(ModelB),
    UnknownVariant,
}
```

This would allow `SomeEnum` to evolve however it needs without breaking any code doing deserialization, and said code would still be able to handle the subset of data models that it knows about. I've got working example that pulls in and slightly modifies the `TaggedContentVisitor` derivation to map unknown tag values to the "unknown" enum field variant and then produce that variant instead of proceeding with `ContentDeserializer` deserialization - but of course that means reaching into the `private` module which is definitely a bad idea. 

Are there existing solutions for this type of problem? If so I'd be happy to learn of them - but it seems to me that this would be a useful feature in general and likely not too difficult to implement. However I'm unsure if this would work for untagged Enums, as I don't think there'd be a way to distinguish between an "unknown" variant and a missing object altogether.

**Comment by dtolnay** [comment]
The attribute for this is `#[serde(other)]` on the variant (requires serde_derive 1.0.79).

```rust
#[derive(Deserialize)]
#[serde(tag = "variant")]
enum SomeEnum {
    VariantA(ModelA),
    VariantB(ModelB),

    #[serde(other)]
    UnknownVariant,
}
```

**Comment by tiras-j** [comment]
Fantastic! Thank you!
