### ISSUE TITLE
Trouble deserializing a tuple variant

### ISSUE THREAD

**Issue by hammerandtongs** [serde-rs/serde#1394]
Hello,

I think I've worked close to a solution for serialization and deserialization of  what I'd term a more complicated "adjacently tagged" enum.

I think the main difference from the tag/content variant attribute route is that the parent struct is complex and has other data besides the type in it and that I'm wrapping child structs in a tuple variant?

For the deserialization I've adopted a naive version of #1343 but it hasn't worked out :(

https://play.rust-lang.org/?gist=aecf3f940da04357f1b787b452b41f34&version=stable&mode=debug&edition=2015

Is what I have so far. Any help along the way is appreciated!

**Comment by dtolnay** [comment]
I would write this using a flattened adjacently tagged enum. I don't think the handwritten Serialize and Deserialize impls are necessary in this case.

```rust
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug)]
struct Foo {
    word: String,
}

#[derive(Serialize, Deserialize, Debug)]
struct Bar {
    number: i64,
}

#[derive(Serialize, Deserialize, Debug)]
#[serde(tag = "Msgtype", content = "Payload")]
enum Payload {
    Foo(Foo),
    Bar(Bar),
}

#[derive(Serialize, Deserialize, Debug)]
struct Message {
    #[serde(rename = "Otherinfo")]
    otherinfo: String,
    #[serde(flatten)]
    payload: Payload,
}

fn main() {
    for msg in &[
        r#"{"Msgtype":"Foo","Otherinfo":"oooka","Payload":{"word":"fooing"}}"#,
        r#"{"Msgtype":"Bar","Otherinfo":"oooka","Payload":{"number":34}}"#,
    ] {
        println!("{:?}", serde_json::from_str::<Message>(msg).unwrap());
    }
}
```

**Comment by gyzerok** [comment]
Hello @dtolnay!

Thanks for sharing this code sample! It made my day :)

However I've got still one problem: in my system extending `Payload` array with more elements is considered to be a non-breaking change. So during deserialization I would prefer to accept longer arrays and just throw away the reminder.

With the code you wrote I get trailing characters error in such cases. Can you help me modify it to address my case?
