### ISSUE TITLE
#[serde(skip)] in tuple enum variants silently ignored

### ISSUE THREAD

**Issue by CAD97** [serde-rs/serde#1396]
```rust
#[macro_use]
extern crate serde_derive; // 1.0.78
extern crate serde; // 1.0.78

struct S;

#[derive(Serialize)]
enum E {
    V(#[serde(skip)] S),
}

```

```
error[E0277]: the trait bound `S: serde::Serialize` is not satisfied
 --> src/lib.rs:7:10
  |
7 | #[derive(Serialize)]
  |          ^^^^^^^^^ the trait `serde::Serialize` is not implemented for `S`
  |
  = note: required by `serde::Serializer::serialize_newtype_variant`

error: aborting due to previous error
```

[Playground](https://play.rust-lang.org/?gist=52468306cc60f55fd62d11eba4a1ca45&version=stable&mode=debug&edition=2015)

The attribute should either work (thus serializing like `enum E { V() }` or give an error/warning that it has no meaning in this position.

**Comment by prasannavl** [comment]
Just ran into this today. Changing the variant into 
```rust
enum E { 
   V { #[serde(skip)] v: S } 
}
```
makes it work as expected. I think should just work instead of an error. This is likely a bug.

**Comment by eddyb** [comment]
This also applies to tuple structs (e.g. `struct Ignore(#[serde(skip)] Foo);`).

**Comment by hcpl** [comment]
Might be related to why `#[serde(default)]` is also ignored: https://github.com/serde-rs/serde/issues/1418.
