### ISSUE TITLE
#[serde(flatten)] attribute support for enum variants

### ISSUE THREAD

**Issue by srijs** [serde-rs/serde#1402]
Hi!

I have the following use-case for a feature similar to `#[serde(flatten)]`, but for enum variants rather than struct fields. Generally happy to dive into `serde_derive` myself in case you think this would be worth having, but it could also be that I'm trying to model this the wrong way.

I'm trying to parse JSON values in the [estree format](https://github.com/estree/estree). The format specifies an ECMAScript syntax tree using an inhertance relationship, where generally only the nodes at the bottom of the hierarchy are tagged.

For example, one type of node is `Expression`, but there doesn't exist any node with the "Expression" tag, because the tag is assigned to the "concrete" expression nodes such as `Identifier` or `Literal`. The representation of the `Expression` node is basically just a union of all possible JSON representations of its descendant node types.

So far, I've been modelling it like this, which has been working fine for the most part:

```rust
#[derive(Deserialize)]
#[serde(tag = "type")]
pub enum Expression {
    Identifier { name: String },
    Literal { value: Value },
    ...
}
```

Now, the difficulty I've been having comes in when I try to mix types that are at the bottom of the node hierarchy with node types that have sub-types (such as `Expression`):

```rust
#[derive(Deserialize)]
#[serde(tag = "type")]
pub enum ForStatementInit {
    VariableDeclaration { kind: String, ... },
    Expression(Expression),
}
```

In this case, what I really want is for the `ForStatementInit` type to be the result of "adding" the node of type `VariableDeclaration` to the set of representations for `Expression`. What ends up happening though of course is that it expects a value tagged with either `VariableDeclaration` or `Expression`.

I can work around this by either nesting `VariableDeclaration` into a single-variant enum, and using `#[serde(untagged)]` on the `ForStatementInit` enum, or by manually "flattening" the expression types, like so:

```rust
#[derive(Deserialize)]
#[serde(tag = "type")]
pub enum ForStatementInit {
    VariableDeclaration { kind: String, ... },
    // Expression
    Identifier { name: String },
    Literal { value: Value },
}
```

However, what I think would be really useful is to be able to do something like this instead, which would apply the same "flattening" transformation in the example above:

```rust
#[derive(Deserialize)]
#[serde(tag = "type")]
pub enum ForStatementInit {
    VariableDeclaration { kind: String, ... },
    #[serde(flatten)]
    Expression(Expression),
}
```

Hope this makes somewhat sense, keen to hear if this is something that you think is worth solving in serde itself!

**Comment by srijs** [comment]
It looks like this is similar to #1350 where you suggest manually flattening, but that would be fairly cumbersome in this case (`Expression` might have a couple dozen variants) and I guess I'm still curious whether there's a "better" way to do this.

**Comment by EliSnow** [comment]
@dtolnay, what would it take to implement `untagged` for variants? I have need for such a feature and may be interested in implementing it.

**Comment by dtolnay** [comment]
I haven't thought through how the feature would work. I would first want to see a handwritten Deserialize impl that behaves the way we would want the code generated for an untagged enum variant to behave. I would schedule 2-6 hours to put together some fully fleshed out handwritten impls to discover any edge cases, depending on your level of familiarity with the deserialization API.

**Comment by EliSnow** [comment]
> a handwritten Deserialize impl that behaves the way we would want the code generated for an untagged enum variant to behave

Meaning a Deserialize impl that enables it without any variant macro? Would tweaking serde-yaml in a branch be sufficient?

**Comment by EliSnow** [comment]
@dtolnay, did you see my previous questions?

**Comment by dtolnay** [comment]
Correct, handwritten meaning without a macro involved. There shouldn't need to be changes to serde-yaml or any other format because you would be touching the enum's Deserialize impl only.

**Comment by EliSnow** [comment]
Ahh, my mistake. I was thinking `Deserializer`

**Comment by EliSnow** [comment]
@dtolnay, I threw together [a few Deserialize impls](https://play.rust-lang.org/?version=beta&mode=debug&edition=2018&gist=bfec6caddd282bef6eaa74dc9e81f388). What edge cases am I lacking?

**Comment by dtolnay** [comment]
Trait bounds make this somewhat more complicated. For example:

```rust
trait Trait<T> {
    type Associated;
}

enum E<A, B, C> where A: Trait<C> {
    A(A::Associated),
    // #[serde(untagged)]
    B(B),
}

// not a legal type
#[allow(non_snake_case)]
struct AHelper<A, B, C> where A: Trait<C> {
    A: A::Associated,
}
```

Otherwise looks good to me.

**Comment by flying-sheep** [comment]
Aw too bad this doesn’t exist yet, I could really use that.

**Comment by azriel91** [comment]
Hiya, is the last edge case necessary to be supported for this feature to be supported?
If it is, wondering if trying to do something like this is too crazy:

```rust
#[allow(non_snake_case)]
struct AHelper<A, B, C, A_Associated>
where
    A: Trait<Associated = A_Associated, C>,
{
    A: A_Associated,
}
```

**Comment by NathanSWard** [comment]
Just checking on any update status for this issue?

**Comment by gengjiawen** [comment]
Which part should I look into to implement such a feature ?

**Comment by LEXUGE** [comment]
Really sad to see this doesn't come to reality.

**Comment by marcinliebiediew** [comment]
would be awesome to have this

**Comment by VoilaNeighbor** [comment]
This is important if we want to group AST nodes as a hierarchy of enums.

**Comment by 95th** [comment]
+1. I am in dire need of this feature.

**Comment by smallstepman** [comment]
A while ago I was struggling with the same... Perhaps, my [stackoverflow question+answer](https://stackoverflow.com/questions/66512221/how-to-destructure-enum-when-de-serializing-yaml-or-json-with-serde) will be useful for someone

**Comment by oli-obk** [comment]
Unfortunately no one has followed my proposal for testing this change on some crates to see if it solves the cases the crate authors on the issue have mentioned.

**Comment by Iron-E** [comment]
Solves my use case. For anyone who didn't know, `[patch]` option was useful in testing the PR. Just put this in your `Cargo.toml`:

```toml
[patch.crates-io.serde]
git = "https://github.com/dewert99/serde"
branch = "partially_untagged"
```

**Comment by wonbyte** [comment]
@gengjiawen ^ for "monkey-rust" 👍

**Comment by gavrilikhin-d** [comment]
Solved for my case. Really love how much code it saves!

**Comment by gavrilikhin-d** [comment]
Though I found another common pattern I do (not related to this PR): unwrapping array with single element to this element itself

**Comment by oli-obk** [comment]
Thanks!
