### ISSUE TITLE
use ? for try!

### ISSUE THREAD

**Issue by guanqun** [serde-rs/serde#1404]
Skim through the code and see the code is still using the old `try!`, I'm a bit curious why we're still using this? Is it for compatibility reason to support as old rust version as possible?

**Comment by dtolnay** [comment]
`try!` currently emits faster code than `?`. Last time I checked, using `?` hurt our benchmarks by around 6%.

**Comment by guanqun** [comment]
Thanks a lot for the prompt reply! It's good to know.
