### ISSUE TITLE
Adding a serializer method to complement deserialize_any

### ISSUE THREAD

**Issue by AGausmann** [serde-rs/serde#1405]
# Problem

A little while ago, I brought up my situation where I had a dynamic data type represented like an enum, for example:

```rust
enum Value {
    Null,
    Bool(bool),
    I64(i64),
}
```

What I want to be able to do is serialize the values themselves without keeping track of variants for self-describing serializers like JSON/TOML, but allow more compact formats to also be used like Bincode by adding more information when needed, for example, an identifying integer value before the data.

# Proposed Solution

Recently, I had this idea: What if we create a counterpart to `deserialize_any` in the `Serializer` trait?

```rust
trait Serializer {
    type SerializeAny: Serializer;

    fn serialize_any(self) -> Result<SerializeAny, Self::Error>;
}
```

- Serializables would only call this method where its corresponding `deserialize_any` would be called in reverse.
- The returned `Serializer` would serialize data in a guaranteed self-describing way so that the type of a value can be determined before its deserialization.
- For already self-describing formats (or a serializer previously returned from `serialize_any`), this simplifies to a no-op (`Ok(self)`) since they do not require any special handling.

## Non-breaking?

Releasing this as a minor non-breaking update may be a bit controversial, but I don't think it's too bad:

- With `Deserialize` / `Deserializer`, the only interface that will change is the implementation of `deserialize_any` for non-self-describing formats. 
    - If an updated `Deserialize` calls a non-updated `deserialize_any`, this will return an error, which is reasonable.
    - If a non-updated `Deserialize` calls an updated `deserialize_any`, *this will break* since the updated data format expects a corresponding call to `serialize_any` that won't happen if `Serialize` also isn't updated. I still think this is reasonably safe since the risk is very low: no one using 1.0.x should be using any data type that requires `deserialize_any` with a non-self-describing format.
- With `Serialize` / `Serializer`, the only interface that will change is the addition of the `serialize_any` and `SerializeAny` items.
    - **The addition of `SerializeAny` is unavoidably breaking, I'm still looking for an alternate solution.** In the worst case, this issue will be blocked on rust-lang/rust#29661 (`associated_type_defaults`).
    - If an updated `Serialize` calls a non-updated `Serializer`, we can have a default implementation of `serialize_any` that returns error indicating the function is not implemented.
    - If a non-updated `Serialize` calls an updated `Serializer`, there will be no call to `serialize_any` anyway since the serializable is not aware of its existence.

**Comment by AGausmann** [comment]
Forgot to mention how someone would theoretically implement `serialize_any` and `deserialize_any` for self-describing formats. 

Using Bincode as an example, each type in the data model would get its own numeric ID. When serializing with `serialize_any`, the returned serializer would write this hardcoded value (probably a single byte) first, then serialize the data. On the other side, `deserialize_any` would read and match against a single byte to drive the type that it deserializes.

**Comment by dtolnay** [comment]
Serde's trait design is generally not well suited to data structures that need to be represented differently across different formats. Type identification is only a part of that and in my opinion not worth addressing on its own.

Further, this approach to serialize_any assumes a binary concept of formats being self-describing vs not self-describing. In reality there is a spectrum with most formats somewhere in between. For example JSON is self-describing if you serialize an untagged enum that is either `bool` or `i64`, but loses type information if you serialize an untagged enum that is either `i32` or `i64`. MessagePack on the other hand tracks those as distinct types.

Thanks anyway for exploring this! If you want to prototype something along these lines in a different library I could take a look.
