### ISSUE TITLE
Deserialization of enums from config doesn't work

### ISSUE THREAD

**Issue by vorner** [serde-rs/serde#1415]
Hello

I'm using the [config](https://crates.io/crates/config) crate together with its serde support. This seems to be problematic together with enums.

# Reproducer

In this code, the `inner` test fails. However, the `outer` and `inner_direct` tests pass, so I think I'm not doing something completely silly.

```rust
use serde_derive::Deserialize;

#[derive(Deserialize)]
enum X {
    A,
    B,
}

#[derive(Deserialize)]
struct Y {
    x: X,
}

#[derive(Deserialize, Default)]
struct Inner {
    #[serde(default)]
    y: Vec<Y>,
}

#[derive(Deserialize, Default)]
struct Outer {
    #[serde(flatten)]
    y: Inner,
}

#[cfg(test)]
mod tests {
    use super::*;

    use config::{Config, File, FileFormat};

    const TOML: &str = r#"
    [[y]]
    x = "A"

    [[y]]
    x = "B"
    "#;

    fn cfg() -> Config {
        let mut config = Config::new();
        config.merge(File::from_str(TOML, FileFormat::Toml)).unwrap();
        config
    }

    #[test]
    fn inner() {
        cfg().try_into::<Inner>().unwrap();
    }

    #[test]
    fn outer() {
        cfg().try_into::<Outer>().unwrap();
    }

    #[test]
    fn inner_direct() {
        toml::from_str::<Inner>(TOML).unwrap();
    }
}
```

Exact versions used, if they matter:
* config: 0.9.1
* serde: 1.0.80
* serde-derive: 1.0.80
* toml: 0.4.8

# Guesses

To me it looks like the enum doesn't like to be deserialized from owned `String`, but doing it from `&str` is fine. And when going through the flattening, something on the way maybe goes from `String` to `&str`. But that's just a wild guess.

**Comment by dtolnay** [comment]
If `inner_direct` passes but `inner` fails, it sounds like this is an issue with the `config` crate rather than with Serde. Please follow up with them about it. Thanks!

**Comment by vorner** [comment]
OK, but still, the fact that `Inner` and `Outer` acts different seems strange. Flattening one structure into another as its only field should IMO make them kind of equivalent?
