### ISSUE TITLE
Allow default for struct if all fields have a default value

### ISSUE THREAD

**Issue by axos88** [serde-rs/serde#1416]
I would like to be able to specify that I intend HttpConfig to contain 0.0.0.0:8080, if the field is missing from the input, without having to implement Default for HttpConfig

```
#[serde(deny_unknown_fields, default)]
#[derive(Serialize, Deserialize, Debug)]
pub struct HttpConfig {
    #[serde(default = "default_address")]
    pub address: String,

    #[serde(default = "default_port")]
    pub port: u32
}

fn default_address() -> String { "0.0.0.0".to_string() }
fn default_port() -> u32 { 8080 }
```

**Comment by dtolnay** [comment]
I believe this already works the way you asked. The `serde(default = "...")` attribute on each field applies when that field is missing from the input, whether or not the surrounding struct has a Default impl.

```rust
use serde::Deserialize;

#[derive(Deserialize, Debug)]
#[serde(deny_unknown_fields)]
struct HttpConfig {
    #[serde(default = "default_address")]
    address: String,
    #[serde(default = "default_port")]
    port: u32
}

fn default_address() -> String {
    "0.0.0.0".to_string()
}

fn default_port() -> u32 {
    8080
}

fn main() {
    println!("{:?}", serde_json::from_str::<HttpConfig>("{}").unwrap());
}
```

**Comment by dtolnay** [comment]
Yep I misunderstood. Thanks for letting me know!

I would prefer to see this handled by a separate crate that knows how to produce a `Default` impl from `serde(default = "...")` attributes (or produce a freestanding default function, if you don't want the `Default` impl to exist).

```rust
#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct Config {
    #[serde(default)]
    http: HttpConfig,
}

#[derive(Deserialize, Default_serde)]
#[serde(deny_unknown_fields)]
struct HttpConfig {
    #[serde(default = "default_address")]
    address: String,
    #[serde(default = "default_port")]
    port: u32,
}

// expands to:
impl Default for HttpConfig {
    fn default() -> Self {
        HttpConfig {
            address: default_address(),
            port: default_port(),
        }
    }
}
```

**Comment by dtolnay** [comment]
I posted a request for implementation: https://github.com/dtolnay/request-for-implementation/issues/4.

**Comment by Luks17** [comment]
For anyone looking at this thread in the future. Here is your solution: https://github.com/TedDriggs/serde_default
