### ISSUE TITLE
Nest primitives during one serialization pass

### ISSUE THREAD

**Issue by yageek** [serde-rs/serde#1419]
Regarding this struct:

```rust
use std::ops;

#[derive(Debug, Clone)]
struct Range {
    name: String,
    range: ops::Range<usize>,
}
let range = Range { name: "price".to_string(), range: 0..3 };
```
I would like to map it like:

```json
{
    "price": {
        "min": 0,
        "max": 3
    }
}
```

I tempted somthing like:

```rust
impl Serialize for Range {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        let range = Range {
            name: "test".to_string(),
            range: 0..3,
        };
        // Inner
        let mut map = serializer.serialize_map(Some(2))?;
        map.serialize_entry("min", &self.range.start)?;
        map.serialize_entry("max", &self.range.end)?;
        map.end()?;

        let mut state = serializer.serialize_struct("Range", 2)?; // Owenerhip issue?
        state.serialize_field(&self.name, &map)?; // Error: SerializeMap is not compatible with Serialize
        state.end()
    }
}
```

Is there a simple way to nest the different primitives during one `Serialize` pass?
Is the only solution to implement a custom serialize method for the `range` field?

**Comment by dtolnay** [comment]
Yes, you will need a Serialize impl for each level of nesting. But the one that serializes "min" and "max" can be generated by derive. I would write this as:

```rust
// Private helper to serialize Range.
#[derive(Serialize)]
struct RangeLimits {
    min: usize,
    max: usize,
}

impl Serialize for Range {
    fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        let mut map = serializer.serialize_map(Some(1))?;
        map.serialize_entry(&self.name, &RangeLimits {
            min: self.range.start,
            max: self.range.end,
        })?;
        map.end()
    }
}
```

**Comment by yageek** [comment]
This is what I thought. 

It may worth to precise inside the documentation this is the way to go to deal with multiples levels and precise that nesting can not be handled inside through one `Serialize` implementation?.

**Comment by dtolnay** [comment]
Thanks, I agree this should be covered better. Do you have a suggestion for where you would expect to see this called out in the documentation?

**Comment by dtolnay** [comment]
Closing as discussed in https://github.com/serde-rs/serde-rs.github.io/pull/86. Ultimately I don't see this come up often enough to make a dedicated example in Implementing Serialize worthwhile.
