### ISSUE TITLE
use of unstable library feature 'inclusive_range_methods'

### ISSUE THREAD

**Issue by ablanleuil** [serde-rs/serde#1423]
When building `serde_derive` for my project, I have these errors:

```
error[E0658]: use of unstable library feature 'inclusive_range_methods' (see issue #49022)
    --> /home/shumush/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.80/src/de/impls.rs:2155:12
     |
2155 |         Ok(RangeInclusive::new(start, end))
     |            ^^^^^^^^^^^^^^^^^^^
     |
     = help: add #![feature(inclusive_range_methods)] to the crate attributes to enable

error[E0658]: use of unstable library feature 'inclusive_range_methods' (see issue #49022)
   --> /home/shumush/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.80/src/ser/impls.rs:259:51
    |
259 |         try!(state.serialize_field("start", &self.start()));
    |                                                   ^^^^^
    |
    = help: add #![feature(inclusive_range_methods)] to the crate attributes to enable

error[E0658]: use of unstable library feature 'inclusive_range_methods' (see issue #49022)
   --> /home/shumush/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.80/src/ser/impls.rs:260:49
    |
260 |         try!(state.serialize_field("end", &self.end()));
    |                                                 ^^^
    |
    = help: add #![feature(inclusive_range_methods)] to the crate attributes to enable
```

I am new to Rust, I may be doing something wrong, but from what I know, the feature problem is not from me, is it ?

My `rustc` version is `rustc 1.27.0-nightly (8ff4b4206 2018-05-08)`

**Comment by hcpl** [comment]
Could you provide the Rust version and the command you used to build your project?

**Comment by ablanleuil** [comment]
```
cargo 1.27.0-nightly (af3f1cd29 2018-05-03)
rustc 1.27.0-nightly (8ff4b4206 2018-05-08)
rustup 1.13.0
```

Just adding `#![feature(inclusive_range_methods)]` in your main library file seems to fix the problem, but I don't know if you want to add this feature in serde project.

**Comment by hcpl** [comment]
In that case, switching to any stable Rust since 1.27 or latest nightly should fix your problem.

FYI, Serde only supports the latest nightly because old and new nightlies are often incompatible, and nightly users are expected to update their compiler "every night" (hence the name). This fact is also true for any crate that has opt-in unstable functionality based on nightly `rustc` and if it doesn't build on the latest nightly, then it should be considered a bug and reported to maintainers.

**Comment by ablanleuil** [comment]
Thank you very much, yes, I totaly forgot to update it ... my bad. When I saw 1.13 on rustup (and not rustc) I thought it was updated.

Sorry for this.
