### ISSUE TITLE
Serialize doc comments

### ISSUE THREAD

**Issue by swfsql** [serde-rs/serde#1430]
I'll point to a [related suggestion](https://github.com/alexcrichton/toml-rs/issues/274) from `toml-rs`. On that issue, Alex pointed out that `serde` doesn't exposes the `doc comments`, and if it's feasible, I'd like to suggest such feature.

**Comment by dtolnay** [comment]
That's a neat idea! I am closing the issue because I would prefer not to support this in Serde, but you could implement your own derive macro using [Syn](https://github.com/dtolnay/syn) that makes doc comments available to a toml serializer.

**Comment by SOF3** [comment]
@dtolnay could you elaborate on why this (or other metadata attributes) is not suitable in syn? I don't see how  something like https://github.com/dtolnay/serde-yaml/issues/145 can be integrated with another proc macei easily, without rewriting/copying the whole serialization interface.

**Comment by andylokandy** [comment]
@dtolnay could we support it under a feature flag?
