### ISSUE TITLE
Deserializing an array of 16+ elements of multiple types

### ISSUE THREAD

**Issue by jean-airoldie** [serde-rs/serde#1431]
Hi,
Lets say I have an array ```[i32, f64, String, ..., Option<i32>]``` containing 26 elements. Lets say I want to deserialize it while maintaining strong typing. By strong typing I mean that I know the type of each element of the array, as opposed to having an array of untagged enum for instance.

One way to do so would be to use a struct tuple. [See here for more details](https://github.com/serde-rs/serde/issues/637). The problem is that serde can only derive serialization for up to [16 elements](https://docs.serde.rs/src/serde/ser/mod.rs.html#59) in a tuple.

My question is, how can I deserialize an array that contains more than the 16 elements (26 in my case), each with different types, while maintaining strong typing?

**Comment by dtolnay** [comment]
You should be able to derive Deserialize for a tuple struct of any size.

```rust
extern crate serde;
extern crate serde_derive;
extern crate serde_json;

use serde_derive::Deserialize;

#[derive(Deserialize, Debug)]
struct Array26(
    i32, f64, String, u8, u8, u8, u8, u8, u8, u8, u8, u8, u8, u8, u8, u8, u8,
    u8, u8, u8, u8, u8, u8, u8, u8, Option<i32>,
);

fn main() {
    let j = r#"
        [1, 2, "3", 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
        20, 21, 22, 23, 24, 25, 26]
    "#;
    println!("{:?}", serde_json::from_str::<Array26>(j).unwrap());
}
```

**Comment by jean-airoldie** [comment]
@dtolnay My question was ill-formed. Specifically, I would like to serialize/deserialize a struct as if it were a tuple struct. To do so I wrote a [macro](https://gist.github.com/jean-airoldie/0a7ac2e87dad9a37aad3d1c250bfcf2d) based on [one of your previous answer on the subject](https://github.com/serde-rs/serde/issues/637#issue-194172259). The problem that I'm referencing seems to only occur when explicitly calling `Deserialize::deserialize`. See [here](https://play.integer32.com/?version=stable&mode=debug&edition=2015&gist=1583a2ca5c9a5857c7c81a3e49e53fc5) for a playground replication link.

**Comment by dtolnay** [comment]
The macro will need to deserialize to a tuple struct rather than a tuple.

```rust
#[derive(Deserialize)]
struct Array($($ftype),*);
Deserialize::deserialize(deserializer)
    .map(|Array($($fname,)*)| Self { $($fname: $fname,)* })
```

**Comment by jean-airoldie** [comment]
@dtolnay Nice. Thanks!

**Comment by jean-airoldie** [comment]
@dtolnay You're right I can simply redefine it in each Serialization and Deserialize impl.
