### ISSUE TITLE
Attach serde attributes into different configurations

### ISSUE THREAD

**Issue by swfsql** [serde-rs/serde#1443]
I'm not sure if this has been suggested before, but I wonder if something like this could be possible in the future:

```rust
#[derive(Serialize)]
struct A {
    #[serde1(rename = "x")]
    #[serde2(rename = "y")]
    a: bool,
    #[serde1(rename = "xx")]
    #[serde2(rename = "yy")]
    b: bool,
}
```

So then I could serialize with the `serde1` (+default, overwriting if applicable) configuration, or perhaps with `serde2` (+default, overwriting if applicable) configuration - and they would have different names, in this example. And I suppose Deserialization could also expect some specific serde configuration (`1`/`2`).
The use-case I have in mind is that different APIs (that may be represented with the same structure) wouldn't need structure re-definition (and accompanying conversions) for implying different serde attributes (such as naming, enum-reorganization, etc).
obs. I picked the `serde1`/`2` naming for clarity

---

Seems related to https://github.com/serde-rs/serde/issues/595

**Comment by swfsql** [comment]
Hello @dtolnay , I have came across this need again,
and would like to ask if you could hint at the design difference that should likely to happen.

I expect that the `Deserialize` would need to be generic over a trait parameter..? otherwise it's implemented only once (in a pretty 'static' fashion) for some (let's say) `struct`, which would go against the goal of having 'multiple `#[serde]` configurations targeting the same struct/object representation'.

Could you hint if this is correct, or what design considerations you would have for such project? I don't really know much about serde internals, and even if it would for certain not be compatible with serde itself, I want to try putting some effort on it.

ps. ^^' I actually need this to refrain from re-declaring multiple times a gigantic structure, since it will have multiple adaptors and each with a particular set of `#[serde]` configurations.

**Comment by taylor1791** [comment]
I am using serde to {de,}serialize to dynamo using `serde_dynamo` and to a JSON api using `serde_json`. Consequently, I run into this quite frequently. I don't expect this alone to convince you to reconsider, but I did want to document my use for posterity.
