### ISSUE TITLE
Add ability to derive IntoDeserializer

### ISSUE THREAD

**Issue by Mingun** [serde-rs/serde#1453]
I try to implement deserializer of GFF format and for some types of values inside this format I want call on visitor the same sequence of methods, as usually auto-generated code calls when some struct deserialized. Something like this:
```rust

#[derive(Deserialize)]
struct MyValue { ... };

impl<'de> de::Deserializer<'de> for MyDeserialier
{
  fn deserialize_any<V>(self, visitor: V) -> Result<V::Value>
    where V: Visitor<'de>,
  {
    let value: MyValue = self.somehow_get_value();

    // visitor get events:
    // begin struct
    //   field 1
    //   field 2
    //   ...
    // end struct
    value.deserialize_into(visitor) // What should be in this line?
  }
}
```
Whether it is possible to make this?

In my real project I want to apply this method in this place for deserializing `LocString`: https://github.com/Mingun/serde-gff/blob/master/src/de/mod.rs#L86-L90

**Comment by Mingun** [comment]
By careful studying of documentation and experiments it was succeeded to find that this problem is solved with use of [`IntoDeserializer`]. However it was heavy! Definitely, documentation to `IntoDeserializer` needs considerable improvement and examples! Also, it would be quite good if `IntoDeserializer` could be derived automatically.

So, my task is solved by this code:
```rust
struct MyValue { ... };

struct MyValueDeserializer<E> {
  value: MyValue,
  marker: PhantomData<E>,
}
impl<'de, E> IntoDeserializer<'de, E> for MyValue
  where E: Error,
{
  type Deserializer = MyValueDeserializer<E>;

  #[inline]
  fn into_deserializer(self) -> Self::Deserializer {
    MyValueDeserializer { value: self, marker: PhantomData }
  }
}

impl<'de, E> Deserializer<'de> for StringKeyDeserializer<E>
  where E: Error,
{
  type Error = E;

  fn deserialize_any<V>(self, visitor: V) -> Result<V::Value, Self::Error>
    where V: Visitor<'de>,
  {
    // push to visitor such events:
    // begin struct
    //   field 1
    //   field 2
    //   ...
    // end struct
  }

  forward_to_deserialize_any!(
    bool i8 i16 i32 i64 i128 u8 u16 u32 u64 u128 f32 f64 char str
    string bytes byte_buf option unit unit_struct newtype_struct seq
    tuple tuple_struct map struct enum identifier ignored_any
  );
}

impl<'de> de::Deserializer<'de> for MyDeserialier
{
  fn deserialize_any<V>(self, visitor: V) -> Result<V::Value>
    where V: Visitor<'de>,
  {
    let value: MyValue = self.somehow_get_value();

    value.into_deserializer().deserialize_any(visitor)
  }
}
```
But it would be just remarkable if it could be reduced to the following:
```rust
#[derive(IntoDeserializer)]
struct MyValue { ... };

impl<'de> de::Deserializer<'de> for MyDeserialier
{
  fn deserialize_any<V>(self, visitor: V) -> Result<V::Value>
    where V: Visitor<'de>,
  {
    let value: MyValue = self.somehow_get_value();

    value.into_deserializer().deserialize_any(visitor)
  }
}
```

[`IntoDeserializer`]: https://docs.serde.rs/serde/de/trait.IntoDeserializer.html

**Comment by dtolnay** [comment]
Glad you got it working!

I would be interested in seeing someone else write a derive macro for `IntoDeserializer` in a separate crate. I don't think this needs to be provided directly by Serde.

**Comment by dtolnay** [comment]
For reusing the existing derives you would want to do something like [serde-value](https://github.com/arcnmx/serde-value).

```rust
let x: MyValue = self.somehow_get_value()?;

let value = serde_value::to_value(x)?; // using `impl Serialize for MyValue`

value.deserialize_any(visitor) // using `impl Deserializer for serde_value::Value`
```

which proceeds in two steps and requires memory allocation.

To go directly from MyValue to V::Value more efficiently, you would need a derive that implements Deserializer or IntoDeserializer for MyValue.
