### ISSUE TITLE
Can't serialize a generic, recursive struct where the generic type is not used. 

### ISSUE THREAD

**Issue by MortenLohne** [serde-rs/serde#1454]
[Minimal reproducable example.](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=8f00b8853ffe6c38b9ba17ebaecc9545)

Consider the following struct:
```
#[derive(Serialize, Deserialize)]
struct MoveTree<T>
where
    T: Board,
    T::Move: Serialize + DeserializeOwned,
{
    moves: Vec<T::Move>,
}
```

The generic type T does not implement `Serialize`, but serializing `MoveTree<T>` it still works, because `T` itself is not present in the struct. However, if the struct is recursive, the compiler complains that the trait bound is not satisfied:

```
#[derive(Serialize, Deserialize)]
struct MoveTree<T>
where
    T: Board,
    T::Move: Serialize + DeserializeOwned,
{
    moves: Vec<(MoveTree<T>, T::Move)>,
}
```

It's still impossible for T to occur in the struct, but the compiler doesn't agree. I'm not sure if this is simply a technical limitation or a bug, but any help or workaround is appreciated.

**Comment by dtolnay** [comment]
The bounds on `T::Move` should only go on the Serialize and Deserialize impl, not on the struct. See also [C-STRUCT-BOUNDS](https://rust-lang-nursery.github.io/api-guidelines/future-proofing.html#c-struct-bounds). I would write this as:

```rust
#[derive(Serialize, Deserialize)]
#[serde(bound(serialize = "T::Move: Serialize"))]
#[serde(bound(deserialize = "T::Move: Deserialize<'de>"))]
struct MoveTree<T: Board> {
    moves: Vec<(MoveTree<T>, T::Move)>,
}
```

**Comment by MortenLohne** [comment]
That works, thank you so much! [Fixed version on playground.](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=382c45cd0305f08f6f7727a9693a8c81)

Is there any reason serde can't add those extra annotations by itself? It's a bit strange that adding a Self-field to a struct breaks serde-derive like that.

**Comment by dtolnay** [comment]
Closing because I would prefer not to extend our trait bound inference to handle this case. There are infinitely many ways that we could extend inference to handle additional use cases, but each extension just means that the boundary cases get even more confusing. Ultimately it is better that we stick with a minimum viable set of rules and allow handwritten trait bounds where the inferred bounds are not correct.
