### ISSUE TITLE
Weird problem with no-std

### ISSUE THREAD

**Issue by elichai** [serde-rs/serde#1464]
Hi,
I have a project with a different `std`, and somehow when I import serde like this:
```
serde = { version = "=1.0.85", default-features = false, features = ["derive"] }
```
I get `std` duplicates like the library is using `std`.

But when I import it like This:
It works just fine. 
```
serde = { git = "https://github.com/serde-rs/serde.git", rev = "v1.0.85", default-features = false, features = ["derive"] }
```

**Comment by elichai** [comment]
Maybe it's something with rust because some of my other libraries use a fork of serde (and all of my libraries are connected in some way)

**Comment by dtolnay** [comment]
I don't think I can help you with this. The Rust Discord chat or Users forum would be a better place to debug this.

The serde crate uses std if and only if the `"std"` Cargo cfg is enabled.

https://github.com/serde-rs/serde/blob/bb99b31eb0a55393101f9c80cd959b3a739ad70f/serde/src/lib.rs#L80
