### ISSUE TITLE
how to reexport Serialize, Deserialize?

### ISSUE THREAD

**Issue by woodgear** [serde-rs/serde#1465]
just like this question
https://github.com/serde-rs/serde/issues/856#issuecomment-330878525
>My use case is slightly different. I have a project set up as a Cargo workspace, and I am thinking about setting up an internal common crate to handle external dependencies shared by multiple internal crates. serde and serde_derive are some of those crates I'd like to share.
With the proc_macro feature, I can easily put the Deserialize/Serialize macros in scope wherever I need them. However, if I do so outside the common crate, I get the error in the issue title.
I haven't looked into the internal workings of these macros at all, but I'm guessing they are looking for ::serde (or maybe $crate::serde) in scope. However, in my case serde will be at ::common::serde. Is there any way I can work around this?

the common crate 
```rust
//lib.rs
#[macro_use]
pub extern crate serde;
pub extern crate serde_json;
pub use serde::{Serialize,Deserialize};//for reexport macro
```
```toml
[dependencies]
serde = { version = "1.*" ,features = ["derive"]}
```
the main crate who want to use serde from common ccrate
```rust
//main.rs
#[macro_use]
extern crate common;
#[derive(Serialize)]
struct Test {

}
fn main() {
    println!("Hello, world!");
}
```
```toml
[dependencies]
common = { path = "../common" }
```

it should be work but always report error like
```bash
error[E0463]: can't find crate for `_serde`
 --> src\main.rs:5:10
  |
5 | #[derive(Serialize)]
  |          ^^^^^^^^^ can't find crate
```

how should i do that?

**Comment by dtolnay** [comment]
There is no supported way to do this currently. The downstream crate will need to add its own dependency on serde.

If it is an absolute requirement that this work, then you could fork serde_derive and modify it to emit paths that refer to common::serde everywhere instead of serde.

**Comment by woodgear** [comment]
I am confusing why it is impossible. could you please give me some explain or I am lose some extra information?

**Comment by dtolnay** [comment]
The code emitted by serde_derive would look something like:

```rust
impl serde::Serialize for Test {...
```

But if there is no such thing as `serde` in the main crate, then this code does not compile.

**Comment by photex** [comment]
I have a very large repo/workspace at work. Many crates have to have their own serde line in the Cargo.toml now and it's going to potentially be a bit of a chore someday in the future. We already have a utils crate that re-exports common cli and logging setup. We have another for grouping common dependencies for certain tasks.
It would be very helpful for Serde to work correctly when re-exported as well.

**Comment by thedavidmeister** [comment]
this is painful for us, we have several repos with a few dozen crates and every time we want to do something with the serde dependencies it is a tedious hunt to go find all the places it is being used

**Comment by thedavidmeister** [comment]
@woodgear why did you close this, it seems unresolved?

**Comment by AgarwalPragy** [comment]
Sorry to bother, is there any update on this?

My usecase is the same as OP

**Comment by Cightline** [comment]
I have the same issue as the last few posters.

**Comment by xixixao** [comment]
Based on https://github.com/yewstack/yew/issues/1454 looks like this is fixable now with `crate::*` on stable.

**Comment by lastmjs** [comment]
So how is this fixable? I'm trying to get it to work, but not having luck

**Comment by skorpi-and-friends** [comment]
Has anybody found a way around this?

**Comment by skorpi-and-friends** [comment]
For anyone looking, I've found a way around this using a derive helper attribute that serde implements ([here](https://github.com/serde-rs/serde/blob/5a8dcac2ed1407fab3f7fd23f2d56af42dcd448f/serde_derive/src/internals/attr.rs#L556-L561); couldn't find where it's documented). 

Usage:

```rust
use common::serde::{self, Deserialize, Serialize}

#[repr(C)]
#[derive(Copy, Clone, Debug, Deserialize, Serialize)]
#[serde(crate = "self::serde")] // must be below the derive attribute
pub struct Foo {
    pub position: glam::Vec3,
}
```

**Comment by lastmjs** [comment]
The above worked for me! Thank you!
