### ISSUE TITLE
Make it simpler to (de)serialize maps to/from list

### ISSUE THREAD

**Issue by upsuper** [serde-rs/serde#1476]
It seems to be a common mistake to try serializing a map (e.g. `HashMap`) with non-string key into a format which doesn't support so. In that case, serde would just throw `key must be a string`.

I suggest that this usecase can be served better via serializing maps as list in forms of `[(key, value)]`. Map can generally be converted to / from list via `IntoIterator` and `FromIterator`. Having something, like a new attribute, to serialize it via those two traits may be very useful, so that people don't need to write a whole custom implementation of `Serialize` and `Deserialize` just for this basic usecase.

**Comment by dtolnay** [comment]
Thanks! I would prefer to see this as a (de)serialize_with function in a different crate. Please file an issue for this in [serde_with](https://github.com/jonasbb/serde_with) or [serde-aux](https://github.com/vityafx/serde-aux) or similar helper crate.

Mentioning @jonasbb @vityafx.

**Comment by upsuper** [comment]
FTR, I have an implementation of this idea here: https://github.com/rust-net-web/areweasyncyet.rs/blob/f3460e6dc11c6dc11d1910f5c13036635285e1b5/src/fetcher.rs#L53 which can be added to a helper crate.

**Comment by jonasbb** [comment]
Thanks for the ping. I am rather busy till the end of next week.
@upsuper Your implementation looks like a nice start. I would like to build on it if you don't mind.

**Comment by upsuper** [comment]
@jonasbb I don't mind, and actually if I have time I may make pull request to serde_with as well. I'm also quite busy at the moment, so if I don't get to it, feel free to build based on my code.
