### ISSUE TITLE
Help understanging different behavior for deserialization of bytes slice in enums

### ISSUE THREAD

**Issue by marmeladema** [serde-rs/serde#1478]
Hello everyone,

In a bigger project i ended up having problems with de-serialization of bytes slice.
This simple code snippet works fine:
```
use serde;

#[derive(serde::Deserialize)]
#[serde(untagged)]
enum Value<'a> {
    Bytes(&'a [u8])
}
```
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=f0e91505c05fcb17e9f2b69d9816a562 

But this does not:
```
use serde;

#[derive(serde::Deserialize)]
#[serde(untagged)]
enum Bytes<'a> {
    Variant(&'a [u8]),
}

#[derive(serde::Deserialize)]
#[serde(untagged)]
enum Value<'a> {
    Bytes(Bytes<'a>)
}
```
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=e0b9663df7b9f07f7fcbdd39b9b092eb

I need help understanding the deep difference between the two forms that causes one to work and the other to fail.

Thank you in advance :+1:

**Comment by dtolnay** [comment]
Looks like there is a `#[serde(borrow)]` attribute missing. Please see https://serde.rs/lifetimes.html. The deep difference between the two forms is that one contains &[u8] and the other does not. Only &[u8] and &str are implicitly borrowed from the input data.
