### ISSUE TITLE
Consistent naming for serde attributes

### ISSUE THREAD

**Issue by Mingun** [serde-rs/serde#1479]
Today serde have several groups of attributes, a part of which influences serialization and deserialization, and a part -- only serialization or only deserialization. These are groups:
`bound` group:
```rust
#[serde(bound = "T: MyTrait")]
#[serde(bound(serialize = "T: MyTrait"))]
#[serde(bound(deserialize = "T: MyTrait"))]
```

`skip` group
```rust
#[serde(skip)]
#[serde(skip_serializing)]
#[serde(skip_serializing_if = "path")]
#[serde(skip_deserializing)]
```

`with` group:
```rust
#[serde(with = "module")]
#[serde(serialize_with = "path")]
#[serde(deserialize_with = "path")]
```

Apparently, naming goes anyhow, there is no single system. I suggest to create it, having renamed some attributes for achievement of such system:
`bound` group:
```rust
#[serde(bound = "T: MyTrait")]
#[serde(bound(serialize = "T: MyTrait"))]
#[serde(bound(deserialize = "T: MyTrait"))]
```

`skip` group:
```rust
#[serde(skip)]
#[serde(skip(serialize))]
#[serde(skip(serialize = "path"))]
#[serde(skip(deserialize))]
```

`with` group:
```rust
#[serde(with = "module")]
#[serde(with(serialize = "path"))]
#[serde(with(deserialize = "path"))]
```

**Comment by dtolnay** [comment]
Overall I think I'm happy sticking with the current names.

Thanks anyway for this suggestion!
