### ISSUE TITLE
serde_codegen does not generate code for derive in cfg_attr

### ISSUE THREAD

**Issue by jmesmon** [serde-rs/serde#148]
For example, this doesn't work:

```
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
struct Foo {
 a: u32,
};
```

It appears that the codegen simply doesn't know what to do about cfg_attr.

I suppose it's possible that not enough info is available when codegen occurs to actually resolve this. If so, feel free to close.

**Comment by dtolnay** [comment]
@jmesmon I just tried this and it seems to work. Can you try again and report back? Here is the code I used:

```rust
#![feature(plugin, custom_derive)]
#![plugin(serde_macros)]

#[cfg(feature = "serde")]
extern crate serde;

#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
struct Foo {
    a: u32,
}

#[cfg(feature = "serde")]
fn main() {
    println!("with serde");

    fn assert<T: serde::Serialize + serde::Deserialize>(_: T) {}
    assert(Foo { a: 0 });
}

#[cfg(not(feature = "serde"))]
fn main() {
    println!("without serde");
}
```

**Comment by jmesmon** [comment]
@dtolnay you're using `serde_macros` (plugin). This bug is talking about `serde_codegen` (generates code with a build script that you then `include!`).

I'm still able to reproduce this with `serde_codegen`.

Here's a project that reproduces: https://github.com/jmesmon/serde-readme

**Comment by dtolnay** [comment]
> I suppose it's possible that not enough info is available when codegen occurs to actually resolve this. If so, feel free to close.

I suspect this is the case, but we can fix it anyway, at least for the common cases. We need to transform this:

```rust
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
struct Foo { ... }
```
... into this:

```rust
#[cfg(feature = "serde")]
impl Serialize for Foo { ... }
#[cfg(feature = "serde")]
impl Deserialize for Foo { ... }
struct Foo { ... }
```

**Comment by dtolnay** [comment]
For those not watching the Syntex repo - check out the PR at https://github.com/serde-rs/syntex/pull/71.

**Comment by erickt** [comment]
bad homu, this isn't implemented in serde yet.

**Comment by dtolnay** [comment]
Actually it is. :smile: That's all it took.

**Comment by nox** [comment]
I have a similar problem with:

```rust
#[cfg(target_os = "macos")]
pub type NativeFontHandle = CGFont;

/// Native fonts are not used on Linux; all fonts are raw.
#[cfg(not(target_os = "macos"))]
#[derive(Clone, Serialize, Deserialize)]
pub struct NativeFontHandle;
```

Is it the same bug? Should I file another one?

**Comment by dtolnay** [comment]
Different bug unfortunately. I filed it as https://github.com/serde-rs/syntex/issues/81.
