### ISSUE TITLE
Implement Serialize/Deserialize for std::io::ErrorKind

### ISSUE THREAD

**Issue by bddap** [serde-rs/serde#1480]
ErrorKind is a simple enum so hopefully implementing ser/de would be straightforward.

One use case: structured error reporting in networked apis. The function:

```rust
fn frob() -> Result<bool, io::ErrorKind>;
```

could be turned into an rpc call.

**Comment by bddap** [comment]
[io::ErrorKind docs](https://doc.rust-lang.org/stable/src/std/io/error.rs.html)

**Comment by bddap** [comment]
[io:ErrorKind docs](https://doc.rust-lang.org/stable/std/io/enum.ErrorKind.html)

**Comment by dtolnay** [comment]
Thanks! I would prefer not to provide these impls because this seems pretty specific to your use case -- I don't recall having seen `Result<T, io::ErrorKind>` before. I would recommend using `serialize_with` or a newtype wrapper to provide the serialization logic yourself.
