### ISSUE TITLE
Where is the "build directory" that update-references.sh talks about?

### ISSUE THREAD

**Issue by RalfJung** [serde-rs/serde#1482]
I added some UI tests, and would like to update the references automatically. I found `test_suite/tests/ui/update-references.sh`, which says I need to point it to the "build directory". It gives `../../../build/x86_64-apple-darwin/test/ui` as an example.

I have no idea what directory that is relative to, but:
* There exist two directories called `build` inside my serde checkout, and neither of them contains a directory named after my target triple.
* It seems the directory should be called `ui` (that's what the example path ends in, after all), but the only directory called `ui` anywhere in my serde checkout is `test_suite/tests/ui`.

So, it doesn't seem like I have any path locally that even remotely matches the example. 

I searched for `*.stderr`, and only found the reference file. It seems that the part in the script which says

> you do a run, which will generate files in the build directory

just does not apply any more -- I did a run, and found no files nowhere.
I am running `cargo test --features compiletest ui` in the `test_suite` directory.

**Comment by RalfJung** [comment]
I now found the files I was looking for in `/tmp`, so for me the right onvication is
```
./update-references.sh /tmp enum*/*.rs
```
but that doesn't look at all like what is described in the script?

**Comment by dtolnay** [comment]
Thanks, fixed in bf27b285546a14265fef960ce218d22afddb8fbf to not require any args.
