### ISSUE TITLE
`#[serde(flatten)]` alternative that supports both flattened and nested input

### ISSUE THREAD

**Issue by magnet** [serde-rs/serde#1485]
Right now, if one applies `#[serde(flatten)]` on a field, the "unflattened" variant will not be deserialized anymore. 

When working with different formats it is more idiomatic in some to use flattened fields, and in others to keep the nested representation. It would be nice to handle this at the Serde level.

Is there already a way to accomplish this without implementing manually the Deserialize trait for the struct containing the flatten field? If not, a `#[serde(flatten)]` variation that accepts both flattened and nested input would be useful. Flatten would keep its default behavior, but it could be altered using an option (e.g `#[serde(flatten = accept)]`or another attribute like `#[serde(allow_flattened)]`.

Is this something you would accept in Serde? If it is, I could try submitting a PR given the right pointers. I had a look at the code of `serde_derive`'s `de::deserialize_struct` and `serde::private::de::FlatMapDeserializer` but I don't know where is the best place to implement this. Ideally, I'd try to deserialize *without* flatten first, and if it failed would try with flattened input. I am also not familiar enough with Serde to know whether that kind of retry is easy to achieve with the current design and how to do so.

Thanks for pointers!

**Comment by dtolnay** [comment]
I believe this should be done with deserialize_with rather than a new attribute.

```rust
use serde::Deserialize;

#[derive(Deserialize, Debug)]
struct S {
    #[serde(flatten, deserialize_with = "deserialize_t")]
    t: T,
}

#[derive(Deserialize, Debug)]
struct T {
    i: i32,
}

macro_rules! flattened_maybe {
    ($fn:ident, $field:literal) => {
        fn $fn<'de, T, D>(deserializer: D) -> Result<T, D::Error>
        where
            T: serde::Deserialize<'de>,
            D: serde::Deserializer<'de>,
        {
            #[derive(serde::Deserialize)]
            struct Both<T> {
                #[serde(flatten)]
                flat: Option<T>,
                #[serde(rename = $field)]
                not_flat: Option<T>,
            }

            let both: Both<T> = serde::Deserialize::deserialize(deserializer)?;
            match (both.flat, both.not_flat) {
                (Some(t), None) | (None, Some(t)) => Ok(t),
                (None, None) => Err(serde::de::Error::missing_field($field)),
                (Some(_), Some(_)) => Err(serde::de::Error::custom(concat!(
                    "`", $field, "` is both flattened and not"
                ))),
            }
        }
    };
}

flattened_maybe!(deserialize_t, "t");

fn main() {
    let j = r#" {"i":1} "#;
    println!("{:?}", serde_json::from_str::<S>(j).unwrap());

    let j = r#" {"t":{"i":1}} "#;
    println!("{:?}", serde_json::from_str::<S>(j).unwrap());

    let j = r#" {} "#;
    println!("{}", serde_json::from_str::<S>(j).unwrap_err());

    let j = r#" {"i":1,"t":{"i":1}} "#;
    println!("{}", serde_json::from_str::<S>(j).unwrap_err());
}
```

FYI @jonasbb

**Comment by magnet** [comment]
@dtolnay Thanks! I like this approach a lot! Maybe this could be an exported macro, like `with_prefix!` is in `serde_with`. I'm going to give it a try.

**Comment by magnet** [comment]
Thanks @jonassbb ! I am closing this as resolved.
