### ISSUE TITLE
SGX Support (Mesalock SGX)

### ISSUE THREAD

**Issue by dingelish** [serde-rs/serde#1488]
Hi there,

I'm maintaining [rust-sgx-sdk](https://github.com/baidu/rust-sgx-sdk) which provide a set of fundamental crates for Intel SGX. This SDK has been adopted in some blockchain projects including [Enigma](https://github.com/enigmampc/enigma-core/blob/master/enigma-principal/enclave/Cargo.toml).

We heavily depend on serde. And currently, I maintain a customized [fork](https://github.com/baidu/rust-sgx-sdk/tree/master/third_party/serde-rs). It supports:
* Use cargo and replace the default libstd using a hack `#![no_std]` `extern crate sgx_tstd as std` `use std::prelude::v1::*`.
* Use xargo to replace the default libstd. The target spec here is `env = "sgx"` `vendor = "mesalock"`

The [modifications](https://github.com/dingelish/serde/commit/29c24c5ccb9bcd5387d48124f93772aaa7a0ab74) are subtle. Basically, the changes are:
* Extra "optional" dependency on sgx_tstd controlled by the following feature
* Additional feature `mesalock_sgx_cargo` to support compiling SGX enclaves in cargo. This feature turns the entire crate into a `no_std` crate with a hack of `extern crate sgx_tstd as std` to replace the libstd. Two lines of `use std::prelude::v1::*` should be always compatible with current codes.
* Additional folder 'sgx' contains: (1) a new workspace including only serde and serde_derive, (2) a target json file and Xargo.toml to specify the mesalock-sgx platform for xargo use. These files are all optional.

With the above changes, one can directly use serde from here (instead of maintaining another branch) in either cargo or xargo mode.

Just wonder if the above changes (or part of them) could be merged to upstream. Thanks!

**Comment by dtolnay** [comment]
Skimming https://github.com/dingelish/serde/commit/29c24c5ccb9bcd5387d48124f93772aaa7a0ab74, I would prefer not to accept any of this in Serde. I would recommend pursuing noninvasive ways of retrofitting sgx support, such as a Cargo wrapper that automatically patches crates.

**Comment by dingelish** [comment]
OK. That makes sense. Thanks!
