### ISSUE TITLE
skip_deserialize for unknown types when using Swagger codegen

### ISSUE THREAD

**Issue by unixunion** [serde-rs/serde#1493]
Hi, 

I am have been trying to add `skip_serializing_if` to swagger's template mustache files, so that keys for None type values are left out of serialised objects. However the following Mustache template yields invalid rust code:

    #[serde(rename = "{{baseName}}", skip_serializing_if="{{{datatype}}}::is_none")]

For basic datatypes this creates valid rust code:

     #[serde(rename = "value", skip_serializing_if="f64::is_none")]
     value: f64,

But does not work for other nested types e.g `Vec<String>` which results in the following 

    #[serde(rename = "photoUrls", skip_serializing_if="Vec<String>::is_none")]
    photo_urls: Vec<String>,

Compiler error:

    #[serde(rename = "photoUrls", skip_serializing_if="Vec<String>::is_none")]
                                                        ^^^^^^^^^^^^^^^^^^^^^^
    error: failed to parse path: "Vec<::models::Tag>::is_none"

Another nested struct error example:

    error: failed to parse path: "Vec<::models::Tag>::is_none"
      --> src/models/pet.rs:26:48
    #[serde(rename = "tags", skip_serializing_if="Vec<::models::Tag>::is_none")]
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Is this something to fix in Swagger? Or is it a serde fix or a rust-lang thing?

**Comment by dtolnay** [comment]
`Vec<T>::f` is not valid Rust syntax so this is a bug on your end. You could try writing `Vec::<T>::f` or `<Vec<T>>::f` which are equivalent and both Rust syntax.

**Comment by unixunion** [comment]
Thanks, I will investigate on the swagger side further, as it is now, swagger does not provide a datatype in a suitable format. 

My reason for creating this was to find out if skip_serialised_if parsed in a way that could be changed within serde, or if it’s more fundamental flaw in swagger

**Comment by unixunion** [comment]
Closing this as I have resolved the issue in Swagger.
