### ISSUE TITLE
Deserialize untagged enum with `ron` crate

### ISSUE THREAD

**Issue by vessd** [serde-rs/serde#1494]
Deserialization of `untagged enum` doesn't work well in `ron`.
For example
```rust
#[derive(Debug, Clone, Deserialize, Serialize)]
enum Bar {
    Bar,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(untagged)]
enum Foo {
    Foo { bar: Bar },
}

let foo_str = "(bar:Bar,)";
let foo: Foo = from_str(foo_str)?;
```
becomes `Content::Map([(Content::String("bar"), Content::Unit)])` and fail in [ContentRefDeserializer::deserialize_enum](https://github.com/serde-rs/serde/blob/295730ba1e8ccfb58afad836ea4907b951698aae/serde/src/private/de.rs#L2070), because it expects either a `Map` or a `String`.

Where should it be fixed? As for me, the `Content::Unit` looks fine.

**Comment by dtolnay** [comment]
Why do you say the Content::Unit looks fine?

I haven't looked through the code in ron, but so far this seems like a ron bug to me. Serde's unit type is for values that hold no information, like unit structs. From what I can tell, ron serializes unit as `()`. I think it should be deserializing `Bar` as something other than unit.

```rust
use serde::Serialize;

#[derive(Serialize)]
struct Bar;

#[derive(Serialize)]
enum Meaningful {
    Bar,
    Bee,
    Queue,
}

fn main() {
    println!("{}", ron::ser::to_string(&Bar).unwrap()); // ()
    println!("{}", ron::ser::to_string(&Meaningful::Bar).unwrap()); // Bar
}
```

**Comment by vessd** [comment]
I asked because I do not know how the serde works well enough.
It looks very strange to me that a `enum` is deserialized normally, but `untagged enum` is not.

**Comment by dtolnay** [comment]
When deserializing an externally tagged enum, the Deserialize impl can provide a hint to the data format as to what type is expected within the enum value. When deserializing an untagged enum, the data format does not get a hint on the type because the type could be any of the different enum variants.

I am closing this issue but please let me know if you report this to ron and they are unable to fix it there.
