### ISSUE TITLE
Unit value could deserialize to struct if all fields have default

### ISSUE THREAD

**Issue by derekdreery** [serde-rs/serde#1498]
Currently if you're trying to deserialize a struct and your deserializer calls `visit_unit`, you get an error. However, you could deserialize the struct if all fields have a default. What do you think of changing behavior from failing to succeeding with default if possible, failing otherwise?

**Comment by dtolnay** [comment]
Thanks for reporting this idea! I am closing the issue because I would prefer not to accept unit (roughly: JSON `null`) to mean a struct with all default field values.
