### ISSUE TITLE
More deserialization formats for Duration

### ISSUE THREAD

**Issue by axos88** [serde-rs/serde#1509]
I'd love to make the deserialization of Duration more flexible, but i'd like to check with you first before submitting a PR.
What I had in mind:
  - make nanos field optional, and default to 0 if not given.
  - accept one-field arrays, and use it as seconds (I'm not entirely sure this is a good idea, it may not be obvious what the units are)
  - accept a single number (I'm not entirely sure this is a good idea, it may not be obvious what the units are)
  - accept string representation in the form of "5 seconds", "5s", "5 sec", "5 min", "5 minutes", "1 hour"
  - accept more fields in the struct ("millis", "minutes", "hours", "days", "weeks"). These would all add up to the correct duration. 

Deserialization would stay the same.

**Comment by jean-airoldie** [comment]
You might want to check out [this crate](https://github.com/tailhook/humantime).

**Comment by dtolnay** [comment]
I would prefer not to build anything fancier for Duration into serde directly, but these additional representations could be provided by a crate like https://github.com/jonasbb/serde_with.
