### ISSUE TITLE
Feature request: Allow #[serde(rename = "...")] on tuple struct / tuple variant member fields

### ISSUE THREAD

**Issue by jplatte** [serde-rs/serde#1510]
Here is some working code that I would love to be able to condense:

```rust
/// The authentication mechanism.
#[derive(Clone, Debug, PartialEq, Eq, Deserialize, Serialize)]
#[serde(tag = "type")]
pub enum LoginType {
    /// A password is supplied to authenticate.
    #[serde(rename = "m.login.password")]
    Password {
        password: String
    },
    /// Token-based login.
    #[serde(rename = "m.login.token")]
    Token {
        token: String
    },
}
```

I tried like this, but got `Error("invalid type: map, expected a string")` on deserialization:

```rust
/// The authentication mechanism.
#[derive(Clone, Debug, PartialEq, Eq, Deserialize, Serialize)]
#[serde(tag = "type")]
pub enum LoginType {
    /// A password is supplied to authenticate.
    #[serde(rename = "m.login.password")]
    Password(#[serde(rename = "password")] String),
    /// Token-based login.
    #[serde(rename = "m.login.token")]
    Token(#[serde(rename = "token")] String),
}
```

This looks like something that *could* be supported to me. Or if it is deemed too niche + cryptic the additional `rename` should probably compile-error since it doesn't have any effect, right?

**Comment by jplatte** [comment]
@dtolnay Would you accept a PR that implements this?

**Comment by dtolnay** [comment]
I would prefer not to support this. I agree it's something that we *could* support, but I don't think the benefit will be big enough to justify adding logic to serde_derive.

One thing I would gladly accept though is any simplifications to serde_derive, to make the implementation more straightforward or compile faster.

**Comment by jplatte** [comment]
That's unfortunate. So should this issue be closed then?

Re. simplifications: Are you talking about the raw compile time of serde_derive, or about the compile time of the code it generates (or both)? I haven't previously done any compile time profiling, but I've heard Rust has pretty decent tooling for this, so I might give it a try.

**Comment by dtolnay** [comment]
> Are you talking about the raw compile time of serde_derive, or about the compile time of the code it generates (or both)?

Both of those are good things!
