### ISSUE TITLE
Possibility of converting a `Serialize` directly to a `Deserialize`

### ISSUE THREAD

**Issue by leoyvens** [serde-rs/serde#1511]
I figure if I can use serde to do `T -> json -> U`, could I use it to do `T -> U` directly, as a lazy way of implementing `TryFrom`? Does the idea of having a `Serializer` and `Deserializer` pair that streams data directly between a `Serialize` and a `Deserialize` type, with no data format in between, make any sense?

**Comment by dtolnay** [comment]
I think it makes sense; I would be interested to see someone pursue this in a library.

A closely related thing I have wanted someone to build is a `derive(Deserializer)` macro. Just like how e.g. `serde_json::Value` implements `Deserializer<'de>` next to its more commonly used Serialize and Deserialize impls. In fact there is also another `Deserializer<'de>` impl for `&'de serde_json::Value` so you can even deserialize borrowed values from it. But the point is such `Deserializer<'de>` impls should be possible to derive for any Serde-serializable data structure.

With this, you could convert data structures `T -> U` via the Deserialize impl of `U` and the Deserializer impl of `T`.

```rust
let u = U::deserialize(t)?; // or U::deserialize(&t) for the borrowing one
```
