### ISSUE TITLE
Re-enable compile-fail tests

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#1513]
Disabled temporarily in #1512 due to libserde now appearing in the nightly sysroot and causing a conflict. We will need to figure out how else to run these tests.

**Comment by dtolnay** [comment]
I think the solution will involve factoring out the test runner from https://github.com/dtolnay/proc-macro-workshop and dropping compiletest_rs in favor of that. It is a more robust approach based on Cargo rather than direct rustc invocations. I have found that it works very reliably and in particular would not have this class of problem.

Upstream issue: https://github.com/dtolnay/proc-macro-workshop/issues/14

**Comment by oli-obk** [comment]
Here's the clippy workaround: https://github.com/rust-lang/rust-clippy/pull/4017
