### ISSUE TITLE
Verify deserialized value

### ISSUE THREAD

**Issue by axos88** [serde-rs/serde#1515]
I have a type which encodes an API Key, which is basically a string, but it must follow a set of predefined rules: length is 40 characters, and it includes lowercase characters and numbers only.

(Yes, this could be verified with a regex, but  for the time being let's assume it's more complicated, and  cannot be validates that simply - although I'm not sure how to force regex validation either)

Roughly:

```
#[dervie(Copy, Clone, Deserialize, Serialize)]
pub struct ApiKey(String);

impl ApiKey {
  pub fn value() -> String { return self.0.clone(); }

  pub fn new(s: String) -> Result<ApiKey, InvalidFormat> {
    if (verify(s)) {
      Ok(ApiKey(s))
    } else {
      Err(InvalidFormat)
    }
  }
}
```

Now the whole point of this structure is that if an instance exists, it's guaranteed that the format of the key conforms to the requirements.

How can I make serde_derive use the ::new() function to construct the object to force validation? Losing the exact would be okay, if there is no way to retain it. I'd expect a deserialization error to be returned if the value does not conform to the requirements.

**Comment by axos88** [comment]
Probably related to #642

**Comment by axos88** [comment]
Another approach:

```
#[dervie(Copy, Clone, Deserialize, Serialize)]
pub struct ApiKey(String);

impl ApiKey {
  fn value() -> String { return self.0.clone(); }

fn validate(self) -> Result<Self, InvalidFormat> {
    if (verify(s)) {
      Ok(self)
    } else {
      Err(InvalidFormat)
    }
}  

  fn new(s: String) -> Result<ApiKey, InvalidFormat> {
    ApiKey(s).validate()
  }
}
```

**Comment by dtolnay** [comment]
I would recommend writing your own Deserialize impl. Something like:

```rust
impl<'de> Deserialize<'de> for ApiKey {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let s = String::deserialize(deserializer)?;
        ApiKey::new(s).map_err(de::Error::custom)
    }
}
```
