### ISSUE TITLE
Adjacently tagged enum takes wrong field

### ISSUE THREAD

**Issue by greaka** [serde-rs/serde#1516]
I have something along the lines of this:
```json
{
  "type": "foo",
  "details": {
    "type": "bar"
  }
}
```

In rust, I have an enum for the parent type, an enum for details and enums for whatever subtype is in details.
I tagged the the enum for details with `#[serde(tag = "type", content = "details")]`.
This produces runtime errors which indicate that serde takes the child type instead of the parent type to try to find an enum variant to fit into.

I am reading from the docs that this shouldn't be this way. But still, I could misunderstand them. I seek help, how can I make serde take the outer type? Type has to be renamed in rust anyway, so if its possible to give serde the rust field name, then this wouldnt be a problem, since they are called differently.

If this is a bug, I am happy to help trying to reproduce this.

**Comment by greaka** [comment]
To give an example:
https://github.com/greaka/gw2api/blob/de18ea1cad252479df1838701d60cd91116e6a17/src/items/items.rs#L445
The Deserializer should take `item_type` from `struct Item` but takes (for example) `weapon_type` from `WeaponDetails` instead.
If you clone and run it, the tests will fail.
Example error message for weapon type (Added some line breaks):
```
---- items::items::tests::test_get_item_weapon stdout ----
thread 'items::items::tests::test_get_item_weapon' panicked
at 'called `Result::unwrap()` on an `Err` value:
Error {
    kind: Json(Error("unknown variant `Sword`,
        expected one of `Armor`, `Back`, `Bag`, `Consumable`, `Container`, `Gathering`, `Gizmo`,
        `MiniPet`, `Tool`, `Trinket`, `UpgradeComponent`, `Weapon`", line: 26, column: 19)),
    url: None
}', src\libcore\result.rs:999:5
```

**Comment by dtolnay** [comment]
Hi @greaka, sorry that no one was able to provide help here. If this is still an issue, you could try taking this question to any of the resources shown in https://github.com/serde-rs/serde#getting-help.
