### ISSUE TITLE
impl serde::{de,ser}::Error for std::convert::Infallible

### ISSUE THREAD

**Issue by srijs** [serde-rs/serde#1517]
It would be useful to have `{de,ser}::Error` impls for `std::convert::Infallible`.

Alternatively serde could provide its own `Infallible`/`Impossible` error structs for these cases.

**Comment by dtolnay** [comment]
Serde errors aren't infallible. The trait methods on serde::ser::Error and serde::​de::Error allow a Serialize / Deserialize impl to construct errors.
