### ISSUE TITLE
New feature - using struct/enum name as a field

### ISSUE THREAD

**Issue by elichai** [serde-rs/serde#1518]
Hi,
I'm proposing a new attribute.
`#[serde(Serialize_as_field)]`

This attribute will make `serde` look at the name of the struct as the field name/key, so that it won't require creating a field inside the struct.

it should work as follow:
```rust
#[derive(Serialize, Deserialize)]
#[serde(serialize_as_field)]
struct Stream(Vec<u8>);


fn main() {
    let stream = Stream(vec![1u8; 4]);
    let result = serde_json::to_string(&stream).unwrap();

    assert_eq!(result, "{\"stream\":[1,1,1,1]}")

}
```

**Comment by jplatte** [comment]
I've requested a more general feature that would enable the same use case [here](https://github.com/serde-rs/serde/issues/1510), but it was rejected. I doubt this feature has a chance to be implemented.

**Comment by exFalso** [comment]
This would be nice indeed

**Comment by dtolnay** [comment]
I would prefer not to build this into serde_derive.

The impls you want serde_derive to generate should be easy enough to handwrite.
