### ISSUE TITLE
Feature request: use field name as tag

### ISSUE THREAD

**Issue by upsuper** [serde-rs/serde#1520]
For example, I'd like to deserialize something like:
```json
[
  { "foo": "xxxx", "a": 1 },
  { "bar": "yyyy", "a": 2, "b": true },
]
```
into
```rust
enum FooBar {
    Foo(Foo),
    Bar(Bar),
}
struct Foo { foo: String, a: i32 }
struct Bar { bar: String, a: i32, b: bool }
```
using whether the field `foo` and `bar` exist as the tag of what to parse.

This is currently doable via `untagged`. The problem is that if you use `untagged` on a relatively deep type, you can easily get something like
> data did not match any variant of untagged enum FooBar

which is sometimes not very helpful for figuring out where the issue is.

Alternatively, maybe there can be something like `#[serde(untagged = "shallow")]`, which only checks the field names for picking variant, rather than trying to parse the whole tree.

**Comment by edulix** [comment]
I second this. Is this very difficult to implement @dtolnay ? Is there any (hacky?) way to workaround it for now? Getting the `data did not match any variant of untagged enum FooBar` reduces a lot the understandability of errors.

**Comment by dtolnay** [comment]
I would prefer not to build something for this into serde_derive, but I would be excited for someone to create a more fully featured enum deserialize macro that could cater to this and other patterns.
