### ISSUE TITLE
dev-dependencies are not allowed to be optional

### ISSUE THREAD

**Issue by gnzlbg** [serde-rs/serde#1535]
Because `dev-dependencies` are not allowed to be optional (cc @ehuss), I have to make `serde_test` an unconditional `dev-dependency`, which means that it will always be part of the dependency graph of my crate when building it, and because `serde_test` requires `std`, this means that building my crate ends up always linking against the standard library.

My crate is a `#[no_std]` crate, so I cannot accept that, therefore, I cannot use `serde_test` for testing.

The only workaround I can think of, is to make `serde_test` an optional dependency of `serde`, and for `serde` to re-export it when this optional dependency is enabled. This way, I can optionally depend on serde, without any features, and I can add a cargo feature to my crate that is enabled only for testing, and that enabled the `serde_test` feature of `serde`. This would allow me to pull in `serde_test` optionally only when testing, allowing my application to only link against the standard library there, and not unconditionally (as it would be caused by an unconditional dev-dependency to `serde_test`).

**Comment by gnzlbg** [comment]
I suppose that, alternatively, I can add `serde_test` as an optional, non-dev dependency. Hmm. Don't know what will work best.

**Comment by dtolnay** [comment]
Currently serde_test is designed to depend on serde so serde can't also depend on serde_test. I would recommend giving your crate an optional ordinary dependency on serde_test and following up with Cargo to improve the flexibility on their end.

**Comment by Anders429** [comment]
Ran into this same issue, and wanted to add here that using [-Z features=dev_dep](https://github.com/rust-lang/cargo/issues/7916) on `nightly` was sufficient to resolve this problem.
