### ISSUE TITLE
How to choose what field to process at runtime

### ISSUE THREAD

**Issue by sansumbrella** [serde-rs/serde#1538]
I have a data structure and visitor set up to parse streaming data for handling multi-gigabyte files. It looks like the following, so I can read the "features" property of massive JSON files:

```
#[derive(Deserialize, Serialize)]
struct CollectionWrapper {
    #[serde(
        deserialize_with = "deserialize_stream",
        rename(deserialize = "features")
    )]
    features_processed: u64,
}
```

I use it to read JSON files that look like:
```
{
  "ignored_property": "whatever",
  "more": …,
  "features": [{name: "something"}, …]
}
```

This works well, however: I would like to make the field I am deserializing configurable. For example, I would like to pass a flag at runtime to specify the name of the `"features"` property in case I have some different JSON. Right now, I can only see how to change this at compile-time, and it doesn't feel right to edit source and recompile just to handle slightly different data layouts.

Is it possible to tell serde the name of fields at runtime? How might I approach that?

I tried driving a visitor that implemented both `visit_map` and `visit_seq`. While I was able to find out dynamically whether a map entry had a key matching what I passed in, I wasn't able to figure out how to proceed with streaming parsing after that point. The visitor doesn't have a reference to the deserializer and seems to load the whole value into memory as part of the map visiting.

Thanks!

**Comment by sansumbrella** [comment]
The closest I've gotten to specifying at runtime is with the visitor implementation below. Is there a way to deserialize the `next_value` (which I know to be an array) in a stream?

```
        fn visit_map<M>(self, mut map: M) -> Result<Self::Value, M::Error>
        where
            M: MapAccess<'de>,
        {
            while let Some(key) = map.next_key()? {
                let key: String = key;
                if key == self.collection_name {
                    // could this perhaps descend into our visit_seq?
                    // how do I stream from here?
                    let v: serde_json::Value = map.next_value()?;
                    println!("value found: {:?}, {}", v, v.is_array());
                } else {
                    map.next_value::<IgnoredAny>()?;
                }
            }
            Ok(0)
        }
```

I'd love to replace the next_value handling with something like:
```
let val: SeqAccess = map.next_value()?;
self.visit_seq(val);
```
That way I could handle the sequence nicely, but SeqAccess can't be instantiated as it's a trait.

**Comment by dtolnay** [comment]
> ```rust
> // could this perhaps descend into our visit_seq?
> // how do I stream from here?
> ```

You would need to call map.next_value_seed with a visitor for processing the value. Something like:

```rust
struct FeaturesVisitor {...}

impl<'de> DeserializeSeed<'de> for FeaturesVisitor {
    type Value = ??;
    fn deserialize<D>(self, deserializer: D) -> Result<Self::Value, D::Error>
    where
        D: Deserializer<'de>,
    {
        deserializer.deserialize_seq(self)
    }
}

impl<'de> Visitor<'de> for FeaturesVisitor {
    type Value = ??;
    fn visit_seq ...
}

map.next_value_seed(FeaturesVisitor {...})
```

The pseudocode you wrote is nicer but would be blocked on [GAT](https://github.com/rust-lang/rust/issues/44265).
