### ISSUE TITLE
Help - Serde default in macro

### ISSUE THREAD

**Issue by 0x1793d1** [serde-rs/serde#1539]
Hi,

I want to use a macro to generate a config structure.
My macro will have a default value for each field as argument.
Is there a way to do so with Serde ? Because serde(default) attribute is using a static string that points to a function, I don't know how to do.

My macro call will looks like :

```rust
config! {
    server: ServerConfig {
        ip_address: IpAddr -> Ipv6Addr::UNSPECIFIED,
        port: u16 -> 8080u16,
    },
}
```

Thanks

**Comment by dtolnay** [comment]
Yep -- you might consider generating something like:

```rust
#[derive(Deserialize)]
#[serde(default)]
struct ServerConfig {
    ip_address: IpAddr,
    port: u16,
}

impl Default for ServerConfig {
    fn default() -> Self {
        ServerConfig {
            ip_address: IpAddr::V6(Ipv6Addr::UNSPECIFIED),
            port: 8080,
        }
    }
}
```

**Comment by 0x1793d1** [comment]
It works!
Thanks!
