### ISSUE TITLE
Serializing an enum as an array where the first element is the tag

### ISSUE THREAD

**Issue by evilbluebeaver** [serde-rs/serde#1540]
Hi.

I have a data structure:
```
#[derive(Deserialize, Serialize, Debug, PartialEq)]
enum Packet {
    Create (Room, ()),
    Terminate (Room, ()),
}
```

When I serialize it I get json
`{"Create":["room",null]}`

But I need it to be like this
`["Create", "room", null]`

Is there a simple way to achieve this with macro options or the only way is to write my own Serializer/Deserializer?

**Comment by jplatte** [comment]
Serializing an `enum` as an array where the first element is the tag isn't possible with `#[derive(Serialize)]`. You could add another tuple element to the variants that always serializes to the tag name and use it in conjunction with `#[serde(untagged)] `, but I'd recommend a manual implementation for this case.

**Comment by dtolnay** [comment]
If the above comment doesn't get you completely unblocked, I would recommend taking this question to any of the resources shown in https://github.com/serde-rs/serde#getting-help.
