### ISSUE TITLE
access tag field on externally tagged enums

### ISSUE THREAD

**Issue by tobias-o** [serde-rs/serde#1552]
I have following structure definition:

```rust
#[derive(Debug,Clone,Deserialize)]
pub struct NamedEnum {
    pub name: String,

    #[serde(flatten)]
    pub variants: Enum,
}

#[derive(Debug,Clone,Deserialize)]
#[serde(tag = "name")]
pub enum Enum {
    Variant1(Variant1Definition),
    Variant2(Variant2Definition),
}

#[derive(Debug,Clone,Deserialize)]
pub struct Variant1Definition {
  pub field1: String,
}

#[derive(Debug,Clone,Deserialize)]
pub struct Variant2Definition {
  pub field2: String,
}
```

Input docs look like this:
```JSON
{"name": "Variant1", "field1": "value1"}
```
and
```JSON
{"name": "Variant2", "field2": "value2"}
```

It works if I deserialize docs to `Enum`, but then I can't access `name`.
If I try to deserialize to `NamedEnum`, it fails to match because `name` is consumed already.

I have a large number of variants and don't want to manually type all match clauses to get the name.
Any other ideas how to solve/work around this problem?

playground here: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=af42b2b2902dc5d58ba0498ff8d28321

PS: this is my first issue on serde and I'm not exactly a rust expert. I'm happy for any input :smiley:

**Comment by dtolnay** [comment]
I would recommend not storing the name as String in NamedEnum, but instead deriving a method to go from &Enum to &'static str. This macro may already exist on crates.io if you do some searching.

```rust
use serde::Deserialize;

#[derive(Deserialize, Debug, VariantName)]
#[serde(tag = "name")]
enum Enum {
    Variant1(Variant1Definition),
    Variant2(Variant2Definition),
}

// generated by #[derive(VariantName)]
impl Enum {
    fn variant_name(&self) -> &'static str {
        match self {
            Enum::Variant1(_) => "Variant1",
            Enum::Variant2(_) => "Variant2",
        }
    }
}

#[derive(Deserialize, Debug)]
struct Variant1Definition {
    field1: String,
}

#[derive(Deserialize, Debug)]
struct Variant2Definition {
    field2: String,
}

fn main() {
    let j = r#"{"name": "Variant1", "field1": "value1"}"#;
    let e: Enum = serde_json::from_str(j).unwrap();
    println!("{:?}\nname = {:?}", e, e.variant_name());
}
```

**Comment by tobias-o** [comment]
Thanks for your input. The crate I'm looking for is strum_macros https://crates.io/crates/strum_macros
