### ISSUE TITLE
IgnoredAny doesn't handle enums, leading to a confusing error message

### ISSUE THREAD

**Issue by jyc** [serde-rs/serde#1558]
If IgnoredAny gets an enum, serde outputs the error message "invalid type: enum, expected anything at all", which doesn't make much sense. This is because IgnoredAny doesn't have a visit_enum impl. I think the intent might make sense if IgnoredAny doesn't know how to deserialize the enum. But "expected anything at all" doesn't really make sense as an error when an enum is clearly something.

**Comment by jyc** [comment]
Actually, after thinking about it, I think this is always buggy behavior. If you agree I'd be happy to open a quick PR.

**Comment by dtolnay** [comment]
Thanks! I released 1.0.94 with a fix.
