### ISSUE TITLE
Add simple binary encoding (SBE) support

### ISSUE THREAD

**Issue by gnzlbg** [serde-rs/serde#156]
Simple Binary Encoding is a serialization format used in financial trading. For an overview see [this post](https://capnproto.org/news/2014-06-17-capnproto-flatbuffers-sbe.html) that compares cap'n'proto, flatbuffers, and sbe. In a nutshell it is a non-random-access, zero copy, serialization format.

**Comment by dtolnay** [comment]
I am closing this because I do not plan to dedicate Serde developer time to implementing this. I would love if anybody steps up to implement SBE support for Serde in a separate crate.
