### ISSUE TITLE
Serialize trait should have `ignore` method

### ISSUE THREAD

**Issue by singpolyma-shopify** [serde-rs/serde#1564]
As per https://github.com/sfackler/serde-transcode/issues/7 transcode (and possibly other cases) needs the `SerializeMap` instance to always call `serialize` on the value in order to advance the underlying `Deserializer`.  As a workaround for this I must create a `Serializer` that throws away all input and use it to call `serialize` on any map values I wish to filter out / ignore.  It would be great if there were a method like `ignore()` on `Serialize` so I could call that to trigger advancing the underlying  state without needing a `Serializer` since I don't want  to consume any data.

**Comment by dtolnay** [comment]
I think I would prefer not to build this into serde, but it would be reasonable for a separate crate to provide a `Serializer` which has that behavior.
