### ISSUE TITLE
JSON scheme support?

### ISSUE THREAD

**Issue by darakian** [serde-rs/serde#1566]
Hey all,

just a quick question. Is json scheme support on the roadmap? 
http://json-schema.org
I've got a project that I'm about to start work on that would benefit greatly from being able to create structs from schemes and then deserialize to said structs.

**Comment by dtolnay** [comment]
https://transform.now.sh/json-schema-to-rust-serde/ has an implementation of this. I don't think the implementation is Rust, so if you need this as a Rust library then there would be some porting involved.

**Comment by darakian** [comment]
Oh man that's cool. It would be nicer to have it in the code itself, but for my current objective this is more than enough. Thanks!
