### ISSUE TITLE
Data format with root typed `(Key, Value)` support

### ISSUE THREAD

**Issue by luojia65** [serde-rs/serde#1573]
Recently I came across a task to write a ser/de library for the NBT format. The problem I met is that, if we regard all formatted files as trees, this format requires a name for every tree root, which we typically do not meet them in JSON, etc. To raise an example, here's a piece of JSON document:
```json
{
  "DataVersion": 19133,
  "Dimension": -1,
  "abilities": {
    "walkSpeed": 0.1,
    "flySpeed": 0.05,
    "mayfly": false,
  }
}
```
Note that there is no something like `rootName: {` in the first line, means that the tree root is a JSON value, instead of a key-value pair. Now here's an equivalent NBT document (transcripted, it was originally a compact binary format):
```
Compound "Player"
  Int "DataVersion" 19133
  Byte "Dimension" -1
  Compound "abilities"
    Float "walkSpeed" 0.1
    Float "flySpeed" 0.05
    Boolean "mayfly" false
  EndCompound
EndCompound
```
The root is a key-value pair with key named _Player_. In fact, all NBT units (or _tags_ as they love to call them) have firstly its type described, and secondly the key name, then finally the value: that means the root tag must have a name. This is different from JSON, where the root is nameless thus is only a value.

To describle NBT format, I can only think of one way: serialize with key added as a parameter in `to_xxx` functions, and when deserializing I may discard this name or return the name as well as the value. For example I have to write: 
```rust
let v = MyStruct { ... }; // inner fields omitted
let s = to_string_transcript(&value, "RootName")?;
let (v, key): (MyStruct, _) = from_string_transcript(s)?;
assert_eq!(key, "RootName");
```
Instead of:
```rust 
let v = MyStruct { ... }; // inner fields omitted
let s = to_string_transcript(&value)?;
let v: MyStruct = from_string_transcript(s)?;
```
... which are easier to understand and could be much simpler. 
In my opinion, if we design functions like this, users have to remember this different convention of parameters (extra key needed), and the API convention is not as graceful as other serde libraries like serde-json and serde-yaml.
Is there a better solution if I use serde to support the NBT format?

**Comment by dtolnay** [comment]
You could use the name of the top level struct as the root name. For example [RON](https://github.com/ron-rs/ron#rusty-object-notation) does that. It can be controlled by a serde rename attribute on the struct as necessary.

**Comment by luojia65** [comment]
@dtolnay Thank you! That would be a nice solution. I've done by using top-level struct name in my project.
