### ISSUE TITLE
Unable to derive Serialize/Derserialize `type annotations required: cannot resolve `T: ...::Deserialize<'de>``

### ISSUE THREAD

**Issue by gatoWololo** [serde-rs/serde#1578]
I'm sorry for asking about my specific problem but I am beyond stuck.

I'm trying to create a simple wrapper struct around ipc-channel::ipc::{IpcReceiver, IpcSender}. My struct looks like:
```rust
pub struct IpcReceiver<T>
where T: for<'de> Deserialize<'de> + Serialize
{
    receiver: ipc::IpcReceiver<(DetThreadId, T)>,
    ... // Extra fields all implementing Derserialize/Serialize
}
```

The above type checks just fine. When I try to add `#[derive(Serialize, Deserialize)]` things fail: `lifetime name `'de` shadows a lifetime name that is already in scope`

Which makes sense, so I change the name to `'dde`. Then I get a `type annotations required: cannot resolve T: _IMPL_DESERIALIZE_FOR_RecordReplayMode::_serde::Deserialize<'de>`

I have looked at the following resources:
https://serde.rs/attr-bound.html
Issue #890 
Issue #891 
https://github.com/serde-rs/json/issues/469
https://stackoverflow.com/questions/51464671/cannot-resolve-t-serdedeserializede-when-using-serialize-and-deserialize
https://serde.rs/lifetimes.html#trait-bounds
https://www.reddit.com/r/rust/comments/7yzn25/trying_to_implement_serialize_deserialize_with/

So I have a sense of what's going on but can't seem to get it working.

The problem seems to stem from the definitions of IpcReceiver/IpcReceiver. As I'm able to deal with the generic when commenting out the channel:
```rust
#[derive(Debug, Serialize, Deserialize)]
#[serde(bound(deserialize = "T: Deserialize<'de>"))]
pub struct IpcReceiver<T> {
    // receiver: ipc::IpcReceiver<(DetThreadId, T)>,
    buffer: RefCell<HashMap<DetThreadId, VecDeque<T>>>,
    metadata: RecordMetadata,
}
```
This works and compiles. However, when adding back the receiver I get:
```
error[E0277]: the trait bound `T: _IMPL_DESERIALIZE_FOR_RecordReplayMode::_serde::Deserialize<'_>` is not satisfied
  --> src/ipc.rs:24:5
   |
24 |     receiver: ipc::IpcReceiver<(DetThreadId, T)>,
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `_IMPL_DESERIALIZE_FOR_RecordReplayMode::_serde::Deserialize<'_>` is not implemented for `T`
   |
   = help: consider adding a `where T: _IMPL_DESERIALIZE_FOR_RecordReplayMode::_serde::Deserialize<'_>` bound
   = note: required because of the requirements on the impl of `for<'de> _IMPL_DESERIALIZE_FOR_RecordReplayMode::_serde::Deserialize<'de>` for `(thread::DetThreadId, T)`
   = note: required by `ipc_channel::ipc::IpcReceiver`
```

Adding back the trait bound:
```rust
#[derive(Debug, Serialize, Deserialize)]
#[serde(bound(deserialize = "T: Deserialize<'de>"))]
pub struct IpcReceiver<T>
where T: for<'dde> Deserialize<'dde> + Serialize
{
    receiver: ipc::IpcReceiver<(DetThreadId, T)>,
    buffer: RefCell<HashMap<DetThreadId, VecDeque<T>>>,
    metadata: RecordMetadata,
}
```
I get:
```
error[E0283]: type annotations required: cannot resolve `T: _IMPL_DESERIALIZE_FOR_RecordReplayMode::_serde::Deserialize<'de>`
  --> src/ipc.rs:19:28
   |
19 | #[derive(Debug, Serialize, Deserialize)]
   |                            ^^^^^^^^^^^
   |
   = note: required by `_IMPL_DESERIALIZE_FOR_RecordReplayMode::_serde::Deserialize`
```

I know trait bounds in struct definitions are not recommended. I believe I need them because the way IpcReceiver/Sender are defined:
```rust
#[derive(Debug)]
pub struct IpcReceiver<T> where T: for<'de> Deserialize<'de> + Serialize {
    os_receiver: OsIpcReceiver,
    phantom: PhantomData<T>,
}
```

All fields inside my struct implement `Deserialize` and `Serialize`. I can't really understand why I can't get it working. Any help would be beyond appreciated.

Thanks.

**Comment by dtolnay** [comment]
This is a compiler bug: https://github.com/rust-lang/rust/issues/41617. The only way I know to get this working is to remove the bounds on IpcReceiver (which shouldn't be there because trait bounds are for behavior and not for data; https://github.com/rust-lang/rust-clippy/issues/1689).

**Comment by gatoWololo** [comment]
Thanks. :sweat: 

I'll look into removing the trait bounds for IpcReceiver then.
