### ISSUE TITLE
Unserialized PHP serialized string

### ISSUE THREAD

**Issue by bcashier** [serde-rs/serde#1582]
Hi,

Is there a way to Desierialize string serialized in PHP side, Here it is:

`number|i:1;test|s:6:"string";array_number|a:2:{i:0;i:1;i:1;i:2;}array_string|a:2:{i:0;s:5:"arr 1";i:1;s:5:"arr 2";}`

Let me know if it's possible

Thanks in advance

**Comment by dtolnay** [comment]
Hi @bcashier, sorry that no one was able to provide help here. If this is still an issue, you could try taking this question to any of the resources shown in https://github.com/serde-rs/serde#getting-help.
