### ISSUE TITLE
Resilency for parse errors on subfields

### ISSUE THREAD

**Issue by david-mcgillicuddy-moixa** [serde-rs/serde#1583]
I have a use case where, as long as I have a valid json document, then parses should always succeed. This is so that I can deal with missing or invalid fields in code and recover from them. Things like `serde(default)` don't handle _invalid_ sections, only missing ones as far as I can tell.

According to https://github.com/serde-rs/serde/issues/464, this is not going to be supported in the general case which makes sense.

My approach has been an untagged and slightly richer `Result`:
```
#[derive(Deserialize, Debug, Clone, Serialize)]
#[serde(untagged)]
pub enum TryParse<T> {
    Parsed(T),
    ParseFailed(HashMap<String, Value>),
    NotPresent
}
impl<T> Default for TryParse<T> {
    fn default() -> Self { TryParse::NotPresent }
}
```
which you can see working on the playground: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=64cb1cae4b70501a908a51fc584539b2
```
#[derive(Deserialize, Debug)]
pub struct Foo4 {
    #[serde(default)]
    inner: TryParse<Inner>,
    
    #[serde(flatten)]
    other: HashMap<String, Value>,
}
```
which will correctly parse whether or not `inner` is present, and also if `inner` is present but fails to parse.

Does anybody have a better way to appoach this? Other options I can immediately see are:
1) Don't use `serde_derive::Deserialize` and make a custom deriver that has the behaviour I want
2) Deserialize once into `serde_json::Value` and then manually translate that into my struct

**Comment by dtolnay** [comment]
The best solution I know would be https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=e7320f84b125bcac0c41f349b03d2f46. That handles NotPresent values without needing a serde(default) attribute on the field.

**Comment by david-mcgillicuddy-moixa** [comment]
That looks great thanks! Feel free to close this or keep it up for discussion(?).

**Comment by johan-bjareholt** [comment]
I'm trying to do a similar thing but skipping elements in a sequence that fails to be parsed.
I'm very close to getting it to work, but when a sub-type is of invalid type and it's either an dict or an seq I get an infinite loop.

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=caad1a13418f548c8b9ec85bbea57879

Any tips on how to solve this?

**Comment by jonasbb** [comment]
@johan-bjareholt The deserializer can get stuck if it runs into an error, because it does not consume all tokens and then you end up in a loop where it tries to process the same tokens. The workaround is to first deserialize into something which is ensured to not fail and then convert this to the final result, which can fail. That is what both solutions in this thread do. The variant by dtonaly makes this explicit by deserializing into a `Option::<serde_json::Value>` and then deserialize the final `T` from this `serde_json::Value`. The solution by david-mcgillicuddy-moixa uses an untagged enum, which does something similar internally.

**Comment by johan-bjareholt** [comment]
@jonasbb Thanks a lot, worked perfectly!

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=caad1a13418f548c8b9ec85bbea57879
