### ISSUE TITLE
Unable to fetch struct name if it contains flattened fields

### ISSUE THREAD

**Issue by luojia65** [serde-rs/serde#1584]
Recently I wrote a serializer with serde for a given format. There is one thing different in my format is that it requires a name for every formatted files; or if regarded as trees, every tree root must be named. I chose to fetch the struct name for root name, but there is one condition where I'm unable to fetch them. Consider this:
```rust
#[derive(Serialize)]
#[serde(rename = "book")] // <- the struct is renamed here
struct Book {
    resolved: Option<i8>,
    #[serde(flatten)]  // <- serde flatten attribute 
    extra: Option<Extra>,
}

#[derive(Serialize)]
struct Extra {
    generation: i32,
    author: &'static str,
    title: &'static str,
}
``` 
When the root struct `Book` contains a flattened struct, I expect the root struct would still be regarded as a struct. But (if I am right) it is actually procceeded as a map instead of a struct. Meanwhile in my serializer, the `serialize_map` function holds this signature as `serde::Serializer` trait requires:
```rust
fn serialize_map(self, _len: Option<usize>) -> Result<Self::SerializeMap>
```
which (unlike `serialize_struct`) does not have a `name` field, meaning the function is unable to capture the root struct name. That means, if I want to use `#[serde(flatten)]` attribute, I have to think of another way to pass the root name; if I need to use the struct name directly as root name, I have no way to use serde flatten attribute which could be useful in my applications.

Are there any solution for this situation?

To reproduce this bug, I put my code into [this](https://github.com/luojia65/coruscant) repository. Run `cargo run --example nbt-option-flatten` command in the cloned project root, the actual output contains:
```
Compound ''
  Byte 'resolved' 1
  Int 'generation' 0
  String 'author' luojia65
  String 'title' hello
EndCompound
```
in the first line, the root name follows default as an empty string, instead of `Compound 'book'` as I expected. I changed the type of `extra` from `Option<Extra>` to `Extra`, but the output is same with an empty root name.

---

Edit: I found a serde code snip [here](https://github.com/serde-rs/serde/blob/e9cd73f78e4d8dc03189ef11afa28df3f4f7000b/serde_derive/src/ser.rs#L292). Should this struct-to-map be a feature or a bug?

**Comment by luojia65** [comment]
Maybe produced by this change: https://github.com/serde-rs/serde/commit/58d52e784b1a6eb71bbd05695fa97b24638ec094 . Is this a feature or a bug? @mitsuhiko

**Comment by dtolnay** [comment]
I think I would prefer not to build an additional attribute into serde_derive for this, but it would be reasonable for a third-party Serialize derive implementation to provide an alternative flatten implementation which is a closer fit for this use case.
