### ISSUE TITLE
Serializing variant types requires static variant string

### ISSUE THREAD

**Issue by rendaw** [serde-rs/serde#1585]
I'm trying to implement [luxem](https://gitlab.com/rendaw/luxem) and having an intermediate type-less representation like Value in JSON is useful in various workflows.  luxem has a "type" construct to represent variants and this is also explicitly representable in Value.

However, passing Value back into a serializer is a problem because the serialize_*_variant methods require the variant name be a string with static lifetime, but the `Value::Typed(String, Value)` element which contains the variant name is not generally static.  I presume the original intent is that the variant types would only refer to actual Rust type names which would be generated as static constants, but I'm not sure how to handle this in a way that doesn't force some un-collectable global storage.

Is there any way the variant string lifetime could be reduced to that of the serializer perhaps?  Or is there another solution that you could suggest here?

**Comment by dtolnay** [comment]
This is intentional in the serde data model. There is a tension between what we require Serialize impls to guarantee and what we permit Serializer impls to assume. Data that is "tagged" with a non-static string does not qualify as a serde enum and its Serialize impl would need to pick a different serde data model representation for that data.

**Comment by rendaw** [comment]
Thanks for taking a look!  This explanation seems circuitous, but perhaps I missed some nuance.  Would you mind elaborating?  Is this a just sort of "this would be a breaking change and our design is finalized at this point" thing?

**Comment by dtolnay** [comment]
That isn't it. To elaborate slightly, when I say "this is intentional in the serde data model" it means those APIs require static strings on purpose. Whether there were breaking changes being made or not, we would want static strings there. When I say "there is a tension between what we require Serialize impls to guarantee and what we permit Serializer impls to assume" it means that in this aspect of the API adding freedom to Serialize impls by removing the static bounds implies taking away freedom from Serializer impls which makes some kinds of Serializers impossible to write.

**Comment by rendaw** [comment]
First of all, thanks for engaging with me on this.

Okay, right, maybe I complicated things by suggesting reducing the lifetime "to that of the serializer."  It still seems strange to me that you'd need to hold on to the variant name for longer than it takes to write it to the stream or copy to some internal storage.

I thought you might be referring to FlatBuffers which for zero copy would require the data to live until the kernel's finished putting it on the wire, but the FlatBuffers impl copies the data to internal storage so that doesn't seem to be the case.  Do you have an example of a class of Serializer that relies on this?

I'm assuming by impossible you mean "at current speeds" because any implementation that needed a longer lifetime for the variant name could always create an owned copy.

**Comment by dtolnay** [comment]
Here is one example I found of a Serializer that leverages the static bound:
https://docs.rs/oauth2/3.0.0/oauth2/helpers/fn.variant_name.html

Your comment about "at current speeds" is reflective of the tradeoff between what Serialize impls must guarantee and what Serializer impls may assume. While it's possible to make different sets of choices which result in Serializer impls being required to run slower, or being required to drop support for no_std by allocating, but those choices wouldn't be better overall.

**Comment by rendaw** [comment]
> https://docs.rs/oauth2/3.0.0/oauth2/helpers/fn.variant_name.html

Thanks!  The original use case of that function didn't need the static bound -- AFAICT it could have been trivially changed to use the lifetime of the data itself.  Since then the use case has been deleted and I can't find evidence of it being used anywhere else (within the project or without) so it's effectively dead code.

> those choices wouldn't be better overall

So basically this optimization choice is part of the design and that part of the design is final?  If that's the case, fine.  I'm not going to twist your hand.

My insistence on this issue mainly revolves around the fact that rejecting a class of (already primarily supported) use cases in favor of an optimization that is not actually used seems a little strange.

Dynamic data (via `Value`) is a feature of almost every major Serde crate.  The YAML and RON crates have fairly visible omissions from their `Value` types due to this restriction, and I'm sure there are other data formats with explicit types similarly restricted.  I can't imagine you'd say "we intentionally support all first class dynamic data _except_ variants."

Similarly it's not like serializers can't already deal with non-static strings.  Variant names are just another string data and every Serde crate I'm aware of is already able to handle non-static strings as a primary data type... using static buffers or global allocators or whatever.  So I don't believe `no_std` is an obstacle here either.

I realize that this _is_ in fact an entrenched decision at this point, but I'd appreciate it if this would be seriously considered for the next major release or whatever the next opportunity for breaking design changes presents itself.

**Comment by inikulin** [comment]
@dtolnay why not change `&'static str` to `Cow<'static, str>` it will maintain the static lifetime, but at the same time will allow serialization formats that have explicit enums (though with some overhead).
