### ISSUE TITLE
Arbitrary serialization/deserialization

### ISSUE THREAD

**Issue by David-OConnor** [serde-rs/serde#1588]
There are three categories this could fall into: Request for documentation, request for feature, or out-of-scope of Serde.

I'm looking to serialize and deserialize a struct. The docs would be on [this page, or it's deserialize equiv](https://serde.rs/impl-serialize.html).

Example that works:
```rust
#[derive(Deserialize, Serialize)]
struct SerializableData {
    field_a: String,
    field_b: Option<String>
}

struct TypedData {
    field_a: TypeA,
    field_b: TypeB
}
```
will work, where you use glue code to convert between the two, which might be `ToString`, `FromStr` etc implementations, or custom methods/functions. How can we skip the intermediate `SerializableData` struct, and just use the typed one? The examples of how to implement `Serialize/Deserialize` in the listed docs page don't seem to include anything obvious. Desired pseudo-code:
```rust
struct TypedData {
    field_a: TypeA,
    field_b: TypeB
}

impl Serialize for TypedData {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        Ok(format!("{}, {}", self.field_a.to_string(), self.field_b.custom_serialize()))
    }
}
// Similar implementation for Deserialization
```
Where when we use whatever serialize sub-lib (JSON, TOML, etc) would auto convert to-from the typed data, without calling the to_string() etc methods and convert between serializable(with only built-in types like String, u32 etc) and custom-typed structs.

Based on this (to-me) seeming like obvious desired functionality, yet not being transparent from the docs, I suspect I have incorrect expectations about what `serde` is expected to do.

**Comment by dtolnay** [comment]
If you want the type to be serialized as the string `"{}, {}"`, I would recommend using the serializer's [collect_str](https://docs.rs/serde/1.0.97/serde/trait.Serializer.html#method.collect_str) method from the Serialize impl.

```rust
serializer.collect_str(
    format_args!("{}, {}", self.field_a, self.field_b.custom_serialize()),
)
```

The Deserialize impl can then deserialize into a string and do whatever parsing to split it into fields.

```rust
let s = String::deserialize(deserializer)?;
...
```

**Comment by David-OConnor** [comment]
Thank you!
