### ISSUE TITLE
Implementing Default by deserializing empty struct

### ISSUE THREAD

**Issue by vorner** [serde-rs/serde#1592]
Hello

I use serde to read configuration. Parts of the configuration are optional and should take default values. This can now be done with the `#[serde(default)]` attribute on each value, eg:

```rust
fn default_max() -> usize { 1024 }
fn default_min() -> usize { 3 }
#[derive(Deserialize)]
struct Limits {
    #[serde(default = "default_max")]
    max: usize,
    #[serde(default = "default_min")]
    min: usize,
}
```

Now I want to put this into the bigger configuration structure. But I want to be able to omit the whole `limits` subobject, therefore I want to use `default` on that too.

```rust
#[derive(Deserialize)]
struct Config {
    #[serde(default)] 
    limits: Limits,
}
```

I can't really stick `#[derive(Default)]` on `Limits`, because that would give me all-zeroes instead of the default values I've provided. I can implement my own, but this is kind of duplicating code/boilerplate.

Would it be possible for serde to somehow support this? I have two ideas how to do it:
* Add some kind of `#[serde(derive_default)]` that, when attached to the `Limits` struct would instruct serde-derive to spit out an `impl Default` block too, based on the values would use when only parts of the struct were missing.
* Provide some function `fn serde_default<T: Deserialize>() -> T` that would build `T` by deserializing an empty object.

I might try implementing it, but I want to ask first if this looks sane and which way to take. Or, alternatively, if it already exists and I didn't notice it yet 😇.

**Comment by dtolnay** [comment]
You could write this without duplication as:

```rust
use serde::Deserialize;

#[derive(Deserialize)]
struct Config {
    #[serde(default)] 
    limits: Limits,
}

#[derive(Deserialize)]
#[serde(default)]
struct Limits {
    max: usize,
    min: usize,
}

impl Default for Limits {
    fn default() -> Self {
        Limits { max: 1024, min: 3 }
    }
}
```

**Comment by vorner** [comment]
I see, there's the way I must have missed, thanks! I should read the docs more thoroughly.
