### ISSUE TITLE
Assume most recent stable compiler if building without build script

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#1593]
Non-Cargo build systems (Bazel, Buck, ...) usually have other ways to encode things that Cargo typically expects build.rs scripts to do, like invoking bindgen, controlling features based on target, running code generators, etc.

It would be helpful if building Serde without its build script could produce a reasonable default modern Serde, rather than a pessimistic maximally compatible Serde with everything newer than rustc 1.13.0 disabled.

Concretely this will involve negating all the rustc-cfg emitted by the current build.rs.

```diff
- if minor >= 25 {
-     println!("cargo:rustc-cfg=core_duration");
- }
+ if minor < 25 {
+     println!("cargo:rustc-cfg=no_core_duration");
+ }
```

**Comment by taiki-e** [comment]
This has been done in https://github.com/serde-rs/serde/commit/55a7cedd737278a9d75a2efd038c6f38b8c38bd6 (serde), https://github.com/serde-rs/serde/commit/efaafd44580dc4776b45b78152fa2c5333d8f0a6 (serde_derive), and https://github.com/serde-rs/serde/commit/a5fd85a9eff9f767a3d4d2079e8d1cacd76f0355 (serde_test).

I also checked the other build scripts in the repository ([serde_derive_internals](https://github.com/serde-rs/serde/blob/ebd06eebdbbacf0c2d5beeb6ebddc77bb2e37bd4/serde_derive_internals/build.rs), [test_suite](https://github.com/serde-rs/serde/blob/f52d134c14f6904010d0a59107987b050b36b811/test_suite/build.rs)) and there was no code for the rustc version in either.

**Comment by dtolnay** [comment]
Great! Thank you.
