### ISSUE TITLE
DeserializedOwned doesn't work for structs with &'static refs?

### ISSUE THREAD

**Issue by Sushisource** [serde-rs/serde#1597]
This playground link illustrates what I'm talking about:

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=4dd075320b16d9a9c6edb4fce6993171

The error:
```
   |
17 |     let f: Foo = test("");
   |                  ^^^^ the trait `for<'de> serde::Deserialize<'de>` is not implemented for `Foo`
   |
   = help: the following implementations were found:
             <Foo as serde::Deserialize<'static>>
   = note: required because of the requirements on the impl of `serde::de::DeserializeOwned` for `Foo`
```

The signature of `test` is similar to `reqwest`s `json` function for deserializing responses. 

I think I understand why this can't work, but the docs aren't very clear on the subject. https://serde.rs/lifetimes.html#trait-bounds makes references to not explicitly using 'static in implementing Deserialize, but it doesn't mention anything about static refs simply not working with `#[derive(Deserialize)]`.

So, if this is in fact impossible, it'd be nice to have the docs call that out explicitly

Thanks! Love Serde!

**Comment by Sushisource** [comment]
Just after this I realized it still fails for me even replacing `'static` with `'a`, with something even more esoteric:

```
error: implementation of `serde::Deserialize` is not general enough
  --> src/main.rs:17:18
   |
17 |     let f: Foo = test("");
   |                  ^^^^
   |
   = note: `Foo<'_>` must implement `serde::Deserialize<'0>`, for any lifetime `'0`
   = note: but `Foo<'_>` actually implements `serde::Deserialize<'1>`, for some specific lifetime `'1`
```

This is definitely pretty confusing to encounter and would be worth mentioning in the section on Derive

**Comment by dtolnay** [comment]
derive(Deserialize) works fine with &'static references, but as with any type that borrows not owns its contents, you need to deserialize it from data that lives long enough.

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=17fa9a33ced083c056f280945e174653

**Comment by Sushisource** [comment]
Thanks, that makes sense. I'm mostly just wondering how this can be made more clear to people who run into this. It's not immediately obvious from reading the docs or any googling, until you think about the actual lifetime implications. 

I think maybe the confusion arises from expecting to see your typical "doesn't live long enough" type of error rather than "this isn't implemented". Perhaps a section in that same bit of the docs that says, hey, if you get this kind of error, it's probably this?
