### ISSUE TITLE
Use of deprecated mem::uninitialized

### ISSUE THREAD

**Issue by nico-abram** [serde-rs/serde#1598]
https://github.com/serde-rs/serde/blob/ce75418e40a593fc5c0902cbf4a45305a4178dd7/serde/src/ser/impls.rs

**Comment by dtolnay** [comment]
There is an allow(deprecated) on the call so this should be fine. The function is not being removed from the standard library and it is being used safely in Serde. There is no reason to bump the required compiler version because of this.
