### ISSUE TITLE
Errors should have a bound for Debug + Display

### ISSUE THREAD

**Issue by skade** [serde-rs/serde#160]
Error types (most notably `Deserializer::Error`) are not bounded to implement `Debug` or `Display`, which means that at all points where the actual `Error` type is not known, the error cannot be printed.

I'd suggest adding those bounds to the actual `Error` trait, perhaps through using `std::error::Error`. http://doc.rust-lang.org/std/error/trait.Error.html

**Comment by shahn** [comment]
Is this blocked only on the gitcop issue on the pull request? This would be really great to have.

**Comment by erickt** [comment]
No, that was me just dropping the ball. Merged it in to the 0.7.x (master) branch.
