### ISSUE TITLE
Please update proc_macro2, quote, and syn to v1.0

### ISSUE THREAD

**Issue by nbraud** [serde-rs/serde#1601]
Dear `serde` maintainers,

While packaging the newest versions of `proc-macro2`, `quote`, and `syn` in Debian (which all recently reached 1.0), I discovered that `serde` doesn't yet support those version.

I am attempting to make a patch for this, but there's a lot to fix, so help would be appreciated.

**Comment by dtolnay** [comment]
For now you may be able to cherrypick #1591, if that's an option for you.

**Comment by nbraud** [comment]
Thanks @dtolnay, I had missed that PR (probably only searched through open issues)

I ended up picking all the commits (except the `rust-format` one) since `v1.0.98`, since it didn't seem worth trying to backport only the necessary change.  Ran into some unrelated issues, but I can hopefully fix `serde_derive` in Debian tomorrow  :)
