### ISSUE TITLE
serde_derive 1.0.99 breaks field attributes

### ISSUE THREAD

**Issue by otavio** [serde-rs/serde#1603]
After updating my project, it fails to build with:

```
error: unknown serde field attribute `deserialize_with`
  --> updatehub-package-schema/src/definitions/target_permissions.rs:11:13
   |
11 |     #[serde(deserialize_with(de::octal_from_str))]
   |             ^^^^^^^^^^^^^^^^
```

Pinning `serde_derive` to `1.0.98` "fixes" it.

**Comment by dtolnay** [comment]
Hmm, that was never the syntax for deserialize_with attributes. The syntax is `#[serde(deserialize_with = "...")]`. It's an accident that we now catch this, but I would prefer not to go back to silently ignoring the invalid attribute.

https://serde.rs/field-attrs.html#deserialize_with

**Comment by otavio** [comment]
Ohh! Sorry for the noise.
