### ISSUE TITLE
Conditionally toggle `#[serde(deny_unknown_fields)]` at runtime

### ISSUE THREAD

**Issue by kennytm** [serde-rs/serde#1609]
Currently `#[serde(deny_unknown_fields)]` is a compile-time attribute applied to the whole container, meaning if we want to toggle whether to report an error at runtime (scenario: read a config file in strict mode vs quirk mode), we'll need to duplicate all related structs and perform lots of boilerplate transformation.

I suggest we extend `deny_unknown_fields` to provide a custom "fallthrough" behavior when an unknown field is encountered.

```rust
#[serde(deny_unknown_fields = "path")]
struct C { ... }

...

fn path<E: de::Error>(field: &str, expected: &'static [&'static str]) -> Result<(), E> {
    if is_strict_mode() {
        Err(E::unknown_field(field, expected))
    } else {
        warn!("encountered unknown field {} for type C", field);
        Ok(())
    }
}
```

**Comment by ericmarkmartin** [comment]
👍 
I'm working on a library right now and to get this behavior as is I have to have two identical structs

**Comment by dtolnay** [comment]
This is supported by using https://github.com/dtolnay/serde-ignored. The caller of serde_ignored::deserialize can decide whether to report an error after unknown fields were observed.
