### ISSUE TITLE
Binary Serializer `Option` issue.

### ISSUE THREAD

**Issue by chrisvittal** [serde-rs/serde#1611]
I have a binary format that I'm writing a serializer for. There's an odd method of handling `Option<T>` in containers like structs, tuples, and seqs.

Suppose we had the following struct:
```rust
struct Foo {
    a: Option<i32>,
    b: Option<f32>,
}
```
This is serialized as follows.
```
Foo { a: Some(1), b: Some(5.5) } // As Hex
00 01 00 00 00 00 00 b0 40
Foo { a: None, b: Some(5.5) }
01 00 00 b0 40
Foo { a: Some(1), b: None }
02 01 00 00 00
Foo { a: None, b: None }
03
```
Basically the two least significant bits in the first byte correspond to if `a` or `b` are `None`. This gets trickier with `struct Bar { a: i32, b: Option<f64> }` as the format would use the least significant bit of the first byte to indicate wether or not `b` is `None`.

How can I know which elements of the type are `Option` so I can know the appropriate number of `None` bits/bytes to reserve.

Thank you.

**Comment by dtolnay** [comment]
Hi @chrisvittal, sorry that no one was able to provide help here. If this is still an issue, you could try taking this question to any of the resources shown in https://github.com/serde-rs/serde#getting-help.
