### ISSUE TITLE
Incrementally serializing structs into an existing file

### ISSUE THREAD

**Issue by Rustinante** [serde-rs/serde#1612]
Hi, is there a way to serialize a struct into a file that already contains a list of such structs? For example, say we first serialize a `Vec<f32>` into file `f`. Can we append another `Vec<f32>` to `f` afterwards through serialization? If we know the first vector `N1` bytes and the second has `N2` bytes, would it be valid to deserialize these two vectors from `f` by providing the offsets? Thanks

**Comment by dtolnay** [comment]
Hi @Rustinante, this is supported but I am sorry that no one was able to provide help here. If this is still an issue, you could try taking this question to any of the resources shown in https://github.com/serde-rs/serde#getting-help.
