### ISSUE TITLE
Deserialize using a helper type

### ISSUE THREAD

**Issue by hoodie** [serde-rs/serde#1624]
Hi there, I'm currently facing a format I'd like to deserialize where a tagged enum field is implicitly of a certain type if the tag is missing. I can't currently figure out how to properly deserialize this, however I can create a similar struct where the given field is implicit. Is there some why to express "please deserialize this into this struct, if not, try this struct and convert"? or make the absence of the tag cause a fallback?

Thank you

**Comment by dtolnay** [comment]
Hi @hoodie, sorry that no one was able to provide help here. If this is still an issue, you could try taking this question to any of the resources shown in https://github.com/serde-rs/serde#getting-help.
