### ISSUE TITLE
Use @ binding operator when matching errors -- very minor nit

### ISSUE THREAD

**Issue by AlterionX** [serde-rs/serde#1625]
I needed to specialize `Deserialize` to a specific `SomeStruct<()>` instead of `SomeStruct<T>`. To do so, I read the docs, quickly gave up, used `cargo expand` to get the generated `Deserialize` from `#[derive(Deserialize)]`, and finally c+p the generated code into my project. Then, I proceeded to manually format the code.

I only included that since I thought it was amusing.

Anyways, in the process, I found a few examples of
```rust
_serde::export::Err(_err) => {
    return _serde::export::Err(_err);
}
```

I would like to replace all instances of this, and things similar to this with
```rust
__err @ _serde::export::Err(_) => {
    return _err;
}
```

`Course, the might (or even already, idk) implement the `Try` trait, but I think pattern binding (the `@` symbol) has been around since the beginning, so no Rust version issues. This is also one of my favorite parts of Rust, so I put them anywhere I can fit them.

[A link to the pattern binding issue for docs](https://doc.rust-lang.org/book/ch18-03-pattern-syntax.html#-bindings)

I was wondering if this is a good idea or not, as well as how to.

Anyways, super minor nit, but I think it's useful.

**Comment by CAD97** [comment]
The error return comes from `serde`'s custom [`try!` macro](https://github.com/serde-rs/serde/blob/master/serde_derive/src/try.rs) which improves compile times of generated code over `?` by skipping the `From::from` call. If we wanted to change this to use `@` pattern binding it would just be a change there. I don't really see any reason to prefer one way or the other, however. (In fact, the second branch could even be further simplified to just `__err => return __err,`.)

**Comment by dtolnay** [comment]
Your before/after snippets (copied below) are not equivalent because only the first allows the matched result and the returned result to have different Ok types. I am skeptical that changing the generated code to always require matched results and returned results to have identical Ok type would work in general.

```rust
_serde::export::Err(_err) => {
    return _serde::export::Err(_err);
}
```

```rust
__err @ _serde::export::Err(_) => {
    return _err;
}
```
