### ISSUE TITLE
Make it easier to serialize only one type

### ISSUE THREAD

**Issue by singpolyma-shopify** [serde-rs/serde#1627]
It is very common to want a serializer that errors on all but one type, for example for map keys I frequently want only String keys and nothing else.  In my project I also have a case where only a map is valid and anything else is an error.

For deserialize we can sort of get this by using the macro helper to dispatch everything to `any` and then having a catch-all condition there.  It would be very useful to have a similar official macro or macros for serialize to reduce the huge amount of boilerplate to create a serializer where every method is an error but one.

**Comment by dtolnay** [comment]
Thanks for the idea. I think I would prefer not to build anything for this directly into serde, but it would be reasonable to have a separate helper library making it easier to write those kinds of Serializer impls.
