### ISSUE TITLE
Custom deserialization for my type

### ISSUE THREAD

**Issue by xTachyon** [serde-rs/serde#1628]
Hello. I'm doing a custom data format for a format that is out of my control. Everything is good, except that the format is kinda stupid and not consistent in many cases.

What I'm trying to solve now is that sequences can be prefixed with the length as u8/u16/u32, but you can't figure it out what it is except if you know it.

So what I'm trying to do is:

```
#[derive(Serialize, Deserialize)]
#[serde(transparent)]
pub struct WeirdVec<T, S> {
  pub inner: Vec<T>,
  pub phantom: marker::PhantomData<S>
}
```

I would've liked to have a default implementation that would work for the other formats, and then specialize the ser/de process for my format and take into consideration the size in bytes of the length prefix.

I would like some advice on how can I do that/what would be the best way to handle this. Thanks.

**Comment by krnik** [comment]
Hi, wasn't this [page](https://serde.rs/impl-deserialize.html) useful?
It should cover the basics of the flow.

**Comment by dtolnay** [comment]
Hi @xTachyon, sorry that no one was able to provide more help here. If this is still an issue, you could try taking this question to any of the resources shown in https://github.com/serde-rs/serde#getting-help.
