### ISSUE TITLE
How rename_all can be used with multiple case convention.

### ISSUE THREAD

**Issue by ganimp84** [serde-rs/serde#1631]
`rename_all` attribute works perfectly fine with single case convention.

extern crate serde_derive;
extern crate serde_json;

#[derive(Debug, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum State {
    None,
    Expansion,
    War,
    CivilWar,
}

fn main() {
    let s = r#" "civil-war" "#;
    let c:State = serde_json::from_str(s).unwrap();
    println!("input: {} output: State::{:?}", s, c);
}

*Result*
input:  "civil-war"  output: State::CivilWar
-------------------------------------------

But, I wonder how it can be used with multiple case convention (such as `lowercase` & `kebab-case`). 

fn main() {
    let s = r#" "CIVIL-WAR" "#;
    let c:State = serde_json::from_str(s).unwrap();
    println!("input: {} output: State::{:?}", s, c);
}

Thanks in advance

**Comment by jplatte** [comment]
There's an existing feature request for this (if I understood your description correctly): https://github.com/serde-rs/serde/issues/1530

**Comment by dtolnay** [comment]
Closing in favor of #1530.
