### ISSUE TITLE
Support deserializing Box<Path>

### ISSUE THREAD

**Issue by heftig** [serde-rs/serde#1633]
I've tried to derive `Deserialize` for a `Rc<Path>` field, which fails.

If I understand the code correctly, it's missing a
```
forwarded_impl!((), Box<Path>, PathBuf::into_boxed_path);
```
so the `Rc<Path>` forwards to `Box<Path>` forwards to `PathBuf`.

**Comment by dtolnay** [comment]
Thanks, I would accept a PR to fix this.
