### ISSUE TITLE
rustdoc docs not rendering correctly

### ISSUE THREAD

**Issue by chrisvittal** [serde-rs/serde#1637]
I'm using firefox 69.0 on linux. I would expect the below image to be syntax highlighted and the `#` lines hidden. When I build and open the docs locally, they render correctly.
![image](https://user-images.githubusercontent.com/15916123/65216723-e473b200-da7f-11e9-804f-21613ab96138.png)

**Comment by dtolnay** [comment]
Where is that image from? It looks fine on https://docs.rs/serde/1.0.101/serde/de/trait.DeserializeSeed.html.

**Comment by dtolnay** [comment]
Ah, it's https://docs.serde.rs/serde/de/trait.DeserializeSeed.html. Let me take a look.

**Comment by chrisvittal** [comment]
Sorry, should have specified that as well.

**Comment by dtolnay** [comment]
Should be fixed now. Thanks for catching this! Apparently the beta compiler does not support 2018 edition documentation in a 2015 edition crate so we need to build docs.serde.rs with nightly.

**Comment by chrisvittal** [comment]
All good on my end. Thanks for fixing this so fast!
