### ISSUE TITLE
Prefixed JSON Values (not keys)

### ISSUE THREAD

**Issue by Sajjon** [serde-rs/serde#1640]
Hey! I'm a complete Rust n00b and it looks like `Serde` is the best De/Serialization SDK for Rust!

As a learning experience, I've begun writing a Rust Client library for the [Radix DLT](https://www.radixdlt.com/) ledger. The API's uses schema-less JSON solution, where each JSON **value**, contains a prefix telling what kind of data follows.

[Here are the JSON value prefixes implemented in the Radix DLT Java library](https://github.com/radixdlt/radixdlt-java/blob/release/1.0-beta.4/radixdlt-java/src/main/java/org/radix/serialization2/mapper/JacksonCodecConstants.java#L23-L31). These constants (prefixes) are then [used for various custom De/Serializers](https://github.com/radixdlt/radixdlt-java/blob/7555d2e1c7787efebe183962149f286aeed16250/radixdlt-java/src/main/java/org/radix/serialization2/mapper/JacksonJsonMapper.java#L61-L108) using Java Jackson, e.g. this custom [`JacksonJsonStringDeserializer`](https://github.com/radixdlt/radixdlt-java/blob/release/1.0-beta.4/radixdlt-java/src/main/java/org/radix/serialization2/mapper/JacksonJsonStringDeserializer.java) which parses all JSON strings prefixed with the ":str:" prefix.

And [here's example JSON](https://github.com/radixdlt/radixdlt-java/blob/release/1.0-beta.4/radixdlt-java/src/main/resources/universe/localnet.json#L2-L8), in short, something like this:
```json
{
	"some_string": ":str:Hello world",
	"some_amount": ":u20:115792089237316195423570985008687907853269984665640564039457584007913129639935",
	"some_bbytes": ":byt:A3hanCWf3pmR5E+i+wtWWfKleBrDOQduLb/vcFKOSt9o",
	"some_address": ":adr:JH1P8f3znbyrDj8F4RWpix7hRkgxqHjdW2fNnKpR3v6ufXnknor",
	"some_hash": ":hsh:0000000000000000000000000000000000000000000000000000000000000001"
}
```

Is it possible in Serde to specify global rules / global custom serializers? I saw [the page impl-deserializer](https://serde.rs/impl-deserializer.html), is that maybe what I wanna do?

Or ought I write custom [`Visitor`s](https://docs.serde.rs/serde/de/trait.Visitor.html)? How can I set up global rules using those?

Sorry, really big and open question, I understand if this is asking to much help.... Any help would be much much appricated!

**Comment by dtolnay** [comment]
Hi @Sajjon, sorry that no one was able to provide help here. If this is still an issue, you could try taking this question to any of the resources shown in https://github.com/serde-rs/serde#getting-help.
