### ISSUE TITLE
Way to tell which type is being serialized in `Serializer::serialize_seq`?

### ISSUE THREAD

**Issue by caelunshun** [serde-rs/serde#1642]
In the [NBT format](https://wiki.vg/NBT), sequences with certain types (`i8`, `i32`, and `i64`) are special cases and need to have their headers serialized differently than other types. Unfortunately, `Serializer::serialize_seq` does not provide the type being serialized, so it is impossible to account for this.

 The [hematite_nbt](https://github.com/PistonDevelopers/hematite_nbt) project has been trying to find a solution to this for a while now, and we have found that there is a hacky solution that only works with non-empty lists, but there is no way to do this correctly.

**Comment by dtolnay** [comment]
Yeah, the serde data model does not directly represent types in the absence of values, such as the type of a non-existing array element. Data formats which expect deeper type information might supplement with a "schema", whether handwritten or derived by a macro. I think serializing in https://github.com/flavray/avro-rs works this way.

**Comment by zeenix** [comment]
FWIW, I bumped into this issue with zvariant crate as well. So I had to require users providing the [type metadata](https://docs.rs/zvariant/2.0.0/zvariant/fn.from_slice_for_signature.html). To make things easier, I also allowed doing that through a [trait implementation](https://docs.rs/zvariant/2.0.0/zvariant/fn.to_bytes.html). However, it would have been great if serde provided type info for contained items so I didn't need any of that.
