### ISSUE TITLE
Build error when compiled from Git URL

### ISSUE THREAD

**Issue by vmx** [serde-rs/serde#1645]
I'm not sure if this is really a Serde bug or not. It purely depends on `Cargo.toml`. When Serde is added with a version (as you would normally do it) and it is fetched from crates.io, things are fine. If I replace it with the Git repository pointing to the same version, things fail.

My `Cargo.toml`:

```toml
[package]
name = "serdegitfail"
version = "0.1.0"
authors = ["Volker Mische <volker.mische@gmail.com>"]
edition = "2018"

[dependencies]
# This one works
#serde = { version = "1.0.101", features = ["derive"] }
# This one doesn't
serde = {git = "https://github.com/serde-rs/serde", tag = "v1.0.101", features = ["derive"]}
serde_json = "1.0.41"
```

The code is:

```rust
use serde::Serialize;
use serde_json::to_vec;

#[derive(Serialize)]
struct MyStruct {
    data: bool,
}

fn main() {
    to_vec(&MyStruct { data: true }).unwrap();
}
```

The error I'm getting is:

```console
$ cargo build
   Compiling serdegitfail v0.1.0 (/home/vmx/src/rust/misc/serdegitfail)
error[E0277]: the trait bound `MyStruct: serde::ser::Serialize` is not satisfied
    --> src/main.rs:10:12
     |
10   |     to_vec(&MyStruct { data: true }).unwrap();
     |            ^^^^^^^^^^^^^^^^^^^^^^^^ the trait `serde::ser::Serialize` is not implemented for `MyStruct`
     | 
    ::: /home/vmx/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_json-1.0.41/src/ser.rs:2192:8
     |
2192 |     T: Serialize,
     |        --------- required by this bound in `serde_json::ser::to_vec`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: could not compile `serdegitfail`.

To learn more, run the command again with --verbose.
```

I've made a repo out of this minimal example for easier consumption: https://github.com/vmx/serdegitfail

**Comment by dtolnay** [comment]
In your main.rs the MyStruct type has an impl of git serde's Serialize trait while serde_json requires an impl of the real published Serialize trait, which are not the same trait. If you want to change serde_json's serde dependency to refer to git as well, you would need to use a patch.
https://doc.rust-lang.org/cargo/reference/manifest.html#the-patch-section

**Comment by vmx** [comment]
Wow @dtolnay, thanks a lot for the quick reply!

For completeness, the same problem is there if you work on a local copy of Serde. The proper way of doing this is the `[patch]` section as @dtolnay mentions. If anyone runs into the same issue, here's how you fix it. Change your `Cargo.toml` to:

```toml
[package]
name = "serdegitfail"
version = "0.1.0"
authors = ["Volker Mische <volker.mische@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1.0.41"

[patch.crates-io]
serde = { git = "https://github.com/serde-rs/serde" }
```
