### ISSUE TITLE
Migrating serialized config file to new schema

### ISSUE THREAD

**Issue by axos88** [serde-rs/serde#1652]
As my product evolves, so does the configuration file. Sometimes breaking changes are needed to keep it lean and clean.

I would like to know if there are any good practices on how to update the schema of serialized data (a config file)?

Say I have a struct like this:

```
 #[serde(deny_unknown_fields)]
 #[derive(Serialize, Deserialize, Debug)]
  struct Foo {
    a: u32,
    b: String
}
```

With foo.txt containing the json serialized version of  a Vec<Foo>:

```
[{ "a" :5, "b": "bar" }, {"a": 6, b: "baz" }]
```

What would be the best way to update Foo to look like:

```
  #[serde(deny_unknown_fields)]
  #[derive(Serialize, Deserialize, Debug)]
  struct Bar {
    "enabled": bool,
    "name": String,
  }
 
  #[serde(deny_unknown_fields)]
  #[derive(Serialize, Deserialize, Debug)]
  struct Foo {
    "a": u32,
    "b": Bar
  }
```

and to calculate Bars' name from the Foo.b string and set enabled to true for values being migrated?

**Comment by axos88** [comment]
Preferably the migration would be something that happens first thing as the application starts running, so that when it loads the config file it will already see the new version.

**Comment by dtolnay** [comment]
Hi @axos88, sorry that no one was able to provide help here. If this is still an issue, you could try taking this question to any of the resources shown in https://github.com/serde-rs/serde#getting-help.
