### ISSUE TITLE
Type Annotations Required when Implementing DeserializeOwned

### ISSUE THREAD

**Issue by hogum** [serde-rs/serde#1653]
I'm trying to implement **Deserialize** for use on a Generic trait.
- Here's the function that receives a generic-type argument `body` and creates a struct using it as one of the fields.

```

pub fn respond<'a, T>(
    data: HashMap<&'static str, &'static str>,
    body: Option<T>,
    err: Option<&'a str>,
) -> Result<HttpResponse, Box<dyn error::Error>>

where
    T: serde::de::DeserializeOwned,
    T: Serialize,
{
    
    let status = StatusCode::from_u16(data["status"].parse::<u16>().unwrap()).unwrap();
    if err.is_some() {
       Ok(HttpResponse::build(status).json(Response::err(
            &status.to_string(),
            err.unwrap())))

    } else {
        Ok(HttpResponse::build(status).json(Response::success(
            status.as_str(),
            &data.get("message").unwrap(),
            body.unwrap(),
        )))
    }
}

```
The function is trying to construct and return an error response if the the `err` argument is Some, otherwise, creates a non-error response.

##### This is the struct with the generic type:
```
#[derive(Deserialize, Serialize, Debug)]
pub struct Response<'a, T> {
    status: &'a str,
    #[serde(skip_serializing_if = "Option::is_none")]
    errors: Option<&'a str>,
    data: Option<T>,
    message: Option<&'a str>,
}
```

##### And here is its present implementation
```
impl<'a, T> Response<'a, T>
where
    T: serde::de::DeserializeOwned + Serialize,
{
    pub fn err<'b>(status: &'b str, errors: &'b str) -> Response<'b, T> {
        Response {
            status,
            errors: Some(errors),
            data: None,
            message: None,
        }
    }

    pub fn success<'b>(status: &'b str, message: &'b str, data: T) -> Response<'b, T> {
        Response {
            status,
            errors: None,
            data: Some(data),
            message: Some(message),
        }
    }
}
```
Calling `Response::success(status, data, body);` works as intended. However, the `Response::err` variant does not compile when called as written in the `respond` function.

I get the error
```
type annotations required: cannot resolve `_: _serde::de::DeserializeOwned`

```
Here's a note on how the compiler complains:
```
note: required by `crate::to::respond::path`
 | / pub fn respond<'a, T>(
 | |     data: HashMap<&'static str, &'static str>,
 | |     body: Option<T>,
 | |     err: Option<&'a str>,
...  |
 | |     }
 | | }
   | |_^

```
Please help me figure out what I've been doing wrong. Thanks

**Comment by dtolnay** [comment]
> ```
> Response::err(
>     &status.to_string(),
>     err.unwrap())
> ```

^ What do you expect the type of this expression to be? There isn't enough information for it to be uniquely determined.

**Comment by hogum** [comment]
I'd expected the return type of this expression
> Response::success(
            status.as_str(),
            &data.get("message").unwrap(),
            body.unwrap(),
        ));


to be equivalent to this

 > Response::err(
    &status.to_string(),
    err.unwrap())

I'd previously tried to assign then return the value.
```
err_response : Response<_> = Response::err(
    &status.to_string(),
    err.unwrap());
Ok(err_response)
```
This could compile but I couldn't call that part of the expression from another function.

Could you help me first understand why the type of the first expression can be determined(and possibly what it type it is), but the second one can't, because I'm unable infer the type of the failing expression explicitly

**Comment by dtolnay** [comment]
Well the first must be `Response<T>` because Response::success returns `Response<?2>` where ?2 is the type of the second argument, and the second argument you pass has type `T`.

The second could be `Response<u8>` or `Response<String>` or `Response<T>` or `Response<Option<T>>` or `Response<!>` or anything else.

**Comment by hogum** [comment]
Thanks for clarifying @dtolnay  :smile:
