### ISSUE TITLE
Endless recursion with #[serde(into = ..)] in conjunction with a generic function

### ISSUE THREAD

**Issue by Ploppz** [serde-rs/serde#1655]
Initially I got stderr of 11MB cryptic errors when compiling my application. After hours of trying to reproduce the error, I finally boiled it down to 58 lines: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=7dfe4f39a473b6ed8c16bca871a99e8e

The error starts with
```
error[E0275]: overflow evaluating the requirement `&mut std::vec::Vec<u8>: std::io::Write`
```

edit: curiously, if you remove the `Vec<u8>` and `Write` (https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=4f512b7db382805db9997222e4966e78) it still has the same error.

If you remove line 50 there is no problem.

What I wanted to achieve was to serialize `Foo` with an extra field `path`.

**Comment by dtolnay** [comment]
I don't think this is something we would be able to fix on our end. In your playground, serializing Foo requires converting it to FooSerde and calling FooSerde's serialize, and at the same time serializing FooSerde requires calling Foo's serialize. This is endless recursion. You would need to change one or both behaviors to not depend on the other in order for the program to be meaningful.

**Comment by Ploppz** [comment]
Thanks for the explanation. How can I then achieve what I wanted (serialoze an extra field)? Do I have to just copy paste all lines of Foo, or is there another way?
