### ISSUE TITLE
tests for serde 0.8.23 fail w/ recent rust

### ISSUE THREAD

**Issue by kentfredric** [serde-rs/serde#1658]
Yes, I'm aware there are newer versions, however, how I ended up in this mess is the recursive linux vendorization chain.

- syn 1.0.5 test 
  - requires insta 0.9.0
   - which requires console 0.7.7
   - which requires parking_lot 0.9.0
   - which requires rustc_version 0.2.3
   - which requires semver 0.9.0
- semver 0.9.0 test
  - requires crates-index 0.5.1
  - which requires git2 0.6.11
  - which requires url 1.7.2
  - which requires serde 0.8.23

And this is why I'm trying to have serde 0.8.23 with working tests.

However, at present, it fails as follows:
```
test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests serde
     Running `rustdoc --test /var/tmp/portage/dev-rust/serde-0.8.23/work/serde-0.8.23/src/lib.rs --crate-name serde -L dependency=/var/tmp/portage/dev-rust/serde-0.8.23/work/debug/deps -L dependency=/var/tmp/portage/dev-rust/serde-0.8.23/work/debug/deps --cfg 'feature="default"' --cfg 'feature="std"' --extern serde=/var/tmp/portage/dev-rust/serde-0.8.23/work/debug/deps/libserde-d0dd6d6113cef31d.rlib`

running 2 tests
test src/macros.rs - forward_to_deserialize (line 157) ... ignored
test src/ser/mod.rs - ser::Serializer::serialize_bytes (line 175) ... FAILED

failures:

---- src/ser/mod.rs - ser::Serializer::serialize_bytes (line 175) stdout ----
error[E0424]: expected value, found module `self`
 --> src/ser/mod.rs:176:22
  |
3 | let mut state = try!(self.serialize_seq(value));
  |                      ^^^^ `self` value is a keyword only available in methods with `self` parameter

error[E0425]: cannot find value `value` in this scope
 --> src/ser/mod.rs:176:41
  |
3 | let mut state = try!(self.serialize_seq(value));
  |                                         ^^^^^ not found in this scope

error[E0425]: cannot find value `value` in this scope
 --> src/ser/mod.rs:177:10
  |
4 | for b in value {
  |          ^^^^^ not found in this scope

error[E0424]: expected value, found module `self`
 --> src/ser/mod.rs:178:10
  |
5 |     try!(self.serialize_seq_elt(&mut state, b));
  |          ^^^^ `self` value is a keyword only available in methods with `self` parameter

error[E0424]: expected value, found module `self`
 --> src/ser/mod.rs:180:1
  |
7 | self.serialize_seq_end(state)
  | ^^^^ `self` value is a keyword only available in methods with `self` parameter

error[E0308]: mismatched types
 --> src/ser/mod.rs:176:17
  |
2 | fn main() {
  |           - expected `()` because of default return type
3 | let mut state = try!(self.serialize_seq(value));
  |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected (), found enum `std::result::Result`
  |
  = note: expected type `()`
             found type `std::result::Result<_, _>`
  = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: aborting due to 6 previous errors

Some errors have detailed explanations: E0308, E0424, E0425.
For more information about an error, try `rustc --explain E0308`.
Couldn't compile the test.

failures:
    src/ser/mod.rs - ser::Serializer::serialize_bytes (line 175)
```

I'm not expecting upstream as-is to fix this as such ( though, if its viable to ship a new point release in 0.8  series to fix that, it would be helpful ), just er, some direction on how to resolve this other than "don't run tests" would be appreciated. ( Vendor patching is entirely viable if need be ).

NB: Its possible there have been some updates to things mentioned in the above chain, which might elide this, just its a problem for me because it takes me weeks to get from 'syn' to 'serde 0.8*', so finding the right point in the tree to diverge is currently painful.

**Comment by kentfredric** [comment]
Seems with syn 1.0.7, the dependency graph doesn't so easily descend into this, as the stack becomes:

- syn 1.0.7 (test)
  - insta 0.11.0
  - console 0.8.0

And console 0.8.0 doesn't descend into parkinglot.

Though I'll undoubtedly hit this problem via some other path one day ....

**Comment by dtolnay** [comment]
Glad you got it working -- I'll close the issue because I don't intend to release a patch to change 0.8's tests. I don't think rustdoc ran those tests at the time.
