### ISSUE TITLE
Add a format base trait?

### ISSUE THREAD

**Issue by djc** [serde-rs/serde#1659]
I've used several of the format implementations that use serde, including serde-json, bincode, serde-yaml, and serde-cbor. I noticed that many of them have very similar high-level APIs, but using different names. For example, bincode has:

```
pub fn deserialize<'a, T>(bytes: &'a [u8]) -> Result<T>
where
    T: Deserialize<'a>, 
pub fn deserialize_from<R, T>(reader: R) -> Result<T> where
    R: Read,
    T: DeserializeOwned, 
```

and serde-cbor has

```
pub fn from_reader<T, R>(reader: R) -> Result<T> where
    T: DeserializeOwned,
    R: Read, 
pub fn from_slice<'a, T>(slice: &'a [u8]) -> Result<T> where
    T: Deserialize<'a>, 
```

I was wondering whether it might make sense for serde itself to provide traits for some of these widely shared implementations, which might make it easier for downstream users to switch, provides guidance on what methods to implement and how to name them, and eventually makes it possible/easier to support multiple formats in one library or application.

**Comment by dtolnay** [comment]
This came up previously in https://github.com/serde-rs/serde/issues/644 but we never arrived at a good API for it. I would like to see a polished external crate for this before it would get included in serde.

**Comment by djc** [comment]
Alright, thanks!
