### ISSUE TITLE
Deserializing seqs with elements in arbitrary order

### ISSUE THREAD

**Issue by alexschrod** [serde-rs/serde#1661]
I am writing a deserializer for a format, and in this format, you can have structs inside structs, and these are always sequences/allow multiple copies. A problem I have run into is when the order these inner structs show up in isn't contiguous/sorted. So when I have
```
outer "Outer" {
    inner1 "First" {
    }
    inner1 "Second" {
    }
    inner2 "Third" {
    }
    inner2 "Fourth" {
    }
}
```
I do fine, because my seq deserializer just keeps going until `inner1` changes to something else (or I encounter '}'), and then calls it a day. But if the file instead looks like this:
```
outer "Outer" {
    inner1 "First" {
    }
    inner2 "Third" {
    }
    inner1 "Second" {
    }
    inner2 "Fourth" {
    }
}
```
I'm in trouble, because the second time I come across `inner1` and try to deserialize it again, serde tells me
> duplicate field `inner1`

Is there some way for me to tell serde to combine the sequences instead of considering them duplicates? Because I parse as I go, I can't know that another value from a previous sequence will come up until I'm already at the point where I'm deserializing the "same seq" twice.

**Comment by dtolnay** [comment]
The nearest example I know to look at would be the TOML deserializer which I believe supports this.

```rust
use serde::Deserialize;

#[derive(Deserialize, Debug)]
struct Data {
    outer: Outer,
}

#[derive(Deserialize, Debug)]
struct Outer {
    inner1: Inner,
    inner2: Inner,
}

#[derive(Deserialize, Debug)]
struct Inner {
    a: Entry,
    b: Entry,
}

#[derive(Deserialize, Debug)]
struct Entry {
    name: String,
}

fn main() {
    let t = r#"
        [outer.inner1.a]
        name = "First"

        [outer.inner2.a]
        name = "Third"

        [outer.inner1.b]
        name = "Second"

        [outer.inner2.b]
        name = "Fourth"
    "#;

    println!("{:#?}", toml::from_str::<Data>(t).unwrap());
}
```

```console
Data {
    outer: Outer {
        inner1: Inner {
            a: Entry {
                name: "First",
            },
            b: Entry {
                name: "Second",
            },
        },
        inner2: Inner {
            a: Entry {
                name: "Third",
            },
            b: Entry {
                name: "Fourth",
            },
        },
    },
}
```
