### ISSUE TITLE
Code generation for other languages

### ISSUE THREAD

**Issue by Timmmm** [serde-rs/serde#1667]
I'd like to use Bincode for cross-language IPC. Ideally I would write my message definitions as Rust structs with `#[derive(Serialize, Deserialize)]` and then I can easily encode/decode them in Rust.

But I would also like to generate code to serialize/deserialize them for my other language (Typescript). Is there a way to do this nicely using Serde? I assume it already parses the struct structure and generates Rust code based on that - that is 90% of the work!

**Comment by Timmmm** [comment]
Issue #345 seems to suggest the answer is no. :-(

**Comment by matbd** [comment]
@Timmmm FYI I have started working on code generation based on Serde formats as part of the [Libra](https://github.com/libra/libra) project.
Here is the [github repo of the library](https://github.com/facebookincubator/serde-reflection) that we are building and the issue that tracks code generation: https://github.com/facebookincubator/serde-reflection/issues/6

**Comment by Timmmm** [comment]
@matbd Ooo interesting! Btw it looks like you can serialise the schema to anything Serde supports - not just YAML? Might want to note that in the Readme because YAML is the product of deranged mind and anything that uses it makes me think "hmm are these people sane?" :-D

For my original use I ended up writing a custom Rust-like IDL and using another program to parse it with Nom and output the Serde and Typescript code. However I have another use case which is to convert Serde definitions to JSON Schema - looks like your library will help with that so I'll check it out, thanks!

**Comment by matbd** [comment]
Cool. YAML is indeed just an example of representation derived from `serde_yaml`. Let me fix the README.
