### ISSUE TITLE
Untagged unit variant fails to deserialize from `visit_none()`

### ISSUE THREAD

**Issue by H2CO3** [serde-rs/serde#1668]
I'm writing a serialization format that uses explicit optionals. Similarly to `serde_json::Value`, my `Value` enum has a `Null` variant representing the null value. When asked to `deserialize_any()`, this null value calls `visit_none()` on the supplied visitor. However, `UntaggedUnitVisitor` doesn't implement `visit_none()`, only `visit_unit()`, so this fails.

It seems to me that `UntaggedUnitVisitor` should ideally implement `visit_none()` because `OptionVisitor` treats unit and `None` as the same, so this would be the consistent behavior. 

Another reason is that although I could fix the error by making `Value::deserialize_any()` call `visitor.visit_unit()` instead of `visitor.visit_none()`, I'd rather not change this behavior, because untagged enums are what I would consider more of a less-used special case, whereas `Option` has very regular structure and semantics, and it is used a lot more frequently too.

**Comment by Mingun** [comment]
@H2CO3 , I found, that the problem here was in calling `deserialize_any`. If derived code would call `deserialize_unit` to request the unit variant for untagged enum, would that solve problem with your format?
