### ISSUE TITLE
Deserialization of map-like data into a tuple

### ISSUE THREAD

**Issue by Yurihaia** [serde-rs/serde#1671]
I'm writing a (de)serializer for a data format with no heterogeneous ordered sequences.
My current solution for serializing a tuple is to write it into a "map" with the keys being the indices of the tuple (IE `{ 0: "a", 1: 123, 3: [] }` for `("a", 123, vec![])`), which definitely works for serialization. The problem with deserialization is that this map *should* be able to be "unordered", and the TupleVisitor for the default visitor implementation doesn't have `visit_map`, so I am unable to deserialize the unordered data correctly.
Is there a workaround I could use for this, or should I just resort to making a tuple look like
`[ { v: "a" }, { v: 123 }, { v: [] } ]`?

**Comment by dtolnay** [comment]
Hi @Yurihaia, sorry that no one was able to provide help here. If this is still an issue, you could try taking this question to any of the resources shown in https://github.com/serde-rs/serde#getting-help.
