### ISSUE TITLE
Generic deserializer for vector of tuple 

### ISSUE THREAD

**Issue by c410-f3r** [serde-rs/serde#1674]
In this use-case: 

```rust
#[serde(Deserialize)]
struct Foo {
  field: Vec<(String, u8)>
}
```

To avoid the famous `Error("invalid type: string \"123\", expected u8", ... )`, I am trying to create a generic custom deserializer based on `FromStr`for all `Vec<(T0, T1, ... , T15)>` as described in #581 but it is surprisingly hard to do so.
I know it is a newbie question but could someone body help me with this matter?

**Comment by ivan-avalos** [comment]
How did you solve the issue! 😡🤬🤬😤😠😠.

**Comment by c410-f3r** [comment]
Create a local type that wraps `Vec<(T0, T1, ... , T15)>` or use a custom trait for n-ary tuples and then implement `Deserialize` for it. E.g.: https://stackoverflow.com/questions/57529456/how-can-i-ignore-extra-tuple-items-when-deserializing-with-serde-trailing-cha

**Comment by oli-obk** [comment]
@ivan-avalos that emoticon chain is super rude. Please remove it and refrain from similar behaviour in the future.
