### ISSUE TITLE
Is is possible to use wildcards to rename a range of field names?

### ISSUE THREAD

**Issue by alexkingnz** [serde-rs/serde#1675]
I am deserializing a webdriver response.  Current selenium-rs uses:

    #[derive(Deserialize)]
    struct ElemValue {
        #[serde(rename = "ELEMENT")]
        element_id: String,
    }

However, instead of (I assume) { "ELEMENT": "xxxxxxx" }, from geckodriver I'm getting {
      "element-6066-11e4-a52e-4f735466cecf": "ce5fdd5a-5906-445a-8a16-df39880857fa"
    },

So I'd like to have something like:

    #[derive(Deserialize)]
    struct ElemValue {
        #[serde(alias = "element-*")]
        element_id: String,
    }

I don't care about serialization, or that I am throwing away some data.  How do I achieve that?

**Comment by dtolnay** [comment]
Hi @alexkingnz, sorry that no one was able to provide help here. If this is still an issue, you could try taking this question to any of the resources shown in https://github.com/serde-rs/serde#getting-help.
