### ISSUE TITLE
Deserialize with additional data

### ISSUE THREAD

**Issue by zbraniecki** [serde-rs/serde#1680]
I have a medium-complexity AST tree structure that I'd like to serialize.

The issue is that the AST stores only `Range<usize>` pointers to a `String`, and I'd like to serialize to JSON the strings, not usize.
Would it be possible to somehow specify additional data to be passed down through the serde derive to the place where the additional data can be used to turn a `Range<usize>` into ` `&str`?

Minimized example:

```rust
struct Resource(Vec<Entry>);

enum Entry {
    Message(Message),
}

struct Message {
    id: Identifier,
    value: Option<Value>
}

struct Identifier {
    name: Range<usize>
}

struct Value {
    content: Range<usize>
}
```

Now, if I produce this AST using a string:

```
key = Value
key2 = Value 2
```

how could I pass that string to the serializer so that `Identifier` and `Value` can be serialized to `&str`?

**Comment by dtolnay** [comment]
Hi @zbraniecki, sorry that no one was able to provide help here. If this is still an issue, you could try taking this question to any of the resources shown in https://github.com/serde-rs/serde#getting-help.
