### ISSUE TITLE
No method named `into_deserializer` for type `<V as foo::_serde::de::Visitor<'_>>::Value`

### ISSUE THREAD

**Issue by djc** [serde-rs/serde#1681]
I'm working on a custom `Deserializer` for AMQP 1.0.0 (unfortunately I don't have permission right now to publish this code in the open). It is based on the `Deserializer` example from the book, with `deserialize_enum()` currently looking like this:

```rust
    fn deserialize_enum<V>(
        self,
        name: &'static str,
        variants: &'static [&'static str],
        visitor: V,
    ) -> Result<V::Value>
    where
        V: Visitor<'de>,
    {
        let described = self.next()?;
        if described == 0 {
            let ty = self.next()?;
            let value = visitor.visit_enum(Enum::new(self))?;
            Ok(value)
        } else {
            visitor.visit_enum(self.deserialize_str(visitor)?.into_deserializer())
        }
    }
```

The line in the if-block causes this problem:

```rust
error[E0599]: no method named `into_deserializer` found for type `<V as sasl::_IMPL_DESERIALIZE_FOR_Mechanisms::_serde::de::Visitor<'_>>::Value` in the current scope
   --> oasis-amqp/src/format.rs:365:63
    |
365 |             visitor.visit_enum(self.deserialize_str(visitor)?.into_deserializer())
    |                                                               ^^^^^^^^^^^^^^^^^ method not found in `<V as sasl::_IMPL_DESERIALIZE_FOR_Mechanisms::_serde::de::Visitor<'_>>::Value`
```

I find this confusing because conceptually it seems like `Deserialize` and `Deserializer` implementations are pretty much decoupled, so I don't grok how this error happens.

`Mechanisms` is a very simple struct:

```rust
    #[derive(Debug, Deserialize)]
    pub struct Mechanisms {
        sasl_server_mechanisms: Vec<Mechanism>,
    }
```

`Mechanism` is an enum for which I've written a custom `Deserialize` implementation.

Context: I'm trying to support two different kinds of enums. AMQP 1.0.0 has `symbol`s, which are basically ASCII strings with a per-use limited domain (in the case of `Mechanism`, they would be SASL mechanisms like `Plain` and `Anonymous`). I'd also like to group some structs (which can be represented in AMQP 1.0.0 as "described types") together into enums (and in this case, we can read the "descriptor" to figure out if it matches one of the nested types).

Any hint on what's going on here?

**Comment by dtolnay** [comment]
> ```rust
> visitor.visit_enum(self.deserialize_str(visitor)?.into_deserializer())
> ```

- The deserialize_str call returns V::Value which may or may not implement IntoDeserializer (in fact probably does not).
    https://docs.rs/serde/1.0.103/serde/trait.Deserializer.html#tymethod.deserialize_str

- The visit_enum argument must implement EnumAccess which an arbitrary Deserializer does not.
    https://docs.rs/serde/1.0.103/serde/de/trait.Visitor.html#method.visit_enum

You should look at some similar data formats to see how they implement enums, and use `cargo expand` to look at some generated code of enums to see how they expect to use the argument of visit_enum.

**Comment by djc** [comment]
Managed to resolve it, thanks! I do feel that some kinds of intermediate documentation (as in, what is the conceptual purpose/difference between a `Deserializer` and its `Visitor`, how do the `EnumAccess` and the `VariantAccess` interact) is underrepresented.
