### ISSUE TITLE
#[serde(tag=...)] attribute not rejected on structs

### ISSUE THREAD

**Issue by jethrogb** [serde-rs/serde#1684]
This:
```rust
use serde::Serialize;

#[derive(Serialize)]
#[serde(tag = "tag")]
pub struct A {
    a: u32
}

fn main() {
    println!("{}", serde_json::to_string(&A { a : 0 }).unwrap());
}
```
prints:
```
{"tag":"A","a":0}
```
I would've expected this to be a compile-time error. Alternatively, this is a documentation bug, as the container attribute documentation clearly only talks about enums.

**Comment by jplatte** [comment]
This is a documentation bug. The behaviour of your example is intended: https://github.com/serde-rs/serde/pull/1448

**Comment by piegamesde** [comment]
I just got badly bitten by this. I accidentally had a `tag = "type"` attribute on a struct, and nesting it in an enum caused serialization to produce two `type` fields. Later on, deserialization failed with a "duplicate field `type`" error.
