### ISSUE TITLE
Using deserialize_in_place in no_std environment

### ISSUE THREAD

**Issue by PraneshAnubhav** [serde-rs/serde#1691]
Hi,

I want to use deserialize_in_place for deserialization to reduce stack consumption. I have enabled the feature. My cargo.toml:
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_cbor = { version = "0.10.2", default-features = false}
serde_derive = { version = "1.0.103", default-features = false, features = ["deserialize_in_place"]}

My code to deserialize:

pub fn deserialize_in_place<'a, T: Deserialize<'a>>(slice: &'a [u8], place: &mut T) -> Result<(), Error> {
    let mut deserializer = Deserializer::from_slice_with_scratch(slice, &mut []);
    let value =  de::Deserialize::deserialize_in_place(&mut deserializer, place)?;
    deserializer.end()?;
    Ok(())
}

I still don't see any difference in stack consumption. I went through the implementation of Deserialize trait for different types in serde:: de ::impls but I don't see implementation of deserialize_in_place for any type except String. 

Can you please guide me to use deserialize_in_place correctly?

**Comment by PraneshAnubhav** [comment]
Hi @dtolnay,
Can you please help me out with this?

**Comment by dtolnay** [comment]
I wouldn't necessarily expect deserialize_in_place to reduce stack size. It is more about reusing already allocated heap buffers.

**Comment by PraneshAnubhav** [comment]
@dtolnay 
I'm using serde with no_std (default-features = false) and we have not enabled "alloc" feature. There is no heap allocations during deserialization. 

Is there a way to check the implementation generated by serde_derive after deserialize_in_place feature is turned on?

**Comment by dtolnay** [comment]
If deserialize_in_place is for reusing heap buffers and you don't have any heap buffers, then I guess that explains why you don't observe a difference. ;)

You can use https://github.com/dtolnay/cargo-expand to see what is emitted by serde_derive.
