### ISSUE TITLE
Ignore Unmatched Enum Variants

### ISSUE THREAD

**Issue by deankarn** [serde-rs/serde#1694]
This is quite similar to https://github.com/serde-rs/serde/issues/1377 but the solution there does not fit my use case.

Here is a playground example: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=87b09f6bbc9ddbf8b95f0401f3de4d9c

I wish to ignore any data that does not match the `Value` enum variants and also have it not be added to the `Map`. Although the example, in this case, is `json`, I'm hoping to find a deserializer agnostic solution.

I could deserialize it all and then throw out the data that doesn't match the types I want but hoping there may be a better solution.

I'm hoping for some help or suggestions on achieving this, thanks in advance for any help.

**Comment by Ayplow** [comment]
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b7d39128223ca5904cfff05954abb93e

Here's a bunch of boilerplate that effectively replaces [the default map deserialization](https://doc.servo.org/src/serde/de/impls.rs.html#1222-1224) with what you want:

```rust
loop {
    if let Ok(next) = map.next_entry() {
        if let Some((key, value)) = next {
            values.insert(key, value);
        } else {
            break;
        }
    }
}
```

**Comment by dtolnay** [comment]
Hi @deankarn, if this is still an issue you could try taking this question to any of the resources shown in https://github.com/serde-rs/serde#getting-help.
