### ISSUE TITLE
Zero copy byte slice serialization doesn't work

### ISSUE THREAD

**Issue by krampenschiesser** [serde-rs/serde#1696]
I tried the following code:

```
extern crate serde_cbor;
extern crate serde;

#[derive(Debug, Eq, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct Bla<'a> {
    slice: &'a [u8],
}
 
fn main() {
    let v = vec![1, 2, 3];
    let bla = Bla {
        slice: v.as_slice(),
    };
    let vec = serde_cbor::to_vec(&bla).unwrap();
    let string = format!("{:x?}",vec.as_slice());
    let _: Bla = serde_cbor::from_slice(&vec).unwrap();
}
```

This ultimately fails as serde always serializes **&'a [u8]** as sequence and not as bytes.
Call tree looks kinda like this:

serialize_struct
serialize_field
value.serialize(&mut *self.ser)?;
serializer.collect_seq(self) (from ser::impls impl<T> Serialize for [T])

In the end this causes cbor to use a tag for a sequence, not the tag for a byte slice, which in the end prevents de-serializing into a byte slice since it tries to create a vec of u8.

p.s. the same error happens when using json crate (https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=7c64d02f86fe3921844cb6a6c800c37b):
```
extern crate serde_json; // 1.0.44;
extern crate serde; // 1.0.103;

#[derive(Debug, Eq, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct Bla<'a> {
    slice: &'a [u8],
}
 
fn main() {
    let v = vec![1, 2, 3];
    let bla = Bla {
        slice: v.as_slice(),
    };
    let string = serde_json::to_string(&bla).unwrap();
    println!("{}", string);
    let _: Bla = serde_json::from_str(&string).unwrap();
}
```

**Comment by dtolnay** [comment]
You would need to use https://github.com/serde-rs/bytes in order to emit cbor bytes.

**Comment by StefanHri** [comment]
I have the same problem. Can you provide a minimal example of how to use  https://github.com/serde-rs/bytes
