### ISSUE TITLE
untagged parsing str into incorrect enum variant

### ISSUE THREAD

**Issue by rockmenjack** [serde-rs/serde#1698]
Given below code:

```rust
use serde::{Deserialize, Serialize};

#[derive(Deserialize, Serialize, Debug)]
struct EnumMember1 {
    name: String,
}

#[derive(Deserialize, Serialize, Debug)]
struct EnumMember2 {
    name: String,
    attrs: Vec<u32>,
}

#[derive(Deserialize, Serialize, Debug)]
#[serde(untagged)]
enum Arg1 {
    Tag1(EnumMember1),
    Tag2(EnumMember2),
}

fn main() {
    let v1: Vec<Arg1> =
        serde_json::from_str(r#"[{"name":"abc"},{"name":"xyz","attrs":[]}]"#).unwrap();
    dbg!("{:?}", &v1);
}

```

the output prints:

```
[src/main.rs:24] &v1 = [
    Tag1(
        EnumMember1 {
            name: "abc",
        },
    ),
    Tag1(  // ??? why Tag1 ???
        EnumMember1 {
            name: "xyz",
        },
    ),
]

```

Should the second element in v1 be parsed as Tag2 instead of Tag1?

**Comment by jplatte** [comment]
This is working as specified. From [the documentation for `untagged` enums](https://serde.rs/enum-representations.html):

> There is no explicit tag identifying which variant the data contains. Serde will try to match the data against each variant in order and the first one that deserializes successfully is the one returned.

You can either reorder your variants or implement `Deserialize` manually.

**Comment by rockmenjack** [comment]
> This is working as specified. From [the documentation for `untagged` enums](https://serde.rs/enum-representations.html):
> 
> > There is no explicit tag identifying which variant the data contains. Serde will try to match the data against each variant in order and the first one that deserializes successfully is the one returned.
> 
> You can either reorder your variants or implement `Deserialize` manually.

Doesn't the matching on variant be considered ended after json object boundary, say, after "}"?   If it is not,  I think the documentation could be more specific on  what ```deserializes successfully``` means.

**Comment by jplatte** [comment]
It us not, although that can be configured. The default is mentioned [here](https://serde.rs/container-attrs.html#deny_unknown_fields).

I agree that it could be more visible in the docs, but I'd recommend opening a new issue for that (if none exists yet) or creating a PR directly, and closing this one.

**Comment by rockmenjack** [comment]
Open a documentation issue instead.
