### ISSUE TITLE
`#[serde(borrow)]` attribute only required on one variant or field

### ISSUE THREAD

**Issue by davesque** [serde-rs/serde#1703]
I'm seeing a weird behavior with the `#[serde(borrow)]` attribute.  It seems like it's only required on at least one variant or field within an enum or struct when I would expect that it would be required for any field that contains a sufficiently nested borrow.  Here's a Rust Playground with what I'm talking about (serde version is 1.0.104):

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=e2550ff22403ada6c56d4fb8b8dc9633

Actually the same phenomenon seems to occur when placing the `#[serde(borrow)]` attribute on enum fields.  That is, if at least one field of one variant in an enum is annotated with `#[serde(borrow)]`, then no other field of any other variant in the same enum requires any annotation to clarify what the lifetime `'de` should be.

**Comment by jdahlbaek** [comment]
I'm experiencing the same. Any information as to whether this is a feature or a bug?

**Comment by dtolnay** [comment]
It's a feature, the only function of `serde(borrow)` is to put a `'de: 'a` bound on the derived impl and you don't need more than one identical bound.

**Comment by dtolnay** [comment]
https://serde.rs/lifetimes.html#borrowing-data-in-a-derived-impl has more detail on how the attribute works.
