### ISSUE TITLE
externally custom tagged enum

### ISSUE THREAD

**Issue by nnovikov** [serde-rs/serde#1710]
Hello!
I want to deserialize some bytes to enum. The first byte describe enum variant and other bytes contains a some structure. Is it possible generate this case by serde_derive and external tag feature?

For example:
```
enum Packet {
    #[serde(tag = 0xAABBCCDD as u32)]
    Requset(Request),
    #[serde(tag = 0xEEFFEEFF as u32)]
    Response(Response)
}

struct Request {....}
struct Response {....}

```

**Comment by nnovikov** [comment]
I play around with the serde and I discover what serde_derive can't produce required code. Anyone can explain to me how write `Deserialie` implementation for this case? URL to example of some code will be a good for an understanding.

**Comment by dtolnay** [comment]
Hi @nnovikov, sorry that no one was able to provide help here. If this is still an issue, you could try taking this question to any of the resources shown in https://github.com/serde-rs/serde#getting-help.
