### ISSUE TITLE
How to use serde with tree implemented by arena?

### ISSUE THREAD

**Issue by Evian-Zhang** [serde-rs/serde#1711]
My `Tree` struct is implemented using the [arena](https://rust-leipzig.github.io/architecture/2016/12/20/idiomatic-trees-in-rust/) technique:

```rust
pub struct Node {
    pub children: Vec<PathBuf>,
    pub properties: HashMap<String, String>,
}

pub struct Tree {
    pub nodes: HashMap<PathBuf, Arc<Mutex<Node>>,
    pub root: Weak<Mutex<Node>>,
}
```

To find the children of a node, we need to query the `Tree` instance:

```rust
let node = Node { .. };
let tree = Tree { .. };
// find the children
for child_path in node.children {
    let child = tree.nodes.get(child_path).unwrap(); // the child
    ...
}
```
I want to serialize my `Tree` object like:

```json
{
    "name": "my_name",
    "property1": "value1",
    "property2": "value2",
    ...
    "children": [
     {
        "name": "child1_name",
        ...
     },
    ...
    ]
}
```

To flatten the `properties` field, I need to add `#[serde(flatten)]` above the `properties` (I didn't find out a way to implement the flatten behavior during the [customized serialization](https://serde.rs/impl-serialize.html)) as follows:

```rust
pub struct Node {
    pub children: Vec<PathBuf>,
    #[serde(flatten)]
    pub properties: HashMap<String, String>,
}
```

To serialize the `children` field, there is no way if I don't add a `tree` field to `Node` struct, since the children nodes are achieved by querying `Tree`'s nodes map. However, if I add a `tree` field to `Node` struct (which I really don't want to), I must customize my serialization or add `#[serde(serialize_with = "path")]` attribute:

```rust
// the latter method
pub struct Node {
    #[serde(serialize_with = "my_serialize")]
    pub children: Vec<PathBuf>,
    #[serde(flatten)]
    pub properties: HashMap<String, String>,
}

fn my_serialize<S>(children: &Vec<PathBuf>, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer {
    ...
}
```

For the latter, the parameter is `Vec<PathBuf>`, and I still can't get the nodes map, so I can't serialize it's children.

Hence, the only feasible solution is to customize my serialization. But as I said above, I didn't find out a way to implement the flatten behavior during the customized serialization.

**Comment by dtolnay** [comment]
Hi @Evian-Zhang, sorry that no one was able to provide help here. If this is still an issue, you could try taking this question to any of the resources shown in https://github.com/serde-rs/serde#getting-help.
