### ISSUE TITLE
Flatten only on deserialization

### ISSUE THREAD

**Issue by scull7** [serde-rs/serde#1715]
I would like to use flatten to group a set of fields within a big bag of fields, but when I serialize this back out into JSON I would like it to keep the nested structure.  Is flatten the correct way to do this?  Is there a way to limit flatten so that it does not affect serialization?

Example input JSON:
```json
{ 
  "foo": 1234,
  "bar": 5678,
  "sub_foo": 9876,
  "sub_bar": 5432,
}
```

Serialization Struct
```rust
#derive(Debug, Deserialize, Serialize)]
pub struct SubThing {
  #[serde(rename(deserialize = "sub_foo"))]
  foo: u32,
  #[serde(rename(deserialize = "sub_bar"))]
  bar: u32
}

#[derive(Debug, Deserialize, Serialize)]
pub struct Thing {
  foo: u32,
  bar: u32,
  sub: SubThing,
}
```

Currently, this will output the following JSON when serializing:
```json
{
  "foo": 1234,
  "bar": 5678,
  "foo": 9876,
  "bar": 5432,
}
```

This seems less than ideal.  Also, how would one go about a similar situation where `sub` was another instance of `Thing`? (i.e. a recursive nesting).

**Comment by jonasbb** [comment]
The `flatten` attribute always works both ways, so serialization and deserialization.
It looks like you can use the container attributes [`from`](https://serde.rs/container-attrs.html#from) and `into` to specify that deserialization/serialization should be done via a second type. This basically means you need to have two structs, one for deserialization and the other for normal use + serialization, which also means you need to duplicate your struct definitions.

Here is how that could work. I assume that you `SubThing` should be identical to `Thing`, but with the additional prefix. Therefore, I have to use the `Option<Box<Thing>>`. Second, to add a prefix to all fields of a struct, you can use the [`serde_with::with_prefix`](https://docs.rs/serde_with/1.3.1/serde_with/macro.with_prefix.html) macro. This works especially well, if you need to use multiple different prefixes.

```rust
#[serde_with::skip_serializing_none]
#[derive(Debug, Deserialize, Serialize)]
#[serde(from="FromThing")]
pub struct Thing {
    pub foo: u32,
    pub bar: u32,
    pub sub: Option<Box<Thing>>,
}

#[serde_with::skip_serializing_none]
#[derive(Debug, Deserialize, Serialize)]
pub struct FromThing {
    pub foo: u32,
    pub bar: u32,
    #[serde(flatten, with = "prefix_sub")]
    pub sub: Option<Box<Thing>>,
}

impl From<FromThing> for Thing {
    fn from(other: FromThing) -> Thing {
        Self {
            foo: other.foo,
            bar: other.bar,
            sub: other.sub,
        }
    }
}

serde_with::with_prefix!(prefix_sub "sub_");

pub fn main() {
    let json_str = r##"{ 
    "foo": 1234,
    "bar": 5678,
    "sub_foo": 9876,
    "sub_bar": 5432
}"##;
    let t: Thing = serde_json::from_str(json_str).unwrap();
    println!("{:?}", t);
    let j = serde_json::to_string_pretty(&t).unwrap();
    println!("{}", j);
}
```
