### ISSUE TITLE
How to remove map entries within a deserializer adapter for a user-defined struct?

### ISSUE THREAD

**Issue by tones111** [serde-rs/serde#1716]
I've been unable to determine how to get derived (de)serialize to handle my use case and am hoping someone can point me in the right direction.

I have several non-trivial structs to (de)serialize with a pre-defined json file format.  I would like to make use of serde's attributes for fields at the top level of the struct, however I am unable due to the file format containing a duplicate key.  It's used as a header / footer at the begining and end of the file and should be validated to be consistent.

I have a [minimized repo](https://github.com/tones111/serde_example) demonstrating the manual (de)seralize pattern I'm trying mimic.

I've found the following resources:
#690, #1607: suggest writing a deserializer adapter and point to some examples.

[serde-ignored](https://github.com/dtolnay/serde-ignored): Leverages deserialize_ignored_any which doesn't allow preventing the duplicate key
[serde-stacker](https://github.com/dtolnay/serde-stacker): Similarly doesn't modify map keys
[serde-with](https://github.com/jonasbb/serde_with/blob/674ee9fa183b06f248a1219590862613f2a41bd7/src/duplicate_key_impls/first_value_wins.rs#L56): Modifies the map keys but deserializes into a map instead of a user-defined struct.

I believe the solution is to write a deserializer adapter wrapping the json deserializer, but I've not yet figured out how/where in the layers of deseralizers, MapAccess objects, visitors, seeds, etc the right place is to catch the second instance of the key and prevent it from being processed.

Any help or suggestions would be greatly appreciated.  Thanks in advance.

**Comment by dtolnay** [comment]
Hi @tones111, sorry that no one was able to provide help here. If this is still an issue, you could try taking this question to any of the resources shown in https://github.com/serde-rs/serde#getting-help.
