### ISSUE TITLE
untagged enums do not support 128 bit integers

### ISSUE THREAD

**Issue by Licenser** [serde-rs/serde#1717]
The `Content` enum 

https://github.com/serde-rs/serde/blob/ff70409215b62fa8cd138ce47534c432352c85bb/serde/src/private/de.rs#L230

does not include `i128` or `u128` fields, this makes it impossible to use those values in untagged enums.

**Comment by mikonieminen** [comment]
I've run into similar issues and raised a bug in `serde_json`: https://github.com/serde-rs/json/issues/740

I've created a fork with tests showing that tagged variant works while untagged variant fails: https://github.com/mikonieminen/json/blob/128bit-bug/tests/128bit.rs

**Comment by Mingun** [comment]
This is duplicate of #1682
