### ISSUE TITLE
Cannot compile on nightly with no_std

### ISSUE THREAD

**Issue by MathiasKoch** [serde-rs/serde#1720]
Trying to compile on nightlies with `default-features = false`, in a no-std project, results in 

```
error[E0463]: can't find crate for `std`
  |
  = note: the `thumbv7em-none-eabihf` target may not be installed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: could not compile `serde`.
```

Not sure how long back this is an issue.

**Comment by Michael-F-Bryan** [comment]
I don't think this is related to `serde`. Have a look at rust-embedded/cortex-m-quickstart#58, you're probably missing a `#![no_std]` annotation at the top of your `lib.rs`.

**Comment by MathiasKoch** [comment]
Nope.. It has `#![no_std]` and works great with a large number of other no_std crates.

Only change it takes to make it fail building is
`serde = { version = "1.0.104", default-features = false }` 
in my Cargo.toml

**Comment by MathiasKoch** [comment]
Update: 
Figured out what went wrong.

This issue describes perfectly what was happening https://github.com/rust-lang/cargo/issues/5730

The issue is that i was having build-dependencies using std lib.
