### ISSUE TITLE
Title  Case

### ISSUE THREAD

**Issue by gilescope** [serde-rs/serde#1724]
Am I the only one that has a case for "Human Case" where I could do with capitals and spaces in the RenameRule?

I'd suggest we close this and only implement it if it gets some thumbs up from others that also could do with this.

**Comment by gilescope** [comment]
Closing unless anyone else needs it...

**Comment by gilescope** [comment]
https://crates.io/crates/heck calls this "Title Case"

**Comment by treble37** [comment]
actually @gilescope - I could use this as well, I was dealing with some JSON that had Title Case / Human Case...any chance to reopen?

**Comment by gilescope** [comment]
I’ve seen a few rust case libraries now and everyone definitely calls this “Title Case”.

**Comment by dtolnay** [comment]
For such less widespread case conventions, I would suggest building this as an attribute macro which inserts appropriate `serde(rename = "...")` attributes onto every field/variant in its input.

**Comment by dzmitry-lahoda** [comment]
me too!

**Comment by dzmitry-lahoda** [comment]
it is very use full with yaml!!! so I can avoid scaring people with snakes and pascals and camels. and using same JSON stuff to render human yaml.
