### ISSUE TITLE
Fields from methods

### ISSUE THREAD

**Issue by UkonnRa** [serde-rs/serde#1727]
I wonder if I can add custom fields from methods?

Just like:

```rust
pub trait Trait {
  fn external(&self) -> String;
}

#[derive(Deserialize, Serialize)]
pub struct Struct {
  pub inner: i32,
}

impl Trait for Struct {
  // Or something like...
  #[serde(something)]
  fn external(&self) => String {
    "The Answer".to_string()
  }
}
```

And the serialized result will be:

```
{
  "inner": 42,
  "external": "The Answer"
}
```

**Maybe a solution**
Add the "Middleware System", like:

```rust
#[derive(Deserialize, Serialize)]
#[serde(middleware = "mid_func")]
pub struct Struct {
  pub inner: i32,
}

fn mid_func(value: serde_json::Value) -> serde_json_Value {
  <do something to wire fields from related methods>
}
```

**Why not just rewrite Serialize/Deserialize**

Too complicated. What I want is just add some fields from methods. It's too heavy to rewrite whe whole Serialize

**Comment by dtolnay** [comment]
I think I would prefer not to build something dedicated to this into serde_derive, but it would be reasonable for a different crate to provide a Serialize derive macro which helps out with implementing this behavior.

```rust
#[derive(Serialize_more)]
#[fields_from(Self::external, /* any others */)]
pub struct Struct {
    inner: i32,
}

impl Struct {
    fn external(&self) -> String {...}
}
```

**Comment by UkonnRa** [comment]
So this feature will not in serde (or serde_json) in the future?

**Comment by dtolnay** [comment]
It would be available as soon as someone writes that derive macro, which would then work with serde_json and any other serde formats.
