### ISSUE TITLE
Provide more detail description on untagged deserialization behaviour

### ISSUE THREAD

**Issue by rockmenjack** [serde-rs/serde#1730]
As discussed in https://github.com/serde-rs/serde/issues/1698, it's at least a documentation improvement.

Quoted from https://serde.rs/enum-representations.html

> There is no explicit tag identifying which variant the data contains. Serde will try to match the data against each variant in order and the first one that deserializes successfully is the one returned.

The documentation shall explicitly mention that deserialization ends immediately after a variant is successfully composed as opposed to ends at object boundary ```}```.

**Comment by dtolnay** [comment]
I think the behavior is exactly as written. The question of whether each variant would ignore or reject additional fields is separate and determined by whether the type in that variant is written with a `serde(deny_unknown_fields)` attribute:

```rust
#[derive(Deserialize)]
pub struct Member1 { // can deserialize even if there is more than just field1
    field1: T,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Member2 { // can deserialize only if field2 is the only field
    field2: T,
}

#[derive(Deserialize)]
#[serde(untagged)]
pub enum E {
    Tag1(Member1),
    Tag2(Member2),
}
```
