### ISSUE TITLE
Test suite for format implementations

### ISSUE THREAD

**Issue by casey** [serde-rs/serde#1731]
Forgive me if this has already been suggested!

I recently ran into a couple of bugs in a serde bencode implementation, and it struck me that it might be possible to create a test suite that would catch such issues while simultaneously lowering the testing burden on new format implementors. I'll give the bugs that I ran into as motivating examples.

The first issue I ran in to was that `bool`s could be serialized, but not deserialized. Bencode does not have a native boolean type, so bools are usually serialized as integers. The implementation correctly serialized bools as integers, but failed when trying to deserialize a bool field from a serialized value.

A hypothetical format-agnostic test suite could catch this with tests checking that all basic types survive a round-trip through the format.

The second issue I ran into was that a struct like `struct Foo { bar: Vec<(u16, u16)> }` could similarly be serialized but not deserialized. A hypothetical test suite could catch this by providing a large number of complex test cases. The vast huge number of compound types presents a large burden on individual format implementors, so a test suite might save them a lot of work.

In addition to improve the robustness and correctness of format implementations, it might also give format authors a useful baseline of functionality to support.

Has anything like this been proposed or discussed before?

**Comment by dtolnay** [comment]
I would prefer not to pursue this in serde, but it sounds like a valuable thing for someone else to put together in its own project.
