### ISSUE TITLE
skip_serializing_if is a footgun

### ISSUE THREAD

**Issue by khuey** [serde-rs/serde#1732]
`skip_serializing_if` only works if the serialization format is self-describing. It does not work with e.g. bincode. This is a footgun in a codebase that uses more than one serialization format at different points, because I can add `skip_serializing_if` to something that gets fed into the JSON serializer and it works fine, but when it gets fed into the bincode serializer it produces garbage that will fail to deserialize.

I think the solution here is for Serializers to declare whether or not they support skipping things and then make `skip_serializing_if` only have an effect for serializers that can tolerate it.

**Comment by dtolnay** [comment]
I think I would prefer not to build an additional toggle into the Serializer API for this.

This is a subissue of a limitation that data structures which need to follow a different codepath for serializing to different formats are not well supported by serde.

**Comment by sffc** [comment]
The lack of this feature causes problems when building serializable data structures to work with an arbitrary serializer.  We have to feature-gate our code to disable `skip_serializing_if` on the "bincode" feature, which is really awkward.

**Comment by Manishearth** [comment]
What if `skip_field` were still passed the field so that the serializer can decide to serialize it _anyway_?

**Comment by Manishearth** [comment]
Filed https://github.com/serde-rs/serde/issues/2012 for that idea

**Comment by khuey** [comment]
This continues to be a source of woe.
