### ISSUE TITLE
Unable to deserialize into a vec of untagged enum

### ISSUE THREAD

**Issue by camcamd** [serde-rs/serde#1735]
Hello,

I have defined structs like this:
```rust
#[derive(Deserialize, Debug)]
#[serde(untagged)]
#[serde(rename_all = "PascalCase")]
enum ElementResult {
	Success(ElementSuccess),
	Error(ElementError),
}

#[derive(Deserialize, Debug)]
#[serde(rename_all = "PascalCase")]
struct ElementSuccess {
	name: String,
}

#[derive(Deserialize, Debug)]
#[serde(rename_all = "PascalCase")]
struct ElementError {
	error_message: String,
}
```
To deserialize an XML looking like this:
```xml
<Element>
    <Name>element-1</Name>
</Element
<Element>
    <Name>element-2</Name>
</Element>
<Element>
    <ErrorMessage>error on element-3</ErrorMessage>
</Element>
```
I am unable to deserialize this XML into `Vec<ElementResult>`

But when I keep the ElementSuccesses from the XML and deserialize it into a `Vec<ElementSuccess>` everything works fine (same for when isolating ElementErrors to deserialize into a `Vec<ElementError>`).

Given the enum representation documentation (https://serde.rs/enum-representations.html), this is not expected behaviour.

**Comment by dtolnay** [comment]
I think this would need to be reported against the XML library you are using, since that is maintained by different people.
