### ISSUE TITLE
Optional fields: Skip if None, deserialize if present into Some

### ISSUE THREAD

**Issue by casey** [serde-rs/serde#1737]
I'm using serde to serialize to and from bittorrent metainfo. Metainfo files are encoded using bencode, which doesn't have a native `Option` type, or an equivalent to null. So, optional fields are not serialized, and if they are serialized, they use the type of the field, without an `Option` wrapper.

To get this working with serde derive, I'm doing something like this:

```
#[derive(Deserialize, Serialize, Debug, PartialEq)]
struct Foo {
  #[serde(skip_serializing_if = "Option::is_none", default, with = "inner")]
  pub(crate) bar: Option<u8>,
}
```

`inner` is a helper that deserializes to and from the inner `T` of `Option<T>` directly, so it always produces `Some`, and panics if you try to use it serialize `None`.

I wrote an version of what doing on the playground, but using `serde_json` since the bencode library I'm using isn't on the playground: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=6090ad28f1746062f05e9d0cd8c55eea

And, finally, to my actual question: This seems like a common pattern, so I'm curious if I might have missed an easier way to do this, e.g. a single attribute that does all of the above.

**Comment by jonasbb** [comment]
Maybe I am missing something, but your example works with bencode, even if you remove the `default` and `with` options on the attribute, like:

```rust
fn case<T>(value: T, expected: impl AsRef<str>)
where
    T: Serialize + DeserializeOwned + PartialEq + Debug,
{
    let serialized = serde_bencode::ser::to_string(&value).unwrap();
    dbg!(&serialized);
    assert_eq!(serialized, expected.as_ref());

    let deserialized = serde_bencode::de::from_str(&serialized).unwrap();
    dbg!(&deserialized);
    assert_eq!(value, deserialized);
}

fn main() {
    #[derive(Deserialize, Serialize, Debug, PartialEq)]
    struct Foo {
        #[serde(skip_serializing_if = "Option::is_none")]
        pub(crate) bar: Option<u8>,
    }

    let none = Foo { bar: None };
    case(none, "de");

    let some = Foo { bar: Some(1) };
    case(some, r#"d3:bari1ee"#);
}
```

So, if the only thing you need is to apply the `#[serde(skip_serializing_if = "Option::is_none")]` attribute to all fields of type `Option`, you can use the [`serde_with`] library to do that. You can put the attribute [`serde_with::skip_serializing_none`] on your struct like:

```rust
#[serde_with::skip_serializing_none]
#[derive(Deserialize, Serialize, Debug, PartialEq)]
struct Foo {
  pub(crate) bar: Option<u8>,
}
```

Your whole pattern with the `inner` de/serializer seems identical to the [`serde_with::rust::unwrap_or_skip`](https://docs.rs/serde_with/1.4.0/serde_with/rust/unwrap_or_skip/index.html) functions. However, the library does not have a nice way to apply this attribute to all fields of type Option.

[`serde_with`]: https://docs.rs/serde_with
[`serde_with::skip_serializing_none`]: https://docs.rs/serde_with/1.4.0/serde_with/attr.skip_serializing_none.html

**Comment by casey** [comment]
I'm actually using a different bencode library, [bendy](https://github.com/P3KI/bendy). `serde-bencode` does not serialize fields with value `None`, so it's more convenient to get the behavior I want here, but it has other quirks that make it unsuitable for my use case.

Ahh, I didn't know about `serde_with::rust::unwrap_or_skip`, it looks like that's what I'm looking for.
