### ISSUE TITLE
Easy(er) way to deserialize a HashMap<&str, serde_json::Value>

### ISSUE THREAD

**Issue by svanharmelen** [serde-rs/serde#1739]
I know there is a `serde_json::Map` which has `String` keys, but I would really like to use something like this:

```
let mut data: HashMap<&str, serde_json::Value> = serde_json::from_str(content).unwrap();
// do custom stuff
let v: MyStruct = serde_json::from_value(serde_json::to_value(data).unwrap()).unwrap();
```

This works, but it would be nice if there is a way to do this without the additional `to_value`. Is that possible? Thanks!

**Comment by dtolnay** [comment]
The [`IntoDeserializer`](https://docs.rs/serde/1.0.104/serde/de/trait.IntoDeserializer.html) trait and the implementations of it in [`serde::de::value`](https://docs.rs/serde/1.0.104/serde/de/value/index.html) provide a way to deserialize directly from a map without the to_value conversion or allocations.

```rust
use serde::de::value::MapDeserializer;
use serde::Deserialize;
use serde_json::Value;
use std::collections::HashMap;

#[derive(Deserialize, Debug)]
struct MyStruct {
    a: usize,
    b: usize,
}

fn main() {
    let content = "{\"a\":1}";
    let mut data: HashMap<&str, Value> = serde_json::from_str(content).unwrap();
    data.insert("b", Value::from(2));
    let v = MyStruct::deserialize(MapDeserializer::new(data.into_iter())).unwrap();
    println!("{:#?}", v);
}
```

**Comment by svanharmelen** [comment]
Super nice @dtolnay! Exactly the kind of solution I was hoping for 👍 Thanks!

**Comment by svanharmelen** [comment]
Hmm... I actually have the same issue/question for doing this the other way around.

So serialize a struct into a `HashMap`. Again I can do this in two stages (first using `to_value` and then using `from_value` to get a `HashMap`.

But I guess/hope there is be a better way to achieve this? Thanks!

**Comment by svanharmelen** [comment]
Hmm...Maybe a better solution for my problem/challenge is something along the lines of https://github.com/serde-rs/serde/issues/1470

Asked an addition questions there about that approach so think this one can be closed then.

**Comment by svanharmelen** [comment]
Guess I'll close this issue as I don't expect any updates anymore...

**Comment by norbertkeri** [comment]
@dtolnay I can't seem to get your example to work with serde_yaml (but it works fine with json). Am I doing something wrong, or is this just a feature that is not yet implemented?

```
error[E0277]: the trait bound `serde_yaml::value::Value: _::_serde::de::IntoDeserializer<'_, _>` is not satisfied
  --> src/main.rs:16:35
   |
16 |     let v = MyStruct::deserialize(MapDeserializer::new(data.into_iter())).unwrap();
   |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `_::_serde::de::IntoDeserializer<'_, _>` is not implemented for `serde_yaml::value::Value`
   |
   = note: required because of the requirements on the impl of `_::_serde::Deserializer<'_>` for `_::_serde::de::value::MapDeserializer<'_, std::collections::hash_map::IntoIter<&str, serde_yaml::value::Value>, _>`
   = note: required by `_::_serde::Deserialize::deserialize`

error: aborting due to previous error
```

**Comment by dtolnay** [comment]
@norbertkeri serde_yaml does not implement this but I filed https://github.com/dtolnay/serde-yaml/issues/169 to follow up.

**Comment by norbertkeri** [comment]
Thanks!

**Comment by bugproof** [comment]
Can't you just deserialize to `serde_json::Value` and then use `as_object`? Or is it less efficient?
