### ISSUE TITLE
Weird target type for Expected, for str cases

### ISSUE THREAD

**Issue by dingxiangfei2009** [serde-rs/serde#1743]
Referring to
https://github.com/serde-rs/serde/blob/27c283ab531271078b338aa4229e695e3da58ea3/serde/src/de/mod.rs#L485

It should have been `impl Expected for str`, so that when `&'a str` is used as `&dyn Expected`, which is mostly seen in uses of `de::Error` associated methods, `&s as &str` is sufficient instead of writing `&(&s as &str)`.

It is weird anyway that it is implemented on `&'a str`, since this traits mostly mimics the `std::fmt::Display` trait while `std::fmt::Display` has been implemented for `str` directly.

**Comment by dtolnay** [comment]
This is required for str to be usable as dyn Expected which is what the APIs in serde::​de::Error all take. &amp;str cannot be used as &amp;dyn Expected because a fat ptr can only have one vtable or len, not two.
