### ISSUE TITLE
Does serde have a new channel for after the mozilla IRC sunset yet?

### ISSUE THREAD

**Issue by jplatte** [serde-rs/serde#1745]
The README.md still mentions irc.mozilla.org, which is going to be shut down. Does serde have any rooms on alternative chat platforms already / is there a plan for an alternative after irc.mozilla.org is gone?

**Comment by skeet70** [comment]
Mozilla itself has switched to https://riot.im/app/#/room/#general:mozilla.org is there going to be a https://riot.im/app/#/room/#serde:mozilla.org? `irc.mozilla.org` seems to be down now. Or will serde be on discord somewhere, which seems to be where the Rust team has generally moved?

**Comment by dtolnay** [comment]
I have updated the readme to suggest other resources.

**Comment by Shados** [comment]
You mention an 'unofficial community Discord' in the readme, but only provide channel links, not an invite link.
