### ISSUE TITLE
The attribute `serde` is currently unknown to the compiler and may have meaning added to it in the future

### ISSUE THREAD

**Issue by redlolgeerf** [serde-rs/serde#175]
I'm trying to rename field:

    #![feature(custom_derive, plugin)]
    #![plugin(serde_macros)]

    extern crate serde;
    extern crate serde_json;

    #[derive(Deserialize, Debug)]
    struct Message {
        #[serde(rename="type")]
        event_type: String,
        payload: String,
    }

but I get error

The attribute `serde` is currently unknown to the compiler and may have meaning added to it in the future.

Cargo.toml:

    [dependencies]
    serde = "*"
    serde_json = "*"
    serde_macros = "*"

> rustc -V
> rustc 1.5.0-nightly (1210fb9bc 2015-10-23)

from Cargo.lock:

    [[package]]
    name = "serde"
    version = "0.6.1"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    dependencies = [
     "num 0.1.27 (registry+https://github.com/rust-lang/crates.io-index)",
    ]

    [[package]]
    name = "serde_codegen"
    version = "0.6.1"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    dependencies = [
     "aster 0.5.0 (registry+https://github.com/rust-lang/crates.io-index)",
     "quasi 0.3.5 (registry+https://github.com/rust-lang/crates.io-index)",
     "quasi_macros 0.3.5 (registry+https://github.com/rust-lang/crates.io-index)",
    ]

    [[package]]
    name = "serde_json"
    version = "0.6.0"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    dependencies = [
     "num 0.1.27 (registry+https://github.com/rust-lang/crates.io-index)",
     "serde 0.6.1 (registry+https://github.com/rust-lang/crates.io-index)",
    ]

    [[package]]
    name = "serde_macros"
    version = "0.6.1"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    dependencies = [
     "serde_codegen 0.6.1 (registry+https://github.com/rust-lang/crates.io-index)",
    ]

**Comment by Luthaf** [comment]
You need to add `#![feature(custom_attribute)]` to your module to enable this feature.

I got help from rustc about this on nightly 1.6.0, but not on stable 1.4.0.

**Comment by erickt** [comment]
Should be fixed in the upcoming 0.6 release!
