### ISSUE TITLE
[help] How to work with utf8 String with bom

### ISSUE THREAD

**Issue by zsynacl** [serde-rs/serde#1753]
I'm new to serde, maybe my question is silly. So sorry to take up your precious time to give some help to me at first  .
I tried to find simular questions on google but noting found.

I'm trying to parse a json string from url `"http://www.csindex.com.cn/zh-CN/indices/index-detail/000001?earnings_performance=5年&data_type=json"`

I have tried these code
```rust
#[derive(Serialize, Deserialize, Debug)]
struct Index {
    indx_code: String,
    tclose: String,
    tradedate: String,
    changes: String,
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let client : Client = Client::new();
    let rsp = client
        .get("http://www.csindex.com.cn/zh-CN/indices/index-detail/000001?earnings_performance=5年&data_type=json")
        .header(CONTENT_TYPE, HeaderValue::from_static("application/json;charset=utf-8"))
        .send().await?;
    let c: String = rsp.text().await?;
    let result = serde_json::from_str::<Vec<Index>>(&c)?;  // won't work
    let txt = String::from(r#"[{"indx_code":"000001","tclose":"3449.31","tradedate":"2015-03-16 00:00:00","changes":"-5.08"}]"#);
    let tmp = &c[0..txt.len()];
    assert_eq!(tmp, txt);
    Ok(())
}
```
serde_json can not deserialize the string from remote server. Serde complains as follows:
```shell
Error: Error("expected value", line: 1, column: 1)
```
I find the string from server has BOM with `assert_eq`:
```shell
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `"\u{feff}[{\"indx_code\":\"000001\",\"tclose\":\"3449.31\",\"tradedate\":\"2015-03-16 00:00:00\",\"changes\":\"-5.08"`,
 right: `"[{\"indx_code\":\"000001\",\"tclose\":\"3449.31\",\"tradedate\":\"2015-03-16 00:00:00\",\"changes\":\"-5.08\"}]"`', src\main.rs:28:5
```

I am confused whether serde support utf8 with bom or not. Or any solutions I can do at this situation.

**Comment by dtolnay** [comment]
We don't support utf8 with bom, but you could trim it out of the input string before calling serde_json:
https://doc.rust-lang.org/std/string/struct.String.html#method.trim_start_matches

**Comment by zsynacl** [comment]
> 
> 
> We don't support utf8 with bom, but you could trim it out of the input string before calling serde_json:
> https://doc.rust-lang.org/std/string/struct.String.html#method.trim_start_matches

That's it! Thank you very much! 

Code works now.
```rust
let result = serde_json::from_str::<Vec<Index>>(c.trim_start_matches("\u{feff}"))?;
```

**Comment by SirWindfield** [comment]
@dtolnay Is BOM support something that would be accepted in a PR? If yes, should it be implemented in the child crates `serde-json`, `toml` etc or inside of `serde` itself?
