### ISSUE TITLE
Implement custom deserialization reusing derived deserializers

### ISSUE THREAD

**Issue by slinkydeveloper** [serde-rs/serde#1758]
Hi!
I'm developing a library to support https://github.com/cloudevents/spec and I'm trying to plug a custom deserialization logic reusing the generated deserializers.

My data structures are (annotations omitted, links to the code at the end):

```rust
pub struct Event {
   pub attributes: Attributes,
    pub data: Option<Data>,
    pub extensions: HashMap<String, ExtensionValue>,
}
pub enum Attributes {
    V10(AttributesV10),
}
pub struct AttributesV10 {
    id: String,
    ty: String,
    source: String,
    datacontenttype: Option<String>,
    dataschema: Option<String>,
    subject: Option<String>,
    time: Option<DateTime<Utc>>,
}
pub enum Data {
    Binary(Vec<u8>),
    Json(serde_json::Value),
}
```

An event in json looks like:

```
{
    "specversion" : "1.0",
    "type" : "com.example.someevent",
    "source" : "/mycontext",
    "id" : "A234-1234-1234",
    "time" : "2018-04-05T17:31:00Z",
    "comexampleextension1" : "value",
    "comexampleothervalue" : 5,
    "datacontenttype" : "text/xml",
    "data" : "<much wow=\"xml\"/>"
}
```

Because I need to support several versions of the spec, I need to tweak a little bit the deserialization/serialization logic of the `data` field, but I wish to avoid to develop from scratch all deserializers. The generated serializers/deserializers for `Attribute` works quite well using the enum tag feature, but I can't manage to plug the logic to correctly deserialize the `data` field using the macro. In particular:  

* If specversion == "0.3" then I need to look into one field in attributes and decide to read the `data` as binary (base64) or as json
* If specversion == "1.0" then I need to seek or for the `data` field or for the `data_base64` field to parse the final `Data` as base64 or not

I managed to get the specversion 1.0 case working with macros, but at the same time i can't make the 0.3 version working, so i decide to try to roll out my own `Deserialize` for `Event`. The parsing logic would be:

1. First I parse the attributes
1. Then, given the attributes, I parse the `data` field
1. In the end I take care of extensions (which are all the other fields)

So I came up with this:

```rust
impl<'de> Deserialize<'de> for Event {
    fn deserialize<D>(deserializer: D) -> Result<Self, <D as Deserializer<'de>>::Error> where
        D: Deserializer<'de> {
        let attributes: Attributes = Attributes::deserialize(deserializer)?;
        let event_visitor = EventVisitor {
            attributes,
            extensions: HashMap::new()
        };
        deserializer.deserialize_map(event_visitor)
    }
}
```

Where `EventVisitor`:

```rust
struct EventVisitor {
    attributes: Attributes,
    extensions: HashMap<String, ExtensionValue>
}

impl<'de> Visitor<'de> for EventVisitor {
    type Value = Event;

    fn visit_map<A>(mut self, mut map: A) -> Result<Self::Value, <A as MapAccess<'de>>::Error> where
        A: MapAccess<'de>, {
        while let Some(k) = map.next_key()? {
            // Parse data or extension
        }

        Ok(Event{
            data: None,
            attributes: self.attributes,
            extensions: self.extensions
        })
    }
}
```

Problem is, this code doesn't compile because `Attributes::deserialize(deserializer)` takes ownership of `deserializer`, so I suppose I'm on the wrong way to solve it...
Do you have any ideas how to solve this? If yes, there is any guide on how to write a deserializer given another derived deserializer? 

Original code: https://github.com/cloudevents/sdk-rust/blob/master/src/event/event.rs#L36, https://github.com/cloudevents/sdk-rust/blob/master/src/event/attributes.rs#L54, https://github.com/cloudevents/sdk-rust/blob/master/src/event/v10/attributes.rs & https://github.com/cloudevents/sdk-rust/blob/master/src/event/data.rs#L9

**Comment by dtolnay** [comment]
Hi @slinkydeveloper, sorry that no one was able to provide help here. If this is still an issue, you could try taking this question to any of the resources shown in https://github.com/serde-rs/serde#getting-help.

**Comment by slinkydeveloper** [comment]
Hi @dtolnay I ended up developing by hand my own serde code
