### ISSUE TITLE
how to deserialize enum with variable string

### ISSUE THREAD

**Issue by guotie** [serde-rs/serde#1759]
for example, I want to deserialize these json:

```
{"type": "result.xxxx", "data": {}}
{"type": "catalog.xxxxx", "data": {} }
```

the field type is not constant, how to deserialize them?

**Comment by maciejhirsz** [comment]
https://serde.rs/enum-representations.html#internally-tagged

**Comment by guotie** [comment]
yes, I mean the tag itself is arbitrary.

**Comment by guotie** [comment]
solved.

see: 
https://github.com/serde-rs/serde/issues/1470
