### ISSUE TITLE
ast::VariantData

### ISSUE THREAD

**Issue by MarkSwanson** [serde-rs/serde#176]
When I compile serde (git master) it works fine (aster 0.5.0 compiles)

However, when I use serde in my own app I have compilation troubles with aster 0.5.0:

aster-0.5.0/src/item.rs:467:18: 467:34 error: use of undeclared type name `ast::VariantData` [E0412]

What's the recommended way around this?

**Comment by erickt** [comment]
This should now work if you do a a `cargo update`. It was fixed in aster 0.6.2 and serde_codegen 0.6.2. Please reopen if you're still having trouble.
