### ISSUE TITLE
Deserialize Type Passed to Method

### ISSUE THREAD

**Issue by synical** [serde-rs/serde#1760]
Hello

I'm playing around with serde and Rust (not very experienced) and am trying to work out how I can create a method that takes a JSON string ref and deserializes it into an arbitrary struct that implements a trait.

```
use serde::{Serialize, Deserialize};

struct SomeStruct {
}

#[derive(Debug, Serialize, Deserialize)]
struct SomeOtherStruct {
    name: String
}

trait SomeTrait {
    fn some_method(self);
}

impl SomeTrait for SomeOtherStruct {
    fn some_method(self) {}
}

impl SomeStruct {
    pub fn deserialize_something<T: SomeTrait>(&self, s: &str) {
        let deserialized: T = serde_json::from_str(&s).unwrap();
    }
}

fn main() {
    let some_struct = SomeStruct{};
    some_struct.deserialize_something::<SomeOtherStruct>("{\"name\": \"test\"}");
}
```

When running the below code, serde complains that Deserialize is not implemented for the underlying type of "T":

```
error[E0277]: the trait bound `T: _IMPL_DESERIALIZE_FOR_SomeOtherStruct::_serde::Deserialize<'_>` is not satisfied
    --> src/main.rs:16:31
     |
15   |     pub fn deserialize_something<T: SomeTrait>(&self, s: &str) {
     |                                  - help: consider restricting this bound: `T: _IMPL_DESERIALIZE_FOR_SomeOtherStruct::_serde::Deserialize<'_>`
16   |         let deserialized: T = serde_json::from_str(&s).unwrap();
     |                               ^^^^^^^^^^^^^^^^^^^^ the trait `_IMPL_DESERIALIZE_FOR_SomeOtherStruct::_serde::Deserialize<'_>` is not implemented for `T
```

Changing the type of the "deserialized" from "T" to "SomeOtherStruct" works ok so I'm assuming this is something related to deriving Deserialize when passing in via "T".

I couldn't see an existing issue for this, so was wondering if anyone could show me where I am going wrong?

```
[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
```

Thanks

**Comment by dtolnay** [comment]
Hi @synical, sorry that no one was able to provide help here. If this is still an issue, you could try taking this question to any of the resources shown in https://github.com/serde-rs/serde#getting-help.
