### ISSUE TITLE
help: Deserialize vector of enums to struct

### ISSUE THREAD

**Issue by Hywan** [serde-rs/serde#1761]
Hello,

I struggle to deserialize a vector of enums to any struct that implements/derives `Deserialize`. Here is the kind of thing I would like to get:

```rust
// The targeted data that will receive the deserialized data
#[derive(Deserialize)] 
struct Point {
    x: i32,
    y: i32
}

enum Value {
    I32(i32),
    I64(i64),
}

let vector: Vec<Value> = vec![Value::I32(1), Value::I32(2)];
let result: Point = some_magic_here(vector);

assert_eq!(result, Point { x: 1, y: 2 });
```

I don't know where to start or how to handle this. Is it even possible knowing that `vector` isn't aware of the `Point` fields?

Thank you for your help.

**Comment by Hywan** [comment]
I think I've to implement `Deserializer` for `Vec<Value>`, and for each `deserialize_<type>`, match the corresponding `Value::<type>`. Just like in https://serde.rs/impl-deserializer.html.

(Github is my yellow 🦆)

**Comment by MarkMcCaskey** [comment]
@hywan I made an example adapted from the serde docs for you: https://github.com/MarkMcCaskey/serde-format-example.  Posting it publicly in case it is helpful to other people!
