### ISSUE TITLE
Serde requires all generics of internal struct to be serializable, but in.str do not needs it.

### ISSUE THREAD

**Issue by TrionProg** [serde-rs/serde#1763]
Hello.

Outer struct State contains internal struct StateA. State A uses generics A and R, but only F serializes. But outer struct State requires all generics to be serializable.

How to fix it?

Code
```rust
//A and R should not be serializable.
//Serde needs all generics of struct inside(StateA) to be serializable

use serde::{Serialize, Deserialize};
use core::marker::PhantomData;

#[derive(Serialize, Deserialize)]

pub enum State<A, F, R> {
    Done(/*PhantomData<(A, R)>*/), //StateA already contains PhantomData
    A(StateA<A, F, R>),//A and R should not be serializable!!
}

#[derive(Serialize, Deserialize)]
pub struct StateA<A, F, R> {
    f:F,//We do not serialize A and R
    
    #[serde(skip_serializing)] //no effect
    #[serde(default)]
    _phantom_data:PhantomData<(A, R)>
}

impl<A, F, R> MyTrait for StateA<A,F,R> where
    F: std::fmt::Display
{
    type A = A;
    type R = R;
    
    //We just use R, or A
    fn poll(&self, r:Self::R) -> Self::R {
        println!("{}", self.f);
        r
    }
}

pub trait MyTrait {
    type A;
    type R;
    
    fn poll(&self, r:Self::R) -> Self::R;
}

fn check<F>(f:&F) where
    F:Serialize + for<'de> Deserialize<'de>
{
    
}

fn main() {
    let mut d = 77i32;
    let ptr = &mut d as *mut i32;
    
    //A and R should not be serializable
    let state_a = StateA::<*mut u32, usize, *mut i32> { 
        f:66,
        _phantom_data: PhantomData
    };
    
    check(&state_a);//Works, we do not serialize A and R
    
    let state = State::A(state_a);
    
    //State want A and R to be serializable
    check(&state);
}

```

Playground:

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b8d90e1589b9c98123740152e671af09

Second problem:
Ok, A and R need to be serializable.

In my case where is a lot of code. But I have this problem:
Somebody requires State to be serializable, I think, StateA, because It uses A, F, R and has reference to State(this is generic). Compiler writes about type State:
`the trait bound A: serde::Serialize is not satisfied`
or
`the trait bound A: serde::Deserialize<'de> is not satisfied`

When I write:
where `A:Serialize`, compiler hides this error, but what to do with `A: Deserialize<de>`? if I write `for<'de> Deserialize<'de>` compiler says, that 'de shadows on existing lifetime parameter, but without 'de it do not knows 'de.

**Comment by jonasbb** [comment]
You can manually specify the trait bound for the derived traits using [`#[serde(bound(serialize="..."))]`](https://serde.rs/container-attrs.html#bound).
In this case you can probably add `#[serde(bound(serialize="F: Serialize", deserialize="F: Deserialize<'de>"))]`.

**Comment by TrionProg** [comment]
@jonasbb Thank you. As I understand, this manual bounds will remove all serde automatical bounds?

Unfortunatelly, second problem still exists =(

It is about:
```rust
pub enum State<A, F, R> where
  A:Serialize + Deserialize<'de> //It requires this line, but it does not compiles
{
    Done(/*PhantomData<(A, R)>*/), //StateA already contains PhantomData
    A(StateA<A, F, R>),//A and R should not be serializable!!
}
```

**Comment by jonasbb** [comment]
Your example code above compiles when adding the `#[serde(bound(...))]` to both the `State` and `StateA` types. I'm unsure what exactly your second problem is after adding this attribute.

**Comment by TrionProg** [comment]
@jonasbb Thank you for your help!
I spent a lot of time and I have made essention of this problem:
https://github.com/serde-rs/serde/issues/1770
