### ISSUE TITLE
Partial deserialization

### ISSUE THREAD

**Issue by d-e-s-o** [serde-rs/serde#1765]
(while titles are the same, https://github.com/serde-rs/serde/issues/1154 seems to have different intentions)

I can't seem to find a way to do the following:

I receive JSON data and effectively what it is is an object with multiple levels of nesting. E.g.,
```json
{"outer":"foo","middle":{"inner":{"bar":"baz"}}}
```

I want to deserialize the two outer level but then retrieve the value of the `inner` attribute (`{"bar":"baz"}`) as raw bytes. Is there a way to go about this?

I understand I could parse the inner portion as `serde_json::Value` but I don't want to parse it, at all. It does not seem possible to convince a `Deserializer` to grant access to the underlying data.

Any suggestions?

Edit: Btw., https://serde.rs/help.html still mentions irc.mozilla.org which I don't think is live anymore)

**Comment by dtolnay** [comment]
Use https://docs.rs/serde_json/1/serde_json/value/struct.RawValue.html:

```rust
// [dependencies]
// serde = { version = "1.0", features = ["derive"] }
// serde_json = { version = "1.0", features = ["raw_value"] }

use serde::Deserialize;
use serde_json::value::RawValue;

#[derive(Deserialize, Debug)]
struct Struct {
    outer: String,
    middle: Middle,
}

#[derive(Deserialize, Debug)]
struct Middle {
    inner: Box<RawValue>, // or &'a RawValue
}

fn main() {
    let j = r#" {"outer":"foo","middle":{"inner":{"bar":"baz"}}} "#;
    println!("{:#?}", serde_json::from_str::<Struct>(j).unwrap());
}
```

```console
Struct {
    outer: "foo",
    middle: Middle {
        inner: RawValue(
            {"bar":"baz"},
        ),
    },
}
```

**Comment by d-e-s-o** [comment]
Works like a charm. Thanks for the quick help! Not sure how I missed that.
