### ISSUE TITLE
Deserializing variable length encoding

### ISSUE THREAD

**Issue by disconsented** [serde-rs/serde#1766]
I am trying to implement a pre-defined network protocol but I am being caught up with a couple of its design decisions. At the moment I am working on implementing packets that rely on lengths being represented as 1 to 5 bytes, the structs are as follows.

```rust
struct VarVec{
  length: VarInt,
  data: Vec<u8>
}
```

```rust
struct Packet {
    packet_length: VarInt,
    packet_id: VarInt,
    #[serde(serialize_with = "ser_vec_no_len")]
    data: Vec<u8>,
}
```
Upon trying to implement Deserialize for VarVec I've realized that deserialize_seq still tries to determine the length ahead of time. 

Is serde a suitable choice for this kind of thing?

I've managed to get serialization for these types working as expected.

**Comment by dtolnay** [comment]
Hi @disconsented, sorry that no one was able to provide help here. If this is still an issue, you could try taking this question to any of the resources shown in https://github.com/serde-rs/serde#getting-help.
