### ISSUE TITLE
Add optional `serialize_rust_field` for guaranteed rust identifiers

### ISSUE THREAD

**Issue by michalsrb** [serde-rs/serde#1767]
This is a suggestion, but I would be happy to also implement it, if you think it is a good idea.

Add a `serialize_rust_field` method to the `Serialize[Tuple]Struct[Variant]` traits, that does the same thing as the `serialize_field` method, but adds a guarantee that the `name` is a [valid Rust identifier](https://doc.rust-lang.org/reference/identifiers.html). It would have default implementation that just calls the method `serialize_field`:

```rust
    /// Serialize a struct field.
    ///
    /// The name is guaranteed to be a valid Rust identifier made of characters:
    ///   [a-z A-Z] [a-z A-Z 0-9 _]* | _ [a-z A-Z 0-9 _]+
    fn serialize_rust_field<T: ?Sized>(
        &mut self,
        key: &'static str,
        value: &T,
    ) -> Result<(), Self::Error>
    where
        T: Serialize;
    {
        self.serialize_field(key, value)
    }
```

Serializers may take advantage of the guarantee and provide more efficient implementation. For example `serde_json` could print this string without checking for escape characters.

Of course, anyone could still call the method with a string that does not fulfill the guarantee, so serializers should not rely on it to the point that could cause unsafety, but it is ok if it just causes incorrect output.

I would expect that this method will be called mostly by the derived `Serialize` implementation and rarely by manually written implementations. The derived implementation must not call it if the field is renamed with `#[serde(rename = "name")]` to something that isn't valid Rust identifier.

-----

We could also do the same thing for the name argument in `serialize_struct`, `serialize_tuple_struct`, etc...

**Comment by dtolnay** [comment]
Can you provide a benchmark to show the impact of this? The escape character scanning is not a significant cost in my experience, and especially not for short strings.

**Comment by Kogia-sima** [comment]
Thanks to a significant improvement of the "const fn" feature in rust 1.46.0, now we can check if escape is needed at compilation time:

```rust
const fn should_escape(feed: &str) -> bool {
    let bytes = feed.as_bytes();

    let mut i = 0;
    while i < feed.len() {
        if bytes[i] <= 0x1f || bytes[i] == b'"' || bytes[i] == b'\\' {
            return true;
        }

        i += 1;
    }

    false
}
```

Have a nice day!

**Comment by dtolnay** [comment]
I'll go ahead and close. In the absence of a really compelling benchmark, I don't feel that this would be worthwhile to build into the serde crate.
