### ISSUE TITLE
Problem with cyclic generics and Traits with bounds Ser/Deser

### ISSUE THREAD

**Issue by TrionProg** [serde-rs/serde#1770]
Hello. I have the large problem. 

I have abstract FSM, and I need to mark it Serializable/Deserializable. That is why I have trait FSMTrait with methods ser/deser, and they use bincode. In the best case I need to use FSMTrait as TraitObject(but I know how implement it). All works good, but then I use SimpleState with generic parameter FS, I have strange errors like `the trait bound `F: _IMPL_DESERIALIZE_FOR_FSM::_serde::Serialize` is not satisfied`

Code:
```rust
pub trait FSMTrait where Self:Sized /*+ Serialize + for<'de> Deserialize<'de>*/ {//Problem is in this line(uncomment)
    fn serialize();
    fn deserialize();
}

pub trait MyTrait {
    type A;
    type R;
    
    fn foo(a:Self::A) -> Self::A;
}

#[derive(Serialize, Deserialize)]
#[serde(bound(serialize="F: Serialize", deserialize="F: Deserialize<'de>"))]
pub enum FSM<A, F, R> where
    F:MyTrait<A=A, R=R> //+ Serialize + for<'d> Deserialize<'d> //do not helps
{
    //Done(PhantomData<(A, F, R)>),
    Done,
    //A(SimpleNode<A, F, R>) //works without Self or FSM<A,F,R>
    A(SimpleState<Self, A, F, R>)
}

impl<A, F, R> FSMTrait for FSM<A, F, R> where 
    //Self:Sized + Serialize + for<'de> Deserialize<'de>, //Problem is in this line
    F:MyTrait<A=A, R=R> + Serialize + for<'de> Deserialize<'de> //or problem is here. We need Self to be serializable
{
    fn serialize() {
        //bincode...
    }
    fn deserialize(){
        //bincode...
    }
}

//SimpleState needs FSM(FS) for some purpose, It do not needs FSM as field, it just has method that have argument:reference to FSM
//FSM(FS) must be generic(where are a lot of FSM)
#[derive(Serialize, Deserialize)]
pub struct SimpleState<FS, A, F, R> where
    FS:FSMTrait
{
    _phantom_data:PhantomData<(FS, A, F, R)>
}
```

You may play here:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a00391de6a2077d503414b27c103d1f0

**Comment by dtolnay** [comment]
This is the correct behavior; your `enum FSM<A, F, R> where F: MyTrait<A = A, R = R>` contains a field of type `SimpleState<Self, A, F, R>`, but the definition of `SimpleState<FS, A, F, R>` requires that `FS: FSMTrait` i.e. in FSM it would require `FSM<A, F, R>: FSMTrait`, and that impl only exists if `F: Serialize + for<'de> Deserialize<'de>` which is not necessarily true in the definition of FSM. Here is a fix with the right bound: https://play.rust-lang.org/?edition=2018&gist=ed0cfc697c69ec7b5f0a9f500960ee74

**Comment by TrionProg** [comment]
Hello. This compiles!! Thank you very much. You have saved my project!

But I still do not know if my project will works.
