### ISSUE TITLE
Deserializing enums with fallback value while still retaining key access

### ISSUE THREAD

**Issue by SirWindfield** [serde-rs/serde#1775]
I have some json in the form of:
```json
{
  "interactions": {
    "look": {},
    "take": {},
    "some_new_name": {}
  }
}
```

I would love to deserialize it using this enum:
```rust
pub enum Interaction {
    Look,
    Take,
    Custom(String),
}
```

Is that currently possible using `serde`? I need access to the custom map key `some_new_name`. I know that it is possible to tag it with `#[serde(other)]` and have a fallback enum value but that does not seem to allow me to access the key itself.

Thanks for taking your time!
P.S.: If there is some other way you achieve my goal, let me know! I just thought that enums make the most sense here. But maybe some specially crafted struct might do the trick.

**Comment by dtolnay** [comment]
Try something like this:

```rust
use serde::Deserialize;
use serde_json::Value;
use std::collections::HashMap;

#[derive(Deserialize, Debug, Eq, PartialEq, Hash)]
#[serde(field_identifier, rename_all = "lowercase")]
pub enum Interaction {
    Look,
    Take,
    Custom(String),
}

const J: &str = r#"{
  "interactions": {
    "look": {},
    "take": {},
    "some_new_name": {}
  }
}"#;

#[derive(Deserialize, Debug)]
struct Data {
    interactions: HashMap<Interaction, Value>,
}

fn main() {
    let obj: Data = serde_json::from_str(J).unwrap();
    println!("{:?}", obj);
}
```

```console
Data {
    interactions: {
        Look: Object({}),
        Take: Object({}),
        Custom("some_new_name"): Object({}),
    },
}
```

**Comment by SirWindfield** [comment]
As far as I can tell this attribute has not been documented [here](https://serde.rs/attributes.html).
