### ISSUE TITLE
Add variant of `serialize_seq` method that doesn't pass length

### ISSUE THREAD

**Issue by ZoeyR** [serde-rs/serde#1776]
I'm working on implementing the ability to serialize sequences of unknown length in `bincode` and ran into an optimization issue. Since `serialize_seq` has to return the same type regardless of whether `Some` or `None` is passed in for the length, there is no way to avoid multiple branches for handling sequence serialization. (Each call to `serialize_element` will have to determine if it is in "length" or "no length" mode)

I think it would make more sense from an optimization perspective for there to be a new method `serialize_seq_no_length` that returns a distinct type so that branching can be avoided.

**Comment by dtolnay** [comment]
Would you be able to put together a benchmark quantifying the cost of the branch?
