### ISSUE TITLE
Deserialize map value which is a string containing space to a vector of strings

### ISSUE THREAD

**Issue by Fiono11** [serde-rs/serde#1781]
Hello! I need to deserialize the following json into a struct:

```
{
  "blocks": {
    "field1": ["142A538F36833D1CC78B94E11C766F75818F8B940771335C6C1B8AB880C5BB1D"],
    "field2": ["4C1FEEF0BEA7F50BE35489A1233FE002B212DEA554B55B1B470D78BD8F210C74"]
  }
}
```
I tried this, but doesn't work:
```
#[derive(Deserialize, Debug)]
struct WalletPending {
    blocks: HashMap<String, Vec<Option<String>>>,
}
```
The arrays can have more than one element or be empty and there can be more "fields". How can I do this? Thanks!

**Comment by dtolnay** [comment]
Seems to work. https://play.rust-lang.org/?edition=2018&gist=d3986a2e9cf610278ccebacf784cc28a

**Comment by Fiono11** [comment]
I was using "from_slice" to deserialize from bytes. When I convert the bytes to a string, blank spaces appear as "/", and that's why it gives me the error "Error("invalid type: string \"\")". Anyway I can solve this?

**Comment by Fiono11** [comment]
Foud this issue: https://github.com/serde-rs/serde/issues/1425.
However, I can't seem to adapt it to my struct. Can someone help me, please?

**Comment by jonasbb** [comment]
@Fiono11 The current version of `serde_with` is unfortunately not very composable, so your case is not easily supported. With the development version it git however, this is possible. Note the value of `field1` is different compared to your playground link.

```Rust
:dep serde = {version = "*", features = ["derive"]}
:dep serde_json
:dep serde_with = { git = "https://github.com/jonasbb/serde_with" }

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use serde_with::{As, Same, NoneAsEmptyString};

#[derive(Serialize, Deserialize, Debug)]
struct WalletPending {
    #[serde(with = "As::<HashMap<Same, Vec<NoneAsEmptyString>>>")]
    blocks: HashMap<String, Vec<Option<String>>>,
}

fn main() {
    let j = r#"
        {
          "blocks": {
            "field1": [""],
            "field2": ["4C1FEEF0BEA7F50BE35489A1233FE002B212DEA554B55B1B470D78BD8F210C74"]
          }
        }
    "#;

    let value = serde_json::from_str::<WalletPending>(j).unwrap();
    println!("Value:\n{:#?}", value);
    println!("---");
    println!("JSON:\n{}", serde_json::to_string_pretty(&value).unwrap());
}
main()
```

    Value:
    WalletPending {
        blocks: {
            "field2": [
                Some(
                    "4C1FEEF0BEA7F50BE35489A1233FE002B212DEA554B55B1B470D78BD8F210C74",
                ),
            ],
            "field1": [
                None,
            ],
        },
    }
    ---
    JSON:
    {
      "blocks": {
        "field2": [
          "4C1FEEF0BEA7F50BE35489A1233FE002B212DEA554B55B1B470D78BD8F210C74"
        ],
        "field1": [
          ""
        ]
      }
    }
