### ISSUE TITLE
Multiple serialization 'profiles' for one type

### ISSUE THREAD

**Issue by inzanez** [serde-rs/serde#1783]
Hi

I was wondering if it were somehow possible to define multiple serialization profiles for one specific type. Having done a lot of work with NewtonSoft JSON in C#, I got used to being able to define different profiles for a specific type. For example an encrypted messages:
- Against the database, I need to store additional information like 'nonce' or 'salt' etc. As my database is storing JSON directly, I use serde to create the database entry
- Sending the encrypted message to the user (after decryption of course) however, should not include things like `nonce` or `salt`.

The same approach could be taken for a Json-API like web API: the request contains information about what fields should be pulled from the database. So the field-set could be different for every request. One solution of course would be to make all the fields optional, but sometimes I need to make sure that the field actually exists (so it should not be `Option<...>`), but still the end-user needs to be able to chose not to receive it in the JSON response.

I haven't seen any other way than creating different types (like data transfer objects) and implementing something like `From` to make a conversion from the actual struct to the stripped down transfer struct. But then I believe that this is quite an overhead for just selecting the fields to be serialized.

Is there a better way to achieve that?

**Comment by dtolnay** [comment]
This isn't supported in serde, but I would be interested in someone developing a different library that is more suited to this use case.

**Comment by yogevm15** [comment]
@dtolnay 
I recently created a [crate for this](https://crates.io/crates/serde_many) that might be helpful.
