### ISSUE TITLE
Introspection in serde

### ISSUE THREAD

**Issue by Ploppz** [serde-rs/serde#1785]
Hello,

I think that introspection is a real need, and I was thinking about making a crate for type introspection. I personally want to use that for OpenAPI spec generation (in the `paperclip` crate), but it will be a general crate I think.

Introspection is needed in many use cases, especially to facilitate interoperability with other languages. Most such use cases are connected to serde - we want to generate a specification of the format we use to communicate with other components, not the Rust struct itself. (these two differ when we use serde attributes like `rename`, `flatten`, `tag`).

As such I found it fitting to ask for a discussion here.
Following https://github.com/serde-rs/serde/issues/345, the conclusion seems to be that any such functionality has to come from some other crate.
So what I have in mind is a crate which is really general, and gives information that can be useful to any application. Maybe it should not treat `serde` attributes specially but preserve and present all attributes in the runtime schema. As such, usage in conjunction with `serde` is _one_ use case.

What do I mean with "runtime schema": the approach I'm thinking is some derive macro e.g. `Introspection` that has a function that returns a struct describing everything about the Rust struct/enum definition. This struct is the "runtime schema".

So I am wondering whether you envision any support for introspection in serde.
Can I design this crate in a way such that you want to include support for it in serde? Thinking something like: If some feature is enabled in serde, then `#[derive(Serialize, Deserialize)]` will also derive `Introspection`. Perhaps serde will make its own "runtime schema" struct which takes into account serde's attributes to flatten, rename etc... many possibilities.
Or any other thoughts?

**Comment by dtolnay** [comment]
This isn't something that would be accepted into Serde (so I'll close the issue) but it could be implemented on top of Serde, either based on the type information present in Deserialize trait impls:

- https://github.com/facebookincubator/serde-reflection

or based on a macro that uses [serde_derive_internals](https://crates.io/crates/serde_derive_internals) to process `#[serde(...)]` attributes:

- https://crates.io/crates/schemars_derive
- https://crates.io/crates/typescript-definitions-derive
- https://crates.io/crates/reflection_derive
- https://crates.io/crates/serde_schema_derive
- https://crates.io/crates/wasm-typescript-definition
