### ISSUE TITLE
duplicate json tag field for enum/struct tags

### ISSUE THREAD

**Issue by abdolence** [serde-rs/serde#1786]
Now we can define tags on structs (which is a great thing), but in the cases you need tags both on enums and structs, there is a duplicate type tag in JSON now:

```rust
#[serde(tag = "type", rename = "s1tag")]
#[derive(Debug,Clone,Serialize,Deserialize)]
struct S1 {
    text : String
}

#[serde(tag = "type", rename = "s2tag")]
#[derive(Debug,Clone,Serialize,Deserialize)]
struct S2 {
    text : String
}

#[serde(tag = "type")]
#[derive(Debug,Clone,Serialize,Deserialize)]
enum E {
    #[serde(rename = "s1tag")]
    S1V(S1),
    #[serde(rename = "s2tag")]
    S2V(S2)
}

fn main() {

    let s1 = S1 {
        text : String::from("test str")
    };

    let s2 = S2 {
        text : String::from("test str")
    };

    let e1 = E::S1V(s1.clone());
    let e2 = E::S2V(s2.clone());

    let s1_ser = serde_json::to_string(&s1).unwrap();
    let s2_ser = serde_json::to_string(&s2).unwrap();
    let e1_ser = serde_json::to_string(&e1).unwrap();
    let e2_ser = serde_json::to_string(&e2).unwrap();

    println!("serialized = {} from {:?}", s1_ser, s1);
    println!("serialized = {} from {:?}", s2_ser, s2);
    println!("serialized = {} from {:?}", e1_ser, e1);
    println!("serialized = {} from {:?}", e2_ser, e2);

}

```
resulted in 
```
serialized = {"type":"s1tag","text":"test str"} from S1 { text: "test str" }
serialized = {"type":"s2tag","text":"test str"} from S2 { text: "test str" }
serialized = {"type":"s1tag","type":"s1tag","text":"test str"} from S1V(S1 { text: "test str" })
serialized = {"type":"s2tag","type":"s2tag","text":"test str"} from S2V(S2 { text: "test str" })
```

I've tried to find a workaround with untagged enums like:

```rust
#[serde(untagged)]
#[derive(Debug,Clone,Serialize,Deserialize)]
enum EU {
    S1V(S1),
    S2V(S2)
}
```
but it won't help because you can't decode enums properly anymore (tags on structs won't be used for enum variations).

Looks like a bug, isn't?

**Comment by agausmann** [comment]
I've never seen `tag` being used on structs, and it's not a well-documented feature. From what I can tell it just outputs a tag during serialization that doesn't get checked during deserialization. I added this to your `main` and it still runs fine, even though the tag is incorrect:

```rust
    let s1_de: S1 = serde_json::from_str(r#"{"type":"s2tag","text":"test str"}"#).unwrap();
    println!("{:?}", s1_de);
```

Putting that aside though, it's not the main focus of this issue.

> in the cases you need tags both on enums and structs, there is a duplicate type tag in JSON now

 I wouldn't expect `serde`/`serde_json` to deduplicate anything you give it. That creates unnecessary overhead that is not needed for the majority of use cases. They simply guarantee that they will produce valid JSON if the `Serialize` logic gives it data that is compatible with JSON.

In this case, you specify that you will use the key `"type"` in two different places. That's like [using the same key for different fields](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=13c404f301af4c4fd3ec0f1782924385), what is it supposed to do there? Determining that they're always compatible with each other is non-trivial. 

<hr>

Aside: Ideally, we'd catch these kinds of things at compile time for `derive`d impls, but the logic for that could get complicated, given that it has to account for things like flattening and enum representations, as you've demonstrated. Plus, there may be some use case where duplicate keys are allowed and possibly even required, so it's not reasonable to implement this kind of check globally.

**Comment by agausmann** [comment]
If you're trying to tag your `S1` and `S2` serializations, you can always wrap them in the relevant enum variant before serializing. That's the approach I would take if I were writing this.

**Comment by abdolence** [comment]
> You can always wrap them in the relevant enum variant before serializing

I know about this workaround and, well, I was exactly trying to remove those intermediate wrapping enums for these scenarios :) They exist only to encode tags for structs and don't look good for me, but it is only one option to produce correct json at the moment.

**Comment by agausmann** [comment]
Maybe you could factor that into a function? I'm using `serde_json::to_string` here, but it should work with whatever method you're using to output the JSON.

```rust
impl From<S1> for E { /* ... */ }
impl From<S2> for E { /* ... */ }

fn to_string<T>(val: T) -> Result<String, serde_json::Error>
where
    T: Into<E>, 
{
    serde_json::to_string(val.into())
}
```

**Comment by abdolence** [comment]
This could work, you're right. And it seems better than wrapping enums. I'll look into this, thanks!
