### ISSUE TITLE
DeserializeOwned of Cow/ToOwned types

### ISSUE THREAD

**Issue by elmarco** [serde-rs/serde#1789]
Hi

Is it possible to deserialize to the ownable version of a ToOwned type like a Cow?

(I would like to avoid duplicating a type hierarchy if possible, while still defaulting to borrowed version)

```rust
#[derive(Debug, Serialize, Deserialize)]
struct Person<'a> {
    #[serde(borrow)]
    name: Cow<'a, str>,
}

fn get_person<T>(data: String) -> Result<T, serde_json::error::Error>
where
    T: de::DeserializeOwned,
{
    let mut reader = BufReader::new(Cursor::new(&data));
    serde_json::from_reader(reader)
}

fn main() -> Result<(), Box<dyn Error>> {
    let data = r#"
        {
            "name": "John Doe"
        }"#;

   /// the borrowed version
    let p: Person = serde_json::from_str(data)?;
/// the owned version, doesn't work :(
    let p: Person = get_person(data.into())?

    Ok(())
}
```

thanks!

**Comment by dtolnay** [comment]
Hi @elmarco, sorry that no one was able to provide help here. If this is still an issue, you could try taking this question to any of the resources shown in https://github.com/serde-rs/serde#getting-help.

**Comment by sffc** [comment]
I asked a similar question [here](https://stackoverflow.com/questions/63201624/how-do-you-make-a-serde-struct-work-with-both-borrowed-and-owned-data).

One thing I discovered: given the following definition of DataStruct

```rust
#[derive(Deserialize, Serialize, Clone, Debug, Default, PartialEq)]
struct DataStruct<'a> {
    #[serde(borrow)]
    pub value: Cow<'a, str>,
}
```

Using `serde_json::from_reader` does not work

```rust
// error: implementation of `_::_serde::Deserialize` is not general enough
let data: DataStruct<'static> = serde_json::from_reader(DATA_JSON.as_bytes()).unwrap();
```

But using `serde_json::Deserializer::from_reader` DOES work

```rust
let deserializer = &mut serde_json::Deserializer::from_reader(DATA_JSON.as_bytes());
let data: DataStruct<'static> = DataStruct::deserialize(deserializer).unwrap()
```
