### ISSUE TITLE
Overconstrained implementation of Serialize

### ISSUE THREAD

**Issue by Kixunil** [serde-rs/serde#1793]
When deriving `Serialize`, the resulting code seems to overconstrain the implementation.

[playground example of this problem](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=81eac9e1e8b36f61c7efec00514b8dd6)

The derive macro seems to require that `T: Serialize` instead of `Foo<T>: Serialize` for some reason. This makes it impossible to write wrappers for implementing `Serialize` in terms of other trait.

**Comment by jonasbb** [comment]
The defaults of the derive are simple and always add the `Serialize` bound for each generic type. However, you can overwrite the trait bounds like `#[serde(bound = "T: MyTrait")]`.
https://serde.rs/container-attrs.html#bound

**Comment by Kixunil** [comment]
Glad to hear there's a usable workaround. Doing the right thing by default would be nicer though.

**Comment by dtolnay** [comment]
Duplicate of #370.

**Comment by dtolnay** [comment]
See https://github.com/dtolnay/syn/issues/370 -- we tried less constrained bounds in 0.7 and it turned out to be worse.

**Comment by Kixunil** [comment]
Damn, that sucks, thanks for pointers!
