### ISSUE TITLE
Is this correct behaviour from this library?

### ISSUE THREAD

**Issue by Niedzwiedzw** [serde-rs/serde#1796]
https://github.com/RReverser/serde-xml-rs/blob/bea4f9afb0c42fac8b489283ea4bdc7e1ff9cd05/src/ser/var.rs#L32 

so as you can see this panics when trying to serialize a map type... 
this test I wrote showcases it 

https://github.com/Niedzwiedzw/serde-xml-rs/blob/bfd38c52440cca274819b6f84f12d47ceb438fa3/tests/test.rs#L173

questions are:
1. is this an intended behaviour or is it a bug
2. could someone experienced with serde tell me whether this is easy to implement for someone not experienced with serde? (me :D)

**Comment by dtolnay** [comment]
Looks like you got this resolved in https://github.com/sfackler/serde-transcode/issues/9.

In the future please cross-link issues when asking the same thing in multiple places.
