### ISSUE TITLE
Implementing Ser/Deser for specific Ser/Deser-ser. Can not call type_of::<S/D>

### ISSUE THREAD

**Issue by TrionProg** [serde-rs/serde#1797]
Hello.  I need implement serialization and deserialization with specific Serializer and Deserializer(bincode). If user uses other deserializer, program wont be compiled or panic will be occured.

Where are two ways:
- Implement ser\deser with specific Serializer or Deserializer. I do not know how to do it(allows rust do it?) And how to impl for excepted serializers(This is near to negative traits)
- Get TypeId of Serializer or Deserializer, match with supported serializer/deserializer, then downcast(transmute), otherwise panic. But I can not do it: compiler says: `the parameter type S may not live long enough` but i can not mark `S:Serialzier + 'static`. But I can use `type_name::<S>()`, and it says, that S is not `SupportedSerializer`, it is `&mut SupportedSerializer`. So i need transmute it as reference.

Code:
```rust
impl Serialize for MyType{
    fn serialize<S:Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        use serde::ser::SerializeStruct;
        use std::any::TypeId;
        use std::any::Any;
        use std::any::type_name;

        //Do not works
        serializer.type_id();
        //Do not works
        TypeId::of::<S>();

        //It works
        println!("{} == {}",type_name::<S>(), type_name::<SupportedSerializer>());

        let sser:&mut SupportedSerializer= unsafe {//maybe works
            std::mem::transmute(serializer)
        };

        //Temporary: Just to compile it
        let mut s = serializer.serialize_struct("MyType", 1)?;
        s.serialize_field("content", &8usize)?;
        s.end()
    }
}
```

Have you ideas, how to solve this problems?

**Comment by dtolnay** [comment]
Hi @TrionProg, sorry that no one was able to provide help here. If this is still an issue, you could try taking this question to any of the resources shown in https://github.com/serde-rs/serde#getting-help.
