### ISSUE TITLE
[Help] Choosing a default variant for when internally tagged variant does not match

### ISSUE THREAD

**Issue by callummance** [serde-rs/serde#1798]
Is there an easy/recommended way to choose a fallback/default variant when deserializing an enum with serde?

To give some more details, I'm writing an API client, and one of the endpoints returns a list of events. I don't have a full list of event types, and the API is unstable enough that they could well add new ones in the future, so I wanted to take note of any unrecognized events but to continue parsing the rest of the events anyway.

The way I have been trying to do this is by adding an extra "unsupported type" variant to my enum, the idea being that I could output one of these whenever I get an error from parsing an event whilst also logging the event. To do this I tried writing a deserialize_with function, but the parser seems to get stuck in an infinite loop when deserializing an unrecognized event type (basic definitions as well as input which produces the issue and output at https://gist.github.com/callummance/331c49d9abde68c27c2b5c10cd01b2d7).

**Comment by agausmann** [comment]
There's been some discussion about this in issue #912 . 

You can specify a "catchall" variant by giving it the attribute `#[serde(other)]` if you're using the `derive` macros, but this is currently only implemented for unit variants (so it can't have any associated data). If you need associated data, then you'll have to implement that manually.

**Comment by dtolnay** [comment]
Closing in favor of #912.
