### ISSUE TITLE
#[serde(default)] as a variant attribute for when the tag is not present

### ISSUE THREAD

**Issue by agausmann** [serde-rs/serde#1799]
I have a scenario where I'd like to infer the variant of an enum where the tag is not present in an internally-tagged representation.

Consider this enum, which deserializes either an item type or a fluid type for an ingredient of a crafting recipe in a video game, as specified by a game or mod developer in the game data. The developer may omit the `type` member and it will be assumed to be an `Item`.

```
#[derive(Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "kebab-case")]
enum Ingredient {
    Item {
        name: String,
        amount: u16,
    }
    Fluid {
        name: String,
        amount: f64,
        #[serde(default)] 
        temperature: Option<f64>,
    }
}
```

The variants are so similar in structure, but so different in semantic meaning, that `untagged` would be inappropriate here. I can not allow a fluid type to be accidentally parsed as item, or vice versa, but because of the ambiguity of numeric types in the data format, it is possible for that to happen.

What I'd like to do is add a `#[serde(default)]` attribute to the `Item` variant, which would infer that it is an `Item` in the case where the `type` tag is not present.

This is somewhat related to #912, but there is an important difference in the expected behavior when the tag is present but not recognized. In this case, unrecognized tags should still be an error, but in #912 the feature is specifically about handling unrecognized tags.

The semantics here are more similar to the existing container/field attribute `#[serde(default)]`, which uses some default value when a field is missing from the input, which is why I propose using this as the syntax.

(Example adapted from https://wiki.factorio.com/Types/IngredientPrototype)

**Comment by agausmann** [comment]
Possible duplicate of #1410

**Comment by agausmann** [comment]
I've implemented a prototype of this feature at [`agausmann/default_variant`](https://github.com/serde-rs/serde/compare/master...agausmann:default_variant)

**Comment by agausmann** [comment]
Here's one possible alternative using a tagged enum nested within an untagged enum, though it isn't nice to manually manage for larger enums.

[(playground)](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=17755bf6b83d89b1866ad307e3074cdd)

```rust
use serde::{Serialize, Deserialize};

#[derive(Debug, Serialize, Deserialize)]
#[serde(from = "MaybeTaggedFoo")]
pub enum Foo {
    Bar {
        name: String,
    },
    Baz {
        name: String,
    },
}

#[derive(Deserialize)] 
#[serde(untagged)]
enum MaybeTaggedFoo {
    Tagged(TaggedFoo),
    Untagged {
        name: String,
    },
}

#[derive(Deserialize)] 
#[serde(tag = "type")]
enum TaggedFoo {
    Bar {
        name: String,
    },
    Baz {
        name: String,
    },
}

impl From<MaybeTaggedFoo> for Foo {
    fn from(foo: MaybeTaggedFoo) -> Foo {
        match foo {
            MaybeTaggedFoo::Tagged(TaggedFoo::Bar { name })
                | MaybeTaggedFoo::Untagged { name }
                => Foo::Bar { name },
            MaybeTaggedFoo::Tagged(TaggedFoo::Baz { name })
                => Foo::Baz { name },
        }
    }
}
```

**Comment by aldanor** [comment]
Wonder if there's no further interest in this? Hit this as well and was wondering how to best handle it...

**Comment by AndrewKvalheim** [comment]
An example found in the wild:

  - [Minecraft’s entities](https://minecraft.gamepedia.com/Chunk_format#Entity_format) are heterogeneous and tagged with an `id` field. For most types of entities, `id` contains a string, but for the player entity `id` is absent.

**Comment by agausmann** [comment]
> 
> 
> Wonder if there's no further interest in this? Hit this as well and was wondering how to best handle it...

@aldanor Judging from the activity on this repository, maintainers are more focused on fixing+maintaining, and are less interested in new features at the moment. (Also evidenced by the fact that we're still on 1.0.x, we've only had patch releases since 1.0.0). 

@aldanor @AndrewKvalheim the best solution for now is to use something like this example: https://github.com/serde-rs/serde/issues/1799#issuecomment-624978919

**Comment by dtolnay** [comment]
I'm glad you got it working &mdash; yeah I don't think this needs to be something we build into serde_derive. If it turns out to be a commonly needed thing, someone could make a separate `Deserialize` derive in a different crate to handle this representation.

**Comment by MattGson** [comment]
I would like this feature as well. Pretty much anywhere you are relying on an external API with polymorphic types, there is a chance that they will add new types. Without this, deserialising fails whenever a new (unknown) variant occurs.

**Comment by gak** [comment]
Here's another solution: https://stackoverflow.com/a/61219284

Use untagged on the enum and specify the tag within each variant struct. The default variant should be last in the enum.

**Comment by lilydjwg** [comment]
The "best solution" is too much boilerplate.

@gak I didn't figure out how to adapt that solution to my case, where variants are unnamed structs instead of tuples.

My case for a default tag variant is to create a configuration file without writing obvious things (e.g. DNS packets are sent by default over UDP, but you can choose TCP, HTTPS or TLS).

**Comment by mmun** [comment]
I also ran into this.

**Comment by joebb97** [comment]
Hey would just like to say I'd love this feature

Tagged deserialization is great, and having a default for the enum when untagged would also be great

**Comment by bruderj15** [comment]
I'd also highly endorse this.
