### ISSUE TITLE
Add automatic derivation of traits for structs that use an associated type in a HashMap (or other data structures?)

### ISSUE THREAD

**Issue by anchpop** [serde-rs/serde#1800]
(I'm using `serde = { version = "1.0", features = ["derive"] }`)

Hi,

Sorry for the bad title. I'm a complete rust newb and I didn't know how better to phrase it. I tried this today and I got bit by it:

```rust
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

pub trait CanBeSmaller {
    type Smaller;
}

impl CanBeSmaller for i64 {
    type Smaller = i32;
}

#[derive(Serialize, Deserialize)]
struct Data<T: CanBeSmaller>
{
    map: HashMap<bool, T::Smaller>,
}
```

The issue is the second to last line, `map: HashMap<bool, T::Smaller>`. If this is changed to `map: T::Smaller` it compiles no problem. If it's `map: HashMap<bool, T>`, also no problem. I assume in both of these cases it figures out what bounds it has to add on the trait definitions. But when you want to have a hashmap that uses an associated type, you get this error message:

```
error[E0277]: the trait bound `<T as CanBeSmaller>::Smaller: _IMPL_DESERIALIZE_FOR_Data::_serde::Serialize` is not satisfied
  --> src\main.rs:15:5
   |
15 |     map: HashMap<bool, T::Smaller>,
   |     ^^^ the trait `_IMPL_DESERIALIZE_FOR_Data::_serde::Serialize` is not implemented for `<T as CanBeSmaller>::Smaller`
   |
   = note: required because of the requirements on the impl of `_IMPL_DESERIALIZE_FOR_Data::_serde::Serialize` for `std::collections::HashMap<bool, <T as CanBeSmaller>::Smaller>`
   = note: required by `_IMPL_DESERIALIZE_FOR_Data::_serde::ser::SerializeStruct::serialize_field`

error[E0277]: the trait bound `<T as CanBeSmaller>::Smaller: _IMPL_DESERIALIZE_FOR_Data::_serde::Deserialize<'_>` is not satisfied
  --> src\main.rs:15:5
   |
15 |     map: HashMap<bool, T::Smaller>,
   |     ^^^ the trait `_IMPL_DESERIALIZE_FOR_Data::_serde::Deserialize<'_>` is not implemented for `<T as CanBeSmaller>::Smaller`
   |
   = note: required because of the requirements on the impl of `_IMPL_DESERIALIZE_FOR_Data::_serde::Deserialize<'_>` for `std::collections::HashMap<bool, <T as CanBeSmaller>::Smaller>`
   = note: required by `_IMPL_DESERIALIZE_FOR_Data::_serde::de::SeqAccess::next_element`

error[E0277]: the trait bound `<T as CanBeSmaller>::Smaller: _IMPL_DESERIALIZE_FOR_Data::_serde::Deserialize<'_>` is not satisfied
  --> src\main.rs:15:5
   |
15 |     map: HashMap<bool, T::Smaller>,
   |     ^^^ the trait `_IMPL_DESERIALIZE_FOR_Data::_serde::Deserialize<'_>` is not implemented for `<T as CanBeSmaller>::Smaller`
   |
   = note: required because of the requirements on the impl of `_IMPL_DESERIALIZE_FOR_Data::_serde::Deserialize<'_>` for `std::collections::HashMap<bool, <T as CanBeSmaller>::Smaller>`
   = note: required by `_IMPL_DESERIALIZE_FOR_Data::_serde::de::MapAccess::next_value`

error: aborting due to 3 previous errors
```

I have perhaps been spoiled by serde "just working" so I had a lot of difficulty parsing this error message haha.

I'm not sure why this doesn't work but the other two cases do. If there's no fix that can be done on the user's end, how much trouble would it be to add support for this? Or am I getting XY problem'd and there's actually a better way to do this that avoids this issue entirely? If neither of those are the case, would it be possible to improve this error message?

Thank you,
Andre Popovitch

**Comment by jonasbb** [comment]
The derive places a trait bound on `T`, such that `T` has to implement `Serialize`. In the struct you are never using `T`, but `T::Smaller`, which is not known to be serializable. You can add a manual trait bound for your `Data` struct:
```
#[serde(bound(serialize = "T::Smaller: Serialize", deserialize = "T::Smaller: Deserialize<'de>"))]
```

**Comment by anchpop** [comment]
Thank you! I'm just wondering why it would compile when I wrote `map: T::Smaller`. Does it automatically add the trait bound in that case?
