### ISSUE TITLE
array in remote crate

### ISSUE THREAD

**Issue by genofire** [serde-rs/serde#1802]
How to handle arrays in remote creates?

The following does not work:
```rust
#[derive(Serialize, Deserialize)]
#[serde(remote = "Process")]
struct ProcessDef {
    #[serde(with = "[DurationDef; 2]")]
    durations: [Duration; 2],
}
```
Full Playground:
[example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=703ccec2b57cef1892d85e11b2fe14ab)

**Comment by dtolnay** [comment]
Hi @genofire, sorry that no one was able to provide help here. If this is still an issue, you could try taking this question to any of the resources shown in https://github.com/serde-rs/serde#getting-help.
