### ISSUE TITLE
serde::private::de::Content is overly strict about matching data to hints.

### ISSUE THREAD

**Issue by agausmann** [serde-rs/serde#1803]
The `Content` enum, used by some derived implementations of `Deserialize` to temporarily store partially-deserialized values, explicitly checks whether the hint provided by the `Deserialize` impl corresponds to the value contained by the `Content`. Usually, this shouldn't cause problems, but in my case it caused unexpected behavior that was hard to diagnose.

My use case: I am working with a data format where [maps and sequences are ambiguous](https://www.lua.org/pil/11.1.html) (Lua values, using the `rlua_serde` crate). There are some places in my code that use `untagged` enums which then internally use `deserialize_any`. In those cases, `rlua_serde` faithfully provides me with maps, but I know that one of the variants actually needs a sequence. So, I create a `map_to_seq` utility deserializer that adapts any `MapAccess` it gets from `rlua_serde` into a `SeqAccess`, and otherwise is completely transparent, forwarding/delegating everything else. For example, this would (theoretically) successfully deserialize both `{r=1, g=0, b=0, a=1}` and `{1, 0, 0, 1}` (sequential numeric keys inferred by the interpreter in the second example):

```rust
#[derive(Deserialize)]
#[serde(untagged)]
enum Color {
    Map {
        r: f32,
        g: f32,
        b: f32,
        a: f32,
    },
    #[serde(deserialize_with = "map_to_seq")]
    // According to the docs of `deserialize_with` for variants, 
    // the type parameter T becomes `(f32, f32, f32, f32)` - the tuple of fields.
    // Since it's structurally the same, no additional conversion is required.
    Seq(f32, f32, f32, f32),
}

fn map_to_seq<'de, T, D>(de: D) -> Result<T, D::Error>
where
    T: Deserialize<'de>,
    D: Deserializer<'de>,
{
    unimplemented!() /* snip */
}
```

Unfortunately, this fails. Because I transparently pass along _every call_ except `visit_map`, when the `Seq` variant attempts to deserialize, it calls `deserialize_tuple`, which is received by the `Content` object, and is checked against the data it owns. Since [`Content` uses `deserialize_any`](https://github.com/serde-rs/serde/blob/099fa25b86524f07d86852ea2de071e8dd2a653f/serde/src/private/de.rs#L309), it [gets a map from `rlua_serde`](https://github.com/zrkn/rlua_serde/blob/bcb30832521366285e534b5a52e36b9b8669184b/src/de.rs#L26), which then [causes an `invalid_type` error](https://github.com/serde-rs/serde/blob/099fa25b86524f07d86852ea2de071e8dd2a653f/serde/src/private/de.rs#L1326) when `deserialize_seq` is called.

I've found a workaround, which is to always send `deserialize_map` to coax the `Content` into giving me its data, but I'm arguing I shouldn't have to do that. Even though it results in correct behavior, it feels wrong to do and prone to breaking in the future.

According to the docs for [implementing `Deserializer`](https://serde.rs/impl-deserializer.html), "For self-describing formats like JSON, it is fine for the Deserializer to ignore this hint and just call whichever Visitor method corresponds to the content of the input data". It is not necessary and it does not seem useful for `Content` to make sure the data type matches the hint. It would be perfectly legal for `Content::deserialize_*` to call the `visit_*` function corresponding to its data regardless of the given hint, and let the `Visitor` perform its own type checking.

**Comment by dtolnay** [comment]
The Deserializer impls for Content are written this way to keep binary size and compile time under control. Ignoring the type info in the Deserializers would result in vastly more Visitor methods needing to be instantiated.

**Comment by agausmann** [comment]
Thanks for explaining it, I never would have thought of that.

**Comment by agausmann** [comment]
Update on my situation: Instead of `map_to_seq` delegating everything to the corresponding `deserialize_*` and `visit_*` functions, pretty much everything forwards to `deserialize_map`, and the visitor will expect and only explicitly handle `visit_map`. Notable exceptions to this include optionals, which I included to support applying `map_to_seq` to `Option<T>` types where T is a sequence type.

This has really shortened my code, since I don't have to explicitly implement every single deserializer/visitor function, and I expect it might also decrease code size like what you were saying earlier. Thanks again for the insight.

Here is the complete code for `map_to_seq`, if anyone is interested:

```rust
fn map_to_seq<'de, T, D>(de: D) -> Result<T, D::Error>
where
    T: Deserialize<'de>,
    D: Deserializer<'de>,
{
    struct MyDeserializer<D> {
        de: D,
    }

    impl<'de, D> Deserializer<'de> for MyDeserializer<D>
    where
        D: Deserializer<'de>,
    {
        type Error = D::Error;

        fn deserialize_any<V>(self, visitor: V) -> Result<V::Value, Self::Error>
        where
            V: de::Visitor<'de>,
        {
            self.de.deserialize_map(MyVisitor { visitor })
        }

        fn deserialize_option<V>(self, visitor: V) -> Result<V::Value, Self::Error>
        where
            V: de::Visitor<'de>,
        {
            self.de.deserialize_option(MyVisitor { visitor })
        }

        forward_to_deserialize_any! {
            bool i8 i16 i32 i64 i128 u8 u16 u32 u64 u128 f32 f64 char str string
            bytes byte_buf unit unit_struct newtype_struct seq tuple
            tuple_struct map struct enum identifier ignored_any
        }
    }

    struct MyVisitor<V> {
        visitor: V,
    }

    impl<'de, V> de::Visitor<'de> for MyVisitor<V>
    where
        V: de::Visitor<'de>,
    {
        type Value = V::Value;

        fn expecting(&self, f: &mut fmt::Formatter) -> fmt::Result {
            write!(f, "a map with integer keys")
        }

        fn visit_map<A>(self, map: A) -> Result<Self::Value, A::Error>
        where
            A: de::MapAccess<'de>,
        {
            self.visitor.visit_seq(MySeqAccess {
                map,
                idx: 0,
                temp_storage: Vec::new(),
            })
        }

        fn visit_none<E>(self) -> Result<Self::Value, E>
        where
            E: de::Error,
        {
            self.visitor.visit_none()
        }

        fn visit_some<D>(self, de: D) -> Result<Self::Value, D::Error>
        where
            D: Deserializer<'de>,
        {
            self.visitor.visit_some(MyDeserializer { de })
        }
    }

    struct MySeqAccess<A> {
        map: A,
        idx: usize,
        temp_storage: Vec<Option<serde_value::Value>>,
    }

    impl<'de, A> de::SeqAccess<'de> for MySeqAccess<A>
    where
        A: de::MapAccess<'de>,
    {
        type Error = A::Error;

        fn next_element_seed<T>(&mut self, seed: T) -> Result<Option<T::Value>, Self::Error>
        where
            T: de::DeserializeSeed<'de>,
        {
            self.idx += 1;
            loop {
                if let Some(value) = self.temp_storage.get_mut(self.idx).and_then(Option::take) {
                    return seed
                        .deserialize(value)
                        .map(Some)
                        .map_err(Self::Error::custom);
                } else {
                    match self.map.next_entry::<usize, _>()? {
                        Some((k, v)) => {
                            if self.temp_storage.len() < k + 1 {
                                self.temp_storage.resize(k + 1, None);
                            }
                            self.temp_storage[k] = Some(v);
                        }
                        None => return Ok(None),
                    }
                }
            }
        }
    }

    T::deserialize(MyDeserializer { de })
}
```
