### ISSUE TITLE
derive(Deserialize) panics with index out of bounds for `#[serde(skip)]`

### ISSUE THREAD

**Issue by matklad** [serde-rs/serde#1804]
Observed in this commit

https://github.com/matklad/cargo_metadata/commit/0b1c8d85c860fe9fb3488fea5990d659780065fc

```
   Compiling cargo_metadata v0.9.1 (/home/matklad/projects/cargo_metadata)
error: proc-macro derive panicked
  --> src/messages.rs:99:35
   |
99 | #[derive(Debug, Clone, Serialize, Deserialize)]
   |                                   ^^^^^^^^^^^
   |
   = help: message: index out of bounds: the len is 5 but the index is 5

error: aborting due to previous error

error: could not compile `cargo_metadata`.
```

I think I am doing something very stupid with this skip, which is a bug in my code, *but* I think serde still should not panic, but rather explain me that I am holding it wrong? 

serde_derive version = "1.0.106"

**Comment by dtolnay** [comment]
This was a bug; what you are doing should work. Fixed in 1.0.107.
