### ISSUE TITLE
Is there any way to deserialize to `Box<dyn Any>`?

### ISSUE THREAD

**Issue by KizzyCode** [serde-rs/serde#1806]
Is there any way to deserialize a self-describing format to `Box<dyn Any>`?

This would be useful if I have an unspecialized struct like
```rust
#[derive(Serialize, Deserialize)]
struct Entry {
    r#type: String,
    payload: Box<dyn Any>
}
```
where the payload can be anything depending on the `r#type`.

**Comment by dtolnay** [comment]
Maybe something like this:

```rust
use serde::{Deserialize, Deserializer};
use serde_json::Value;
use std::any::Any;

#[derive(Deserialize, Debug)]
pub struct Entry {
    pub r#type: String,
    #[serde(deserialize_with = "any_value")]
    pub payload: Box<dyn Any>,
}

fn any_value<'de, D>(deserializer: D) -> Result<Box<dyn Any>, D::Error>
where
    D: Deserializer<'de>,
{
    let value = Value::deserialize(deserializer)?;
    Ok(Box::new(value))
}

fn main() {
    let j = r#"
    {"type": "array", "payload": []}
    "#;

    println!("{:#?}", serde_json::from_str::<Entry>(j).unwrap());
}
```

Also take a look at https://github.com/dtolnay/typetag which is possibly more appropriate for your use case than `dyn Any`.

**Comment by KizzyCode** [comment]
Oh, apparently I didn't phrase my question very well – I was wondering how I could extend my own Serializer/Deserializer to allow the work with type-erased objects. However I found a way using a custom visitor and `erased-serde`: https://github.com/KizzyCode/serde_asn1_der-rust/blob/master/src/any.rs

Ty 😊
