### ISSUE TITLE
What is the most efficient way to handle a parent structure with some differing children

### ISSUE THREAD

**Issue by jeffka11** [serde-rs/serde#1810]
I'm making an API for an application [ttrss_api](https://github.com/jeffka11/ttrss_api) that essentially takes JSON like this:

```
    { "seq": 0,
    "status":0,
    content: { ...}
}
```

where content is very different depending on the API call. The code is in the link above, but in short, the code does this:

```
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct Response {
    pub seq: Option<u8>,
    pub status: u8,
    pub content: Content,
}

#[derive(Serialize, Deserialize, Debug, Clone, Eq, PartialEq, Display)]
#[serde(untagged)]
pub enum Content {
  Login(Login),
  GetApiLevel(ApiLevel),
  ....
}

#[derive(Serialize, Deserialize, Debug, Clone, Eq, PartialEq)]
pub struct Login {
    pub session_id: String,
    pub api_level: u8
}

#[derive(Serialize, Deserialize, Debug, Clone, Eq, PartialEq)]
pub struct ApiLevel {
    pub level: u8,
}

```

and the user does this:
```
fn main() {
    let apilevel: Option<ApiLevel> = match get_api_level().expect("Failed to get response").content {
        Content::GetApiLevel(x) => { Some(x) },
        _ => None,
    };
    println!("api level {:?}", apilevel.unwrap());
}
```

The user experience seems a bit tedious, but I'm overall somewhat new to Rust so maybe that's just me. For both the code organization and user actions, is there something better I should do? I'm mostly worried about making the user `match` after unwrapping the result from get_api_level().

**Comment by dtolnay** [comment]
Hi @jeffka11, sorry that no one was able to provide help here. If this is still an issue, you could try taking this question to any of the resources shown in https://github.com/serde-rs/serde#getting-help.
