### ISSUE TITLE
Prefixing flattened structs

### ISSUE THREAD

**Issue by elpiel** [serde-rs/serde#1812]
Hello,
I would like to suggest to add a way to prefix fields, especially when used with `flatten`. Our case being that we don't want to rename the fields of a struct, but be able to use it inside another struct with `flatten`. 
This also has the benefit of still being able to use that struct on it's own separate from it's usage with `flatten`.

```rust
pub struct Input {
    #[serde(default, flatten, prefix = "ad_view.")] // this doesn't look good, but it shows my point
    ad_view: Option<AdViewInput>,
}

pub struct AdViewInput {
    seconds_since_show: u64,
    has_custom_preferences: bool,
}
```

I just thought that this can also enable you to use it with `serde_json` like:
```json
{ "ad_view.seconds_since_show": 50 }
```

PS: Amazing crate, I love it and I hope you continue the great work that's going on here :heart:

**Comment by jonasbb** [comment]
If you don't mind using another crate for this, take a look at [`serde_with::with_prefix`](https://docs.rs/serde_with/1.4.0/serde_with/macro.with_prefix.html), which covers exactly this option.

**Comment by elpiel** [comment]
Thanks for the information. I've missed this one 😅
