### ISSUE TITLE
"Getting help" page is outdated

### ISSUE THREAD

**Issue by jmafc** [serde-rs/serde#1815]
The page says "Serde developers live in the #serde channel on irc.mozilla.org" but if you click on the latter link, it says the following: "Note that on 2nd March 2020, Mozilla moved away from IRC to Matrix for its public channels, the IRC server was be shut down."

**Comment by dtolnay** [comment]
Thanks, fixed in https://github.com/serde-rs/serde-rs.github.io/commit/92e7b66f015696d5c2a50e6e2c9533b8067242e7 to match the help section in this repo's readme.
