### ISSUE TITLE
`rustc-serialize` vs. serde

### ISSUE THREAD

**Issue by nabilmerk** [serde-rs/serde#1816]
Hi,

I've been looking at [Rust](https://github.com/rust-lang/rust) repository and found out that Rust make use of [`rustc-serialize`](https://crates.io/crates/rustc-serialize) which has been deprecated in favor of `serde` crate.

I've opened a discussion in [Rust Programming Language Internals Forum](https://internals.rust-lang.org/t/libserialize-replacement/12380) to evaluate the possibility to replace the `rustc-serialize` to `serde` in the Rust repository.

You might have already investigated this possibility and I think your feedback will be more than welcome regarding this topic.

**Comment by dtolnay** [comment]
This is tracked in https://github.com/rust-lang/rust/issues/40177.

**Comment by nabilmerk** [comment]
Many thanks for the link.
