### ISSUE TITLE
Duplicate field in base struct and flattened struct

### ISSUE THREAD

**Issue by RCasatta** [serde-rs/serde#1820]
In my codebase I have a situation like this:

```
pub struct Base {
    #[serde(flatten)]
    pub flattened: Option<Flattened>,
    pub name: String,
}

pub struct Flattened {
    pub name: String,
}
```

I didn't realize I had the field `name` repeated  in the `Base` and in the `Flattened` struct and I wasn't explaining the value of the field in the serialized json since I was setting the one in the `Flattened` struct but it was serialized the value in the `Base` struct. 

I think it would be super cool a warning from the compiler if name collisions like this one are found.

**Comment by dtolnay** [comment]
I'll close this because I don't think the information for diagnosing this is available to proc macros. You could report this suggestion as a lint to https://github.com/rust-lang/rust-clippy which operates with more type information and has serde-specific checks already.

**Comment by BatmanAoD** [comment]
It would be good to have the behavior documented on the page about flattening. From trying it out, it looks like it's effectively treated as though the inner, flattened field is simply left out of serialization or deserialization, resulting in an error if it's a non-optional field.
