### ISSUE TITLE
im::HashMap does not implement Deserialize

### ISSUE THREAD

**Issue by Gastove** [serde-rs/serde#1823]
I'd like to use an [im.rs HashMap](https://docs.rs/im/15.0.0/im/struct.HashMap) as a struct field; I need to deserialize it, which should be fine (`im::HashMap` [implements `Deserialize`](https://docs.rs/im/15.0.0/im/struct.HashMap.html#impl-Deserialize%3C%27de%3E)). I have a tuple struct, `FieldName(String)`, and an enum, `FieldType`, wrapped in a struct called `Spec`; something like:

```rust
#[derive(Clone, Debug, Deserialize, Eq, Hash, PartialEq)]
pub struct FieldName(pub String);

#[derive(Debug, Clone, Deserialize)]
pub enum FieldType {
    String { length: usize },
    Integer,
    Boolean,
    Float,
}

#[derive(Debug, Clone, Deserialize)]
struct Spec {
    fields: HashMap<FieldName, FieldType>,
}
```
I've verified that each type implements all the needed traits -- `Clone`, `Hash`, `Eq` for the key, `Clone` for the value. However, on build, I get this:
```
the trait `engine::_IMPL_DESERIALIZE_FOR_FieldName::_serde::Deserialize<'_>` is not implemented for `im::hash::map::HashMap<engine::FieldName, engine::FieldType>`
    |
    = note: required by `engine::_IMPL_DESERIALIZE_FOR_FieldName::_serde::de::SeqAccess::next_element`

// and

the trait `engine::_IMPL_DESERIALIZE_FOR_FieldName::_serde::Deserialize<'_>` is not implemented for `im::hash::map::HashMap<engine::FieldName, engine::FieldType>`
    |
    = note: required by `engine::_IMPL_DESERIALIZE_FOR_FieldName::_serde::de::MapAccess::next_value`
```
This same code compiles perfectly if I swap my use from `im::HashMap` to `std::collections::HashMap`. It seems like I must be doing something odd, but I can't for the life of me figure out what. Would deeply appreciate any guidance!

Thanks for the remarkable library!

**Comment by dtolnay** [comment]
Please see https://docs.rs/im/15.0.0/im/#feature-flags, I don't think they provide Serde impls by default.

**Comment by Gastove** [comment]
Holy guacamoly, how did I miss that. Thank you so much, that did it!
