### ISSUE TITLE
Deserializing external key into a struct's field

### ISSUE THREAD

**Issue by takagiy** [serde-rs/serde#1829]
Assume that we have following data file and want to deserialize it into rusty data structure.

```toml
[example1]
number = 1
string = "spam"

[example2]
number = 2
string = "egg"
```

Thanks to serde, following definition can do that. But I wonder if I can put the keys such as `"example1"` and `"example2"` to the structs' fields of entries like the second code. What do you think about it?

```rust
#[derive(Deserialize)]
struct Entry {
    number: i32,
    string: String,
}

#[derive(Deserialize)]
struct Config {
    #[serde(flatten)]
    entries: HashMap<String, Entry>,
}
```

```rust
#[derive(Deserialize)]
struct Entry {
    // how can i tell to serde to bring this field from the external key?
    name: String,

    number: i32,
    string: String,
}

#[derive(Deserialize)]
struct Config {
    #[serde(flatten)]
    entries: Vec<Entry>,
}
```

**Comment by dtolnay** [comment]
Hi @takagiy, sorry that no one was able to provide help here. If this is still an issue, you could try taking this question to any of the resources shown in https://github.com/serde-rs/serde#getting-help.
