### ISSUE TITLE
Cannot Skip Fn Field

### ISSUE THREAD

**Issue by erayerdin** [serde-rs/serde#1832]
I have a boxed `Fn` in a struct and I naturally would like to skip it (since there's no way to deserialize/serialize a function).

What I have:

```rust
type InvokerFn = Box<dyn Fn(&str) -> InvocationResult>;

#[derive(Serialize, Deserialize)]
struct Code<'a> {
    name: &'a str,
    description: String,
    #[serde(skip)]
    invoker: InvokerFn,
}
```

It fails saying:

```
the trait bound `dyn for<'r> std::ops::Fn(&'r str) -> std::result::Result<std::string::String, code::CodeError<'r>>: std::default::Default` is not satisfied

the trait `std::default::Default` is not implemented for `dyn for<'r> std::ops::Fn(&'r str) -> std::result::Result<std::string::String, code::CodeError<'r>>`

note: required because of the requirements on the impl of `std::default::Default` for `std::boxed::Box<dyn for<'r> std::ops::Fn(&'r str) -> std::result::Result<std::string::String, code::CodeError<'r>>>`
note: required by `std::default::Default::default`rustc(E0277)
code.rs(39, 5): the trait `std::default::Default` is not implemented for `dyn for<'r> std::ops::Fn(&'r str) -> std::result::Result<std::string::String, code::CodeError<'r>>`
```

How do I skip a boxed `Fn` field?

***

# Environment

 - Rust 1.43.1
 - serde 1.0.111

**Comment by dtolnay** [comment]
What value should go in `invoker` when (not) deserializing it?

**Comment by erayerdin** [comment]
@dtolnay 

Now that I think about it with a clear mind (it was midnight where I was when I had written that code and opened this issue), it's natural for serde to fail, or rather this is how Rust works. This `Fn` is not wrapped with an `Option` at all. What was I thinking?

Sorry for bothering. I think the issue better be closed.
