### ISSUE TITLE
Add `#[serde(ref_into = "RefIntoType")]` where `&T: Into<RefIntoType>, RefIntoType: Serialize`

### ISSUE THREAD

**Issue by timotree3** [serde-rs/serde#1833]
I suggest adding a container-level attribute `ref_into`. With this feature, the following two examples would be equivalent:
```rust
// Example one

pub struct Foo;

impl Serialize for Foo {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error> where S: Serializer {
        let val: RefIntoType = self.into();
        val.serialize(serializer)
    }
}
```
```rust
// Example two

#[derive(Serialize)]
#[serde(ref_into = "RefIntoType")]
pub struct Foo;
```
This feature would be applicable whenever `&Foo` implements `Into<RefIntoType>` and `RefIntoType` implements `Serialize`.

There's already a very similar shortcut [`#[serde(into = "IntoType")]`](https://serde.rs/container-attrs.html#into) but it clones the value before converting and therefore would be wasteful in cases like this where conversion only requires a reference.

As always, the exact chosen name `ref_into` is subject to bikeshedding.

**Comment by Mingun** [comment]
This should be easy to implement, need just introduce and use special `RefInto` trait: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ace054282891ad2e26a184f6487dc88a

**Comment by JakobDegen** [comment]
I also have a use case for this, but I don't think restricting it to `&T: Into` or such makes sense. Just having `into_with = "path"` where `path` is some `fn(&Self) -> T` where `T: Serialize` seems like a more general solution.

**Comment by dtolnay** [comment]
I think I would prefer to leave this use case to handwritten Serialize impls, instead of introducing new dedicated `ref_into` or `into_with` attributes.

As you showed above, these tiny Serialize impls are trivial to handwrite.
