### ISSUE TITLE
Option of NonZeroXX

### ISSUE THREAD

**Issue by r4v3n6101** [serde-rs/serde#1834]
Assuming we have such type:
```rust
#[derive(Deserialize)]
struct Smth(Option<NonZeroU8>);
```
Attempt of parsing `1` from `serde_json` returns `Some(1)`. But `0` returns `Err(expected a non-zero value)`. However, I expected `None`.

Using `bincode` deserializing of `0` returns `None` which is ok, but other nums give `UnexpectedEof`.

So, it seems that serde can't differ `Option<T>` from `Option<NonZeroXX>`.

**Comment by dtolnay** [comment]
This is the intended behavior. Option\<T\> in JSON means null or T, so Option\<NonZeroU8\> is null or a nonzero integer. 0 is neither null nor a nonzero integer.
