### ISSUE TITLE
Unexpected "lowercase" behavior for structs

### ISSUE THREAD

**Issue by LazyMechanic** [serde-rs/serde#1835]
Hello, I need to rename all struct fields to lowercase due to the [tiled API](https://doc.mapeditor.org/en/stable/reference/json-map-format/), but the attribute `rename_all = "lowercase"` did nothing.
Is there any reason why `rename_all = "lowercase"` is not defined for struct fields [(src)](https://github.com/serde-rs/serde/blob/95b1a5d3d9838aaf5d554658bce38385c05011ee/serde_derive/src/internals/case.rs#L67)?

#### Code:
```rust
use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub struct Map {
    snake_case: String,
    lowercase:  i32,
}

fn main() {
    let text = r#"
    {
        "snakecase": "A",
        "lowercase": 1
    }
    "#;

    let res = serde_json::from_str::<Map>(text);
    println!("{:?}", res);
}

```

#### Actual output:
```bash
Err(Error("missing field `snake_case`", line: 5, column: 5))
```

#### Expected output:
```bash
Ok(Map { snake_case: "A", lowercase: 1 })
```

**Comment by dtolnay** [comment]
This is the intended behavior. Lowercase turns capital letters into lowercase; and in general the renames assume idiomatic capitalization of field and variant names, and field names idiomatically do not contain capital letters.

```rust
#[derive(Serialize)]
#[serde(rename_all = "lowercase")]
enum E {
    One,  // "one"
    Two,  // "two"
    Error,  // "error"
}
```

For converting `a_a` to `aa` you would need to use `#[serde(rename = "aa")]` on the individual field.

**Comment by Rexagon** [comment]
The problem is that for api where this strange naming style is actively used, you will need to place this attribute on almost everything.

Maybe it's worth adding a new `rename_all` variant (e.g. `flatcase`)?

**Comment by dtolnay** [comment]
I am not interested in building this into Serde, but it would be reasonable to implement as a separate attribute macro which inserts the right `rename` attributes.

**Comment by alexschrod** [comment]
> it would be reasonable to implement as a separate attribute macro which inserts the right `rename` attributes.

I decided to make a go at this, but I'm running into a problem where my attributes are seemingly being ignored by serde.

If I try to put my macro before the derive macro, i.e.
```rust
#[serde_power_rename_all(concatenatedlowercase)]
#[derive(Debug, serde_derive::Deserialize)]
pub struct Qux { ... }
```
I get this error:
```
error: cannot find attribute `serde` in this scope
 --> tests\rename_all.rs:3:1
  |
3 | #[serde_power_rename_all(concatenatedlowercase)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `serde` is in scope, but it is a crate, not an attribute
  = note: this error originates in the attribute macro `serde_power_rename_all` (in Nightly builds, run with -Z macro-backtrace for more info)
```

If I put it in the opposite order, i.e.
```rust
#[derive(Debug, serde_derive::Deserialize)]
#[serde_power_rename_all(concatenatedlowercase)]
pub struct Qux {
    foo: String,
    bar: i32,
    foo_bar: f32,
    bar_baz: (),
}
```
I don't get an error at the compilation stage, but the attributes I've added seem to have no effect. Here's the output as determined by `cargo expand`:
```rust
pub struct Qux {
    #[serde(rename = "FOO")]
    foo: String,
    #[serde(rename = "BAR")]
    bar: i32,
    #[serde(rename = "FOO_BAR")]
    foo_bar: f32,
    #[serde(rename = "BAR_BAZ")]
    bar_baz: (),
}
```
but it behaves as through they're not there:
```
thread 'test' panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `foo`", line: 7, column: 5)', tests\rename_all.rs:22:45
```
Commenting out the original struct and putting the expanded struct in its place makes the deserialization work as expected/intended.

I can only really conclude that having a third party macro add these serde rename attributes isn't actually an available option, unless someone can tell me what I might be doing wrong and how to rectify the problem I'm running into.
