### ISSUE TITLE
Deserialize value of AccessMap using custom deserializer

### ISSUE THREAD

**Issue by seriousbusinessuser** [serde-rs/serde#1838]
Hi!

I have a custom deserializer for a struct similar to the one from https://serde.rs/deserialize-struct.html, and I'd like to deserialize `Duration` from JSON where `secs` are either `u64` or `{ n: u64 } `. When I use `secs = Some(map.next_value()?);` it fails when it encounters `{ n: u64 }` case.

I've read this article https://serde.rs/string-or-struct.html but I don't know how to apply it outside of `#[serde(deserialize_with = "string_or_struct")`.

Could you please explain how can I use custom deserializer with `AccessMap` value within custom struct deserializer?

**Comment by dtolnay** [comment]
Hi @seriousbusinessuser, sorry that no one was able to provide help here. If this is still an issue, you could try taking this question to any of the resources shown in https://github.com/serde-rs/serde#getting-help.
