### ISSUE TITLE
Document difference, if any, between visit_str and visit_string

### ISSUE THREAD

**Issue by cmbrandenburg** [serde-rs/serde#184]
If I'm implementing my own `serde::de::Visitor` for a string type, do I need to implement `visit_str`, `visit_string`, or both? The documentation should make this clear

**Comment by erickt** [comment]
Yeah, it should be in the docs. `visit_str` is a performance optimization. It enables deserializers that are reusing an internal buffer for strings like [serde_json](https://github.com/serde-rs/json/blob/master/json/src/de.rs#L19) to pass a `&str` slice to that string to the [visitor](https://github.com/serde-rs/json/blob/master/json/src/de.rs#L153) without forcing a copy. This then can be used by implementations, like [integers and floats](https://github.com/serde-rs/serde/blob/master/serde/src/de/impls.rs#L154) to deserialize from the `&str`.

So as you can see, it's not strictly necessary, but it does help to eliminate some unneeded work.

**Comment by erickt** [comment]
This has landed!
