### ISSUE TITLE
Serializing ahead of time

### ISSUE THREAD

**Issue by jonhoo** [serde-rs/serde#1843]
I recently ran into an interesting challenge in trying to get rid of [this hot function](https://github.com/mit-pdos/noria/blob/c9e0efe346f6bf2c2477ae9481b878bde99212d4/server/src/worker/readers.rs#L138-L163) in Noria. The issue, plainly stated, is that I have data that can only be borrowed for a very short time, that needs to be sent over the wire at some later point in time.

My current approach is to clone all the data when I borrow it, and then serialize the full owned structure when the later time comes (essentially, when all the operations in a batch have completed). But, perhaps unsurprisingly, this is unfortunate, as it leads to a lot of unnecessary allocation and `memcpy`'ing.

What I _really_ want to do is to serialize each "segment" of the final response when I have a borrow of it, and then at the end, when I serialize the message to be sent over the wire, just splice in those "pre-serialized" bits as appropriate. And of course, ideally, the receiver should be entirely oblivious to this, and should be able to serialize the owned type as they do today.

Unfortunately, this is turning out fairly complicated (for good reasons). The outline of my current (incomplete) approach is:
```rust
use serde::ser::{Serialize, SerializeSeq, Serializer};
struct SerializedReadReplyBatches(Vec<Vec<u8>>);
impl Serialize for SerializedReadReplyBatches {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        // we're trying to mimick  Vec<Vec<Vec<DataType>>>
        //   when what we have is  Vec<Vec<u8>>
        // where the Vec<u8> is a pre-serialized Vec<Vec<DataType>>
        let seq = serializer.serialize_seq(Some(self.0.len()))?;
        for batch in self.0 {
            // XXX XXX XXX what goes here?
        }
        seq.end()
    }
}
```
When I got to the highlighted line, I realized that serde does not have a way for me to "inject" an already serialized stream into the output. This is (I think) for a good reason: you have no guarantee that the current serializer (`T`) is the same one that produced the bytestring you'd be splicing in. Or that the format even supports such splicing in the first place (one that does compression might not for example).

Which, then, finally brings me to my question: _assuming_ my serializer supports splicing (I think the `bincode` format does), and _assuming_ that I have manually made absolutely sure I only ever serialize a `SerializedReadReplyBatches` with `bincode`, is there a way for me to do this? Even if it is through some completely different design.

I'll add that, due to the larger architecture I'm working within, it would be very difficult to get a handle to the `Write` that ultimately gets written to, which obviously (and unfortunately) limits the space of possible solutions.

**Comment by dtolnay** [comment]
Maybe like this?

```rust
// [dependencies]
// bincode = "1.2"
// serde = "1.0"
// serde_bytes = "0.11"

use serde::de::{self, Deserialize, DeserializeSeed, Deserializer, SeqAccess, Visitor};
use serde::ser::{Serialize, SerializeSeq, Serializer};
use std::fmt;
use std::net::{IpAddr, Ipv4Addr, Ipv6Addr};

type Obj = IpAddr; // or Vec<Vec<DataType>>

struct SerializedReadReplyBatches(Vec<Vec<u8>>);

impl Serialize for SerializedReadReplyBatches {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        let mut seq = serializer.serialize_seq(Some(self.0.len()))?;
        for batch in &self.0 {
            seq.serialize_element(serde_bytes::Bytes::new(batch))?;
        }
        seq.end()
    }
}

#[derive(Debug)]
struct Received {
    vec: Vec<Obj>,
}

impl<'de> Deserialize<'de> for Received {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        struct Elem;
        struct Batch;

        impl<'de> Visitor<'de> for Elem {
            type Value = Obj;

            fn expecting(&self, f: &mut fmt::Formatter) -> fmt::Result {
                f.write_str("encoded Obj")
            }

            fn visit_bytes<E>(self, bytes: &[u8]) -> Result<Self::Value, E>
            where
                E: de::Error,
            {
                bincode::deserialize(bytes).map_err(de::Error::custom)
            }
        }

        impl<'de> DeserializeSeed<'de> for Elem {
            type Value = Obj;

            fn deserialize<D>(self, deserializer: D) -> Result<Self::Value, D::Error>
            where
                D: Deserializer<'de>,
            {
                deserializer.deserialize_bytes(self)
            }
        }

        impl<'de> Visitor<'de> for Batch {
            type Value = Received;

            fn expecting(&self, f: &mut fmt::Formatter) -> fmt::Result {
                f.write_str("batch of encoded Obj")
            }

            fn visit_seq<A>(self, mut seq: A) -> Result<Self::Value, A::Error>
            where
                A: SeqAccess<'de>,
            {
                let mut vec = Vec::new();
                while let Some(elem) = seq.next_element_seed(Elem)? {
                    vec.push(elem);
                }
                Ok(Received { vec })
            }
        }

        deserializer.deserialize_seq(Batch)
    }
}

fn main() -> bincode::Result<()> {
    let objs: Vec<Obj> = vec![
        IpAddr::V4(Ipv4Addr::LOCALHOST),
        IpAddr::V6(Ipv6Addr::LOCALHOST),
    ];

    let batches = SerializedReadReplyBatches(
        objs.iter()
            .map(|obj| bincode::serialize(obj))
            .collect::<Result<_, _>>()?,
    );

    let transmission = bincode::serialize(&batches)?;

    let received: Received = bincode::deserialize(&transmission)?;
    println!("{:#?}", received);

    Ok(())
}
```

**Comment by dtolnay** [comment]
Alternatively if the outer encoding is known to be bincode then you can hax and receive it as this:

```rust
// [dependencies]
// bincode = "1.2"
// serde = "1.0"
// serde_bytes = "0.11"

use serde::ser::{Serialize, SerializeSeq, Serializer};
use std::net::{IpAddr, Ipv4Addr, Ipv6Addr};

type Obj = IpAddr; // or Vec<Vec<DataType>>

struct SerializedReadReplyBatches(Vec<Vec<u8>>);

impl Serialize for SerializedReadReplyBatches {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        let mut seq = serializer.serialize_seq(Some(self.0.len()))?;
        for batch in &self.0 {
            seq.serialize_element(serde_bytes::Bytes::new(batch))?;
        }
        seq.end()
    }
}

fn main() -> bincode::Result<()> {
    let objs: Vec<Obj> = vec![
        IpAddr::V4(Ipv4Addr::LOCALHOST),
        IpAddr::V6(Ipv6Addr::LOCALHOST),
    ];

    let batches = SerializedReadReplyBatches(
        objs.iter()
            .map(|obj| bincode::serialize(obj))
            .collect::<Result<_, _>>()?,
    );

    let transmission = bincode::serialize(&batches)?;

    let received: Vec<(u64, Obj)> = bincode::deserialize(&transmission)?;
    println!("{:#?}", received);

    Ok(())
}
```

**Comment by jonhoo** [comment]
That's very helpful, thank you! I was hoping to find a way to keep the bytes going over the wire the same so that only the sending side would need to know about this hack, but it seems like that might sadly be tricky to achieve. And I don't think serde can even safely support this kind of "splicing" in a generic way, since not all protocols would be able to support it.

**Comment by dtolnay** [comment]
Usually you would do that by writing multiple times to the `Write`, which you said is hard. But for bincode this keeps the bytes on wire the same:

```rust
use serde::ser::{Serialize, SerializeTuple, Serializer};
use std::net::{IpAddr, Ipv4Addr, Ipv6Addr};

type Obj = IpAddr; // or Vec<Vec<DataType>>

struct SerializedReadReplyBatches(Vec<Vec<u8>>);

impl Serialize for SerializedReadReplyBatches {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        struct Bytes<'a>(&'a [u8]);
        impl Serialize for Bytes<'_> {
            fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
            where
                S: Serializer,
            {
                let mut bytes = serializer.serialize_tuple(self.0.len())?;
                for b in self.0 {
                    bytes.serialize_element(b)?;
                }
                bytes.end()
            }
        }

        serializer.collect_seq(self.0.iter().map(|b| Bytes(b)))
    }
}

fn main() -> bincode::Result<()> {
    let objs: Vec<Obj> = vec![
        IpAddr::V4(Ipv4Addr::LOCALHOST),
        IpAddr::V6(Ipv6Addr::LOCALHOST),
    ];

    let batches = SerializedReadReplyBatches(
        objs.iter()
            .map(|obj| bincode::serialize(obj))
            .collect::<Result<_, _>>()?,
    );

    let transmission = bincode::serialize(&batches)?;

    let received: Vec<Obj> = bincode::deserialize(&transmission)?;
    println!("{:#?}", received);

    Ok(())
}
```

**Comment by jonhoo** [comment]
Ah, interesting, so basically just encoding each byte individually. I'm guessing that would likely end up a fair bit slower, but it would certainly do the trick. I think I'll probably just also modify the reader in this case to try and keep the performance (given that this is such hot code), but the example was helpful nonetheless!

I don't know if there's much serde can really do here, so feel free to close :) Thanks again for the help!

**Comment by jonhoo** [comment]
Having different types for serialization and deserialization seems to be landing me in all sorts of trouble once that type is nested inside other types. The type above is _really_ the type `D` in
```rust
enum ReadReply<D> {
  Normal(Result<Vec<D>, ()>),
  // other variants
}
```
And I'm running into deserialization errors when I serialize `ReadReply<Vec<u8>>` and then try to deserialize as `ReadReply<Vec<Obj>>`. Interestingly, this doesn't happen if I `bincode::deserialize(bincode::serialize(x))`, only if I go through some other crate that does the serialization (in this case [`async-bincode`](https://docs.rs/async-bincode/)). I'll keep digging.
