### ISSUE TITLE
Is there a way to tell serde to use different rename rules in a struct?

### ISSUE THREAD

**Issue by Armiixteryx** [serde-rs/serde#1846]
Hello. First, I want to thank you for you great work in this library.

Now, here is the reason of this issue:

I have some structs that I use to parse and generate JSON.

Sometimes I need to deserialize and serialize the fields of a struct in camelCase and in other times in snake_case.

I usually use `rename_all` attribute in a struct to rename its fields, like this:

```
#[derive(Serialize, Deserialize)]
#[serde(rename_all(serialize = "camelCase", deserialize = "snake_case"))]
struct MyStruct { ... }
```

Which works great to parsing a camelCase JSON an to generate another JSON with the same fields in snake_case, but the opposite is not possible with that way.

Until now I was cloning the struct with all its inner structs to put it the remaining annotation, something like this:

```
#[derive(Serialize, Deserialize)]
#[serde(rename_all(serialize = "camelCase", deserialize = "snake_case"))]
struct MyStructV1 { ... }

#[derive(Serialize, Deserialize)]
#[serde(rename_all(serialize = "snake_case", deserialize = "camelCase"))]
struct MyStructV2 { ... }
```

But it increases the size of the code without a good reason I think, because V1 and V2 have the same fields and they shall be used the same, and if I want to modify something in the struct I would have to do it twice.

So I need to know if there is a way to tell serde to use various `rename_all` rules or something equivalent in a struct, so I can use the same struct to parse and to generate JSON. I am already aware of the `alias` attribute but the main idea is to let serde handle the JSON without adding manually a hint of the fields more than the Rust name, to be able to focus more in the parsed data.

Thank you again.

**Comment by dtolnay** [comment]
Sorry that no one was able to provide guidance here! If this is still an issue, please take this question to one of the resources listed in https://github.com/serde-rs/serde/tree/v1.0.135#getting-help.
