### ISSUE TITLE
No way to de/serialize a decimal or bignum

### ISSUE THREAD

**Issue by apoelstra** [serde-rs/serde#185]
The `Serialize` trait has no way to serialize a decimal number without converting it to a Rust primitive numeric type, none of which are able to represent decimals.

A `Decimal` type might implement `Serialize` by pretending to be a string, i.e. calling `visit_str`, but then the `Serializer` will treat it as a string (e.g. by putting quotes around it). A subsequent parse will then read the value as the wrong type.

There is an analogous problem with `Deserialize`.

**Comment by Yoric** [comment]
If someone has time to patch it, this should be relatively simple. It's just about adding the corresponding code in `serde/src/de/impls.rs` and `serde/src/ser/impls.rs`.

**Comment by erickt** [comment]
Serde 0.7 dropped the num dependency, but I did just push up https://github.com/rust-num/num/pull/171 to add serde support there. @Yoric / @apoelstra: Does that work for you, or do you think serde needs explicit support for decimal / bignum types?

**Comment by oli-obk** [comment]
I think it would be way prettier for json and xml to serde these to/from numeric primitives that are too big for Rust's integrals. The corresponding method could pass a str.

**Comment by apoelstra** [comment]
@erickt Yes, I need support for JSON-style numbers, which are encoded as numbers, not strings or lists or any other proxy type.

**Comment by nubis** [comment]
Pull request #375 adds basic support for d128, I'm suggesting a version bump to 0.8.0 but I see someone else wants that number 😛 

I'm sending a corresponding serde_json pull request today or tomorrow at the latest. 

If you need this for any of your projects (like me) you may point to my fork.

**Comment by dtolnay** [comment]
I started working on this today. Does anyone have a favorite arbitrary precision decimal type? It looks like the `num` crate does not provide one yet - https://github.com/rust-num/num/issues/8.

**Comment by dtolnay** [comment]
Given that there is no good arbitrary precision decimal type yet in Rust, I ended up using String and leaving it up to the user - https://github.com/serde-rs/json/pull/252. We can adopt a better representation backward-compatibly if one materializes.

If you have been waiting for this feature, please take a look at the PR and let us know whether it addresses your use case.

**Comment by dtolnay** [comment]
Diesel is now using [`bigdecimal`](https://github.com/akubera/bigdecimal-rs).

**Comment by alexreg** [comment]
@dtolnay Judging by your comment on the other issue, is this something you'll want to reconsider more strongly when it comes to prototyping Serde 2.0?

**Comment by dtolnay** [comment]
I am satisfied with the approach in serde_json which uses the existing Serde data model to pass arbitrary precision numbers to a format-specific number type.

```toml
[dependencies]
serde_json = { version = "1.0", features = ["arbitrary_precision"] }
```

```rust
#[macro_use]
extern crate serde_derive;

extern crate serde;
extern crate serde_json;

use serde_json::Number;

#[derive(Deserialize)]
struct LanSyncPacket {
    host_int: Number,
}

fn main() {
    let j = r#" {"host_int": 123456789012345678901234567890123456789} "#;
    let packet = serde_json::from_str::<LanSyncPacket>(j).unwrap();
    println!("{}", packet.host_int);
}
```

```
123456789012345678901234567890123456789
```

**Comment by dharric** [comment]
Switching to Number does work, but then one get's the error for Queryable: the trait bound `serde_json::number::Number: diesel::Queryable<diesel::sql_types::Numeric, diesel::pg::Pg>` is not satisfied
Is there no way of serializing BigDecimal? Or perhaps is there a diesel feature to enable this impl?

**Comment by technic** [comment]
Hi!
Can the number be borrowed as &str? Ideally a would like to have visit_number_as_str method in the Visitor, instead of current implementation.

**Comment by technic** [comment]
@dtolnay Another suggestion, arbitrary precision (or better visit number as &str) should be runtime option of the serializer/deserializer. This can be achieved by Generics.
