### ISSUE TITLE
Feature: extensible object-model

### ISSUE THREAD

**Issue by Diggsey** [serde-rs/serde#1850]
Serde has a fixed object-model, determined by the set of `serialize_xyz` and `deserialize_xyz` methods on the `Serializer` and `Deserializer` traits.

The idea here is to add the ability to extend the object-model, by adding `serialize_custom` and `deserialize_custom` methods to the respective traits.

```rust
fn serialize_custom<T: Any, U: Any>(self, value: &T, opts: &U) -> Result<()> {
    // Default implementation always returns an error
    Err(...)
}

fn deserialize_custom<T: Any, U: Any>(self, opts: &U) -> Result<T> {
    // Default implementation always returns an error
    Err(...)
}
```

This allows designing types which will be treated specially by a custom serializer. For example, I could make a wrapper around a `oneshot::Sender` which implements `Serialize` via `serialize_custom`, and then create a custom serializer that understands how to serialize a channel.

In the absence of specialization, implementations would use the `downcast`-related methods on `Any` and `Box<Any>` to determine whether the custom type is supported. The compiler is quite capable of optimizing these away, so there's no real performance cost:
https://godbolt.org/z/p3L7ae

**Comment by dtolnay** [comment]
I think I would prefer not to pursue this in this crate. But I would be excited to see someone give this a shot in a separate library.

**Comment by Diggsey** [comment]
Hmm, I understand the sentiment, but it's a difficult thing to experiment with in a separate library given how deeply embedded serde is in the ecosystem. I think the only practical way might be to fork serde and intend that users `[patch]`` in the substitute?

Is this something you would be open to including if such an experiment was successful? (For some definition of successful...)

**Comment by oli-obk** [comment]
Why do you need aid from serde here? At least for serializers with no lifetimes, you should be able to downcast the serializer from within your `Serialize` impl (or at least use TypeId to detect which serializer it is)
