### ISSUE TITLE
Creating a generic function to deserialize from a file

### ISSUE THREAD

**Issue by QuarkNerd** [serde-rs/serde#1854]
I have created this function 
```
pub fn open_with_relative_path<T>(file: PathBuf) -> T 
    where 
        T: DeserializeOwned,
{
    let mut path = current_dir().unwrap();
    path.push(file);
    let mut file = File::open(path).unwrap();
    let mut serialized_string = String::new();
    file.read_to_string(&mut serialized_string).unwrap();
    let a: T = serde_json::from_str(&serialized_string).unwrap();
    a
}
```

I try to use it like so 
```
let a : HashMap<&'static str, Strategy> = open_with_relative_path::HashMap::<&'static str, Strategy>(path);
```

where `Strategy` is a custom struct that derives `Serialize` and `Deserialize`.

That line gives me therror "implementation of `players::_IMPL_DESERIALIZE_FOR_Strategy::_serde::Deserialize` is not general enough"
Can someone explain this?

I have tried to derive `DeserializeOwned`. And I am told "cannot find derive macro `DeserializeOwned` in this scope".
Why is this?

I have a vauge understanding of lifetme, but don't see why they matter here

**Comment by dtolnay** [comment]
Please take this question to one of the resources listed in https://github.com/serde-rs/serde/tree/v1.0.135#getting-help. Sorry that no one was able to provide guidance here.
