### ISSUE TITLE
`#[derive(serde::Deserialize)]` fails to implement for `&[u8; 20]`, but works for `[u8;20]`

### ISSUE THREAD

**Issue by Byron** [serde-rs/serde#1857]
Here is a link [to the playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=825c161aefc77d63857d372e958faabb) illustrating this.

<img width="903" alt="Screenshot 2020-07-16 at 15 01 23" src="https://user-images.githubusercontent.com/63622/87637724-3b681780-c775-11ea-990f-3f9d7d3cc776.png">

The manual implementation looks [like this](https://github.com/Byron/git-oxide/blob/9f46efd625d45a9ad947e9f7bc6f31f4426f3cfc/git-object/src/borrowed/id.rs#L36-L61) but currently [panics](https://github.com/Byron/git-oxide/blob/9f46efd625d45a9ad947e9f7bc6f31f4426f3cfc/git-object/src/borrowed/id.rs#L61) if the underlying slice is not of the desired length.

#### Motivation

I just recently learned that borrowed arrays are similar to a slice, but encodes the desired length of the slice at the same time. This makes such a type self-documenting in my use case, and is thus preferable over using bare slices.

As it is possible to convert slices into arrays of respective sizes using `TryInto`, I believe this is a default feature naturally supported in Rust.

This is why I would have hoped borrowed arrays to be supported in serde as well.

#### Hopes

Unless there is a technical limitation for this, I hope there is a chance to have deserialization implemented for borrowed arrays up to a size of 32 elements.

In any case, thanks for all your efforts.

#### Other Observations

* `serde::Serialize` can be auto-implemented without problems

#### Meta

* tested *serde 1.0.114* on MacOS using rustc v1.44.1

**Comment by dtolnay** [comment]
An implementation of this was attempted in #1877 but it turned out not to be worthwhile in my opinion because of the impact on compile time.
