### ISSUE TITLE
Collect duplicate fields using derive attribute

### ISSUE THREAD

**Issue by Plecra** [serde-rs/serde#1859]
This continues #690. @dtolnay recommended using a Deserializer adapter as a solution, but I'm not sure how it helps. I don't think there's any `Deserialize` method that could be used for this behaviour.

```rust
#[derive(Deserialize)]
struct Cores {
    #[serde(duplicates)]
    core: Vec<String>,
}
```

[Here's an possible implementation on the playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ad43c1fe9ba368d3b57cd90a9321ae80)

**Comment by nickbabcock** [comment]
Yeah I ended up implementing this with my own custom derive macro for structs (based on your gist -- thank you again for showing me)

Some implementation detail differences in behavior when a field is decorated with `#[serde(duplicated)]` compared to a regular field:

- Initialized with `Vec::new()` (ie: not initialized to an `std::option::Option::None`)
- When the `__Field` is encountered, always blindly push the next value:

```rust
(#name).push(::serde::de::MapAccess::next_value::<#farg>(&mut __map)?);
```

- No need to have a step to extract field from an Option or check if there is a default fallback for said field.

There are some significant downsides to implementing one's own custom derive macro -- I haven't implemented many of serde's field / container attributes. I've also only gotten `duplicated` to work for the `Vec` containers. So if there does exist a `Deserializer` adapter for a solution, I'd love to see it!

**Comment by dtolnay** [comment]
I still don't feel this is something that needs to be built into the serde crate. Thanks anyway for the suggestion!
