### ISSUE TITLE
No way to serialize Weak pointers

### ISSUE THREAD

**Issue by erickt** [serde-rs/serde#186]
As mentioned on [reddit](https://www.reddit.com/r/rust/comments/3u4ri0/serde_serializing_weak/). Open question: What do we do if the value the `Weak` pointer is pointing at has been destroyed? Should we serialize them as an `Option` pointer?

**Comment by erickt** [comment]
It's also not clear what we should do for deserialization.

**Comment by oli-obk** [comment]
I'd serialize it as an `Option` pointer and during deserialization, in case it's `None`, just create an `Rc`, make a `Weak` from that and `drop` the `Rc`.

**Comment by erickt** [comment]
@oli-obk: I suppose that would work, but it seems sad that we wouldn't actually be able to deserialize these weak types. I wonder if a better idea would be to get a `impl Default` implemented for `Weak` types, that defaults to it not being defined.

**Comment by shahn** [comment]
I think it doesn't really make sense to put more time into this until #194 is resolved somehow. For Weak pointers the failure modes mentioned in #194 are even worse.

Nevertheless, getting a default impl for Weak into rust seems smart.

**Comment by apasel422** [comment]
rust-lang/rust#30467 added a `Weak::new` method, though it is unstable.

**Comment by oli-obk** [comment]
`Weak::new` is now (1.10) stable: https://github.com/rust-lang/rust/issues/30425#issuecomment-219836269

**Comment by shahn** [comment]
My point about #194 being unresolved remains I'm afraid, tho of course I'm happy Weak::new is stable now
