### ISSUE TITLE
Cannot use rename_all or rename on untagged enum

### ISSUE THREAD

**Issue by kjeremy** [serde-rs/serde#1861]
I am trying to serialized the `TextDocumentContentChangeEvent` from https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_didChange and am running into the following problem:

This:

```rust
/// An event describing a change to a text document. If range and rangeLength are omitted
/// the new text is considered to be the full content of the document.
#[derive(Debug, Eq, PartialEq, Clone, Deserialize, Serialize)]
#[serde(untagged, rename_all = "camelCase")]
pub enum TextDocumentContentChangeEvent {
    Full {
        /// The new text of the document.
        text: String,
    },
    Range {
        /// The range of the document that changed.
        range: Range,

        /// The length of the range that got replaced.
        #[serde(skip_serializing_if = "Option::is_none")]
        #[deprecated]
        range_length: Option<u64>,

        /// The new text of the range.
        text: String,
    },
}
```

serializes as

```json
{"range":{"start":{"line":0,"character":0},"end":{"line":0,"character":12}},"range_length":12,"text":"range contents"}
```

But `range_length` should serialized as `rangeLength`. If I add `serde(rename="rangeLength")` to the `range_length` field then suddenly serde forgets that the enum is untagged.

I cannot seem to get this to work unless I pull the enum variants out into their own structs.

**Comment by jonasbb** [comment]
Maybe I am missing something, but this seems to work for me on the [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a7ac849d1db8bc813de6fa4254c77c26).

```rust
        /// The length of the range that got replaced.
        #[serde(skip_serializing_if = "Option::is_none", rename="rangeLength")]
        #[deprecated]
        range_length: Option<u64>,
```

produces

```json
{"range":{"start":{"line":0,"character":0},"end":{"line":0,"character":12}},"rangeLength":12,"text":"range contents"}
{"text":"range contents"}
```

**Comment by kjeremy** [comment]
You're right. I made a mistake. It looks like it's failing this round trip test on the deserialize assertion (Range always deserializes to Full variant):

```rust
fn test_serialization<SER>(ms: &SER, expected: &str)
    where
        SER: Serialize + for<'de> Deserialize<'de> + PartialEq + std::fmt::Debug,
    {
        let json_str = serde_json::to_string(ms).unwrap();
        assert_eq!(&json_str, expected);
        let deserialized: SER = serde_json::from_str(&json_str).unwrap();
        assert_eq!(&deserialized, ms);
    }
```

**Comment by kjeremy** [comment]
It succeeds if range_length is `None`

**Comment by kjeremy** [comment]
Maybe this is the same as #1560

**Comment by jonasbb** [comment]
The test seems to pass if you define `Range` before `Full`.

**Comment by kjeremy** [comment]
I tried that but then it failed when round-tripping the other variant.

**Comment by dtolnay** [comment]
If there is still unexpected behavior that is distinct from the issue linked above, please open a different issue with a minimal compilable example that reproduces what you feel is the wrong behavior.
