### ISSUE TITLE
Empty tuple variant does not call any de::VariantAccess methods

### ISSUE THREAD

**Issue by Tamschi** [serde-rs/serde#1862]
Given a
```rust
#[derive(Debug, Deserialize, PartialEq)]
enum Enum {
    Structured { i32: i32, f64: f64 },
    Tuple(u8, u8),
    Newtype(u8),
    Unit,
    EmptyTuple(),
}
```
, deserialising this (in this case within a struct or Vec) calls the expected `de::VariantAccess` methods for the first four variants, but does not call any of them after determining the variant is `EmptyTuple()` via `de::EnumAccess`.

I can work around this easily enough and I like that I (name aside) can distinguish `EmptyTuple()` from `Unit`, but this is still pretty odd and seems to contradict the documentation at <https://docs.serde.rs/serde/de/trait.VariantAccess.html>.

I'm using derived `Deserialize` implementations without further relevant configuration, and `serde` and `serde_derive` v1.0.114.

**Comment by dtolnay** [comment]
I think this is working correctly as far as I can tell; it calls VariantAccess::tuple_variant with len=0 as I would expect.

From inspecting with `cargo expand` the generated code contains:

```rust
(__Field::__field4, __variant) => {
    struct __Visitor<'de> {
        marker: _serde::export::PhantomData<Enum>,
        lifetime: _serde::export::PhantomData<&'de ()>,
    }
    impl<'de> _serde::de::Visitor<'de> for __Visitor<'de> {
        type Value = Enum;
        fn expecting(
            &self,
            __formatter: &mut _serde::export::Formatter,
        ) -> _serde::export::fmt::Result {
            _serde::export::Formatter::write_str(
                __formatter,
                "tuple variant Enum::EmptyTuple",
            )
        }
        #[inline]
        fn visit_seq<__A>(
            self,
            _: __A,
        ) -> _serde::export::Result<Self::Value, __A::Error>
        where
            __A: _serde::de::SeqAccess<'de>,
        {
            _serde::export::Ok(Enum::EmptyTuple())
        }
    }
    _serde::de::VariantAccess::tuple_variant(  // <--------------------------
        __variant,
        0usize,
        __Visitor {
            marker: _serde::export::PhantomData::<Enum>,
            lifetime: _serde::export::PhantomData,
        },
    )
}
```

**Comment by Tamschi** [comment]
You're right, apologies.

Fyi, what tripped me up was not hitting my breakpoint on the function for one of the variants between `Tuple(u8, u8)` and `EmptyTuple()` (Which seems to depend on the calling order, must be some strangeness with the Rust integration in Code.) and `visit_seq` not validating the end of the sequence.
