### ISSUE TITLE
deny_unknown_fields while ignoring a whitelist of fields

### ISSUE THREAD

**Issue by chinedufn** [serde-rs/serde#1864]
Hey!

I have a large dialogue data structure that I'd like to use `#[serde(deny_unknown_fields)]` in order to prevent typos when deserializing it.

However, the YAML that I'm deserializing contains some extra metadata that is read by tests, but not at all used by the runtime struct that I am deserializing to.

Currently, there doesn't _seem_ to be a way to deny all unknown fields excluding some set of fields that you've whitelisted.

I attempted the following as a hacky approach which I expected to work, but it did not:

```rust
#[serde(deny_unknown_fields)]
struct MyStruct {
    field: u8,
    // (use a ZST to avoid the memory cost of keeping unnecessary data in my struct)
    #[serde(skip)]
    ignored_field: ()
}
```

Error: `Result::unwrap()` on an `Err` value: Message("unknown field `ignored_field`,`

If you have YAML such as

```yml
field: 0
ignored_field: "Some data structure that I don't want to deserialize in MyStruct because I only use it for tests"
```

---

I also tried the following with no luck:

```rust
#[serde(deny_unknown_fields)]
struct MyStruct {
    field: u8,
    #[serde(deserialize_with = "nothing")]
    ignored_field: ()
}

fn nothing<'de, D>(_d: D) -> Result<(), D::Error>
where
    D: Deserializer<'de>,
{
    Ok(())
}
```

I'm using `serde = "1.0.111"` and `serde_yaml = "0.8.12"`.

Is this use case currently possible?

**Comment by dtolnay** [comment]
Untested but I would expect that the following would work:

```rust
#[derive(Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct MyStruct {
    field: u8,

    #[serde(default, skip_serializing)]
    ignored_field: serde::de::IgnoredAny,
}
```

and if there are many such fields that you don't want all cluttering the struct:

```rust
#[derive(Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct MyStruct {
    field: u8,

    #[serde(flatten, skip_serializing)]
    ignored_fields: IgnoredFields,
}

#[derive(Deserialize)]
struct IgnoredFields {
    #[serde(default)]
    ignored_field0: IgnoredAny,
    #[serde(default)]
    ignored_field1: IgnoredAny,
}
```

In both cases `skip_serializing` would only be needed if you are deriving Serialize too.

**Comment by chinedufn** [comment]
Worked perfectly, thanks as always!!

For anyone that comes across this, here's my setup (I used a new type wrapper since I needed PartialEq)

```rust
// Real test_meta is in here in another file
#[cfg(feature = "test-utils")]
mod test_meta;
// In non-testing environment I ignore test_meta
#[cfg(not(feature = "test-utils"))]
mod test_meta {
    use serde::de::IgnoredAny;

    #[derive(Deserialize, Debug, Copy, Clone, Default)]
    pub struct TestMeta(IgnoredAny);

    impl PartialEq for TestMeta {
        fn eq(&self, _other: &Self) -> bool {
            true
        }
    }
}

#[derive(Deserialize, Serialize, Debug, Clone, Default, PartialEq)]
#[serde(deny_unknown_fields)] 
struct MyStruct {
    #[cfg_attr(not(feature = "test-utils"), serde(skip_serializing))]
    test_meta: test_meta::TestMeta,
}
```
