### ISSUE TITLE
IPA pronunciation for this project's name

### ISSUE THREAD

**Issue by rtpg** [serde-rs/serde#1865]
This project's name is a portmanteau of two English words, leading both to native speakers saying it every which way, and non-native English speakers being very unsure of how to start pronouncing it.

Putting an IPA pronunciation guide would both add a little flair to the intro, but also just give people the answer to this question if they are mainly learning Rust through text.

Apologies if this opens up the longest bike-shedding issue possible :nerd_face:

**Comment by ConnorTroy** [comment]
It’s sehr-day

**Comment by dtolnay** [comment]
I don't think this needs to be covered by the readme. In general there is a tradeoff that the more you write, the less of it people will read, and I don't think this meets the bar for what is most important to cover.
