### ISSUE TITLE
Feature Request: Option type lookahead

### ISSUE THREAD

**Issue by XAMPPRocky** [serde-rs/serde#1866]
Serde's `Deserializer` can currently support a large variety of data formats, however I don't think there is a way to deserialize a value of a optional type if you need the inner type information to correctly deserialize. As an example of this in the wild; ASN.1 Packed Encoding Rules (PER) is a binary format that encodes every type with a tag and you can have "sequences" (which are fixed field ordered `struct`s) with optional fields.

In order to know if an optional field is present, the parser checks if the tag in the buffer matches the tag of that type, if not it's considered `null` and the parser checks for the next field. It would be nice if there was a way to support this use-case in serde.

**Comment by dtolnay** [comment]
I would prefer not to build this into the serde crate. In general it isn't a goal to support the union of all features that all formats in the world need, and this doesn't sound like one of the common ones.
