### ISSUE TITLE
Migrate the codebase to edition = "2018" ?

### ISSUE THREAD

**Issue by Veetaha** [serde-rs/serde#1867]
I wonder what is the main blocker for migrating the main codebase of `serde` crates to `edition = "2018"`?
IIRC it is not a breaking change to switch the edition:
https://doc.rust-lang.org/book/appendix-05-editions.html

> All Rust compiler versions support any edition that existed prior to that compiler’s release, and they can link crates of any supported editions together. Edition changes only affect the way the compiler initially parses code. Therefore, if you’re using Rust 2015 and one of your dependencies uses Rust 2018, your project will compile and be able to use that dependency. The opposite situation, where your project uses Rust 2018 and a dependency uses Rust 2015, works as well.

I don't think we need to wait for `2.0` (if it is really going to happen at all, isn't it?) to update the edition the implementation of `serde` uses.

**Comment by MikailBag** [comment]
AFAIK serde supports Rust v1.13, which does not implement Rust 2018.

**Comment by Veetaha** [comment]
Might it make sense to update the msrv in a minor release?
For example this issue proposes to update the msrv in minor releases in tokio: https://github.com/tokio-rs/tokio/issues/2718#MSRV

**Comment by dtolnay** [comment]
I don't think we need an issue open for this. There isn't any rush since I don't know of anything from 2018 edition that this crate needs, like new keywords or whatnot.
