### ISSUE TITLE
Better derive for trait bounds of generics

### ISSUE THREAD

**Issue by technic** [serde-rs/serde#1868]
Hi,

Thanks a lot for this wonderful crate!!!

I have the following type which I want to serialize:

```rust
#[derive(Serialize)]
struct Response<'a, I>
where
    I: Iterator<Item = &'a Point>,
{
    points: IteratorAdapter<I>,
}
```

I use this wrapper for iterators, but it is not important. The important point is that there is a `Serialize` implementation for the `IteratorAdapter<I>` and of course also for `Point`. The problem is that the derive macro generates the following trait bounds:

```rust
#[automatically_derived]
impl <'a, I> _serde::Serialize for Response<'a, I> where
I: Iterator<Item = &'a Point>, I: _serde::Serialize {
    // some code
}
```

It requires `I: _serde::Serialize`, and it does not compile.
However, the thing which is really needed to be serializable is `IteratorAdapter<I>`. So the correct trait bound should be 
`IteratorAdapter<I>: _serde::Serialize`.

There is a workaround for this by declaring just

```rust
#[derive(Serialize)]
struct Response<Ps>
{
    points: Ps,
}
```

The link to the playground https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=f6a9ac1985b570c9357f59bdc052411c

**Comment by dtolnay** [comment]
This is a consequence of https://github.com/rust-lang/rust/issues/26925.

You can manually provide the intended bound though.

```rust
use serde::Serialize;

#[derive(Serialize)]
#[serde(bound(serialize = "IteratorAdapter<I>: Serialize"))]
struct Response<'a, I>
where
    I: Iterator<Item = &'a Point>,
{
    points: IteratorAdapter<I>,
}
```

**Comment by technic** [comment]
@dtolnay thanks!
