### ISSUE TITLE
Combine "transparent" and "skip_serializing_if" tags

### ISSUE THREAD

**Issue by dspicher** [serde-rs/serde#1870]
I would like to have a transparent struct with a single field, whose serialization is skipped if some condition is fulfilled:
```
#[derive(serde::Serialize)]
#[serde(transparent)]
struct Foo {
    #[serde(skip_serializing_if = "String::is_empty")]
    inner: String,
}
```

However, if the `transparent` tag is included, the inner tag is ignored, i.e. this compiles:
```
#[derive(serde::Serialize)]
#[serde(transparent)]
struct Foo {
    #[serde(skip_serializing_if = "String::i_am_ignored")]
    inner: String,
}
```

Is this expected behaviour?

**Comment by dtolnay** [comment]
What would you want the serialized representation to be if skipped?

**Comment by dtolnay** [comment]
By which I mean, in the case of something like:

```rust
use serde::Serialize;

#[derive(Serialize)]
#[serde(transparent)]
struct Foo {
    #[serde(skip_serializing_if = "String::is_empty")]
    inner: String,
}

fn main() {
    let empty_foo = Foo { inner: String::new() };
    println!("{}", serde_json::to_string(&empty_foo).unwrap());
}
```

**Comment by dspicher** [comment]
Well, is there something like an empty serialization?

**Comment by dspicher** [comment]
To clarify the intent, I would like to use this on an optional field, not on the top-level serialization object.

**Comment by toxeus** [comment]
Related: https://github.com/serde-rs/serde/issues/65#issuecomment-422162821

**Comment by dtolnay** [comment]
There isn't something like an empty serialization. When a Serialize impl runs, the only way it can succeed is by serializing something.

The thing whose field this is can decide not to serialize that field, though.
