### ISSUE TITLE
the trait `serde::Serialize` is not implemented for `sgx_isa::Attributes`

### ISSUE THREAD

**Issue by lx-1234** [serde-rs/serde#1871]
Hey, how can I serialize the type sgx_isa::Attributes?

error[E0277]: the trait bound `sgx_isa::Attributes: serde::Serialize` is not satisfied
--> src/main.rs:25:5  
   |  
25 |     attributes: Attributes,  
   |     ^^^^^^^^^^^^^^^^^^^^^^ the trait `serde::Serialize` is not implemented for `sgx_isa::Attributes`  
   |  
   = note: required by `serde::ser::SerializeStruct::serialize_field`

**Comment by dtolnay** [comment]
Please take this question to one of the resources listed in https://github.com/serde-rs/serde/tree/v1.0.135#getting-help. Sorry that no one was able to provide guidance here.
