### ISSUE TITLE
Manually specifying derive implementation where clause

### ISSUE THREAD

**Issue by BenHall-7** [serde-rs/serde#1876]
So I learned that serde could do this sort of automatic where clause when a struct or enum contained an associated type field, in the following manner:
```rust
use serde::{Serialize, Deserialize};

trait TestTrait {
    type AssociatedType;
}

#[derive(Serialize, Deserialize)]
struct TestStruct<T: TestTrait>(T::AssociatedType);
```
and the output contained
```rust
impl<T: TestTrait> _serde::Serialize for TestStruct<T>
where
    T::AssociatedType: _serde::Serialize,
```
However, if my associated type is wrapped in another type like
```rust
#[derive(Serialize, Deserialize)]
struct TestStruct<T: TestTrait>(Vec<T::AssociatedType>)
```
the where clause is no longer included when, in my use case, its inclusion is desired behavior. Would it be possible to manually specify that certain types in the output implement Serialize/Deserialize? Or is there another way to get this behavior without manually implementing (Deserialize especially)?

**Comment by jonasbb** [comment]
This can be done with the [`bound` attribute](https://serde.rs/container-attrs.html#bound).

**Comment by BenHall-7** [comment]
Fantastic! I hadn't seen that one before, so I will close this issue
