### ISSUE TITLE
Clarify when `deserialize_any` gets called on flattened structs.

### ISSUE THREAD

**Issue by lamafab** [serde-rs/serde#1881]
Hi

I'm writing a serde implementation for a non-self describing format and I'm running into issues when using `#[serde(flatten)]`.

Deserializing with this type works fine:

```rust
    #[derive(Deserialize)]
    struct Custom {
        a: u32,
        b: u32,
        c: u32,
        d: u32,
    }
```

Deserializing into a HashMap works too. However, when doing the following I run into issues.

```rust
    #[derive(Deserialize)]
    struct Custom {
        a: u32,
        b: u32,
        #[serde(flatten)]
        x: Sub,
    }

    #[derive(Deserialize)]
    struct Sub {
        c: u32,
        d: u32,
    }
```

Serde attempts to call `deserialize_any` when deserializing the *value* (not the field) of `Sub`->`c`, which in my case is unsupported and returns a *NotSupported* error. What's not quite clear to me is why a type hint is required here, since it's explicitly specified what the type is.

Could you give me some info on why this happens and what to look out for? As best as you can, of course, since you don't see the full implementation of mine.

Thanks a lot, highly appreciated!

**Comment by lamafab** [comment]
Okay, I played around a little and found a fix by implementing a very basic `deserialize_any` method.

```rust
fn deserialize_any<V>(self, visitor: V) -> Result<V::Value, Self::Error>
where
    V: Visitor<'a>,
{
    if self.is_next_numeric()? {
        self.deserialize_i64(visitor)
    } else {
        self.deserialize_string(visitor)
    }
}
```

The format I'm dealing with is primarily ASCII based, so this *should* probably be ok. However, I'm not sure how to feel about this. This looks like a hack and I'll need a very strong testsuite to make sure this will work as I hope it will.

I'd appreciate how the logic of `#[serde(flatten)]` is driven here: why does it need a type hint in the first place?

**Comment by lamafab** [comment]
Is it possibly related to how `FlatMapDeserializer`/`FlatMapAccess`/`FlatStructAccess` and respectively `Content` is implemented? Note the comment:

```rust
    impl<'de> Deserialize<'de> for Content<'de> {
        fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
        where
            D: Deserializer<'de>,
        {
            // Untagged and internally tagged enums are only supported in
            // self-describing formats.
            let visitor = ContentVisitor { value: PhantomData };
            deserializer.deserialize_any(visitor)
        }
    }
```

*untagged* ~= *flattened* (?)

**Comment by lamafab** [comment]
Found a way around this. Seems like using `#[serde(flatten)]` on non-self describing formats is unsupported.

**Comment by kevincox** [comment]
Is there is technical reason that this isn't done? It seems silly that serde_derive asks for `any` then errors out when it doesn't get the right type. It seems like it knows the type it needs so why is it making us guess?
