### ISSUE TITLE
Serialize NewStruct(u64) as string in JSON, but binary in BinCode.

### ISSUE THREAD

**Issue by koalefant** [serde-rs/serde#1884]
I need following behavior: a `struct UserId(u64);` needs to be serialize u64 as string (hexadecimal number) in JSON (for readable logs) but use binary u64 number when using BinCode (for compact/fast transmission). 

Is there a way I could branch Serialize impl based on Serializer type?

**Comment by Mingun** [comment]
Check serializer/deserializer with [is_human_readable()](https://docs.serde.rs/serde/trait.Serializer.html#method.is_human_readable) and serialize/deserialize your struct accordingly

**Comment by koalefant** [comment]
Exactly what I was looking for.
