### ISSUE TITLE
Providing context during deserialization

### ISSUE THREAD

**Issue by shutton** [serde-rs/serde#1886]
There doesn't seem to be any way to provide any runtime context to a custom deserializer (or even to carry information gleaned from earlier processing).

I ask because I'm looking at a JSON dataset that's structured similar to
```
{ "meta1": "x",
  "meta2": "y",
  "items": [
    { "id": 9999, "field1": 123 },
    { "id": 8888, "field1": 456 },
    (many thousand more)
  ]
}
```
The goal is to search through "items" for particular values that are relevant to an outer context, screening out some elements altogether, and then looking at other elements to find the most relevant items to some external criteria that's determined at run time.  Obviously, the goal is to not retain the *entire* structure in memory as it's deserialized.

I can get close by specifying
```
  #[serde(deserialize_with = "my_scanner")]
  #[serde(rename = "items")]
  best_item: Item,
```
But, unfortunately, there doesn't seem to be a way to pass any external information to `my_scanner()` -- a locally-scoped functions can't reference its environment.  And, as best as I can tell, there's no obvious way to specify a closure as a deserializer due to the complex typing and lifetimes (though it might just be beyond my current skill level).

In other languages, this would be handled with a "user data" element given to the initial call to the deserializer, but serde doesn't appear to support this.  Any workarounds?

**Comment by shutton** [comment]
For the record, I did explore using a stream deserializer.  The problem is that the "streaming" portion of the structure is wrapped in a meta record, so the stream doesn't begin until the entire structure has been parsed.

**Comment by dtolnay** [comment]
If you are still interested in getting this working, please follow up in one of the resources listed in https://github.com/serde-rs/serde/tree/v1.0.135#getting-help. Sorry that no one was able to provide guidance here.
