### ISSUE TITLE
Support seq length from same struct

### ISSUE THREAD

**Issue by clouds56** [serde-rs/serde#1887]
I'm coming from `bincode`, and would like to (de)serialize `Vec` with variant fixed length (that means fixed without looking at data of `Vec`)

```rust
#[derive(Serialize, Deserialize)]
struct Mesh {
  pub count: u32,
  #[serde(seq_size="count as usize * 3")]
  pub position: Vec<f32>,
  #[serde(seq_size="count as usize * 2")]
  pub uv: Vec<f32>,
}
```
and this would first `deserialize_u32` into `count` field from buffer and then apply it to `position` and `uv` using `deserialize_tuple` other than `derserialize_seq` when visit `Mesh` via `__Visitor::visit_seq` (but not `__Visitor::visit_map` since the order of field in map is unknown)

**Comment by dtolnay** [comment]
I would prefer not to build this into serde_derive, but someone could provide a different `Deserialize` derive macro in a different crate which would implement this behavior.

**Comment by clouds56** [comment]
@dtolnay could you briefly explain how to extend `Deserialize` derive?
I mean do I have to create a new macro that replace `Deserialize`?

If feature A (like this `seq_size`) could be found in crate `serde_with_seq_size`, and export macro `serde_with_seq_size::Deserialize` (which extends `serde::Deserialize`), while feature B could be found in another crate `serde_another::Deserialize` also extending `serde::Deserialize`, how could I use both feature A and B?
