### ISSUE TITLE
Partial update deserialization

### ISSUE THREAD

**Issue by kevincox** [serde-rs/serde#1889]
It would be very useful if deserialization could be used for partial updates. For example I have a struct and I want to deserialize into it but allow some fields to me missing.

Right now the only real option is to make every field `Option<T>`. This works but makes working with the structure very inconvinent. You will almost always want to create a second structure without all of the `Option` fields and that increases maintenance burden to keep the two in sync.

If you write your own deserializer I think you can accomplish this but again, there is a lot of maintenance burden for this.

I think one way to implement this would be add an option to the `deserialize_in_place` generation to `serde_derive` to not raise an error if fields are missing. This would allow just updating the relevant fields. This is safe because all of the fields were valid before `deserialize_in_place` was called so it is fine to keep them as they were.

Example use cases:

* Configuration merging. This would enable efficiently and easily deep-merging multiple objects together.
* Multiple default values. This is sort of the same as the previous but right now your only options for defaults are setting them in `#[serde(default="some::path")]` which hardcodes them. If you could merge on top of an existing object that existing object becomes the defaults.
* Delta updates. This is useful for HTTP PATCH or other remote communication. It allows you just to send over the changed fields.

**Comment by dtolnay** [comment]
I would prefer not to build anything for this into the serde crate, but it sounds like something that could be implemented outside of serde, covering all of the use cases you listed. Something like:

```rust
let mut deserializer = serde_json::Deserializer::from_str(" { ... } ");
let defaults = MyStruct { ... };
let s: MyStruct = deserialize_with_defaults(&mut deserializer, &defaults)?;
```

**Comment by kevincox** [comment]
I don't think that would be possible because `serde::Deserialize` only has one method and it returns `Result<Self, _>` this means that there is no way to inject a "base" object and no way to deserialize in a way that doesn't return a complete object.

The only way I can possible thing of this working is something like serialize the default object, prepend it to the data, then deserialize. However that is awful for a variety of reasons not which of least is that it won't work for most formats.

I think this would need to be supported in-crate. My first idea without much thought would be something like:

```rust
pub trait DeserializePartial<'de>: Sized {
    type Base;

    fn deserialize_partial<D: serde::Deserializer>(base: Self::Base, deserializer: D) -> Result<Self, D::Error>;
}
```

Ideally `serde_derive` could then be updated to generate the `Base` type automatically. It could be a struct that is a clone of the struct that it is developed on except that every field is wrapped in `Option`. (More efficient systems could also be used).

**Comment by Mingun** [comment]
Actually, there is a hidden method in the `Deserialize` trait, but I don't think that this will help you much:
https://github.com/serde-rs/serde/blob/c3ce2c934a9123b5a309256d65cca6b6d19466ec/serde/src/de/mod.rs#L543-L570

**Comment by kevincox** [comment]
Yeah, I think the "base" would need to be a different type in most cases. (An exception being where the struct can implement `Default` or has a similar default state.) I think the semantics are also expected to be different. I would expect this method to still return an error or set a field to the default if missing, not reuse the value of "place". It seems that the input value of `place` should not affect the semantic value of the output value of `place`.
