### ISSUE TITLE
Pluggable serializers and deserializers

### ISSUE THREAD

**Issue by vanillajonathan** [serde-rs/serde#1890]
I would like to create two methods on a struct, one that uses serde to serialize and one that uses serde to deserialize, but I want neither of the methods to depend on a specific data interchange format such as JSON. So I don't want the methods to have any direct reference to serde_json.

Instead the methods could rely on traits specified as input parameters to the `new` function on the struct

**Comment by dtolnay** [comment]
If you are still interested in guidance on this, please follow up in one of the resources listed in https://github.com/serde-rs/serde/tree/v1.0.135#getting-help.
