### ISSUE TITLE
I don't know how can deserialize an object with one random parameter

### ISSUE THREAD

**Issue by dancespiele** [serde-rs/serde#1892]
Hello I try to deserialize a object with one random parameter like this:

```json
{"RANDOM": [
  [3, "string", "string", 3]
],
  "last": 15664444
}
```

I saw that similar issue here https://github.com/serde-rs/json/issues/165 however the api changed and I saw [this](https://serde.rs/deserialize-struct.html) but I really don't understand anything,

It will be great to have an example how can I deserialize this object please

**Comment by bepitulaz** [comment]
I'm new in Rust too and also don't understand how to parse this object:

```
{
   "dataset": [
       ["2020-09-17T07:00:00.000000Z", "XXX", 166347000, 162411000, 228.634271400000, 37535346121, 163693000, 163642000, 163693000]
   ]
}
```
I hope someone can shed some lights to deserialize it. Thank you.

**Comment by bepitulaz** [comment]
@dancespiele I'm new in Rust and Serde too. I have the same problem as you with the same object structure like that. You can create two structs.

```
#[derive(Debug, Deserialize, Serialize)]
struct YourMixedArray {
    item_a: i64,
    item_b: String,
    item_c: String,
    item_d: i64
}

#[derive(Debug, Deserialize, Serialize)]
struct YourObject {
    last: i64,
    random: Vec<YourMixedArray>
}
```
Hope it helps.

**Comment by dtolnay** [comment]
If you're still interested in guidance on this, please take this question to one of the resources listed in https://github.com/serde-rs/serde/tree/v1.0.135#getting-help.
