### ISSUE TITLE
Can't use stringify! in place of serde(rename = ...) and similar

### ISSUE THREAD

**Issue by Mingun** [serde-rs/serde#1895]
[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=0c89e9ffbd18f1f255885de6d0cb5686)

I trying to write macros that will create some container structs with elements. Because usually in the code you should name list properties pluralized, and in serialization format you prefered singular form (because multipli elements already assumed by the serialization form), rename is required. And because usually type name will match serialized element name, I try to deduce name from type name by using `stringify!`. Unfortunately, thats not work. Because the same construct works well for doc attributes, I assume, that problem in serde attributes.

Try to comment `#[serde(rename = $name)]` line:
```rust
// Adapted from
// https://stackoverflow.com/questions/55582838/call-stringify-inside-macro
use serde::Serialize; // 1.0.115

macro_rules! my_macro {
    () => { my_macro!(stringify!($x + $y)); };

    ($name:expr) => {
        #[derive(Serialize)]
        struct Container {
            #[serde(rename = $name)]// Doesn't work: "error: expected literal"
            #[doc = $name]// Work
            item: String,
        }
    };
}
my_macro!();
```

**Comment by davidhewitt** [comment]
Related: #450 (which is asking for `#[serde(rename = SOME_CONST)]`, which I think has similar technical constraints).

**Comment by Mingun** [comment]
Just found that this is duplicate of #1636 so closing this one
