### ISSUE TITLE
opt_in_serializing instead of skip_serializing

### ISSUE THREAD

**Issue by EverlastingBugstopper** [serde-rs/serde#1897]
so... i'm not sure if this is the right place for this but I figure folks on this repo would know where to point me for what I want to do. this _might_ be a feature request but likely will just need to be its own crate since the feature doesn't seem like it fits in with the rest of `serde` itself.

`serde` has this `#[serde(skip_serializing)]` attribute which is super handy. what i want to do is to have something like the opposite, where you need to explicitly opt-in to serializing a specific field instead of opting out of serialization. the reason for this is that I want to make it really easy to add additional fields to my anonymous usage data collection. it's the difference between adding an attribute to every field except the one i want to opt-in on, and adding an attribute to only the fields i want to opt in on. the latter is much more appealing to me because the cost of accidentally serializing something is high (i capture data i don't want to capture) and the cost of accidentally not serializing something is low (i just happen to lose some data and i'm ok with that)

the only way i can really think to do this is to create a new crate that wraps serde or just copies serde entirely and just makes some modifications to the #[derive(Serialize)] proc macro, probably renaming it to something like OptInSerialize or something like that.

so, my question here is 2 part:

1) anybody know if this already exists?
2) if the answer to 1 is no, it doesn't exist, what's the plan of attack? I took a quick look into how the `serde` library is set up and i'm a bit lost as to where i'd start working on this stuff.

---

to be completely explicit here, i'd like to replace the following:

```rust
#[derive(Debug, Clone, Serialize)]
struct MyStruct {
  #[serde(skip_serializing)]
  sensitive_data: String,

  #[serde(skip_serializing)]
  more_sensitive_data: Uuid,

  #[serde(skip_serializing)]
  even_more_sensitive_data: MySpecialType,
  
  #[serde(rename="os")]
  operating_system: String
}
```

with something that really captures the _intent_ of the serializing that's being performed:

```rust
#[derive(Debug, Clone, Capture)]
struct MyStruct {
  sensitive_data: String,

  more_sensitive_data: Uuid,

  even_more_sensitive_data: MySpecialType,
  
  #[capture(rename="os")]
  operating_system: String
}
```

**Comment by dtolnay** [comment]
I would prefer not to build this into the serde crate, but someone could create a different crate with a `Serialize` derive macro which implements this behavior. If you need guidance getting that working, check out any of the resources listed in https://github.com/serde-rs/serde/tree/v1.0.135#getting-help.
