### ISSUE TITLE
Using #[serde(tag = "field_name")] when a variant of the enum contains "field_name" serializes "field_name" twice

### ISSUE THREAD

**Issue by Tomaz-Vieira** [serde-rs/serde#1901]
If you have a serializable Enum with `#[serde(tag="field_name")]` and one of the variants of the enum also has a field called "field_name", then serializing that variant of the enum (to json, at least) will produce an output with a repeated "field_name". Here's some code to reproduce the issue

```rust
use serde_json;
use serde::Serialize;
use serde::ser::Serializer;
use core::marker::PhantomData;

#[derive(Serialize)]
pub struct MyGeneric<T: Named>{
    id: u64,
    #[serde(serialize_with = "serialize_marker")]
    marker: PhantomData<T>, //also used as enum tag
}

pub trait Named{
    fn class_name() -> &'static str;
}

fn serialize_marker<S: Serializer, T: Named>(
    value: &PhantomData<T>, serializer: S
) -> Result<S::Ok, S::Error>{
    return serializer.serialize_str(&T::class_name())
}

#[derive(Serialize)]
pub struct Person();
impl Named for Person{
    fn class_name() -> &'static str{
        "Person"
    }
}

#[derive(Serialize)]
#[serde(tag="marker")]
pub enum MyVariants{
    Person(MyGeneric<Person>),
}

fn main(){
    let p = MyVariants::Person(
        MyGeneric::<Person>{id: 123, marker: PhantomData}
    );
    println!("{}", serde_json::to_string(&p).unwrap());
    // prints this: {"marker":"Person","id":123,"marker":"Person"}
}
```

My intentions with this code was for a serialized MyGeneric<T> to be also deserializable as a `MyVariants`, so I thought I'd just tell `MyVariants` to leverage the `marker` value as a tag.

**Comment by dtolnay** [comment]
I think this behavior is fine. If you need the field to appear only once in your use case, you could replace `serde_json::to_string` with `serde_json::to_value`, which should discard the duplicated one.
