### ISSUE TITLE
#[serde(default)] uses type's default instead of struct's default method

### ISSUE THREAD

**Issue by jmwielandt** [serde-rs/serde#1903]
Hi, 

[The docs](https://serde.rs/container-attrs.html#default) about `#[serde(default)]` says: 

> When deserializing, any missing fields should be filled in from the struct's implementation of `Default`. Only allowed on structs.

But i currently have:

```rs
#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Config {
    #[serde(default)]
    pub some_value: u64,
}

impl Default for Config {
    fn default() -> Self {
        Self { some_value: 30_000 }
    }
}
```

If I use the `Config::default()` method, `some_value` is 30000, but if I try to deserialize a .toml file which `some_value` is missing, it will be 0 instead of 30000.

_PS: that code was written from scratch here._

**Comment by Tschrock** [comment]
The documentation you linked is for a struct, but your example is using it on a field.

See https://serde.rs/container-attrs.html#default
> When deserializing, any missing fields should be filled in from the struct's implementation of Default. Only allowed on structs.

vs https://serde.rs/field-attrs.html#default
> If the value is not present when deserializing, use the Default::default().

I've checked in one of my own projects, and using the attribute on a struct gives the desired results.
