### ISSUE TITLE
Allow deserializing T into Vec<T> with a single element

### ISSUE THREAD

**Issue by rimutaka** [serde-rs/serde#1907]
I ran into a situation where a sequence with only one value was stripped of the enclosing `[ ]`. E.g.
```
{
  "a": [1, 2, 3 ],
  "b": [4],
  "c": 5,
}
```
where `a`, `b`, `c` are `Vec<usize>`, but somehow the source of the JSON data lost `[ ]` around `5`.
As you would expect, the deserialization  fails on `"c": 5,` with `expected a sequence` error message.

**Questions to the maintainers**:

1. Would you consider a PR for a field attribute to enforce `Vec<T>` over `T`?
2. Is there already a way of achieving the same without a custom deser function?

relates to #1891

**Comment by Mingun** [comment]
This is relatively easy, see my implementation: https://github.com/Mingun/ksc-rs/blob/8532f701e660b07b6d2c74963fdc0490be4fae4b/src/parser.rs#L18-L42

**Comment by rimutaka** [comment]
@Mingun , thanks for sharing. That's a neat solution! I think it is a bit different from the use case I'm targeting.

In your YAML you have separate entries for `one` and `many`:
```yaml
 one: just a string
 many:
   - 1st string
   - 2nd string
```
which is different from either an object (map) or an array of the objects in the same entry:
- json 1: `{ "a": [1, 2, 3 ] }`
- json 2: `{ "a": [4] }`
- json 3: `{ "a": 5 }`

Would your implementation apply?

I posted my custom de-serializer in https://gist.github.com/rimutaka/401ec6ad6dc27fb49be570467cad041e. I wonder if there is a better of achieving the same and if it should be built into Serde as an option.

**Comment by Mingun** [comment]
> In your YAML you have separate entries for one and many:

No, that is just an example of two possible inputs. It can parse all your 3 jsons, but, of course, you need either use the `OneOrMany<i32>` as a type of your json fields:
```rust
#[derive(Deserialize)]
struct MyStruct {
  field: OneOrMany<i32>,
  ...
}
```
, or use patched serde with #1623 applied:
```rust
#[derive(Deserialize)]
struct MyStruct {
  #[serde(from = "OneOrMany<i32>")]
  field: Vec<i32>,
  ...
}
```
or use unpatched version and `#[serde(deserialize_with = "...")]`

**Comment by rimutaka** [comment]
@Mingun , I think you put me on the right path here. Looks like the docs describe this use case in https://serde.rs/enum-representations.html, which I didn't read until now. I need to dig into it some more. Will post a more detailed solution here a bit later and close the issue.

**Comment by dtolnay** [comment]
I'll close this since I believe the use case is adequately supported by the `deserialize_with` attribute and we shouldn't add a new attribute dedicated just to this.

**Comment by Caellian** [comment]
Per your convenience, here's the module with functions that try a single value and then try a Vec:

```rust
pub mod serde_one_or_many {
    use serde::{Deserialize, Deserializer, Serialize, Serializer};

    fn deserialize<'de, D, T>(de: D) -> Result<Vec<T>, D::Error>
    where
        D: Deserializer<'de>,
        T: Deserialize<'de>,
    {
        T::deserialize(de)
            .map(|it| vec![it])
            .or(Vec::<T>::deserialize(de))
    }

    fn serialize<S, T>(value: &Vec<T>, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
        T: Serialize,
    {
        if value.len() == 1 {
            value[0].serialize(serializer)
        } else {
            value.serialize(serializer)
        }
    }
}
```
