### ISSUE TITLE
Support for robust deserialization

### ISSUE THREAD

**Issue by matklad** [serde-rs/serde#1908]
Preface: I have **not** opened this issue for like ten times already (as I think this is unactionable), but I keep coming back to it, so I feel it might still be valuable to log this.

I find the need for a function with roughly this signature:

```rust
fn deserialize<T: Deserialize + Default>(s: &str) -> (T, Vec<Error>)
```

that is, I want a best-effort deserialization, where I always get *something* out of the input, but perhaps with a list of errors. 

The case where it comes up is deserialization of configs for rust-analyzer. If the config is invalid, I want to show an error to the user, but I don't want to terminate the whole process. Right now, I achieve robustness by hand-coding all the things:

https://github.com/rust-analyzer/rust-analyzer/blob/f7144dcd52c663cefc789445fe561771d935fbf0/crates/rust-analyzer/src/config.rs#L431-L519

I don't think there exists a way to make serde do what I want, but maybe I am missing some existing crates/patterns?

**Comment by dtolnay** [comment]
I think this would be valuable to explore in a different serialization library.
