### ISSUE TITLE
Maps don't consume inputs when used in flatten structs?

### ISSUE THREAD

**Issue by Mingun** [serde-rs/serde#1909]
I'm wonder of existence of that test:
https://github.com/serde-rs/serde/blob/e6f086d85edfa3bde3f4486142301962ec5f1c8c/test_suite/tests/test_annotations.rs#L1928-L1968

Why first map don't consume all keys? It seems to me that it should. Current behavior is very unintuitive

**Comment by jonasbb** [comment]
Have you read the commit message of the commit introducing the code? It explains why. 5ee2fc0562a28c51483c2d80ca50801941dc91b2

**Comment by Mingun** [comment]
No, I don't read, thanks fo pointing it. But anyway, this isn't explains why such behaviour considered as correct. Custom struct type interested only in some keys and consumes them from the input. `Map<K, V>` is a degenerate case of such struct that interested in _all_ keys. I don't understand why it shouldn't consume them.

**Comment by dtolnay** [comment]
I think my preference would be to stick with the current behavior on this.
