### ISSUE TITLE
Using `RawValue` in more than 1 enum variant causes lifetime issues

### ISSUE THREAD

**Issue by pwoolcoc** [serde-rs/serde#1911]
Here's the playground for the issue I'm seeing: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=6952a4e555ecade8cc6c19c8f34d8fd4

TLDR: Trying to use RawValue in an enum like this seems to cause lifetime issues when derive Deserialize

```
#[derive(Deserialize)]
#[serde(untagged)]
enum Foo<'a> {
    A(A<'a>),
    B(B<'a>),
}

#[derive(Deserialize)]
struct A<'a> {
  id: &'a str,
  a: &'a RawValue,
}

#[derive(Deserialize)]
struct B<'a> {
    id: &'a str,
    b: &'a RawValue
}
```

**Comment by dtolnay** [comment]
Seems like it's just missing a `serde(borrow)` attribute in Response. https://serde.rs/lifetimes.html#borrowing-data-in-a-derived-impl

```rust
#[derive(Deserialize, Debug)]
#[serde(untagged)]
enum Response<'a> {
    #[serde(borrow)]
    Success(Success<'a>),
    Error(Error<'a>),
    Event(Event<'a>),
}
```

**Comment by pwoolcoc** [comment]
Ah, ok, sorry. I'd used that on the nested structs but hadn't tried it on the enum itself. Thanks a lot!
