### ISSUE TITLE
Adjacently tagged enum with tag nested inside an object.

### ISSUE THREAD

**Issue by ryzhyk** [serde-rs/serde#1915]
With adjacently tagged enums, we can deserialize something like this:

```
{
  "tag": "Type1",
  "data": {
     "field1": 1,
     "field2": "foo"
  }
}
```

But I cannot think of a way to deserialize the following (without implementing `Deserialize` manually), where the tag is hidden inside the "metadata" object:

```
{
  "metadata": {
    "tag": "Type1",
    "id": 123456
  },
  "data": {
     "field1": 1,
     "field2": "foo"
  }
}
```

I will greatly appreciate any relevant pointers.

**Comment by dtolnay** [comment]
Please take this question to one of the resources listed in https://github.com/serde-rs/serde/tree/v1.0.135#getting-help. Sorry that no one was able to provide guidance here.
