### ISSUE TITLE
Can't compile serde_macros under nightly?

### ISSUE THREAD

**Issue by pwoolcoc** [serde-rs/serde#192]
`serde_macros` seems to disable `quasi_codegen`s default feature, which causes a compliation failure for me under rustc-1.6.0-nightly. I can checkout and compile `quasi_codegen` just fine, so I assume that the fact that `serde_macros` is not using the `with-syntex` feature of `quasi_codegen` is the signifcant difference here. I am not familiar with the `rustc_plugin` crate, do I need to do something to enable access to it?

```
~/code/serde/serde_macros $ cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling aster v0.8.0
   Compiling serde_codegen v0.6.5 (file:///home/paul/code/serde/serde_macros)
   Compiling quasi v0.3.8
   Compiling quasi_codegen v0.3.9
/home/paul/.multirust/toolchains/nightly/cargo/registry/src/github.com-88ac128001ac3a9a/quasi_codegen-0.3.9/src/lib.rs:25:1: 25:27 error: can't find crate for `rustc_plugin` [E0463]
/home/paul/.multirust/toolchains/nightly/cargo/registry/src/github.com-88ac128001ac3a9a/quasi_codegen-0.3.9/src/lib.rs:25 extern crate rustc_plugin;
                                                                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
error: aborting due to previous error
Could not compile `quasi_codegen`.

To learn more, run the command again with --verbose.
```

**Comment by killix** [comment]
it's fix by using the last version of quasi. [See the PR](https://github.com/serde-rs/serde/pull/193)

**Comment by erickt** [comment]
Yeah, this should be fixed. Want to re-open this if you are still having problems?

**Comment by pwoolcoc** [comment]
thanks @erickt !
