### ISSUE TITLE
Improve "unknown rename rule for rename_all" error with list of possible values

### ISSUE THREAD

**Issue by Mingun** [serde-rs/serde#1923]
Currently, the error not very helpful if you use the wrong rule by mistake, for example "CamelCase" instead of "PascalCase" or "camelCase"
```
error: unknown rename rule for #[serde(rename_all = "CamelCase")]
 --> term-config-editor/src/main.rs:8:22
  |
8 | #[serde(rename_all = "CamelCase")]
  |                      ^^^^^^^^^^^

```

**Comment by petar-dambovaliev** [comment]
@Mingun it seems like the commits are rolling but the issues and contributions from other people aren't noticed much.
Is this repo open for contributions?

**Comment by Mingun** [comment]
@petar-dambovaliev, small misprints, fixed by me, was merged in 1-2 days, but but more serious problems project owners, probably, prefer not to notice :(. Unfortunately, project not in good condition
