### ISSUE TITLE
How to serde array with index in name

### ISSUE THREAD

**Issue by clouds56** [serde-rs/serde#1929]
I'd like to parse a csv which has columns like
```csv
Id,Name,ChildId1,ChildName1,ChildId2,ChildName2,ChildId3,ChildName3
```
I'd like to parse it to
```rust
struct S {
  id: u32,
  name: String,
  child_id: Vec<u32>,
  child_name: Vec<String>,
}
```
Is there any suggestions?

**Comment by jonasbb** [comment]
You can relatively easily collect the ids and names into a vec of tuples like so:
```rust
struct S {
    id: u32,
    name: String,
    children: Vec<(u32, String)>,
}
```
Full example:
https://play.rust-lang.org/?gist=e6b814767837a3fd23586a8a8cbcaf3a

If you need the ids and names in separate `Vec`s than you probably need to add a conversion step. Serde is not particularly good in handling interleaved data. You can use the [`from`](https://serde.rs/container-attrs.html#from) and [`into`](https://serde.rs/container-attrs.html#into) attributes to convert between the struct with separate `Vec`s and with a vec of tuples.

**Comment by clouds56** [comment]
Thanks for kindly reply, I wonder how from/into attributes convert it to separate `Vec`s.
And I think this way could not handle extra fields in the line.
```csv
Id,Name,ChildId1,ChildName1,ChildId2,ChildName2,ChildId3,ChildName3,Comment
```
Nor could it handle csv with `.has_headers(true)`

**Comment by clouds56** [comment]
I implemented one using custom `Visitor::visit_map`, but I don't think it's as good as what I want.
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=cac01c3fcf78d7bffe95c902d58fa460
I have multiple such vector with different prefix,
```csv
Id,Name,
ChildList1Id1,ChildList1Name1,ChildList1Id2,ChildList1Name2,ChildList1Id3,ChildList1Name3,
ChildList2Id1,ChildList2Name1,ChildList2Id2,ChildList2Name2,ChildList2Id3,ChildList2Name3,
ChildList3Id1,ChildList3Name1,ChildList3Id2,ChildList3Name2,ChildList3Id3,ChildList3Name3,
Comment
```
and to type
```rust
struct S {
    id: u32,
    name: String,
    #[serde(flatten, with = "...")]
    children_list_1: Vec<(u32, String)>,
    #[serde(flatten, with = "...")]
    children_list_2: Vec<(u32, String)>,
    #[serde(flatten, with = "...")]
    children_list_3: Vec<(u32, String)>,
    comment: String,
    #[serde(flatten)]
    other: HashMap<String, Value>,
}
```

1. after it parsed `children_list_1`, the field matches prefix `ChildList1` would again passed to `children_list_2` and `others`, which causes both low performance and incorrectness, is there any workaround?
2. I have to implement `prefix` myself, I know there's a wonderful crate `serde_with`, but I cannot combine 2 `with` for different functionality, could I?

**Comment by jonasbb** [comment]
The format from your last post seem very complicated. You might need to implement [`Deserialize` by hand](https://serde.rs/impl-deserialize.html).
1. I don't think so. It is on purpose that `flatten` does not consume the values.
2. You cannot have two `with` attributes on one field. What would that even mean. But you can of course use the with-function in the implementation of another with-function.
