### ISSUE TITLE
Implement Serialize and Deserialize for std::io::Cursor

### ISSUE THREAD

**Issue by TheLostLambda** [serde-rs/serde#1930]
Hey! Sorry I couldn't put in a PR for this one right off the bat, I'm not super familiar with the inner workings of serde just yet.

I noticed that the helpful [`std::io::Cursor`](https://doc.rust-lang.org/std/io/struct.Cursor.html) struct is missing some Serde implementations. I need to implement a trait on `Cursor` that also requires `Serialize` and `Deserialize` to be implemented, but the orphan rule is obviously disallowing that.

It is possible to implement `Serialize` and `Deserialize` for a type like `Cursor` that has private fields? Or am I out of luck?

I'm very willing to do this work myself, but I need some guidance to get me started :)

Thanks!

**Comment by dtolnay** [comment]
I don't think this impl would make sense to build into serde &mdash; hopefully you were able to figure out some other approach to accommodate your use case.
