### ISSUE TITLE
Support `std::io::Read::read_vectored` and `std::io::Write::write_vectored`         

### ISSUE THREAD

**Issue by bobbobbio** [serde-rs/serde#1941]
For some background on the issue, I will explain our use case. I am working on a project that runs on Linux and does XDR serialization / deserialization. We have written our own XDR serializer and deserializer using serde. It has worked great for us so far, but we have identified there is some room for improvement concerning the handling of data pages.

Currently when dealing with data we use a `Vec<u8>` and `serialize_bytes` and `deserialize_byte_buf`. This is less than ideal for us, as I will explain.

The fastest way for us to send and receive data pages is to maintain them as (Kernel-size) pages reading data with `readv` and writing with `writev`. (My understanding is this is due to the kernel dealing in pages internally, and we prevent it from having to do its own internal copying of our data). There is also a desire to minimize the number of syscalls so thus `readv` and `writev` take vectors of pages.                                                              
                                                                                    
`std::io::Read` and `std::io::Write` already support doing vectored reads /  writes via `read_vectored` and `write_vectored`, but to take advantage of them  when doing serialization we would need serde to have some support for it as well.                                           
                                                                             
For supporting serialization, I was thinking the `Serializer` trait could  support a `serialize_bytes_vectored` call that takes a `&[IoSlice<'_>]`. Then implementors could call `write_vectored` on the underlying writer.
                                                    
For supporting deserialization, the `Deserializer` trait could have a `deserialize_bytes_vectored` which calls `visit_borrowed_bytes_vectored` that takes something like a `&'de [IoSlice<'_>]`.
                        
I wish something like `deserialize_byte_buf_vectored` could be added, but since there is not an owned vectored data type available in `std` it gets tricky, but possibly something could be done with generics.

Thought I would make this post to see if there we any existing plans, or if anyone had suggestions for what might be the best way of supporting this type of thing in serde.

**Comment by dtolnay** [comment]
I can see how this would be valuable for some types, but I don't think this case is widespread enough to justify dedicating a new Serializer method to it. Thanks anyway for the suggestions!
