### ISSUE TITLE
#[serde(default)] seems to not invoke the deserialise_with

### ISSUE THREAD

**Issue by vityafx** [serde-rs/serde#1945]
Originally coming from the [serde-aux](https://github.com/vityafx/serde-aux/issues/6) crate's issue, the `#[serde_default)]` seems to override any `#[serde(deserialize_with)]` field attribute so that it is never invoked. I'd expect the `deserialize_with` to always work as:

1. The documentation states that the `deserialize_with` is invoked when a field should be deserialized.
2. There can be thousands of fields of type `T` either with `deserialise_with` (and even different ones) and not, but if we just add `#[serde(default)]` on a struct (`#[serde(default = "path")]` also breaks the behaviour), fields, where the type is of that struct, are never deserialised with the provided `deserialize_with` implementation, what simply breaks the whole usage of the struct and this attribute.

The first question is whether it is the intended behaviour or not. If it is indeed, I think it should be mentioned in the documentation of both, `deserialize_with` and `#[serde(default)]`. If it is not intended, then this is, perhaps, a bug.

**Comment by rib** [comment]
I'm also a bit confused about the expected interaction between `#[serde(default)]` and `#[serde(deserialize_with]`.

In my case I'm trying to use `#[serde(default)]` and `#[serde(deserialize_with]` on the same field and I was expecting that the `deserialize_with` function would only be called if the field existed, but it looks like the `#[serde(default)]` is ignored and I end up with a "missing field" error.

My structure looks like this:

```rust
#[derive(Serialize, Deserialize, Default)]
pub struct StatDesc {
    pub guid: String,

    pub name: Option<String>,

    #[serde(rename = "type")]
    #[serde(default)]
    #[serde(skip_serializing_if="is_default_stat_eval_type")]
    pub eval_type: StatType,

    pub units: String,

    #[serde(deserialize_with = "deserialize_scopes_hashset_from_array")]
    pub scopes: HashSet<StatScope>,
    //pub scope: String,
    pub span: String,
    pub visible: bool,

    #[serde(default)]
    pub fifo_max_n: Option<u32>,
    #[serde(default)]
    pub fifo_max_days: Option<u32>,
    //#[serde(default)]
    //pub fifo_ref: Option<String>,

    #[serde(deserialize_with = "deserialize_stat_eq")]
    pub eq: Vec<EqData>,

    #[serde(default)]
    #[serde(deserialize_with = "deserialize_hashset_from_array")]
    pub tags: HashSet<String>,

    #[serde(default)]
    pub conditions: Option<Conditional>
}
```

I was expecting to get a `::default()` `HashSet` for `tags` in this case if no tags were given.

The docs don't suggest that these attributes conflict, but it looks like in this case they can't be used together and I should handle the optional deserialization within my `deserialize_with` function and return a `::default()` set manually?

It seems like it would be convenient if they could be combined, but if that's not possible for some reason it could help to have a warning in the docs about the conflict.

**Comment by jonasbb** [comment]
> I was expecting that the deserialize_with function would only be called if the field existed

@rib That is exactly what I see on the playground: <https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=0da84c9fa9d958eaf46bc4ca2b38e86c>
If you see other behaviour you should provide more details (serialization format, exact error message) or ideally a minimal running example like the playground link.

**Comment by rib** [comment]
Actually I'm even more confused now...

I removed the use of `'#[serde(default)]` with the tags field and updated the `deserialize_with` function to try and handle missing tags but serde is throwing an error about the missing tags before even calling the `deserialize_with` function.

This is what my struct looks like atm:
```rust
#[derive(Serialize, Deserialize, Default)]
pub struct StatDesc {
    pub guid: String,

    pub name: Option<String>,

    #[serde(rename = "type")]
    #[serde(default)]
    #[serde(skip_serializing_if="is_default_stat_eval_type")]
    pub eval_type: StatType,

    pub units: String,

    // NB: can't use default with deserialize_with
    #[serde(deserialize_with = "deserialize_scopes_hashset_from_array")]
    pub scopes: HashSet<StatScope>,
    //pub scope: String,
    pub span: String,
    pub visible: bool,

    #[serde(default)]
    pub fifo_max_n: Option<u32>,
    #[serde(default)]
    pub fifo_max_days: Option<u32>,
    //#[serde(default)]
    //pub fifo_ref: Option<String>,

    #[serde(deserialize_with = "deserialize_stat_eq")]
    pub eq: Vec<EqData>,

    // NB: can't use default with deserialize_with
    //#[serde(default = "HashSet::new")]  // I also tried this just for good measure
    #[serde(deserialize_with = "deserialize_optional_hashset_from_array")]
    pub tags: HashSet<String>,

    #[serde(default)]
    pub conditions: Option<Conditional>
}
```

And this is my deserialize_with function for tags:
```rust
pub fn deserialize_optional_hashset_from_array<'de, D>(deserializer: D) -> Result<HashSet<String>, D::Error>
where
    D: de::Deserializer<'de>,
{
    let ids: Option<Vec<String>> = match Option::deserialize(deserializer) {
        Ok(field) => field,
        Err(err) => {
            eprintln!("Failed to Option::deserialize hashset from array: {}", err);
            return Err(err);
        }
    };

    let mut id_set = HashSet::new();

    if let Some(ids) = ids {
        for id in ids {
            id_set.insert(id);
        }
    }

    Ok(id_set)
}
```
(extra explicitly error checking around Option::deserialize just to help me see where my error is being thrown from (it's not coming from here))


<details>
  <summary>This is the panic I'm getting:</summary>


```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `tags`", line: 1, column: 104460)', realfit/src/stats.rs:122:114
stack backtrace:
   0: rust_begin_unwind
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:101:14
   2: core::result::unwrap_failed
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/result.rs:1617:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/result.rs:1299:23
   4: <realfit::stats::ALL_USER_STAT_DESCRIPTIONS as core::ops::deref::Deref>::deref::__static_ref_initialize
             at ./src/stats.rs:122:64
   5: core::ops::function::FnOnce::call_once
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ops/function.rs:227:5
   6: spin::once::Once<T>::call_once
             at /home/rib/.cargo/registry/src/github.com-1ecc6299db9ec823/spin-0.5.2/src/once.rs:110:50
   7: lazy_static::lazy::Lazy<T>::get
             at /home/rib/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.4.0/src/core_lazy.rs:21:9
   8: <realfit::stats::ALL_USER_STAT_DESCRIPTIONS as core::ops::deref::Deref>::deref::__stability
             at /home/rib/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.4.0/src/lib.rs:142:21
   9: <realfit::stats::ALL_USER_STAT_DESCRIPTIONS as core::ops::deref::Deref>::deref
             at /home/rib/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.4.0/src/lib.rs:144:17
  10: realfit::stats::index_stats
             at ./src/stats.rs:75:17
  11: <realfit::stats::ALL_USER_STAT_DESCRIPTIONS_INDEX as core::ops::deref::Deref>::deref::__static_ref_initialize
             at ./src/stats.rs:123:97
  12: core::ops::function::FnOnce::call_once
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ops/function.rs:227:5
  13: spin::once::Once<T>::call_once
             at /home/rib/.cargo/registry/src/github.com-1ecc6299db9ec823/spin-0.5.2/src/once.rs:110:50
  14: lazy_static::lazy::Lazy<T>::get
             at /home/rib/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.4.0/src/core_lazy.rs:21:9
  15: <realfit::stats::ALL_USER_STAT_DESCRIPTIONS_INDEX as core::ops::deref::Deref>::deref::__stability
             at /home/rib/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.4.0/src/lib.rs:142:21
  16: <realfit::stats::ALL_USER_STAT_DESCRIPTIONS_INDEX as core::ops::deref::Deref>::deref
             at /home/rib/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.4.0/src/lib.rs:144:17
  17: stats_tool::show_user_stats::{{closure}}
             at ./src/bin/stats_tool.rs:299:18
  18: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/future/mod.rs:80:19
  19: stats_tool::main::{{closure}}
             at ./src/bin/stats_tool.rs:413:21
  20: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/future/mod.rs:80:19
  21: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /home/rib/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/park/thread.rs:263:54
  22: tokio::coop::with_budget::{{closure}}
             at /home/rib/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/coop.rs:106:9
  23: std::thread::local::LocalKey<T>::try_with
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/thread/local.rs:399:16
  24: std::thread::local::LocalKey<T>::with
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/thread/local.rs:375:9
  25: tokio::coop::with_budget
             at /home/rib/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/coop.rs:99:5
  26: tokio::coop::budget
             at /home/rib/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/coop.rs:76:5
  27: tokio::park::thread::CachedParkThread::block_on
             at /home/rib/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/park/thread.rs:263:31
  28: tokio::runtime::enter::Enter::block_on
             at /home/rib/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/runtime/enter.rs:151:13
  29: tokio::runtime::thread_pool::ThreadPool::block_on
             at /home/rib/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/runtime/thread_pool/mod.rs:77:9
  30: tokio::runtime::Runtime::block_on
             at /home/rib/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/runtime/mod.rs:463:43
  31: stats_tool::main
             at ./src/bin/stats_tool.rs:448:5
  32: core::ops::function::FnOnce::call_once
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
</details>
(backtrace itself isn't really that helpful here)

Yeah, so I'm a bit confused at the moment about what's going wrong here.

**Comment by Mingun** [comment]
> (backtrace itself isn't really that helpful here) 

You can use `cargo expand` to get the compiled code

**Comment by rib** [comment]
oh jeeze 🤦 as I was moving more and more of my code into the rust playground to create a minimal reproduction I finally realised it was something really dumb! I was fixating on the wrong "tags" field based on the error - there's also a tags field in the `Conditional` struct that hadn't occurred to me, urgh (the input json is also a somewhat large compacted file so I hadn't cross referenced with the line/column from the error since I was so convinced it must be the tags in the `StatDesc`).

So in this `Conditional` struct I was missing a `#[serde(default)]` that was needed and once I add that then it in indeed does work as I originally imagined, as as was shown by @jonasbb.

Really sorry for the noise here!

Thanks so much for going to the effort of making a minimal test @jonasbb and showing that the expected behaviour in fact did work.

Apologies!

**Comment by vityafx** [comment]
This doesn't work.

```rust
extern crate serde;
extern crate serde_aux;
extern crate serde_json;

use serde::{Deserialize, Serialize};
use serde_aux::prelude::*;

#[derive(Serialize, Deserialize, Debug, Default)]
struct MyStruct {
    #[serde(deserialize_with = "deserialize_default_from_empty_object")]
    empty_as_default: Option<MyInnerStruct>,
}

#[derive(Serialize, Deserialize, Debug, Default, PartialEq)]
#[serde(default)]
struct MyInnerStruct {
    mandatory: u64,
    optional: u64,
}

fn main() {
    let s = r#" { "empty_as_default": {} } "#;
    let a: MyStruct = serde_json::from_str(s).unwrap();
    assert_eq!(a.empty_as_default, None);
}
```
`#[serde(default)]` on the `MyInnerStruct` overrides the `#[serde(deserialize_with)]` of a field in `MyStruct`.

**Comment by jonasbb** [comment]
@rib The [serde_path_to_error](https://docs.rs/serde_path_to_error) crate can be quite helpful in finding out which field/struct is the problem, especially if the JSON is a bit unwieldy. Great that you could figure it out.

**Comment by vityafx** [comment]
I am sorry, but why did you close this? I had and still have a legitimate question that no one has been able to answer.

**Comment by dtolnay** [comment]
Regarding https://github.com/serde-rs/serde/issues/1945#issuecomment-971919575, as far as I can tell everything there is behaving as intended/documented. The deserialize_with function deserializes the incoming `{}` into `EmptyOrNot` defined as:

```rust
#[derive(Debug, Deserialize)]
#[serde(untagged)]
enum EmptyOrNot {
    NonEmpty(Option<MyInnerStruct>),
    Empty(EmptyObject),
    Null,
}
```

The meaning of `untagged` is that it'll try deserializing each field in order. Since you put `serde(default)` on MyInnerStruct, `{}` will happily deserialize as `MyInnerStruct` with all default fields, and therefore also as `Option<MyInnerStruct>`, and therefore also as the first untagged variant: `EmptyOrNot::NonEmpty(Some(MyInnerStruct { .. defaults }))`. From your `assert_eq` it sounds like you are expecting `deserialize_default_from_empty_object` to return `Ok(<Option<MyInnerStruct>>::default())`, but that only happens if you deserialized the thing to either `EmptyOrNot::Empty` or `EmptyOrNot::Null`, neither of which is the case.

**Comment by vityafx** [comment]
Thank you @dtolnay. This is so confusing sometimes, I am revisiting this chunk of code for the fifth time, always leaving it thinking I have finally understood it.
