### ISSUE TITLE
serde 1.0.119 breaks semantic versioning.

### ISSUE THREAD

**Issue by ryzhyk** [serde-rs/serde#1946]
serde release 1.0.119 changes the public interface of the serde library without advancing its minor version number.  Specifically, it no longer exposes the `export` module that used to re-export various bits of the standard library.  Unfortunately, this breaks a released version of my software.

**Comment by dtolnay** [comment]
Semver only applies to public APIs. That module is an internal implementation detail that has always been hidden and commented "not public API", so it has no bearing on semantic versioning and is not supposed to be used externally.

https://github.com/serde-rs/serde/blob/e7974312681c9c1c54f7586e86b0d7013b350a54/serde/src/lib.rs#L267-L269
