### ISSUE TITLE
Public alternative to Content and ContentRefDeserializer?

### ISSUE THREAD

**Issue by richardwhiuk** [serde-rs/serde#1947]
We are currently using Content and ContentRefDeserializer from serde::private (which has been renamed serde::__private in Serde 1.0.119) which has obviously (and intentionally) broken our usage. 😞 I can appreciate why you want to discourage public use of private APIs though ❤️ .

We are using this to decode an untagged enum in a specific fashion - we need specific behaviour depending on whether it matches one, or more than one of the enum options. Largely however, we want to match the behaviour given by serde_derive though.

As far as I can tell, this isn't exposed publicly - does anyone know the right way to do this?

An example of our usage is in https://github.com/Metaswitch/swagger-rs/blob/fdd728f0088659446215ab70ea4abcd2a91ca304/src/one_any_of.rs#L62-L73

I don't think we can move to using `serde_derive` and (thus `serde_derive::de::deserialize_untagged_enum`) which seems to be the only supported path of calling this, as we want specific behaviour which that doesn't implement.

In the short term, we'll move to `__private`, but clearly that's not a sustainable fix!

**Comment by dtolnay** [comment]
Yes, it would be reasonable for someone to maintain both of those types in a separate crate.

**Comment by richardwhiuk** [comment]
i.e. extract it from serde into a separate crate, and then both serde and my crate depend on it? I can look into doing that.

**Comment by Sytten** [comment]
Did someone extract it somewhere? I was implementing the approach suggested here https://github.com/serde-rs/serde/issues/745#issuecomment-1450072069 for versioning but I wanted to error out if the version is matching but the JSON is invalid for that version. Seems like I a visitor like this one.

**Comment by Sytten** [comment]
I ended up doing it myself.
See: https://github.com/caido/serde-content-ref
