### ISSUE TITLE
serde::export are private since 1.0.119

### ISSUE THREAD

**Issue by bachue** [serde-rs/serde#1949]
![c1235d13-15f8-4c8d-b186-fae71be4539a](https://user-images.githubusercontent.com/321962/104406010-3efc2000-5599-11eb-95bd-1828a859308c.png)

**Comment by dtolnay** [comment]
That module has never been a public API. It has always been hidden and commented "not public API":

https://github.com/serde-rs/serde/blob/e7974312681c9c1c54f7586e86b0d7013b350a54/serde/src/lib.rs#L267-L269
