### ISSUE TITLE
Equivalent of the "rename" annotation for enums?

### ISSUE THREAD

**Issue by jimmycuadra** [serde-rs/serde#195]
I have an enum that I'd like to serialize with a different format for the variants than it appears in the Rust source code. For example, a value of this enum:

``` rust
enum Example {
  FirstExample,
  SecondExample,
}
```

would be serialized as the string "first_example" or "second_example". For structs, there is the annotation `#[serde(rename="first_example")]` that can be used for a field's name, but I'm wondering if there is an equivalent for enum variants to avoid having to implement serialization and deserialization manually. I think this would only make sense for enum variants without data.

**Comment by erickt** [comment]
Unfortunately there isn't support for that yet, but it's a reasonable feature request.

**Comment by jimmycuadra** [comment]
If I were to take a shot at implementing it, would you want to reuse the "rename" annotation or would you prefer something else?

**Comment by erickt** [comment]
Dup of #182. Thanks though!
