### ISSUE TITLE
`deserialize_with` callback doesn't get called on Option<T> values, fails with an error "missing field"

### ISSUE THREAD

**Issue by vjancik** [serde-rs/serde#1951]
I reproduced the issue here: [https://github.com/vjancik/serde_bug/blob/main/src/main.rs](https://github.com/vjancik/serde_bug/blob/main/src/main.rs)

The output is:
```
Error: Error { inner: ErrorInner { kind: Custom, line: Some(0), col: 0, at: Some(0), message: "missing field `optional`", key: [] } }
```

and [line:24](https://github.com/vjancik/serde_bug/blob/main/src/main.rs#L24) never executes...

Am I using the API wrong? 
But there doesn't seem to be any other possible definition of the callback function.

**Comment by jonasbb** [comment]
By default, serde accepts a missing field if the type of the field is `Option<_>`. If you add a `with` or `deserialize_with` attribute serde will fail with the "missing field" error message, as you noticed. This is on purpose. You can change what happens on missing fields with the `default` attribute, either applied to the field in question or the whole struct.

**Comment by vjancik** [comment]
Thank you, I missed that.

So then the correct implementation for the `deserialize_with` on an `Option<T>` would be not to call `deserialize_option(...)` but `deserialize_<T>` for the corresponding "present" data type?

**Comment by jonasbb** [comment]
@vjancik Either behavior can be the correct. It really depends on what you want to achieve.
