### ISSUE TITLE
The trait `Serialize` is not implemented for `std::collections::hash_map::RandomState`

### ISSUE THREAD

**Issue by InnovativeInventor** [serde-rs/serde#1954]
Is this something I'm expected to implement myself or is this something that is supposed to be implemented in this repo?

I'm happy to provide a PR if this is the appropriate place for an implementation!

**Comment by jonasbb** [comment]
Are you sure you want to serialize the RandomState type? You can provide your own serialization logic using attributes: https://serde.rs/field-attrs.html#with

**Comment by dtolnay** [comment]
See https://doc.rust-lang.org/std/collections/hash_map/struct.RandomState.html. There is no API on RandomState that exposes its complete internal state for serialization, nor any API that would construct a new RandomState matching a provided internal state for deserialization.
