### ISSUE TITLE
What if serde uses bytes::Bytes in Deserializer?

### ISSUE THREAD

**Issue by akiradeveloper** [serde-rs/serde#1956]
Now owned buffer is typed as `Vec<u8>` but I think this limits the flexibility of serde and it will be more flexible if it is replaced with `bytes::Bytes`.

```rust
    fn visit_byte_buf<E>(self, v: Vec<u8>) -> Result<Self::Value, E>
    where
        E: Error,
    {
        self.visit_bytes(&v)
    }
```

My goal is zero-copy decoding. I know serde supports it by lifetime but the referenced buffer is copied after all if the application is using bytes::Bytes.

For example, suppose we have such structure.

```rust
#[derive(Deserialize)]
struct Command<'a> {
  seq_id: u64,
  payload: &'a [u8]
}
```

We can decode this structure in zero-copy but application usually wants to localize this lifetime. In other words, application don't want to spread this local lifetime to other part of the application.

```rust
#[derive(Deserialize)]
struct Command {
  seq_id: u64
  payload: Bytes
}
```

If the structure looks like this, the lifetime issue is gone.

Bytes is a very convenient structure. It is reference counted and we don't need to care about the lifetime to share the instance or fragments.

If serde uses Bytes, we can use Bytes as the source of the deserialization and make a owned buffer in zero-copy.

**Comment by dtolnay** [comment]
The bytes crate has had 3 major version changes in the time that serde has had 0. The Bytes type is nice but it would not be worth being on serde 4.0 right now just for that. The number of crates that use `serde` is way higher than the number of crates that use `bytes`, which makes breaking changes vastly more disruptive for us. I think it wouldn't be wise to couple our public API to theirs.
