### ISSUE TITLE
#[serde(flatten)] error behavior is different to normal one

### ISSUE THREAD

**Issue by edwin0cheng** [serde-rs/serde#1957]
Example: 

```rust
use serde::Deserialize;
#[derive(Deserialize, Debug)]
#[serde(deny_unknown_fields)]
struct B {
    s: String,
}
#[derive(Deserialize, Debug)]
#[serde(deny_unknown_fields)]
struct A {
    #[serde(flatten)]
    b: B
}
fn main() {
    let json = r#"{"non_exists" : "", "s": ""}"#;
    if let Err(err) = serde_json::from_str::<B>(json) {
        println!("B=> {:?}", err);
    };
    if let Err(err) = serde_json::from_str::<A>(json) {
        println!("A=> {:?}", err);
    };
}
```

Output:

```txt
B=> Error("unknown field `non_exists`, expected `s`", line: 1, column: 14)
A=> Error("unknown field `non_exists`", line: 1, column: 29)
```

I would expect both errors should be equal, but it is different. Maybe I miss something important here ?

[Edit] A better example and output

**Comment by jonasbb** [comment]
Is there any reason why you assume that the error message should be identical in both cases? Both seem appropriate and serde can only report one error at a time.

Also be careful with combining `deny_unknown_field` with `flatten`. [They don't](https://github.com/serde-rs/serde/issues/1547#issuecomment-705744778) [mix well](https://github.com/serde-rs/serde/issues/1600).

**Comment by edwin0cheng** [comment]
@jonasbb I updated the example and output , it should be better to reflect the problem.

My question is , why 'A' is missing the "expected `s`" part ?

**Comment by jonasbb** [comment]
@edwin0cheng Maybe check how the macros expand using `cargo expand` (also available in the playground). I would guess the message get's emitted by `A`, which has no expected fields, thus instead of showing an empty list that part is removed.

**Comment by edwin0cheng** [comment]
Okay, I think the problem here is the error handling code is different between two structs.

`A` is using the following path, which didn't handle that `expected` part.

https://github.com/serde-rs/serde/blob/b0c99ed761d638f2ca2f0437522e6c35ad254d93/serde_derive/src/de.rs#L2519-L2530

Maybe we could collect the __values in there to report the error as how 'B' one do. ?

**Comment by dtolnay** [comment]
I think this is all right as currently implemented.

If you do manage to come up with a PR that makes identical error messages in this situation, I would be interested to take a look.
