### ISSUE TITLE
Question - deriving a hash

### ISSUE THREAD

**Issue by avnerbarr** [serde-rs/serde#1975]
I need my structs to be hashable. they don't mutate once created so it could be possible to store the hash on creation

My struct looks like this
```
#[derive(Clone, Debug, Deserialize)]
pub struct Predicate {
    note: Option<String>,
    arguments: Option<HashMap<String, Value>>,
    value: Value,
}
```

I tried to add `Hash` directive , but `Value` doesn't implement `Hash`

tried to implement myself 

`impl Hash for Value {`

but getting error 

``` impl Hash for Value {
    | ^^^^^^^^^^^^^^-----
    | |             |
    | |             `Value` is not defined in the current crate
    | impl doesn't use only types from inside the current crate
```

so 2 possible solutions would suffice for me

1. calculate and store the hash on deserializization and save as a field 
2. Implement `Hash` on `Value` - but not sure it is possible to do outside of serde.

option 1 could work for me (store during deserialize)

I saw in the documentation https://serde.rs/field-attrs.html#deserialize_with

`#[serde(deserialize_with = "path")]`

but didn't see any example how it can be done

Thanks

**Comment by andrewhickman** [comment]
Note that `HashMap` doesn't implement `Hash` either, because it doesn't have a stable iteration order

**Comment by dtolnay** [comment]
Please take this question to one of the resources listed in https://github.com/serde-rs/serde/tree/v1.0.135#getting-help. Sorry that no one was able to provide guidance here.
