### ISSUE TITLE
It doesn't seem to be possible to fill in struct defaults from a runtime value

### ISSUE THREAD

**Issue by pfmoore** [serde-rs/serde#1986]
I'm trying to read in a struct from a file. But I want to allow the user to omit one or more fields from the struct, and have them filled in with default values. The obvious way to do that is with `#[serde(default = "path")]`. However, the default I want to use is computed dynamically, in another part of the program, and isn't available to be hard-coded into a static function located at "path" in the way that the attribute requires.

Here's some example code that illustrates what I'm trying to do.

```rust
use serde::Deserialize;
use serde_json;

#[derive(Deserialize)]
struct MyStruct {
    field1: String,
    field2: String,
}

fn main() -> () {
    let defval = MyStruct { field1: "foo".into(), field2: "bar".into() };
    // I want to fill in missing values from defval
    let s: MyStruct = serde_json::from_str_with_default("{\"field1\": \"baz\"}", &defval).unwrap();
    println!("{}", s.field1); // should print "baz"
    println!("{}", s.field2); // should print "bar"
}
```

The only way I have found to achieve this is to have two parallel versions of the struct, one with all fields wrapped in `Option`, which is what I deserialise into, and then I copy to the other version which requires all fields, filling in the omitted values from the default.

Something like a `from_str_with_default` function would avoid all of that extra complexity.

Apologies if I've missed something that already exists, or an explanation of why this sort of pattern is not supported. I've searched for examples or workarounds and haven't been able to find anything.

**Comment by dtolnay** [comment]
I'm glad you got it working! That approach sounds fine to me.

If you want `from_str_with_default`, something like that could be implemented in a separate crate. Probably as:

```rust
let mut de = serde_json::Deserializer::from_str(" { ... } ");
let s: MyStruct = deserialize_with_defaults(&mut de, &defval)?;
```

**Comment by pfmoore** [comment]
I'm confused. Are you saying that it's expected that I should need to duplicate my structure definitions? That seems like a pretty bad violation of "don't repeat yourself" and likely to lead to errors if the two versions don't get kept in line.

If you mean implementing `str_with_default` seems reasonable, the problem is that I don't know how to do this (again, without having 2 versions of the struct).

Can you clarify, please?

**Comment by dtolnay** [comment]
I recommend taking this to any of the resources listed in https://github.com/serde-rs/serde/tree/v1.0.135#getting-help to help you out. Sketch of the most basic implementation would be:

```rust
fn deserialize_with_defaults<'de, D, T>(de: D, defaults: T) -> Result<T, D::Error>
where
    D: Deserializer<'de>,
    T: Serialize + DeserializeOwned,
{
    let new_input = serde_json::Value::deserialize(de)?;
    let old_values = serde_json::to_value(defaults)?;
    let combined = merge_json_value(new_input, old_values);
    return T::deserialize(combined);
}
```

Folks can help you generalize this to not involve serde_json::Value, and make it streaming like the serde_transcode crate to avoid buffering/merging the objects in memory.

**Comment by pfmoore** [comment]
Thanks, I see what you're saying now, and your sketch gives me the information I need to ask the questions intelligently. Much appreciated.
