### ISSUE TITLE
[Question] Enum with optional Tag

### ISSUE THREAD

**Issue by hn-sl** [serde-rs/serde#1988]
I need to deserializes  json string into enum with a variant that only inferred when tag is missing.

For example, 
```rust 
enum Foo {
    A(i32), // tag A
    B(f32), // tag B
    C(String), // tag C
    NoTag(String), // tag is missing
}
```

- ```{"type":"A","value":1}``` => ```Foo::A(1)```
- ```{"type":"A","value":2.5}``` =>  Error(2.5 is not type of i32)
- ```{"type":"A","value": "not integer"}``` =>  Error("not integer" is not type of i32)
- ```{"type":"B","value":2.5}``` => ```Foo::B(2.5)```
- ```{"type":"invalid tag","value":"aa"}``` => Error(unknown tag value)
-  ```{"value":"aa"}``` => ```Foo::NoTag("aa")```
-  ```{"value": 1}``` => Error(1 is not type of string)

Is there any easy and efficient way to achieve this ? I knows about ```untagged``` but I think it is inappropriate here because things like```{"type":"A","value": "aa" }``` or ```{"type":"invalid tag","value": "aa" }```  should be treated as error, not ```Foo::NoTag("aa")``` nor ```Foo::C("aa")```. 

I think it would be nice if this can be done like below.
```rust
#[derive(serde::Serialize, serde::Deserialize, Debug)]
#[serde(tag = "type", content = "value")]
enum Foo {
    A(i32),
    B(f32),
    C(String)
    #[serde(notagg)]
    NoTag(String),
}
```

**Comment by dtolnay** [comment]
Please take this question to one of the resources listed in https://github.com/serde-rs/serde/tree/v1.0.135#getting-help. Sorry that no one was able to provide guidance here.
