### ISSUE TITLE
Serde derive fails to compile if the `serde` crate is renamed

### ISSUE THREAD

**Issue by NZSmartie** [serde-rs/serde#1990]
[The fix](https://serde.rs/container-attrs.html#crate):
```
#[serde(crate = "serde_cr")] 
```

Short story:
I want to have my package expose a `serde` feature; however I cannot just use the `serde = { optional = true }` as I also need to enable the `serde` feature on the `uuid` package. Cargo makes this harder than necessary because you can't name a feature the same as a dependency. The [work around I've found from this blog post](https://blog.turbo.fish/cargo-features/) is to rename the dependency and and set up an alias as needed. 

Unfortunately renaming the serde crate breaks the derive macro:

```console
$ cargo +nightly --version
cargo 1.52.0-nightly (bf5a5d5e5 2021-02-18)
$ cargo +nightly tree
serde-bug v0.1.0 (/home/nzsmartie/Projects/serde-bug)
└── serde v1.0.123
    └── serde_derive v1.0.123 (proc-macro)
        ├── proc-macro2 v1.0.24
        │   └── unicode-xid v0.2.1
        ├── quote v1.0.9
        │   └── proc-macro2 v1.0.24 (*)
        └── syn v1.0.60
            ├── proc-macro2 v1.0.24 (*)
            ├── quote v1.0.9 (*)
            └── unicode-xid v0.2.1
$  RUSTFLAGS="-Z macro-backtrace" cargo +nightly build
error[E0463]: can't find crate for `serde`
  --> src/lib.rs:5:21
   |
5  | #[derive(Serialize, Deserialize)]
   |                     ^^^^^^^^^^^
   |                     |
   |                     can't find crate
   |                     in this macro invocation
   |
  ::: /home/nzsmartie/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_derive-1.0.123/src/lib.rs:89:1
   |
89 | pub fn derive_deserialize(input: TokenStream) -> TokenStream {
   | ------------------------------------------------------------ in this expansion of `#[derive(Deserialize)]`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: could not compile `serde-bug`
```

I have a minimal reproducible example:

`Cargo.toml`:
```
[package]
name = "serde-bug"
version = "0.1.0"
edition = "2018"

[dependencies]
serde_cr = { package = "serde", version="1.0.123", features = ["derive"] }
```

`src/lib.rs`:
```
extern crate serde_cr as serde;
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize)]
pub struct Test {
    field: u8
}
```

**Comment by taiki-e** [comment]
I think you have to use `#[serde(crate = "...")]`: https://serde.rs/container-attrs.html#crate

**Comment by NZSmartie** [comment]
Yep, sorry ... just found that too. I'll try and write up a guide on how to set the `serde` feature up with extra libraries so some future traveller won't have to do the trial and error all over again

**Comment by Stargateur** [comment]
why [`$crate` ](https://veykril.github.io/tlborm/decl-macros/minutiae/hygiene.html#crate)can't be used in serde side ?

**Comment by Mingun** [comment]
Macro hygiene applied only to declarative macros (`macro_rules!`), procedural macros not hygienic. AFAIK there is no analogous of `$crate` for procedural macros
