### ISSUE TITLE
serde triggers clippy::use_self lint on recent clippy

### ISSUE THREAD

**Issue by imp** [serde-rs/serde#1993]
On recent nightly (2021-02-27) serde upsets clippy when `clippy::use_self` lint [is activated](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=8bcd4e9adcc43b71004a32bdd99a8a8c). Apparently this lint got some [attention recently](https://github.com/rust-lang/rust-clippy/issues/3909), so it might be related

**Comment by dtolnay** [comment]
Could you file this against Clippy? I believe that lint should not be triggering inside of macro generated code.

**Comment by MarijnS95** [comment]
It seems like this has resurfaced in Rust 1.61: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=f735206a9a21f1ec7d55730e2d6c6a17
