### ISSUE TITLE
Serialize unit variant in untagged enum as {}

### ISSUE THREAD

**Issue by TonalidadeHidrica** [serde-rs/serde#1994]
Suppose I had the following enum:
```rust
use serde::{Serialize, Deserialize};

#[derive(Serialize, Deserialize)]
#[serde(untagged)]
enum Enum {
  Unit,
  Values {
    x: u32,
    y: u32,
  },
}

fn main() -> anyhow::Result<()> {
  println!("{}", serde_json::to_string_pretty(&Enum::Unit)?);
  println!("{}", serde_json::to_string_pretty(&Enum::Values { x: 33, y: 4 })?);
  Ok(())
}
```
It outputs ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=0423aee320f99aff12d63ccebcd874bd)):
```
null
{
  "x": 33,
  "y": 4
}
```

Is there a convenient way to obtain `{}` instead of `null` for the first conversion?

**Comment by jonasbb** [comment]
You can customize the serialization logic for individual fields using the [with attribute](https://serde.rs/field-attrs.html#with).
[Example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=21b1fb21a8586d1b479599d91bb17123)

**Comment by TonalidadeHidrica** [comment]
I got it, thanks!
