### ISSUE TITLE
Enable `integer128` feature for emscripten targets

### ISSUE THREAD

**Issue by vmarkushin** [serde-rs/serde#1995]
It seems like 128-bits integers support has been added to the emscripten compiler (https://github.com/emscripten-core/emscripten-fastcomp/issues/169), does it mean we can enable it back [here](https://github.com/serde-rs/serde/blob/master/serde/build.rs#L58)?

**Comment by extrawurst** [comment]
I am interested in landing this. I wonder how to enable this *feature* ? it does not seem to relate to a cargo feature flag?
