### ISSUE TITLE
[Feature request]: Field must be value X

### ISSUE THREAD

**Issue by rakshith-ravi** [serde-rs/serde#2006]
Hey, it would be very nice to have a attribute that forces a field to be of a certain value, and will fail to deserialize if it is not of the give value. This is mostly used for correctness of code.

For example, lets say I have an API that returns a response with the following response. In case of a success response, it returns:
```json
{
    "success": true,
}
```
And in case of an error, it returns:
```json
{
    "success": false,
    "error": "errorString",
    "message": "messageString"
}
```

In this case, I'd like to have an enum that represents the API response as follows:
```rust
#[derive(Serialize, Deserailize)]
#[serde(untagged)]
#[serde(rename_all = "camelCase")]
pub enum ApiResponse {
    Success {
        success: bool,
    },
    Error {
        success: bool,
        error: String,
        message: String,
    }
}
```

In the given case, it will always deserialize to `ApiResponse::Success`, even if the `"success"` field in the json is false. While the order can be changed allowing the error to be parsed first, yes, in more complicated situations, this might get very tricky to handle, and would be cumbersome for the developer to play out the deserialization scenarios in their head before writing the code.

What would be nice is to have a attribute that enforces a value, which can be a constant value as well. Like so:

```rust
#[derive(Serialize, Deserailize)]
#[serde(untagged)]
#[serde(rename_all = "camelCase")]
pub enum ApiResponse {
    Success {
        #[serde(must_be = true)]
        success: bool,
    },
    Error {
        #[serde(must_be = false)]
        success: bool,
        error: String,
        message: String,
    }
}
```

In the above example, the `#[serde(must_be = true)]` attribute ensures that the right enum variant is matched, based on what the value of the field is.

Would love to hear more thoughts on the same and see how we can implement something like this

**Comment by ColinTimBarndt** [comment]
Another approach would be to allow the `rename` attribute to take numbers and booleans as an input if `tag` is used on the enum:

```rust
#[derive(Debug, Serialize, Deserialize)]
#[serde(tag = "success")]
pub enum ApiResponse {
    #[serde(rename = true)]
    Success,
    #[serde(rename = false)]
    Error {
        error: String,
        message: String,
    }
}
```

This would no longer require the `success` field.

Here is a working syntax [example] if "success" was a string:
```rust
#[derive(Debug, Serialize, Deserialize)]
#[serde(tag = "success")]
pub enum ApiResponse {
    #[serde(rename = "true")]
    Success,
    #[serde(rename = "false")]
    Error {
        error: String,
        message: String,
    }
}

const JSON: &str = r#"{
    "success": "true",
    "error": "Some error",
    "message": "Some message"
}"#;

fn main() {
    println!("{:#?}", serde_json::from_str::<ApiResponse>(JSON));
}
```

[example]: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=e430fd76bf80207d7e2e32c8456e2ae6

**Comment by rakshith-ravi** [comment]
Oh this seems nice. Does this way of implementing it allow us to use multiple `#[serde(must_be = <value>)]` and enforce values for multiple fields? Or is this only for one field?

**Comment by ColinTimBarndt** [comment]
It inself only works with one possible value, because the value is used to index the enum. But I think that it is possible to let multiple values point to one enum variant by using `#[serde(alias = "foo")]`.

**Comment by rakshith-ravi** [comment]
Ahh, right. Maybe it's just me, but it feels like a hack, and feels like the programmer needs to wrap their head around a lot of these concepts to figure out how to make it work as expected (in all honesty, I still don't understand how your `alias` thingy would work). I'd still prefer to have a `#[serde(must_be = value)]` option for making it simpler.

Considering this issue has been open for a couple of months now, I'm assuming people are not able to put in the hours to implement this. How can I help? Can I implement this? If so, where do I start?

**Comment by ColinTimBarndt** [comment]
Wait, I think there is a very simple solution to your problem. You could create an enum for each "must_be" field, where each variant is one possible field value. You can then implement a deserializer for the enum, where each variant represents one "must_be" value for the fielt. This way, the deserializer would return a well human-readable error and the struct does not need to store all possible values for a field and only the possible ones, also probably allowing for better compile-time optimization.

```rust
struct MustBeTrue;
struct MustBeFalse;
struct MustBeI32<const N: i32>;
enum MustBeFooBar {Foo, Bar}
```

You could extend the serde derive macro if you want to. I have never needed to implemented one yet, but you could look into the code of the `Deserialize` macro [here](https://github.com/serde-rs/serde/blob/master/serde_derive/src/de.rs). The `deserialize_enum` function might be interesting, because `must_be` restricts the possible values of a field, which basically is an enum.

**Comment by dtolnay** [comment]
> ```
> #[derive(Serialize, Deserialize)]
> #[serde(untagged)]
> pub enum ApiResponse {
>     Success {
>         #[serde(must_be = true)]
>         success: bool,
>     },
>     Error {
>         #[serde(must_be = false)]
>         success: bool,
>         message: String,
>     },
> }
> ```

I made a crate for this: https://github.com/dtolnay/monostate. I don't think this is a thing that needs to be built into serde_derive so I'll close your issue.

```rust
#[derive(Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApiResponse {
    Success {
        success: MustBe!(true),
    },
    Error {
        success: MustBe!(false),
        message: String,
    },
}
```

**Comment by rakshith-ravi** [comment]
Thanks for that @dtolnay. But I am curious though, why wouldn't this be a part of serde_derive?
