### ISSUE TITLE
Support externally tagged structs

### ISSUE THREAD

**Issue by autarch** [serde-rs/serde#2007]
Here's an example of what I'm looking for.

I have some JSON something like this:

```
{
   "Root":{
      "first":{
         "Foo":{
            "size":42,
            "color":"blue"
         }
      },
      "second":{
         "Bar":{
            "mood":"indigo",
            "car":"Super"
         }
      },
      "actions":[
         {
            "Run":{
               "speed":84
            }
         },
         {
            "Sleep":{
               "hours":8
            }
         }
      ]
   }
}
```

What I'd like is to deserialize this to some structs like this:

```rust
#[derive(Debug, Deserialize)]
struct Root {
    first: Foo,
    second: Option<Bar>,
    actions: Vec<Action>,
}

#[derive(Debug, Deserialize)]
struct Foo {
    size: i8,
    color: String,
}

#[derive(Debug, Deserialize)]
struct Bar {
    mood: String,
    car: String,
}

#[derive(Debug, Deserialize)]
enum Action {
    Run { speed: i64 },
    Sleep { hours: i8 },
}
```

However, I can't do that with serde right now. Instead, I need to introduce a bunch of wrapper enums to make this work. So I end up with this:

```rust
#[derive(Debug, Deserialize)]
enum RootWrapper {
    Root(Root),
}

#[derive(Debug, Deserialize)]
struct Root {
    first: FooWrapper,
    second: Option<BarWrapper>,
    actions: Vec<Action>,
}

#[derive(Debug, Deserialize)]
enum FooWrapper {
    Foo(Foo),
}

#[derive(Debug, Deserialize)]
struct Foo {
    size: i8,
    color: String,
}

#[derive(Debug, Deserialize)]
enum BarWrapper {
    Bar(Bar),
}

#[derive(Debug, Deserialize)]
struct Bar {
    mood: String,
    car: String,
}

#[derive(Debug, Deserialize)]
enum Action {
    Run { speed: i64 },
    Sleep { hours: i8 },
}
```

This then requires lot of destructuring to pull the structs out of their wrappers. But in cases where the wrapper only has one variant, it'd be really nice to not need the wrapper at all.

So some sort of "externally tagged struct" support would be great. I don't really know exactly what this might look like in terms of implementing. Maybe a `#[serde(tagged_struct)]` attribute on the struct? But I'm not sure if it makes sense for the attribute to be on the struct, the field that references the struct, or maybe offer both?

It's worth noting that in my example there's no field pointing to a `Root` struct, so that's why I think there needs to be a way to attach this to a struct as well as a field.

I wrote some blog posts about this topic in relation to a project I'm working on. In that case I'm parsing much more complex JSON structures representing a Postgres SQL AST, but the same principal holds. The blog posts are:

* [Writing a Postgres SQL Pretty Printer in Rust: Part 1.5](https://blog.urth.org/2021/03/21/writing-a-postgres-sql-pretty-printer-in-rust-part-1-5/)
* [Writing a Postgres SQL Pretty Printer in Rust: Part 1](https://blog.urth.org/2021/03/14/writing-a-postgres-sql-pretty-printer-in-rust-part-1/)

Part 1.5 goes into more detail on this issue, so it'd probably make sense to read that one first if you're reading either.

**Comment by pickfire** [comment]
I don't see why we can't reuse externally tagged enum which serde already supports. Like `#[serde(tag = "Root")]`, is there some other reasons it is only for enum?

By the way, here is a good example of externally tagged enum.

https://github.com/FlorianUekermann/rustls-acme/blob/bd7f8e2c921eb2e10fa076d6e2cce0831c1623a7/src/acme.rs#L170-L184

**Comment by dtolnay** [comment]
I'd prefer not to build this into the serde_derive crate, but anyone should feel free to make their own `Deserialize` derive macro implementing this representation.
