### ISSUE TITLE
Serialize enum as either tagged/untagged?

### ISSUE THREAD

**Issue by vedantroy** [serde-rs/serde#2009]
Rather than mandating that when an enum is serialized, it will/won't serialize the tags by using `#[serde(untagged)]` is there a way to choose at serialization/deserialization time wether the input should be serialized with tags / the output should be read assuming/not-assuming tags?

**Comment by ColinTimBarndt** [comment]
You could implement a wrapping struct that has a bool field for wether it is serialized tagged or not. In the serializer, you could then only serialize the enum (un-)tagged:

```rust
struct MaybeTagged {
  inner: MyEnum,
  tagged: bool,
}
```

**Comment by dtolnay** [comment]
I would prefer not to build anything for this into this crate.

Depending on what granularity you want to control the representation, you could either wrap individual serializable enums as suggested above, or wrap the whole `Serializer` to make it serialize *all* tagged enums in the whole input in untagged form instead. Something like:

```rust
let value = /*thing to serialize*/;
let mut ser = serde_json::Serializer::new(...);
value.serialize(AllEnumsUntagged(&mut ser))?;
```
