### ISSUE TITLE
Serde not serializing string with " correctly

### ISSUE THREAD

**Issue by OutOfBoundCats** [serde-rs/serde#2011]
Hello all
I have  a code like below like  where the type of scope is String in struct defination

       let mut string1 = r#""https://www.googleapis.com/auth/cloud-platform","#.to_string();`
       let mut string2 = r#""https://www.googleapis.com/auth/datastore","#;`
       let mut string3 = r#""https://www.googleapis.com/auth/devstorage.read_write","#;`
       let mut string4 = r#""https://www.googleapis.com/auth/firebase","#;`
       let mut string5 = r#""https://www.googleapis.com/auth/identitytoolkit","#;`
       let mut string6 = r#""https://www.googleapis.com/auth/userinfo.emai","#;`
       let stre = string1 + string2 + string3 + string4 + string5 + string6;`
        

       let myclaim = _firebase_common::Claims {
            iss: self.fireabse_config.client_email.clone(),
            scope: stre,
            aud: "https://oauth2.googleapis.com/token".to_string(),
            exp: 1617548751,
            iat: 1617547546,
        };`
But when i serialise it like below
`println!(
            "the claims json {}",
            &serde_json::to_string(&myclaim).unwrap()
        );`

this is what i get in terminal
`the claims json {"iss":"firebase-adminsdk-7ec4b@loggernow-204f2.iam.gserviceaccount.com","scope":"\"https://www.googleapis.com/auth/cloud-platform\",\"https://www.googleapis.com/auth/datastore\",\"https://www.googleapis.com/auth/devstorage.read_write\",\"https://www.googleapis.com/auth/firebase\",\"https://www.googleapis.com/auth/identitytoolkit\",\"https://www.googleapis.com/auth/userinfo.emai\",","aud":"https://oauth2.googleapis.com/token","exp":1617548751,"iat":1617547546}`

there are this weird `"\` before a string and at end of it i am unsure what should be done so i get something like below
`the claims json {"iss":"firebase-adminsdk-7ec4b@loggernow-204f2.iam.gserviceaccount.com","scope":"https://www.googleapis.com/auth/cloud-platform","https://www.googleapis.com/auth/datastore","https://www.googleapis.com/auth/devstorage.read_write","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/identitytoolkit","https://www.googleapis.com/auth/userinfo.emai",","aud":"https://oauth2.googleapis.com/token","exp":1617548751,"iat":1617547546}`

I dont know much about serde can you please help here.

thanks in advance

**Comment by jonasbb** [comment]
The output you get seems correct. You write `r#""`, which means that each string starts with a literal `"`. A `"` needs to be encoded while generating JSON and its encoded form is `\"`. The result you expect is not valid JSON.

**Comment by OutOfBoundCats** [comment]
okay understood thanks for replying.
