### ISSUE TITLE
New enum representation combining externally and adjacently tagged

### ISSUE THREAD

**Issue by moogstuart** [serde-rs/serde#2013]
It would be great to have support for the following enum representation which is kind of a combination of externally and adjacently tagged e.g. externally_with_adjacent (terrible name but I can't think of a good one at the moment).

```
#[derive(Serialize, Deserialize)]
#[serde(externally_with_adjacent="message")]
enum Message {
    Request { id: String, method: String, params: Params },
    Response { id: String, result: Value },
}
```

Would be represented as:-

```
{
"Message: "Request",
"Request": {"id": "...", "method": "...", "params": {...}}
}
```

Although the Request part is duplicated in the adjacent tag and the first part of the nested keys this allows for receiving json with just the message type and no extra fields (for this example that might not make sense but for other it could be useful.

```
{
"Message: "Request",
}
```

**Comment by l4l** [comment]
Stumbled into the same issue. @dtolnay, may I ask you for the help with this issue? I'm interested in implementing it.

**Comment by dtolnay** [comment]
I'd prefer not to build this into serde_derive, but anyone should feel free to write a `Serialize`/`Deserialize` derive macro that implements this representation. That shouldn't require changes in the serde crate.
