### ISSUE TITLE
Build script fails to resolve syntex::Registry

### ISSUE THREAD

**Issue by jimmycuadra** [serde-rs/serde#202]
This started happening in a crate that uses Serde with code generation.

* Stable Rust 1.5
* serde_codegen 0.6.7
* syntex 0.24.0 (0.25.0 exhibits the same behavior)

Output from `cargo build` 

```
   Compiling serde_codegen v0.6.7
/Users/user/.cargo/registry/src/github.com-88ac128001ac3a9a/serde_codegen-0.6.7/build.rs:12:33: 12:46 error: mismatched types:
 expected `&mut syntex::Registry`,
    found `&mut inner::syntex::Registry`
(expected struct `syntex::Registry`,
    found struct `inner::syntex::Registry`) [E0308]
/Users/user/.cargo/registry/src/github.com-88ac128001ac3a9a/serde_codegen-0.6.7/build.rs:12         quasi_codegen::register(&mut registry);
                                                                                                                             ^~~~~~~~~~~~~
/Users/user/.cargo/registry/src/github.com-88ac128001ac3a9a/serde_codegen-0.6.7/build.rs:12:33: 12:46 help: run `rustc --explain E0308` to see a detailed explanation
error: aborting due to previous error
Could not compile `serde_codegen`.
```

**Comment by jimmycuadra** [comment]
Apparently this is happening due to rust-lang/cargo#/2064.

**Comment by JohnHeitmann** [comment]
As a workaround you can lock quasi to 0.3.11, aster to 0.9.2, syntex to 0.24.0, and syntex_syntax to 0.24.0.

I think the problem here might be a bit simpler than that cargo bug. I think here it's just breaking API changes that weren't versioned perfectly.

**Comment by erickt** [comment]
@JohnHeitmann: I did do a release yesterday which should have fixed this issue on stable rust. nightly rust support is currently broken due to https://github.com/rust-lang/rust/issues/30713.

I was thinking about this issue yesterday, and yeah, I think I did make a semver violation here. While I didn't have to modify any quasi code when I updated it to 0.3.12, I did do a major change on a public dependency. Along with https://github.com/rust-lang/cargo/issues/2064, this means I ended up with two instances of syntex, which caused this confusing error message. I'll be more careful next time.

**Comment by jmesmon** [comment]
I'm still seeing this today (2 different versions of syntex), but might be related to another cargo issue: https://github.com/rust-lang/cargo/issues/2277

**Comment by erickt** [comment]
This should be fixed now. Please reopen if you still have problems.

**Comment by jimmycuadra** [comment]
This is happening to me on nightly now, not sure if it's the same issue or not:

```
/Users/user/.cargo/registry/src/github.com-88ac128001ac3a9a/quasi_macros-0.4.0/src/lib.rs:19:29: 19:32 error: mismatched types:
 expected `&mut syntex::Registry`,
    found `&mut rustc_plugin::registry::Registry<'_>`
(expected struct `syntex::Registry`,
    found struct `rustc_plugin::registry::Registry`) [E0308]
/Users/user/.cargo/registry/src/github.com-88ac128001ac3a9a/quasi_macros-0.4.0/src/lib.rs:19     quasi_codegen::register(reg);
                                                                                                                          ^~~
/Users/user/.cargo/registry/src/github.com-88ac128001ac3a9a/quasi_macros-0.4.0/src/lib.rs:19:29: 19:32 help: run `rustc --explain E0308` to see a detailed explanation
error: aborting due to previous error
Build failed, waiting for other jobs to finish...
Could not compile `quasi_macros`.
```

In Cargo.toml:

``` toml
[dependencies]
serde = "0.6.11"
serde_json = "0.6.0"
serde_macros = "0.6.11"
```

```
$ rustc -V
rustc 1.8.0-nightly (9a07087bc 2016-01-30)
```

**Comment by jimmycuadra** [comment]
Disregard that last comment. I discovered the issue: I was depending on a crate that uses Serde but only supported building Rust stable/serde_codegen. Modifying that dependency to build on both stable and nightly did the trick. I'm not totally clear why, but it seems that if syntex is added to the build at all, quasi_macros will choke.

**Comment by jimmycuadra** [comment]
Can this be reopened? I'm having the same issue again: failing to build on nightly because a dependency somehow introduced syntex (and so far I'm not spotting how to get rid of it.) Seems like this is a problem more people might run into and perhaps there's a way to deal with it at the library level.

**Comment by erickt** [comment]
@jimmycuadra: Any chance you could push up your work somewhere in a branch so I could look into it?

**Comment by jimmycuadra** [comment]
It's already public, actually! The main project is https://github.com/rusoto/rusoto. Check out the feature-rust-codegen branch. You'll also need https://github.com/rusoto/botocore_parser checked out to a sibling directory (there's a path dependency.) Thanks for reopening.

**Comment by indiv0** [comment]
I'm getting this too. Is there a way to work around this?

**Comment by SkylerLipthay** [comment]
Is there actually anything that can be done to solve this? This seems like a very unfortunately cargo edge case. I'm stuck in syntex hell because my project's dependencies use serde_codegen instead of serde_macros. :sob:

**Comment by Manicqin** [comment]
Happens to me too :(
Is the textnonce's commit suppose to fix the problem?

**Comment by dtolnay** [comment]
Check out [this forum topic](https://users.rust-lang.org/t/here-is-how-to-avoid-being-broken-by-syntex-updates/6189?u=dtolnay) for how to fix this permanently by using `serde_codegen::expand`. It is supported as of Serde 0.7.9.
