### ISSUE TITLE
Pass struct length to `serialize_map` in case of `#[serde(flatten)]` 

### ISSUE THREAD

**Issue by thomaseizinger** [serde-rs/serde#2020]
I am developing a serde-module for a binary format where I always need to know the number of fields of a struct.

This works well as long as I don't use `#[serde(flatten)]`. With flatten, the code generated by `derive(Serialize)` passes `None` to `serialize_map`.

I guess this sort of makes sense. The struct that is being flattened is completely opaque to serde apart from it needing to implement `Serialize`. Still, it would be nice if we didn't lose the information about how many fields we are about to serialize just because they are being flattened.

Would it make sense to extend the the interface of `Serialize` with some sort of "size-hint"?

**Comment by dtolnay** [comment]
I can see how building a size hint into `Serialize` would be helpful for some formats, but I don't feel that this is a widespread enough use case to justify expanding the API for this. Thanks anyway for the suggestion!
