### ISSUE TITLE
can support auto Parse String to Number when Deserialize json to struct?

### ISSUE THREAD

**Issue by adminSxs** [serde-rs/serde#2023]
example:

```rust
struct Info{
  name: String,
  age: u16
}


let info_str=r#"
   {
        "name":"info",
        "age": 12
   }
";

use info_str Deserialize  to Info struct will success, but when age as a String such "12" will panic `value: Error("invalid type: string )`


```

**Comment by jonasbb** [comment]
Are you looking for something like this [`DisplayFromStr`](https://docs.rs/serde_with/1.8.1/serde_with/struct.DisplayFromStr.html#examples) type? There are other crates which implement support for such conversions too, e.g., `serde_str`.

**Comment by adminSxs** [comment]
> Are you looking for something like this [`DisplayFromStr`](https://docs.rs/serde_with/1.8.1/serde_with/struct.DisplayFromStr.html#examples) type? There are other crates which implement support for such conversions too, e.g., `serde_str`.

thanks your help very much

**Comment by ColinTimBarndt** [comment]
@adminSxs Has your question been answered? You can close this Issue if that's the case
