### ISSUE TITLE
Support typed arrays for zero-copy parsing

### ISSUE THREAD

**Issue by ColinTimBarndt** [serde-rs/serde#2028]
I am implementing a binary format which supports binary `i32` and `i64` arrays. Currently, serde only supports typed `u8` arrays by default because byte-order does not matter. The binary format I am implementing comes in a BE and LE variation, so depending on the target hardware, zero-copying is possible with these arrays.

Currently, zero-copying these kinds of arrays is not supported by Serde, because they have to be (de-)serialized as a "List", which Serde treats as untyped.

I am working on my own serde-fork which has `visit_array_i32`/`i64` and `deserialize_array_i32`/`i64` functions with their `borrowed` and `buf` variations in the Visitor and Deserializer traits with serialization work in progress. My fork supports all variations that are supported for byte arrays (borrowed/buffered/owned) and can be made compatible with "normal" Serde without any issues. I am willing to share my code when I'm done, if it helps.

**Comment by dtolnay** [comment]
I think I'd prefer not to build anything for this into the serde crate, but I'm glad you got it working! Thanks anyway for the suggestion.
