### ISSUE TITLE
The serde version should be 1.1+

### ISSUE THREAD

**Issue by kornelski** [serde-rs/serde#2029]
Since 1.0.0, serde has added some new features to its API, e.g. https://github.com/serde-rs/serde/commit/c162d518668de8363af67f6ffc1686ebec6de993

This affects crates that claim to be compatible with `serde = "1.0"`, but actually aren't, e.g. `serde_stacker` won't work with the `serde` version it asks for in its `[dependencies]`:

> method `visit_i128` is not a member of trait `de::Visitor` 
> method `skip_field` is not a member of trait `ser::SerializeStruct`
> no method named `is_human_readable` found for type `S` in the current scope

**Comment by dtolnay** [comment]
This involves somebody adjudicating whether every change is or is not a "feature", which I have not been interested in.

The serde_stacker issue seems mostly unrelated. That crate can declare a dependency on whatever serde version contains the things it needs, independent of how the serde releases are numbered.
