### ISSUE TITLE
serde_codegen – generated Serialize code for tuple variants and struct variants call incorrect Serializer methods

### ISSUE THREAD

**Issue by jnicholls** [serde-rs/serde#203]
The generated code for Serialize trait should:

1. For tuple variants, the generated Visitor should for each element call visit_tuple_variant_elt, but is currently calling visit_tuple_struct_elt.
2. For struct variants, the generated Visitor should for each field call visit_struct_variant_elt, but is currently calling visit_struct_elt.

This could be a copy/paste error, I don't know.  I can try to dig into the code, but I just wanted to create an issue for this so it's tracked.

**Comment by erickt** [comment]
This will be fixed by #238.

**Comment by jnicholls** [comment]
Awesome!

**Comment by erickt** [comment]
This was implemented in #238!
