### ISSUE TITLE
serde and network packets

### ISSUE THREAD

**Issue by jbaublitz** [serde-rs/serde#2030]
A while back, I tried to write a serde `Deserializer` and now that I have a lot more experience with Rust, I wanted to talk about a specific kind of use case that I'm not sure there's a good solution for in serde.

I've looked at the JSON and bincode serde implementations and so far what I see is that the JSON implementation is able to pretty easily look at the serialized data to deserialize it appropriately. bincode is binary data so it doesn't have the same flexibility to guess the type from the data itself from what I can see in the documentation, but it does have one notable difference from the format I'm trying to work with: the length of variably sized types like strings and byte buffers appears to be encoded directly before the actual data itself.

Personally, I would love to migrate over to serde because it would be great to be able to interchangeably serialize to JSON and my binary representation for example, but I've bumped into some of the same problems that I did last time and wanted to see if we can work to find a solution now that I can explain it in a little bit more depth.

### The problem
My binary format is packet based and has a lot of nested headers. Sometimes these headers encode a length and other times they do not. They all really need to be represented as structs. If there is a length associated with the packet header, it is always at the beginning of the packet header and the payload is at the end. I'm not really finding a way to associate the length as the first field with the size of the byte buffer, string, or other data type that's deserialized as the payload or last field.

### My understanding of serde's model
I've been doing a lot of digging into the architecture, and from what I've seen so far, it appears that the `Deserialize` implementation drives the `Deserializer` to expect the correct types for deserializers that need this, the `Deserializer` is responsible for actually reading and parsing the data and passing it to the visitor, and the `Visitor` is responsible for taking that data presented to the visitor from the `Deserializer` (whether this is a struct handler or just a simple `u32`) and generating the final representation expected by the `Deserialize` method. Because visitors are used across `Deserializer` implementations, they should not be involved in actually parsing any data. Rather, it is on the `Deserializer` to handle the parsing and provide data structures that implement traits like `SeqAccess` to further handle deserialization from the visitors.

### Generic deserializer problem
I've tried `DeserializeSeed` as this appears to be the way to implement stateful deserialization but the problem here is that it's implemented for a generic deserializer. My byte buffer for the entire packet needs to be stored internally in the deserializer and therefore, if I pass a length into `DeserializeSeed`, I have no way to set that length in my deserializer for the next payload deserialization. I can't access the byte buffer to slice it appropriately, I can't call any methods on it to set the length as they won't be recognized given trait bounds on the type parameter, and this generally doesn't seem to be the use case for `DeserializeSeed`. I've also considered the `deserialize_with` field attribute, but this obviously has the same generic deserializer problem. Even if I could provide a simple boolean for each sub-header that's being deserialized, it would be pretty trivial to make that `true` if the first field was a length and `false` if not, but because the deserializer is provided at the top level when `Deserialize::deserialize` is called and doesn't really seem to be accessible at lower levels of struct parsing, I'm not entirely sure how I would go about providing that on a per-struct basis.

#### What it boils down to
I considered what would be most helpful here and I think the fundamental problem is that serde deserializes all structs using the same method on the deserializer. To internally handle the length currently, I can't keep the length in its original `u32` format because there is no way to differentiate between a `u32` that has no side effect on the deserializer and a `u32` that is a length and does have a side effect on the deserializer. Wrapping the length in a newtype struct also seems challenging because I could potentially special case the newtype struct handler to recognize a type name associated with lengths, but this also seems fraught because it involves string comparison for determining the type which I generally would prefer to avoid and I wouldn't know what the internal type of the length is from the newtype struct handler alone (`u16` or `u32`) as it only accepts a name and visitor. Perhaps this could be worked around by passing a `PhantomData` marker to the visitor in the deserialize method, but I'm still not sure that this is the recommended way to do so. What are your thoughts? Is there a way to pass additional information to the `Deserializer` struct to provide more context for the parsing step that I'm missing?

**Comment by dtolnay** [comment]
Sorry that no one was able to provide guidance here! If you are still interested in talking about this use case, please take this to one of the resources listed in https://github.com/serde-rs/serde/tree/v1.0.135#getting-help.
