### ISSUE TITLE
Another solution for the example [Deserialize either a string or a struct](https://serde.rs/string-or-struct.html)

### ISSUE THREAD

**Issue by QuarticCat** [serde-rs/serde#2031]
Recently I encountered a similar problem that I want to provide a simple form of some configuration. However, this official example ([Deserialize either a string or a struct](https://serde.rs/string-or-struct.html)) cannot help me. The reason is that the workaround is written for the struct that uses `Build` rather than modifying the `deserialize` method of `Build`, which will cause these problems:

- All places that use `Build` should add a `#[serde(deserialize_with = "string_or_struct")]`.
- It is a bit troublesome to write tests for the deserialization of `Build`.
- If the field type is `HashMap<String, Build>` rather than `Build`, things will become very annoying.

Or we can wrap `Build` with a flattened new type so that the problems above can be solved. But that makes using `Build` instances annoying.

I find another solution that results in much less code and it solves all the problems above:

```rust
#[derive(Debug, Deserialize)]
struct Service {
    build: Build,
}

#[derive(Debug)]
struct Build {
    context: String,
    dockerfile: Option<String>,
    args: Map<String, String>,
}

impl<'de> Deserialize<'de> for Build {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        // write the definition of `Build` again and add serde features to it
        #[derive(Debug, Deserialize)]
        #[serde(remote = "Build")]
        struct This {
            context: String,
            dockerfile: Option<String>,
            #[serde(default)]
            args: Map<String, String>,
        }

        #[derive(Deserialize)]
        #[serde(untagged)]
        enum Helper {
            Simple(String),
            #[serde(with = "This")]
            Complex(Build),
        }

        Ok(match Helper::deserialize(deserializer)? {
            Helper::Simple(context) => Self {
                context,
                dockerfile: None,
                args: Map::new(),
            },
            Helper::Complex(this) => this,
        })
    }
}
```

[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=576bcea526c31b13a821240a5b02eacd)

There might be a little performance loss here. I haven't benchmarked it yet.

Furthermore, I think serde can provide derives like `from_xxx = "some_function"` to automatically generate implementations like this.

**Comment by dtolnay** [comment]
Thanks for sharing!
