### ISSUE TITLE
Deserialize enum tags via regex (or alternative for dynamic many-to-one enum tags)

### ISSUE THREAD

**Issue by blagovestb2c2** [serde-rs/serde#2032]
Hello people,

I am trying to Deserialize a json structure that comes in a slightly unfortunate format for serde as it currently comes out of the box.

```json
{
"tag": "part1.part2.part3",
"data": {...}
}
```

Now, this looks deceptively like it would easily be handled by the adjacently tagged enum representation. However, my use case is one in which the format of "data" depends solely on "part1" (say) whereas part2 and part3 could be anything, dynamic (that only makes sense in the context). We tried ignoring the tag and using an untagged enum for "data" only, but fields overlap between variants and sometimes we get the wrong deserialization. In other words, we need to inspect "tag" as well :( 

At least to my knowledge of serde, deserializing something like this is not possible without going the custom impl route.  But since the issue seems somewhat generalizable, I thought of suggesting an improvement to serde so everyone could benefit.

At its core my problem is that I am dealing with an enum structure whose tags are many-to-one in relation to the content format. So I am proposing that there be a way to specify this mapping somehow using serde field attributes. 

For example, allowing tags to be deserialized via a regex, could allow me to capture "part1" only and have serde do its usual thing deserializing enums. Alternatively, allowing a custom mapping function to be specified would allow me to transform "part1.part2.part3" into the usable "part1" upon which the rest of the deserialization process could take place.

Do you think something like this would be reasonable? It is deserialization-specific (I guess a serialization extension could be based on providing a custom function that could choose which one, out of many, tags one should produce upon serialization).

**Comment by dtolnay** [comment]
I would prefer not to build this into serde_derive, but someone could provide a different `Deserialize` derive macro in a different crate which could be more fully featured and handle this case.
