### ISSUE TITLE
Improve bind with fsm in mind

### ISSUE THREAD

**Issue by irevoire** [serde-rs/serde#2033]
Hello, today I was working with a struct with multiples states, and I wanted to Deserialize my struct **only** in a specific (Unchecked) state.
Here is the code I ended up with:
```rust
#[derive(Deserialize)]
struct A;
#[derive(Serialize)]
struct B;

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(bound(serialize = "T: Serialize", deserialize = "T: Deserialize<'static>"))]
pub struct Fsm<T> {
    pub field: String,
    #[serde(skip)]
    pub _kind: PhantomData<T>,
}

impl Fsm<A> {
    pub fn into_b(self) -> Fsm<B> {
        Fsm { field: self.field, _kind: PhantomData::default() }
    }
}

fn main() {
    let data = r#"{ "field": "hello" }"#;
    let fsm: Fsm<A> = serde_json::from_str(data).unwrap();

    // does not compile
    // let fsm: Fsm<B> = serde_json::from_str(data).unwrap();
    // let res = serde_json::to_string_pretty(&fsm);

    let res = serde_json::to_string_pretty(&fsm.into_b()).unwrap();
    println!("{}", &res);
}
```

It's quite good, but I thought we could improve the `bind` keyword for these specific use cases.
Being able to bind to structures instead of traits would be one solution:
```rust
#[serde(bound(serialize = "T = A ", deserialize = "T = B"))]
```
The good part is that we don't need to derive `Serialize` or `Deserialize` on the states.
But the main problem here is that it does not follow the type system we know of, and we should be able to provide multiple accepted state in the `serialize` or `deserialize`.

Anyway, thanks for the lib. I was still able to achieve what I wanted in a minimal number of lines :grinning:

**Comment by dtolnay** [comment]
I'd prefer not to build that into this crate, but thanks anyway for the suggestion!
