### ISSUE TITLE
Is it possible to serialize a sequence of maps/sequences without knowing maps/sequences upfront?

### ISSUE THREAD

**Issue by WaffleLapkin** [serde-rs/serde#2036]
I want to make a proxy serializer, that serializes enums as arrays (this is needed for compatibility with another language/library). E.g. I want to serialize `Enum::Struct { a, b }` as `["Struct", {"a": a, "b": b}]`. But I've got a problem: 
1. To serialize `["Struct", ..]` in `serialize_struct_variant` I need to call `.serialize_seq()` on the inner serializer
2. Then I need to return something implementing `SerializeStructVariant`
3. `SerializeStructVariant` requires serializing field-by-field, so I can't just call `.serialize_element(map)` on the inner serializer's `SerializeSeq` (I don't have the map upfront)
4. `SerializeStructVariant::serialize_field` takes a `&T` where both the lifetime and the type are generic which means that I can't save the value into a map

Is there any way to get around these limitations?

Also, it seems that the problem is equivalent to **un**flattening sequence, i.e. serializing `[a, b, c, d, e]` as e.g. `[[a, b], [c, d], [e]]`.

**Comment by jonasbb** [comment]
Is it a hard requirement that this needs to be implemented as a proxy serializer? Turning an enum into `["Struct", {"a": a, "b": b}]` is quite possible with a custom `Serialize` implementation or alternatively using the `serialize_with`/`with` attributes.

**Comment by WaffleLapkin** [comment]
That isn't a hard requirement, but it would be a lot more convenient since I wouldn't need to think about every occurrence of an enum.

**Comment by dtolnay** [comment]
Previous work on this topic: #768. It ended up not being reasonably implementable at the time.

I think I would recommend directly using format-specific APIs when this style of serialization is a requirement. For example in the case of JSON, serializing a sequence of maps/sequences without knowing the maps/sequences up front is possible by directly interacting with serde_json::ser::Formatter.
