### ISSUE TITLE
Really Stuck On Writing a custom DeSerializer

### ISSUE THREAD

**Issue by gluax** [serde-rs/serde#2041]
I have no clue how to deserialize the inner type of Enum Variant from a u32 to a char. See below.
![image](https://user-images.githubusercontent.com/16431709/121966307-416acd80-cd23-11eb-999c-02899a5119fb.png)
Results in `thread 'main' panicked at 'Unable to parse json.: Error("invalid type: sequence, expected A scalar enum containing a u32.", line: 43, column: 42)'`

The documentation for this kind of stuff really sucks, with no examples of how stuff like this works and it's easy to get confused.

**Comment by jonasbb** [comment]
You probably meant to attach the `deserialize_with` on the `char` not on the `Scalar` variant.

```rust
fn char_from_u32<'de, D: Deserializer<'de>>(deserializer: D) -> Result<char, D::Error> {
    let int = u32::deserialize(deserializer)?;
    char::from_u32(int).ok_or(serde::de::Error::custom("Failed to convert u32 to scalar char."))
}

#[derive(Debug, Deserialize, Serialize)]
enum Char {
    Scalar(
        #[serde(deserialize_with = "char_from_u32")] char
    ),
    NonScalar(u32),
}

serde_json::from_value::<Char>(serde_json::json!(
    {"Scalar":97}
))?
```

You only need to keep the `Visitor` if you need the custom expecting message. You should also call `deserialize_u32` instead of `*_u64` since you only implement `visit_u32`.

**Comment by gluax** [comment]
Bless thanks for the help!
