### ISSUE TITLE
Can a struct be serialized while async filling a member queue?

### ISSUE THREAD

**Issue by tmplt** [serde-rs/serde#2042]
I have
```rust
struct DataSet { ... }

struct  DataSets {
    collection_start: TimeStamp,
    data: VecDeque<DataSet>
}
```
that I wish to serialize. During run-time, `DataSets::data` will continuously be appended to asyncronously. At the same time I want to serialize the all `DataSet`s that are available and then wait for more. A signal will denote that no more `DataSet`s will be appended so that serialization can end.

Can serde help me here? From [the examples](https://serde.rs/stream-array.html) something akin to the reverse is possible, so I need to implement some custom serializer logic. My present use-case can be simplifed to serializing `Timestamp, DataSet, DataSet, ...` without the `DataSets` wrapper, but requirements may change, so I'm investigating viability.

**Comment by jonasbb** [comment]
> During run-time, DataSets::data will continuously be appended to asyncronously. At the same time I want to serialize the all DataSets that are available and then wait for more.

If I understand you correctly, you want to have a `VecDeque` which you append to and read from at the same time? This is not possible with Rusts borrowing rules.

With a custom `Serialize` implementation it should be possible to create the same serialized for as your `DataSets` but while consuming `DataSet` from a channel or similar, allowing them to be generated concurrently.

Creating a sequence like `Timestamp, DataSet, DataSet, ...` is relatively simple. You can pass the `seq` around and serialize the `DataSet`s one by one.

```rust
use serde::ser::Serializer;
use serde::ser::SerializeSeq;

let mut buffer = Vec::new();
{
    let mut ser = serde_json::Serializer::new(&mut buffer);
    let mut seq = ser.serialize_seq(None)?;
    seq.serialize_element(&1)?;
    seq.serialize_element(&"Foo")?;
    seq.serialize_element(&"Bar")?;
    seq.end()?;
}
std::str::from_utf8(&buffer)
```

**Comment by tmplt** [comment]
I was not aware of `serialize_seq`, which is much easier solution. Thanks.

**Comment by tmplt** [comment]
I've been experimenting around with `serialize_seq` for a bit. I'd like to abstract all I/O setup in some `Foo::new() -> Self` function:
```rust
struct Foo {
    seq: serde_json::ser::Compound<....>,
}

impl Foo {
    pub fn new() -> Self {
        Foo { seq: { ... }.serialize_seq(None) }
    }

    pub fn serialize(data: u8) {
        self.seq.serialize_element(data);
    }
}

impl Drop for Foo {
    fn drop(&mut self) {
        self.seq.end();
    }
}
```
But this requires me to store the underlying `serde_json::Serializer` somewhere and I'm not allowed to do that inside `Foo` itself.  Any ideas on how to manage this?

**Comment by dtolnay** [comment]
Sorry that no one was able to provide guidance on your last question. If this is still an issue, please take the question to one of the resources listed in https://github.com/serde-rs/serde/tree/v1.0.135#getting-help.
