### ISSUE TITLE
Deserialize untagged enums using integer representation?

### ISSUE THREAD

**Issue by vedantroy** [serde-rs/serde#2046]
I've been working on fixing enums in https://github.com/3Hren/msgpack-rust/issues/225. By default, msgpack-rust serializes enums to integers (specifically maps with a single K/V pair where the key = integer, value = associated data or nil).

I've adopted the serde_json approach to serializing/deserializing enums for msgpack-rust. Enums variants w/o associated data are now serialized as integers.

This works fine, except when deserializing untagged enums. The code ends up going here:
https://github.com/serde-rs/serde/blob/3805c037a8805e7f4559a140bbd228e13feac391/serde/src/private/de.rs#L1366

This method seems to only support deserializing enums as strings / maps with a single K/V pair. Was wondering why this is the case. Mostly I need to decide whether to tell the msgpack-rust maintainers that they should remove support for serializing enums to single integers.

**Comment by dtolnay** [comment]
This seems like a consequence of #1183, so I'll close in favor of tracking it over there.
