### ISSUE TITLE
Serialize specific fields which is decided dynamically

### ISSUE THREAD

**Issue by sagarnayak** [serde-rs/serde#2058]
Let's say I have a struct

	struct User{
		name: String,
		balance: f64,
		email: String,
		email_masked: String,
	}

And I have two kinds of user

    enum Users{
		admin,
		merchant,
	}

I want to serialize all the fields in user when I am sending any response to the user which is an `admin`. but when the user is `merchant` i want to skip the `balance and email` fields.

I read the [field attributes](https://serde.rs/field-attrs.html#skip) but don't really get anything that fits this case.

Any suggestions.

**Comment by dtolnay** [comment]
Please take this question to one of the resources listed in https://github.com/serde-rs/serde/tree/v1.0.135#getting-help. Sorry that no one was able to provide guidance here.
