### ISSUE TITLE
rustc panics when adding #[derive(Deserialize)] to pub type declaration

### ISSUE THREAD

**Issue by dikaiosune** [serde-rs/serde#206]
I already reported this to the compiler repo (rust-lang/rust#30861), but it was pointed out that it was possibly an issue in serde_macros.

Basically, I accidentally added a `#[derive(Deserialize)]` to a `pub type _ = _;` statement (instead of the struct I was intending to annotate), and instead of reporting an error the compiler panicked. I won't duplicate the entire bug report here since it's linked above, but I certainly can if that's needed.

**Comment by erickt** [comment]
I ought to be using a different error reporting mechanism here. I forgot all about fixing it. I'll swap them out.
