### ISSUE TITLE
Leading underscores are discarded when using `#[serde(rename_all = "camelCase")]`

### ISSUE THREAD

**Issue by Lindenk** [serde-rs/serde#2061]
## Problem
When using `#[serde(rename_all = "camelCase")]` on a struct, leading underscores on field names are ignored. This makes parsing data with fields with leading underscores (specifically json) significantly more time consuming and error prone as every field would need to be `#[serde(rename = "...")]` individually.

## [Example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a47e95e8c283ecd8e37b1fca25a67085)

```rust
use serde::{Serialize, Deserialize}; // 1.0.126
use serde_json; // 1.0.64

#[derive(Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
struct Foo {
    _foo_bar : i32
}

fn main() {
    let json = r#"{ "_fooBar": 42 }"#;
    let _ : Foo = serde_json::from_str(json).unwrap(); // no `fooBar` field found, whereas 
                                                       // it should be named `_fooBar` 
}
```

## Possible solutions

- Have serde leave leading underscores when converting to camelCase
- Provide `serde(prefix = "...")` and `serde(suffix = "...")` container attributes

**Comment by jonasbb** [comment]
Renaming to camel case removes all underscores. Why should leading ones be treated differently? A general prefixing/suffixing mechanism is out of scope for serde (see this issue https://github.com/serde-rs/serde/pull/1794) but can be provided by other crates.

**Comment by Lindenk** [comment]
Leading underscores indicate private or self contained fields rather than word seperatation, therefore I'd argue trimming leading underscores when converting from snake to camel case is incorrect behavior.

**Comment by jonasbb** [comment]
This works, but I wouldn't really recommend it, since it uses undocumented implementation details:

```rust
#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
#[serde(remote = "Self")]
struct Foo {
    _foo_bar_ : i32
}

impl Serialize for Foo {
    fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        Foo::serialize(self, serde_with::with_prefix::WithPrefix {
            delegate: serializer,
            prefix: "_",
        })
    }
}

serde_json::to_string(&Foo {_foo_bar_: 123})? // => {"_fooBar":123}
```

A proc-macro, which applies `rename` attributes to all fields, as mentioned in #1794, is probably the better option, unless the prefix needs to be determined during runtime.

**Comment by Lindenk** [comment]
Thanks for the idea, but that seems like a significant amount of overhead for such a basic operation. I'll take a look a `serde_with`, although it seems like a hacky workaround to solve a problem that probably should've been solved cleanly in serde proper. Anyway it looks like other snake to camel case libraries trim leading underscores so I suppose that's standard if unintuitive. I'll go ahead and close the issue. Thanks for the help
