### ISSUE TITLE
 Error("invalid type: string \"[...]\", expected a borrowed string" error when deserializing a struct that's serialized with serde

### ISSUE THREAD

**Issue by DRG-developer** [serde-rs/serde#2065]
It seems to only occur on items with \\\" in it. I find this really weird, because I have a response from a website, in JSON, i then deserialize that into struct A, i then save that struct A to a file, and then later i open that file, and when deserializing that file back into struct A i get the error:  Error("invalid type: string \"{Something with \\\" in it]\", expected a borrowed string". struct A is just ```
`Struct A {
    name: String
}
`

**Comment by Mingun** [comment]
Are you sure that you don't use the `&str` instead of `String` of your struct definition? Because your example works: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=2b8951c1b1b59a11a269a73c72684d62

**Comment by DRG-developer** [comment]
The mistake was that I can't read, i deserialized the struct into a hasmap where i used &str, issue closed.
root cause found: stupid me.

**Comment by danzek** [comment]
Here we are a couple years later. Same issue. Same cause. This chain was helpful to me.

**Comment by Tails** [comment]
My custom Deserialize was doing a match{} on map.next_key() (or something similar) and it implicitly coerced the key to &str instead of String. Doing map.next_key::<String>() was the trick for me. Thanks you guys!

**Comment by rben01** [comment]
> My custom Deserialize was doing a match{} on map.next_key() (or something similar) and it implicitly coerced the key to &str instead of String. Doing map.next_key::() was the trick for me. Thanks you guys!

To add onto this: the serde docs provide a good solution (https://serde.rs/deserialize-struct.html, Ctrl-F `visit_map`). It's to deserialize the keys into an enum which itself is deserialized from a `&str` (by matching against `&'static str`). By matching the map’s keys directly against `&'static str`, you inadvertently tell Rust to infer the return type of `map.next_key()?` to be `&'static str`, which will naturally fail (you cannot deserialize into a `&'static str`).

**Comment by Mingun** [comment]
> (you cannot deserialize into a `&'static str`).

To be clear: this is totally possible. If you have source in `&'static str` and you deserialize it using deserializer that supports borrowing, you may get result in `&'static str`. `'static` does not mean that reference should point to constant data. [`leak`](https://doc.rust-lang.org/std/string/struct.String.html#method.leak) methods may return you `'static` lifetime.

**Comment by jonnyso** [comment]
Ouch, what a runtime surprise this was, thank you @Tails !
