### ISSUE TITLE
Serde json fails to deserialize vector of enum values with serde(untagged) if one of enum values is a scalar

### ISSUE THREAD

**Issue by Mekanik** [serde-rs/serde#2066]
Serde fails to deserialize vector of `untagged` enum values when possible enum options are structs and scalars.
Serialization works. Deserialization for single values works, but not for vector.

`Err value: Error("data did not match any variant of untagged enum Foo", line: 0, column: 0)'`

Full repro - [Playground][1]

```rust
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug)]
#[serde(untagged)]
enum Foo {
    A(usize),
    B{x: u8, y: u8 },
}

fn main() {
    let foo_a = Foo::A(10); // Works
    let foo_b = Foo::B {x: 1, y: 2}; // Works
    let vector = vec![foo_a, foo_b]; // Vector doesn't work
    
    let serialized = serde_json::to_string(&vector).unwrap();
    println!("serialized = {}", serialized); // serialized = [10,{"x":1,"y":2}]

    let deserialized: Foo = serde_json::from_str(&serialized).unwrap();
    println!("deserialized = {:?}", deserialized); // Fails with "did not match any variant"
}
```

  [1]: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b1cad182f9301e2c99ae38098cfff69e

**Comment by jonasbb** [comment]
You are serializing a `Vec<Foo>` but deserializing only a `Foo`. The code works if you change it to `let deserialized: Vec<Foo>`.

**Comment by Mekanik** [comment]
Jonas, thanks for pointing to a mistake. I created a bad repro example and that lead me to a wrong conclusion. The original deserialization error I have in my code is related
to an already opened bug [Deserializing a RawValue inside an untagged enum always fails](https://github.com/serde-rs/json/issues/497).
Closing, as it's not a bug/no repro.
