### ISSUE TITLE
For serde-yaml, is there a way to get a struct to serialise in an inline format?

### ISSUE THREAD

**Issue by dwalter0** [serde-rs/serde#2067]
I'm trying to serialise a vector into an inline yaml list. When I serialize, it needs to look like this:
`Attribute: [value, value, value]`
but it looks like this:
```
 Attribute:
    -value
    -value
    -value
```

I tried implementing the serialize trait and the result was to produce something like this
`Attribute: "[value, value, value]"`.
The quotes make it invalid.

Here is my custom serializer:
```
impl Serialize for Router {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
            S: serde::Serializer {
        let mut output = String::new();
        output += "[";
        output += &self.vlans.join(", ");
        output += "]";    
        let mut state = serializer.serialize_struct("Router",1)?;
        state.serialize_field("vlans", &output);
        state.end()

    }
}
```

**Comment by dtolnay** [comment]
Please take this question to one of the resources listed in https://github.com/serde-rs/serde/tree/v1.0.135#getting-help. Sorry that no one was able to provide guidance here.
