### ISSUE TITLE
Prefix name of flattened fields

### ISSUE THREAD

**Issue by tristanCadet** [serde-rs/serde#2071]
**Usecase**

I want to serialize a struct containing other structs to CSV, which is why I use flatten.
However some of these structs have fields with the same name, which make the output unpractical to read.
I would like to prefix the flattened fields to be able to distinguish them.

**Minimal example**

```rust
use serde::Serialize;

fn main() {
    let json = serde_json::to_string(&Message::default()).unwrap();
    println!("{}", json);
}

#[derive(Serialize, Default)]
struct Message {
    content: String,
    #[serde(flatten)] // put new feature here
    from: Person,
    #[serde(flatten)] // put new feature here
    to: Person,
}

#[derive(Serialize, Default)]
struct Person {
    name: String,
}
```

**Output**
```json
{"content":"","name":"","name":""}
```

**Wanted Output example**
```json
{"content":"","from.name":"","to.name":""}
```

Maybe this could be implemented as an option on the flatten macro, or as an extension on the renaming macro ?

**Comment by jonasbb** [comment]
This is very similar to the request in https://github.com/serde-rs/serde/issues/970. The [suggested solution](https://github.com/serde-rs/serde/issues/970#issuecomment-395205409) is to use the [`serde_with::with_prefix!`](https://docs.rs/serde_with/1.9.4/serde_with/macro.with_prefix.html) macro.

```rust
serde_with::with_prefix!(prefix_from "from.");
serde_with::with_prefix!(prefix_to "to.");

#[derive(Serialize, Default)]
struct Message {
    content: String,
    #[serde(flatten, with = "prefix_from")]
    from: Person,
    #[serde(flatten, with = "prefix_to")]
    to: Person,
}
```

However, IIRC, the `csv` crate does not support structs which use `flatten` internally.

**Comment by dtolnay** [comment]
I'd prefer not to build anything for this into this crate, so for now the suggestion is to use `serde_with`'s macro for this.
