### ISSUE TITLE
Implement Serialize/Deserialize for Infallible

### ISSUE THREAD

**Issue by TehPers** [serde-rs/serde#2073]
Suppose I have [an API where a value can only be `null`](https://discord.com/developers/docs/topics/permissions#role-object-role-tags-structure). In Rust, the semantic way to represent `null` is via `Option::<T>::None`, but it's unclear what `T` should be because the value can never be `Some(value)`, only `None`.

I think it would be useful to be able to use `Option<Infallible>` (and possibly `Option<!>`) to represent these values. One way to do this is to implement `Serialize` directly for `Infallible`:

```rs
impl Serialize for Infallible {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        match *self {}
    }
}
```

Since an instance of `Infallible` should *theoretically* never be serialized, this would allow `Option<Infallible>` to serialize as `None`.

It would also be nice to be able to deserialize `Option<Infallible>`:

```rs
impl<'de> Deserialize<'de> for Infallible {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        Err(de::Error::custom("value can never be constructed"))
    }
}
```

As a temporary solution, it's possible to define an empty enum and implement these traits on it.

**Comment by dtolnay** [comment]
For types with only one possible value, a unit struct seems more appropriate than something involving `Infallible`. In formats like JSON a unit struct will serialize to `null`, which sounds like is what you want.

```rust
#[derive(Serialize)]
struct Null;
```

**Comment by zakarumych** [comment]
Implementing `Serialize` and `Deserialize` for `Infallible` is desired for generic enums.

Imagine enum like this.
```rust
#[derive(Serialize, Deserialize)]
enum Foo<T> {
  A,
  B,
  C(T),
}
```

it may be desirable to serialize and deserialize `Foo<Infallible>`.
Without it, users have to define ad-hoc
```rust
#[derive(Serialize, Deserialize)]
enum Never {}
```
and use `Foo<Never>`

**Comment by arctic-hen7** [comment]
I'm working on a system that accepts user state in the form of a `Result<T, E>` (which can't be changed due to reactivity constraints), and, although most of the time there will be an error type, some cases will use `Infallible`. It would be extremely helpful to have this implementation!

**Comment by andyleiserson** [comment]
I was able to use `#[serde(skip, default = "Option::default")]` to make a struct having an `Option<E>` field serializable for `E = Infallible`. However in my case I'm either instantiating the struct in a context where serialization is not required, or I am instantiating it with `E = Infallible`. If it were necessary to actually serialize the field for other choices of `E`, something more complicated would be necessary.
