### ISSUE TITLE
support for fully qualified names?

### ISSUE THREAD

**Issue by JeremyRubin** [serde-rs/serde#2074]
One thing that has come up in some of my work is that the rename options do not have a way to automatically include e.g. the full module path. Example:

```
struct A;
mod B {
struct A;
}
```

In this example the struct name for both B::A and A would be the same, unless it's somehow overriden. This becomes more of an issue when working with structs from e.g. different crates.

This is related to previously discussed issues:

- https://github.com/serde-rs/serde/issues/1964
- https://github.com/serde-rs/serde/issues/1636

but much more specific since it's just a case of needing crate/module unique identifiers.

**Comment by dtolnay** [comment]
I'd prefer not to build something dedicated to this into this crate, but either of the issues you linked is still a possibility so I'll close in favor of those.

**Comment by JeremyRubin** [comment]
I think where this is unique is in applying the rename to the base struct name, rather than a field-level rename (which doesn't work nicely for things like Vec<A>).
