### ISSUE TITLE
Help getting the signatures to work when using `serde(with = "some_module")`

### ISSUE THREAD

**Issue by zohaad** [serde-rs/serde#2075]
I am trying to get serde working with `Option<sqlx::types::Uuid>`, for this I implemented serialize and deserialize in the module `some_module`, but when using the "with" attribute, the default attribute is not applied.

```
error[E0308]: mismatched types
  --> src/lib.rs:79:25
   |
79 | #[derive(sqlx::FromRow, Serialize)]
   |                         ^^^^^^^^^ expected struct `Uuid`, found enum `std::option::Option`
   |
   = note: expected reference `&Uuid`
              found reference `&'__a std::option::Option<Uuid>`
```

**Comment by jonasbb** [comment]
Without a runnable code snippet, it is hard to be certain, but it looks like your `some_module` has functions of the wrong signature.
The error message indicates the function looks like `fn serialize<S: serde::Serializer>(value: &Uuid, serializer: S) -> Result<S::Ok, S::Error>` but expected is `fn serialize<S: serde::Serializer>(value: &Option<Uuid>, serializer: S) -> Result<S::Ok, S::Error>` where the first argument is a reference to an `Option`.

The `default` field attribute is only relevant for deserialization, which you are not deriving in your error message.
