### ISSUE TITLE
Add Serde Gura to Data formats list

### ISSUE THREAD

**Issue by Genarito** [serde-rs/serde#2083]
Hi!

I've developed [my own Serde implementation](https://github.com/gura-conf/serde-gura/) for [Gura](gura.netlify.app/) (which is a file format for configuration files readable as YAML and simple as TOML) . I wonder if it could be added to the [list of Data formats](https://serde.rs/#data-formats) if not too much trouble.

Thanks in advance!

**Comment by dtolnay** [comment]
The data formats list is not meant to be exhaustive. I think this one is similar enough to others on the list that I would prefer not to include it. Thanks anyway!
