### ISSUE TITLE
Please bump semver-minor version when adding new public APIs

### ISSUE THREAD

**Issue by kornelski** [serde-rs/serde#2087]
[continuing from another thread](https://github.com/alexcrichton/cc-rs/issues/601)

Serde uses "1.0.LARGENUM" numbering scheme instead of adhering to SemVer. However, Cargo and crates.io tell users that all crates use SemVer, and this sets expectations for users of this crate too. Specifically, SemVer tells users that "1.0.*" versions are interchangeable, and this is not true for `serde`.

I understand that you don't want to deal with ambiguous cases when it's unclear whether a change is patch/minor/major according to SemVer.

However, there are also plenty of cases that are totally unambiguous. For example, addition of a new public API is a semver-minor change, not a patch.

You're free to resolve ambiguities however you want. However, please respect SemVer at least in cases where there's no ambiguity. [If you're rather not spend time thinking about SemVer](https://github.com/serde-rs/serde/issues/2029), please at least err towards using "1.LARGENUM.0" versioning scheme.

**Comment by dtolnay** [comment]
It should be clear that I am not interested in making a change here. 

Following semver spec to the letter has *never* been a Cargo dictum (far from it). The Rust ecosystem does what is right for the Rust ecosystem, and where that diverges from semver, that's useful information to fold back into the spec but we still do what is right for the Rust ecosystem.

I apologize for locking but issues like this always get dogpiled nonproductively.
