### ISSUE TITLE
Is there a way to check what failed serialization with serde_json?

### ISSUE THREAD

**Issue by Milo123459** [serde-rs/serde#2089]
I have been getting this error for ages and I can't figure out what is causing it. Would be cool if serde could tell you what was failing to serialise.

**Comment by jonasbb** [comment]
Are you by any chance looking for <https://docs.rs/serde_path_to_error>?

**Comment by Milo123459** [comment]
That looks like it might be the best thing in the world. Hold on.

**Comment by Milo123459** [comment]
Well, I'm using `reqwest`'s JSON method. How can I implement this there?

**Comment by jonasbb** [comment]
I don't know if there is a convenient way with reqwest. You can always get the raw string and deserialize it "manually" without reqwests method.

**Comment by Milo123459** [comment]
Thank you so much. You are the best. Thank you. So. Much.
