### ISSUE TITLE
How does skip_serializing work?

### ISSUE THREAD

**Issue by TyOverby** [serde-rs/serde#209]
The name implies that when the serializer hits that field it won't serialize it, but what happens when serde tries to deserialize a struct with skip_serializing on it?  Does it try anyway?  Should there be a synonymous skip_deserializing or should I really just not be using serde in this way?

**Comment by erickt** [comment]
`#[serde(skip_serializing)]` only is used when serializing, so you'll need to pair it with `#[serde(default)]`, which will call `Default::default()`. I've considered automatically pairing the two, but we might grow other mechanisms for setting these values, so I was erring on giving us more flexibility in the future.

**Comment by TyOverby** [comment]
Thanks!
