### ISSUE TITLE
[Question] Is it technically feasible to extract line number information (and other metadata) when deserializing?

### ISSUE THREAD

**Issue by willfindlay** [serde-rs/serde#2093]
Hi. I'm currently using Serde to implement deserialization for user-defined policy files. What I would like to do is be able to match individual policy rules to their original line number (or numbers) in the policy file (e.g. a JSON or YAML file). Is this something that would be technically feasible, for example by implementing my own deserializer? Any suggestions would be appreciated.

**Comment by dtolnay** [comment]
Yes &mdash; for example I believe the `toml` crate does this using https://docs.rs/toml/0.5.8/toml/struct.Spanned.html.
