### ISSUE TITLE
Better options than feature flag for RC types

### ISSUE THREAD

**Issue by JeremyRubin** [serde-rs/serde#2097]
If one wishes to derive Serialize/Deserialize for an Arc type, it's impossible to do so correctly in general (since Arcs will not preserver shared-ness across serializations).

If one sets the "rc" feature, this enables Arc serialization globally.

It's not desirable to have such a non-granular switch, as one often would want to enable rc support for a specific struct but not globally.

I suggest instead that it would make sense to have a field attribute that allows turning this behavior on field-by-field. This can be implemented already in user-level code using serialize_with, but I think it's a common enough patternt to give it first class support.

**Comment by JeremyRubin** [comment]
for reference, it would be adding code so that:

```rust
mod arc_serde {
    use serde::{Deserialize, Deserializer, Serialize, Serializer};
    use std::borrow::Borrow;
    use std::sync::Arc;
    pub fn serializer<T, S>(v: &Arc<T>, s: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
        T: Serialize
    {
        let b: &T = v.borrow();
        b.serialize(s)
    }
    pub fn deserializer<'de, T, D>(d: D) -> Result<Arc<T>, D::Error>
    where
        D: Deserializer<'de>,
        T: Deserialize<'de>
    {
        Ok(Arc::new(T::deserialize(d)?))
    }
}


#[derive(Serialize, Deserialize)]
pub struct ContinuationPoint {
    #[serde(serialize_with = "arc_serde::serializer")]
    #[serde(deserialize_with = "arc_serde::deserializer")]
    pub schema: Arc<String>,
}
```

could be just

```rust
#[derive(Serialize, Deserialize)]
pub struct ContinuationPoint {
    #[serde(rc_cloned)]
    pub schema: Arc<String>,
}
```

**Comment by jplatte** [comment]
I don't think this makes sense as a builtin thing. It would only work for fields of type `Arc`, not for example `Vec<Arc<String>>` or `MyType<Arc<String>>`.

**Comment by jonasbb** [comment]
This code already works and also supports the `Arc` inside other containers.
```rust
#[serde_with::serde_as]
#[derive(Serialize, Deserialize, Debug)]
#[serde(transparent)]
struct W(
    #[serde_as(as = "Vec<Arc<_>>")]
    Vec<Arc<String>>
);

let v: Vec<Arc<String>> = vec!["a", "b", "C", "d"]
    .into_iter()
    .map(|s| s.to_string().into())
    .collect();

let json = serde_json::to_string(&W(v))?;
println!("{}", json);
// ["a","b","C","d"]

let W(v) = serde_json::from_str(&json)?;
dbg!(v);
// [src/lib.rs:154] v = [
//     "a",
//     "b",
//     "C",
//     "d",
// ]
```

**Comment by JeremyRubin** [comment]
maybe a better way of explaining this is that the RC flag is kind of weird to have *at all* and should be removed. It's problematic that a dependency could enable buggy/error prone code by enabling serde rc, and mostly we should want it to be a compiler error unless behavior is specified manually.

**Comment by jplatte** [comment]
Having multiple `Arc<ValueType>` (`ValueType` being anything without interior mutability) with the same value is not usually a problem apart from increased memory usage. It shouldn't break anything, and is often better than using `Box<ValueType>` and cloning *that* all over the place.

**Comment by JeremyRubin** [comment]
As an example, this should not serialize as the graph description would be broken.

```
struct Node {
   weight: u64,
   out_edges: Vec<(u64, Arc<Node>)>
}
```

**Comment by dtolnay** [comment]
I think I'm happy with the current behavior on this. https://github.com/serde-rs/serde/issues/2097#issuecomment-980691141 would be my recommendation in code that wants a granular opt-in, and [assert_not_impl_any](https://docs.rs/static_assertions/1.1.0/static_assertions/macro.assert_not_impl_any.html) or [cargo-guppy](https://github.com/facebookincubator/cargo-guppy) if you want to enforce the global opt-in does not get enabled.

**Comment by JeremyRubin** [comment]
I think the issue is that you don't want to enforce global opt in not being used, what you want is to be able to *include* a library that does use it and a library that asserts it does not get enabled. Those crates would be not mutually compatible even though they could be safely as the opting into Arc serde's safeness is up to the library knowing it's types are duplication safe.

**Comment by JeremyRubin** [comment]
Imagine how annoying it would be if let's say a DateTime transitive dependency of some database used the Arc Deserialization feature and then i used assert_not_impl_any and it blocked me being able to include a database library.

**Comment by dtolnay** [comment]
Again, I'm happy with this as currently implemented. If your project needs to have dependencies that enable the *global* opt-in, then obviously don't put an assert_not_impl_any.
