### ISSUE TITLE
Deserializing untagged enums is slow

### ISSUE THREAD

**Issue by epage** [serde-rs/serde#2101]
When [profiling](https://epage.github.io/blog/2021/09/optimizing-toml-edit/) toml_edit, a hand-written `Deserialize` for an untagged enum took a benchmark for a common case in cargo from **484us** to **181us** (for a single `Cargo.toml` file, using this in the dependency resolving would multiple that by hundreds).

### Root Cause

The derive's untagged enum implementation tries each variant, one after another.
```rust
#[automatically_derived]
impl <'de> _serde::Deserialize<'de> for Value {
    fn deserialize<__D>(__deserializer: __D)
     -> _serde::__private::Result<Self, __D::Error> where
     __D: _serde::Deserializer<'de> {
        let __content =
            match <_serde::__private::de::Content as
                      _serde::Deserialize>::deserialize(__deserializer)
                {
                _serde::__private::Ok(__val) => __val,
                _serde::__private::Err(__err) => {
                    return _serde::__private::Err(__err);
                }
            };
        if let _serde::__private::Ok(__ok) =
               _serde::__private::Result::map(<i64 as
                                                  _serde::Deserialize>::deserialize(_serde::__private::de::ContentRefDeserializer::<__D::Error>::new(&__content)),
                                              Value::Integer)
           {
            return _serde::__private::Ok(__ok);
        }
        if let _serde::__private::Ok(__ok) =
               _serde::__private::Result::map(<f64 as
                                                  _serde::Deserialize>::deserialize(_serde::__private::de::ContentRefDeserializer::<__D::Error>::new(&__content)),
                                              Value::Float) {
            return _serde::__private::Ok(__ok);
        }
	// ...
        if let _serde::__private::Ok(__ok) =
               _serde::__private::Result::map(<Table as
                                                  _serde::Deserialize>::deserialize(_serde::__private::de::ContentRefDeserializer::<__D::Error>::new(&__content)),
                                              Value::Table) {
            return _serde::__private::Ok(__ok);
        }
        _serde::__private::Err(_serde::de::Error::custom("data did not match any variant of untagged enum Value"))
    }
}
```

For each failure, we generate an error which allocates its message and is adverised as a `#[cold]`
```rust
#[cold]
fn invalid_type(unexp: Unexpected, exp: &Expected) -> Self {
    Error::custom(format_args!("invalid type: {}, expected {}", unexp, exp))
}
```

### Potential Solutions

- Add a new attribute for suggesting a type to dispatch off of.  This can be brittle as it requires knowing the Deserialize implementation of each of the types within the untagged enum.
- Find a backwards-compatible way of checking each variant without a call to `invalid_type`
- Find a backwards-compatible way of not allocating in `invalid_type`
- Consider making this error not be `#[cold]` (I'm assuming this will make little difference)

**Comment by dtolnay** [comment]
This previously came up in #748. My preference is that this be explored in a different crate with a `Deserialize` derive macro geared toward producing high-performance deserialization of untagged enums. The slow part isn't in serde but in the derive-generated code, so a different derive could have different performance characteristics while still using only the same traits, although would likely take longer to compile than serde_derive.

**Comment by epage** [comment]
Should we at least have some note in the [documentation for untagged](https://serde.rs/enum-representations.html)?

**Comment by dtolnay** [comment]
Currently there is a moratorium on new attributes to keep serde_derive compile time under control.

**Comment by epage** [comment]
Would a PR for the untagged documentation that discusses the trade offs and calls out `serde_untagged` be of interest?

**Comment by dtolnay** [comment]
Yes -- thanks! I am not sure what to say about the serde-untagged yet since I am rewriting erased-serde at the moment; after that I will have a better idea of what the guidance should be.
