### ISSUE TITLE
Support RFC8941 Structured Header Fields

### ISSUE THREAD

**Issue by dcow** [serde-rs/serde#2107]
RFC8941 https://www.rfc-editor.org/rfc/rfc8941.html is the new way to go when sending structured data in http header fields. Top level Items, Lists and Maps are specified. It would be cool to see a support added for this format. I've found myself manually parsing http headers far too often.

**Comment by dtolnay** [comment]
I don't take requests for data formats here so I'm closing this issue. All data formats live outside of the serde crate so it's not going to take a code change in the serde crate for somebody to implement this format.
