### ISSUE TITLE
Consider removing format specific renames

### ISSUE THREAD

**Issue by erickt** [serde-rs/serde#211]
cc @hugoduncan.

I did a quick search through github, and I couldn't find anyone using `#[serde(rename(json=..., xml=...))]` and etc. I'm not sure if it's pulling it's weight and I'm considering removing it in the upcoming 0.7.0 release. This is also adding some complication in #207. Does anyone have any arguments towards keeping it?

**Comment by hugoduncan** [comment]
I'm using it in my AWS code, as the names used in the XML replies from
AWS don't match the names used in their API requests.

Having said that I haven't found time to work on anything in rust in the
last few months.

**Comment by erickt** [comment]
@hugoduncan: Do you have your code online? I did find another rust AWS API client, [rusoto](https://github.com/rusoto/rusoto), but I didn't see you in the contributors, nor does it seem to be doing any field renames. Are your serialized structures using multiple renames, or are you just doing a rename for the xml replies? Because that could be captured by just `#[serde(rename="xyz")]`.

**Comment by hugoduncan** [comment]
Code is here: https://bitbucket.org/hugoduncan/rust-awaze

It is doing multiple renames.  I wanted idiomatic rust variable names,
which resemble neither the XML response name, nor the request name.

For example: `vpc_id`, is `vpcId` in XML responses and `VpcId` in
requests.

**Comment by erickt** [comment]
@hugoduncan: I just looked through awaze, and I still see that you're using `#[serde(rename_serialize=..., rename_deserialize=...)]` that you removed in #69. Did you end up using the code you implemented in #69 somewhere else?

**Comment by erickt** [comment]
ps: amazon is very silly to return different names here :)

**Comment by erickt** [comment]
This was removed in #233.
