### ISSUE TITLE
Consider introducing an aggregate trait for types that can be both serialized and deserialized

### ISSUE THREAD

**Issue by Andlon** [serde-rs/serde#2113]
## Motivation

*Very* often when writing generic code I'm assuming that types that can be both serialized and deserialized. So I might have to write something like

```rust
fn foo<T: Serialize + DeserializeOwned>() {}
```
it seems senseful to me to be able to write something like
```rust
fn foo<T: Serde>() {}
```
instead. `serde` could provide a blanket impl to that effect. To motivate this with a real-world example, I currently have these trait bounds in a piece of code:

```rust
    Material: Serialize + DeserializeOwned,
    Material::Parameters: Serialize + DeserializeOwned,
    OPoint<f64, D>: Serialize + DeserializeOwned,
```
With the suggested addition, it would instead read
```rust
    Material: Serde,
    Material::Parameters: Serde,
    OPoint<f64, D>: Serde,
```
which, arguably, is far simpler.

## Q & A

- *You could just provide your own `Serde` trait, it doesn't need to be in `serde` proper.*
  - I could, but there are at least two problems with this:
    - I would like to have this functionality across many crates and projects: I would have to create a mini-crate with *only* this trait.
    - Users reading the code wouldn't be familiar with the trait, so upon reading the code it might not be clear what the trait does. If it's provided by `serde`, then it would have more legitimacy and users might be more familiar with it.
- *Wouldn't trait aliases be better suited for this? Maybe we should wait for trait aliases to land?*
  -  Perhaps. This feature seems far away, and we'd need the MSRV to follow suit, which would take far longer (maybe even never / version 2?). I don't immediately see any benefits of implementing it as a trait alias - both implementations would achieve the same practical result. `DeserializeOwned` is already precedence: it's effectively a trait alias implemented by way of a blanket impl.
- *The trait should be called `SerDe`, not `Serde`!*
  - Yeah, I'm worried that this might be a particular source of bike-shedding. I also considered `SerializeDeserialize`, but the benefits diminish somewhat by having a very long trait name.

I'm interested to hear what people think.

**Comment by dtolnay** [comment]
I'd prefer not to build something like this into this crate. Thanks anyway for the suggestion!
