### ISSUE TITLE
Reverse-Flattening a Sub-Struct in a Parent Struct

### ISSUE THREAD

**Issue by zedseven** [serde-rs/serde#2115]
I say "reverse-flattening" because this seems to be the inverse of `#[serde(flatten)]`.

I want to turn what currently deserializes into:
```rust
#[derive(Deserialize)]
struct ExternalApiResponse {
  ...
  sub_struct: SomeSmallStruct,
  ...
}

#[derive(Deserialize)]
struct SomeSmallStruct {
  field_0: u32,
  field_1: f64,
}
```
into:
```rust
#[derive(Deserialize)]
struct ExternalApiResponse {
  ...
  field_0: u32,
  field_1: f64,
  ...
}
```

I've looked for solutions before posting this, like #868. Unfortunately from what I can tell, its solution only works for one sub-field.

Implementing a non-generic version of the solution posted there looks something like this:
```rust
#[derive(Deserialize)]
struct ExternalApiResponse {
  ...
  #[serde(rename = "sub_struct", deserialize_with = "extract_field_0")]
  field_0: u32,
  #[serde(rename = "sub_struct", deserialize_with = "extract_field_1")]
  field_1: f64,
  ...
}

fn extract_field_0<'de, D: Deserializer<'de>>(deserializer: D) -> Result<u32, D::Error> {
  SomeSmallStruct::deserialize(deserializer).map(|a| a.field_0)
}
fn extract_field_1<'de, D: Deserializer<'de>>(deserializer: D) -> Result<f64, D::Error> {
  SomeSmallStruct::deserialize(deserializer).map(|a| a.field_1)
}
```
Unfortunately in the above example, `field_1` is not populated. I suspect this is because `sub_struct` is only visited once.

Is it possible to do this, and if so is it possible without my ugly `extract_*` functions all over the place?

**Comment by dtolnay** [comment]
Please take this question to one of the resources listed in https://github.com/serde-rs/serde/tree/v1.0.135#getting-help. Sorry that no one was able to provide guidance here.

**Comment by LoganDark** [comment]
> Please take this question to one of the resources listed in https://github.com/serde-rs/serde/tree/v1.0.135#getting-help. Sorry that no one was able to provide guidance here.

This is a feature request... just ran into this missing feature trying to type the JSON responses from [`text-generation-inference`](https://github.com/huggingface/text-generation-inference), which has some unnecessary nesting.
