### ISSUE TITLE
'deny_unknown_fields' and 'skip' not compatible (a skipped field results in a 'unknown field' error)

### ISSUE THREAD

**Issue by d4h0** [serde-rs/serde#2121]
If a struct is annotated with `deny_unknown_fields`, and it contains a field that should be skipped, deserializing always fails with a 'unknown field' error:

```rust
#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)
struct Test {
    #[serde(skip)]
    useless: String
}
```

This was already reported at least once [here](https://github.com/serde-rs/serde/issues/1164), but for some reason was closed as "works as intended".

Maybe there is a technical reason why this is the intended behavior, however from a logical point of view this doesn't make sense to me. If a field is skipped explicitly, it's clearly a known field, so I don't understand why this should fail.

I'm using `serde` to deserialize JSON that I get from an API. I use `deny_unknown_fields` because I want to get notified as soon as the returned format of the JSON changes (so that I don't miss any updates of the API). However, I'd like to ignore a few fields that I'm not interested in (and therefore mark them with `skip`).

Even if this is really the intended behavior (and I hope it's not), I think this incompatibility between `deny_unknown_fields` and `skip` then needs to be documented (similar to how the [docs of `deny_unknown_fields`](https://serde.rs/container-attrs.html#deny_unknown_fields) mention that it isn't compatible with `flatten`).

**Comment by d4h0** [comment]
Something else I've noticed while working on a workaround (if I didn't make a mistake):

```rust
#[derive(Debug, Deserialize)]
struct Foo {
    #[serde(skip)]
    bar: String,

    #[serde(flatten)]
    extra: HashMap<String, Value>,
```

It seems `bar` always ends up in `extra`, which seems unintuitive to me (but of course it's for the same reason as the above).

**Comment by d4h0** [comment]
In case someone with the goal I've described above stumbles upon this issue via a search engine:

There is [serde_ignored](https://crates.io/crates/serde_ignored) which is basically like `serde(deny_unknown_fields)`, but doesn't fail automatically. I'll probably use this to log a warning when additional fields in the return value of an API endpoint are found (which makes more sense than to fail completely).

I haven't tested it, but I assume `serde_ignored` also doesn't work with `serde(skip)`.

Fortunately, I think I found a nice alternative for `serde(skip)` (which also should be compatible with `serde(deny_unknown_fields)`):

```rust
use serde::{Deserialize, Deserializer};

/// A type that ignores any value. If the key it's assigned to doesn't
/// exist, `Ignored` is still assigned (identically to how `serde` treats
/// fields that contain `Option<_>` that are missing in the input)
#[derive(Debug, Deserialize)]
#[serde(from = "Ignore")]
struct Ignored;

// We'll use `Ignore` to deserialize `Ignored`
impl From<Ignore> for Ignored {
    fn from(_: Ignore) -> Self {
        // We just discard `Ignore` and return `Ignored` instead:
        Ignored
    }
}

#[derive(Debug, Deserialize)]
#[serde(transparent)]
// Note: `serde(transparent)` above is required so `Ignored` is treated like
// `Option<_>` if the field doesn't exist. Otherwise, we'd get an error.
struct Ignore(#[serde(deserialize_with = "ignore")] Option<()>);

fn ignore<'de, D>(_: D) -> Result<Option<()>, D::Error>
where
    D: Deserializer<'de>,
{
    Ok(None)
}

// Example:

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct Test {
    #[serde(flatten)]
    foo: Extra,
}

#[derive(Debug, Deserialize)]
struct Extra {
    bar: Ignored,
}
```

The only problem with the above is, that I don't understand how and why it works... 😆

Why does this work without consuming anything in the `ignore` function?

And could any problem result from this?

I also managed to create a variant that uses `serde_json::value::RawValue`:

```rust
#[derive(Debug, Deserialize)]
#[serde(from = "Ignore")]
struct Ignored;

#[derive(Debug, Deserialize)]
#[serde(transparent)]
struct Ignore<'a>(#[serde(borrow)] Option<&'a serde_json::value::RawValue>);

impl<'a> From<Ignore<'a>> for Ignored {
    fn from(_: Ignore<'a>) -> Self {
        Ignored
    }
}

// Example:

#[derive(Debug, Deserialize)]
struct Test {
    foo: String,
    bar: Ignored, // Works
    #[serde(flatten)]
    extra: Extra,
}

#[derive(Debug, Deserialize)]
struct Extra {
    baz: Ignored, // Doesn't work
}
```

The problem is, as indicated, that this doesn't work with `serde(flatten)`... :(

If `serde(flatten)` is used with a container that contains an `Ignored` value, the following error is emitted at runtime:

> Invalid type: newtype struct, expected any valid JSON value

This seems to be a known issue: https://github.com/serde-rs/json/issues/599

**Comment by Mingun** [comment]
It seems you reinvented [IgnoredAny](https://docs.serde.rs/serde/de/struct.IgnoredAny.html)

**Comment by d4h0** [comment]
Thanks for your comment, @Mingun!

Damn. When I read the documentation I got the impression that `IgnoredAny` can only be used to write deserializes by hand (of which I know nothing), not that it can be used as regular type of a field. This probably shows my lack of understanding of how `serde` works... 😆

**Comment by dtolnay** [comment]
I'll go ahead and close since it sounds like you got this working, and the current behavior of the derive seems fine to me.

> from a logical point of view this doesn't make sense to me. If a field is skipped explicitly, it's clearly a known field, so I don't understand why this should fail.

I think this isn't quite the right mental model for `skip`. An illustrative counterexample is something like:

```rust
#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct Message<T> {
    the_only_data_field: i32,
    #[serde(skip)]
    marker: PhantomData<fn() -> T>,
}
```

where `marker` is a Rust-only thing and is not part of the data layer. Seeing it in the input for a `deny_unknown_fields` struct is supposed to be an error just like any other unexpected field. If the message format were to start using `marker` for something on its end, the right fix would most likely be renaming the Rust-only thing to a different field name, like `phantom_data`.

**Comment by matthiasg** [comment]
The documentation of [IgnoredAny](https://docs.serde.rs/serde/de/struct.IgnoredAny.html) could be improved though for this use case. @d4h0 did not see the use of it and I am sure others did not either
