### ISSUE TITLE
Introduce `untagged_strict` mode.

### ISSUE THREAD

**Issue by nathan-at-least** [serde-rs/serde#2122]
**Suggestion:** Add an `untagged_strict` mode for enums which fails unless exactly one set of enum keys is present with no other unrecognized keys for that enum variant.

If I have an untagged enum like this:

```
#[derive(serde::Deserialize)]
#[serde(untagged)]
enum Source {
  Url { url: String, expected_hash: String }
  LocalPath { path: PathBuf }
}
```

-then I can successfully deserialize (at least with `toml`) an entry like this:

```
url: "http://foo.net"
path: "bananas"
```

This will successfully match `Source::LocalPath` with no error. For my application this is very likely to confuse any users who have a malformed configuration file.

**Comment by Mingun** [comment]
I think, that `deny_unknown_fields` can help you here.

**Comment by dtolnay** [comment]
Yep I think this is just `#[serde(untagged, deny_unknown_fields)]`.
