### ISSUE TITLE
Serializing and Deserializing references using stateful serialization?

### ISSUE THREAD

**Issue by shangjiaxuan** [serde-rs/serde#2125]
There are cases where references in formats where references are better stored once and referenced multiple times. Typically when a large and complex field is used.

Maybe using a trait (similar to `DeserializeSeed`), and let the format's `Serializer/Deserializer` implementation keep track of the objects (e.g. xml entities)?

Adding something like this to the extended `Serializer/Deserializer` trait:
```
fn serialize_reference<Rc<T>>(self, name: &'static str, value: &Rc<T>) -> Result<Self::Ok, Self::Error>
// probably? but sometimes static strings are not meant to be used as string pool
// use a field attribute to control?
fn serialize_reference<&T>(self, name: &'static str, value: &T) -> Result<Self::Ok, Self::Error> 
```

This way serializer and deserializer can distinguish a reference and can implement to have only one copy in serialize data and in memory.

**Comment by dtolnay** [comment]
I'd prefer not to build this into this crate. Thanks anyway for the suggestion!
