### ISSUE TITLE
Option for type formating hints/features

### ISSUE THREAD

**Issue by the-eater** [serde-rs/serde#2128]
Hello,

I am currently implementing a serde serializer for a format I'm writing, however some types (e.g. sequences) can be defined in several ways (a stream, a list with known sizes, and a list with a jump table) 

I was hoping to provide access to other sequences types with serde, but I can't find any way to feed options or metadata about a field in the documentation.

The only way to achieve my goal now would be to write my own Serialize for a struct and sneakily run it through serialize_newtype_struct so I can match it (with `TypeId::of::<T>() == TypeId::of::<JumpTableSeq>()`) and do the Correct Action™ (Edit: this does not work because it would be `JumpTableSeq<T>` so I am stuck rip)

Is there a way to provide metadata about a type or field to the serializer?

e.g. in short I am looking for something alike

```rs
#[derive(Serialize)]
struct Gamers {
  #[serde(features = [MyFormatFeature::JumpTable])
  names: Vec<String>
}
```

and then being able to retrieve those features in the `serialize` functions

**Comment by dtolnay** [comment]
Please take this question to one of the resources listed in https://github.com/serde-rs/serde/tree/v1.0.135#getting-help. Sorry that no one was able to provide guidance here.
