### ISSUE TITLE
Need help implementing struct and enum deserialization in a format that stores field ids as hashes

### ISSUE THREAD

**Issue by Yuri6037** [serde-rs/serde#2130]
I'm writing a deserializer for a custom format. I got the basic types and a partial deserialize_any, however there are a few parts I can't deserialize: enums and structs.

For enums the problem is very simple: the VariantAccess trait doesn't give any way to return the enum variant index back to the caller so the caller knows what variant it is.

For structs the problem is a bit more complicated: there are no traits to deserialize structs and looking at the doc example, the only thing I can find is treating structs as maps however this is impossible in my format as all struct keys must be strings and the format does not store the actual names it stores hashes instead.
I couldn't find anything in the doc which allows the caller to call into my deserializer with a pattern like deserialize_struct_field(name_of_field, expected_type). The caller must provide what field name it wants and what is the expected type of the field.

EDIT: I've fixed the struct problem by returning a sequence ordered in the exact order of the fields static double array.
I've kind of fixed the enum problem but that required a hacky solution: create a dummy deserializer with a single u32 corresponding to the serialized variant index then implement deserialize_identifier for it but leave all other methods as `todo!()`

EDIT2: I fixed the enum problem by assuming that only enum variants will call into deserialize_identifier.

**Comment by dtolnay** [comment]
Please take this question to one of the resources listed in https://github.com/serde-rs/serde/tree/v1.0.135#getting-help. Sorry that no one was able to provide guidance here.
