### ISSUE TITLE
missing field is being raised on enum variant with option when using tag and content 

### ISSUE THREAD

**Issue by shwahnim** [serde-rs/serde#2131]
Hello, I'm not sure how to get this to work, but using an enum variant with `Option` type and with attributes `#[serde(deserialize_with="..")]` inside an enum annotated with `#[serde(tag="t", content="c")]`  fails if the the content field is missing
 
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=e9ac9ac8e4848bcc16e37b577d51e4fe

```
extern crate serde;
#[macro_use]
extern crate serde_derive;
use serde::{Deserialize, Deserializer};

#[derive(Debug, Deserialize)]
struct S {
    state: State,
}

#[derive(Debug, Deserialize)]
#[serde(tag="type", content="value")]
enum State {
    #[serde(deserialize_with = "callback")]
    X(Option<i32>),
    #[serde(deserialize_with = "callback")]
    Y(Option<i32>),
}


fn callback<'de, D>(deserializer: D) -> Result<Option<i32>, D::Error>
where
    D: Deserializer<'de>,
{
    Option::<i32>::deserialize(deserializer)
}


fn main() {
    println!("{:?}", serde_json::from_str::<S>(r#"{"state": { "type": "X"} }"#));
}
```

**Comment by Mingun** [comment]
Clarification: the error is only present if `deserialize_with` attribute is used and not present without it: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=4a06a3ac4872213ddb62361ab7f9ac95

**Comment by shwahnim** [comment]
> 

yes, the error is only present if `deserialize_with` attribute is used

**Comment by jonasbb** [comment]
Did you mean to write this?
```rust
X(
    #[serde(deserialize_with = "callback", default)]
	Option<i32>
),
```

**Comment by shwahnim** [comment]
> Did you mean to write this?
> 
> ```rust
> X(
>     #[serde(deserialize_with = "callback", default)]
> 	Option<i32>
> ),
> ```

thanks, it works
