### ISSUE TITLE
Support `Serializer` to specialize for specific types

### ISSUE THREAD

**Issue by quininer** [serde-rs/serde#2135]
In some cases, the `Serializer` trait defined by `serde` is not enough to describe all definitions of serialization scheme.

For example, there are two types of `null` and `undefined` in cbor, but `Serializer` only has a corresponding method called `serialize_none`.

Another more complicated example is the tag in cbor. The two cbor crate that support serde both use a less than ideal scheme to transmit information under the constraints of serde.
`serde_cbor` uses `thread_local!` to pass tags (https://github.com/pyfisch/cbor/blob/master/src/tags.rs#L220),
and `ciborium` uses a special newtype variant to pass tags (https://github.com/enarx/ciborium/blob/main/ciborium/src/tag.rs#L6).

I think specialization can help with such problems.
Ideally, we can get specialized support from compiler, like

```rust
pub struct Undefined;

default impl Serialize for Undefined { .. }

impl Serialize for Undefined {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer + CborSerializerUndefined
    {
        serializer.serialize_undefined()
    }
}
```

but compiler specialization is currently impossible.
maybe we can add a `serialize_any` method to `Serializer` to allow specialize a specific type.

```rust
impl Serializer for &'a mut CborSerializer {
    fn serialize_any(self, v: &dyn std::any::Any) -> Result<Option<Self::Ok>, Self::Error> {
        if v.is::<Undefined>() {
            self.serialize_undefined().map(Some)
        } else {
            Ok(None)
        }
    }
}

impl Serialize for Undefined {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer
    {
        if serializer.serialize_any(self)?.is_none() {
             serializer.serialize_none()?; // fallback to none
        }
        Ok(())
    }
}
```

**Comment by dtolnay** [comment]
I think I'd prefer not to build anything for this into this crate. It sounds like the cbor crates you linked both got this working using the existing Serializer API, but it's also possible they'd want to provide their own trait + `derive` macro to support aspects of the format that fit serde's model less well.
