### ISSUE TITLE
`serde_test` test deserialize_with.

### ISSUE THREAD

**Issue by BratSinot** [serde-rs/serde#2136]
Greetings!

How can I test `Deserializer` with deserialize_with?
```rust
    struct Address {
        host: String,
        #[serde(deserialize_with = "number_or_string")]
        port: u16,
    }
    
    #[test]
    fn test_number_or_string() {
        //assert_ser_tokens(&mapper.readable());
    }
```

**Comment by dtolnay** [comment]
Please take this question to one of the resources listed in https://github.com/serde-rs/serde/tree/v1.0.135#getting-help. Sorry that no one was able to provide guidance here.
