### ISSUE TITLE
Serialize multiple keys into one enum

### ISSUE THREAD

**Issue by cemoktra** [serde-rs/serde#2137]
Hi,

this is more of a question if possible, in any way i could easily manipulate the json a bit before deserializing.

The problem is, that i receive a json with two fields among others that have a relation to each other and only allow certain combinations, e.g.:
```json
{
    "field1": "A", 
    "field2": "B"
}
```

Now only some combinations are possible like AA, AB, BB and i want to combine those into an enum with all possible combinations. I would need a visitor that visits both fields.

Target enum being like:
```Rust
enum Field {
 AA = 0,
 AB = 1,
 BB = 2,
 Invalid = 3
}
```

As is said i can manipulate the json to combine those fields into one but i'm curious if this would be possible without this step

**Comment by dtolnay** [comment]
Please take this question to one of the resources listed in https://github.com/serde-rs/serde/tree/v1.0.135#getting-help. Sorry that no one was able to provide guidance here.
