### ISSUE TITLE
#[serde(flatten)] on multiple fields doesn't work correctly

### ISSUE THREAD

**Issue by 95th** [serde-rs/serde#2142]
I have a struct with two maps where I want to collect all the known keys into one map and rest into another.

```rust
use serde::*;
use std::collections::HashMap;

#[derive(Debug, Serialize, Deserialize)]
pub struct BarMap {
    #[serde(flatten)]
    known: HashMap<FooEnum, String>,
    
    #[serde(flatten)]
    other: HashMap<String, String>,
}

#[derive(Debug, Hash, PartialEq, Eq, Serialize, Deserialize)]
pub enum FooEnum {
    A,
    B,
}


fn main() {
    let x: BarMap = serde_json::from_str(r#"{ "A": "what", "C": "yes" }"#).unwrap();
    println!("{:?}", x);
}
```

Expected behavior:
---
`BarMap` has one entry for `A` in `known` and one entry for `C` in `other` hash map.

Actual Behavior:
---
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("unknown variant `C`, expected `A` or `B`", line: 1, column: 27)', src/main.rs:21:76

[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=8930aa2fe9fb747a9999548eb0501132)

**Comment by dtolnay** [comment]
I'm happy with the existing behavior on this. When deserializing, a flattened map like `HashMap` means "all the rest". Treating anything that fails to deserialize into a flattened map as silently ignored wouldn't be a better behavior I think.
