### ISSUE TITLE
Discord link in README not working

### ISSUE THREAD

**Issue by MarcelRobitaille** [serde-rs/serde#2151]
The links to the discord in the README are broken. I am getting this when I click them. Is this reproducible or is it just my discord being weird?

![image](https://user-images.githubusercontent.com/8503756/148665674-ffc787ad-2f7c-41cc-8393-a796bdd6dcc9.png)

**Comment by hasezoey** [comment]
> Is this reproducible or is it just my discord being weird?

just tried too, getting same "errors" for both `#general` and `#beginners`
