### ISSUE TITLE
Any way to get the order of sections when deserializing toml?

### ISSUE THREAD

**Issue by MarcelRobitaille** [serde-rs/serde#2152]
I am deserializing a struct from toml and I would like to be able to know the order in which the fields appear in the file. The reason is that I would like to change the order in which different sections get processed based on the order of these sections in the config file.

For example, with this config
```rust
struct Foo;
struct Bar;

#[derive(Deserialize)]
struct Config {
    foo: Foo,
    bar: Bar,
}
```

I can choose to process foo before bar
```toml
[foo]
[bar]
```

or bar before foo
```toml
[bar]
[foo]
```

In my real situation, the structs `Foo` and `Bar` would each have their own unique fields and there would be more of them.

I know it probably couldn't be done in exactly the same way because structs are unordered, but maybe there is some way to do something similar?

Sorry if I am missing something obvious, but I haven't seen anything looking through the docs or other issues.

**Comment by avitex** [comment]
If you want to preserve order, you need to store additional data of the order you received it. This order is lost for deserializing to structs. This is not something serde can or will deal with.

Consider using a structure similar to https://docs.rs/indexmap/latest/indexmap/map/struct.IndexMap.html

This question is probably best asked somewhere else, see https://github.com/serde-rs/serde#getting-help

**Comment by MarcelRobitaille** [comment]
Thanks for your response.

I am sorry for asking as an issue, but I did try to ask in https://github.com/serde-rs/serde#getting-help first, which is why I opened #2151. I also tried to find the discord through google with no luck. :)
