### ISSUE TITLE
Serde rename_all attribute consistency

### ISSUE THREAD

**Issue by ppearson** [serde-rs/serde#2153]
I think there might be an inconsistency with the Serde 'rename_all' attribute for certain values, in order to rename struct fields in a convenient way:

if I have a field called "my_field" (i.e. lower case, and with underscores - to match the style guide), and I use rename_all = "camelCase", then the resulting name used for serialisation/deserialisation becomes "myField", which is expected. i.e. the underscores are stripped out.

If I use rename_all = "UPPERCASE", I was expecting the underscores to be stripped out, seeing as using "SCREAMING_SNAKE_CASE" would allow keeping them with uppercase, but that does not appear to be the case: they're left in, meaning there's no practical difference between "UPPERCASE" and "SCREAMING_SNAKE_CASE" that I can see, and no apparent way to remove the underscores while makeing the case uppercase.

Indeed, looking at:
https://github.com/serde-rs/serde/blob/master/serde_derive/src/internals/case.rs

UpperCase and ScreamingSnakeCase have identical behaviour in apply_to_field(), whilst CamelCase seems to end up calling PascalCase.apply_to_field() which I think removes the underscores. UpperCase doesn't call that, so the underscores stay in.

I'd personally say that UpperCase should be stripping the underscores as well for consistency, unless this is as expected?

**Comment by dtolnay** [comment]
I think this is fine as implemented. The reason for UPPERCASE to exist, even if it does the same thing as SCREAMING_SNAKE_CASE for field names, is that when there is no underscore in any field names it doesn't make sense to think of them as "snake case". The identifier `one` is just as much kebab-case as it is camelCase as it is snake_case. Asking for a conversion to SNAKE_CASE in this situation is misleading and it's better to think of just converting the single word to UPPERCASE.

```rust
#[serde(rename_all = ???)]
struct S {
    one: T,
    two: T,
    three: T,
}
```

Inversely the reason for SCREAMING_SNAKE_CASE to exist is that its underscore insertion is usually needed for enum variants. UPPERCASE doesn't give any indication that underscores would be inserted. That behavior needs "snake case" in the name.

```rust
#[serde(rename_all = ???)]
enum E {
    FirstThing,
    SecondThing,
}
```

**Comment by ppearson** [comment]
But surely that's a 'peculiarity' of the very short identifier, and I don't see why it would be 'misleading' personally: In fact, I'd argue the opposite: I'd say it'd be fairly obvious that if a field name of 'one' was converted you wouldn't want underscores in there because it doesn't need them, so yes, for very short one-word field names, there isn't a difference, but surely that's not the point? The differences between the type values of rename and rename_all should be relevant to the name of the field: if they've got underscores in them, the type value should do something about it, if they don't then just the case is modified. I don't see why your example makes any difference.

How else is one to get the desired behaviour of uppercase with no underscores, without littering each field with a manual rename, which is pretty poor and annoying IMO (compared to a single rename_all at the top)?

**Comment by coriolinus** [comment]
I could also use some rename_all rules which adjust the spacing. Perhaps a concrete example is useful to demonstrate the motivation: I'm consuming an API which has objects with fields `firstname`, `lastname`, `streetnumber`, and the like. In a perfect world, I could write this as 

```rust
#[derive(Debug, Deserialize, Serialize)]
#[serde(rename_all="lowercase")]
struct FromForeignApi {
    first_name: String,
    last_name: String,
    street_number: String,
    // etc
}
```

However, attempting this, I encounter the surprising situation that unlike most `rename_all` rules, `lowercase` does not adjust the spacing between the words.

There is of course the argument that we shouldn't change the behavior of a presumably large quantity of code in the world already using these rename_all rules. I'd therefore propose adding two new rename_all rules: `compactlowercase` and `COMPACTUPPERCASE`, which adjust both casing and spacing.

@dtolnay What's your thought on that proposal? Is it something you're willing to work on yourself, something you'd consider favorably if a PR showed up, or something you think should not be part of serde?

**Comment by dtolnay** [comment]
A lot of people have made demands for various new rename rules over the years, and changes to existing rules. My recommendation is implement it in a different crate. You can make a macro that emits individual serde(rename) attributes.
