### ISSUE TITLE
Add collect_bytes or a similar method

### ISSUE THREAD

**Issue by Kixunil** [serde-rs/serde#2155]
There are cases when a type has a well-known compact byte encoding but can not be constructed as a single byte slice directly. A simple example would be a struct with two fields that are generally serailized as concatenated bytes.

There already exist `collect_str` and `collect_seq` for similar non-byte cases. `collect_seq` is probably the closest but it doesn't communicate that the items are bytes. It'd be nice adding `fn collect_bytes(iter: impl Iterator<Item=u8>) -> Result<(), Self::Error>` to the `Serializer` trait delegating to `serialize_seq` by default.

**Comment by dtolnay** [comment]
I can see how this would sometimes be helpful, but I don't see it being a widespread enough use case to justify a new Serializer method for this. Thanks anyway for the suggestion!

**Comment by Kixunil** [comment]
If you have any idea how to workaround this it'd be appreciated. Thanks for the answer anyway!
