### ISSUE TITLE
Add support for comments

### ISSUE THREAD

**Issue by andrewgazelka** [serde-rs/serde#2156]
Comments are an important part of many formats serde supports. However, serde does not expose a comment type, so in current crates there is no way to add them.

Here are some people in the community asking for comment support:
- https://github.com/alexcrichton/toml-rs/issues/274
- https://github.com/dtolnay/serde-yaml/issues/145
- https://github.com/dtolnay/serde-yaml/issues/219
- https://github.com/dtolnay/serde-yaml/issues/100
- https://github.com/serde-rs/json/issues/168

In addition, [HJSON](https://github.com/Canop/deser-hjson) could be serializable instead of just deserializable

Comments are usually tied to fields. Perhaps serde could parse doc strings and expose them. For instance, if we had 
```rust
struct Tester {
   /// use this for reason xyz
   a_field: u32
}
```
and used serde-yaml, we could generate
```yaml
# use this for a reason xyz
a_field: 123
```
from
```rust
Tester { a_field: 123 }
```

However, this has disadvantages. It doesn't allow for dynamic comments. It might be better to have a `Comment` type, but I am not sure this would be as clean. At least it would be better in terms of backward compatibility. We could also have a custom comment property on fields. Thoughts?

**Comment by dtolnay** [comment]
You can see my responses in many of the issues you linked. I would prefer not to build this into this crate.
