### ISSUE TITLE
Better message when failing to match any variant of an untagged enum

### ISSUE THREAD

**Issue by GeeWee** [serde-rs/serde#2157]
Reopen of issue #773 as there still seems to be interest, and there is someone who's started doing some work on it #1544 . Of ocurse, feel free to close, but I hope you'll reconsider this as important.

Further info: We have a lot of untagged enums in our public-facing API, and it's extremely difficult to give proper error messages to the user as all we can get out of Serde is `data did not match any variant of untagged enum` - if there was an opt-in to getting better error messages here, it would make our life a lot easier.

**Comment by GeeWee** [comment]
Related to #1544 which seems to have been stalled for a while.

**Comment by dtolnay** [comment]
I published https://docs.rs/serde-untagged implementing one of the suggested approaches from https://github.com/serde-rs/serde/pull/2376#issuecomment-1519172405. It constructs error messages by incorporating information about which of the Serde data model's types your type knows how to deserialize from. Also leading to better error messages is that you can avoid buffering (`Content`) when there is at most one map-based or seq-based variant.

If there are remaining use cases still not well served by this, I would like to see someone make a different crate dedicated to any of those.
