### ISSUE TITLE
Promote runtime deserialization error to compile-time for tag name <=> struct field collision

### ISSUE THREAD

**Issue by shustinm** [serde-rs/serde#2164]
```rust
#[derive(Debug, Deserialize)]
#[serde(tag = "node_type")]
pub enum Node {
    Branch(Branch),
    Leaf(Leaf)
}

#[derive(Deserialize, Debug)]
pub struct Branch {
    pub node_type: String,
    pub uri: String,
    pub child_nodes: Vec<Branch>
}

#[derive(Deserialize, Debug)]
pub struct Leaf {
    pub node_type: String,
    pub uri: String,
    pub input_type: String,
    pub poll: bool,
    pub parameters: Vec<String>,
    pub actions: Vec<Action>
}
```
Deserializing `Node` will always fail at runtime. However, this issue could be found at compile-time error. The problem is that `Node` "uses up" the field `node_type` and then when either struct is being deserialized, `serde` complains about missing the field `node_type`.

Environment
- rustc 1.42.0 
- serde 1.0.115
- serde_json 1.0.57 (I used serde_json to deserialize)

Thank you @namibj so much for helping me find the error and write the issue!

**Comment by dtolnay** [comment]
While it's possible that this could be found at compile time, I don't think that the effort and compile time needed would be worth the benefit, so I'll go ahead and close this suggestion. Thanks anyway!
