### ISSUE TITLE
OsString cannot be serialized as a JSON map key

### ISSUE THREAD

**Issue by dimo414** [serde-rs/serde#2165]
[Playground example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=8ed9214941f3abecefefeafd71a3ac35)

As discussed in https://stackoverflow.com/q/51276896/113632, JSON only supports string keys, which `OsString` (technically) is not. Unlike a custom struct, however, it's not straightforward (or possible?) for a user to define a custom `Serialize` implementation for `OsString` or `Map<OsString, ...>` types to work around this issue.

One approach I could imagine is serializing `OsString` objects as Base64 (or another textual encoding), though I don't know whether it would be safe/acceptable to change its serialized form. Alternatively perhaps Serde could represent maps with non-string keys as an array of pairs in JSON.

serde-rs/json#465 is related but essentially the opposite problem, since `PathBuf` is serialized as a string.

**Comment by dtolnay** [comment]
I think I would prefer to keep the current Serialize impl on OsString, but if you need it you can serialize the OsString map keys in a different way like this:

```rust
use serde::Serialize;
use serde::ser::{SerializeMap, Serializer};
use std::collections::HashMap;
use std::ffi::OsString;

fn main() {
    let mut map = HashMap::new();
    map.insert(OsString::from("key"), true);

    let ser = serde_json::value::Serializer;
    let serialized = serialize_with_lossy_string_keys(&map, ser).unwrap();
    println!("{}", serialized);

    #[derive(Serialize)]
    struct Struct {
        #[serde(serialize_with = "serialize_with_lossy_string_keys")]
        map: HashMap<OsString, bool>,
    }

    let serialized = serde_json::to_string(&Struct { map }).unwrap();
    println!("{}", serialized);
}

fn serialize_with_lossy_string_keys<'a, M, T, S>(value: &'a M, serializer: S) -> Result<S::Ok, S::Error>
where
    &'a M: IntoIterator<Item = (&'a OsString, &'a T)>,
    T: 'a + Serialize,
    S: Serializer,
{
    let mut map = serializer.serialize_map(None)?;
    for (k, v) in value {
        map.serialize_entry(&k.to_string_lossy(), v)?;
    }
    map.end()
}
```
