### ISSUE TITLE
MSRV question

### ISSUE THREAD

**Issue by atouchet** [serde-rs/serde#2168]
The Readme lists serde as requiring Rust 1.13+ but the Cargo.toml lists the minimum version as 1.15. Is one of these wrong?

**Comment by dtolnay** [comment]
Yeah good catch, 1.13 is the right one.

**Comment by atouchet** [comment]
Should serde_test be updated as well: https://github.com/serde-rs/serde/blob/master/serde_test/Cargo.toml#L5

**Comment by dtolnay** [comment]
Done.
