### ISSUE TITLE
Deserializing an `enum` with a `tag` directive causes `deserialize_any` to be called instead of `deserialize_enum`.

### ISSUE THREAD

**Issue by scrblue** [serde-rs/serde#2170]
As stated in the title, two otherwise identical `enum`s, one of which with a `#[serde(tag =  "...")]` directive deserialize differently. Without the directive, `deserialize_enum` is called first while in the second `deserialize_any`  is called.

This has consequences when a `deserialize_any` method is not identical in functionality to the rest of the deserialize functions (as with your own JSON formatting crate, see: https://github.com/serde-rs/json/issues/855 for context) .

I'm not sure how to report a minimal example without requiring modifications to `serde_json` or a similar crate.  While the issue happens in the following example, I was only able to see it happen with a local version of `serde_json`with logging  added to the  `de` module. In any case `enum A` will deserialize as an `enum` while `enum B`  deserializes as `any`. In the case of `serde_json`, this means that `enum` members are also read as `any` instead of their known types, leading to unexpected functionality.

```rs
use serde::{Deserialize, Serialize};

fn main() {
	let a: A = A::VarA{mem: 1};
	let b: B = B::VarB{mem: 2};

	let a_json = serde_json::to_string(&a).unwrap();
	let b_json = serde_json::to_string(&b).unwrap();

	let a: A = serde_json::from_str(&a_json).unwrap();
	let b: B = serde_json::from_str(&b_json).unwrap();
}

#[derive(Debug, Serialize, Deserialize)]
pub enum A {
	VarA {mem: usize },
	VarB {mem: usize },
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(tag = "state")]
pub enum B {
	VarA {mem: usize },
	VarB {mem: usize },
}
```

**Comment by dtolnay** [comment]
This is intentional, since the "enum" type in the serde data model (i.e. the thing that `deserialize_enum` deals with) specifically refers to the externally tagged notion of enums, where the variant can always be figured out without inspecting any of the contents of the variant.
