### ISSUE TITLE
#[serde(default)] for Vec<_> with null values

### ISSUE THREAD

**Issue by xamgore** [serde-rs/serde#2173]
With the following code:

```rust
#[derive(Debug, Deserialize, Default)]
pub struct Obj {
  #[serde(default)]
  pub b: Vec<At>,
}

#[derive(Debug, Deserialize)]
pub struct At { pub name: String }

fn main() {
    let json = "[{ b: null }]";
    let jd = &mut serde_json::Deserializer::from_str(json.as_str());
    let res: Vec<Obj> = serde_path_to_error::deserialize(jd)?;
}
```

> Error: [0].b: invalid type: null, expected a sequence at line 1 column 3156

It seems to me `serde(default)` should set `b == Vec::new()`, should not it? `null` is equivalent to an omitted key in my sense.

**Comment by dtolnay** [comment]
I think this is behaving correctly. `serde(default)` describes what to do if a key is not present. If the key is present, the value is deserialized into the type specified by your struct, and `null` is not a valid value of type Vec.
