### ISSUE TITLE
Have derive macro to derive NoSerialize that returns serde::Error

### ISSUE THREAD

**Issue by bobyangyf** [serde-rs/serde#2183]
With erased serde, we can now mark traits as `Serialize`, which forces each implementer to implement `Serialize`.
However, due to object safety and serde being its own crate, it's not possible at the trait level to provide defaults that types are not serializable. This forces each implementer of traits to derive or implement Serialize, even though it may be reasonable that some implementers of the trait is not Serializable. 

Is it reasonable to offer a `derive(NoSerialize)`, such that there is a consistent and succinct way so types can satisfy the erased serde trait requirement while not being serializable?

**Comment by dtolnay** [comment]
I'd prefer not to build this into serde_derive because I don't think it would end up being sufficiently pervasively used. But another proc macro crate could provide that derive macro.
