### ISSUE TITLE
Safety: can create a `Buf` w/ arbitrary bytes that can be `unsafe`ly interpreted as a `str` via `str:from_utf8_unchecked()`

### ISSUE THREAD

**Issue by dconnolly** [serde-rs/serde#2184]
The latest release allows one to create a `Buf` via `Buf::new()` that will set an arbitrary, possibly invalid UTF-8 slice of bytes. You can then process these bytes `unsafe`ly via `Buf::as_str()`, which also does not check that the bytes are valid UTF-8.

https://github.com/serde-rs/serde/compare/v1.0.133...v1.0.136

![](https://user-images.githubusercontent.com/552961/151268835-65e21890-d79e-4551-97e0-1bbbd2f29ab0.png)

Example (`0xfe` is invalid UTF-8):
```rust
let bytes = [0xfe];
let buf = Buf::new(&mut bytes);
let bad_str = buf.as_str();
```

One /can/ use this safely, but a `# Safety` mention would be good to have for safe usage of `Buf`. 

Thank you for `serde`!

**Comment by dtolnay** [comment]
I believe this code is correct and sound. The initial contents of the buffer is not relevant, only the parts overwritten by Write::write_str, which is always UTF-8.
