### ISSUE TITLE
Question about typo in yaml

### ISSUE THREAD

**Issue by manfredlotz** [serde-rs/serde#2189]
I am using serde_derive to read a yaml file and want to notice if there is a typo in the YAML file.

Here a minimal example:

```
use serde::{Serialize, Deserialize};

#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct Config {
    pub host: String,
    pub port: Option<u32>
}


fn main() {
    let yaml =
    "
---
host: www.blabla.com
pord: 42000
";
    println!("{}", yaml);

    let playbook = serde_yaml::from_str::<Config>(&yaml);
    println!("<<< {:?}", &playbook);
}
```

Output is

`<<< Ok(Config { host: "www.blabla.com", port: None })`

Reason is that there is a typo in the YAML source: pord instead of port. This is something unintended by the creator of the YAML file.

Question: Is there a way to get an error if that happens?

**Comment by Mingun** [comment]
You looked for [`deny_unknown_fields`](https://serde.rs/container-attrs.html#deny_unknown_fields):

```rust

use serde::{Serialize, Deserialize};

#[derive(Debug, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Config {
    pub host: String,
    pub port: Option<u32>
}


fn main() {
    let yaml =
    "
---
host: www.blabla.com
pord: 42000
";
    println!("{}", yaml);

    let playbook = serde_yaml::from_str::<Config>(&yaml);
    println!("<<< {:?}", &playbook);
}
```
[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=da303188e8d99d24ea4902c53cd7adb9)

**Comment by manfredlotz** [comment]
Yes, indeed. Thanks a lot for your quick help!
