### ISSUE TITLE
Cannot skip serialization of Option<T>

### ISSUE THREAD

**Issue by seguidor777** [serde-rs/serde#2192]
Hi,

I'm having a problem with this code

```rust
#[derive(Apiv2Schema, Debug, Default, Deserialize, Serialize)]
pub struct HttpResponse<T> {
    pub code: u16,
    #[serde(skip)]
    pub data: Vec<u8>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub body: Option<T>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub validation_errors: Vec<ValidationError>,
}
```

The fields which call the skip_serializing_if are skipped correctly except the one of type Option\<T\>, I don't know if the fact of wrapping a generic affects the skip for that option. Can you tell me know how could I fix?

**Comment by seguidor777** [comment]
I tried to make a [minimal reproducible example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=f3c38189c7d6689ec892d977e888e042), but I could'nt reproduce it, it works as expected
The difference is that I'm not using the actix_web crate in the example, it makes me assume that this is most related to how actix_web serializes the structs. Can you please let me know if my assumption is correct?

**Comment by seguidor777** [comment]
I found what the problem is. Somewhere in my code, I am setting the option value to `Some(())`, which causes the condition to never be met. Can you tell me what condition should I use in the `skip_serializing_if` call so that I can skip those values as well?
[example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=cfe37e4ea5a31b0a3b6fe7af8b4bf11e)

**Comment by Lucretiel** [comment]
Because the response is generic over any T, you need to introduce some traits for T that can be used to define when a non-null body should be skipped. One simple example:

```rust
fn skip_when_default<T>(value: &Option<T>) -> bool
    where T: Eq + Default
{
    value
        .as_ref()
        .map(|v| *v == T::default())
        .unwrap_or(true)
}
```

This function will skip options that are `None`, or that are `Some` the default value for T. This means that things like `()`, `0`, `””`, or `vec![]` will all be skipped.

**Comment by seguidor777** [comment]
Thanks @Lucretiel this is the solution that I needed. I updated my [code example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=e5104da0128f075954bc0237067d1597)
For anyone looking to do something like this
