### ISSUE TITLE
Should have a specialized deserialize_xxx function for enum field.

### ISSUE THREAD

**Issue by lcy03406** [serde-rs/serde#220]
For now, when deserializing variants, the __Field::deserialize just calls the 'dynamic' version of deserialize, with a visitor that accepts usize or string.
The problem is, some protocol doesn't have type information on wire format and completely relies on the generated code. The deserizalizer needs to know that it should parse an enum field.
So I think it's better to have a specialized deserialize_enum_tag().

**Comment by pwoolcoc** [comment]
+1 on this. @erickt, would I be correct in assuming that, until something like this was put in, deserializing a struct with an enum field would not be possible? I have been trying to find a way around that for a few days now.

**Comment by lcy03406** [comment]
@pwoolcoc , My workaround is to add a flag in my Deserializer to indicate that it should deserialize an enum, and set/unset the flag before/after visit_variant.
In the visit() function, if the flag is set, then deserialize a u32 and feed it to the visitor, or else the flat is not set, I just panic of unimplemented because my protocol really needs the type information. If you wish, you can also implement your own dynamic visit here in the else part.

**Comment by erickt** [comment]
We recently landed https://github.com/serde-rs/serde/pull/223, which added a deserialize_struct_key hint. Would that work for this?

**Comment by erickt** [comment]
Closing because I believe this is satisfied by #223. Please reopen if this is not the case!

**Comment by jwilm** [comment]
Note that the hint is now `deserialize_struct_field`

**Comment by erickt** [comment]
Ah, right. If you do need similar functionality for the enum variant, you can also use the `VariantVisitor::visit_variant` to see that the next value should be parsed out as a variant name.
