### ISSUE TITLE
Net addresses in no_std environment

### ISSUE THREAD

**Issue by Felix-El** [serde-rs/serde#2202]
I'm writing a crate that should support `std` and embedded use equally.
Part of the job is to offer serialization/deserialization of addresses which currently live in `std::net`.

I found that people are working on moving these types into `core::net` (https://github.com/rust-lang/rfcs/pull/2832)
sometime soon, however that has not landed, yet, and it is not clear when this will happen.
In the meantime, someone has created the `no-std-net` crate, which transparently re-exports types such as `Ipv4Addr` from `std` when available. With the `std` feature disabled, the crate exports its own set of types replicating the official ones.

I'm wondering if we could change `serde` to import the address types from `no-std-net` instead of `std::net`, so that serialization/deserialization of addresses could be offered in `std` and `no_std` environments transparently.
(I'd prepare a MR if that is generally appreciated.)

**Comment by dtolnay** [comment]
I don't think `no-std-net` is mature enough for Serde to publicly add a dependency on it.
