### ISSUE TITLE
maybe I can design an input to make this crate stackoverflow?

### ISSUE THREAD

**Issue by Ren-ZY** [serde-rs/serde#2207]
Hello! 
I have found a lot of recursive functions in **serde/serde_derive/src/internals/receiver.rs**, line 75
one example is **visit_type_mut -> visit_type_mut_impl -> visit_type_mut** 
Maybe I can design an **nested** input to make this recursive function **recursive deeply** and cause **stackoverflow error**?

**Comment by dtolnay** [comment]
Yes.
