### ISSUE TITLE
Allow extraction of the original error when using `try_from`

### ISSUE THREAD

**Issue by GeeWee** [serde-rs/serde#2211]
# Problem
When using `try_from` we have error classes that are generated, that contain more information than is just listed in the `Display` method. This could be extra information about what failed, or a HTTP status code that corresponds to a given error.

I would like to be able to use `#[serde(try_from = "SomeIntermediateStruct")]`, however the try_from mechanics seem to discard the original error, and maps it to a serde error only using the display trait.

Some way of retrieving the original error would be wonderful - perhaps using `error.source()` to get the underlying error thrown from `TryFrom`.

Allow me to demonstrate with an example that I would like to pass
```rust
use serde::Deserialize;
use std::fmt;
use std::fmt::Debug;

#[derive(Debug)]
pub struct MyError {
    pub message: String,
    pub some_other_property_that_is_important: i32,
}

impl fmt::Display for MyError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.message)
    }
}

impl std::error::Error for MyError {}

#[derive(Deserialize, Debug)]
#[serde(try_from = "Intermediate")]
pub struct Final {
    pub foo: String,
}

#[derive(Deserialize, Debug)]
pub struct Intermediate {
    pub foo: String,
}

impl TryFrom<Intermediate> for Final {
    type Error = MyError;

    fn try_from(_value: Intermediate) -> Result<Self, Self::Error> {
        Err(MyError {
            message: "error message".to_string(),
            some_other_property_that_is_important: 123,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;
    use std::error::Error;

    #[test]
    fn try_to_get_origin_error() {
        // Try parsing through intermediate model using try_from
        let result: Result<Final, _> = serde_json::from_value(json!({"foo": "foo"}));

        // This will return an error because the try_from fails
        let error = result.unwrap_err();

        // However at this point I've lost the original error property "some_other_property_that_is_important"
        // I would like to access it - I would think that error.source() would provide it here.
        let source = error.source();
        assert!(source.is_some()); // I would like this to pass
    }
}
```

**Comment by SuperFluffy** [comment]
This issue just bit me - I couldn't figure out why my eyre backtraces stopped at the `Display` message of my error and didn't report the underlying issue. Turns out, it's how the `try_from` attribute handles errors.

My workaround for now is to do a custom `Deserialize` implementation for my type and call the intermediate types (the ones used in `try_from`) manually.

**Comment by dtolnay** [comment]
The `try_from` attribute generates almost no code; basically this:

```rust
impl<'de> Deserialize<'de> for Final {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        <Intermediate as Deserialize>::deserialize(deserializer)
            .and_then(|value| TryFrom::try_from(value).map_err(serde::de::Error::custom))
    }
}
```

so if you want to customize exactly how the TryFrom impl's error type is turned into a serde error, I think it would be reasonable to handwrite a Deserialize impl to handle that.

**Comment by GeeWee** [comment]
I think that's also reasonable if you want to customize how the error is reported. However what I'm asking for here is for serde to populate `error::source` with the underlying error for retrieval later - not customizing the creation of the serde error. Doesn't that seem like a reasonable default?

**Comment by JulesGuesnon** [comment]
Hey! I tried using the method you mentioned @dtolnay , but in my case the error gets overridden by the error of an untagged enum (`data did not match any variant of untagged`). It would be really cool to have the underlying error being bubble up to be able to understand why the data did not match any variant (in my case)
