### ISSUE TITLE
How to hide a field

### ISSUE THREAD

**Issue by irevoire** [serde-rs/serde#2219]
Is there a way to hide a field akin to what we can do in [clap](https://docs.rs/clap/latest/clap/struct.Arg.html#method.hide).

Here is my structure;
```rust
#[derive(Deserialize, Debug)]
#[serde(deny_unknown_fields)]
pub struct Search {
  query: Option<String>,
  #[serde(default = "false")]
  limit: usize,
  #[serde(default = "false")]
  experimental: bool,
}
```

And when I receive an unknown field, the following error message is thrown, which is great;
```
Query deserialize error: unknown field `plouf`, expected one of `query`, `limit`, `experimental`.
```

But I would like to hide the `experimental` field from the error message.

I was looking for something like that:
```rust
pub struct Search {
  ...
  #[serde(default = "false", hide)]
  experimental: bool,
}
```
But it doesn’t exist. Did I miss something?

**Comment by Mingun** [comment]
There is not such attribute. I think it would be useless mostly. You can use an [`expecting`](https://github.com/serde-rs/serde/pull/1916) attribute to override default serde error message:
```rust
#[derive(Deserialize, Debug)]
#[serde(deny_unknown_fields)]
#[serde(expecting = "expected one of `query`, `limit`")]
pub struct Search {
  query: Option<String>,
  #[serde(default = "false")]
  limit: usize,
  #[serde(default = "false")]
  experimental: bool,
}
```

**Comment by dtolnay** [comment]
Yeah there isn't an attribute for this.

I would recommend handwriting the Deserialize impl for `Search` to have full control over the error reporting.
