### ISSUE TITLE
Optimize buffer handling

### ISSUE THREAD

**Issue by DemiMarie** [serde-rs/serde#2223]
For large data streams, the fastest approach available is asynchronous direct I/O.  This requires manual buffer management, which needs to be optimized.  Furthermore, one can parse and serialize much faster into large buffers than small ones, as many bounds checks can be skipped.

I suggest providing APIs that take what is effectively some sort of chunk iterator.

**Comment by dtolnay** [comment]
I think I would prefer not to build this into serde. But I would be interested to hear if you pursue this in a different Rust serialization library.

**Comment by DemiMarie** [comment]
> I think I would prefer not to build this into serde. But I would be interested to hear if you pursue this in a different Rust serialization library.

Why is this?  Serde’s main advantage is the huge number of codecs that are compatible with it, and building my own library would lose that advantage.  I also do not have the time to build one myself.

“I don’t have time,” and ”I don’t want to,” are very much valid responses, but I am curious if there are technical reasons why this would be a poor fit for Serde, and if so, what those reasons are.  That might inform me of something I missed when creating this issue.
