### ISSUE TITLE
Is this an opportunity to expand on which types serde deserializes?

### ISSUE THREAD

**Issue by EdmundsEcho** [serde-rs/serde#2225]
## Quick-check

If there is a "built-in" way to serialize and deserialize the following Rust type, 
```rs
pub enum Purpose {
    Subject = 0,
    Quality = 1,
}
```
...using:
```json
[{
   "purpose": "quality"
},
{
   "purpose": "subject"
}]
```
Similarly, the following Rust type 
```rs
pub struct Uuid {
    #[prost(bytes="vec", tag="1")]
    pub uuid: ::prost::alloc::vec::Vec<u8>,
}
```
... using
```json
 "uuid": [247, 77, 52, 211, 77, 52, 211, 77, 52, 211, 77, 52] 
```
... or
```json
"uuid": "00000000"
```

Then "never-mind" :))  Otherwise,

Serde is "tried and true", and just plain powerful and well designed. So, carefully treading onward and ready to wrong... 

## The core idea
Is there a basis for having serde include the above types as "officially" supported without having to "roll-your-own"?  I put forward more than just a qualitative, but perhaps a formal way to articulate the implied contract between serde and the Rust community.

## Where I am

One way I have come to "model" my using serde: 
> A way to cast a Rust type to "some recordable equivalent"; equivalent by way of the information each encodes

## One specification for what I mean by "Equivalent"  

I'm using the term "equivalent" because the composition of the two functions deserialize and serialize is an equivalent of the identity function. If it is an "identity function" of sorts, then I should be able to apply it to all serializable Rust type. 

From the perspective of Rust (not from json), depending on the context, we have choices on how to accomplish its namesake "serde" (full circle where depending on the context, the "in-between" representation is an implementation detail).  

There are a lot of good reasons to choose json.  Of course, this is not how "we came to serde", first came json then serde.  Strictly speaking, from the perspective of Rust and the task, it could have been serde_json, serde_toml etc... (but importantly, **not** serde_stream, serde_text).  

From this "serde" (as crate)'s perspective, choosing json is also an "implementation detail".  In fact, is how serde describes itself per the first line I believe in [the docs](https://serde.rs/):  

> Serde is a framework for ***ser***ializing and ***de***serializing Rust data structures efficiently and generically.

That the Rust community chose "serde" as the defacto choice to host serializable information, and "serde" landed on json (as the default) is a coincidence and a property that comes from the popularity of json, nothing else.

## `serde` as an identity function

From the perspective of the identity function, something I can only sketch using pseudo code: 

```rs
fn identity(parseThisJson: Json) -> (writeThisJson: Json) {
  let myRustValue = deserialize(parseThisJson);
  serializeThisValue(myRustValue)
}
```
Using whatever amount of blurry eyes required to "equate" the types, I could start thinking about each half of this round trip as a "cast" (of sorts, different memory etc... but conceptually useful).  In fact, I could argue that the really nice thing about `serde` is how well built it is to cast my Rust type to some sort of `json` artifact, and vice-versa.

## The line between `serde` and a parser

The exercise of how I'm describing a "cast" is different than "parsing".  As `serde` makes clear in the docs (somewhere I can't seem to find), while serde can take on attributes of a parser, it isn't a parser. "the subject of" a parser can be json, but is much broader. 

But, nor should I underestimate how flexible and powerful serde is in its ability to effectively "parse" json.  

## The motivation for "enhancing" the built-in "power" of serde 

Because json can encode the same information using different combinations of json types, decisions need to be made. 

### Where it makes sense for serde to "encapsulate the decision"

When it's possible to represent our Rust types in more that one way using json, we have a decision.  Which decisions can be made "ahead of time" may be solid candidates for building the functionality into `serde`.  In other words, less a feature, but more "a must" to deliver on the `serde`'s "contract" implied by its namesake (and self-described intent).

So, what to use as a basis for where and how to make a decision.  

#### Canonical is likely too broad - insufficient to "decide ahead of time"

While "canonical" by definition means "the preferred" or "obvious" choice, according to webster: 
> a general rule or standard

To the degree "canonical" depends on the context,  then "canonical" might not be "powerful" enough to decide ahead of time what is "right or wrong". So, `serde` bakes in a means for the end user to "make a choice" (e.g., internal and external tags, flatten and the like).

#### Limit to what "other possibilities" need be supported

Canonical also implies a choice among other possibilities. Any type that can be reduced to a combination of an already supported type, is out of scope. 

A trivial case in point, `serde` need only support key::primitive, value::primitive hosted in an object to represent the following

```json
{
   "string": "string",
   "string": "string",
}
```

### Where serde supports mutliple representations

One way to capture the scope of the problem; when there is more than one valid function to accomplish the following (where a valid function has a 1:1 relationship between input and output):
```rs
fn rust -> json
```

The serde docs on [structs and enums](https://serde.rs/json.html) captures where a choice was required, and it's preferred choice; promoted by way of "a convention".  I suspect these conventions are what is used when I ask serde "to derive" an approach for my Rust types.  Similarly, a lot of impressive work to manage the [different json represenations](https://serde.rs/enum-representations.html) of a Rust enum.

The focus of mine is not on the which choice is "the convention", but rather, where the need arises and how serde chose to integrate this logic into the library itself; otherwise, why not have the end-user "role their own" if the user doesn't agree with with the "chosen convention"?  From the perspective of its namesake, from the Rust perspective, serde "has met the need" without the user having to do so.    

Of course, there is an obvious shortcoming to that thought process: it's not just about the round-trip `Rust -> something` and `something -> Rust`, but broader than that. Somehow, someone decided it's ok to represent Rust types in json using something other than "the chosen convention".

In the preamble to this point, I have drawn additional boundaries that limit `something -> Rust`.  Where the gaps remain, and the point of this post:

For the following Rust type, 
```rs
pub enum Purpose {
    Subject = 0,
    Quality = 1,
}
```

There are two possible means by which I can represent my "casting" the type to json.  Only one of them is supported (best I can tell), by serde's built-in functionality:

*Supported*
```json
[{
   "purpose": 1
},
{
   "purpose": 0
}] 
```

*Not supported*
```json
[{
   "purpose": "quality"
},
{
   "purpose": "subject"
}]
```

Similarly, the following Rust type 
```rs
pub struct Uuid {
    /// string uuid = 1; 
    #[prost(bytes="vec", tag="1")]
    pub uuid: ::prost::alloc::vec::Vec<u8>,
}
```

...cannot be "cast" to what seems like an otherwise "fair" representations in json:

```json
 "uuid": [247, 77, 52, 211, 77, 52, 211, 77, 52, 211, 77, 52] 
```
... nor
```json
"uuid": "00000000"
```

# Conclusion and key question

Serde supports multiple ways to "fairly" encode certain types of Rust types, but not others.  The Rust "c-like" enum and Rust `bytes` could be represented in several "reasonable", non-redundant ways that are not supported by serde.

Is there a basis for having serde include these types as "officially" supported without having to "roll-your-own"?  They seem like outliers where they are otherwise similarly "perfectly valid, singularly expressed Rust types".  In other words, all things considered, it's unclear why or even how I can "roll-my own".  Furthermore, it seems to me to be more of a hack to adjust the Rust type in order to have it "fit" serde, rather than the other way around.

**Comment by dtolnay** [comment]
In way more words than this, it sounds like you are wondering whether we are interested in serde's derive macros supporting all the different possible representations that someone could dream up for any Rust data structure.

No, that is not a goal. The macros support a short list of the most commonly desired representations. People can write other macros for other representations that arise less commonly than the ones built into serde's derive, or they can implement arbitrary other representations by handwriting bespoke `Serialize` and `Deserialize` impls without a macro.

**Comment by EdmundsEcho** [comment]
Apologies for the long-winded expression of the idea. I was doubling down on my thinking to make sure I wasn't off base somewhere. 

I was hoping to make the case that in fact, there aren't an infinite number of ways to represent the information hosted in a rust type using json. 

Non-redundant, primitive combinations is what serde has *already accomplished*... except for the two examples. 

Do you know of another example of "non-redundant, primitive combination" of json types used to represent a rust value not somehow supported by serde?
