### ISSUE TITLE
the trait `common::handler::_::_serde::Serialize` cannot be made into an object

### ISSUE THREAD

**Issue by shanliu** [serde-rs/serde#2226]
```
pub struct RestJsonResult {
    code:String,
    sub_code:String,
    message:String,
    data:Option<Box<dyn serde::Serialize>>,//the trait `common::handler::_::_serde::Serialize` cannot be made into an object
}
```
how save dyn serde::Serialize to struct ?

**Comment by jonasbb** [comment]
> The usual Serde Serialize, Serializer and Deserializer traits cannot be used as trait objects like &dyn Serialize or boxed trait objects like Box<dyn Serialize> because of Rust's ["object safety" rules](http://huonw.github.io/blog/2015/01/object-safety/). In particular, all three traits contain generic methods which cannot be made into a trait object.

**Comment by shanliu** [comment]
thx
