### ISSUE TITLE
support derive for unions with from/into attributes

### ISSUE THREAD

**Issue by chlobes** [serde-rs/serde#2243]
the following code will not compile
```rust
#[derive(Deserialize)]
#[serde(from = "u8")]
union Foo {
    field: u8,
}

impl From<u8> for Foo {
    fn from(field: u8) -> Foo {
        Foo { field }
    }
}
```
(the same is true for Serialize+Into)
using these attributes, serde never has to interact with the internals of the union, it can treat it exactly like any other struct.

**Comment by dtolnay** [comment]
Is this a real use case that came up for you in real-world code, or just an observation that this might as well work?

**Comment by chlobes** [comment]
this is a real use case, I had a union that was always guarenteed to be valid and wanted to automatically derive serializing it as an array of bytes

**Comment by dtolnay** [comment]
My sense is this is sufficiently uncommon, and the handwritten impl is sufficiently straightforward, that it isn't going to make sense supporting in serde_derive.
