### ISSUE TITLE
Question: Why can't `#[serde(default)]` be applied to enums?

### ISSUE THREAD

**Issue by ahl** [serde-rs/serde#2248]
It seems like it might be viable to have `#[serde(default)]` for an `enum` that implements `Default`. I could imagine this being challenging for an externally tagged enum since the type (object or string?) isn't known *a priori*, but at least would this be viable for an internally- or adjacently-tagged enum since it they're equivalent to structs with constraints?

```rust
struct AdjacentEnum {
    tag: VariantPartOfEnum,
    contents: ContentsPartOfEnumIfItWereUntagged,
}

struct InternalEnum {
    tag: VariantPartOfEnum,
    #[serde(flatten)]
    contents: ContentsPartOfEnumIfItWereUntagged,
}
```

If any of this seems reasonable I would be happy to put together a PR.

**Comment by edgarogh** [comment]
You can use `#[serde(default)]` with any type that implements `Default` including any enum, with any serde representation. However, `#[serde(default)]` is a [field attribute](https://serde.rs/field-attrs.html#default), so you have to put it on the container field and not on an enum variant.

This is not related to the `Default` trait at all but in case there is a misunderstanding and you just want a fallback variant on your enum, use [`#[serde(other)]`](https://serde.rs/variant-attrs.html#other).

Don't hesitate to reply with additional context if I didn't answer your question.

**Comment by evbo** [comment]
Thanks @edgarogh I think `#[serdee(other)]` is an awesome way to provide a default value when an unexpected value is encountered.

Playground here demoing it, should fit the need most people are looking for in this case I think:

**Comment by seanpianka** [comment]
Perhaps this should be closed? I had a red herring in my code that led me to believe #[serde(default)] doesn't work with enums, along with a chatgpt that falsified such information as true, so we could close this as a definitive "yes, it works with enums as a field attribute." 

A new issue could be opened with a more accurate title regarding using #[serde(default)] as a container attribute.
