### ISSUE TITLE
Release case conversion as a separate crate

### ISSUE THREAD

**Issue by banool** [serde-rs/serde#2256]
Hey, I'm running into a tricky issue (https://github.com/poem-web/poem/issues/362) with another project where the snake casing behavior is a bit different between serde and the backend it uses, [inflector](https://github.com/whatisinternet/inflector). In our project we're using both Poem and serde, e.g. Poem for the API, serde for storage. I'm exploring ways to fix this, I figure one is to make Poem use the same case conversion behavior as serde (which would be more standard in general). For this though, the case conversion code (https://github.com/serde-rs/serde/blob/master/serde_derive/src/internals/case.rs) would either need to be exposed from within serde_derive, or just pulled out into a separate crate.

I wonder if you think either of these options make sense? There are other ways around this issue, but this seems to be one of the nicer ones, plus I imagine others might want this case conversion library for other reasons too.

Thanks!

**Comment by dtolnay** [comment]
That file is published to https://docs.rs/serde_derive_internals/0.26/serde_derive_internals/attr/enum.RenameRule.html.

**Comment by banool** [comment]
Okay awesome, thanks a lot, I'll take a look at using that.
