### ISSUE TITLE
serde_json documentation linked in README out of date

### ISSUE THREAD

**Issue by fuchsnj** [serde-rs/serde#226]
It looks like the documentation is for an older version of serde_json.

At least one difference are the variants of "Error" between the documentation:
https://serde-rs.github.io/serde/serde_json/serde_json/error/enum.Error.html

and the latest version of serde_json (0.6.0):
https://github.com/serde-rs/json/blob/master/json/src/error.rs#L102

**Comment by erickt** [comment]
Hello! Oops, that link to serde_json is quite old. I'll remove it. Try this [one](https://serde-rs.github.io/json/serde_json/error/enum.Error.html) instead.
