### ISSUE TITLE
Unable to discriminate  enum variants by tag for flattened contained enum

### ISSUE THREAD

**Issue by bjeanes** [serde-rs/serde#2260]
This is a hard one to explain, so here is a playground link with some structs and tests: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=2cc36040116bcc6c379a2bf7ee675ef1

The idea here is to decode the following json objects:

```json
{"type": "u32", "scale": 2}
{"type": "array", "of": "u32", "scale": 2, "length": 10}
{"type": "string", "length": 10}
```

However, because `type` of "array" and "string" comes from the tag of an inner variant, it appears to be unable to discriminate between "array" and "string" in some cases (when optional fields `of` and `scale` are absent, for instance).

I am aware that untagged enums carry the risk of failing to distinguish between variants with similar fields, but in this case the `type` is always present and _serializes_ correctly. The enums can't be combined and flattened at the type level, because some fields like `scale` and `offset` cannot exist on the string type.

I thought I'd open this in case this is a solvable bug but assuming this is just a sharp edge of untagged enums, I'll try to shuffle my types around to work around this.

**Comment by Mingun** [comment]
This is because `#[serde(tag)]` has no meaning on `struct`s, but the derive macro silently accept it. So actually your `RegisterString` and `RegisterArray` types are indiscernible

**Comment by bjeanes** [comment]
I see. That makes sense. I think the fact that generated a `type` field in the output even though it has no meaning must have confused me here. Since it didn't error nor no-of, I thought it must be valid.

Honestly, I have been struggling to write types to represent this document structure such that `scale`/`offset` can be specified for array and numeric types but not string, while restricting the types the array can contain to also exclude string. It's kinda doing my head in.

If you happen to have an idea, I would appreciate it but otherwise thanks for setting that straight!
