### ISSUE TITLE
Unite structs with similar paths through flatten doesn't work

### ISSUE THREAD

**Issue by BratSinot** [serde-rs/serde#2261]
Greetings!

The problem is that I can't split structure into several structures and unite them through flatten.
P.S. `serde_json` is just to show the problem. I faced with it using `config` crate.

```rust
#[derive(Debug, serde::Deserialize)]
struct First {
    path: Path0,
}

#[derive(Debug, serde::Deserialize)]
struct Path0 {
    begin: Box<str>,
}

#[derive(Debug, serde::Deserialize)]
struct Second {
    path: Path1,
}

#[derive(Debug, serde::Deserialize)]
struct Path1 {
    end: Box<str>,
}

#[derive(Debug, serde::Deserialize)]
struct Unite {
    #[serde(flatten)]
    first: First,
    #[serde(flatten)]
    second: Second,
}

fn main() {
    let json = serde_json::json!({
        "path": {
            "begin": "too",
            "end": "not_too",
        }
    });

    let data = serde_json::from_value::<Unite>(json);

    println!("{data:?}");
}
```

**Comment by edgarogh** [comment]
The error message is clear: "Err(Error("missing field `path`", line: 0, column: 0))"

Through flattening, the `Unite` struct looks like this from serde's point of view:

```rs
struct Unite {
    // From flattening First
    path: Path0,

    // From flattening Second
    path: Path1,
}
```

You have the same field declared twice (I don't even know if serde is supposed to handle this), and you're not even giving a field named "path" to your deserializer. So it obviously fails.

**Comment by BratSinot** [comment]
> You have the same field declared twice (I don't even know if serde is supposed to handle this), and you're not even giving a field named "path" to your deserializer. So it obviously fails.
The reason was clear, it doesn't clear how to deal with it.

> Did you forget to flatten `First::path` and `Second::path`? Did you forget a `#[serde(transparent)]` on any of these structs?
I add fully working example in first message (it uses `serde` and `serde_json`).
With `#[serde(transparent)]`:
```rust
#[derive(Debug, serde::Deserialize)]
#[serde(transparent)]
struct First {
    path: Path0,
}

#[derive(Debug, serde::Deserialize)]
#[serde(transparent)]
struct Path0 {
    begin: Box<str>,
}

#[derive(Debug, serde::Deserialize)]
#[serde(transparent)]
struct Second {
    path: Path1,
}

#[derive(Debug, serde::Deserialize)]
#[serde(transparent)]
struct Path1 {
    end: Box<str>,
}

#[derive(Debug, serde::Deserialize)]
struct Unite {
    #[serde(flatten)]
    first: First,
    #[serde(flatten)]
    second: Second,
}
```
gives error:
```log
Err(Error("can only flatten structs and maps", line: 0, column: 0))
```

**Comment by edgarogh** [comment]
I think I understand, but this looks very weird and I'm not even sure there is a solution. Why do you need to split a deserialize struct in 2 like this ? It's much simpler to just do:

```rs
#[derive(Debug, serde::Deserialize)]
struct Path {
    #[serde(flatten)]
    first: First,
    #[serde(flatten)]
    second: Second,
}


#[derive(Debug, serde::Deserialize)]
struct Unite {
   path: Path,
}
```

And depending on your use case, you should take a look at [figment](https://docs.rs/figment/latest/figment/), another deserialization library (made for configuration files), partially based on serde, that can resolve multiple "layers" of configuration exactly like what you're trying to do. The [Rocket](https://rocket.rs) web server uses it to allow fairings (extensions) to read from the same configuration file as rocket.

**Comment by BratSinot** [comment]
> It's much simpler to just do:

It's not an option for my case, because I have struct with generic.

> you should take a look at [figment](https://docs.rs/figment/latest/figment/), another deserialization library

Hm, thanks, I'll take a look. I use `config` crate, seems that I can use `figment` instead of `config`. I'll definitely take a look if `figment` solve my problem.

**Comment by Mingun** [comment]
Why you try to flatten fields that are effectively `Box<str>` (because of `flatten`)? Of course this will not work, because string has no internal structure.

Your struct equivalent to this:
```rust
#[derive(Debug, serde::Deserialize)]
struct Unite {
    #[serde(flatten)]
    first: Box<str>,
    #[serde(flatten)]
    second: Box<str>,
}
```

**Comment by BratSinot** [comment]
> Why you try to flatten fields that are effectively `Box<str>` (because of `flatten`)?

Sorry, what?
I'm flattening `struct First` and `struct Second` which give that (as @edgarogh already said #issuecomment-1232005440) it comes into this:
```rust
struct Unite {
    // From flattening First
    path: Path0,

    // From flattening Second
    path: Path1,
}
```

**Comment by Mingun** [comment]
I misprinted. `#[serde(trasparent])` means that structure with one field will be serialized as only field. Actually, you can see this code after expanding macros:
```rust
#[derive(serde::Deserialize)]
#[serde(transparent)]
struct First {
    path: Path0,
}
```
turns into
```rust
#![feature(prelude_import)]
#[prelude_import]
use std::prelude::rust_2021::*;
#[macro_use]
extern crate std;
#[serde(transparent)]
struct First {
    path: Path0,
}
#[doc(hidden)]
#[allow(non_upper_case_globals, unused_attributes, unused_qualifications)]
const _: () =
    {
        #[allow(unused_extern_crates, clippy :: useless_attribute)]
        extern crate serde as _serde;
        #[allow(unused_macros)]
        macro_rules! try {
            ($__expr : expr) =>
            {
                match $__expr
                {
                    _serde :: __private :: Ok(__val) => __val, _serde ::
                    __private :: Err(__err) =>
                    { return _serde :: __private :: Err(__err) ; }
                }
            }
        }
        #[automatically_derived]
        impl<'de> _serde::Deserialize<'de> for First {
            fn deserialize<__D>(__deserializer: __D)
                -> _serde::__private::Result<Self, __D::Error> where
                __D: _serde::Deserializer<'de> {
                _serde::__private::Result::map(_serde::Deserialize::deserialize(__deserializer),
                    |__transparent| First { path: __transparent })
            }
        }
    };
```
Apply chain of that transformations, in the end your struct serialized the same as
```rust
#[derive(Debug, serde::Deserialize)]
struct Unite {
    #[serde(flatten)]
    first: Box<str>,
    #[serde(flatten)]
    second: Box<str>,
}
```
and in that case `flatten` is impossible to work because absence of the internal structure of a string.

**Comment by BratSinot** [comment]
Okey, for now I use this workaround:

```rust
impl<'de> Deserialize<'de> for Unite {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let value = Value::deserialize(deserializer)?;

        let first = First::deserialize(&value).map_err(D::Error::custom)?;
        let second = Second::deserialize(value).map_err(D::Error::custom)?;

        Ok(Self { first, second })
    }
}
```

**Comment by Mingun** [comment]
You just need to remove `#[serde(flatten)]`

**Comment by BratSinot** [comment]
> You just need to remove `#[serde(flatten)]`

```rust
#[derive(Debug, serde::Deserialize)]
#[serde(transparent)]
struct First {
    path: Path0,
}

#[derive(Debug, serde::Deserialize)]
#[serde(transparent)]
struct Path0 {
    begin: Box<str>,
}

#[derive(Debug, serde::Deserialize)]
#[serde(transparent)]
struct Second {
    path: Path1,
}

#[derive(Debug, serde::Deserialize)]
#[serde(transparent)]
struct Path1 {
    end: Box<str>,
}

#[derive(Debug, serde::Deserialize)]
struct Unite {
    first: First,
    second: Second,
}
```

```log
Err(Error("missing field `first`", line: 0, column: 0))
```

**Comment by dtolnay** [comment]
The solution in https://github.com/serde-rs/serde/issues/2261#issuecomment-1235272468 looks good to me!
