### ISSUE TITLE
Testing `DeserializeSeed` using `serde_test`

### ISSUE THREAD

**Issue by Anders429** [serde-rs/serde#2262]
Is there any way to test types that implement `DeserializeSeed`, as opposed to `Deserialize`, using the `serde_test` crate? I am looking for some equivalent of `assert_de_tokens`, but that would accept the seed as well to test stateful deserialization. Perhaps something like a `assert_de_seed_tokens` or similar?

I would love to know if such a thing exists or if there are any workarounds that can be used to test `DeserializeSeed` types with the current tools.

**Comment by Shatur** [comment]
Encountered the same issue and tried to deserialize into tokens manually. But [de](https://github.com/serde-rs/serde/blob/master/serde_test/src/de.rs) module is private despite that [Deserializer](https://github.com/serde-rs/serde/blob/d208762c81883a181e8c6a9ca3f303e040105c7d/serde_test/src/de.rs#L11) itself is `pub`. Maybe make this module public?

**Comment by dtolnay** [comment]
I notice https://github.com/Anders429/serde_assert now exists. Thanks!
