### ISSUE TITLE
How can I serialize a function return value

### ISSUE THREAD

**Issue by hoijui** [serde-rs/serde#2264]
I have a struct, which has fields, and associated functions.
I want to serialize the return value of one of these functions (with &self as the only argument), in addition to the fields.
How can I do this?

Is it possible to annotate a function so its return value gets serialized like a field?

**Comment by edgarogh** [comment]
For reference, functions associated to structs are called _methods_.

If you want a method to provide the value for a deserialized field, I'm afraid you'll have to implement [`Serialize`](https://serde.rs/impl-serialize.html) yourself on your entire struct.
