### ISSUE TITLE
Unable to serialize/deserialize `std::io::Error`

### ISSUE THREAD

**Issue by pradyumnar-sahaj** [serde-rs/serde#2268]
I am trying to implement a custom error with `thiserror` that needs to implement a serialization trait. 
The custom error needs to translate errors for `std::io::Error` into the custom`PrintError`
```rust
#[derive(Error, Debug, Serialize, Deserialize)]
pub enum PrintError {
  #[error("Connection Error: ")]
  Connection(#[from] std::io::Error)
}
```

But doing so gives the following error:
```
Connection(#[from] std::io::Error)
    |      ^ the trait `Serialize` is not implemented for `std::io::Error`
```

Given that `std::io::Error` is from the standard library, I won't be able to implement a custom Serialize/Deserialize in my project.

Is there a workaround for this?

**Comment by edgarogh** [comment]
You can use [`#[serde(with = "...")]`](https://serde.rs/field-attrs.html#with) to implement you own serialization routines for a specific field (here, `PrintError::Connection.0`). [`#[serde(remote = "")]`](https://serde.rs/remote-derive.html) might come in handy too.

**Comment by pradyumnar-sahaj** [comment]
I implemented serialization like so:
```rust
#[derive(Error, Debug)]
pub enum PrintError {
  #[error("Not able to connect")]
  ConnectionFailed(#[from] std::io::Error)
}

impl Serialize for PrintError {
  fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
      where
          S: serde::Serializer {
      serializer.serialize_str(self.to_string().as_ref())
  }
}
```

Is this approach okay?

**Comment by edgarogh** [comment]
If you only need to serialize your error in human-readable format (no further processing later), this looks good to me. I haven't checked if it compiles but I guess it does :sweat_smile:
