### ISSUE TITLE
Unable to add #[derive(Serialize)] to struct in 3rd party library so I can't serialize whole struct

### ISSUE THREAD

**Issue by darkSuperman** [serde-rs/serde#2271]
I have a trouble. If I have a struct that needs to be serialized, a field in this struct is a struct type in a third-party library, but I can't add #[derive(Serialize)] to the struct in the third-party library, so I can't serialize the whole struct.

 
#[derive(Serialize)]
struct Simple {
   one:String,
   two:Oid     //struct in 3rd party library, without #[derive(Serialize)], I can't add
}
 

 

Is there any way to solve this problem at the moment, I checked most of the issues and didn't find a similar problem, thanks

**Comment by edgarogh** [comment]
The docs have a page dedicated to this specifically: https://serde.rs/remote-derive.html
If `Oid` doesn't have its fields public, you can also use [`#[serde(with = "...")]`](https://serde.rs/field-attrs.html#with) to implement the serialization/de-serialization yourself with your own function. Finally you could wrap `Oid` in you own newtype and implement `Serialize`/`Deserialize` yourself.

You're not telling which crate `Oid` comes from so I won't be able to help you more.

**Comment by darkSuperman** [comment]
Thanks for the recovery so I can find a solution to my problem :)
