### ISSUE TITLE
Merge two deserializers into one

### ISSUE THREAD

**Issue by leviska** [serde-rs/serde#2274]
I have two different deserializers, each one of which fills some of the fileds of the struct.
The simplest similar example is this: imagine I have two jsons, which must fill the fields of one struct:
```rust
#[derive(Debug, serde::Serialize, serde::Deserialize)]
struct Foo {
    foo: i32,
    bar: i32,
}

fn main() {
    let foo: Foo = serde_json::from_str(r#"{"foo":3}"#).unwrap();
    let bar: Foo = serde_json::from_str(r#"{"bar":4}"#).unwrap();
    dbg!(foo);
    dbg!(bar);
}
```
But this code panics, because in the first string `bar` not found and serde can't initialize the struct correctly. We could implement default and add `serde(default)`, but there will be two structs, which we will need to merge, and also there might be a case with some enums, where `default` is not trivial (and in my case for other reasons it's hard to do)

What I'm asking is there any way to make a deserializer, which will merge two other? Like, in this example, for each field we can try deserialize it with first one, and if it fails, try to do it with the second one.

**Comment by jonasbb** [comment]
This is not something directly supported by serde. As a workaround it might be possible to deserialize a Value type, merge the two values and use that to deserialize the final value. You can also check how other libraries are doing that, for example https://crates.io/crates/config.

**Comment by leviska** [comment]
That works only for `serde_json`(?), but in my example sadly it's actually two different deserializers (one is json and one is path extractor from actix)
Is there something stopping me in making custom deserializer, which will visit fields one by one with other deserializers?
I haven't written any code for serde, but from docs it seems that this might work

**Comment by leviska** [comment]
Aha, I see
The problem is that deserializer works by calling visitor function, which takes the visitor and returns value (or error)
And you can't call it twice sadly (because it doesn't implement copy)
Basically deserialization inside works the same way as deserializing the struct: it should return the whole struct or an error, and we've come the full circle to the original question
I guess there only one option indeed, it is to make some temporary values (like `serde_json::Value` or straight the structs themselves)
If I'm right and there's nothing else to do, I guess you can close the issue(?)

**Comment by kangalioo** [comment]
Yes, a Deserializer invokes `visit_map(map: impl MapAccess)`. We have two Deserializer's, but need both MapAccess instances to build the struct. Hence we need a temporary storage
