### ISSUE TITLE
Is there a way to serialize an Option::None to a visible value instead of and empty string

### ISSUE THREAD

**Issue by mindoodoo** [serde-rs/serde#2275]
Hey all,
I'm trying to find a way to serialize a structure containing an option. However, when the option is none, the serialization is empty. Serde can still deserialize the structure correctly, however is there a simple way to tell serde to explicitly specify the None value in the serialization without implementing a custom serializer ?

**Comment by edgarogh** [comment]
Serde doesn't serialize anything itself. Are you using `serde_json` ? Something else ? You're probably not on the right issue tracker. Without more info, it's hard to understand what "null" refers to.

**Comment by edgarogh** [comment]
If you're actually using `serde_json`, I'm unable to reproduce your issue : https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=cccc48eaf1e5a3ca4f9cfac1c1d44a36 (the null is there)

**Comment by mindoodoo** [comment]
Hey @edgarogh , sorry for the delayed response.
No, I'm using the toml package in order to serialize to toml.
I am not that familiar with how serialization and what not, is this maybe more of an issue with the toml crate than serde then ?

**Comment by jonasbb** [comment]
toml does not have a representation for "null". If you want to change the handling of `None`s for in all cases you will need to look into a modified `Serializer`. If you are only concerned with a couple of places, you can write special serialization logic for these and use serde's [with-attribute](https://serde.rs/field-attrs.html#with).

**Comment by mindoodoo** [comment]
I will look into it, thank you !
