### ISSUE TITLE
Question:how to know if the struct I created Is correct for the json?

### ISSUE THREAD

**Issue by RESDXChgfore9hing** [serde-rs/serde#2276]
I am new to rust so it would be great if there is some reference.

I have a json in my mind>
{
"path":"pathtothatproj",
"defaultcmd":"cp",
"Cmdlist":[
"cp":{"windows":"someoscommand","linux":"someoscommand"},
.....

]
}

I know that I need to Strongly typed json serialize,as mentioned in the readme,as the structure is kinda predictable

here is the struct rust code I have in my mind.
//OSdependentcmdtorun
#[derive(Serialize, Deserialize, Debug)]
struct Onecmd {
windows: String,
linux: String
}

//
#[derive(Serialize, Deserialize, Debug)]
struct Config {
proj_path:String,
defaultcmd:String,
Cmdlist:Vec
}

Is it correct?
I know how to convert the str to the json*struct.let varname: Config = serde_json::from_str(data)?;
but how to create this complex struct object and become json is kinda confusing.
Any reference would be helpful.thank you.

Opened one in json repo no response,https://github.com/serde-rs/json/issues/925

so decided to ask here.

**Comment by dtolnay** [comment]
Please take your question to any of the resources shown in https://www.rust-lang.org/community. This library is one of the most widely used Rust libraries and plenty of people will be able to provide guidance about it.
