### ISSUE TITLE
Skip serialization on None on a per record basis

### ISSUE THREAD

**Issue by letto4135** [serde-rs/serde#2280]
Is it possible to optionally skip serialization?

Say I have a db query that is select * where I want all values to be serialized whether there is data or not
vs
a db query that specifies what I want selected where I only want to serialize the values that are not None...

I don't know if #[serde(skip_serializing_if = "Option::is_none")] is flexible enough for this case..

Maybe something like...

```
#[derive(Serialize, Deserialize)]
struct SomeStruct {
  value: Option<Value>
}

let mut val = SomeStruct::new();
val.skip_serialization(Option::is_none);
```

**Comment by kangalioo** [comment]
I don't understand what you're asking.

Do you have data like `[{"value": "a"}, {"value": null}, {"value": "b"}]` and want to deserialize this into `[SomeStruct { value: "a" }, SomeStruct { value: "b" }]`, i.e. filter out the null entries?

**Comment by letto4135** [comment]
@kangalioo no, if I do a select * query to the db I want to serialzie everything null or not, but if I select specific values from the db I only want to serialize those.

**Comment by dtolnay** [comment]
Hi @letto4135, sorry that no one was able to provide guidance here. If this is still an issue, you could try taking this question to any of the resources shown in https://www.rust-lang.org/community. This library is one of the most widely used Rust libraries and plenty of people will be able to provide guidance about it.

**Comment by letto4135** [comment]
I forgot about this. I did end up figuring out a really terrible way to do this, but it's been a while and I don't remember what it was exactly... I think I ended up returning either the struct itself or a built up Json object with only the fields I wanted..
