### ISSUE TITLE
derive macro error for wrong style of attribute syntax is misleading

### ISSUE THREAD

**Issue by drmason13** [serde-rs/serde#2287]
```rs
#[derive(Debug, Serialize, Deserialize)]
pub struct Config {
    download: PathBuf,
    #[serde(skip_serializing_if(Option::is_none))]
    storage: Option<PathBuf>,
    upload: bool,
}
```
The above code will cause the following compiler error:

```
error: unknown serde field attribute `skip_serializing_if`
  --> src/main.rs:10:13
   |
10 |     #[serde(skip_serializing_if(Option::is_none))]
   |             ^^^^^^^^^^^^^^^^^^^
```

however, there *is* a field attribute `skip_serializing_if`.

It would be more helpful to recognize the wrong syntax and suggest the correct syntax instead:
```
error: expected key = value syntax, e.g. `skip_serializing_if = "..."`
  --> src/main.rs:10:13
   |
10 |     #[serde(skip_serializing_if(Option::is_none))]
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I expect this will be painstaking due to the number of possible serde attributes, but the result is possible in theory.

I'd like to take a stab at implementing it if you're happy with the stated goal. I've [done similar](https://users.rust-lang.org/t/i-wrote-my-first-custom-derive-macro/57887/10?u=drmason13) for much simpler and smaller) proc macros of my own in the past.

If not, no worries. It might make serde slightly slower to compile anyway for what is only a minor papercut for beginners (or muppets such as myself) :)

**Comment by dtolnay** [comment]
As of syn 2 (serde_derive 1.0.157+), the error is better.

```console
error: expected `=`
 --> src/main.rs:6:32
  |
6 |     #[serde(skip_serializing_if(Option::is_none))]
  |                                ^
```
