### ISSUE TITLE
Can I get type name in `Deserializer` ?

### ISSUE THREAD

**Issue by Shiroi-Yuki** [serde-rs/serde#2296]
I want to implement a raw deserializer for reading file:

```rust
struct Test {
    name: u16
    follow: u16
}

let res = Test::from(&[0x12, 0x34, 0x56, 0x78]);

assert_eq!(res, Test { name: 0x3412, follow: 0x7856 });
```

In function `deserialize_struct`:

```rust
fn deserialize_struct<V>(
    self,
    _name: &'static str,
    _fields: &'static [&'static str],
    _visitor: V,
) -> Result<V::Value, Error>
where
    V: Visitor<'de>,
{
    unimplemented!()
}
```

I want to known type names of all members in this struct, beacuse the raw data is not including any type infomation. In other cases, like json, yaml or toml, we can known the type from an input string. But in this case, it's not.

I think it's possible in serde, but it's seem like not implemented.

Do anybody has plans to implement it?

**Comment by Mingun** [comment]
Is a [serde-pod](https://github.com/Mingun/serde-pod) the thing you are looking for?

**Comment by Shiroi-Yuki** [comment]
> Is a [serde-pod](https://github.com/Mingun/serde-pod) the thing you are looking for?

It's great, thanks.
