### ISSUE TITLE
Deriving Deserialize causing incorrect dead_code warnings

### ISSUE THREAD

**Issue by Kampfkarren** [serde-rs/serde#2298]
The following code:

```rs
use serde::Deserialize;

#[derive(Deserialize)]
struct X {
    filename: String,
}

fn names() -> Vec<String> {
    let files: Vec<X> = Vec::new();
    
    files.into_iter().map(|file| file.filename).collect()
}
```

...produces the following warning:

```
warning: field `filename` is never read
 --> src/lib.rs:5:5
  |
4 | struct X {
  |        - field in this struct
5 |     filename: String,
  |     ^^^^^^^^
  |
  = note: `#[warn(dead_code)]` on by default
```

Removing `Deserialize` silences the warning.

**Comment by jimvdl** [comment]
It _might_ be due to not calling `names()`. The warning goes away as soon as I add `let n = names();` even with the `Deserialize` attribute. Is this the case for you as well?

**Comment by Kampfkarren** [comment]
Maybe in this MVCE (though I haven't tested), but in the larger real case I hit, the code path was definitely being called.

**Comment by jimvdl** [comment]
Is there a reproducible example that you can link, perhaps there is a natural way to suppress it or it's a bug in serde.

**Comment by Kampfkarren** [comment]
This was the case I had it in: https://github.com/Mothblocks/moth-fans-runtimes/blob/7c320863c758b9f30a0127a81c13663290b2f392/src/rounds.rs#L357-L361

**Comment by Kampfkarren** [comment]
Doesn't happen anymore O_o

I'll close this until I'm able to get a better MVCE--the code path was definitely visited but was being marked as dead, and ONLY with Deserialize implemented
