### ISSUE TITLE
thread 'main' has overflowed its stack when using a wrapper with derive

### ISSUE THREAD

**Issue by Skeletonxf** [serde-rs/serde#2299]
Minimum working example here: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b05606f4e212d06a700f8ff38fa26d12

I seem to be getting a runtime `thread 'main' has overflowed its stack` error when trying to delegate to a wrapper type for deserialisation. Seems possibly related to a prior issue with a similar thing happening at compile time: https://github.com/rust-lang/rust/issues/55779 but that is marked as completed.

**Comment by dtolnay** [comment]
I think this is behaving correctly. You've written a Deserialize impl for Foo that requires deserializing Wrapper, and a Deserialize impl for Wrapper that involves deserializing Foo.

**Comment by Skeletonxf** [comment]
Thanks I see now. Is there any way to use a new type and `#[derive(Deserialize)]` like this without creating a recursive issue?
