### ISSUE TITLE
Serialize/deserialize tagged newtype variant containing unit

### ISSUE THREAD

**Issue by tage64** [serde-rs/serde#2302]
To me, it seems that a tagged newtype variant containing `()` should be serializable/deserializable in the same way as unit variants. Specificly I have the following enum:

```rust
#[derive(Serialize, Deserialize, Debug)]
#[serde(tag = "result", rename_all = "snake_case")]
enum Response<T> {
    Success(T),
    Error {
        ...
    },
}
```

I'd expect `Success(())` to pe deserialized from and serialized to `{ "result": "success"}`, but that doesn't seem to be the case. It doesn't work to deserialize it and when I try to serialize it (with serde_json) I get the following error:

```
Error("cannot serialize tagged newtype variant Response::Success containing unit", line: 0, column: 0)
```

Is there any reason why this doesn't work, or should we fix this? I'd would be happy to make a PR.

**Comment by dtolnay** [comment]
It would be fine to make this work I think.

**Comment by tage64** [comment]
The PR is: #2303
