### ISSUE TITLE
Remove/Add terminator character in deserialize/serialize

### ISSUE THREAD

**Issue by chriseyhorn** [serde-rs/serde#2307]
I'm processing messages coming from a SignalR WebSocket, and according to the specs, they end with a terminator character:
"All JSON messages must be terminated by the ASCII character 0x1E (record separator)."

Does a feature exist to look for this and remove it before deserialization or add it during serialization?  If not, how would one do this inside a custom deserialize fn?

**Comment by kangalioo** [comment]
This is not something that should take place in serde deserialization.

Your code should extract the data in-between 0x1E characters and pass _that_ to serde.

**Comment by kangalioo** [comment]
For example with https://doc.rust-lang.org/std/io/trait.BufRead.html#method.read_until

`websocket_data.read_until(0x1E, &mut bytes_vec)`
