### ISSUE TITLE
Exposing `#[serde(flatten)]` for custom `Serialize` implementation

### ISSUE THREAD

**Issue by w1ll-i-code** [serde-rs/serde#2311]
Hi, I'm trying to implement a custom serialization for JsonRpc. That requires to always have the field `"jsonrpc": "2.0"` present, so I opted for a custom implementation. The methods are a big enum with `#[serde(tag = "method", content = "params")]` However I can't flatten them into the serialization because they are not exposed. The code is generated at runtime with 

Example:
``` Rust
use serde::{Serialize, Serializer};
use serde::ser::{SerializeMap};

struct JsonRpc {
        method: Method,
        id: Option<usize>,
}

impl Serialize for JsonRpc {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error> where S: Serializer {
        let mut map = serializer.serialize_map(None)?;
        map.serialize_entry("jsonrpc", "2.0")?;
        map.serialize_entry("test", &self.method)?; // <- call something like Method::serialize_into(&self.method, map, serializer)?;
        if let Some(id) = self.id {
            map.serialize_entry("id", &id)?;
        }
        map.end()
    }
}

#[derive(Serialize)]
#[serde(tag = "method", content = "params")]
enum Method {
    #[serde(rename = "my_method")]
    MyMethod{},
}

fn main() {
    let result = serde_json::to_string(&JsonRpc {method: Method::MyMethod{}, id: None}).unwrap();
    assert_eq!(result, r#"{"jsonrpc": "2.0", "method": "my_method", "params":{}}"#)
}
```

This could be solved by generating the necessary code for a trait that is then implemented for enums, structs and maps. So you can import the trait if you need it.

**Comment by dtolnay** [comment]
I would prefer not to build that into this library. But you can implement this outside of serde by writing a `Serializer` impl that serializes into a `SerializeMap`.

```rust
self.method.serialize(SerializeIntoMap::new(&mut map))?;
```
