### ISSUE TITLE
#[serde(flatten)]: FlatStructAccess's MapAccess impl doesn't return unknown keys

### ISSUE THREAD

**Issue by sunshowers** [serde-rs/serde#2312]
Hi :)

I got a bit nerd-sniped by https://github.com/dtolnay/serde-ignored/issues/17, and I spent a few hours investigating the issue. I think I've figured out the issue as well as a possible way forward.

So the issue is that serde-ignored uses [`deserialize_ignored_any`](https://docs.rs/serde/1/serde/trait.Deserializer.html#tymethod.deserialize_ignored_any) -- anything that's passed into it. This is generally invoked via [`serde::de::IgnoredAny`](https://docs.rs/serde/1/serde/de/struct.IgnoredAny.html).

Taking the example in [@nyurik's OP](https://github.com/dtolnay/serde-ignored/issues/17#issue-1419616847), which I'll reproduce here:

```rust
#[derive(Debug, PartialEq, Deserialize)]
struct Package {
    #[serde(flatten)]
    pub sub: SubPackage,
}

#[derive(Debug, PartialEq, Deserialize)]
struct SubPackage {
    name: String,
    dependencies: Map<String, Dependency>,
}
```

This is what the generated code for `SubPackage` looks like:

* https://gist.github.com/sunshowers/63fda4f8aaaba66dda39e7703e81b405#file-ignored_any_example-rs-L61-L71

And if you don't use `#[serde(flatten)]` (e.g. by directly deserializing a `SubPackage`), `MapAccess::next_value` is called for any unknown fields with `IgnoredAny` and everything works as expected.

However, if you *do* use `flatten` as done in `Package` above, what happens is that all the values get collected into a vector of (name, value) pairs. Here's the generated code for the example above.

* https://gist.github.com/sunshowers/63fda4f8aaaba66dda39e7703e81b405#file-flat_map_deserializer-rs-L15-L36

Then, a `SubPackage` is deserialized from the vector.

* https://gist.github.com/sunshowers/63fda4f8aaaba66dda39e7703e81b405#file-flat_map_deserializer-rs-L38-L48

The implementation uses a `FlatMapDeserializer`, which is a private implementation detail of serde.

* https://github.com/serde-rs/serde/blob/3fd8e52f0c59045482a004073b6e3e033ed2bc67/serde/src/private/de.rs#L2693-L2697

In our example above, `deserialize_struct` is called on the `FlatMapDeserializer` (since `SubPackage` is a struct):

* https://github.com/serde-rs/serde/blob/3fd8e52f0c59045482a004073b6e3e033ed2bc67/serde/src/private/de.rs#L2778-L2788

This calls `next_key_seed` on the `FlatStructAccess`:

* https://github.com/serde-rs/serde/blob/3fd8e52f0c59045482a004073b6e3e033ed2bc67/serde/src/private/de.rs#L2926-L2941

Note that this implementation only returns fields that are known to the deserializer, via `use_item`.

I haven't tried this yet, but what if we also return fields that aren't known? At least in principle it should kick off the `IgnoredAny` machinery.

**Comment by sunshowers** [comment]
OK, so the issue is that if you have multiple `flatten`s then.

It seems like there needs to be a way to potentially say "I'm done flattening everything, call IgnoredAny for whatever hasn't been consumed yet".

**Comment by sunshowers** [comment]
Ahh, so the other issue is that the `deserialize_ignored_any` implementation doesn't get forwarded to the `FlatMapDeserializer` that gets created on the fly.

This is a pretty tricky issue. I'm probably done investigating this for now, but hopefully this is helpful in the future.

**Comment by sunshowers** [comment]
I guess this is a specific instance of the general issue: https://github.com/serde-rs/serde/issues/1183

**Comment by dtolnay** [comment]
That's right; this would be one of the things to revisit after making progress on #1183. Thanks for the writeup.
