### ISSUE TITLE
[`serde_derive`] Is there a way to derive my own "`None`" variant?

### ISSUE THREAD

**Issue by vidhanio** [serde-rs/serde#2313]
I have an `enum` with a few variants, and I would like one of them to behave as `None` would, deserializing to and from it if a `null` is encountered. Is this possible with `serde_derive`?

**Comment by mountainfloating** [comment]
Take a look at the docs of field attributes: https://serde.rs/field-attrs.html They're very well documented! Maybe default is, what you're looking for.
