### ISSUE TITLE
[`serde_derive`] Conditional deserializing defaults based on other field's value

### ISSUE THREAD

**Issue by JohnTheCoolingFan** [serde-rs/serde#2315]
I'm migrating my project from custom derive macro for a custom trait that deserializes directly from lua (using mlua). I have some cases where defaults in a struct change based on a field. Here is example made from trimmed project's code. Here, the defaultt value for `collision_mask` field is different based on `type` field
```rs
#[derive(Debug, Clone, PrototypeFromLua)]
pub struct EntityBase {
    #[default(Self::default_collision_mask(prot_table.get::<_, String>("type").ok()?))]
    collision_mask: CollisionMask, // Default: ("item-layer", "object-layer", "player-layer", "water-tile") and depends on type
}

impl EntityBase {
    fn default_collision_mask(t: String) -> CollisionMask {
        match t.parse::<PrototypeType>().unwrap() {
            // Matching on a `type` value and selecting different defaults based on that
        }
    }
}

// Using serde from now on
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct Arrow {
    #[serde(flatten)]
    entity_base: EntityBase
}

pub struct CollisionMask(pub(crate) u64);

impl CollisionMask {
    pub const GROUND_TILE: CollisionMask = CollisionMask(1);
    pub const WATER_TILE: CollisionMask = CollisionMask(1 << 1);
    pub const RESOURCE_LAYER: CollisionMask = CollisionMask(1 << 2);
//...
}

impl<T: AsRef<str>> FromIterator<T> for CollisionMask {
    fn from_iter<I: IntoIterator<Item = T>>(layers: I) -> Self {
        // implementation
    }
}
```
Examples of acceptable data for deserializing into `Arrow`:
```json
{
    "type": "arrow",
    "collision_mask": ["ground-tile", "water-tile"]
}
```
And without the field:
```json
{
    "type": "arrow"
}
```
I would've gave an example of manually written deserialization code if I was familiar with manual deserialization implementation, but I'm having a really hard time wrapping my head around it. Also, these structs in real project have much more fields, so doing it all manually is doable, but leads to a lot of boilerplate.

**Comment by dtolnay** [comment]
Hi @JohnTheCoolingFan, sorry that no one was able to provide guidance here. If this is still an issue, you could try taking this question to any of the resources shown in https://www.rust-lang.org/community. This library is one of the most widely used Rust libraries and plenty of people will be able to help with it.
