### ISSUE TITLE
Question: Deserializing ["foo",3,"bar",5] into ("foo",3) ("bar,5)

### ISSUE THREAD

**Issue by jbtobar** [serde-rs/serde#2316]
How to deserialize a vector of repeated items into its subsets?
i.e, the json string is;
```
["foo",3,"bar",5 ... ]
```
with an indefinite length of items but all in pairs. 

How to deserialize into a vec of items `Vec<Item>` where:
```rust
struct Item {
 name: String,
 value: usize
}
``` 

?

Thanks!

**Comment by Mingun** [comment]
Implement you own deserialization function with custom `Visitor` which will call `seq.next_element()` twice in cycle and construct `Item`s. Take the inspiration from https://serde.rs/stream-array.html.

**Comment by oli-obk** [comment]
Usually such questions are better asked in the forum or the discord (see https://www.rust-lang.org/community for links), as we don't really have the capacity to do general support for `serde` users
