### ISSUE TITLE
How can I `flatten` a struct field only when I serialise it?

### ISSUE THREAD

**Issue by rnarkk** [serde-rs/serde#2318]
Currently, I have only one option which I flatten a field both at serialisation and deserialisation time:

```rust
#[derive(Serialize, Deserialize)]
pub struct MyStruct {
    #[serde(flatten)]
    to_be_flattened: ToBeFlattened
}
```

I want to flatten it only when I serialise it. How can I do this?
Thanks,

**Comment by BenJeau** [comment]
Have you found a way to accomplish that? Would be great if serde has options for that, e.g. `#[serde(flatten = "serialize")]`

**Comment by BenJeau** [comment]
Figured out how to do this currently, but it requires having multiple structs, e.g.

```rust
#[derive(Serialize, Deserialize)]
#[serde(from = "ToBeFlattened")]
pub struct MyStruct {
    #[serde(flatten)]
    to_be_flattened: ToBeFlattened
}

impl From<ToBeFlattened> for MyStruct {
    fn from(item: ToBeFlattened) -> Self {
        MyStruct { to_be_flattened: item }
    }
}
```

But admittedly it is verbose to do so

**Comment by dtolnay** [comment]
The solution in the previous comment looks good if there is a single field. In general if there are other fields in the data structure besides the flattened one, you could pretty easily handwrite a Serialize impl.
