### ISSUE TITLE
Deserializing borrowed strings with escape sequences in custom deserializer

### ISSUE THREAD

**Issue by Jomy10** [serde-rs/serde#2321]
I'm currently writing a deserializer with serde for a file format.

In strings, I want to replace some escape sequences.

The code for parsing these strings is the following:
```rust
impl<'de> crate::de::Deserializer<'de> {
    pub(crate) fn parse_string(&mut self) -> Result<String> {
        let (start, end) = self.collected.map(Ok).unwrap_or_else(|| {
            let (line, col) = self.get_line_column();
            Err(Error::new(ErrorCode::ExpectedString, line, col))
        })?;
        let src_slice = &self.source[start..end];
        let collected = src_slice
            .replace("`[", "[")
            .replace("`]", "]")
            .replace("``", "`");
        Ok(collected)
    }
}
```

This code returns an owned string, so when I try to implement the deserialize_str method:
```rust
impl<'de, 'a> de::Deserializer<'de> for &'a mut Deserializer<'de> {
    //...
    fn deserialize_str<V>(self, visitor: V) -> Result<V::Value>
    where
        V: de::Visitor<'de> {
        visitor.visit_borrowed_str(self.parse_string()?)
    }
}
```

I get an error because the string has to be borrowed for `'de`. How could I fix this issue? I've found a few issues regarding something similar, but none seemed to fix the issue.

**Comment by Mingun** [comment]
Change `parse_string` definition to return `Cow<'de>`. If you doesn't make any replaces, return a `Borrowed` variant, otherwise return an `Owned` variant.

You also can try to make in-place replacements in your string and always return a borrowed string from `parse_string`

**Comment by oli-obk** [comment]
Does that answer your questions? If not, you can usually get quicker help in the forum or the discord (see https://www.rust-lang.org/community for links)
