### ISSUE TITLE
rename_all = "snake_case" is very dumb

### ISSUE THREAD

**Issue by poscat0x04** [serde-rs/serde#2323]
It cannot correctly recognize camelCase field names. For example for the following struct:

```rust
#[derive(Eq, PartialEq, Debug, Serialize, Deseralize)]
#[serde(rename_all = "snake_case")]
struct Foo{
  fooBarBaz: u32
}
```

when serializing/deserializing, serde will try to find a key with the name "fooBarBaz" instead of (the intended) "foo_bar_baz"

**Comment by dtolnay** [comment]
This is the intended behavior -- the expectation is you're following Rust's widely established naming conventions in the Rust data structure and that is why a rename attribute is getting applied in the first place.

**Comment by poscat0x04** [comment]
Could you document that it requires the field names to be in snake case?
