### ISSUE TITLE
A new trial for proposing serialization interface for big numbers

### ISSUE THREAD

**Issue by cmpute** [serde-rs/serde#2326]
As mentioned in #185, #1463, a proper interface for serializing big numbers (bigger than the built-in types) is still missing in '`serde`. I thereby propose a new interface for big numbers without breaking changes or relying on a specific big number library.

Notice that the support for big numbers (especially for arbitrary precision numbers) usually exists only for text-based data formats, because it's rather hard to come up with a general and portable data structure for big numbers. So, this proposal mainly focuses on serialization with text-based formats.

To serialize big numbers, I propose adding a method (maybe called `serialize_str_raw`) to the `Serializer` trait, which serializes a string but without quotes in the text. Specifically for JSON, `serialize_str("123")` will produce `"123"` in json, but `serialize_str_raw("123")` will directly produce `123` in json. By this way to can serialize big numbers by converting them to strings. The default implementation for this method will forward to `serialize_str`.

To deserialize big numbers, I propose adding a method (maybe called `visit_unknown_as_str`) to the `Visitor` trait, which provide an interface to read a piece of data as a string, when the serializer find that it doesn't fit in the existing data models (such as big numbers). Then for integer literals in json, a JSON deserialize should call primitive visitors such as `visit_i64` when then number is small, or call `visit_unknown_as_str` when the number doesn't fit in a primitive type. The default implementation for this method will forward to `visit_str`.

With these two methods, we could provide a clean interface for big numbers (e.g. bigints, u256, u512, decimals, etc).

The only remaining issue that come to my mind is that there are possible security issues for `serialize_str_raw`, but this might be mitigated by limiting the feasible character set for the input, or provide a switch for the user to enable/disable these two methods, although the latter solution will lead to a break change for the serializer API.

**Comment by dtolnay** [comment]
The serialize_str_raw / visit_unknown_as_str suggestion does not strike me as promising.

My preferred path forward is https://internals.rust-lang.org/t/pre-rfc-non-footgun-non-static-typeid/17079?u=dtolnay, and second is something along the lines of https://doc.rust-lang.org/std/any/struct.Demand.html (or perhaps directly based on Demand).

I think this is adequately tracked already by #1463 so I'll close this one.
