### ISSUE TITLE
Question about customize serialization/deserialization

### ISSUE THREAD

**Issue by tubzby** [serde-rs/serde#2343]
Hi, there.

I already have a client/server protocol communicating using msgpack, I'm trying to re-implementing the server using RUST, but have had some problems recently with how to customize the serialization using serde.

For each message, the sender side will first send an integer id to indicate the message type, and then with the real message, that's the opposite for the other part.

Message define:
```rust
use serde::{Deserialize, Serialize};

#[derive(Deserialize, Serialize, Debug, Clone)]
pub struct LoginReq {
    pub username: String,
    pub password: String,
 }

#[derive(Deserialize, Serialize, Debug)]
pub struct LoginRsp {
    pub ret: u32,
 }

#[derive(Deserialize, Serialize, Debug)]
pub enum Msg {
    LoginReq(LoginReq),
    LoginRsp(LoginRsp),
}
```

By default, type *Msg* will encode into a map, which is not compatible with the current protocol, so I want to implement a customize serializer/deserializer:

```rust
impl Serialize for Msg {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        match *self {
            Msg::LoginReq(ref msg) => {
                // HOW TO DO IT?
                let mut sv = serializer.serialize_struct("LoginReq", 2)?;
                sv.serialize_field("username", &msg.username)?;
                sv.serialize_field("password", &msg.password)?;
                sv.end()
            }
            Msg::LoginRsp(ref msg) => {
                let mut sv = serializer.serialize_struct_variant("Msg", 0, "LoginRsp", 1)?;
                sv.serialize_field("code", &msg.code)?;
                sv.end()
            }
        }
    }
}

```

Take *LoginReq* for example, I want to first send a primitive id equal to 0, and then the real object, how can I do that? *serialize_struct* have to take ownership of *serializer* so I can't use it to do two serialization in one call.

**Comment by dtolnay** [comment]
Hi @tubzby, sorry that no one was able to provide guidance here. If this is still an issue, you could try taking this question to any of the resources shown in https://www.rust-lang.org/community. This library is one of the most widely used Rust libraries and plenty of people will be able to provide guidance about it.
