### ISSUE TITLE
Add higher-level camel case setting

### ISSUE THREAD

**Issue by wcarmon** [serde-rs/serde#2346]
1. camelCase is idiomatic for all json properties
1. snake_case is idiomatic for all rust fields
1. today we have to mark every type with [rename_all](https://serde.rs/container-attrs.html#rename_all)
1. for large projects, this implies tons of mindless copy-pasting for something that is idiomatic (this doesn't scale)

Can we have a "higher-level" setting for this conversion?

eg. 
```rust
let serde_conf = SerdeConf{ rename_all: CaseFormat::CAMEL_CASE };
let foo : Foo = serde_json::from_str_with_conf(json_str, serde_conf);
```
or 

```rust
let serde_conf = SerdeConf { rename_all: CaseFormat::CAMEL_CASE };
serde_json::set_default_conf(serde_conf);
...

let foo : Foo = serde_json::from_str(json_str);
```

**Comment by dtolnay** [comment]
It would be up to individual data formats to provide such a configuration. I don't think this touches anything in serde.

For example TOML already implicitly converts between kebab-case in the serialized data and snake_case in the Rust data structure.
