### ISSUE TITLE
`serde_test`: Support model-based testing.

### ISSUE THREAD

**Issue by jswrenn** [serde-rs/serde#2351]
I'm adding serde support to [deflect](https://jack.wrenn.fyi/blog/deflect/), and I'd like to test that my implementations of `Serialize` over reflected values match the serializations produced by `#[derive(Serialize)]` on those values. The `serde_test` crate could support this use-case, if it provided a `assert_ser_eq` helper to check that two values serialize to the same sequence of `Token`s.

**Comment by dtolnay** [comment]
I think I would prefer not to build this into serde_test. But it would be reasonable for someone to maintain a more fully featured Serde testing library that includes model-based testing.
