### ISSUE TITLE
How to skip deserialize empty json object `{}` ?

### ISSUE THREAD

**Issue by udoless** [serde-rs/serde#2362]
```rust
#[derive(Deserialize, Serialize)]
pub struct Message {
    pub file: Option<File>,
}

#[derive(Deserialize, Serialize)]
pub struct File {
    pub uuid: String,
    pub url: String,
}
```
When json is `{"file": {}}` I want the filed `file` deserializes to `None`, not produce an error: `missing field 'uuid'`

**Comment by nickelc** [comment]
You can achieve this behavior with an untagged enum helper.
```rust
#[derive(Deserialize, Serialize)]
pub struct Message {
    #[serde(default, deserialize_with = "deserialize_empty_object")]
    pub file: Option<File>,
}

#[derive(Deserialize, Serialize)]
pub struct File {
    pub uuid: String,
    pub url: String,
}

pub fn deserialize_empty_object<'de, D, T>(deserializer: D) -> Result<Option<T>, D::Error>
where
    D: Deserializer<'de>,
    T: Deserialize<'de>,
{
    #[derive(Deserialize)]
    #[serde(
        untagged,
        deny_unknown_fields,
        expecting = "object, empty object or null"
    )]
    enum Helper<T> {
        Data(T),
        Empty {},
        Null,
    }
    match Helper::deserialize(deserializer) {
        Ok(Helper::Data(data)) => Ok(Some(data)),
        Ok(_) => Ok(None),
        Err(e) => Err(e),
    }
}
```

**Comment by udoless** [comment]
> 

Thank you, it works!

**Comment by jonasbb** [comment]
The `Empty {}` variant needs to be the first in the `Helper` enum, as otherwise it might still be possible to get a `T` out of the `deserialize_empty_object` function, even on a `{}` input.
You can see the difference here: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=d6dde3898cb203b10bf2842cf6081272

**Comment by nickelc** [comment]
> The `Empty {}` variant needs to be the first in the `Helper` enum, as otherwise it still is possible to get a `T` out of the `deserialize_empty_object` function, even on a `{}` input. You can see the difference here: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=d6dde3898cb203b10bf2842cf6081272

That's because of the `#[serde(default)]` you added on `File`.
