### ISSUE TITLE
Proposal:  #[serde(base = "other_entity.aggregate.count")]

### ISSUE THREAD

**Issue by liusong1111** [serde-rs/serde#2372]
Give a json:
```json
{
  "id": 123,
  "other_entity": {
    "aggregate": {
       "count": 456
    }
  }
}
```

I want to deserialize to :
```rust
#[derive(Deserialize)
struct Entity {
  id: usize,
  #[serde(base = "other_entity.aggregate.count")]
  other_count: usize,
}
```

I know `flatten` can help, but a inline declaration is prefered.

**Comment by dtolnay** [comment]
I think I would prefer not to build something for this into serde_derive. But it would be reasonable for someone else to make a different crate to make deserializing this kind of data easier.

**Comment by Mingun** [comment]
The [serde_query](https://lib.rs/crates/serde-query) crate does what is required

**Comment by liusong1111** [comment]
https://github.com/pandaman64/serde-query/issues/6#issuecomment-1448268869

It seems that serde_query is not actively maintaining, and I hoped serde_query's features are integrated into serde_derive.

I know your opinion now, and appreciate the reply.
