### ISSUE TITLE
`serialize_with` is giving me an error message for a generated lifetime that I don't have access to: `'__a`

### ISSUE THREAD

**Issue by Teajey** [serde-rs/serde#2378]
Minimal reproduction: https://github.com/Teajey/graphql-parser/blob/serde_repro/src/lib.rs

For context, actual error occurs here: https://github.com/Teajey/graphql-parser/blob/fdcd0e50062648e0f59c319f9e6011bc45e1acd8/src/common.rs#L99

It might help to observe the diff to see how I've painstakingly tried to add the feature without modifying the original program at all: https://github.com/Teajey/graphql-parser/pull/1/files

# Explanation

I'm trying to add a serde feature to [graphql-rust/graphql-parser](https://github.com/graphql-rust/graphql-parser) so that I can serialize it's GraphQL document type as JSON.

It has this `Text` trait that abstracts across string types (`&str`, `String`, `Cow<'_, str>`): 
```rs
pub trait Text<'a>: 'a {
    type Value: 'a
        + From<&'a str>
        + AsRef<str>
        + std::borrow::Borrow<str>
        + PartialEq
        + Eq
        + PartialOrd
        + Ord
        + fmt::Debug
        + Clone;
}

impl<'a> Text<'a> for &'a str {
    type Value = Self;
}

impl<'a> Text<'a> for String {
    type Value = String;
}

impl<'a> Text<'a> for std::borrow::Cow<'a, str> {
    type Value = Self;
}
```
I'm sure this is very useful for them, but it makes serializing fields that use this type quite difficult.

I don't want to tack `+ serde::Serialize` onto `type Value`'s trait constraints because it's never actually serialized as a straight string.

A field like `name` defined here
```rs
pub struct Directive<'a, T: Text<'a>> {
    pub name: T::Value,
}
```
Should actually become an object in JSON:
```json
{
  "name": {
    "kind": "Name",
    "value": <actual string value goes here>
  }
}
```

# Actual problem

So the right solution seems to be to use a `serialize_with` function on these fields. But the problem is I often get this compiler error from within the `Serialize` derive macro that suggests that I modify a generated lifetime `'__a`:
```
error: lifetime may not live long enough
   --> src/common.rs:99:38
    |
99  | #[cfg_attr(feature = "serde", derive(serde::Serialize))]
    |                                      ^^^^^^^^^^^^^^^^
    |                                      |
    |                                      lifetime `'__a` defined here
    |                                      argument requires that `'__a` must outlive `'a`
100 | pub struct Directive<'a, T: Text<'a>> {
    |                      -- lifetime `'a` defined here
    |
    = help: consider adding the following bound: `'__a: 'a`
```

It seems like serde is in the wrong here, because it's tripped up by a valid trait type (that I can't modify, however convoluted it is).

I guess I'm asking what would be the correct way to get around this?

**Comment by dtolnay** [comment]
Your `serialize_arguments` function has the wrong signature. You wrote `&'a ...` in the argument type. But the actual argument you're serializing would live shorter than `'a` in general.

For example if I am dealing with `Value<'static, T>` it doesn't mean that the `Vec` it's inside of is `&'static Vec<...>`.
