### ISSUE TITLE
`trivially_copy_pass_by_ref` warnings for custom serde logic on `Copy` types

### ISSUE THREAD

**Issue by andrewbanchich** [serde-rs/serde#2385]
When enabling the `clippy::trivially_copy_pass_by_ref` I get Clippy warnings for custom serde logic for `Copy` types ([example playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=321832017be9303068b706579c5d126d)).

Is there a reason `serde` requires a `&T` instead of a `Borrow<T>` for this?

**Comment by dtolnay** [comment]
I recommend disabling this lint -- so far I have not found it beneficial in my crates.

You could also look into whether clippy could avoid triggering this lint on any function which is invoked via a serde serialize_with attribute.
