### ISSUE TITLE
MSRV bumped substantially with 1.0.157 (due to syn MSRV bump)

### ISSUE THREAD

**Issue by TheBlueMatt** [serde-rs/serde#2408]
Looks like the `Cargo.toml` `rust-version` line is stale again, syn indicates 1.56

**Comment by dtolnay** [comment]
The Cargo.toml rust-version line in 1.0.157 is accurate, it says 1.56:

https://github.com/serde-rs/serde/blob/479a00a215cd291e9c0b0ad0373e26694018bf1c/serde_derive/Cargo.toml#L14
