### ISSUE TITLE
Allow specifying default value for types not implementing `Default`

### ISSUE THREAD

**Issue by Alibirb** [serde-rs/serde#2428]
Currently, `#[serde(default = "my_function")]` only works for types implementing the `Default` trait. I don't think this trait should be required when a function is specified to provide the default value, rather than relying on the default provided by the `Default` trait implementation.

Example:

```rust
use serde::{Deserialize, Serialize};
use url::Url;

fn base_url_default() -> Url {
	Url::parse("http://clustervms.localdomain").unwrap()
}

#[derive(Clone, Default, Debug, Deserialize, Serialize)]
pub struct ClusterVmsConfig {
	#[serde(default = "base_url_default")]
	pub base_url: Url,
}
```

**Comment by dtolnay** [comment]
This is working correctly as far as I can tell. The generated impls are:

```rust
impl Serialize for ClusterVmsConfig

impl<'de> Deserialize<'de> for ClusterVmsConfig
```

which does mention the Default trait.

**Comment by Alibirb** [comment]
Oh, my bad. I totally misread my compiler error. It's the derive for `Default` that's requiring `base_url` to implement `Default`, not the `#[serde(default=...)]`. Guess that's what I get for trying to use minimal screen brightness to conserve battery during a long car ride.
