### ISSUE TITLE
Support for serde in the linux kernel

### ISSUE THREAD

**Issue by ariel-miculas** [serde-rs/serde#2440]
I'm working on a filesystem driver in rust and I would like to reuse as much code as I can from the implementation in userspace (using the FUSE linux kernel framework). Although at the moment it's not clear in the "Rust for linux" community whether they will support third-party crates in the kernel (or which ones they would like to support), I think serde would be a good candidate for the inclusion in the kernel since it's a generic framework and a lot of the serializing libraries are built on top of it. So I was wondering if there's any interest for this or if it would be useful to anyone else if serde would be included in the kernel.

**Comment by oli-obk** [comment]
Can you elaborate on how you think inclusion in the linux kernel would affect us? Serde is already used in embedded projects and has the right licenses for you to use it.

**Comment by ariel-miculas** [comment]
Well, to list a few of the issues I've had when trying to make it work:
* error: expected identifier, found reserved keyword `try`
* error: hidden lifetime parameters in types are deprecated
* error[E0782]: trait objects must include the `dyn` keyword
* error: outlives requirements can be inferred
So at least some changes to the code would be required in order to make it work.
Can you give me some examples of embedded projects it's used in so I can see how it's integrated?

**Comment by oli-obk** [comment]
You need to compile serde with `--edition 2021` if you are compiling directly with rustc. Similarly, other things stated in `Cargo.toml` need to be addressed. I recommend you compile with `cargo build --verbose --no-default-features` and compare the command line flags that are used for the rustc calls with the ones you are using.

**Comment by oli-obk** [comment]
Closing as this issue is not serde specific
