### ISSUE TITLE
Add feature to exclude `Option::None` fields from serialization by default

### ISSUE THREAD

**Issue by Kuly14** [serde-rs/serde#2451]
By default, if you have a `Option<T>` field in a struct and it's `None`, Serde will serialize it as null. If you'd like to avoid this and omit the field entirely from the serialized output when it's `None`, you can use the `#[serde(skip_serializing_if = "Option::is_none")]` attribute on each field:

```rust
#[derive(Serialize)]
struct MyStruct {
    #[serde(skip_serializing_if = "Option::is_none")]
    field1: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    field2: Option<i32>,
    // and so on...
}
```

However, applying this attribute to each optional field can become tedious and clutter your code, especially if your struct has many optional fields.

As of my knowledge, Serde does not offer a container attribute to apply this behavior to all optional fields in a struct. Would it be possible to add this?

**Comment by martin-g** [comment]
See https://docs.rs/serde_with/latest/serde_with/#skip_serializing_none

**Comment by Kuly14** [comment]
Oh nice, sorry then lol. I didn't find it on the serde.rs website.

Thanks for the help!
