### ISSUE TITLE
`#[serde(default)]` on fields adds unnecessary bounds to generic parameters

### ISSUE THREAD

**Issue by Mingun** [serde-rs/serde#2452]
The following snippet silently assumes, that `Deserialize` will be implemented only if `T: Deserialize`, although this [is not required](https://doc.rust-lang.org/std/vec/struct.Vec.html#impl-Default-for-Vec%3CT,+Global%3E)
```rust
#[derive(Deserialize)]
struct List<T> {
    // default allows empty list
    #[serde(default)]
    element: Vec<T>,
}
```
[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=57cfb725f1ac10220c6139863a8d566e)

**Comment by dtolnay** [comment]
I think this is behaving as intended. This is consistent with the heuristic for inferring Serialize and Deserialize bounds in serde's derived, and how all other bounds like Clone or Debug are inferred by standard library derives.

One can write a `bound` attribute on the struct to control the generated trait bound.

```rust
#[derive(Deserialize)]
#[serde(bound(deserialize = "T: Deserialize<'de>"))]
struct List<T> {
```

**Comment by Mingun** [comment]
> and how all other bounds like Clone or Debug are inferred by standard library derives.

Not sure, that this is direct analogues. When you derive `Clone` or `Debug`, the same trait bounds are added (i. e. `Clone` or `Debug`). In this case we derive `Deserialize`, but `Default` bound is added. I agree, that heuristic would be useful in that case:
```rust
#[derive(Deserialize)]
struct List<T> {
  #[serde(default)]
  element: T,
}
```
because in that case the `T: Default` is obviously needed. Why not generate `Vec<T>: Default` for the mentioned case? That is what is actually needed. I think, it in any case would be better to explicitly define required bounds on the type, if some other type instead of `Vec` would be used.
