### ISSUE TITLE
Be able to access the value of the tag in a tagged enum variant

### ISSUE THREAD

**Issue by acheronfail** [serde-rs/serde#2455]
I have the use-case where after parsing some tagged JSON objects (e.g., `{"type":"foo", ... }`) and I need to print the value of the `type` property.

Right now, I'm using this as a workaround: 

```rust
use serde_derive::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "snake_case", tag = "type")]
pub enum TaggedEnum {
    One { num: usize },
    Two { string: String },
    Three { boolean: bool },
}

impl TaggedEnum {
    pub fn tag(&self) -> &'static str {
        match self {
            TaggedEnum::One { .. } => "one",
            TaggedEnum::Two { .. } => "two",
            TaggedEnum::Three { .. } => "three",
        }
    }
}

fn main() {
    let x: TaggedEnum = serde_json::from_str(r#"{"type":"one","num":2}"#).unwrap();
    dbg!(x.tag());
}
```

But it's very brittle - if I change the `#[serde(rename_all ...)]` attribute, then my `tag()` method will break (the casing will be different). I also must update it each time I add/remove/change an enum variant.

* I've looked at the output of `serde` using `cargo expand`, and I don't think anything is emitted that I could use for this. 
* I can't add a `type: String` field to each variant of the enum, since `serde` errors with: ``variant field name `type` conflicts with internal tag``

The only way I can think of to make my `tag()` method more reliable is something like this:

```rust
impl TaggedEnum {
	pub fn tag2(&self) -> String {
        match serde_json::to_value(&self).unwrap() {
            Value::Object(map) => map.get("type").unwrap().as_str().unwrap().to_owned(),
            _ => unreachable!(),
        }
    }
}
```

But that's far from ideal, since to access this I must convert it to a `Value` first, and then extract the value manually...

So, unless I'm missing an obvious way how to do this, **I propose the following:**

* If a field in the enum exists with the same name as the `tag`, then deserialize the tag into that field; or
* `impl` an optionally derived method `.tag()` which returns a `&'static str` of the derived tag value

**Comment by Mingun** [comment]
As a workaround you can implement a special serializer that will capture tag field

**Comment by dtolnay** [comment]
I would prefer not to build this into serde_derive.

If the first solution shown above is too brittle and the second solution is too not ideal, I'd recommend using a separate derive macro that can generate the `.tag()` method, using the serde_derive_internals crate to handle `rename_all` in a way that is consistent with serde_derive.

**Comment by dtheodor** [comment]
I also ran into this. Would a way forward here is to be able to pass a custom rename function? So you define the tag name logic in one place in a regular function, use it for whatever additional purposes and also pass it to the serde rename attribute

**Comment by dtheodor** [comment]
Something like this comment https://github.com/serde-rs/serde/issues/1964#issuecomment-974828312
