### ISSUE TITLE
visit_bytes and visit_str docs are partially wrong

### ISSUE THREAD

**Issue by mattfbacon** [serde-rs/serde#2459]
https://github.com/serde-rs/serde/blob/938ab5ddec1bd7822bd0ae595bdd475e03574cdb/serde/src/de/mod.rs#L1542-L1549

This seems to apply to `visit_byte_buf`, not `visit_bytes`. The same issue is present with `visit_str` whose docs seem to apply to `visit_string`.

**Comment by dtolnay** [comment]
It looks correct to me. Could you elaborate on what aspect you feel is incorrect?

**Comment by mattfbacon** [comment]
Nevermind I misread, sorry
