### ISSUE TITLE
Adjacently tagged enums with content field name same as tag

### ISSUE THREAD

**Issue by semirix** [serde-rs/serde#2461]
This is a duplicate of #1343. I believe this is worth re-opening because while @dtolnay's workaround is fine, I am in a situation where I am dealing with generated structs coming from `prost` and I have limited control over the structs generated.

What I am able to do is have attributes prepended before an enum declaration, so I could add something like `#[serde(tag = "type", content = tag)]`. It is important I am able to do this as I need to maintain a standard JSON serialisation format between Rust and JS as protobuf is not enough by itself, and it seems to be quite common that JS libraries, in particular libraries that generate types for protobuf files seem to prefer ADT types for `oneof` fields that look like:
```js
{
  type: "foo"
  foo: { ... }
}
```
I do realise that implementing this is not a simple matter and will likely need to consider fields with `#[serde(rename)]` and similar attributes. That being said, I do believe a library like `serde` benefits from being able to handle more formats.

**Comment by dtolnay** [comment]
My feeling is this representation is not ubiquitous enough to be worth building into serde_derive. But someone should feel free to implement support for this in a separate crate!
