### ISSUE TITLE
Round trip serialization and deserialization fails when storing an `Option<UnitStruct>`

### ISSUE THREAD

**Issue by alice-i-cecile** [serde-rs/serde#2462]
When writing to JSON, `Some(UnitStruct)` is serialized the same as `None`. This only seems to occur for structs with no data / fields.

I haven't investigated if this is a problem in other file formats.

This then causes the deserialization to not match the original value.

**Comment by alice-i-cecile** [comment]
The field gets serialized as `field: null`. I suspect this is a JSON-specific limitation around handling enum values.

**Comment by dtolnay** [comment]
Neither serde nor serde_json makes round trip guarantees in general.

What JSON would you expect to get for each of the two values?

**Comment by alice-i-cecile** [comment]
Given that unit structs are represented as `null` per the [serde-json spec](https://serde.rs/json.html), I don't think there's a good solution. I'm very fine to leave this as "Won't Fix": this was merely a surprise that I felt was worth poking at and adding to the Google search results :)
