### ISSUE TITLE
Serializable format value cannot deserialize to itself due to lack of `visit_struct` Visitor API, treating structs as map.

### ISSUE THREAD

**Issue by PsichiX** [serde-rs/serde#2469]
Hi, i have created an intermediate fat serde representation format value that serves me as type erased version of serializable data for various use cases such as versioning and patching.
https://github.com/PsichiX/serde-intermediate

Now one of the goal of it is to be embeddable in other data so for example:
`Foo { bar: Intermediate }`
can store fat serde representation no matter what master format we serialize to / deserialize from, so for example i can make JSON:
`{ "bar": { "value": 42 } }`
and it should yield `Foo` with `bar` represented as `Intermediate` tree.

That being said, for that to happen i do require symmetry of serializing to / deserializing from `Intermediate` to itself. The problem with it is that this `Intermediate` format knows the difference between [structure](https://docs.rs/serde-intermediate/latest/serde_intermediate/value/intermediate/enum.Intermediate.html#variant.Struct) and [map](https://docs.rs/serde-intermediate/latest/serde_intermediate/value/intermediate/enum.Intermediate.html#variant.Map) information, and it uses `IntermediateVisitor` which has [`visit_map` that always yields `Map` variant](https://docs.rs/serde-intermediate/latest/src/serde_intermediate/de/intermediate.rs.html#629) no matter what `MapAccess` it gets. What i suspect is that `Visitor::visit_struct` would greatly help here, but it's not found in `serde` yet, and instead both struct and map reads do use same `visit_map` with just different `MapAccess` that doesn't allow to tell if it's reading struct or map so i could return proper `Struct` or `Map` variant in `visit_map`.

How can i make `Intermediate` properly deserializing to itself, so i achieve symmetry of input and output `Intermediate` values when run deserialization from `Intermediate` to itself?

---

- Test that expects same value but fails:
  https://github.com/PsichiX/serde-intermediate/blob/master/core/src/tests.rs#L196
  `serialized` is result of serialization of `Foo` into `Intermediate`, `deserialized` is results of faulty deserialization `Intermediate` into itself.

- Deserializer for `Intermediate` values:
  https://github.com/PsichiX/serde-intermediate/blob/master/core/src/de/intermediate.rs#L102-L106
  In case of deserialization from `Intermediate` to itself, we use `IntermediateVisitor`.

- `IntermediateVisitor` that always return `Map` variant no matter if in this case we use struct or map deserializer:
  https://github.com/PsichiX/serde-intermediate/blob/master/core/src/de/intermediate.rs#L621-L630
  I have no idea how can i make it return `Struct` variant if it detects reading struct.

**Comment by dtolnay** [comment]
I would consider this out of scope for Serde -- I am not planning to grow the API with a `visit_struct` mechanism.
