### ISSUE TITLE
When is `Serializer::serialize_bytes` used ?

### ISSUE THREAD

**Issue by Baptistemontan** [serde-rs/serde#2474]
I'm currently implementing a custom binary format and being able to serialize bytes array in a form that enables to borrow it in the deserialization would be a great optimisation, but when I test my implementation with a simple
```rust
#[derive(Debug, Serialize, Deserialize, PartialEq)]
struct TestBorrow<'a, 'b> {
    name: &'a str,
    bytes: &'b [u8],
}

#[test]
fn test_serialize_deserialize_borrowed() {
    let value = TestBorrow {
        name: "john",
        bytes: b"doe",
    };

    let mut v: Vec<u8> = Vec::new();
    ser::to_writer(&value, &mut v).unwrap();

    let res: TestBorrow = de::from_bytes(&v).unwrap();

    assert_eq!(value, res);
}
```

I found out that the `bytes` field is serialized as a sequence by the auto derive, so I tried to implement it myself but when you implement manually the `Serialize` trait you write something like

```rust

impl<'a, 'b> Serialize for TestBorrow<'a, 'b> {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        let mut struct_serializer = serializer.serialize_struct("TestBorrow", 2)?;
        struct_serializer.serialize_field("name", self.name)?;
        struct_serializer.serialize_field("bytes", self.bytes)?;
        struct_serializer.end()
    }
}
```

So how do I tell the serializer to serialize the field as a byte slice and not as a sequence ?

**Comment by Baptistemontan** [comment]
I don't know why I did'nt thought of that instantky, the solution is obvious:

```rust
#[derive(Debug, Serialize, Deserialize, PartialEq)]
struct TestBorrow<'a, 'b> {
    name: &'a str,
    #[serde(serialize_with = "serialize_as_bytes")]
    bytes: &'b [u8],
}

fn serialize_as_bytes<S>(bytes: &[u8], serializer: S) -> Result<S::Ok, S::Error>
where
    S: serde::ser::Serializer,
{
    serializer.serialize_bytes(bytes)
}
```

But why is'nt this the default behavior for `&[u8]` ?

My guess is that there is a `impl<T: Serialize> Serialize for &[T]`, but `&str` and `&[u8]` are two special types that don't require `#[serde(borrow)]`, so special case are already handle. I guess this would be a breaking change for some format, but most serializer already forward `Serializer::serialize_bytes` to `Serializer::serialize_seq` anyway.

**Comment by jonasbb** [comment]
> My guess is that there is a `impl<T: Serialize> Serialize for &[T]`,

This is basically the answer to your question. You have these generic implementations for [T] and Vec<T>. Since they are generic they have to use serialize_seq. If you want a different implementation for [u8] that requires specialization in rust, which is not available yet and it might not be for many years. Even then the backwards compatability concerns will prevent serde from using it.

The serde solution is to annotate the fields with serde(with="") to opt in to bytes handling. You have crates which make it easier: https://docs.rs/serde_bytes/0.11.9/serde_bytes/ or https://docs.rs/serde_with/3.0.0/serde_with/struct.Bytes.html

**Comment by Baptistemontan** [comment]
This look fairly easy to implement without breaking much, and would probably allow some neat optimizations for some other types.

From just implementing your suggestion only 1 test fail, `test_lifetime_propagation_for_flatten` in `test_suite\tests\test_annotations.rs`, which assumed `b"x"` would be serialized as a sequences and not bytes, but this show the difference in serializing/deserializing when changing

```rust
let mut borrowed_map = HashMap::new();
borrowed_map.insert(&b"x"[..], 42u32);
assert_ser_tokens(
    &C {
        t: borrowed_map.clone(),
    },
    &[
        Token::Map { len: None },
        Token::Seq { len: Some(1) },
        Token::U8(120),
        Token::SeqEnd,
        Token::U32(42),
        Token::MapEnd,
    ],
);

assert_de_tokens(
    &C { t: borrowed_map },
    &[
        Token::Map { len: None },
        Token::BorrowedBytes(b"x"),
        Token::U32(42),
        Token::MapEnd,
    ],
);
```

to simply 

```rust
let mut borrowed_map = HashMap::new();
borrowed_map.insert(&b"x"[..], 42u32);

assert_tokens(
    &C { t: borrowed_map },
    &[
        Token::Map { len: None },
        Token::BorrowedBytes(b"x"),
        Token::U32(42),
        Token::MapEnd,
    ],
);
```

make the test pass

**Comment by Baptistemontan** [comment]
Looking more into it `Vec<u8>` just need to move from `seq_impl!` to `deref_impl!`, but I don't know what would be the right call for `[u8; N]`, as `[T; N]` is serialized as a tuple.

**Comment by dtolnay** [comment]
It's not something I would be interested in changing at this point.
