### ISSUE TITLE
Implementing traits depending on serde's Serialize/Deserialize

### ISSUE THREAD

**Issue by daniel7grant** [serde-rs/serde#2489]
Sorry if this is not the correct place for asking for help, but my issue is so specific, I don't think I could get help from the Discord servers.

I am the maintainer of the [redis-macros](https://crates.io/crates/redis-macros) crate which is basically a derive macro for the [redis](https://crates.io/crates/redis) crate's traits, and adds support for automatically serializing complex structs and enums into Redis savable data (JSON strings usually). For most cases, it is pretty straightforward: implement the `ToRedisArgs` and `Serialize` to serialize the data before saving, and `FromRedisValue` and `Deserialize` to read it back. Basically these are two traits that depend on the `serde` traits. 

```rust
#[derive(Serialize, Deserialize, FromRedisValue, ToRedisArgs)]
struct User { ... }
```

One issue, that I run into is when generic types are involved (see https://github.com/daniel7grant/redis-macros/issues/2). Serde has some heuristics to add trait constraint implicitly to generic structs (see https://github.com/serde-rs/serde/issues/964#issuecomment-310419911). For example `#[derive(Serialize)]` will produce similar code on a generic struct:

```rust
#[derive(Serialize)]
struct Container<T> { t: T }

// Generated code - adds the where automatically!
impl<T> _serde::Serialize for Container<T>
where
    T: _serde::Serialize,
{ ... }
```

My problem is that my traits do not have these bounds and for this reason the generated code fails.

```rust
#[derive(Serialize, ToRedisArgs)]
struct Container<T> { t: T }

// Generated code - no constraint added!
impl<T> ::redis::ToRedisArgs for Container<T> {
    // fn definition ...
    let buf = ::serde_json::to_string(&self).unwrap();
    //        ----------------------- ^^^^^ the trait `Serialize` is not implemented for `T`
    //        |
    //        required by a bound introduced by this call
}
```

Basically the `Serialize` implementation states that *if and only if* `T` implements `Serialize`, does `Container<T>` implement `Serialize`, so any dependent traits should also contain the same trait bounds. A logical step would be for my crate to copy `serde`'s behaviour. However after some digging in the [Serialize implementation](https://github.com/serde-rs/serde/blob/master/serde_derive/src/ser.rs#L133), it seems like there is a non-trivial amount of code to implement the where clause (handling `skip_serialize`, enum variants, lifetimes).

Is there a way I can reuse this logic? I'm wary of copying the code into my crate. To see some initial progress, see the [feature/generic-structs](https://github.com/daniel7grant/redis-macros/tree/feature/generic-structs) branch and the [derive_generic example](https://github.com/daniel7grant/redis-macros/blob/feature/generic-structs/examples/derive_generic.rs).

**Comment by dtolnay** [comment]
Putting `where Container<T>: Serialize` would reuse serde's generated bound exactly.

**Comment by daniel7grant** [comment]
Oh cool, I didn't knew Rust could do that. Thanks for your help.
