### ISSUE TITLE
How to skip some bytes when deserlializer?

### ISSUE THREAD

**Issue by cathaysia** [serde-rs/serde#2490]
I now have a custom deserializer and a custom Visitor struct. During the deserialization process, some fields in the data stream are not supported, but the length of these fields can be calculated so  skip these bytes. Does serde provide some mechanism to skip the these bytes?

IgnoredAny doesn't seem to be used to skip bytes. And if IgnoredAny is used, it will still enter the deserialization process. But I just want those bytes to be simply skipped.

**Comment by Mingun** [comment]
Hmm... just skip them in your read stream procedure (I believe that by "have a custom deserializer" you mean "implements its own serialization format" and does not wrap another deserializer)

**Comment by cathaysia** [comment]
> Hmm... just skip them in your read stream procedure (I believe that by "have a custom deserializer" you mean "implements its own serialization format" and does not wrap another deserializer)

The deserializer contains two deserializers. The first deserializer is used to read fields and split the binary into dictionaries. The second serializer is used to convert the binary into a structure

**Comment by cathaysia** [comment]
But whether the field is unknown can only be known in the structure. Therefore, other ways may be needed to skip bytes

**Comment by Mingun** [comment]
> some fields in the data stream are not supported

Not supported by your deserializer? How your deserializer knows that them are not supported? It read some sign from the data stream? Then skip bytes as soon as you read this sign.

The deserialized type will ask deserializer about data that it contain, so deserializer can just not answer "I have some data" if it cannot understand them but skip them instead.

**Comment by cathaysia** [comment]
The form of these data is like this: [(k,v), (k,v)]. where the length of k is fixed and the length of v is explained by k. v is deserialized by one deserializer de1 and (k,v) is deserialized by another deserializer de2.
Among them, the structure maps the fields of the structure to strings through serde(rename), that is, k.
I implemented the visit_map method in the deserialize method for the struct. Check if this field is supported by checking the key. If not supported, require the serializer to be able to skip v

**Comment by cathaysia** [comment]
I probably figured out what was going on. I will close this issue
