### ISSUE TITLE
Accumulation of error messages from validation of multiple fields

### ISSUE THREAD

**Issue by samgj18** [serde-rs/serde#2507]
Hello, is there any chance to validate multiple fields and have all error messages accumulated and returned in a single Vec, without having to manually write de Deserializer each time (i.e. deriving it):

```rust
#[derive(serde::DeserializeNel)]
pub struct LoginFormData {
    email: String,
    password: String,
}
```

```json
{}
```

For something like this maybe we could return something around the lines of:

`Json deserialize error: missing field *email* at line 3 column 1 and *password* at line 4 column 1. `

Thanks a lot in advance! I'd be happy to contribute on this one if open to this approach!

**Comment by oli-obk** [comment]
[Similarly to how we do not collect all errors during untagged enum deserialization](https://github.com/serde-rs/serde/pull/2376#issuecomment-1519172405), I think this is not something that will benefit users of your crate, but only your own development of it. While this is of course beneficial, it also requires extra complexity in serde and I'm not sure there's much benefit to it compared to the current behaviour where you just need to recompile and rerun with the new field added.

**Comment by samgj18** [comment]
I see how your concern is valid. However, I believe this could benefit the web developers beyond than myself immensely as accumulating parsing errors is a very common (and in some cases desirable) practice. 

In any case, if opened the space for this in the future I'll be glad to contribute.
