### ISSUE TITLE
Refuses to serialize Rc<RefCell<Item>> field - despite #[serde(skip_serializing)]

### ISSUE THREAD

**Issue by cambiata** [serde-rs/serde#2510]
When using the `"rc"` feature flag, serializing structs with `Vec<Rc<Child>>` fields works fine.

However, if I add a field to the same struct that shouldn't be serialized (using `#[serde(skip_serializing)]` for that) containing a `RefCell` (for example a `Rc<RefCell<Child>>`), it doesn't compile.

```rust
#[derive(Debug, PartialEq, Eq, Hash, serde::Deserialize, serde::Serialize)]
struct Child {
    data: i32,
}

#[derive(Debug, PartialEq, Eq, Hash, serde::Deserialize, serde::Serialize)]
struct Parent {
    // persistent field - should be serialized
    children: Vec<Rc<Child>>,

    // computed field - shouldn't be serialized
    // As soon as I add the child field below
    #[serde(skip_serializing)]
    child: Rc<RefCell<Child>>, // <- causes compile error `RefCell<Child>: Hash` not satisified
}

Is there a way to allow non-serialized fields containing RefCells in an otherwise serialized struct?

```

**Comment by jonasbb** [comment]
That is a problem with the `Hash` derive macro, that ships with the Rust standard library. It has nothing to do with serde.
These derive macros offer no customization. You will need to implement `Hash` by hand or look for a crate.

**Comment by Mingun** [comment]
The problem is because [`RefCell`](https://doc.rust-lang.org/std/cell/struct.RefCell.html) does not implement `Hash`. A possible workaround is to use newtype wrapper for `Rc<RefCell<Child>>` and implement `Hash` for it manually. But I recommend to google first, why `RefCell` doesn't implement `Hash` for the first place -- maybe there is some non-obvious obstacles

**Comment by cambiata** [comment]
Thanks guys! I get that `RefCell` doesn't implement `Hash`, but - as mentioned - I don't need to serialize any field using `RefCell`s. 
When adding `#[serde(skip_serializing)]` to a field, I was expecting that field to be completely ignored - regardless using `RefCell` or not.

It would be very nice if the serde docs could provide some info about this limitation, and - at best - some examples on how to get around it.

**Comment by dtolnay** [comment]
I am locking the issue because, as already pointed out above, this has literally nothing to do with serde.

You can remove all serde attributes and derives from this code and still get the same error.
