### ISSUE TITLE
serde_derive with pre-compiled binary does not work when building via Bazel with rules_rust

### ISSUE THREAD

**Issue by kiron1** [serde-rs/serde#2530]
When building some crate which using or depending serde_derive 1.0.172 via Bazel using rules_rust on x86_64 GNU Linux the build will fail with:

```
error: proc-macro derive panicked
 --> main.rs:3:10
  |
3 | #[derive(Serialize, Deserialize, Debug)]
  |          ^^^^^^^^^
  |
  = help: message: failed to spawn process: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

It does not find the precompiled binary used in the derive macro.

Would it be possible to add an opt-out option to *not* use the precompiled binary for `serde_derive` which can be set until a proper solution is found?

Issue in the rules_rust repository: https://github.com/bazelbuild/rules_rust/issues/2071
Somehow related issue: https://github.com/serde-rs/serde/issues/2526

**Comment by dtolnay** [comment]
You would need to sort this out with other Bazel users.

I am using serde_derive successfully from Buck which is a conceptually similar system, so it is definitely usable.

**Comment by superboum** [comment]
I would also like to mention that it does not work with [cargo2nix](https://github.com/cargo2nix/cargo2nix) either.
I don't understand how I can configure serde to compile from source and have not found any documentation about it yet :-(

**Comment by Fuuzetsu** [comment]
I'm also a nix user, investigating the problem. It's not that hard to make the binary from crates.io visible but it just segfaults straight away on my CPU with "invalid instruction". So whatever fixes, including whatever suggested in #2526 are done, this is just not going to work.

Presumably there should simply be a feature to opt-into from-source code path instead of picking based on platform and crossing fingers.

**Comment by Fuuzetsu** [comment]
>Presumably there should simply be a feature to opt-into from-source code path instead of picking based on platform and crossing fingers.

In meantime we'll just be maintaining a fork with a patch to just use the source version I guess...

https://github.com/tsurucapital/serde/commit/45a3539b1ed5104a857f4512381eaf8cb7b736eb

**Comment by SylvKT** [comment]
> > Presumably there should simply be a feature to opt-into from-source code path instead of picking based on platform and crossing fingers.
> 
> In meantime we'll just be maintaining a fork with a patch to just use the source version I guess...
> 
> [tsurucapital@45a3539](https://github.com/tsurucapital/serde/commit/45a3539b1ed5104a857f4512381eaf8cb7b736eb)

Thank you for this. I've been looking for a fork of some kind to use.
