### ISSUE TITLE
Field/variant aliases are not checked for uniqueness

### ISSUE THREAD

**Issue by Mingun** [serde-rs/serde#2551]
[The code](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=0551945af3b0581fefd8c0c9684e4182)
```rust
use serde::Deserialize; // 1.0.171;
use serde_json; // 1.0.102;

#[derive(Deserialize, Debug)]
#[serde(deny_unknown_fields)]
pub struct Thing {
    pub w: u8,

    #[serde(alias = "z", alias = "x")]
    pub y: u8,

    #[serde(alias = "same", alias = "other", alias = "same", alias = "x", alias = "y")]
    pub same: u8,
}

fn main() {
    let j = r#" {"j":null} "#;
    println!("{}", serde_json::from_str::<Thing>(j).unwrap_err());
}
```
gives the following output:
```
unknown field `j`, expected one of `w`, `x`, `z`, `y`, `other`, `same`, `x`, `y` at line 1 column 5
```

**Comment by jmi2k** [comment]
Just want to point out this can lead to surprising behavior. While looking for a mechanism similar to the one proposed in #2605, I found myself declaring the same alias to all fields. As serde didn't stop me after the second duplicate alias, I supposed it would work as I intended, only to discover later at runtime it only applied to the first field.
