### ISSUE TITLE
Consider adding a lossy deserialization method

### ISSUE THREAD

**Issue by erickt** [serde-rs/serde#256]
The idea is from [matthieum on reddit](https://www.reddit.com/r/rust/comments/47rs6d/the_highs_and_lows_of_rust/d0fubcy). It might be possible to add a `Deserialize::deserialize_lossy` that opts in at a call-site to ignore missing fields. Maybe suppress other errors too.

**Comment by e-oz** [comment]
Nobody answered on reddit, so I'll ask this question here: will serde on decode set "none" to the field of structure, if type if this field is Option<T> and field does not exist in input string?

**Comment by dtolnay** [comment]
@e-oz No, Serde the framework does not deserialize missing Option fields to None. That sort of thing is up to the individual Serde formats to handle. The Serde format for YAML ***does*** have this behavior - see the relevant code [here](https://github.com/dtolnay/serde-yaml/blob/0a1c2a656796d338409eb5c93899aa7b8e1b7387/yaml/src/de.rs#L132). Same thing in the JSON deserializer [here](https://github.com/serde-rs/json/blob/7bc9b0a98ec65b90f8c4600d5966d1ca0679b089/json/src/de.rs#L759).

**Comment by e-oz** [comment]
@dtolnay so deserialization will just fail if partial structure will be send to input? I can't believe it, it's too brittle to survive. I'm not trying to say you are lying, of course, I just really can't believe it. But if it's so, then you are saving tone of my time (I just will not even try to switch to serde).

**Comment by oli-obk** [comment]
Without this behaviour you would not be able to specify a format that's supposed to error on missing fields. Note that it's trivial to enable this behaviour in your own format.

**Comment by dtolnay** [comment]
In other words, the decision of whether to fail on a "partial structure" depends on the format that is being deserialized. Concretely, for those formats that serialize structs as maps (JSON, YAML, some others), the behavior is controlled by this [missing_field](https://serde-rs.github.io/serde/serde/de/trait.MapVisitor.html#method.missing_field) method, which may return either an error or a default value for the missing field. Both JSON and YAML Serde formats return a default of None when the type of the missing field is Option.

There are other formats in which this is not possible. In particular, some formats are not self-describing so we can't even tell whether a field is missing. Serde the framework attempts to be general across all of these different formats.

**Comment by e-oz** [comment]
@oli-obk easy, just make them non-Optional.

@dtolnay

> Both JSON and YAML Serde formats return a default of None when the type of the missing field is Option.

In your first response I thought you are saying exactly opposite thing. Sorry for misunderstanding, glad to hear it works this way.

**Comment by dtolnay** [comment]
<details><summary>I deleted an irrelevant discussion.</summary><p>

@e-oz

> Nobody answered on reddit, so I'll ask this question here: will serde on decode set "none" to the field of structure, if type if this field is Option and field does not exist in input string?

@dtolnay

> @e-oz No, Serde the framework does not deserialize missing Option fields to None. That sort of thing is up to the individual Serde formats to handle. The Serde format for YAML does deserialize missing Option fields to None - see the relevant code [here](https://github.com/dtolnay/serde-yaml/blob/0a1c2a656796d338409eb5c93899aa7b8e1b7387/yaml/src/de.rs#L132). Same thing in the JSON deserializer [here](https://github.com/serde-rs/json/blob/7bc9b0a98ec65b90f8c4600d5966d1ca0679b089/json/src/de.rs#L759).

@e-oz

> @dtolnay so deserialization will just fail if partial structure will be send to input? I can't believe it, it's too brittle to survive. I'm not trying to say you are lying, of course, I just really can't believe it. But if it's so, then you are saving tone of my time (I just will not even try to switch to serde).

@oli-obk

> Without this behaviour you would not be able to specify a format that's supposed to error on missing fields. Note that it's trivial to enable this behaviour in your own format.

@dtolnay

> In other words, the decision of whether to fail on a "partial structure" depends on the format that is being deserialized. Concretely, for those formats that serialize structs as maps (JSON, YAML, some others) the behavior is controlled by this [missing_field](https://serde-rs.github.io/serde/serde/de/trait.MapVisitor.html#method.missing_field) method which may return either an error or a default value for the missing field. Both JSON and YAML Serde formats return a default of None when the type of the missing field is Option.
>
> There are other formats in which this is not possible. In particular, some formats are not self-describing so we can't even tell whether a field is missing. Serde the framework attempts to be general across all of these different formats.

@e-oz

> @oli-obk easy, just make them non-Optional.
>
> @dtolnay
>
> > Both JSON and YAML Serde formats return a default of None when the type of the missing field is Option.
>
> In your first response I thought you are saying exactly opposite thing. Sorry for misunderstanding, glad to hear it works this way.

</details>

**Comment by dtolnay** [comment]
Does anyone have real examples where they need to deserialize the same struct with and without ignoring unknown field / missing field errors?

Also are there any libraries in other languages that handle this that we could use for inspiration?
