### ISSUE TITLE
Clarify serde_derive platform support

### ISSUE THREAD

**Issue by DarkKirb** [serde-rs/serde#2574]
_Originally posted by @dtolnay in https://github.com/serde-rs/serde/issues/2538#issuecomment-1682519944_

> […] The precompiled implementation is the only supported way to use the macros that are published in serde_derive. […]

This does seem to imply that platforms where the precompiled implementation is not available are not officially supported. However the rust compiler, which uses serde_derive, is supported on many platforms, most of which are listed in the [rust documentation](https://doc.rust-lang.org/nightly/rustc/platform-support.html).

**Comment by chloekek** [comment]
Compiling to bytecode would make little sense, because then a bytecode interpreter must be shipped in addition to serde-derive, which would itself most certainly take even longer to compile.

**Comment by pacak** [comment]
> Compiling to bytecode would make little sense, because then a bytecode interpreter must be shipped in addition to serde-derive, which would itself most certainly take even longer to compile.

There's https://github.com/dtolnay/watt and readme suggests that compiling a bytecode interpreter is faster than complex macro with dependencies, what's more - it uses `serde` as an example.

**Comment by DarkKirb** [comment]
watt would work for my use-case (cargo2nix), but it is still incompatible with corporate or distro policy

**Comment by dtolnay** [comment]
Thanks for clarifying the unclear wording &mdash; this specifically refers to platforms on which cargo build involves the precompiled implementation in the first place. The crate works on all host platforms on which rustc supports proc macros; not all of those involve a precompiled macro. It also only refers to support extended by a serde maintainer. Support obtained from elsewhere (notably distro packagers) would be free to support different build modes, as always.
