### ISSUE TITLE
Make serde-derive installable system-wide

### ISSUE THREAD

**Issue by Keruspe** [serde-rs/serde#2586]
Making it possible to run e.g. `cargo install serde-derive` then using that installed binary instead of the bundled one would yield the same speed up without the problems that come with the bundled binary.
Would such a solution be acceptable / supported?

**Comment by oli-obk** [comment]
I don't think that is possible at present. We have no way of changing what dependencies to load based on availability of a binary. We could change what binary gets used, but we can't switch to source in case the binary is missing

**Comment by dtolnay** [comment]
I agree with Oli &mdash; pruning the dependency chain (`syn`, `quote`, `proc-macro2`, `unicode-ident`) is the largest part of the benefit, and that has to be decided before _anything_ builds, even build scripts.
