### ISSUE TITLE
serde and serde_derive crates contain a Cargo.toml.orig

### ISSUE THREAD

**Issue by jayvdb** [serde-rs/serde#2589]
I downloaded 1.0.183 manually from crates.io, and both crates contain a `Cargo.toml.orig` which differs significantly from the `Cargo.toml`.

I couldnt see any build step here which is causing this file to be created.

**Comment by NobodyXu** [comment]
This is automatically created by cargo-publish.

If you check other crates, you will notice the same thing.

**Comment by jayvdb** [comment]
I learn something new .. thanks.

**Comment by dtolnay** [comment]
This file in the published crate:

- https://docs.rs/crate/serde_derive/1.0.183/source/Cargo.toml.orig

and this file in the git repository:

- https://github.com/serde-rs/serde/blob/v1.0.183/precompiled/serde_derive/Cargo.toml

have the same contents.
