### ISSUE TITLE
best replacement for `skip_serializing_if_none`

### ISSUE THREAD

**Issue by florianjacob** [serde-rs/serde#261]
c268eb22580dffd63f3f8228cd81264188c396d4 mentions that `skip_serializing_if` should be used to replace `skip_serializing_if_none`. I wonder what's the best way to do so? Do I really need to implement a Trait, or can I somehow use a closure or something?

This doesn't seem to work:

```
struct Point {
    x: usize,
    #[serde(skip_serializing_if="self.y == 0")]
    y: usize,
}
```

results in:

```
src/main.rs:40:33: 40:46 error: expected ident, found `"self.y == 0"`
src/main.rs:40     #[serde(skip_serializing_if("self.y == 0"))]
                                                     ^~~~~~~~~~~~~
src/main.rs:40:47: 40:48 error: expected `]`, found `)`
src/main.rs:40     #[serde(skip_serializing_if("self.y == 0"))]
```

**Comment by compressed** [comment]
This works, not sure if it is the best way though:

```rust
#[derive(Serialize)]
struct Point {
    x: usize,
    #[serde(skip_serializing_if="is_zero")]
    y: usize,
}

fn is_zero(v: &usize) -> bool {
    *v == 0
}
```

**Comment by florianjacob** [comment]
Thanks alot for showing how it works without implementing a trait! :smile: 
I actually needed a replacement for `is_none`, the example was adapted from a serde 0.7 discussion / PR I found somewhere which seemed to support a kind of closure expression.

For anyone also searching this, with the predefined `Option::is_none` function, this boils down to:
```rust
struct Point {
    x: usize,
    y: usize,
    #[serde(skip_serializing_if="Option::is_none")]
    name:  Option<String>,
}
```
…which is quite an elegant & readable solution. Thanks again. :+1:

**Comment by florianjacob** [comment]
(Could be added to the documentation, though, for people coming from serde <0.7 and trying to find out how to replace `skip_serializing_if_none`.)

**Comment by erickt** [comment]
Thanks! I added a small section here: https://github.com/serde-rs/serde#upgrading-from-serde-06
