### ISSUE TITLE
Add #[derive(serde::Default)] that is aware of serde `default` annotations

### ISSUE THREAD

**Issue by BrynCooke** [serde-rs/serde#2622]
When using serde defaulting users currently have to manually create Default implementations that match the serde annotations.

For example:

```rust
    #[test]
    fn test() {
        #[derive(Deserialize)]
        struct Container {
            a: A,
        }
        #[derive(Deserialize)]
        struct A {
            #[serde(default)]
            b: B,
        }

        #[derive(Deserialize, Default)]
        struct B {
            #[serde(default = "true_fn")]
            c: bool,
        }

        fn true_fn() -> bool {
            true
        }

        let container1 = serde_yaml::from_str::<Container>("a: {}").unwrap();
        let container2 = serde_yaml::from_str::<Container>("a: {b: {}}").unwrap();
        println!("{}", container1.a.b.c);
        println!("{}", container2.a.b.c);
    }
```

The output is:
```
true
false
```

This is because the implementation of Default disagrees with the serde defaults.

The current workaround for this is to manually create the default implementation of B such that it agrees exactly with serde. On large and complex structs this is almost guaranteed to lead to errors. 

It'd be great if serde provided derive support for `Default` that is aware of the serde `default` annotations.

**Comment by dtolnay** [comment]
I would prefer not to build this into this crate. But this derive can be implemented in a separate crate.

**Comment by BrynCooke** [comment]
Looks like such a crate already exists: https://docs.rs/serde_default/0.1.0/serde_default/

**Comment by BrynCooke** [comment]
The crate listed above didn't work for me, so I created a new one: https://crates.io/crates/serde_derive_default
