### ISSUE TITLE
using deserialize_with gives unclear error messages.

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [serde-rs/serde#2633]
I want to convert a string to a float, yet even sending in a float directly, gives me an error:
```rust
struct Test {
#[serde(deserialize_with="str_float")] x: f64,
}
```
```rust
fn str_float<'de, D>(x: D) -> Result<f64, D::Error> where D: Deserializer<'de> {

    Ok(1.0)
}
```

```rust
serde_json::from_str(&message.unwrap().into_text().unwrap()).unwrap();
```

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected `,` or `}`", line: 1, column: 83)', src\main.rs:60:96 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Mingun** [comment]
Actually, documentation for `deserialize_with` should be updated, that you MUST consume something from the deserializer (if you do not need anything from deserializer, deserialize `IgnoredAny`), otherwise various bugs are possible, including returning errors or infinity loops.
