### ISSUE TITLE
Constify `Deserialize`(/`Serialize`) on nightly with the `const_trait_impl` and `effects` features.

### ISSUE THREAD

**Issue by bend-n** [serde-rs/serde#2649]
This would make it possible for me to write a proc macro that spawns a rustc process, at compile time, with code, runs it, deserializes that output, in the output code, (so i dont have to spawn yet another process to deserialize the output json) so that you can constify virtually any function.

i am not sure if this is possible

**Comment by oli-obk** [comment]
If you are using a proc macro anyway, you can deserialize the output and generate the constants yourself.

For the general use case of using serde at compile time, I don't think the effect feature is ready enough to be used even behind a cargo feature.

**Comment by bend-n** [comment]
> you can deserialize the output and generate the constants yourself

how?

**Comment by oli-obk** [comment]
I don't know how your proc macro looks, but proc macros generally use the `quote` crate to generate code. You can implement a bunch of `quote` traits to make `quote!(const FOO: YourType = $your_local_variable;` work

**Comment by bend-n** [comment]
Thats not quite what im doing.

My thing, is more of a `r! { || -> chrono::Utc { chrono::Utc::now() } }` kinda thing.

**Comment by oli-obk** [comment]
Gotcha.

I'm going to close this issue, because I think with the current state of const traits there is no need to track anything in individual crates yet
