### ISSUE TITLE
Case insensitive deserialization?

### ISSUE THREAD

**Issue by szguoxz** [serde-rs/serde#2658]
It's just odd, that this can't be done with serde?
I simply want a way to deserialize a json to a struct in a case insensitive manner. A struct may have child struct or deeper. I do not mind to have a derive attribute to each struct involved.

But it seems impossible? Any work around?

Thanks.

**Comment by szguoxz** [comment]
Also, I simply can't get rename_all work. I am not sure if I under stand the doc wrong. The following code keep failing, complaining missing field "Title". This is really ODD.

#[derive(serde::Deserialize)]
        #[serde(rename_all = "lowercase")]
        pub struct YYY
        {
            pub Title: String
        }

        let ss = r#"
        {
            "title": "dsd"
        }
        "#;   
        let x: YYY = serde_json::from_str(ss).unwrap();
        assert_eq!(x.Title, "dsd");

**Comment by oli-obk** [comment]
you can use https://docs.rs/serde-aux/latest/serde_aux/container_attributes/fn.deserialize_struct_case_insensitive.html for case insensitive deserialization.

> The following code keep failing, complaining missing field "Title"

the lowercase attribute assumes your field name is lowercase but your json has uppercase letters, not the other way around

**Comment by Gowee** [comment]
> you can use https://docs.rs/serde-aux/latest/serde_aux/container_attributes/fn.deserialize_struct_case_insensitive.html for case insensitive deserialization.

What about enum?
