### ISSUE TITLE
failed to deserialize untagged enum which has a f64 inner value

### ISSUE THREAD

**Issue by link-duan** [serde-rs/serde#2661]
```rust
#[test]
fn test_debug() {
    #[derive(serde::Deserialize, serde::Serialize, PartialEq, Debug)]
    #[serde(untagged)]
    enum B {
        C(f64),
    }
    
    assert_eq!(serde_json::to_string(&B::C(123.45)).unwrap(), "123.45"); // this assertion is passed
    
    let b: B = serde_json::from_str("123.45").unwrap(); // panicked at here
    assert_eq!(b, B::C(123.45));
}
```

Output Error:
```plaintext
called `Result::unwrap()` on an `Err` value: Error("data did not match any variant of untagged enum B", line: 0, column: 0
```

**Comment by link-duan** [comment]
@dtolnay @erickt

**Comment by dtolnay** [comment]
Derived untagged enums do not support arbitrary precision numbers. If serde_json's "arbitrary_precision" feature is turned on then you need to use serde_json::Number instead.

```rust
#[derive(Deserialize)]
#[serde(untagged)]
pub enum B {
    C(serde_json::Number),
}
```

or deserialize it using [serde-untagged](https://docs.rs/serde-untagged/0.1/serde_untagged).

```rust
pub enum B {
    C(f64),
}

use serde::de::{Deserialize, Deserializer};
use serde_untagged::UntaggedEnumVisitor;

impl<'de> Deserialize<'de> for B {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        UntaggedEnumVisitor::new()
            .f64(|f| Ok(B::C(f)))
            .map(|map| {
                let de = serde::de::value::MapAccessDeserializer::new(map);
                let number = serde_json::Number::deserialize(de)?;
                match number.as_f64() {
                    Some(f) => Ok(B::C(f)),
                    None => Err(serde::de::Error::custom(format!("out of range: {}", number))),
                }
            })
            .deserialize(deserializer)
    }
}
```

**Comment by link-duan** [comment]
> Derived untagged enums do not support arbitrary precision numbers. If serde_json's "arbitrary_precision" feature is turned on then you need to use serde_json::Number instead.
> 
> ```rust
> #[derive(Deserialize)]
> #[serde(untagged)]
> pub enum B {
>     C(serde_json::Number),
> }
> ```
> 
> or deserialize it using [serde-untagged](https://docs.rs/serde-untagged/0.1/serde_untagged).
> 
> ```rust
> pub enum B {
>     C(f64),
> }
> 
> use serde::de::{Deserialize, Deserializer};
> use serde_untagged::UntaggedEnumVisitor;
> 
> impl<'de> Deserialize<'de> for B {
>     fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
>     where
>         D: Deserializer<'de>,
>     {
>         UntaggedEnumVisitor::new()
>             .f64(|f| Ok(B::C(f)))
>             .map(|map| {
>                 let de = serde::de::value::MapAccessDeserializer::new(map);
>                 let number = serde_json::Number::deserialize(de)?;
>                 match number.as_f64() {
>                     Some(f) => Ok(B::C(f)),
>                     None => Err(serde::de::Error::custom(format!("out of range: {}", number))),
>                 }
>             })
>             .deserialize(deserializer)
>     }
> }
> ```

thanks. I did  turned on arbitrary_precision

**Comment by Sytten** [comment]
Apart from "it's not supported", is there an explanation so we can understand what is going on? I am curious
