### ISSUE TITLE
Serialize a struct with variable sized sequence

### ISSUE THREAD

**Issue by steviez** [serde-rs/serde#2664]
Hello, I read the [getting help](https://github.com/serde-rs/serde?tab=readme-ov-file#getting-help) page which suggested some other mediums, but ended up posting an issue here as the issue seems fairly in depth to serde.

Suppose I have some struct I want to serialize (I'm interested in json but I believe that is irrelevant to the question):
```rust
struct Person {
    name: String,
    age: u8,
};

struct Event {
    title: String,
    location: String,
    attendees: Vec<Person>,
}
```
This is a basic type so I could just slap `#[derive(Serialize)]` on the types and be done with it. However, this approach requires that I have all of the `Person` objects collected in a `Vec`. I'm interested in an approach where I could stream the contents of the `attendees` field. Perhaps `attendees` is a very large list that I need to collect from scanning a database or something like that, and that I want to pass the `Serializer` to my scan function to serialize items as I go (as opposed to collecting a very large list and handling at the end).

I know that I can serialize sequences in isolation with `serialize_seq()`. However, I don't think I have the option to do that for the field of a struct per the docs for `SerializeStruct`:
https://docs.rs/serde/latest/serde/ser/trait.SerializeStruct.html

So, two questions:
1. Am I correct that what I'm asking to do is not possible?
2. Could `SerializeStruct` hypothetically be extended to allow a field to be a sequence that is built up element by element (ie same as `serialize_seq()`) as opposed to needing the field to be an already collected container?

**Comment by Mingun** [comment]
Use a supplier struct instead of `Vec<Person>` and stream data as you want:
```rust
struct Supplier(/*connect to DB*/);
impl Serialize for Supplier {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        let mut seq = serializer.serialize_seq(None)?;
        for element in self.stream_data_from_db() {
            seq.serialize_element(element)?;
        }
        seq.end()
    }
}
struct Event {
    title: String,
    location: String,
    attendees: Supplier,
}
```

**Comment by steviez** [comment]
> Use a supplier struct instead of `Vec<Person>` and stream data as you want:
> 
> ```rust
> struct Supplier(/*connect to DB*/);
> impl Serialize for Supplier {
>     fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
>     where
>         S: Serializer,
>     {
>         let mut seq = serializer.serialize_seq(None)?;
>         for element in self.stream_data_from_db() {
>             seq.serialize_element(element)?;
>         }
>         seq.end()
>     }
> }
> struct Event {
>     title: String,
>     location: String,
>     attendees: Supplier,
> }
> ```

Thank you @Mingun! It seems so obvious seeing it written out, but I couldn't think of this earlier and this looks to accomplish exactly what I want. I prototyped this out for my actual use-case and I see no problems, so going to close this issue out. Thanks again!
