### ISSUE TITLE
Enum Representations Internally tagged is Abigious for Tuple Structs

### ISSUE THREAD

**Issue by elibroftw** [serde-rs/serde#2693]
https://serde.rs/enum-representations.html#internally-tagged

There needs to be an example of a Tuple struct here. It's hard to infer how the following would look serialized.

```rs
#[derive(Serialize, Deserialize)]
#[serde(tag = "type")]
enum Message {
    Tuple(String)
}
```
Would this be serialized like this? I only guessed the content field from the "Adjacently tagged" section where `content="c"` was used.

```json
{"type": "Tuple", "content" : "..." }
```

Or like this

```json
["Tuple", "..."]
```

**Comment by elibroftw** [comment]
"cannot serialize tagged newtype variant XXXXXXX::Tuple containing a string"

Nice!

**Comment by elibroftw** [comment]
I believe the adjacent content needs to be before because otherwise it isn't clear that an error will occur

**Comment by dtolnay** [comment]
I think this is covered by the documentation section you linked to where it says:

> This representation works for struct variants, newtype variants containing structs or maps, and unit variants but does not work for enums containing tuple variants.

Your enum has a newtype variant containing a string, which is not any of the supported cases.

**Comment by kirit0s** [comment]
The documentation says that this is a compilation error. But compilation done without errors.

> Using a #[serde(tag = "...")] attribute on an enum containing a tuple variant is an error at compile time.

**Comment by Mingun** [comment]
The topicstarter used wrong name for his example. This is what is named "newtype" in serde. Tuple contains 0 or 2 or more elements

**Comment by kirit0s** [comment]
@Mingun 
Can you please provide example of enum with tuple variant, which is mentioned in the documentation?

**Comment by kirit0s** [comment]
```rs
#[derive(Serialize)]
#[serde(tag = "tag")]
enum A {
  VariantOne((i32, i32))
}
```

Also compile without errors.

**Comment by Mingun** [comment]
```rust
#[derive(Serialize)]
#[serde(tag = "tag")]
enum A {
  Tuple(i32, i32)
}
```

**Comment by kirit0s** [comment]
Ok, now I see compile error.

I wonder if it is possible to check at compile time, that newtype variants containing invalid type for serialize with internally tagged representation.

**Comment by Mingun** [comment]
Probably it is possible if introduce a set of traits and require that traits when deriving
