### ISSUE TITLE
Macro serialization for struct methods

### ISSUE THREAD

**Issue by kardeiz** [serde-rs/serde#271]
Is there any plan to add annotations that would allow (public) struct methods to be serialized? Something like:

```
#[derive(Serialize, Deserialize, Debug)]
struct Foo { /* ... */ }
impl Foo {
    #[serde(serialize))]
    pub fn bar(&self) -> i32 {
        // ...
    }
}
```

For example, this would be similar to the `@JsonProperty` annotation for methods used by some Java JSON libraries.

I asked about this on [StackOverflow](http://stackoverflow.com/questions/36159031/add-struct-method-to-serde-serialization-output) and received a possible workaround, but no definitive answer.

It seems like this would be a pretty common scenario, where one would want to serialize something that might not be a field (unless I am missing something). I skimmed through the issues and didn't see any relevant discussion, but I apologize if this has been discussed elsewhere&mdash;

**Comment by jwilm** [comment]
How is that "property" supposed to be deserialized?

**Comment by kardeiz** [comment]
Right&mdash;I understand that this would be a one-way kind of thing. It's very possible that this would be out of the scope of `serde` since there would be no pure back-and-forth serialization-deserialization. I guess it might be more appropriate to structure this "view" of the struct through a separate struct, as suggested by Shepmaster on SO.

I just know that `@JsonProperty` and similar features are very convenient in the languages where I have used them...

**Comment by dtolnay** [comment]
See #760 for a similar request - serializing constant values.

```rust
// must be serialized as {"type": "Program", "body": [...]}
pub struct Program {
    pub body: Vec<Stmt>
}

#[serde(tag = "type")]
pub enum Expr {
    // must be serialized as {"type": Literal", "value": null}
    Literal
}
```

Given that we never want to have people writing code inside of attributes, I think this is just a degenerate case of serializing method values.

**Comment by TedDriggs** [comment]
@dtolnay, the enum tag case feels a bit special, in part because I don't know how one would access the tag name for a variant in a method on the enum.

**Comment by dtolnay** [comment]
Oh in the enum case it is not the tag that would be added. That is already supported. See [playground](http://play.integer32.com/?gist=4d429c12b7f4c0e65d36cf486333567a). The user wants to add the constant field `"value": null`.

**Comment by GyrosOfWar** [comment]
I've looked into this a little. I imagine it would be nice if you could do something like
```rust
#[derive(Deserialize)]
struct Test {
    value: i32
}

impl Test {
    // The name attribute would be optional, the default name would be the name of the function
    #[serde(serialize(name = "data"))]
    pub fn as_string(&self) -> String {
        format!("The number is {}", self.value)
    }
}
```
However my knowledge of syn is very limited (as in, I looked at some of serde's attribute parsing code for about an hour today) and I couldn't find how to parse attributes on methods. Is there some existing code that I could look at that does this? If this isn't possible, you'd have to specify the methods as paths in a container attribute (which wouldn't be as nice I think).

**Comment by dtolnay** [comment]
As nice as it is, we won't be able to do it that way. Macro expansion (including derive expansion) happens before any type information is available, including information about what methods exist on what types. I think this feature would need to be a container or variant attribute.

**Comment by GyrosOfWar** [comment]
So I guess it could look like this?
```rust
#[derive(Deserialize)]
#[serde(method_properties(data = "Test::as_string"))]
pub struct Test {
    dummy: i32,
}

impl Test {
    pub fn as_string(&self) -> String {
        format!("Value {}", self.dummy)
    }
}
```
The name of the deserialized property would then be `data`.

**Comment by dtolnay** [comment]
Yep, something like that would be reasonable. A couple things left to figure out:

1. How to specify names that are not valid words in an attribute? For example a fake field called `da-ta` or `da.ta` or `da ta`.
2. How do these compose with field attributes, if at all? For example, say I want to serialize the value of `Test::as_string` but use a `skip_serializing_if` or `serialize_with` attribute on it.
3. How do these compose with container attributes? If there is a `rename_all` on the container, does that apply to this fake field?

**Comment by GyrosOfWar** [comment]
I think I'll just focus on getting a basic implementation running first and keep those in the back of my head. I committed some code to my fork of the repository; I think I found the spot where I'd have to put the code to deserialize the additional properties but I'm not quite clear on how to generate the code yet. Parsing the attribute seems to work.

**Comment by dtolnay** [comment]
Closing because I would prefer for this functionality to be provided in a different crate. Something like:

```rust
#[derive(Serialize_extra)]
#[extra(k = "data", v = "Self::compute_b")]
struct Test {
    a: i32,
}

impl Test {
    fn compute_b(&self) -> String {
        /* ... */
    }
}
```

```rust
// expands to:

impl Serialize for Test {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        #[derive(Serialize)]
        #[serde(rename = "Test")]
        struct Helper {
            a: i32,
        }

        /*
        Code similar to TaggedSerializer https://github.com/serde-rs/serde/blob/v1.0.85/serde/src/private/ser.rs#L96
        for serializing Helper with all the requested extra fields injected
        */
    }
}
```
