### ISSUE TITLE
Taking an ownership of archived serde-yaml

### ISSUE THREAD

**Issue by SVilgelm** [serde-rs/serde#2722]
Hello,

The [serde-yaml](https://github.com/dtolnay/serde-yaml) project has been archived recently. Would you be interesting in forking it under the serde-rs org?

The project will be a very valuable addition to serde family.

**Comment by dtolnay** [comment]
I would not be interested in forking it here.

**Comment by oli-obk** [comment]
David is the main maintainer of serde-rs and also the owner of serde-yaml 🤣 I think that answers your question with "No"

**Comment by SVilgelm** [comment]
> David is the main maintainer of serde-rs and also the owner of serde-yaml 🤣 I think that answers your question with "No" Edit: damn, too slow

didn't know
