### ISSUE TITLE
serde-parquet

### ISSUE THREAD

**Issue by kurt-rhee** [serde-rs/serde#2758]
Hello, 

First off, thank you for serde, it has made my life much easier.  I was wondering, is there a serde-parquet like there is serde-json?  Apologies if this has already been asked, I looked through the issue tracker and was not able to find any similar questions.

**Comment by lucianosrp** [comment]
Hi! 

There seems to be an implementation on GitHub but I haven't tried it and it doesn't seem to be maintained. https://github.com/ali5h/serde-parquet

Depending on your use-case you might want to have a look at the offical [parquet crate](https://crates.io/crates/parquet)

If you really need to use `serde`, I found out a quick combinations between `serde_json` and the `Row.to_json_value` method.  Here is a snippet: 

```toml
[dependencies]
parquet = { version = "52.2.0", features = ["json"] }
serde = { version = "1.0.207", features = ["serde_derive"] }
serde_json = "1.0.124"
```

Sample `Titanic.parquet` from [here](https://www.tablab.app/datasets/sample?datatable-source=demo-titanic)

```rust
use parquet::{
    file::reader::{FileReader, SerializedFileReader},
    record::Row,
};
use serde::{Deserialize, Serialize};
use std::{fs::File, path::Path};

#[derive(Deserialize, Serialize, Debug)]
#[serde(rename_all = "PascalCase")]
struct Passenger {
    name: String,
    sex: String,
    age: Option<f32>,
}

impl From<Row> for Passenger {
    fn from(val: Row) -> Self {
        serde_json::from_value(val.to_json_value()).unwrap()
    }
}

fn main() -> Result<(), parquet::errors::ParquetError> {
    let path = Path::new("Titanic.parquet");
    if let Ok(file) = File::open(path) {
        let reader = SerializedFileReader::new(file)?;
        let row_group_reader = reader.get_row_group(0)?;
        let ri = row_group_reader.get_row_iter(None)?;
        let passengers: Vec<Passenger> = ri.map(|x| x.unwrap().into()).collect();
        println!("{:?}", passengers);
    }
    Ok(())
}
```

Again, it all really depend on your case, and some of the stuff  I wrote above may need a better implementation.
Not sure if this helps ..  Let me know what approach you end up taking !   :)

**Comment by kurt-rhee** [comment]
This is great!  Thank you so much, I am going to try the official crate.
