### ISSUE TITLE
Convert serde_json::error::Error to serde::de::Deserializer::Error

### ISSUE THREAD

**Issue by shahn** [serde-rs/serde#276]
For the other conversion direction, there's a From implementation, but not this way.

**Comment by dtolnay** [comment]
Can you justify this by sharing the code where this would have been useful?

**Comment by shahn** [comment]
When I chatted with erickt about it I used this small code sample https://gist.github.com/shahn/32fa57a6fd1f2e3b3224b3e925308960 - he said that the change to support this kind of use case is probably useful, but maybe too disruptive to do.

**Comment by dtolnay** [comment]
What impl do we need to provide to make this better? Rust does not allow us to provide `impl<T> From<serde_json::Error> for T where T: de::Error`.

**Comment by shahn** [comment]
I think (after a discussion with @erickt on irc) that this would require a larger refactoring and a breaking change

**Comment by shahn** [comment]
I wonder if this should be closed as wontfix or if this is still considered as a worthwhile thing?

**Comment by dtolnay** [comment]
As of Serde 0.9 this is no longer as bad as it was in 0.8 because the Error trait changed from taking Into\<String> to taking Display. So this sort of conversion can now be done with map_err(Error::custom).

For example:

```rust
fn from_json<T, D>(deserializer: D) -> Result<T, D::Error>
    where T: Deserialize,
          D: Deserializer
{
    let s = String::deserialize(deserializer)?;
    serde_json::from_str(&s).map_err(Error::custom)
}
```
