### ISSUE TITLE
`IpAddr` and `SocketAddr` are in `core`, but serde implements only for `std`

### ISSUE THREAD

**Issue by Ddystopia** [serde-rs/serde#2760]
Hello, recently `IpAddr` was moved to `core`, but serde still requires `std` feature

**Comment by MathiasKoch** [comment]
Would a PR fixing this be accepted, even though it would raise MSRV significantly?

**Comment by oli-obk** [comment]
This should just affect/duplicate a few imports behind cfgs, this seems fine to me.
