### ISSUE TITLE
Differentiated Serialization Formats for Structs

### ISSUE THREAD

**Issue by XuJiandong** [serde-rs/serde#2766]
### Problem Statement

I have the following struct definitions:

```rust
#[derive(Serialize, Deserialize)]
struct TypeA {
    // ...
}

#[derive(Serialize, Deserialize)]
#[special_compact]
struct TypeB {
    // ...
}
```

The goal is to serialize `TypeA` and `TypeB` into different formats. Specifically, `TypeB` should be serialized into a more compact format than `TypeA`. 

### Expected Behavior

- `TypeA` should be serialized using the default serialization format.
- `TypeB` should be serialized using a custom, compact format as indicated by the `#[special_compact]` attribute.

### Actual Behavior

Currently, both `TypeA` and `TypeB` are serialized using the same format, and there doesn't seem to be an out-of-the-box solution for differentiating their serialization formats.

### Request for Solution

Is there a way to achieve this within the current framework of `serde`? If not, could you provide guidance or a potential feature enhancement to support this functionality?

Thank you!

**Comment by devnetsec** [comment]
Serde provides a *framework* for serialization and deserialization using Rust's trait system. Other crates, like `serde_json`  actually implement the data formats. If your types implement `Serialize` and `Deserialize`, then any data format that uses `Serde` can be used to serialize and deserialize data of these types. The [homepage](https://serde.rs) provides a list of such data formats.

**Comment by dtolnay** [comment]
Devnetsec's response speaks to your misconception, I think. There is no "default serialization format" that a `Serialize` impl gives you. You can serialize the same data structure in a variety of human-readable formats and compact formats with a single `Serialize` impl. The data format you serialize it to is not decided by the Serialize derive.
