### ISSUE TITLE
CVE RUSTSEC-2024-0320 yaml-rust is unmaintained; Consider using a maintained alternative

### ISSUE THREAD

**Issue by gacallea** [serde-rs/serde#2768]
Hi,

I am learning Rust (very early stages still) and, along with it, computer science. Because I want to be a good self-taught software engineer. I recently started exploring and learning about AppSec/DevSec and the importance of [Securing the entire SDLC](https://www.youtube.com/watch?v=hDvz8KivY_U). Among other "findings" (tools, websites, guidelines and so forth), I just found out about [RustSec](https://rustsec.org/).

Because I love learning by both studying and doing, I have an itch to scratch app that I will (knock knock) start coding as soon as I finish The Book and Rust in Action. That said, I have already researched the tools and crates I will be using. One of them is `rusti18n` which depends on `serde`. So today, out of curiosity I ran `cargo audit` (from RustSec) and found out about [https://rustsec.org/advisories/RUSTSEC-2024-0320](https://rustsec.org/advisories/RUSTSEC-2024-0320) impacting this very project.

I believe it would be beneficial if `rusti18n` could adopt the proposed resolution of that CVE: switching to a maintained package.

Please and thank you

**Comment by dtolnay** [comment]
Serde does not depend on yaml-rust, so this issue has nothing to do with this repo. If there is some library in your dependency graph that depends on yaml-rust, you would need to report the issue to that library's repo.

**Comment by gacallea** [comment]
hi @dtolnay , my bad. I may have misread the output:

```bash
╰─❯ cargo audit
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
      Loaded 630 security advisories (from /Users/andreacfromtheapp/.cargo/advisory-db)
    Updating crates.io index
    Scanning Cargo.lock for vulnerabilities (458 crate dependencies)
Crate:     yaml-rust
Version:   0.4.5
Warning:   unmaintained
Title:     yaml-rust is unmaintained.
Date:      2024-03-20
ID:        RUSTSEC-2024-0320
URL:       https://rustsec.org/advisories/RUSTSEC-2024-0320
Dependency tree:
yaml-rust 0.4.5
└── serde_yaml 0.8.26
    ├── rust-i18n-support 3.0.1
    │   ├── rust-i18n-macro 3.0.0
    │   │   └── rust-i18n 3.0.1
    │   │       └── crab_news 0.1.0
    │   └── rust-i18n 3.0.1
    └── rust-i18n-macro 3.0.0

warning: 1 allowed warning found
```

is serde_yaml a different package then?

sorry!

**Comment by gacallea** [comment]
I answer my own: yes it is and it is deprecated.

**Comment by gacallea** [comment]
Hi @dtolnay,

I was thinking about this issue and it must have come across badly. Besides the mistake of not making sure about the dependency, I only had good intentions. That said, my apologies if this has annoyed/offended you in any way.

Cheers
