### ISSUE TITLE
suggestion: deserializing should make position (line number and column) of deserialized objects opaque to calling code

### ISSUE THREAD

**Issue by ilka-schulz** [serde-rs/serde#2790]
I would love to deserialize data and keep the information where each object was placed in the serialized stream:

```rust
#[derive(Deserialize)]
struct MyDocument {
    foo: WithPositionAnnotation<String>,
    bar: WithPositionAnnotation<i64>,
}

let serialized = "foo=\"abc\"\nbar=123";

let deserialized = MyDocument::deserialize(toml::Value::from_str(serialized));
```

I would then like to know the position of `foo` (1:1) and `bar` (2:1).

**Comment by luoky69** [comment]
Hello, in your gitlab project [ASCLEPIOS](https://gitlab.com/asclepios-project)
[Platform](https://gitlab.com/asclepios-project/platform), there is no .env.example file which you said we should do cp in your readme.md
How can I contact you? or could you please help me with this issue?

**Comment by oli-obk** [comment]
This can be done for your own formats by tracking the information in thread local tables.

Exposing this information from serde would require major changes for little benefit to most users. I think serde is the wrong tool for this. You probably want to directly use a parser that exposes such information
