### ISSUE TITLE
 Unlock issue #2016

### ISSUE THREAD

**Issue by robertbastian** [serde-rs/serde#2807]
The issue was locked without any comment, and without addressing https://github.com/serde-rs/serde/issues/2016#issuecomment-1019423610, which imho deserves a response.

**Comment by oli-obk** [comment]
`serde_derive` is in maintenance mode and only gets critical bug fixes or whatever maintainers find the *intrinsic* motivation and time for. There are workarounds for this, so it's not something to spend valuable time on
