### ISSUE TITLE
`anyhow::Result` for custom impl of `Deserialize<'de>`

### ISSUE THREAD

**Issue by amab8901** [serde-rs/serde#2809]
I'm doing custom implementation of Deserialize and it looks like this:

```
impl<'de> Deserialize<'de> for Object {
    fn deserialize<D>(deserializer: D) -> std::result::Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {...}
}
```

Now if I have a Result type inside `deserialize(..)` function body, I have to write `unwrap()` to keep it brief, or I have to write a longer error handling to match `D::Error` in return type. But ideally, I'd like to be able to use `anyhow::Result` so I can just use question mark operator instead. Perhaps u can implement `anyhow` feature in serde?

**Comment by dtolnay** [comment]
I would prefer not to allow returning `anyhow::Error` from Deserialize impls. The current signature is intentional and requires you to return `D::Error`, which is whatever error type the user will get from the data format they are using.
