### ISSUE TITLE
Allow configuration for extra spaces after field

### ISSUE THREAD

**Issue by Jasperav** [serde-rs/serde#2810]
I am parsing, modifying and writing away a json file with an .xcstrings extension. It's from Apple and it's used to localize apps on all their platforms.

There is one little 'issue' I want to solve. Apple, for some reason, adds a space after each field. I don't think it's possible in serde, so now my whole changelog is full with this:

![image](https://github.com/user-attachments/assets/b71970e0-13af-4a34-bc91-771e135c74a1)

To clarify: the gray part is from Apple, the green part was originally a Rust struct and serialized with serde.

Can an extra space be configurable in serde?

**Comment by martin-g** [comment]
Since you talk about JSON I think this issue should be moved to https://github.com/serde-rs/json.
Also take a look at https://github.com/serde-rs/json/blob/master/src/ser.rs and more specifically https://github.com/serde-rs/json/blob/50c4328e2199a54e9952bf63f120ff00e9cee44a/src/ser.rs#L48

**Comment by dtolnay** [comment]
That's right &mdash; this would be implemented using a JSON Formatter.
