### ISSUE TITLE
serde `default` attribute fails on bool

### ISSUE THREAD

**Issue by wcarmon** [serde-rs/serde#2815]
How can we set a default of `true` for a boolean field?

The following two attempts fail compilation

```rust
use serde::Deserialize;

#[derive(Deserialize)]
struct Foo {
    #[serde(default = true)]
    b: bool,
}
```
**error: expected serde default attribute to be a string: `default = "..."`**

```rust
use serde::Deserialize;

#[derive(Deserialize)]
struct Baz {
    #[serde(default = "true")]
    b: bool,
}
```
**error: failed to parse path: "true"**

Related documentation: https://serde.rs/attr-default.html

**Comment by oli-obk** [comment]
As the documentation states, a function name/path is expected. The function should return the type of the field. So you'd need a `fn mk_true() -> bool { true }` and specify that.

You can read more about hypothetical future support in https://github.com/serde-rs/serde/issues/368
