### ISSUE TITLE
Pass deserialize through a reference.

### ISSUE THREAD

**Issue by 10takla** [serde-rs/serde#2827]
For scenarios where I need to use deserialization several times [`deserialize`](https://docs.rs/serde/latest/serde/trait.Deserialize.html#tymethod.deserialize) is not good.
For example the field `id: i32` in serialized json form can be a number, or it can be a string, and I would like to handle both cases in one step: first try [`String:deserialize`](https://docs.rs/serde/latest/serde/trait.Deserialize.html#impl-Deserialize%3C'de%3E-for-String), if error, then [`i32::deserialize`](https://docs.rs/serde/latest/serde/trait.Deserialize.html#impl-Deserialize%3C'de%3E-for-i32). But I can't, since `deserialize` passes possession at the time of `String:deserialize`.

**Comment by oli-obk** [comment]
We cannot make `deserialize` reusable, as the deserializer may not be able to roll back (e.g. if reading from a network stream) in order to retry.

What you can do instead is to change the field deserialization to be able to handle both strings and ints: https://serde.rs/string-or-struct.html

**Comment by 10takla** [comment]
> deserializer may not be able to roll back

Is my understanding correct that the deserializer sequentially scans through the string, and when it tries to deserialize a field, the pointer moves forward, and it cannot return back because there is no mechanism for this? Since I am not familiar with the details of how serde works, I would like to ask you: if such a mechanism existed, would it be useful? Do you think it could negatively affect performance and memory consumption?

**Comment by oli-obk** [comment]
It's impossible to add such a mechanism. The bytes may have been read from a network stream and discarded. I don't think it is necessary even if we can figure it out due to buffering and such as there is already a solution that will work
