### ISSUE TITLE
Examples/Enum representations says tuple variants can't use internally tagged representation

### ISSUE THREAD

**Issue by LunarLambda** [serde-rs/serde#2834]
...even though they can.

https://serde.rs/enum-representations.html#internally-tagged

> This representation works for struct variants, newtype variants containing structs or maps, and unit variants but does not work for enums containing tuple variants. **Using a `#[serde(tag = "...")]` attribute on an enum containing a tuple variant is an error at compile time.**

(Emphasis mine)

Example: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=a82b6ee3b1f12cb2fc1e1869533b50e6

**Comment by dtolnay** [comment]
Those are newtype variants in your playground, not tuple variants.
