### ISSUE TITLE
Negative zero being deserialized as a float

### ISSUE THREAD

**Issue by mbhall88** [serde-rs/serde#2867]
I have a strange example (which may just be my misunderstanding) where a JSON value of `-0` is being deserialized to a float even though it should be an `i64`. An example

```rust
use serde::Deserialize;

#[derive(Debug, Deserialize, PartialEq)]
struct Score {
    median_dist: i64,
}

fn main() {
    let json = r#"{ "median_dist": -0 }"#;
    let result: Result<Score, _> = serde_json::from_str(json);
    match result {
        Ok(score) => println!("Deserialized score: {:?}", score),
        Err(e) => println!("Failed to deserialize: {}", e),
    }
}
```

this errors with `Failed to deserialize: invalid type: floating point `-0.0`, expected i64 at line 1 column 19`

However, I can do

```rust
let i: i64 = -0;
println!("{}", i);
```

without any such issues and this prints `0`

If I remove the negative sign (`0`) it works as expected. My current workaround is to create a custom deserializer which handles the case of -0.

I know in a perfect world there just shouldn't be a sign on the zero, but this is what the API I am calling to is returning to me.

This is my current workaround

```rust
use serde::de::{self, Deserializer};
use serde::Deserialize;

fn deserialize_vec_i64_from_any<'de, D>(deserializer: D) -> Result<Vec<i64>, D::Error>
where
    D: Deserializer<'de>,
{
    let values = serde_json::Value::deserialize(deserializer)?;
    match values {
        serde_json::Value::Array(arr) => {
            let mut result = Vec::new();
            for value in arr {
                match value {
                    serde_json::Value::Number(num) => {
                        if let Some(i) = num.as_i64() {
                            result.push(i);
                        } else if let Some(f) = num.as_f64() {
                            if f == -0.0 {
                                result.push(0);
                            } else {
                                return Err(de::Error::custom(format!("expected i64, got {}", f)));
                            }
                        } else {
                            return Err(de::Error::custom(format!("expected i64, got {}", num)));
                        }
                    }
                    _ => return Err(de::Error::custom(format!("expected i64, got {}", value))),
                }
            }
            Ok(result)
        }
        _ => Err(de::Error::custom("expected an array of i64")),
    }
}

#[derive(Debug, Deserialize, PartialEq)]
struct Score {
    #[serde(deserialize_with = "deserialize_vec_i64_from_any")]
    median_dist: i64,
}
```

**Comment by jakoritarleite** [comment]
As seem this is a problem with the [`Deserializer::parse_number`](https://github.com/serde-rs/json/blob/4aa05b9143ea7ca9c690e874f4c0f4f43cae9716/src/de.rs#L503) method, where it falls under the rest case, and as [stated there](https://github.com/serde-rs/json/blob/4aa05b9143ea7ca9c690e874f4c0f4f43cae9716/src/de.rs#L513) it converts into a float if underflow or if value is `-0`.

This was introduced in the following commit: [51a4db1](https://github.com/serde-rs/json/commit/51a4db1631d2746f28fe3b6f2eafda3aff03af4b) from this pull request [serde_json#801](https://github.com/serde-rs/json/pull/801)

**Comment by mbhall88** [comment]
Thanks for pointing out the origin. I had been looking for a while but couldn't see it. I don't really care about the sign, so I'll just stick to my workaround of forcing it to an integer.
