### ISSUE TITLE
Heads-up: #[start] is being removed

### ISSUE THREAD

**Issue by RalfJung** [serde-rs/serde#2870]
We are planning to remove the unstable `#[start]` attribute from the compiler, see https://github.com/rust-lang/rust/pull/134299 for rationale and further details. This repo showed up in a search for users of the attribute in [this file](https://github.com/serde-rs/serde/blob/master/test_suite/no_std/src/main.rs). For all we know, there's no good reason to use this attribute and you can do the following instead:
```rust
#![no_main]

#[no_mangle]
extern "C" fn main(argc: core::ffi::c_int, argv: *const *const u8) -> core::ffi::c_int {
  // ...
}
```

If that for some reason does not work, please let us know!

**Comment by dtolnay** [comment]
Thanks!
