### ISSUE TITLE
DeserializeSeed doesn't support certain stateful deserialization patterns

### ISSUE THREAD

**Issue by starptr** [serde-rs/serde#2875]
As an example, I have some data that looks like this:
```rust
#[derive(Serialize, Deserialize)]
struct Truth {
    id: u64;
}
struct Data {
    source_of_truth: Vec<Arc<Truth>>,
    how_many_truths: Vec<Weak<Truth>>,
}
```
- `Data` is a struct where `how_many_truths` has weak pointers that point to `source_of_truth`
- I've serialized the `Weak<Truth>` to be `Truth::id` and `Arc<Truth>` to be the derived `Truth`.

When defining the deserialization for `Data` for the `how_many_truths` field, I need to access the already-deserialized `source_of_truth` pointers to construct the corresponding `Weak` pointers. To do so, I want to pass in some state, i.e. `source_of_truth` to the `DeserializeSeed` implementation for `how_many_truths`. However, the current signature for `next_value_seed()` doesn't seem to support this, as the seed must be the same type as the deserialized value. This won't work here because the seed is `Vec<Arc<Truth>>` and the deserialized value is `Vec<Weak<Truth>>`.

Am I understanding how `next_value_seed()` should be used correctly? What's the intended way to deserialize a struct like this?

**Comment by dtolnay** [comment]
> the seed must be the same type as the deserialized value.

This is not the case. The seed can be an arbitrary type that has a DeserializeSeed implementation.

https://docs.rs/serde/1/serde/de/trait.MapAccess.html#tymethod.next_value_seed

**Comment by starptr** [comment]
Oh I see thanks, I didn't read this carefully enough; the `DeserializeSeed::Value` type is used here to specify the return type, not `DeserializeSeed`.

**Comment by starptr** [comment]
For posterity:

When writing
```rust
impl DeserializeSeed for Foo { … }
```
and
```rust
impl Deserialize for Bar { … }
```
the two impls are *not* following the same "pattern". That is, while the second block semantically means we are implementing deserialization for `Bar`, the first block does *not* semantically mean that we are implementing a stateful deserialization for `Foo`. The first block is actually implementing a stateful deserialization method that returns `DeserializeSeed::Value`, and `Foo` is actually the type of the seed. This interpretation makes much more sense when recalling the signature of `next_value_seed()`. In hindsight, this should've been obvious, but I got tricked because both traits declare `deserialize()` so my brain assumed both traits have the same pattern 🥲
