### ISSUE TITLE
Conditionally using Serde (cargo feature)

### ISSUE THREAD

**Issue by hgrecco** [serde-rs/serde#288]
I am trying to use serde as optional feature defined in cargo. Most of the time is quite easy because I can just use `cfg` to conditional compile certain functions or modules. But I am having trouble to conditionally compile `Serialize, Deserialize` within a `derive` call. The only way I have found is repeating the struct twice but is not convenient. Is there any convenient way to achieve it?

**Comment by dtolnay** [comment]
Does [`cfg_attr`](https://doc.rust-lang.org/book/conditional-compilation.html#cfg_attr) do what you want?

```rust
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
struct X { ... }
```

Currently there is a bug (#148) where this does not work if you use a build.rs to run the code generator, but it should work if you use `#![plugin(serde_macros)]`.

**Comment by hgrecco** [comment]
That should do it. What would be the right way if I want to derive Debug in all cases?

**Comment by hgrecco** [comment]
Additionally, have you thought about creating a no op crate? In that way I could just change the extern part. It would make thing much cleaner

**Comment by dtolnay** [comment]
```rust
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
struct X { ... }
```

Do you mean a no-op crate specifically for `derive(Serialize, Deserialize)` which marks the attribute as used but ignores it? We could make one, but it would not replace `cfg_attr` for people who use it to (1) work with stable Rust which does not support compiler plugins, or (2) avoid a dependency.

**Comment by hgrecco** [comment]
Thanks for taking the time to answer. Indeed I was thinking about a crate that allows you to do:

```rust
#[cfg(feature="serde")]
extern crate serde;
#[cfg(not(feature="serde"))]
extern crate serde_noop;

#[derive(Debug,Serialize, Deserialize)]
struct Point {
    x: i32,
    y: i32,
}
```

Might not seem like a big win. But when you have lots of structs, it is certainly helpful and keeps the code cleaner. Not sure if you can do something like that works in stable rust.

Regarding the the dependency, I think that an extra light weight trait is not such a big deal. In particular with Cargo that makes things really simple.

**Comment by dtolnay** [comment]
I filed #289 to track your idea.
