### ISSUE TITLE
ASN.1 serialization/deserialization

### ISSUE THREAD

**Issue by MrSpock** [serde-rs/serde#292]
Is there any plan for support ASN.1/BER support. This would help a lot to create rust libraries that are using this. For example there is no SNMP library for rust. Creation would be possible if ASN.1 encoder/decoder exist.

**Comment by oli-obk** [comment]
There's already DER support here: https://github.com/alex/rust-asn1

Maybe you can add BER support to that crate.

**Comment by cmr** [comment]
An OER encoder would be very interesting to me.

**Comment by dtolnay** [comment]
I am closing this because I do not plan to dedicate Serde developer time to implementing this. I would love if anybody steps up to implement ASN.1 support for Serde in a separate crate.
