### ISSUE TITLE
Ownership of serde_json

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#299]
@erickt @nox @pcwalton What is the story? It looks like there are a few PRs that have sat for 2 months. Is anyone responsible for those?

**Comment by oli-obk** [comment]
I have github permissions to do stuff, but we've never talked about whether these permissions should be used and how much they should be used.

@erickt feel free to offload PRs on `serde` and `serde_json` to me (or I can start reviewing PRs on my own, just a question of whether I should merge PRs, too, or just @mention you when I feel it's ready)

we could also setup bors to automatically start assigning PRs to people

**Comment by dtolnay** [comment]
I am also happy to help out, at least as far as triage and review.

In general I think all of these repos have suffered from painfully slow iteration time on PRs and I think we can do a lot better going forward.

**Comment by oli-obk** [comment]
@erickt any thoughts on this topic?

**Comment by dtolnay** [comment]
I will try to bring this up with Erick in person at the SF meetup on Thursday because I think this is important.

**Comment by erickt** [comment]
Hey folks! I'd love the help actually. I've been swamped and haven't had enough time for serde as you've seen. @dtolnay, you've also been doing great work. Want to also help? The main thing is to just make weird to respect semver so we might need to bump the major version now and then.

**Comment by dtolnay** [comment]
I would like to help. Mainly we were wondering whether you are comfortable with Oliver merging PRs when he (or both he and I) thinks they are ready.

Please add Oliver as a collaborator on serde-json (weird that being in the [serde-rs org](https://github.com/orgs/serde-rs/people) does not give him that, according to https://github.com/serde-rs/serde/issues/299#issuecomment-215655377).

If you are okay with it, add me as well and that would help me close issues (#90 #141 #158 are the ones I have been trying to get someone to close, maybe a few others) and merge simple things like docs fixes or commits that have been reviewed and the feedback addressed.

@oli-obk once @erickt gives you permission, let's both of us try to get through the serde-json PRs in the next couple days. The oldest one is 10 weeks old.

**Comment by dtolnay** [comment]
This has been addressed. Oliver and I will continue to play an active role in serde_json.
