### ISSUE TITLE
think about generating code from a json spec

### ISSUE THREAD

**Issue by erickt** [serde-rs/serde#3]
https://github.com/KhronosGroup/glTF/blob/master/specification/glTF.schema.json

**Comment by dtolnay** [comment]
Updated link: https://github.com/KhronosGroup/glTF/blob/d453cd16420d4f3c8a0bf4a1f1c7a9c8c4f70fbc/specification/schema/glTF.schema.json

**Comment by dtolnay** [comment]
I am closing this as something that I don't think the Serde team needs to own. Please comment if anyone feels strongly otherwise.
