### ISSUE TITLE
Regression in serde_codegen 0.7.4

### ISSUE THREAD

**Issue by benashford** [serde-rs/serde#305]
Today I have upgraded one of my projects, updating all the Serde dependencies to the latest versions.  My project can be found here: https://github.com/benashford/rs-es/tree/upgrade_serde_dependencies the upgrade is currently in a branch `upgrade_serde_dependencies`.

In the project I have many structs which use `#[derive(Deserialize)`, these were all working and tested using the previous version of serde_codegen, but since 0.7.4 it seems to be generating incorrect code.  But only for two of the structs.

What the two structs have in common is a type parameter, with a trait bound of `Deserialize` (i.e. the struct could contain any arbitrary struct which is also deserializeable).

The specific structs are: [SearchHitsHitsResult](https://github.com/benashford/rs-es/blob/upgrade_serde_dependencies/src/operations/search/mod.rs#L738-L755) and [GetResult](https://github.com/benashford/rs-es/blob/upgrade_serde_dependencies/src/operations/get.rs#L121-L135)

The error is repeated for every field in each struct:

```
src/operations/get.rs:122:1: 122:30 error: mismatched types:
 expected `std::string::String`,
    found `T`
(expected struct `std::string::String`,
    found type parameter) [E0308]
src/operations/get.rs:122 #[derive(Debug, Deserialize)]
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/operations/get.rs:122:1: 122:30 note: in this expansion of #[derive_Deserialize] (defined in src/operations/get.rs)
src/operations/get.rs:122:1: 122:30 note: in this expansion of include!
src/operations/get.rs:122:1: 122:30 help: run `rustc --explain E0308` to see a detailed explanation
```

And also, for each field in both structs:

```
src/operations/get.rs:122:1: 1:1 error: mismatched types:
 expected `T`,
    found `operations::get::_IMPL_DESERIALIZE_FOR_GetResult::<impl serde::Deserialize for operations::get::GetResult<T>>::deserialize::__Field`
(expected type parameter,
    found enum `operations::get::_IMPL_DESERIALIZE_FOR_GetResult::<impl serde::Deserialize for operations::get::GetResult<T>>::deserialize::__Field`) [E0308]
(internal compiler error: unprintable span)
src/operations/get.rs:122:1: 1:1 note: in this expansion of #[derive_Deserialize] (defined in src/operations/get.rs)
src/operations/get.rs:122:1: 1:1 note: in this expansion of include!
src/operations/get.rs:122:1: 1:1 help: run `rustc --explain E0308` to see a detailed explanation
```

All of the above is with Rust: `rustc 1.10.0-nightly (8da2bcac5 2016-04-28)` but it can also be seen with the stable and beta Rust's too.

The output is quite long, so I won't list it all here, but for reference it can be seen on the Travis CI log of my project: https://travis-ci.org/benashford/rs-es/builds/127847754

**Comment by dtolnay** [comment]
Type inference is failing us for some reason. I have narrowed it to the following fairly-reasonable-looking code:

```rust
struct Generic<T: Deserialize> {
    v: Option<T>
}

impl<T: Deserialize> Deserialize for Generic<T>
    where Option<T>: Deserialize
{
    fn deserialize<D>(d: &mut D) -> Result<Generic<T>, D::Error>
        where D: Deserializer
    {
        struct __Visitor<D: Deserializer,
                         T: Deserialize>(PhantomData<D>, PhantomData<T>)
            where Option<T>: Deserialize;
        impl<D: Deserializer, T: Deserialize> Visitor for __Visitor<D, T>
            where Option<T>: Deserialize
        {
            type Value = Generic<T>;
            fn visit_seq<V>(&mut self,
                            mut visitor: V) -> Result<Generic<T>, V::Error>
                where V: SeqVisitor
            {
                let __field0 =
                    match try!(visitor.visit()) {
                        Some(value) => { value }
                        None => {
                            return Err(de::Error::end_of_stream());
                        }
                    };
                try!(visitor.end());
                Ok(Generic{v: __field0})
            }
        }
        const FIELDS: &'static [&'static str] = &["v"];
        d.deserialize_struct("Generic", FIELDS,
            __Visitor::<D, T>(PhantomData, PhantomData))
    }
}
```

which fails like this:

```
 expected `std::option::Option<_>`,
    found `T`
(expected enum `std::option::Option`,
    found type parameter) [E0308]
Ok(Generic{v: __field0,})
              ^~~~~~~~
```

I will keep digging but could use another pair of eyes. If I can't figure this out soon, I will start reverting serde_codegen commits.

**Comment by dtolnay** [comment]
So it works if `visitor.visit()` is changed to `visitor.visit::<Option<T>>()`, which is odd because that is exactly what should be inferred based on the code below it.

**Comment by dtolnay** [comment]
Narrowed further:

```rust
extern crate serde;
use serde::Deserialize;

struct Generic<T> {
    v: Option<T>
}

struct SeqVisitor;
impl SeqVisitor {
    fn visit<T>(&mut self) -> Result<Option<T>, ()> {
        panic!()
    }
}

fn visit_seq<T>() -> Generic<T> where Option<T>: Deserialize {
    Generic{v: SeqVisitor.visit().unwrap().unwrap()}
}
```

```
 expected `std::option::Option<_>`,
    found `T`
(expected enum `std::option::Option`,
    found type parameter) [E0308]
src/main.rs:17     Generic{v: SeqVisitor.visit().unwrap().unwrap()}
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by dtolnay** [comment]
A commenter on the [forum thread](https://users.rust-lang.org/t/type-inference-for-result-option-t-unwrap-unwrap/5709) suggests this may be a compiler bug. I think we have a workaround which I will try implementing tonight.

**Comment by dtolnay** [comment]
Using my PR #308 I was able to build the upgrade_serde_dependencies branch of rs-es.

**Comment by benashford** [comment]
Cool, thanks for this, there's good detective work there!
