### ISSUE TITLE
Specialize Serialize for [u8] and Deserialize for Vec<u8>

### ISSUE THREAD

**Issue by tikue** [serde-rs/serde#309]
Under the nightly feature flag, of course.

**Comment by tikue** [comment]
In [this benchmark](https://github.com/tikue/tarpc/blob/async/examples/throughput.rs), which is admittedly worst-case, using a local copy of serde and bincode that specialize `Vec<u8>` increases server throughput from 375 MB/s to 3000 MB/s.

**Comment by oli-obk** [comment]
> increases server throughput from 375 MB/s to 3000 MB/s.

Wheeee! I'm very excited about specialization, but we need to tread carefully so we don't end up massively cfg-ing our code.

**Comment by dtolnay** [comment]
Also Deserialize for `Box<[u8]>`.

**Comment by dtolnay** [comment]
I started implementing this and I ran into a problem where specialization affects type inference in an undesirable way (caught by a unit test luckily). Toy code:

```rust
#![feature(specialization)]

trait Serialize {
    fn serialize(&self);
}

impl Serialize for i32 {
    fn serialize(&self) {
        println!("{}", self);
    }
}

impl Serialize for u8 {
    fn serialize(&self) {
        println!("{}", self);
    }
}

impl<'a, T> Serialize for &'a T where T: Serialize {
    fn serialize(&self) {
        (**self).serialize();
    }
}

impl<T> Serialize for [T] where T: Serialize {
    default fn serialize(&self) {
        println!("serializing &[T]");
        for elem in self {
            elem.serialize();
        }
    }
}

impl Serialize for [u8] {
    fn serialize(&self) {
        println!("serialized &[u8]");
        for elem in self {
            elem.serialize();
        }
    }
}

fn main() {
    [1, 2, 300].serialize();
}
```

Without the impl for [u8], this prints "serializing &[T]" as expected and [1, 2, 300] is serialized. The type is inferred as T=i32.

With specialization this prints "serialized &[u8]" as expected, but also prints a warning and [1, 2, 44] is serialized.

```
warning: literal out of range for u8, #[warn(overflowing_literals)] on by default
  --> src/main.rs:44:12
   |
44 |     [1, 2, 300].serialize();
   |            ^^^
```

Unclear whether there is anything we can do about this or whether it will affect anybody in practice.

**Comment by dtolnay** [comment]
Oh we just need to specialize for every other integer type too... If I add an impl for `[i32]` then things work. That's annoying but at least there is a path forward.

**Comment by dtolnay** [comment]
This would be a backward compatibility risk so I am not going to try to push this in 1.0. But I am still interested in ways that we could support high performance [u8] / Vec\<u8\> better.
