### ISSUE TITLE
to rebase or not to rebase

### ISSUE THREAD

**Issue by oli-obk** [serde-rs/serde#318]
brought up by @dtolnay 

> some points in favor of merge commits:
> 1. A large part of the point of PRs is code review. As PRs change, GitHub keeps track of what part each reviewer has seen. Every rebase screws that up and forces reviewers to start from the beginning.
> 2. Many times a PR has already been reviewed fully but is not ready to merge for a variety of reasons. If there are only merge commits since the time that it was reviewed, it is probably okay to merge. On the other hand if there is a single rebased commit, you have no idea. Better review the whole thing again to make sure nothing important has changed.
> 3. The "Files changed" view is no different whether there are merge commits or not. It shows you the diff compared to the base branch. So if that is your workflow, it is not hindered by merge commits.
> 4. If we care about preserving a relatively simple commit history, PRs that include merge commits can be rebased and squashed right at the end, after the review is finished.

I find 1, 2 and 3 very convincing. ~~IIRC 4 can be done by bors (at least the squashing part)~~

**Comment by jwilm** [comment]
With regards to 1, I've had really good experiences using [https://reviewable.io/](reviewable.io) for code review in both open and closed source environments. Review history can only be advanced; rebases are just another change set. It has, in my experience, enabled more thorough of reviews. It's also free for open source. I think servo is using it too?

In a world where reviewable is used, 2. pretty much goes away with the exception that a rebase could introduce a few changes (but that's all you see).

My main argument against merge commits is a messier commit history, but it sounds like bors could fix that.

**Comment by oli-obk** [comment]
There was some discussion [here](https://github.com/barosl/homu/issues/58) about squashing with homu, but it died.

**Comment by oli-obk** [comment]
Adding 

```
# Rebase instead of merge, using the local git command
rebase = true

# Auto-squash commits while rebasing
autosquash = true
```

to the homu config will rebase + autosquash instead of adding a merge commit. "autosquash" means that all commits that don't change anything will be removed, since merge commits don't do anything after a rebase, this seems to be exactly what we'd want: a clean history and comfy reviewing

**Comment by indirect** [comment]
Not sure if anyone is still interested in this, but I needed squashing for my own use of Homu, so I added a `squash` option: https://github.com/bundler/homu/compare/3edacc0e7b2c920ebde12e6a6cfdbb5a5339e8dd...f0a5943d08a29dd475bebf0996d868174d3e2e60

**Comment by dtolnay** [comment]
Whatever we're doing seems to work well enough. I don't think we need to put more thought into this at the moment.
