### ISSUE TITLE
Handling uuid::Uuid

### ISSUE THREAD

**Issue by mann-ed** [serde-rs/serde#324]
I was trying to serialize a struct with uuid in it and received the following error.

```
src/Book/model.rs:3:45: 3:45 error: the trait bound `uuid::Uuid: Book::model::_IMPL_DESERIALIZE_FOR_Book::_serde::Deserialize` is not satisfied [E0277]
src/Book/model.rs:3 #[derive(Queryable, Serialize, Deserialize)]
                                                                ^
src/Book/model.rs:3:45: 3:45 note: in this expansion of try! (defined in <std macros>)
src/Book/model.rs:3:45: 3:45 note: in this expansion of #[derive_Deserialize] (defined in src/Book/model.rs)
src/Book/model.rs:3:45: 3:45 note: in this expansion of include!
src/Book/model.rs:3:45: 3:45 help: run `rustc --explain E0277` to see a detailed explanation
src/Book/model.rs:3:45: 3:45 error: the trait bound `uuid::Uuid: Book::model::_IMPL_DESERIALIZE_FOR_Book::_serde::Deserialize` is not satisfied [E0277]
src/Book/model.rs:3 #[derive(Queryable, Serialize, Deserialize)]
                                                                ^
```

Here is the struct

```
use uuid::Uuid;

#[derive(Queryable, Serialize, Deserialize)]
pub struct Book {
    pub book_id: Uuid,
    pub book_abbr: Option<String>,
    pub book_volume: Option<String>,
    pub book_name: String,
    pub book_altname: Option<String>,
}
```

Is there something that i am missing?

Thanks

**Comment by dtolnay** [comment]
You need to enable the [`serde` feature flag](https://github.com/rust-lang-nursery/uuid/blob/fcb9ec465c0a831979be1c501030e64690f1f545/Cargo.toml#L17) on the uuid crate in order for it to provide `Serialize` and `Deserialize` impls.

**Comment by nbro** [comment]
In case you're wondering, like I did, how to specify it, here's an example:

    uuid = { version = "0.7", features = ["v4", "serde"] }

**Comment by dbolduc** [comment]
If anyone stumbles on this thread in the future, the feature is now called `std`, not `serde`.

```toml
uuid = { version = "1", features = ["v4", "std"] }
```

**Comment by TownCube** [comment]
> If anyone stumbles on this thread in the future, the feature is now called std, not serde.

This is incorrect. Using these features alone results in ``error[E0277]: the trait bound `Uuid: Serialize` is not satisfied``

The [latest documentation](https://docs.rs/uuid/1.17.0/uuid/index.html#other-features) maintains the `serde` feature has not changed:

> serde - adds the ability to serialize and deserialize a UUID using serde.

**Comment by dbolduc** [comment]
> This is incorrect.

Yep, you are right, I was wrong. Sorry!
