### ISSUE TITLE
serde::de::Visitor's Value bound of Deserialize is restrictive

### ISSUE THREAD

**Issue by cmsd2** [serde-rs/serde#328]
I'm trying to serialize/deserialize url::Url which doesn't implement Serialize or Deserialize.
I've successfully added serialize_with and deserialize_with annotations.
To hook up the annotations as per the docs I've implemented appropriate functions for url::Url and a SerializeWith and DeserializeWith trait similar to the code in serde's tests.

I want to reuse this to work with Option&lt;url::Url&gt;.
I could create a specific impl for this new type. This works ok.

I tried though creating a generic impl for T where T: SerializeWith etc. This works for serialization.
The corresponding deserialization impl doesn't work because I have to use a visitor to deserialize the option, but the visitor trait requires that the produced result value is a subtype of serde::de::Deserialize.
Since I'm effectively working with a parallel type heirarchy I don't have this bound.

Is this something that can be changed?

code example (requires nightly. doesn't compile due to this issue):
https://github.com/cmsd2/serde-deserialize-with-example/blob/master/src/lib.rs

**Comment by oli-obk** [comment]
I think you could use a newtype around Url that implements `Deserialize`, and use that type and extract the `Url` from the newtype after deserialization.

**Comment by cmsd2** [comment]
I like the idea -- that would allow me to apply the serde annotations to the inner Url value without needing special handling for all the wrapper types.

I just tried it with a newtype struct:
pub struct SerializableUrl(#[serde(...)] Url)
but that doesn't seem to work: it complains about Url not satisfying a Deserialize bound.
is the field not getting filtered out by serde::de::deserialized_by_us?

using a full-fat struct with a url field does work though.

the other alternative was to use a type alias but i couldn't see where to put annotations there. I think i might be able to implement the serde traits manually in that case though...

**Comment by oli-obk** [comment]
I took the liberty of adding backticks to your code to get rid of the german flag in `:de:` ;)

> using a full-fat struct with a url field does work though.

I suggest to use that for now. I filed an issue about tuple structs: #330

**Comment by dtolnay** [comment]
PR #335 fixes `serialize_with` and `deserialize_with` attributes inside tuple structs/variants and newtype structs/variants so you will be able to use:

```rust
pub struct SerializableUrl(
    #[serde(serialize_with="ser_url", deserialize_with="de_url")]
    Url);
```

I am closing this ticket because that bug is tracked at #330. @cmsd2 please reopen if there is anything more you need from us on this.
