### ISSUE TITLE
Published crates include some junk files

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#331]
I guess these are sitting ignored in Erick's clone? @erickt you should make a fresh clone for publishing.

We can close this after confirming that the next release does not include these.

**Comment by dtolnay** [comment]
The serde_macros crate also includes a ton of junk:

```
bar.rs
bench-606762c8cf051d2b
foo
foo.d
foo.dSYM/
foo.ll
foo.rs
gen1.rs
gen1.rs.bk
gen1.rust
gen2.rs
```

**Comment by dtolnay** [comment]
And serde_json contains a file called "old" which looks like an old Cargo.lock.

**Comment by jmesmon** [comment]
cargo has a feature where you can limit the included files in a published package that might be useful here. Documentation is here http://doc.crates.io/manifest.html (search for `include =` or `exclude =`.

I've found just using `include =` and being explicit about what files go in the published packages works well for my crates.

**Comment by dtolnay** [comment]
Thanks Cody. I will look into using `include =` and explicitly listing the files we want.

**Comment by erickt** [comment]
Ugh I forgot that cargo did that. I've gotten a clean checkout, and will look into using `include =` to keep this from happening again.
