### ISSUE TITLE
Should Serialize::serialize be able to fail?

### ISSUE THREAD

**Issue by makoConstruct** [serde-rs/serde#332]
Deserializations can fail, because input data can often come from a wide range of sources and it can vary in a lot of ways. Serializations, on the other hand, almost always can't, at all, because internal structs have well known and well maintained invariant. I worry that this API will almost always just amount to an unexplained unwrap with no documented panic conditions.
What're the use cases for this? When should implementations be allowed to _sometimes_ fail to serialize according to runtime conditions? Is that really useful?

When I searched the issue history for previous discussions, I did seem to come across one single possible use case, apparently Paths can't always serialize straightforwardly if they aren't valid unicode, but it looks like the project responded to that by just escaping the Path in those cases (as you should) and again the Result wrapping is redundant and meaningless and the serialization cannot possibly fail.

So I guess my question is are there plans to change the signature from `serialize -> Result<T>` to `serialize -> T` come 1.0.0?

**Comment by oli-obk** [comment]
well, your serialization target may not accept any more bytes... Or it might be invalid to serialize floats to the target format...

**Comment by oli-obk** [comment]
it would be nice to capture all that in the type system, but there's a long way to go until the error messages become useful enough to start doing that kind of associated type magic

**Comment by makoConstruct** [comment]
Just out of curiosity, could you link me to any discussions of the problems with error reporting that would make this unergonomic? If not, any keywords so I can find it?

**Comment by sfackler** [comment]
Even if the serialization format can handle anything you give it, the serializer is going to be writing into something (e.g. `File` or `TcpStream`), and that operation can fail.

**Comment by lfairy** [comment]
In other words, it's not the serialization itself that can fail, but the process of writing the result that can fail? That makes sense -- the `std::fmt` traits make the same assumption.

**Comment by dtolnay** [comment]
`std::fmt` is a good analogy.
