### ISSUE TITLE
impl Serialize and Deserialize for std::time::Duration

### ISSUE THREAD

**Issue by tikue** [serde-rs/serde#339]

**Comment by dtolnay** [comment]
Do you have a particular format in mind for this?

**Comment by tikue** [comment]
I don't, but visiting the fields -- seconds and nanos -- seems like a reasonable option.

**Comment by dtolnay** [comment]
This is included in [Serde 0.8.1](https://github.com/serde-rs/serde/releases/tag/v0.8.1).

**Comment by vagola** [comment]
That not very friendly format when you use in configuration
