### ISSUE TITLE
Usage of de::Error::invalid_length(len: usize)

### ISSUE THREAD

**Issue by pyfisch** [serde-rs/serde#342]
Is Serde trait method [`de::Error::invalid_length(len: usize)`](https://serde-rs.github.io/serde/serde/de/trait.Error.html#method.invalid_length) supposed to be called with the number of elements found or the number of elements expected?

Suppose I try to deserialize a sequence that must contain at least one element but may contain many more. If the sequence is found to be empty should I emit `de::Error::invalid_length(0)` or should I use a custom error because the length is not fixed?

The documentation should be updated to be more precise here.

**Comment by oli-obk** [comment]
it's supposed to be the number of elements given.

> The documentation should be updated to be more precise here.

You're right. Note: PRs are very welcome ;)
