### ISSUE TITLE
README example does not deserialize using bincode

### ISSUE THREAD

**Issue by mikedilger** [serde-rs/serde#348]
The README example for deserializing point works fine with serde_json, but bincode calls visit_seq() which is not implemented in the example.

Also, it would be **great** to have more examples in the examples directory.  For instance, how to implement `Serialize`/`Deserialize` for a type in someone else's crate by using a tuple and returning the tuple-wrapped value from `visit_map()`, `visit_seq()`, etc.

**Comment by dtolnay** [comment]
I was not able to reproduce the bincode failure. The following code worked as expected for me. Can you confirm that this is still an issue?

```rust
#[derive(Serialize, Deserialize, Debug)]
struct Point {
    x: i32,
    y: i32,
}

fn main() {
    let point = Point { x: 1, y: 2 };
    let limit = bincode::SizeLimit::Infinite;

    let serialized = bincode::serde::serialize(&point, limit).unwrap();
    println!("{:?}", serialized);

    let deserialized: Point = bincode::serde::deserialize(&serialized).unwrap();
    println!("{:?}", deserialized);
}
```

> ```
[0, 0, 0, 1, 0, 0, 0, 2]
Point { x: 1, y: 2 }
```

**Comment by dtolnay** [comment]
> Also, it would be **great** to have more examples in the examples directory. For instance, how to implement `Serialize`/`Deserialize` for a type in someone else's crate by using a tuple and returning the tuple-wrapped value from `visit_map()`, `visit_seq()`, etc.

I filed #380 to follow up on this.

**Comment by mikedilger** [comment]
Yeah, seems to work.  I don't know how to reproduce what I ran into, most likely I was doing something wrong.
