### ISSUE TITLE
Derive Deserialize to Struct with Lifetime 

### ISSUE THREAD

**Issue by craftytrickster** [serde-rs/serde#359]
I have been using serde to deserialize json and it has been very easy to use and helpful.

However, I have a question regarding deserializing to a struct with a lifetime. Take the following for example:

```rust
#[derive(Deserialize)]
struct Person<'a> {
    first_name: &'a str,
    last_name: &'a str
}
```

When using owned Strings, it works fine, but if I try to compile the above, I get the following error message:

```
error: the trait bound `&'a str: _IMPL_DESERIALIZE_FOR_Person::_serde::Deserialize` is not satisfied [E0277]
src/main.rs:19 #[derive(Deserialize)]
```
As long as this struct does not outlive the original input string being deserialized, I do not see why having a str reference is problematic. 

Is there something I am doing wrong here, or is it not supported? If it is not supported, are there any plans in the future? Perhaps I can help.

**Comment by dtolnay** [comment]
This is not supported and there are currently no plans to support it.

How would it work in this case?

```json
{"first_name": "escaped\"quote"}
```

The struct needs to contain a reference to the string `escaped"quote`. There is no such string in the input for it to refer to.

**Comment by craftytrickster** [comment]
Let's say I have the following input:
`let input_string_slice = "{\"first_name\":\"escaped\\\" quote\"}";` 

In order to deserialize I make the following call:
`let person = serde_json::from_str(input_string_slice).unwrap();` 

Why can't the person's first_name field just be a &str that refers to `&input_string_slice[15..30]`? After all, we already know that input_string_slice exists, since it is used in the `from_str` call. Owned Strings (like in the following code) deserialize completely fine.
```rust
#[derive(Deserialize)]
struct Person {
    first_name: String
}
```

I assume that the first_name value is able to be turned into an owned String by copying the chars from that same 15..30 range with something like ``&input_string_slice[15..30].to_string()`. 

Since we already know that range, I would just like to make a slice reference for the below, to avoid needing to allocate new string objects:

```
#[derive(Deserialize)]
struct Person<'a> {
    first_name: &'a str
}
```

**Comment by dtolnay** [comment]
Because `&input_string_slice[15..30]` is this string:

```
escaped\" quote
```

And the correct deserialized string that the struct should contain after deserializing from JSON is this string:

```
escaped" quote
```

And those are different strings.

**Comment by dtolnay** [comment]
I filed #360 to improve the error message for this case.

**Comment by craftytrickster** [comment]
Thank you for the explanation.
