### ISSUE TITLE
Parallelize the Travis build

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#366]
There are so many build steps in [.travis.yml](https://github.com/serde-rs/serde/blob/58fa30200708cd1ccc91d2bbea0b620f69b5397b/.travis.yml#L18-L31), especially for nightly. The nightly build currently takes 20 minutes. Let's split these into multiple parallel builds and see if we can get <5 minutes.

**Comment by erickt** [comment]
Sounds great to me. It might be possible to add another matrix build that builds serde with nightly and syntex. That'd cut down on a bunch of compile time.

**Comment by dtolnay** [comment]
Unfortunately it looks like parallelizing further would not help much. I don't see it in the docs but it appears that this restriction is still in effect: https://twitter.com/travisci/status/424990533447327744

> @Stof70 yes, there’s a limit of 5 concurrent builds per owner, i.e. the org/user the repository belongs to

As of #372 we are already at 5 concurrent builds.

**Comment by dtolnay** [comment]
I implemented parallelization within each of the 5 builds but only managed to speed up by about a minute, so not worth pursuing right now. The commit is https://github.com/dtolnay/serde/commit/8c1f0250f278aee9bf42e4bb137b1310d757f752 in case it is useful later.

#377 removes some of the low-risk Travis builds and cuts it down from 26 minutes to 10 minutes. I think that is the best we can do right now.
