### ISSUE TITLE
implement Serialize + Deserialize for HashMap with custom hash functions

### ISSUE THREAD

**Issue by neon64** [serde-rs/serde#369]
As far as I am aware the implementation of HashMap serialization/deserialization is only for SipHasher. 

```
impl<K, V> Serialize for HashMap<K, V>
    where K: Serialize + Eq + Hash,
          V: Serialize,
```

Is it feasible or desired to implement it for all hashers? (eg: `impl<K, V, S> Serialize for HashMap<K, V, S>`)

My specific use case is to serialize/deserialize a HashMap using https://github.com/servo/rust-fnv

**Comment by erickt** [comment]
Custom hashers were added in Rust 1.7, and since serde is currently tracking the last 3 releases it seems like we could add support for this now. @dtolnay / @oli-obk: what do you two think?

**Comment by dtolnay** [comment]
Let's do it.

**Comment by dtolnay** [comment]
I added the following impls in #371:

```rust
impl<K, V, S> Serialize for HashMap<K, V, S>
    where K: Serialize + Eq + Hash,
          V: Serialize,
          S: BuildHasher,

impl<K, V, S> Deserialize for HashMap<K, V, S>
    where K: Deserialize + Eq + Hash,
          V: Deserialize,
          S: BuildHasher + Default,
```

As well as unit tests that use rust-fnv.

**Comment by dtolnay** [comment]
I added HashSet too:

```rust
impl<T, S> Serialize for HashSet<T, S>
    where T: Serialize + Eq + Hash,
          S: BuildHasher,

impl<T, S> Deserialize for HashSet<T, S>
    where T: Deserialize + Eq + Hash,
          S: BuildHasher + Default,
```

**Comment by neon64** [comment]
Awesome thanks very much @dtolnay for your help
