### ISSUE TITLE
Release 0.8.0 to stop public dependency on syntex

### ISSUE THREAD

**Issue by erickt** [serde-rs/serde#374]
After we get the soon-to-be-released 0.7.10 out, how about we do a 0.8.0 release that also breaks `serde_codegen`'s dependency on syntex, since that's caused a lot of havoc for people, as seen in #358?

Is it worthwhile trying to get the other [v0.8.0](https://github.com/serde-rs/serde/milestones/v0.8.0) milestone tasks done?

This also could be done by just incrementing `serde_codegen`'s version. If we do that, we should consider whether or not we should just pull `serde_codegen` and `serde_macros` into a separate repository, since the two aren't updated at the same time *that* often.

**Comment by dtolnay** [comment]
I think 0.8.0 can wait. People can already use `expand` in 0.7.9 to avoid being broken by Syntex - the `register` function doesn't break them if they don't use it.

The only other actionable issue scheduled for 0.8.0 (#267) does not seem urgent now that Cargo has a workaround.

**Comment by dtolnay** [comment]
I filed #376 regarding your idea to version `serde_codegen` and `serde_macros` independently from `serde`.

**Comment by dtolnay** [comment]
I am closing this issue now that we have the ball rolling on an 0.8.0 release. The Syntex dependency is removed in #445.
