### ISSUE TITLE
Stop breaking public dependencies on patch versions.

### ISSUE THREAD

**Issue by Aaronepower** [serde-rs/serde#379]
Twice in the past 30 days there has been a `serde` patch update, which updates the minor versions of **some** of it's dependencies. Namely `syntex`, this causes dependent crates to not be able to compile due to cargo getting the updated version of `syntex`, and the old version of `syntex`. This is in violation of semver. There tools like [`crusader`](https://github.com/brson/cargo-crusader) for checking if the update is actually a breaking change.

**Comment by dtolnay** [comment]
Check out [this forum thread](https://users.rust-lang.org/t/here-is-how-to-avoid-being-broken-by-syntex-updates/6189) and update your build.rs accordingly so that these are no longer breaking changes. Let us know if you can think of a better way of messaging this solution to users.

**Comment by Aaronepower** [comment]
@dtolnay You have to make it a 0.x change, not a 0.7.x change in the future. It is a breaking change, even if every other package update so this isn't a problem, there will still be packages that depend on older versions using the old `build.rs` style.

**Comment by dtolnay** [comment]
By our judgment, moving to 0.8.0 now for the sole reason of removing `serde_codegen::register` will cause more breakage than informing people about `serde_codegen::expand` and continuing to release patches.

The current `serde_codegen::register` is deprecated (we can't use `#[deprecated]` because we support old compilers that don't have it). It will be removed in 0.8.0. If you use `serde_codegen::expand` these are not breaking changes.

**Comment by Aaronepower** [comment]
@dtolnay How it cause more breakage, than the current process which breaks all stable packages on release without authors even realising it? People won't accidentally download 0.8.0 in their dependencies, people will continue to receive breaking patches on every patch version you do.

**Comment by mrhota** [comment]
Isn't 0.X.Y "for initial development."? The semver spec continues: "Anything may change at any time. The public API should not be considered stable."

**Comment by Aaronepower** [comment]
@mrhota Yes, but in use this mostly means breaking changes are on `0.Y.0`. And cargo follows semver, and cargo will automatically download patch version of `0.Y.Z` applications. If the library is supposed to be completely unstable at every iteration, then it shouldn't be on [crates.io](https://crates.io), and you should just link directly to the git repository.

**Comment by dtolnay** [comment]
Fixed in #445.
