### ISSUE TITLE
Give dtolnay reviewer permission in Homu

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#388]
I get ignored: #383, #387.

**Comment by oli-obk** [comment]
https://github.com/serde-rs/serde/pull/377#issuecomment-226150667 same here

**Comment by dtolnay** [comment]
But this one https://github.com/serde-rs/serde/pull/378#issuecomment-225622763 worked for Oliver. I have never had one work.

Are there logs from Homu that would help debug this?

**Comment by erickt** [comment]
Unfortunately homu.io is currently semi-working. The service works but last I checked it's impossible to add new projects or modify settings. I have an outstanding offer for the rust community team to [take the project over](https://github.com/barosl/homu/issues/151) but there have been no replies yet :(

**Comment by dtolnay** [comment]
Seems like this isn't possible right now. I subscribed to https://github.com/barosl/homu/issues/151 and we will see what happens.
