### ISSUE TITLE
All users should activate 2FA

### ISSUE THREAD

**Issue by erickt** [serde-rs/serde#390]
due to the recent attack on Github, I want to require that all developers enable 2 factor authentication to the serde repos. @nox / @hugoduncan / @SimonSapin, I've temporarily disabled your write access. Please let me know once you get it on and I'll give you write access again.

**Comment by oli-obk** [comment]
![](http://imgs.xkcd.com/comics/password_reuse.png )

**Comment by dtolnay** [comment]
:+1: I've been using it since the feature was added.
