### ISSUE TITLE
Issue Deriving Deserialize

### ISSUE THREAD

**Issue by mmstick** [serde-rs/serde#393]
I have imported both `serde::Deserialize` and `serde_json::de`, and I have `#![feature(custom_derive)]` and `#![feature(custom_attribute)]` defined at the crate level, but I am unable to use `#[derive(Deserialize)]` on a struct that I have created. It simply errors that the trait bound, `serde::Deserialize` is not satisfied. Anyone else having this problem?

**Comment by dtolnay** [comment]
Can you share the code to help debug?

I have seen this before when there are multiple Serde versions involved. You may be using a version of serde_json that uses a different version of serde than your crate - so you are deriving a Deserialize impl corresponding to one version of Serde but serde_json is expecting a Deserialize impl corresponding to a different version of Serde, which is not satisfied. Check your Cargo.lock.

**Comment by mmstick** [comment]
What versions should be paired? This is a just-initialised project so I'm using the latest of the two available on Crates.io, which is version 0.7.10 of serde and version 0.7.1 of serde_json..

**Comment by dtolnay** [comment]
Those should work. I cannot reproduce the issue using those versions.

As a sanity check you could try using [`cargo expand`](https://github.com/dtolnay/cargo-expand) to confirm that a Deserialize impl is being generated.

**Comment by mmstick** [comment]
It doesn't seem to be expanding. Repository here: https://github.com/mmstick/rustcyp

**Comment by dtolnay** [comment]
You're missing:

```rust
#![feature(plugin)]
#![plugin(serde_macros)]
```

**Comment by mmstick** [comment]
I have it working now.
