### ISSUE TITLE
Public Codegen API

### ISSUE THREAD

**Issue by KodrAus** [serde-rs/serde#396]
I have a scneario where I want to be able to know what `serde` will do with a struct field, but there isn't a public API for querying `serde_codegen`. Whether or not it's even a good idea to produce one is a good question, my scenario may be an edge-case that isn't really worth supporting.

I have some serialisation codegen that I want to be 'compatible' with `serde` attributes (so if a user serialises their struct field as `renamed`, I want to know so I can serialise my generated field as `renamed` too.) Currently, I just do some basic checks on `serde` attributes, but don't mark them as used. This is crummy because it doesn't cater for more complex renaming, and could fall out of step with `serde` itself.

The easiest way to make this work would be to just make `serde_codegen::attr` public, so a caller could access the exact same metadata as `serde` itself.

**Comment by dtolnay** [comment]
I don't like the backward-compatibility implications of "just making `serde_codegen::attr` public." Adding a new attribute would become a breaking change even though serde_codegen users don't care. We struggle enough with maintaining backward compatibility with the existing public API.

I would be open to separating `serde_codegen::attr` (or the new `serde_codegen::item`) into an independently versioned `serde_attr` crate, with the understanding that it makes breaking changes more frequently than either serde or serde_codegen. Would that still be useful to you?

**Comment by KodrAus** [comment]
Yeh, I don't see it as a _standard_ usecase so understand it's introducing more surface area to break without much gain. Splitting it into a separate crate sounds good to me, because then I'm explicitly opting-in to that backend library with the understanding that I'm downstream so have to take changes as they come.

I can also get by if it's something that simply isn't on `serde`'s radar if it's not going to be useful to many people.
