### ISSUE TITLE
Rename serde_item

### ISSUE THREAD

**Issue by erickt** [serde-rs/serde#399]
I'm not sure if the name serde_item is really capturing that crate's functionality, so I'd like us to consider some other names. Off the top of my head could be `serde_codegen_ast`, or even `serde_ast`. @dtolnay  / @oli-obk, do either of you have a better suggestion?

**Comment by dtolnay** [comment]
`serde_internal::ast`?

**Comment by dtolnay** [comment]
Let's yank the old one when we make the change.

**Comment by erickt** [comment]
Ah I didn't see a tag, so I didn't realize it was already published. Do you mean `serde_internal_ast`?

**Comment by oli-obk** [comment]
I like the idea of a general serde_internals that can frequently make major version bumps. Putting the current content of serde_item in a submodule can wait until we put more stuff there imo.
