### ISSUE TITLE
Publish serde_codegen 0.7.11

### ISSUE THREAD

**Issue by KodrAus** [serde-rs/serde#410]
Hey guys, is there anything still blocked on publishing `serde_codegen 0.7.11` to `crates.io`?

**Comment by 0nkery** [comment]
PR #406 still fails to build. I think it's the thing we are waiting for.

**Comment by dtolnay** [comment]
We don't need to wait for that. I will publish right now. I don't know why @erickt didn't publish after merging #405.

**Comment by sinhpham** [comment]
+1, I'm also waiting for this, serde_codegen is not building due to aster 0.18 having some incompatibilities with the latest nightly.

**Comment by dashed** [comment]
Heh. I was using this as workaround in my `Cargo.toml`

```
[dependencies.serde_macros]
git = "https://github.com/serde-rs/serde"
rev = "5941f1d071157923203a278c16fbaddec4077932"
```

**Comment by 0nkery** [comment]
Thanks for release.

**Comment by dtolnay** [comment]
There it is. Release notes will be up in a few minutes.

**Comment by dtolnay** [comment]
Hopefully #406 will be the end of serde_macros being broken on nightly all the time.
