### ISSUE TITLE
Document that visit_string should never be implemented without visit_str

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#424]
The default implementation of `visit_string` delegates to `visit_str`. Some formats use one or the other (JSON currently uses `visit_str`, bincode uses `visit_string`). You want neither, both, or just `visit_str`, never just `visit_string`.

**Comment by oli-obk** [comment]
I can do you one better, I can implement a clippy lint, so anyone using clippy and serde will trigger a lint that mentions this issue.

**Comment by oli-obk** [comment]
clippy lint has been implemented: https://github.com/Manishearth/rust-clippy/pull/1093

**Comment by dtolnay** [comment]
https://docs.serde.rs/serde/de/trait.Visitor.html#method.visit_string

> It is never correct to implement `visit_string` without implementing `visit_str`. Implement neither, both, or just `visit_str`.
