### ISSUE TITLE
Consider using rustfmt

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#438]

**Comment by dtolnay** [comment]
Overall I am very happy with the formatting in #439. There are a few bugs to iron out and maybe we need to develop new idioms around chained aster builders but I think rustfmt will be a net benefit.

**Comment by oli-obk** [comment]
Should we add a rustfmt target to travis? Doesn't need to fail the build, but just so we know the state of things?

**Comment by oli-obk** [comment]
note that we fail the build in clippy if rustfmt fails, but there have been some voice speaking against that.

**Comment by dtolnay** [comment]
I don't think that would be valuable. The tradeoff is scaring away new contributors. If someone makes a PR, I would prefer that they remember it as a reasonable discussion about meaningful things, rather than as a struggle to satisfy a grumpy buildbot. Even if the overall build is green, seeing a red task can be anxiety-inducing and uncertain about whether you are responsible for fixing it. Instead, if the code looks mostly fine then I won't notice or care anyway, and somebody will run rustfmt every month or so and it takes 10 seconds to clean everything up so there isn't really anything to gain from enforcing it.

**Comment by oli-obk** [comment]
Sounds sensible!
