### ISSUE TITLE
Current Quasi version used in serde_macros is broken on latest nightly(1.12.0-nightly (7ad125c4e 2016-07-11))

### ISSUE THREAD

**Issue by TheDoctorsLife** [serde-rs/serde#440]
WTTS

**Comment by dtolnay** [comment]
I cannot reproduce this. Please paste the error. Maybe you need to run `cargo update` in serde_macros.

**Comment by TheDoctorsLife** [comment]
Yep, sorry for taking your time for such a simple error.
