### ISSUE TITLE
partially successful deserialization

### ISSUE THREAD

**Issue by oli-obk** [serde-rs/serde#464]
inspired by https://users.rust-lang.org/t/solved-serde-deserialization-on-error-use-default-values/6681

We might want to evaluate ways to ensure that certain deserialization issues can be caught and enable `Deserializer`s to clean up in case more stuff is going to get deserialized.

Expanding on the example in the above link:

``` rust
#[derive(Deserialize, Clone, Debug)]
pub struct ParentObject {
    unique_id: String,
    super_complicated_object: MegaAwesomeObject,
    more_stuff: String,
}
```

The proposed solution

``` rust
#[derive(Deserialize, Clone, Debug)]
pub struct ParentObject {
    unique_id: String,
    #[serde(deserialize_with="ok_or_default")]
    super_complicated_object:  MegaAwesomeObject,
    more_stuff: String,
}

fn ok_or_default<T, D>(deserializer: &mut D) -> Result<T, D::Error>
    where T: serde::Deserialize + Default,
          D: serde::Deserializer
{
    Ok(serde::Deserialize::deserialize(deserializer)
        .unwrap_or_else(|_| Default::default()))
}
```

suffers from the obvious disadvantage, that the deserializer is left in an undefined state, so it might not be able to deserialize the further fields (or even do random weird stuff).

There are basically two classes of errors, syntactical errors in the format, which are mostly unrecoverable (related json issue: https://github.com/serde-rs/json/issues/70), and deserialization errors like wrong types, missing field, unknown field, too long sequences, ... which can "easily" be recovered from, by using the format's syntax to move back up to the last successful level and then report the error. This could be used to implement `Deserialize` for some `Result`-like type, which is `Ok(T)` when successful and `Err(SomeSerdeError)` when not successful.

**Comment by dtolnay** [comment]
Maybe this would be better served by deserializing to `serde_json::Value` first and then using `from_value`. That way you can distinguish between unrecoverable syntax errors and recoverable type errors, and the deserializer is left in a consistent state to continue deserializing.

**Comment by dtolnay** [comment]
```rust
fn ok_or_default<T, D>(deserializer: &mut D) -> Result<T, D::Error>
    where T: serde::Deserialize + Default,
          D: serde::Deserializer
{
    let value = try!(serde::Deserialize::deserialize(deserializer));
    Ok(serde_json::from_value(value).unwrap_or_else(|_| Default::default()))
}
```

**Comment by oli-obk** [comment]
> Maybe this would be better served by deserializing to serde_json::Value first and then using from_value. That way you can distinguish between unrecoverable syntax errors and recoverable type errors, and the deserializer is left in a consistent state to continue deserializing.

that would definitely be a better choice for json-only, but I'm wondering if we can get this done in a format independent way in serde, so the format can decide whether to error out hard or softly

**Comment by TedDriggs** [comment]
@oli-obk I've been working on support in [colin-kiegel/rust-derive-builder](https://github.com/colin-kiegel/rust-derive-builder) for deriving traits on the generated builder objects. You could probably do something with that where you deserialize into the builder, and missing or invalid fields end up as `None`.

**Comment by dtolnay** [comment]
I would love to see this explored in a different library specifically geared toward fault-tolerant partially successful deserialization. I think a binary success/failure will continue to be appropriate for Serde.
