### ISSUE TITLE
Serializer methods with `T: Serialize` arguments would make more sense as `&T`

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#467]
From @sfackler in IRC:

> the signatures of methods implies things about how they're expected to be used. If a method takes something by value, I'm going to assume it needs ownership of the value, and I can only find that the "normal" intent is to pass by reference if I find that forwarding implementation buried in the pile of 100 or however many there are in rustdoc

(the forwarding implementation is `impl<'a, T: ?Sized> Serialize for &'a T where T: Serialize`)

**Comment by dtolnay** [comment]
This was the response in IRC:

> **\<erickt\>** It possibly takes things by value because it'll let you potentially serialize some value without a copy
> **\<sfackler\>** ah that makes sense

@erickt do you have an example of this? Serialize::serialize is defined on &self so I'm not sure where it would avoid a copy.

**Comment by dtolnay** [comment]
The same question applies to `serde_json::to_*`, for example [`to_writer`](https://docs.serde.rs/serde_json/ser/fn.to_writer.html). Those currently take &T which is inconsistent with the Serializer methods taking T.

**Comment by oli-obk** [comment]
It would only make sense for serializing to `json::Value` or similar types. It's probably not worth the effort, but strictly more powerful for the future. My slight preference is thus to move everything to by val.

**Comment by oli-obk** [comment]
I have tried to implement #571 with a wrapper type, but it's not possible without some `RefCell<Option<T>>` dance, because to iterate over an iterator, you need mutable access to the iterator. If we moved `Serialize::serialize` to take `self` by value and suggest that users implement it for `&'a TheirType` then we could do it without any `RefCell` code.

I'll try other workarounds, maybe this is unnecessary, it seems inelegant to me.

**Comment by oli-obk** [comment]
The backend has moved to by value. So now this is mainly a question of how the helper functions of specific serializers expose it.

**Comment by dtolnay** [comment]
We still need to evaluate these methods:

- `Serializer::serialize_newtype_struct`
- `Serializer::serialize_newtype_variant`
- `Serializer::serialize_some`
- `SerializeSeq::serialize_element`
- `SerializeTuple::serialize_element`
- `SerializeTupleStruct::serialize_field`
- `SerializeTupleVariant::serialize_field`
- `SerializeMap::serialize_key`
- `SerializeMap::serialize_value`
- `SerializeStruct::serialize_field`
- `SerializeStructVariant::serialize_field`

All of those currently take T by value which is inconsistent with Serialize taking Self by reference. I think I am still in favor of updating it all to be &T.

**Comment by dtolnay** [comment]
Gah, neither solution is obviously better. I don't think we should spend more time on this. The current approach is decent and consistent enough.

**Comment by oli-obk** [comment]
If we are not moving to changing `Serialize::serialize` to take the argument by value, we should move all functions to by ref and remove the impl for references.

The only advantage of moving to values is wrapper helpers not requiring any runtime checks.

**Comment by dtolnay** [comment]
I am okay with that but I don't see the reason to remove the impl Serialize for &'a T (if that's what you mean). I opened https://github.com/serde-rs/serde/pull/716 and https://github.com/serde-rs/json/pull/210 to make the change.
