### ISSUE TITLE
XML Support

### ISSUE THREAD

**Issue by mattnenterprise** [serde-rs/serde#48]
Will this library ever support XML?

**Comment by erickt** [comment]
See @oli-obk's awesome PR #39 :)

**Comment by oli-obk** [comment]
@mattnenterprise please give me uses cases! so I can figure out how to implement stuff. like some xml you have and what rust-structure you expect from it and vice versa.

**Comment by dtolnay** [comment]
The serde_xml crate is now linked from the readme, so I think this issue can be closed. Further XML-related issues can be filed against that project.
