### ISSUE TITLE
Serde logo

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#481]
The GitHub autogenerated one is among the lamest I've seen.

<img src="https://cloud.githubusercontent.com/assets/1940490/26278983/e844e3f8-3d5c-11e7-869a-f0f35a85eda3.png" width=460>

**Comment by oli-obk** [comment]
Maybe something like the poster combo?

![](http://imgs.xkcd.com/comics/dorm_poster.png)

**Comment by erickt** [comment]
@dtolnay: wow, that's hillarious.

@oli-obk: I like the direction! I wonder what we could to do make it not look like the Pink Floyd poster. I thought about [gravitational lensing](https://upload.wikimedia.org/wikipedia/commons/1/11/A_Horseshoe_Einstein_Ring_from_Hubble.JPG) but that's probably too far out there. Something from [this app](http://www.atoptics.co.uk/fz747.htm) might work.

Another option might be some play on [aqua regia](https://www.google.com/search?biw=1795&bih=831&tbm=isch&q=aqua+regia&spell=1&sa=X&ved=0ahUKEwi14MOEnLLOAhUW3mMKHdgyANsQBQgbKAA#imgrc=xbhhsJHFcuNGLM%3A), based off of [Bohr dissolving some gold Nobel Prizes to hide them from Nazis, and then reconstituted them after the war](http://www.npr.org/sections/krulwich/2011/10/03/140815154/dissolve-my-nobel-prize-fast-a-true-story).

**Comment by oli-obk** [comment]
that's a pretty cool app

**Comment by killercup** [comment]
How about a simple icon like [this](https://thenounproject.com/search/?q=prism&i=362080)? Or, you know one of [these](https://thenounproject.com/search/collection/?q=alchemy). Maybe [this one](https://thenounproject.com/adeoh/collection/alchemy/?oq=alchemy&cidx=1&i=210038).

**Comment by Paluth** [comment]
![serde](https://cloud.githubusercontent.com/assets/18539987/25249191/689dcce6-25e7-11e7-9fa7-dc601afb1011.png)
I made an icon, just a sketch right now, but the idea is there. What do you guys think?

**Comment by bstrie** [comment]
@Paluth That's not how sprockets work! :)

EDIT: Oh wait those actually are gears... to which I say *heresy*. :P

**Comment by Paluth** [comment]
we can churn the gears a little with each major release! :)

**Comment by Diggsey** [comment]
![serde](https://cloud.githubusercontent.com/assets/451321/25259040/764bfa1c-263b-11e7-8498-8c41c32f9d12.png)

Was trying to do a dissolving effect, but couldn't get it to look right 🙁 oh well!

**Comment by clarcharr** [comment]
What about a picture of the rust gear printed on a piece of paper?

**Comment by fspmarshall** [comment]
![serde_logo](https://cloud.githubusercontent.com/assets/16642166/25275787/b8e1df58-2632-11e7-8ab5-d4cc8ffdcc60.png)

Started off trying to turn the rust gear into a sun... kinda ended up with a yin/yang thing at some point... eh :/

**Comment by tapeinosyne** [comment]
I appreciate that the cogwheel is a recognizable element of Rust's logo, but I find it to be a rather hackneyed symbol in OSS. It would be nice to try something different, e.g. a cheap geometric bauble:

![serde logo sketch](https://cloud.githubusercontent.com/assets/3063022/25295734/bb01ec06-26dc-11e7-8755-8f7dfac69b35.png)

**Comment by dtolnay** [comment]
@tapeinosyne I agree with you and I love your design. Would you or anyone else be willing to put some more time into this? I think we can make something work.

Things I like:

- Subtle emphasis on the two halves of the word ser and de. Different colors for ser vs de or anything similarly in-your-face would be too much. What you have is brilliant.
- Square is great for the icon of the github org.

Things that would really sell it:

- A variation / minimalization that works in 44x44 pixels - the size of the icon left of this comment.
- Some idea of how this would fit into the context of a readme or website - whether in square form or a banner-shaped variation. Designing a website is a whole separate thing but if we have a logo it might as well be usable on the current one.

**Comment by tapeinosyne** [comment]
I'd be happy to hear from others in this thread and refine the design. A benefit of these baubles is that they can be crammed through cookie-cutter steps to extrude variations; it's easy to iterate on them.

So, here are the basic elements of this particular bauble:

- a technical font in a single color,
- one solid color or mostly homogeneous pattern,
- one simple pattern that works nicely with the other,
- use of vertical alignment to visually separate the prefix “ser” from the suffix “de”.

It only takes a few minutes to sketch an alternative design based on these steps. I used [Input Serif](http://input.fontbureau.com/) Compressed in medium weight, a palette based on the Solarized color scheme, and a simple pattern of pips. Now, tasked with adapting the bauble to a different form factor, I can renounce any sophistication and nevertheless obtain tolerable results:

![pips_extended](https://cloud.githubusercontent.com/assets/3063022/25315274/b0089934-284a-11e7-9336-a66f378b90ff.png)

It is similarly easy to experiment with different patterns:

![rhombus](https://cloud.githubusercontent.com/assets/3063022/25315251/4b6a2858-284a-11e7-9cdb-ec066dfa0111.png)

Less so with minimization, which can seldom be done without some tedious pixel-wrangling. (At least, not with Affinity Designer; it could be that Illustrator offers better rasterization.)

![pips_small](https://cloud.githubusercontent.com/assets/3063022/25315982/21e32334-2856-11e7-9826-c0984ce51018.png)

If we identify a variation we like well enough, it won't take long to refine the design (ensure alignment, adjust spacing, and so on). Meanwhile, we can experiment without much effort.

**Comment by arnabanimesh** [comment]
`serde` is basically a communication medium between two systems who needs a common language.

Ideal representation should be where where `ser` is converting system data (maybe machine code) and sending messages; and `de` is receiving messages and converting them back into machine code in a different machine.

Machine code can be represented by mechanical stuff and messages can be represented by communication stuff too.

**Comment by ssokolow** [comment]
What about a more polished version of this five-minute prototype?

![serde_logo_proposal](https://user-images.githubusercontent.com/46915/197350364-e2ed72cb-1ff4-4363-839f-7f27d2a8916b.png)
