### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by maximih** [serde-rs/serde#483]
I noticed serde 0.8 was released but cannot find any release notes or blog post about it so it's not easy to find out which new features are included and if there is any breaking change.

I suggest serde devs add a doc with list of new features and breaking changes to make it easier for the users to find this info and so make it easier for the user to always use latest serde release.

Thanks

**Comment by dtolnay** [comment]
As always, the release notes are on the [releases page](https://github.com/serde-rs/serde/releases/tag/v0.8.0). Same for [serde_json](https://github.com/serde-rs/json/releases/tag/v0.8.0). The release was announced on [/r/rust](https://www.reddit.com/r/rust/comments/4v4m23/serde_and_serde_json_08_many_simplifications_bug/) with a link to the release notes. Let us know if you think of a way we could have done it better.

**Comment by maximih** [comment]
I was not aware of the releases page. Sorry for wasting your time.

**Comment by erickt** [comment]
@maximih: no worries, we've changed traditions a little with more developers coming online.

@dtolnay: think it'd be worthwhile starting a proper serde development blog? Talking about the json benchmarking could be nice, and if we want to talk through our thought process developing some feature.
