### ISSUE TITLE
Serde layering issue.

### ISSUE THREAD

**Issue by crlf0710** [serde-rs/serde#484]
Maybe i'm wrong, but it occurs to me that there's some layering issues in `serde`.

There are things that each serializer and visitor recognizes, which belong to a finite set represented by the trait interface.
There are user-defined things that implements serialize and deserialize, which is taken cared of by user application.

This takes the view that every value is either **primitive** (implemented by the serializer/deserializer) or **aggregate** (decoupled by user into several values).

However, think that i have a very special **primitive**. A serializer/deserializer may want to support it if this format has support for it, otherwise it may fall back into decomposed form of less accurate primitive values. (say serialize to a str?)

Currently there's no way to support this. I can't modify serde ser/de code just to support a special case. And if i implement serialize/deserialize for specific format, that's bringing special case to generic also, which is not desirable.

What do you think about this? I think if things like this is not corrected, issues just like #186 and #194 will continuously extend and finally bring `Serializer` and `Visitor` to an awful appearance.

**Comment by oli-obk** [comment]
We're working on this issue in #455 

Basically the intent is that if your type doesn't fit into the predefined system, you specialize the ´Serialize´ impl for ´Serializer´s that can actually treat the type specially. You still need to provide a fallback for all other ´Serializer´s that just offer the regular interface.

**Comment by crlf0710** [comment]
@oli-obk  
ok, glad to see that this is being worked on. I'm seeing through the changes, though not finished it yet. 

I think it is the chance of the Serializer who is able to use a more optimized or compact or even legal data format to serialize. I haven't give the nightly feature specialization a try yet, and i wonder if that person, who neither own Serialize(serde did) nor the type (the type crate author did) can actually specialize that :(

Besides that, some data formats that use special marks to turn circular data structure into uncircular one for serialization have to track state inside the serializer in some way, i'm afraid. The type crate author doesn't have the ability to ask the serializer to do these book keeping.

Is it a good idea to add a `serialize_any` or `serialize_specialize` on the serializer so it can use any::TypeId to specialize somehow ?

**Comment by oli-obk** [comment]
>  who neither own Serialize(serde did) nor the type (the type crate author did) can actually specialize that :(

that's where you'd use a newtype wrapper.

But the owner of the `Serializer` should be able to do it. We'll see how specialization turns out

> Is it a good idea to add a serialize_any or serialize_specialize on the serializer so it can use any::TypeId to specialize somehow ?

interesting idea... Maybe we could add a bound to `serialize`
