### ISSUE TITLE
Container attribute to deserialize C-like enum using FromStr

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#493]
In an situation like this, the mapping from string to enum variant is duplicated across the `rename` attributes and the FromStr impl. It can be deduplicated by having FromStr forward to serde deserialize i.e. implement FromStr as `serde_json::from_str("\"" + s + "\"").map_err(...)`. It would be nicer if serde deserialize could be implemented in terms of FromStr instead.

``` rust
#[derive(Deserialize)]
pub enum EventAction {
    #[serde(rename="assigned")]
    Assigned,
    #[serde(rename="unassigned")]
    Unassigned,
    #[serde(rename="labeled")]
    Labeled,
    #[serde(rename="unlabeled")]
    Unlabeled,
}

impl FromStr for EventAction {
    /* ... */
}
```

cc @jaredwy

**Comment by tomprince** [comment]
It sounds like you are suggesting that for C-like enums, `#[derive(Deserialize)] ` will generate a `FromStr` implementation, and then a `Deserialize` will be generated based on that? That is something I would be interested in having; at least the part about having a `FromStr` implementation that matches the serde deserialization.

As an aside, you can implement `FromStr` with `from_value(Value::String(s))`

**Comment by dtolnay** [comment]
This has been implemented in the serde_plain crate.

- [Implement Deserialize in terms of FromStr](https://docs.rs/serde_plain/0.3.0/serde_plain/macro.derive_deserialize_from_str.html)
- [Implement FromStr in terms of Deserialize](https://docs.rs/serde_plain/0.3.0/serde_plain/macro.forward_from_str_to_serde.html)
