### ISSUE TITLE
Container attribute to serialize C-like enum as number

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#497]
Something like:

``` rust
#[derive(Serialize, Deserialize)]
#[serde(as_u8)]
enum SmallPrime {
    Two = 2,
    Three = 3,
    Five = 5,
    Seven = 7,
}
```

**Comment by alexreg** [comment]
Yep, this would be perfect. We would want `as_*` meta-items for all the primitive integral types I guess.

**Comment by dtolnay** [comment]
Yep, including `as_str`.

**Comment by alexreg** [comment]
What would that do?

**Comment by dtolnay** [comment]
It calls `serialize_str` instead of `serialize_unit_variant`.

```rust
#[derive(Serialize, Deserialize)]
#[serde(as_str)]
enum E {
    // calls serialize_str("A")
    A,
    // calls serialize_str("b")
    #[serde(rename = "b")]
    B,
}
```

**Comment by alexreg** [comment]
Oh, I see. This won’t make a difference for some serializers I guess (e.g. serde-json), but will affect others?

**Comment by dtolnay** [comment]
[Correct](https://github.com/serde-rs/json/blob/ccb6e44a6dda9fd2bf21361560ab97962478cfc5/json/src/ser.rs#L181-L189).

**Comment by oli-obk** [comment]
@RReverser notes that it would be nice to serialize as string on human readable formats and enum discriminant in all other formats.

**Comment by dtolnay** [comment]
Closing because I would prefer to see this provided by derive macro in a separate crate specific to this use case. Something like:

```rust
#[derive(SerializeRepr, DeserializeRepr)]
#[repr(u16)]
enum SmallPrime {
    Two = 2,
    Three = 3,
    Five = 5,
    Seven = 7,
}
```

which emits the appropriate Serialize and Deserialize impl.

**Comment by alexreg** [comment]
Super, thanks.
