### ISSUE TITLE
Useless attribute: #[allow(unused_imports)]

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#500]
I see hundreds of these in the Travis output.

```
warning: useless lint attribute, #[warn(useless_attribute)] on by default
    --> /home/travis/build/serde-rs/serde/testing/target/debug/build/serde_codegen-603f0181a943aed4/out/lib.rs:3456:159
     |
3456 |                       #[allow(unused_imports)]
     |                       ^^^^^^^^^^^^^^^^^^^^^^^^
/home/travis/build/serde-rs/serde/serde_codegen/src/lib.rs:33:1: 33:47 note: in this expansion of include!
     |
help: if you just forgot a `!`, use
     |                       #![allow(unused_imports)]
     = help: for further information visit https://github.com/Manishearth/rust-clippy/wiki#useless_attribute
```

**Comment by oli-obk** [comment]
why do we have that attribute anyway?

**Comment by oli-obk** [comment]
something with old rust version support?

**Comment by oli-obk** [comment]
so our codebase has the `unused_imports` character sequence exactly once, and that one is not linting. It's all in the generated code. Is aster/syntex generating those?

**Comment by oli-obk** [comment]
quasi generates those `unused_imports`: https://github.com/serde-rs/quasi/blob/d554e9eee0f0ef48a07a3825414f28806a77bbb9/quasi_codegen/src/lib.rs#L747

since that is the only useful lint attribute on a `use` that I can think of, I'll just whitelist it.
