### ISSUE TITLE
Deserialize a field containing either a complex struct or a string

### ISSUE THREAD

**Issue by emk** [serde-rs/serde#515]
Thank you for a great serialization library! But I've hit a puzzling deserialization riddle, and I need extra help from experts.

The `docker-compose.yml` file format contains `Service` and `Build` structures which look something like this:

```rust
/// A service which will be managed by `docker-compose`.
#[derive(Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct Service {
    /// How to build an image for this service.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub build: Option<Build>,

    // ...
}

/// Information on how to build a Docker image.
#[derive(Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct Build {
    /// The source directory to use for this build.
    pub context: Context,

    /// The name of an alternate `Dockerfile` to use.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dockerfile: Option<String>,

    /// Build arguments.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty",
            deserialize_with = "deserialize_map_or_key_value_list")]
    pub args: BTreeMap<String, String>,
}
```

But the `Build` can be represented in one of two ways. Sometimes we'll get an actual struct:

```yaml
my_service:
  build:
    context: "."
    dockerfile: "Dockerfile"
    args:
      key: "value"
```

But it's also valid to specify just the `context` field as a bare string:

```yaml
my_service:
  build: "."
```

It's possible to deserialize these two representations manually if I'm willing to write a monster `Deserialize` function for `Build` by hand:

```rust
impl Deserialize for Build {
    fn deserialize<D>(deserializer: &mut D) -> Result<Build, D::Error>
        where D: Deserializer
    {
        // We create a `Visitor` type, with one method for each data type
        // we support.  The deserializer will call the method corresponding
        // to the data that's actually in the file.
        struct BuildVisitor;

        impl Visitor for BuildVisitor {
            type Value = Build;

            // The deserializer found a string, so handle it.
            fn visit_str<E>(&mut self, value: &str) -> Result<Build, E>
                where E: de::Error
            {
                Ok(Build {
                    context: Context::new(value),
                    dockerfile: None,
                    args: Default::default(),
                })
            }

            // The deserializer found a key/value map.  We'll need to
            // extract the keys and values one at a time and turn them into
            // an object.
            fn visit_map<V>(&mut self, mut visitor: V) -> Result<Build, V::Error>
                where V: MapVisitor
            {
                let mut context: Option<Context> = None;
                let mut dockerfile: Option<String> = None;
                let mut args: Option<BTreeMap<String, String>> = None;

                while let Some(key) = try!(visitor.visit_key::<String>()) {
                    match key.as_ref() {
                        "context" => {
                            if context.is_some() {
                                return Err(<V::Error as Error>::duplicate_field("context"));
                            }
                            context = Some(try!(visitor.visit_value()));
                        }
                        "dockerfile" => {
                            if dockerfile.is_some() {
                                return Err(<V::Error as Error>::duplicate_field("dockerfile"));
                            }
                            dockerfile = Some(try!(visitor.visit_value()));
                        }
                        "args" => {
                            if args.is_some() {
                                return Err(<V::Error as Error>::duplicate_field("args"));
                            }
                            args = Some(try!(visitor.visit_value::<MapOrKeyValueList>()).into_map());
                        }
                        name => {
                            return Err(<V::Error as Error>::unknown_field(name));
                        }
                    }
                }
                try!(visitor.end());
                let context = match context {
                    Some(context) => context,
                    None => try!(visitor.missing_field("context")),
                };
                Ok(Build {
                    context: context,
                    dockerfile: dockerfile,
                    args: args.unwrap_or_else(|| { Default::default() }),
                })
            }
        }

        const FIELDS: &'static [&'static str] = &["context"];
        deserializer.deserialize_struct("Build", FIELDS, BuildVisitor)
    }
}
```

But this is obviously not a scalable solution, because many similar problems occur elsewhere in the file format. This typically happens when a pre-existing string field has been expanded to handle more complex data by allowing an optional struct.

In a perfect world, I'd love some way to write a new `visit_str` to handle the special case, but to reuse the `visit_map` method provided by `#[derive(Deserialize)]` on `Build`. But I spent a couple hours staring at the API this weekend, and I couldn't find a better way to do this:

- The `BuildVisitor` generated by serde is not exposed, so I can't build another visitor that wraps it and calls into it.
- I can't find any way to do look-ahead in a custom `deserialize` method. If I could tell whether or not I had a simple string, I could either decide to deserialize it myself, or I could pass it to `Build`'s automatically generated `Deserialize` implementation.
- By the time I'm inside `visit_map`, it seems to be too late, because there's no way to hand off my `MapVisitor` to any other deserialization API, and certainly not to `Build`'s automatically generated `Deserialize` implementation.

Is there a way around this problem without writing a lot of large, hairy `visit_map` implementations that serde should be generating for me? Any pointers you can provide would be greatly appreciated!

**Comment by dtolnay** [comment]
Great question @emk. Here is one possible approach based on your comment that this typically happens where a pre-existing string field is expanded to handle more complex data. I am using Rust's builtin [`FromStr`](https://doc.rust-lang.org/std/str/trait.FromStr.html) trait as well as the [`Void`](http://burntsushi.net/rustdoc/void/enum.Void.html) type to mean that FromStr never fails.

I am using `serde_json::Value` because I have not gotten around to implementing a deserializable `serde_yaml::Value` yet (tracked at https://github.com/dtolnay/serde-yaml/issues/23). It will work fine though because the formats are so similar from Serde's perspective.

You can reuse the `#[serde(deserialize_with = "string_or_struct")]` everywhere else this happens because it is generic over the type of struct.

```rust
#[derive(Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct Service {
    #[serde(skip_serializing_if = "Option::is_none",
            deserialize_with = "string_or_struct")]
    pub build: Option<Build>,
}

impl FromStr for Build {
    type Err = Void;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        Ok(Build {
            context: s.to_string(),
            dockerfile: None,
            args: BTreeMap::new(),
        })
    }
}

fn string_or_struct<T, D>(d: &mut D) -> Result<Option<T>, D::Error>
    where T: Deserialize + FromStr<Err = Void>,
          D: Deserializer
{
    let value: serde_json::Value = try!(Deserialize::deserialize(d));
    if let serde_json::Value::String(s) = value {
        return Ok(Some(FromStr::from_str(&s).unwrap()));
    }
    serde_json::from_value(value).map(Some).map_err(|e| {
        serde::de::Error::custom(e.to_string())
    })
}
```

**Comment by dtolnay** [comment]
> By the time I'm inside `visit_map`, it seems to be too late, because there's no way to hand off my `MapVisitor` to any other deserialization API

I agree this is a problem. I filed #516 to think of a better way to do this.

**Comment by dtolnay** [comment]
Ah #516 exists already! Here is a much better approach without using `serde_json::Value`:

```rust
fn string_or_struct<T, D>(d: &mut D) -> Result<Option<T>, D::Error>
    where T: Deserialize + FromStr<Err = Void>,
          D: Deserializer
{
    struct StringOrStruct<T>(PhantomData<T>);

    impl<T> de::Visitor for StringOrStruct<T>
        where T: Deserialize + FromStr<Err = Void>
    {
        type Value = T;

        fn visit_str<E>(&mut self, value: &str) -> Result<T, E>
            where E: de::Error
        {
            Ok(FromStr::from_str(value).unwrap())
        }

        fn visit_map<M>(&mut self, visitor: M) -> Result<T, M::Error>
            where M: de::MapVisitor
        {
            let mut mvd = de::value::MapVisitorDeserializer::new(visitor);
            Deserialize::deserialize(&mut mvd)
        }
    }

    d.deserialize(StringOrStruct(PhantomData)).map(Some)
}
```

**Comment by emk** [comment]
The second version is just exactly what I was hoping for! Let me try it out and see if it works once I add the last couple of bells and whistles.

**Comment by dtolnay** [comment]
I added a slightly simplified version of this example to the website: https://serde.rs/string-or-struct.html. I don't have time right now but later today I will add some more detailed comments especially about what MapVisitorDeserializer is doing.

**Comment by emk** [comment]
Your proposed idea is working great! I implemented both serialization and deserialization, and added support for a real `Context` type (which is an enum distinguishing between different kinds of strings found in `context:`).

Please feel free to close this issue whenever you've finished any further doc changes you want to make on your end.
