### ISSUE TITLE
YAML Support

### ISSUE THREAD

**Issue by hugoduncan** [serde-rs/serde#52]
YAML support would be interesting for configuration files that wanted to use structured richer than TOML allows for, and also wanted to allow comments (which JSON doesn't).

**Comment by erickt** [comment]
I did see that someone's made a binding to [libyaml](https://github.com/kimhyunkang/libyaml-rust), which we could use as the foundation for this.

**Comment by Byron** [comment]
@erickt I'd very much like a pure-Rust yaml implementation, to prevent dependencies to libyaml. Maybe the latter could be statically linked in the [libyaml](https://github.com/kimhyunkang/libyaml-rust) project, right now it is only linked dynamically though. On the other hand, how hard can it be to get a native Rust implementation going ... ? Would you be OK if I try to make said implementation - I happen to need yaml support for my project. The main benefit I see is the ability to use the pre-existing `Serializer`/`Deserializer` implementation on my structures (currently used for json only), and possibly the ability to let these objects share a common `Value` enum. What are your thoughts about that ?

**Comment by Byron** [comment]
@hugoduncan I need it as well and will implement a Rust version of it, just to get rid of the libyaml dependency which would make deploying programs harder. You can watch the progress on the [corresponding PR](https://github.com/serde-rs/serde/pull/73).

**Comment by softprops** [comment]
+1

**Comment by dtolnay** [comment]
YAML support exists at [dtolnay/serde-yaml](https://github.com/dtolnay/serde-yaml). It uses a [pure rust YAML implementation](https://github.com/chyh1990/yaml-rust), so no libyaml. I have added a link in the Serde readme. I think this issue can be closed.

**Comment by dtolnay** [comment]
@hugoduncan @softprops YAML support exists at [dtolnay/serde-yaml](https://github.com/dtolnay/serde-yaml). It uses a [pure rust YAML implementation](https://github.com/chyh1990/yaml-rust), so no libyaml. I have added a link in the Serde readme. I think this issue can be closed.

**Comment by erickt** [comment]
Thanks!
