### ISSUE TITLE
Deserialization errors like "Error: Invalid type. Expected `I64`" are hard for users to understand

### ISSUE THREAD

**Issue by emk** [serde-rs/serde#528]
Thank you for your help parsing mixed strings and structs! Here's a second issue to think over. :-)

Here, I'm parsing a 1,300-line `docker-compose.yml` file which uses bare string notation, and which therefore sometimes accidentally uses an integer value like `1` where it should have used a string:

``` yaml
version: 2
services:
  foo:
    environment:
      NOKOGIRI_USE_SYSTEM_LIBRARIES: 1
      REDIS_URL: redis://redis:6379
```

I deserialize this with the following declaration:

``` rust
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty",
            deserialize_with = "deserialize_map_or_key_value_list")]
    pub environment: BTreeMap<String, String>,
```

The function `deserialize_map_or_key_value_list` contains a `visit_map` function which calls `visitor.visit_value::<String>()` to read a string.

When I run this program over the 1,300 line input file, it gives me the following error:

```
target/debug/examples/normalize < docker-compose.yml > test.yml
Error: Invalid type. Expected `I64`
```

There are several problems here:
1. The error message should be the "other way around", and include both the expected type and the one we actually got.
2. The error message should ideally include a line number so the user knows where in the enormous file the error occurs.
3. The error message should include the actual I64 value.

This would ideally give us something like:

```
<input>:869: Expected String, got I64 value `1`.
```

This would make my program much more user friendly. :-) I can easily provide a slightly better workaround in this particular case, but I'd love to find a more general solution.

**Comment by Bjohnson131** [comment]
+1 for this- Would be neat if there was a field name, or some other sort of debug info printed..
