### ISSUE TITLE
Provide macro to forward deserializer methods to inner deserializer

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#531]
@nox 

> So for my deserializer forwarder,
> my use case is that I want to wrap MapDeserializer in a newtype,
> and implement Deserializer on the newtype, forwarding to inner deserializer.

Some brainstorming:

``` rust
forward_to_deserializer! {
    (self.integers) {
        usize u8 u16 u32 u64 isize i8 i16 i32 i64
    }
    (self.floats) {
        f32 f64
    }
}

forward_to_deserializer! {
    (usize u8 u16 u32 u64 isize i8 i16 i32 i64) => self.integers;
    (f32 f64) => self.floats;
}
```

**Comment by nox** [comment]
I like the second one a bit more I think.

**Comment by dtolnay** [comment]
I am closing the issue because I haven't encountered this as a frequent need.
