### ISSUE TITLE
Serde dependency versioning policy.

### ISSUE THREAD

**Issue by cstorey** [serde-rs/serde#532]
I've just looked at upgrading the dependencies on a project of mine, which depends on `etcd` 0.5.4. Now, when I started using it, the current version of `serde_codegen` was 0.7.7, which depended in turn on `syntex` 0.31.0. 

Now, attempting to build `etcd` from scratch, cargo finds that `serde_codegen` has a release at 0.7.15, which in turn depends on `syntex 0.33.0`. So, we end up in a situation where `serde_codegen::expand` expects a version 0.33.0 `syntex::Registry`, but we pass in a version 0.31.0 `syntex::Registry`, which naturally is a different type.

So from my understanding of how cargo handles versioning constraints when no explicit constraints are passed, I'd like to suggest the following policy fix:

If a dependency's minor/major version changes and you expose that dependency in your public API, then your minor/major version should change to indicate your compatibility constraints. So if your dependency on `syntex` changes from 0.31.0 to 0.33.0, then `serde_codegen` should have at least a minor version bump, from 0.7.2 to say, 0.8.0.

Does that seem fair?

**Comment by jwilm** [comment]
This was fixed in #362. Serde no longer has a public dependency on syntex, and your project doesn't need the dev dependency. Your build script will need slight modifications, though. Afterwards, you won't run into syntex versioning issues with serde. :smile:

**Comment by dtolnay** [comment]
Check out [this forum thread](https://users.rust-lang.org/t/here-is-how-to-avoid-being-broken-by-syntex-updates/6189?u=dtolnay) for how to avoid being broken by Syntex updates. See #356 for extensive discussion about why your proposed scheme is not feasible. We fixed this by removing `serde_codegen::register` in 0.8.0 so Syntex is no longer part of the API.

**Comment by cstorey** [comment]
Ah, okay. I'm afraid I'd missed that ticket. I'll mark this as closed, as it looks like it'll be a non-issue with newer releases then.

Thanks!
