### ISSUE TITLE
impl Serialize and Deserialize for std::time::SystemTime

### ISSUE THREAD

**Issue by jplatte** [serde-rs/serde#535]
If there is a different type that is better suited for timestamps in serialized data that's already supported by serde, I'd be happy to know about it. The serialized format should probably be [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601).

**Comment by dtolnay** [comment]
:+1: We're going to have to use this approach mentioned in the documentation:

> Although a `SystemTime` cannot be directly inspected, the `UNIX_EPOCH` constant is provided in this module as an anchor in time to learn information about a `SystemTime`. By calculating the duration from this fixed point in time, a SystemTime can be converted to a human-readable time, or perhaps some other string representation.

@jplatte for now can you use [`chrono::DateTime`](https://lifthrasiir.github.io/rust-chrono/chrono/datetime/struct.DateTime.html) which already supports Serde serialization to ISO 8601?

**Comment by jplatte** [comment]
@dtolnay Thanks for the pointer, I actually like the explicitness of that API, I'll happily use it, not just temporarily. However, it doesn't seem to be supported in the latest crates.io release of serde (0.8.6), I get

```
the trait bound `chrono::DateTime<chrono::Local>: serde::Deserialize` is not satisfied
```

(same if I try UTC)

**Comment by dtolnay** [comment]
@jplatte they make you opt into Serde support because not everybody wants it:

https://github.com/lifthrasiir/rust-chrono/blob/6cc5d1869641f75bda2135e58aef60f333df4227/Cargo.toml#L21

```toml
[dependencies]
chrono = { version = "0.2", features = ["serde"] }
```

**Comment by jplatte** [comment]
Ah, thanks again, now it works! :)

**Comment by ebkalderon** [comment]
Would also be nice to support [`Instant`](https://doc.rust-lang.org/std/time/struct.Instant.html) as well.
