### ISSUE TITLE
`deserialize_struct` is called with real field names instead of deserializable names

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#559]
``` rust
#[derive(Deserialize)]
pub struct S {
    #[serde(rename = "A")]
    a: u8,
    #[serde(skip_deserializing)]
    b: u8,
}
```

I was surprised to see this in the generated code:

``` rust
const FIELDS: &'static [&'static str] = &["a", "b"];
deserializer.deserialize_struct("S", FIELDS, __Visitor)
```

If I had been asked to guess, I would have guessed it would be `["A"]` instead of `["a", "b"]`. Unclear whether this affects anything because I don't know what uses those field names.

**Comment by erickt** [comment]
@dtolnay: yeah I think this would make sense to change. There isn't much reason for the deserializer to get passed the rust-field-specific names. This must have just been something we missed when we added field renaming. I'm not sure if anyone uses them. Maybe toml? I remember it did some funky things with trying to reparse fields a few different ways to see if the types were correct.

**Comment by dtolnay** [comment]
Same thing for renamed variants:

```rust
#[derive(Deserialize)]
pub enum E {
    #[serde(rename = "B")]
    A,
}
```

```rust
const VARIANTS: &'static [&'static str] = &["A"];
deserializer.deserialize_enum("E", VARIANTS, __Visitor)
```
