### ISSUE TITLE
Issues with the new `serde_derive` system

### ISSUE THREAD

**Issue by neon64** [serde-rs/serde#567]
When using that plugin, there are two errors:

```
error: the semantics of constant patterns is not yet settled (see issue #31434)
  --> src/state.rs:10:1
   |
10 | pub enum ArchiveEntryPerReplica {
   | ^
   |
   = help: add #![feature(structural_match)] to the crate attributes to enable

error: internal implementation detail (see issue #29642)
  --> src/state.rs:10:1
   |
10 | pub enum ArchiveEntryPerReplica {
   | ^
   |
   = help: add #![feature(rustc_attrs)] to the crate attributes to enable
```

Both of these are easily solvable by following the compiler's instructions. But I suppose my question is, why are these needed in the first place and should it be documented so that new users don't get tripped up?

Additionally if I run `cargo doc` then cargo tries to document the `serde_derive` crate and complains because it contains items with `#[rustc_macro_derive]`.

```
error: the `#[rustc_macro_derive]` attribute is only usable with crates of the `rustc-macro` crate type
 --> /home/chris/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_derive-0.8.10/src/lib.rs:9:3
  |
9 | #[rustc_macro_derive(Serialize)]
  |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: the `#[rustc_macro_derive]` attribute is only usable with crates of the `rustc-macro` crate type
  --> /home/chris/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_derive-0.8.10/src/lib.rs:18:3
   |
18 | #[rustc_macro_derive(Deserialize)]
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I realise it is super early days for `serde_derive` but I thought I'd just point out these issues as from some quick searching I can't see any acknowledgement of them.

**Comment by dtolnay** [comment]
Thanks for reporting these!

The first one is fixed in https://github.com/rust-lang/rust/pull/36782 and will be in tomorrow's nightly.

The second one I filed as https://github.com/rust-lang/cargo/issues/3132.

**Comment by dtolnay** [comment]
I confirmed that `#![feature(structural_match, rustc_attrs)]` are no longer necessary in `rustc 1.14.0-nightly (289f3a4ca 2016-09-29)`.

The doc issue is in progress at https://github.com/rust-lang/rust/pull/36847.

**Comment by neon64** [comment]
Thanks very much by the way for the quick progress made on these two issues.

**Comment by dtolnay** [comment]
The rustdoc fix just merged. I will leave this ticket open until I can confirm that it works.

**Comment by dtolnay** [comment]
I confirmed that `cargo doc` works using rustc 1.14.0-nightly (9c31d76e9 2016-10-03).
