### ISSUE TITLE
[Question] Array deserialization from JSON Object

### ISSUE THREAD

**Issue by impowski** [serde-rs/serde#580]
For example I have a JSON Object:
``` object {
    "deps": ["libx","liba","libb"]
} ```
And when I'm trying to make something like this https://is.gd/wmcdIj it's not working. And the 2 possible ways I see is to implement my own Deserialize or use codegen. Maybe I'm missing something?

**Comment by oli-obk** [comment]
I'm not sure what your playground link has to do with your problem. You had `'` as the opening for a json string, which is illegal according to [the standard](json.org). See http://play.integer32.com/?gist=e36ee81c19c6b531c915e8789b18b85b for a working example.

Is your final goal to turn your json text into the following struct?

```rust
struct Object {
    deps: Vec<String>,
}
```

**Comment by impowski** [comment]
@oli-obk it's kinda not mine the guy from IRC linked me this. Yeah my goal is to deserialize JSON to a struct with a bunch of arrays. But I still don't understand which way is better with serde_codegen or with my own Deserialize trait impl? And I will check your link right now.

**Comment by oli-obk** [comment]
in 3 months there'll be a convenient stable method through `serde_derive`. Until then, if that simple one is all you need, I suggest you just go with the method in the playground, since it requires the same amount of allocation and all you want is a `Vec<String>`.

**Comment by impowski** [comment]
@oli-obk yeah I know about that, because I used it in nightly. I finally figured that I had and object inside of another JSON now it works. Sorry was my mistake.

**Comment by oli-obk** [comment]
No worries. Always happy to help. Feel free to ask here or on irc in the #serde channel if you have any questions.
