### ISSUE TITLE
Serde field attributes not written to TokenStream

### ISSUE THREAD

**Issue by KodrAus** [serde-rs/serde#585]
Previously, I've piggybacked on `serde_codegen_internals` to get whether or not a field will be serialised, and if so, what it will be called.

With the new macros 1.1 stuff this doesn't work because the `serde` field attributes are being removed from the token stream output if my code runs after `Serialize`:

```rust
//No serde attributes for ElasticType
#[derive(Serialize, ElasticType)]
struct MyType { ... }
```

```rust
//All the serde attributes for ElasticType
#[derive(ElasticType, Serialize)]
struct MyType { ... }
```

Wouldn't this also affect attributes visible to `Deserialize` if you also derive `Serialize` first?

**Comment by sfackler** [comment]
This is intentional - the crate would fail to compile if the attributes weren't stripped since they're unknown to the compiler. It's one of the known bugs on the tracking issue for macros 1.1: https://github.com/rust-lang/rust/issues/35900#issuecomment-252499766
