### ISSUE TITLE
Question: hand-implementing Deserialize for a newtype struct wrapping an already-Deserialize(able) value

### ISSUE THREAD

**Issue by orthecreedence** [serde-rs/serde#601]
Hi, I'm on stable and not wanting to use codegen because of the trade-offs, so I want to find a way to do this by hand.

Basically, I have a type wrapping `serde_json::Value` (I would just use `Value` for my type but I want to implement `Default` for it) and I'm trying to figure out how exactly to deserialize it:

```rust
pub struct SyncData(Value);
impl Serialize for SyncData {
    fn serialize<S>(&self, serializer: &mut S) -> Result<(), S::Error>
        where S: Serializer
    {
        self.0.serialize(serializer)
    }
}
impl Deserialize for SyncData {
    fn deserialize<D>(deserializer: &mut D) -> Result<Self, D::Error>
        where D: Deserializer
    {
        struct SyncDataVisitor;
        impl<'a> ::serde::de::Visitor for SyncDataVisitor {
            type Value = SyncData;

            fn visit_newtype_struct<D>(&mut self, deserializer: &mut D) -> Result<Self::Value, D::Error>
                where D: Deserializer
            {
                // What do I do here??
            }
        }
        deserializer.deserialize_newtype_struct("SyncData", SyncDataVisitor)
    }
}
```

I'm not clear at all on how to get the actual value I need to deserialize from `deserializer` or `self` in `visit_newtype_struct`. I can't find any examples of how to do this.

Any help would be greatly appreciated!

**Comment by dtolnay** [comment]
If you just need it to deserialize exactly as though it were deserializing a serde_json::Value, you don't need your own visitor. This should do the trick:

```rust
impl Deserialize for SyncData {
    fn deserialize<D>(deserializer: &mut D) -> Result<Self, D::Error>
        where D: Deserializer
    {
        Deserialize::deserialize(deserializer).map(SyncData)
    }
}
```

This works by inferring that `Deserialize::deserialize(...)` needs to be a `Result<Value, D::Error>` so it knows to use `Value`'s implementation of Deserialize.

**Comment by orthecreedence** [comment]
Ah it works!!! Thank you!
