### ISSUE TITLE
CloudFlare prevents Tor users from accessing documentation

### ISSUE THREAD

**Issue by burdges** [serde-rs/serde#603]
It appears that https://serde.rs/codegen.html has a CloudFlare configuration that blocks Tor users.  There are sites like wikipedia that face enough vandalism that blocking Tor users helps, but most sites do not benefit from doing so.  There is a configuration option for giving Tor users access in your CloudFlare configuration, probably under the countries section since they enabled this by treating Tor as a country.

**Comment by dtolnay** [comment]
Thanks for the report. This was not intentional. I added the following whitelist under "Access Rules" in Cloudflare:

![selection_012](https://cloud.githubusercontent.com/assets/1940490/19833020/13d0adf0-9de8-11e6-8e28-d61828c4a7d3.png)

Can you check whether it is accessible now?

**Comment by burdges** [comment]
You, your links from README.md pop up just fine now.  Thanks you!  :)
