### ISSUE TITLE
Sequence and map types needed

### ISSUE THREAD

**Issue by diwic** [serde-rs/serde#607]
I'm looking into serde support for my D-Bus bindings, but quickly ran into problems with trying to Serialize an empty array.

D-Bus allows typing of arrays, i e, all elements must be the same type. I could take that type from the first element, if it weren't for the fact that arrays can be empty. So, if I receive a `serialize_seq_fixed_size` with a size of 0 (or a `serialize_seq` directly followed by a `serialize_seq_end`), I have no idea if I need to append an empty D-Bus array of `i32`s, `&str`s or something else.

Edit: The same applies to maps, which are also strongly typed.

**Comment by oli-obk** [comment]
We could make `serialize_seq` generic over the type to be serialized, just like `serialize_seq_elt`. But we'd still need a way to use a `Serialize` type without an object. I think this is closely related to the tagging troubles we have with cbor

**Comment by diwic** [comment]
Yeah, given the current design of serde I'm not sure how to solve it either...
