### ISSUE TITLE
serde_codegen is removing macro_rules from source

### ISSUE THREAD

**Issue by AerialX** [serde-rs/serde#608]
Starting with the [syntex example](https://github.com/serde-rs/serde/tree/master/examples/serde-syntex-example), and replacing the `println!("{}", serialized);` line in [main.rs.in](https://github.com/serde-rs/serde/blob/master/examples/serde-syntex-example/src/main.rs.in#L11) with the following:

```rust
	macro_rules! test_thing {
		() => {
			println!("{}", serialized);
		};
	}

	test_thing!();
```

results in the following error: `error: macro undefined: 'test_thing!'`

The macro definition is completely stripped out of the source. This only happens when building with serde_codegen/syntex, the code compiles fine with unstable proc_macros. This is a regression, as it used to work in previous versions; and still does if you move the macro outside of the `main()` function scope (however, due to hygene, the `serialized` identifier will need to be provided as a macro argument).

Wasn't sure where to put this, it's probably a syntex bug or something rather than a serde one? I couldn't find any related existing reports...

**Comment by dtolnay** [comment]
Thanks for the detailed report Aaron. You don't need to worry about where to file issues, this repo is always a good fallback for libraries that we maintain.

@erickt this sounds like it's from the brutal macro expansion changes / merge conflicts in syntex 0.45. When I get home I will confirm by testing it with 0.44 and 0.45, then try to track down where the merge went wrong.

**Comment by dtolnay** [comment]
I confirmed that this is a regression between serde_codegen 0.8.12 and 0.8.13, which is right when the bad syntex merge conflict happened. The only relevant change in that version is bumping the syntex dependency from 0.44 to 0.45. I will start tracking this down in syntex.

**Comment by dtolnay** [comment]
[This looked like it could be relevant](https://github.com/serde-rs/syntex/blob/v0.48.0/syntex_syntax/src/ext/tt/macro_rules.rs#L171-L176) but even with keep_macs=true this fails the same way.

**Comment by dtolnay** [comment]
@oli-obk do you have some time to help look at this?

**Comment by dtolnay** [comment]
serde_codegen is not supported anymore.
