### ISSUE TITLE
Serialization for C-like enums optimizes badly 

### ISSUE THREAD

**Issue by dotdash** [serde-rs/serde#610]
Some serialization formats, for example bincode, don't care about the type and variant names, but only need to serialize the variant index. Unfortunately, there's still code generated for each variant, and for example when serializing to a `Vec<u8>`, after inlining we get a call to `Vec::reserve` in each match arm, and neither Rust nor LLVM can currently to hoist the identical block prefixes out of the match arms. So for a C-like enum, the function does effectively just write a single integer to the vector, but it grows in a linear fashion with the number of enum variants.

I'm not exactly familiar with serde's internals, but I guess one possibility would be to have a `serialize_variant_index` method to start the serialization of an enum, followed by a call to one of the `serialize_*_variant` methods. The bincode serializer would then implement `serialize_variant_index` to store the variant index, and then simply forward to `serialize_unit` in `serialize_unit_variant`.

**Comment by dtolnay** [comment]
```rust
enum E { A, B }
```

I think we can fix this without changing the Serializer API by recognizing the C-like enum case during codegen and treating it differently. Currently we generate something like:

```rust
match *self {
    E::A => serializer.serialize_unit_variant("E", 0usize, "A"),
    E::B => serializer.serialize_unit_variant("E", 1usize, "B"),
}
```

Instead we could generate:

```rust
let name = match *self {
    E::A => "A",
    E::B => "B",
}
serializer.serialize_unit_variant("E", *self as usize, name)
```

@dotdash do you think this would optimize as well as you would like?

**Comment by dtolnay** [comment]
I am closing this issue because this can be handled by a derive macro in a separate crate. Something like:

```rust
#[derive(Serialize_fast)]
enum E {
    A,
    B,
}
```

which emits the appropriate Serialize impl shown in https://github.com/serde-rs/serde/issues/610#issuecomment-271113463.

If we see that enough people are sensitive enough to the performance of this case to use that other derive, then we can consider implementing the same code generation in serde_derive.
