### ISSUE TITLE
stable/syntex attribute parsing is dependent on order

### ISSUE THREAD

**Issue by AerialX** [serde-rs/serde#612]
A struct defined as follows does not error upon reaching unknown fields when compiled with syntex/stable, the attribute is effectively ignored:

```rust
#[serde(deny_unknown_fields)]
#[derive(Deserialize)]
pub struct SomeStruct {
	...
}
```

However, this definition works as expected:

```rust
#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SomeStruct {
	...
}
```

Both variants are fine with serde_derive/unstable. Not sure whether this a regression or not.

**Comment by dtolnay** [comment]
Thanks! I moved this to https://github.com/serde-rs/syntex/issues/111 because Serde will be moving off of Syntex now that Macros 1.1 is being stabilized.
