### ISSUE TITLE
Update to use proc_macro_derive attributes

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#614]
https://github.com/rust-lang/rust/pull/37614 introduces `#[proc_macro_derive(Serialize, attributes(serde))]` to whitelist attributes of a certain name inside structs that have a custom derive. We no longer need to strip serde attributes after expansion.

Also that change requires custom derives to no longer return a copy of the input item so we need to fix that.

**Comment by dtolnay** [comment]
Fixed in #618 but currently blocked by rust-lang/rust#37788.

**Comment by antoyo** [comment]
The bug you mentioned is fixed.
Could you please update a new version on crates.io?

**Comment by dtolnay** [comment]
Published as [0.8.18](https://crates.io/crates/serde_derive/0.8.18).
