### ISSUE TITLE
Canno't derive my struct

### ISSUE THREAD

**Issue by k0pernicus** [serde-rs/serde#615]
Hi there,
I'm implementing a crate to communicate with the Github API.
I have a lot of structures that implement a `get` and `update` methods, and each function returns it own structure that deriving `Debug`, `Serialize` and `Deserialize`.

So, I implemented a trait that convert and returns a structure, and some other traits for other functionalities of my crate.

For example, I have:
```
trait GetterAPI {
    fn get<T>(&self) -> Result<T, String>
        where T: std::fmt::Debug + serde::Serialize + serde::Deserialize;
}
```

and a user structure
```
#[derive(Debug, Serialize, Deserialize)]
pub struct UserInfoStructure {
...
}
```

So, I decided to implement `GetterAPI` for the structure `UserClient`:
```
impl<'a> GetterAPI for UserClient<'a> {
    fn get<UserInfoStructure>(&self) -> Result<UserInfoStructure, String> {
        let url = ... ;
        match self.github_client
            .process_request(Method::Get, &url, None) {
            Ok(response) => {
                match serde_json::from_str::<UserInfoStructure>(&response) {
                    Ok(user_structure) => Ok(user_structure),
                    Err(error) => {
                        Err(format!("Error when converting the string request from Github to \
                                     JSON: {}, for response {}",
                                    error,
                                    response))
                    }
                }
            }
            Err(error) => Err(error),
        }
    }
}
```

The problem here is I have this error message, and I don't understand it because `UserStructure` is deriving `Deserialize`...
```
error[E0277]: the trait bound `UserInfoStructure: serde::Deserialize` is not satisfied
  --> src/user.rs:80:23
   |
80 |                 match serde_json::from_str::<UserInfoStructure>(&response) {
   |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `serde::Deserialize` is not implemented for `UserInfoStructure`
   |
   = help: consider adding a `where UserInfoStructure: serde::Deserialize` bound
   = note: required by `serde_json::from_str`
```

Is there a mistake in my code?

**Comment by k0pernicus** [comment]
Ok, I solved the problem using this definition:
```
fn get<UserInfoStructure>(&self) -> Result<UserInfoStructure, String>
        where UserInfoStructure: serde::Deserialize
```
but I don't understand why I need to specify `where UserInfoStructure: serde::Deserialize` considering `UserInfoStructure` is deriving `Deserialize` :-/

**Comment by oli-obk** [comment]
you used `UserInfoStructure` as a generic argument to `fn get<UserInfoStructure>(&self) -> Result<UserInfoStructure, String>`. This is the same as using `fn get<T>(&self)->Result<T, String>`.

I think what you actually want is for `UserClient::get` to always return a `Result<UserInfoStructure, String>`, so your trait should be 

```rust
trait GetterAPI {
    type GetType: std::fmt::Debug + serde::Serialize + serde::Deserialize;
    fn get(&self) -> Result<Self::GetType, String>
}
```

and your impl should be

```rust
impl<'a> GetterAPI for UserClient<'a> {
    type GetType = UserInfoStructure;
    fn get(&self) -> Result<UserInfoStructure, String> {
        ...
    }
```

**Comment by k0pernicus** [comment]
That's right - thank you for your explanation @oli-obk :-) 👍
