### ISSUE TITLE
serde_codegen seems to be removing derive()s with some cfg attrs

### ISSUE THREAD

**Issue by vvuk** [serde-rs/serde#616]
This is a bit of a weird one.

See this commit for a needed workaround: https://github.com/servo/webrender/commit/efd4e1d444e54d5c7429f14e872be5c8678ca116

With some analysis at https://github.com/servo/webrender/pull/549#discussion_r87451885 -- basically, given:

```#[cfg_attr(all(unix, not(target_os = "macos")), derive(Clone, Serialize, Deserialize))] ```

`Serialize` and `Deserialize` have code generated, but the resulting code does not retain `#[cfg_attr(..., derive(Clone)]` as it should.  (or even just `#[derive(Clone)]`, if codegen is supposed to evaluate cfgs.)  But

```#[cfg_attr(not(any(target_os = "macos", target_os = "windows")), derive(Clone, Serialize, Deserialize))]```

works.  Can be reproduced by checking out webrender from https://github.com/servo/webrender/commit/6a2f35474186c593aa204559ba4373d5dbf861fb and building on linux.

**Comment by dtolnay** [comment]
I moved this to https://github.com/serde-rs/syntex/issues/110 because Serde will no longer be using Syntex after Macros 1.1 is stable.
