### ISSUE TITLE
Value enum usable across different formats

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#617]
@autrilla @Mark-Simulacrum I wanted to follow up on following exchange I noticed in IRC:

> *\* autrilla wishes serde provided some sort of Value enum instead of every serde_<format> doing so*
> **<simulacrum>** autrilla: Why do you want that? If you're converting YAML -> JSON this might be helpful: https://serde.rs/transcode.html
> **<autrilla>** simulacrum: I want to parse either yaml or json and check if stuff under certain keys has certain formats
> **<simulacrum>** Oh. Hm. Would deriving serialize or deserialize work on a struct of your own?
> **<autrilla>** simulacrum: that would require me to know the structure of the yaml/json I'm getting, right?
> **<simulacrum>** autrilla: Yes.
> **<autrilla>** simulacrum: unfortunately I have to take arbitrary json/yaml
> **<simulacrum>** (at least up to a point, you can deserialize HashMap<String, String> for example

The JSON Value enum and the YAML Value enum are actually different - the JSON one requires map keys to be strings while YAML allows map keys of other types. It wouldn't make sense for Serde to prefer one or the other.

Fortunately from Serde's perspective both serde_json::Value and serde_yaml::Value are just some type that implements Serialize and Deserialize. There is nothing in serde_json that is specific to serde_json::Value. You can have serde_json deserialize a serde_yaml::Value, and you can have serde_yaml deserialize a serde_json::Value (as long as all map keys are strings).

So the solution is: just use serde_json::Value! Or just use serde_yaml::Value! It depends whether you need to support non-string keys, or whether you want to adopt the lowest-common-denominator of JSON and have non-string keys fail to deserialize.

**Comment by autrilla** [comment]
Woah, thanks! I'm now just deserializing to `serde_yaml::Value`s. When I mentioned this I was thinking of just having serde provide the greatest common denominator (so, for JSON and YAML that'd be what YAML provides) and have runtime checks when serializing, but this could get messy when you add more formats that could have very different structures.

**Comment by dtolnay** [comment]
Hmm, the [`serde-value`](https://github.com/arcnmx/serde-value) crate provides something like that.

```rust
pub enum Value {
    Bool(bool),
    Usize(usize),
    U8(u8),
    U16(u16),
    U32(u32),
    U64(u64),
    Isize(isize),
    I8(i8),
    I16(i16),
    I32(i32),
    I64(i64),
    F32(f32),
    F64(f64),
    Char(char),
    String(String),
    Unit,
    UnitStruct(&'static str),
    Option(Option<Box<Value>>),
    Newtype(Box<Value>),
    Seq(Vec<Value>),
    Map(BTreeMap<Value, Value>),
    Bytes(Vec<u8>),
}
```

It would be pretty unwieldy for your use case because serde_yaml doesn't distinguish between a lot of those variants, so most of them you would never end up with. But other formats do distinguish and would be unhappy with YAML's Value enum.

I am open to other ideas but for now all the Value use cases I can think of are reasonably well suited by some choice of `serde_json::Value`, `serde_yaml::Value`, and `serde_value::Value`.

> **\<autrilla>** dtolnay: I hope you didn't take my comment about serde to mean serde was bad or anything. I just thought having some kind of common ground could be useful for stuff like what I'm doing.

Haha don't worry about that. I almost certainly think Serde is worse than you think it is!
