### ISSUE TITLE
Does not compile on 1.15 (nightly)

### ISSUE THREAD

**Issue by jjuraszek** [serde-rs/serde#620]
https://travis-ci.org/serde-rs/serde/jobs/176255470

**Comment by dtolnay** [comment]
Thanks for the report! The three things broken in that build are Clippy and two Rust issues:

- https://github.com/Manishearth/rust-clippy/issues/1343
- https://github.com/rust-lang/rust/issues/37786
- https://github.com/rust-lang/rust/issues/37788

I see progress already on all of those so I don't think there is any action here for Serde.
