### ISSUE TITLE
Simple string serializer/deserializer implementations

### ISSUE THREAD

**Issue by alexreg** [serde-rs/serde#622]
I was speaking with @oli-obk on IRC about this. It would be nice to have bundled with serde some really simple Serializer/Deserializer implementations that work for primitive types (i.e. numbers, enums, strings, but not collections, structs, etc.) for use as building blocks, particularly in `serialize_with`/`deserialize_with` functions. Is this something that could be added?

**Comment by dtolnay** [comment]
These could be included with #553 so it wouldn't just be serialize_with/deserialize_with functions but also helpers for implementing your own ones.

**Comment by dtolnay** [comment]
Let's continue to track this as part of #553.
