### ISSUE TITLE
Panic with proc-macro

### ISSUE THREAD

**Issue by sackery** [serde-rs/serde#623]
error: internal compiler error: ../src/librustc_metadata/decoder.rs:490: entry: id not found: DefIndex(1) in crate "serde_derive" with number 105

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

thread 'rustc' panicked at 'Box<Any>', ../src/librustc_errors/lib.rs:424
note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by dtolnay** [comment]
Thanks for the report! This is https://github.com/rust-lang/rust/issues/37788 for which a fix has merged into Rust and will be in tomorrow's nightly.

**Comment by dtolnay** [comment]
[Today's build failed](https://buildbot.rust-lang.org/builders/nightly-dist-rustc-linux/builds/715), maybe we'll get it tomorrow.

**Comment by sackery** [comment]
So slowly.
