### ISSUE TITLE
Struct deserialization question / clarification

### ISSUE THREAD

**Issue by bluss** [serde-rs/serde#625]
The manual implementation here https://serde.rs/deserialize-struct.html talks about struct -> sequence and struct -> map correspondances for bincode and JSON respectively.

Are those the only cases, so should it say "*the* two possibilities", or are they just incidental?

**Comment by dtolnay** [comment]
There might be serializers that don't support structs at all, so supporting all formats isn't something you should worry about when writing a Deserialize impl. For practical purposes those are the two possibilities that matter.

Serde codegen handles [two more cases](https://github.com/serde-rs/serde/blob/v0.8.17/serde_codegen/src/de.rs#L757-L773) which are maps with usize keys and maps with &[u8] keys but I don't know any formats that use those. @erickt might be able to say more about the history there.

**Comment by bluss** [comment]
Thank you for the clarification. This is related to ndarray, which uses its own indexing / memory layout scheme, so it's not entirely trival to use derived serialization for it.

In theory it should be simple, because it could be like this:

- Serialization provides a struct of an array of usize, an array of isize, an iterator of &T.
- Deserialization wants: a struct of an array of usize, an array of isize, a `Vec<T>`

How to put those two together into one intermediate struct that is what I don't really see right now. For deserialization, going through Vec is no extra cost. For serialization, we would like to just provide an iterator of the elements, not allocating an intermediate Vec.

**Comment by bluss** [comment]
Maybe the iterator/Vec ser/de pair could be some kind of reusable thing that's implemented only once.

**Comment by dtolnay** [comment]
> Maybe the iterator/Vec ser/de pair could be some kind of reusable thing that's implemented only once.

Would [`std::borrow::Cow`](https://doc.rust-lang.org/std/borrow/enum.Cow.html) work?

```rust
extern crate serde_json;

use std::borrow::Cow;

fn main() {
    let vec = vec![2, 4, 8, 16];
    let cow: Cow<[u8]> = Cow::Borrowed(&vec);

    let j = serde_json::to_string(&cow).unwrap();
    println!("{}", j);

    let cow: Cow<[u8]> = serde_json::from_str(&j).unwrap();
    println!("{:?}", cow);
}
```

**Comment by bluss** [comment]
I considered it, but this is not so simple as a slice and a Vec. As you know, we can't implement custom DSTs in Rust, so we have no chance of using something like Cow for custom views (like arrayview vs array).
