### ISSUE TITLE
[Servo release build] attribute must only have on argument

### ISSUE THREAD

**Issue by novaksam** [serde-rs/serde#630]
`error: attribute must only have one argument
 --> /Users/User/Documents/Sources/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_derive-0.8.19/src/lib.rs:9:3
  |
9 | #[proc_macro_derive(Serialize, attributes(serde))]
  |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
`

`
error: attribute must only have one argument
  --> /Users/User/Documents/Sources/servo/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_derive-0.8.19/src/lib.rs:17:3
   |
17 | #[proc_macro_derive(Deserialize, attributes(serde))]
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
`

Just giving a heads up.

**Comment by dtolnay** [comment]
You need a newer nightly. This feature was added in https://github.com/rust-lang/rust/pull/37614.

Servo avoids problems like this by locking in a version of serde_derive and a version of Rust that work together:

- https://github.com/servo/servo/blob/4dbca055c6d225e5fe5030bf2d402b73d2ea94da/Cargo.lock#L2355
- https://github.com/servo/servo/blob/4dbca055c6d225e5fe5030bf2d402b73d2ea94da/rust-nightly-date#L1
