### ISSUE TITLE
Mastering Rust

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#632]
I noticed [this comment](https://users.rust-lang.org/t/whats-everyone-working-on-this-week-42-2016/8188/4?u=dtolnay) on the users forum.

> Eleventh chapter of https://www.packtpub.com/application-development/mastering-rust4 -- which covers parsing and serialization with all kinds of tools.
>
> Book is currently at about 240 pages, which means that I should still write a little over a hundred pages. The rest of the chapters will be "case study" chapters, covering library/framework usage (Iron, gtk-rs etc).

@vegai if Serde happens to be mentioned in this chapter or one of the case studies later, let me know if you need me to clarify anything about Serde or review what you've written to see if I can think of better approaches for some things.

**Comment by vegai** [comment]
@dtolnay Thank you! I'll certainly appreciate that. I'll contact you later when I have something to show.

**Comment by dtolnay** [comment]
Sounds good. I am closing the issue because there is no action for us at this point, but feel free to comment here whenever you are ready or email me at dtolnay@gmail.com if you don't want to share publicly.
