### ISSUE TITLE
Serialization with a Visitor

### ISSUE THREAD

**Issue by lukas-123** [serde-rs/serde#633]
I am a rust newb and I have a question about custom serialization.
I have the following struct:
```rust
#[derive(Clone, Debug, Deserialize, Eq, PartialEq)]
pub struct StatusBlock {
    pub full_text: String,
    pub short_text: Option<String>,
    pub color: Option<String>,
    pub background: Option<String>,
    pub border: Option<String>,
    pub min_width: Option<Width>,
    pub align: Option<Align>,
    pub name: Option<String>,
    pub instance: Option<String>,
    #[serde(default = "StatusBlock::default_is_urgent")]
    pub urgent: bool,
    #[serde(default = "StatusBlock::default_has_seperator")]
    pub seperator: bool,
    pub seperator_block_width: Option<u32>,
    #[serde(default = "StatusBlock::default_markup")]
    pub markup: Markup,
}
```

I now have a struct ```struct StatusBlocks(Vec<StatusBlock>)``` which I want to serialize to html as a string. I would like the user to be able to supply a visitor for ```StatusBlock``` so that he can generate an html string based on the information that the struct contains. How would I do that with serde?

**Comment by oli-obk** [comment]
I'm not sure how you produce your html, but assuming you have a `to_html()` method you can just

```rust
impl Serialize for StatusBlock {
    fn serialize<S>(&self, serializer: &mut S) -> Result<(), S::Error>
        where S: Serializer {
        serializer.serialize_string(self.to_html())
    }
}
```

**Comment by lukas-123** [comment]
Thank you for your answer. The thing is that I don't know how to produce the html yet and therefore I wanted to do something similiar to what I also use for Deserialization: 
```rust
impl serde::Deserialize for Width {
    fn deserialize<D>(deserializer: &mut D) -> Result<Self, D::Error>
        where D: serde::Deserializer
    {
        struct WidthVisitor;

        impl serde::de::Visitor for WidthVisitor {
            type Value = Width;

            fn visit_str<E>(&mut self, s: &str) -> Result<Width, E>
                where E: serde::de::Error
            {
                Ok(Width::AsString(s.to_string()))
            }

            fn visit_u64<E>(&mut self, v: u64) -> Result<Width, E>
                where E: serde::de::Error
            {
                Ok(Width::AsNumber(v))
            }
        }
        deserializer.deserialize(WidthVisitor)
    }
}
```
The only difference would be that the visitor, maybe ```StatusBlockVisitor```, is supplied by the user, so the user himself can determine how the html should be generated.

**Comment by oli-obk** [comment]
Deserialization and serialization work in very different ways. You won't be able to have a Visitor style serialization.

I suggest you add a function to your type that your users can supply (a field of type function, not a method). This function should be of signature `fn(&StatusBlock) -> String`. And then you can use the setup I showed in the previous post.

**Comment by lukas-123** [comment]
That sounds good. Thank you for your help 👍
