### ISSUE TITLE
skip_(de)serializing still checks for trait bound

### ISSUE THREAD

**Issue by shinglyu** [serde-rs/serde#634]
I'm deriving trait `Serialize` and `Deserialize` for a struct, but one of the field is from a third party crate and does not implement `Serialize` and `Deserialize`. I wan to skip it like so:

```
#[derive(Serialize, Deserialize)]
pub struct CSSColor {
    #[serde(skip_serializing, skip_deserializing)]
    pub parsed: cssparser::Color,  // This is from third party crate and I don't want to implement Serialize/Deserialize for it.
    pub authored: Option<String>,  // This is ok, I want to derive it
}
``` 

But even with `#[serde(skip_serializing, skip_deserializing)]` I still get the following error:

```
the trait `serde::Serialize` is not implemented for `cssparser::Color`
the trait `serde::Deserialize` is not implemented for `cssparser::Color`
```

Can we make `skip_serializing` and `skip_deserializing` ignore the trait bound?

**Comment by dtolnay** [comment]
I was not able to reproduce this with the following code. Based on [this rustdoc](https://docs.rs/cssparser/0.7.1/cssparser/enum.Color.html) it seems like you might be misreading the error message - `Default` is not implemented for `cssparser::Color`. Take a look at [this page](https://serde.rs/attr-default.html) to see various options for deserializing default values for a field.

```rust
#![feature(proc_macro)]

#[macro_use]
extern crate serde_derive;

extern crate serde;

mod cssparser {
    #[derive(Default)]
    pub struct Color;
}

#[derive(Serialize, Deserialize)]
pub struct CSSColor {
    #[serde(skip_serializing, skip_deserializing)]
    pub parsed: cssparser::Color,
    pub authored: Option<String>,
}

fn main() {}
```
