### ISSUE TITLE
Attribute skip_(de)serializing for enum variants

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#638]
```rust
#[derive(Serialize, Deserialize)]
enum E {
    A,
    B,
    #[serde(skip_serializing, skip_deserializing)]
    C,
}
```

When serializing, it should error when the value is that variant. When deserializing, it should be like the variant doesn't exist.

**Comment by dtolnay** [comment]
#641 handles `skip_deserializing`. We still need to do `skip_serializing`.

**Comment by shinglyu** [comment]
This is what I get so far: https://github.com/serde-rs/serde/compare/master...shinglyu:skip_se#diff-3ffa97289153ae55d850a4b1effa6225R256

But I don't know how to get the name `Error` into this file. I suppose I have to `extern crate serde` in `serde_codegen/src/lib.rs`, but I got 

```
   Compiling serde_codegen v0.8.20 (file:///home/shinglyu/workspace/serde/serde_codegen)
error[E0463]: can't find crate for `serde`
  --> /home/shinglyu/workspace/serde/serde_codegen/src/lib.rs:22:1
   |
22 | extern crate serde;
   | ^^^^^^^^^^^^^^^^^^^ can't find crate
```

**Comment by shinglyu** [comment]
Oh I fixed it! Now I just need to clean up the unit test then we are ready for review!

**Comment by dtolnay** [comment]
I filed https://github.com/serde-rs/serde-rs.github.io/issues/31 to remember to document these on the website.
