### ISSUE TITLE
serde-derive does not compile on rustc nightly

### ISSUE THREAD

**Issue by maghoff** [serde-rs/serde#640]
When attempting to follow the [instructions for using serde_derive](https://serde.rs/codegen-nightly.html) with Macros 1.1, I get stranded on the following compile time errors:

```
   Compiling serde_derive v0.8.19
error: attribute must only have one argument
 --> /home/mag/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_derive-0.8.19/src/lib.rs:9:3
  |
9 | #[proc_macro_derive(Serialize, attributes(serde))]
  |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: attribute must only have one argument
  --> /home/mag/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_derive-0.8.19/src/lib.rs:17:3
   |
17 | #[proc_macro_derive(Deserialize, attributes(serde))]
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 2 previous errors

Build failed, waiting for other jobs to finish...
error: Could not compile `serde_derive`.

To learn more, run the command again with --verbose.
```

I can get it working if I downgrade to serde-derive 0.8.17 and rustc nightly-2016-11-06.

I suspect there is something else I should be doing instead, but I am unable to figure it out. Perhaps this other thing should be specified in the documentation I linked above? (That is, <https://serde.rs/codegen-nightly.html>)

**Comment by dtolnay** [comment]
Are you using the most recent nightly? You should be seeing:

```
$ rustc --version
rustc 1.15.0-nightly (daf8c1dfc 2016-12-05)
```

**Comment by maghoff** [comment]
Oh, my, I was certain that I _did_ have the most recent nightly, but I had not understood how rustup works. Updating to the most recent nightly makes it work with the most recent serde_derive.

Thanks, and sorry for the bother! :)
