### ISSUE TITLE
Add a "Discard" type

### ISSUE THREAD

**Issue by mitsuhiko** [serde-rs/serde#643]
I'm currently encountering the issue that I want to selectively discard data of maps. Effectively I have a deeply nested JSON structure and at one point all I care about is the keys of a map but not the values. So ideally one could use something like a `serde::Discard` as a stand-in that's implemented similarly to `serde_json::Value` but completely discards all values while still parsing correctly.

**Comment by oli-obk** [comment]
this could also just be a helper function for `deserialize_with` #553

**Comment by dtolnay** [comment]
This exists as [`serde::de::impls::IgnoredAny`](https://docs.serde.rs/serde/de/impls/struct.IgnoredAny.html).

**Comment by dtolnay** [comment]
Closing because I see you used IgnoredAny in https://github.com/mitsuhiko/rust-sourcemap/commit/a665671e71f70b01edce1d0afc2ea9622621d79f.

**Comment by mitsuhiko** [comment]
Sorry yeah, forgot to reply to this. Completely missed it in the docs. Thanks!
