### ISSUE TITLE
Abstract over formats that deal with bytes

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#644]
Currently there is no way to abstract over different data formats that convert Serialize -> bytes and bytes -> Deserialize. This is a common API for Serde data formats (but not all of them). It may be useful to have something like:

```rust
trait ByteSerializer: Serializer {
    fn to_writer<W, T: ?Sized>(writer: W, value: &T) -> Result<(), Self::Error>
        where W: Write, T: Serialize;

    fn to_string<T: ?Sized>(value: &T) -> Result<String, Self::Error>
        where T: Serialize
    { /* default implementation */ }
    fn to_bytes<T: ?Sized>(value: &T) -> Result<Vec<u8>, Self::Error>
        where T: Serialize
    { /* default implementation */ }
}

trait ByteDeserializer: Deserializer {
    fn from_reader<R, T>(reader: R) -> Result<T, Self::Error>
        where R: Read, T: Deserialize;

    fn from_str<T>(s: &str) -> Result<T, Self::Error>
        where T: Deserialize
    { /* default implementation */ }
    fn from_bytes<T>(v: &[u8]) -> Result<T, Self::Error>
        where T: Deserialize
    { /* default implementation */ }
}
```

**Comment by dtolnay** [comment]
As an example of a Serializer and Deserializer that would not implement these traits: [`serde_json::value::Serializer`](https://docs.serde.rs/serde_json/value/struct.Serializer.html) and [`serde_json::value::Deserializer`](https://docs.serde.rs/serde_json/value/struct.Deserializer.html). These deal with Serialize -> serde_json::Value and serde_json::Value -> Deserialize, rather than with bytes.

**Comment by dtolnay** [comment]
I tried writing some code against this and I don't think we have the right approach yet. The motivation for this issue was to enable abstractions like the following:

```rust
pub struct OnDisk<T, S, D> {
    file: File,
    ty: PhantomData<T>,
    ser: PhantomData<S>,
    de: PhantomData<D>,
}

impl<T, S, D> OnDisk<T, S, D>
    where T: Serialize + Deserialize,
          S: ByteSerializer,
          D: ByteDeserializer
{
    pub fn new<P: AsRef<Path>>(path: P) -> Result<Self, io::Error> {
        Ok(OnDisk {
            file: File::open(path)?,
            ty: PhantomData,
            ser: PhantomData,
            de: PhantomData,
        })
    }
    pub fn write(&mut self, data: &T) -> Result<(), S::Error> {
        self.file.set_len(0).unwrap();
        S::to_writer(&mut self.file, data)
    }
    pub fn read(&mut self) -> StdResult<T, D::Error> {
        self.file.seek(SeekFrom::Start(0)).unwrap();
        D::from_reader(&mut self.file)
    }
}

let path = "/tmp/vec";
let mut on_disk_vec = OnDisk::<...>::new(path)?;

let data = vec![1, 2, 3];
on_disk_vec.write(&data)?;
let data2 = on_disk_vec.read()?;
```

Unfortunately it is pretty awful to use. The ellipses is:

```rust
OnDisk::<_, &mut serde_json::Serializer<File>, &mut serde_json::Deserializer<io::Bytes<File>>>::new(path)
```

All we really want to say is "store the data as JSON." Ideally I would like to aim for something more like this:

```rust
let mut on_disk_vec = OnDisk::<_, serde_json::Format>::new(path)
```

```rust
trait serde::Format {
    // to_writer
    // to_string
    // to_bytes
    // from_reader
    // from_str
    // from_bytes
}

enum serde_json::Format {} // void type just for this purpose
```

One other thing I would like to address is whether these methods should take `&self`. Hypothetically if the JSON serializer let you configure the number of spaces for indentation, is 2-space JSON a different format from 4-space JSON or are they different instantiations of the same format? My inclination is no `&self` so they would be different formats, but happy to hear opinions.

**Comment by dtolnay** [comment]
This needs more discussion and experimentation so I am unscheduling it from 0.9.0.

**Comment by tikue** [comment]
My intuition: 2-space and 4-space json does not a different format make. Is there some technical wrinkle that leads you to believe otherwise?

**Comment by dtolnay** [comment]
@tikue not a technical wrinkle but a usability wrinkle. Having a &self parameter requires every user's code to pass around a parameter holding the configuration of the format they are dealing with, when the fact is almost nobody ever cares. If we omit a &self parameter then the <1% of users who care for configuration can define their own format that bakes in whatever configuration they want.

**Comment by tikue** [comment]
Another case where it matters is bincode, which has a `SizeLimit` parameter.

**Comment by dtolnay** [comment]
One thing that hasn't come up yet is this new API will need to support DeserializeSeed, not just Deserialize. See #282 for that discussion.

**Comment by cjhowe** [comment]
> Having a &self parameter requires every user's code to pass around a parameter holding the configuration of the format they are dealing with, when the fact is almost nobody ever cares.

This sounds like an ideal use for the `Default` trait. I think we could have a trait with methods that take the `self` parameter, and then have a separate, automatically implemented trait with functions that uses `Default` to automatically create the configuration and call the first trait's methods. I guess that'd look something like this:

```
trait ByteSerializerCfg: Serializer {
    fn to_writer_cfg<W, T: ?Sized>(&self, writer: W, value: &T) -> Result<(), Self::Error>
        where W: Write, T: Serialize;

    fn to_string_cfg<T: ?Sized>(&self, value: &T) -> Result<String, Self::Error>
        where T: Serialize
    { /* default implementation */ }
    fn to_bytes_cfg<T: ?Sized>(&self, value: &T) -> Result<Vec<u8>, Self::Error>
        where T: Serialize
    { /* default implementation */ }
}

trait ByteSerializer {
    fn to_writer<W, T: ?Sized>(writer: W, value: &T) -> Result<(), Self::Error>
        where W: Write, T: Serialize;
    fn to_string<T: ?Sized>(value: &T) -> Result<String, Self::Error>
        where T: Serialize;
    fn to_bytes<T: ?Sized>(value: &T) -> Result<Vec<u8>, Self::Error>
        where T: Serialize;
}

impl<T: ByteSerializerCfg + Default> ByteSerializer for T {
    fn to_writer<W, T: ?Sized>(writer: W, value: &T) -> Result<(), Self::Error>
        where W: Write, T: Serialize {
        let s: Self = Default::default();
        s.to_writer_cfg(writer, value)
    }

    fn to_string<T: ?Sized>(value: &T) -> Result<String, Self::Error>
        where T: Serialize {
        let s: Self = Default::default();
        s.to_string_cfg(writer, value)
    }

    fn to_bytes<T: ?Sized>(value: &T) -> Result<Vec<u8>, Self::Error>
        where T: Serialize {
        let s: Self = Default::default();
        s.to_bytes_cfg(writer, value)
    }
}
```

I know this kind of solution increases the API surface, but no one is going to have to implement the `ByteSerializer` trait in this example, and most users would want to use that trait. I think it makes sense to make the easy case easy, and the hard case possible. Is this kind of solution feasible?

**Comment by dtolnay** [comment]
I am unscheduling this from 1.0 because I want to get some experience with Deserialize\<'de> before settling on an API here. In particular, the big question is which of these methods to have:

```rust
fn from_reader<R, T>(&self, reader: R) -> Result<T, Self::Error>
    where R: io::Read,
          T: DeserializeOwned;

fn from_reader<'de, R, T>(&self, reader: R) -> Result<T, Self::Error>
    where R: io::Read,
          T: Deserialize<'de>;
```

The first one is usually what you want because when deserializing from an IO stream you never want T to contain &str or similar. You want to find that out at compile time rather than try to deserialize &str and have it always fail.

The second one possibly may be useful in rare cases. For example if T is the following struct, deserializing from an IO stream could succeed:

```rust
#[derive(Deserialize)]
struct S<'a> {
    #[serde(borrow)]
    cow: Cow<'a, str>,
}

**Comment by dtolnay** [comment]
I would prefer for these traits to be provided outside of Serde by a different crate -- with optional dependencies on each data format that it wants to support.

```toml
[dependencies]
serde_cbor_0_9 = { package = "serde_cbor", version = "0.9", optional = true }
serde_json_1 = { package = "serde_json", version = "1.0", optional = true }
serde_yaml_0_8 = { package = "serde_yaml", version = "0.8", optional = true }
```
