### ISSUE TITLE
Stateful deserialization

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#650]
In many places the current Serde API has reasonable support for deserializing in a stateful way - where the deserialization depends on some data structure that previously exists. As a concrete example the following code deserializes a JSON array into a preallocated slice. Something similar could be useful in a time series database that wants to reuse a single buffer rather than allocating a new Vec for each array in the input.

```rust
extern crate serde;
extern crate serde_json;

use serde::de::{Deserialize, Deserializer, Visitor, SeqVisitor};

fn main() {
    let j = "[10, 20, 30]";
    let mut vec = vec![0; 5];

    deserialize_into_slice(&mut vec, j).unwrap();

    println!("{:?}", vec); // [10, 20, 30, 0, 0]
}

fn deserialize_into_slice<T>(out: &mut [T], j: &str) -> Result<(), serde_json::Error>
    where T: Deserialize
{
    struct IntoSlice<'a, T: 'a>(&'a mut [T]);

    impl<'a, T> Visitor for IntoSlice<'a, T>
        where T: Deserialize
    {
        type Value = ();

        fn visit_seq<V>(&mut self, mut visitor: V) -> Result<Self::Value, V::Error>
            where V: SeqVisitor
        {
            let mut iter = self.0.iter_mut();
            while let Some(elem) = visitor.visit()? {
                iter.next().map(|spot| *spot = elem);
            }
            visitor.end()
        }
    }

    let mut deserializer = serde_json::Deserializer::new(j.bytes().map(Ok));
    deserializer.deserialize_seq(IntoSlice(out))
}
```

In other places the support is a lot worse. Some libraries ([serde-transcode](https://github.com/sfackler/serde-transcode), [erased-serde](https://github.com/dtolnay/erased-serde)) are able to work around the limitations by using a thread_local stack to pass state into Deserialize::deserialize but this is confusing and unsafe.

Let's see if we can come up with an API that supports stateful use case in a better way. It may even be possible to prototype a solution as a helper crate which uses thread_local behind the scenes.

CC @sfackler who has been hoping for progress on this.

**Comment by sfackler** [comment]
This would also enable things like

```rust
#[derive(Deserialize)]
struct Foo {
    #[serde(deserialize_keys_using = "key_deserializer")]
    bar: Map<String, String>,
}

fn key_deserializer<D>(d: &mut D) -> Result<String, D::Error>
    where D: Deserializer
{
    // ...
}
```

**Comment by dtolnay** [comment]
This may be as simple as any place we do `fn<T: Deserialize>(...) -> Result<T>`, instead doing `fn<X: DeserializeState>(x: X, ...) -> Result<X::Value>`.

Then providing:

```rust
pub use std::marker::PhantomData as Stateless;

impl<T> DeserializeState for Stateless<T>
    where T: Deserialize
{
    type Value = T;

    fn deserialize<D>(self, deserializer: &mut D) -> Result<Self::Value, D::Error>
        where D: Deserializer
    {
        T::deserialize(deserializer)
    }
}
```

**Comment by sfackler** [comment]
Yep, that's about it I think. I'm writing up a quick `serde-stateful-deserialize` crate right now and I think all it is is the trait definition, that, and a proxy object to use with current serde.

**Comment by sfackler** [comment]
https://github.com/sfackler/serde-stateful-deserialize

**Comment by sfackler** [comment]
Ok, implementation is actually pretty simple! https://github.com/sfackler/serde-stateful-deserialize/blob/master/src/lib.rs

**Comment by sfackler** [comment]
Using it in serde-transcode: https://github.com/sfackler/serde-transcode/commit/16b770e3c8637875a45e62c38b6c914911907276

**Comment by dtolnay** [comment]
I updated erased-serde: https://github.com/dtolnay/erased-serde/commit/d3ac4bbf84606c26a8482404667ba508cdbc1e95. It compiles but the tests fail, still investigating. I think I actually rely on there being a stack of states rather than a single one at a time.

**Comment by sfackler** [comment]
I though I could get away with not needing an explicit stack since the states should be moved out immediately, but that could be wrong?

**Comment by dtolnay** [comment]
In any case, it's only broken because of the thread_local hack and it would definitely work fine if this were the actual SeqVisitor / MapVisitor API. So far this seems like a promising direction.

The next step is to mitigate the damage as much as possible given that the vast majority of calls are going to be with stateless Deserialize.

**Comment by dtolnay** [comment]
The best name I have so far is `Seed` which is more concise and also more evocative than DeserializeState. It means seed in the same sense that PRNGs have a seed - some initial state that exists before you start using the thing. Also google search for `serde state` returns a bunch of unrelated results, especially since we already  used the word "state" in the Serializer. Google search for `serde seed` returns low-quality results which means it will be easy to search for after we add it.

For the stateless case I like `Scratch` which means deserialize the thing "from scratch" without relying on any pre-existing state. Is this usage confusing for non-native english speakers? `Void` could also be good although it is used by the void crate. That may be less of a concern now that `!` exists and pretty much supercedes `Void`.

Any other suggestions?

**Comment by alexbool** [comment]
I personally find `Seed` and `Scratch` too confusing initially. `DeserializeState ` is more verbose, but more straightforward as well

**Comment by dtolnay** [comment]
How about `Initializer` + `Stateless` or `Factory` + `Stateless`?

Is it better to scrap the Stateless / Scratch / Void idea and ask people to pass PhantomData directly?

**Comment by dtolnay** [comment]
Reopening while I confirm that things get inlined properly and this does not affect benchmarks.

**Comment by dtolnay** [comment]
Ah it is consistently 2-5% slower @oli-obk. That was unexpected. I will investigate.

Or we fix https://github.com/serde-rs/json/issues/184 which is a 5% improvement and call it even :stuck_out_tongue:.

**Comment by dtolnay** [comment]
Oh it is missing #[inline] on `<PhantomData<T> as DeserializeSeed>::deserialize`... I bet that is the difference. Confirming now.

**Comment by dtolnay** [comment]
That was it. I added #[inline] in https://github.com/serde-rs/serde/pull/705 and now performance is identical before and after.
