### ISSUE TITLE
Enforce correct use of Serialize and Deserialize traits

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#651]
Currently the responsibilities of these traits are:

- **Serialize** - make exactly one primitive Serializer call or exactly one chain of begin/elt/end complex Serializer calls
- **Deserialize** - make exactly one Deserializer call

But the type system does not enforce this in either case - you can make zero or more than one call. The result will be a correctly-written Serializer generating invalid output or a correctly-written Deserializer accepting invalid input / rejecting valid input.

Let's see if we can foolproof these.

**Comment by oli-obk** [comment]
If we change the `Serialize` trait to take a `SerializerRef` object that is consumed instead of taking references (and internally has a reference to the actual Serializer) we might be able to enforce it through ownership

**Comment by dtolnay** [comment]
Yep ownership can help enforce <=1 call. For deserialization I would also like to enforce >=1 call i.e. forbid a Deserialize implementation that just returns Ok(Self) without invoking the Deserializer. And for serialization I would like to enforce >=1 call in order to return Ok (should be fine to Err immediately without serializing anything).

**Comment by dtolnay** [comment]
<=1 call turned out to be quite easy on the Deserializer side - just change every method to take `self` instead of `&mut self` and implement Deserializer for `&'a mut JsonDeserializer` instead of for `JsonDeserializer`.

More complicated on the Serializer side because of how we do seq / seq_elt / seq_end. They could shuffle ownership of the Serializer into the SeqState object but that raises the complexity for Serializer implementers...

This commit https://github.com/servo/rust-url/pull/252/commits/ad8d172b7e220a752003d259d507ba7eb9d9d23d is an example of what I would like to prevent.

**Comment by dtolnay** [comment]
Here is a Serializer API that can only be used correctly. Still need to benchmark and mitigate any performance impact.

```rust
pub trait Serializer {
    /// Everybody set Ok = ().
    type Ok;
    type Error: Error;
    type SerializeSeq: SerializeSeq<Ok = Self::Ok, Error = Self::Error>;
    fn serialize_u8(self, v: u8) -> Result<Self::Ok, Self::Error>;
    fn serialize_seq(self, len: Option<usize>) -> Result<Self::SerializeSeq, Self::Error>;
}

pub trait SerializeSeq {
    type Ok;
    type Error: Error;
    fn serialize_elt<T: Serialize>(&mut self, value: T) -> Result<(), Self::Error>;
    fn serialize_end(self) -> Result<Self::Ok, Self::Error>;
}

pub trait Serialize {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
        where S: Serializer;
}
```

Example:

```rust
impl<T> Serialize for Vec<T>
    where T: Serialize
{
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
        where S: Serializer
    {
        let mut seq = serializer.serialize_seq(Some(self.len()))?;
        for elt in self {
            seq.serialize_elt(elt)?;
        }
        seq.serialize_end()
    }
}
```

**Comment by dtolnay** [comment]
I implemented the Serializer side of this in #687 and the Deserializer side in #686. I updated serde_json in https://github.com/serde-rs/json/pull/185 and confirmed there is no performance difference.

**Comment by oli-obk** [comment]
Great job, this turned out much better than anticipated. I think this much more teachable, too, because one needs way fewer hacks

**Comment by oli-obk** [comment]
We still have one case: `MapSerializer::serialize_map_value` can be called before `MapSerialize::serialize_map_key`, in fact, these can be called in arbitrary orders and counts.

**Comment by dtolnay** [comment]
Any ideas?

```rust
let mut map = serializer.serialize_map(Some(self.len()))?;
for (k, v) in self {
    let map = map.serialize_key(k)?.serialize_value(v)?;
}
map.end()
```

I am a lot less concerned about this case than I was about [abuse](https://github.com/servo/rust-url/pull/252/commits/ad8d172b7e220a752003d259d507ba7eb9d9d23d) and forgetting to call `end()` so it would be nice to solve but I don't think we necessarily need to.

**Comment by oli-obk** [comment]
sounds good to me. a `#[must_use]` on the `MapValueSerializer` (and all other serializers) would probably be smart, too, what do you think?

**Comment by oli-obk** [comment]
Becomes to unwieldly. We'll just lint it from clippy.
