### ISSUE TITLE
Ability to add default serialize/deserialize trait without derive

### ISSUE THREAD

**Issue by zbraniecki** [serde-rs/serde#659]
I have a use case where I want to provide multiple different serialization strategies (preferably at runtime).

In the ideal scenario, I'd like to have a single AST and depending on some variable in my program use one of multiple serialization/deserialization strategies.

At the moment the only thing I found is that I can use `cfg` compiler argument to conditionally include one mod or another.

In result, I have `ast.rs` which does not have `serde` dependency, and then I have two different `json.rs` - one with custom `Serializer` and `Deserializer` traits, and the other should use exactly the same strategy as the defaults from `#[derive(Serialize, Deserialize)]` use.

Is there a way to expose those so that I can just link those strategies without having to use `derive` directive?

And side note - what would be the canonical rust/serde way of selecting one of the two serialization strategies?

**Comment by dtolnay** [comment]
`cfg_attr` could be useful here: https://doc.rust-lang.org/book/conditional-compilation.html#cfg_attr

```rust
#[cfg_attr(feature = "strategy-normal", derive(Serialize, Deserialize))]
struct S {
    /* ... */
}

#[cfg(feature = "strategy-compact")]
impl Serialize for S { /* ... */ }
#[cfg(feature = "strategy-compact")]
impl Deserialize for S { /* ... */ }

#[cfg(feature = "strategy-verbose")]
impl Serialize for S { /* ... */ }
#[cfg(feature = "strategy-verbose")]
impl Deserialize for S { /* ... */ }
```

**Comment by dtolnay** [comment]
The canonical rust/serde way of selecting a strategy is going to depend on how the strategy is chosen.

If the crates that depend on your crate choose the strategy, I would say the above with cfg/cfg_attr is canonical.

If your crate chooses the strategy by running some logic, then the above in combination with [cargo:rustc-cfg outputs from build.rs](http://doc.crates.io/build-script.html#outputs-of-the-build-script).

If your crate chooses the strategy based on user input at runtime, something like:

```rust
// set at runtime
static STRATEGY: Strategy = Strategy::Normal;

enum Strategy {
    Normal,
    Verbose,
}

trait SerializeVerbose {
    fn serialize_verbose<S>(&self, serializer: &mut S) -> Result<(), S::Error>
        where S: Serializer;
}

trait DeserializeVerbose: Sized {
    fn deserialize_verbose<D>(deserializer: &mut D) -> Result<Self, D::Error>
        where D: Deserializer;
}

struct Wrapper<T>(T);

impl<T> Serialize for Wrapper<T>
    where T: Serialize + SerializeVerbose
{
    fn serialize<S>(&self, serializer: &mut S) -> Result<(), S::Error>
        where S: Serializer
    {
        match STRATEGY {
            Strategy::Normal => self.0.serialize(serializer),
            Strategy::Verbose => self.0.serialize_verbose(serializer),
        }
    }
}

impl<T> Deserialize for Wrapper<T>
    where T: Deserialize + DeserializeVerbose
{
    fn deserialize<D>(deserializer: &mut D) -> Result<Self, D::Error>
        where D: Deserializer
    {
        match STRATEGY {
            Strategy::Normal => T::deserialize(deserializer).map(Wrapper),
            Strategy::Verbose => T::deserialize_verbose(deserializer).map(Wrapper),
        }
    }
}
```
