### ISSUE TITLE
JSON deserializer only sees part of object

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#660]
From IRC:

> **\<@ekleog>** (as this was pushed far up the backlog, trying again) Hi! I'm discovering serde, and am hitting a weird issue: the JSON deserializer seems to go through only a part of the json object: http://xelpaste.org/AcA6xy only goes through the "policy" element of the object defined at line 118 (http://xelpaste.org/AcA6xy#L118), would you have any idea why this is happening?

**Comment by dtolnay** [comment]
Looks like there are two things wrong: your FilterVisitor::visit_map is missing v.end() and your JSON is invalid (trailing comma inside "filters").

The end() functions are confusing, easy to get wrong, and give bad error messages. I hope to get rid of them in the next release: https://github.com/serde-rs/serde/issues/656.

**Comment by dtolnay** [comment]
To explain why this went wrong in the way that it did: the v.end() call in FilterVisitor::visit_map is in charge of processing the closing curly brace after `"then": "allow"`. Since the call wasn't there, the curly brace wasn't processed as part of Filter. Instead it was processed as part of Config, ending the deserialization before getting to the filters key.

**Comment by Ekleog** [comment]
Great, thanks! (not having opened this I can't close it, but problem solved, thanks!)
