### ISSUE TITLE
Expose number of variants when serializing enum

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#663]
From IRC:

> **\<cmr>** Hm, this seems problematic. My serializer can't keep unbounded state, but I want to encode enum variant tags with the minimum amount of bytes necessary, using the same representation Rust does ideally.
> **\<cmr>** The obvious approach of using a stack of recent total-number-of-variants is out, but I don't see how else it's possible.
> **\<cmr>** (in fact, afaict, the serializer \*never even has access\* to that information, although the deserializer does.)
> **\<cmr>** in the form of the len of the variants arg to deserialize_enum

cc @cmr

**Comment by dtolnay** [comment]
@cmr I don't have the IRC logs but if I remember correctly, you realized that aiming for an encoding that is "at most as many bytes as Rust" was not feasible because of NonZero-related optimizations such as for Option\<&T>, not to mention https://github.com/rust-lang/rfcs/issues/1230. For just minimizing number of bytes, a variable-length encoding seems like it would be a better approach. The vast majority of enums will use 1 byte.

I am inclined to not make this change, rather than complicating the Serializer interface for this use case. What do you think?

**Comment by 414owen** [comment]
I would quite like to see this reopened!
Yes, you can use variable length ints, but this isn't size-optimal.
Here's a use-case for you:
You're implementing a bit-oriented format, which is not self-describing.
Your tag might require only three bits, and the format dictates that you use only three bits, but without knowing how many variants there are in a type, you cannot implement this format.
