### ISSUE TITLE
Serde 0.9.0

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#668]
I would like to release Serde 0.9.0 some time in the week of 1/15 - 1/21. This is 6 months after the release of 0.8.0 and 2 weeks before the stabilization of Macros 1.1.

Here are the open issues I intend to include in 0.9: https://github.com/serde-rs/serde/milestone/16

Possibly controversially, I would like to raise the minimum supported Rust version to 1.15.0 and drop support for Syntex. Otherwise we will be supporting that mess for a long time.

In between the release and Rust 1.15, we can help the major players update (bincode, msgpack, toml, servo, rusoto) and get the ecosystem in a good place in time for any increase in adoption brought on by Rust 1.15.

Not included in this release are any changes related to specialization, bignums, or object-safety. We can continue working on those in time for a 1.0 release later this year.

**Comment by oli-obk** [comment]
Can't we release after 0.15 so noone needs to use nightly even in the transition period?

**Comment by dtolnay** [comment]
Mainly I am contrasting these two perceptions of Serde:

- "At one point for a period of a week or two, the latest Serde release required a not-yet-stable feature but now that feature is stable and Serde will always work on stable."
- "I tried Serde for the first time and got errors like `the trait serde::ser::Serialize is not implemented for S` even though I did everything right according to the docs and put `#[derive(Serialize)]` on the thing, everything sucks."

The two major non-technical obstacles we need to overcome before 1.0 are "Serde is unstable" and "Serde is confusing." I think given "Serde is unstable now but will be stable in 2 weeks" it is easy to believe "Serde will continue to be stable," whereas given "Serde is busted now but will be less busted in 2 weeks" it is harder to convince someone "Serde will continue being less busted." In that sense the second perception does more lasting damage to our reputation.

Another aspect is support burden. If we are anticipating an increase in adoption, I would rather spend support hours on the interesting new use cases rather than mechanics of why two libraries don't work together in ways that give useless error messages. I think doing the release early will shift the brokenness in the direction that has fewer new users, which is good.

Existing users are not forced to use nightly, they just stay on 0.8 until ready.

I haven't made up my mind yet which way is better, but that is my thought process. Let me know if you have a different point of view.

**Comment by dtolnay** [comment]
Reasonable suggestion from @sfackler:

> would the serde crate itself require 1.15? I think a reasonable approach might be to cut one final release of serde-codegen supporting the serde 0.9 apis with whatever the current syntax is and then abandon it. That'll let people who don't want to jump to 1.15 for whatever reason have a path forward while hopefully not being a huge maintenance burden

I would be comfortable doing that. The serde crate will not require 1.15.

**Comment by dtolnay** [comment]
Here is the 0.9.0 milestone in serde_json: https://github.com/serde-rs/json/milestone/2

**Comment by dtolnay** [comment]
@oli-obk if you have time to review the existing open PRs tonight, I think I can finish all the remaining open serde and serde_json issues tomorrow, do a thorough documentation pass on Monday and release Monday night.

**Comment by oli-obk** [comment]
Sorry. My tablet broke down on Friday, so I won't be able to do much on weekends anymore.

**Comment by dtolnay** [comment]
We're almost there! It looks like all of the planned code changes in both serde and serde_json have been addressed. I have https://github.com/serde-rs/serde/pull/716 and https://github.com/serde-rs/json/pull/210 open but they are minor.

This is a very big release compared to 0.8.0. Everybody please take a few minutes to browse through the docs of the most recent release candidate (which includes the above PRs) and call out any APIs that you would be unhappy supporting for the entire 0.9.x lifecycle.

- https://docs.rs/serde/0.9.0-rc3/serde/
- https://docs.rs/serde_json/0.9.0-rc2/serde_json/

On my end I am going to focus some thought on `serde_json::Value` methods. The new `json!` macro from https://github.com/serde-rs/json/pull/207 makes `serde_json::Value` so incredibly accessible and pleasant that I would like the rest of Value's API to be presentable as well.

Other than that, I scheduled the rest of tonight and most of tomorrow for documentation work. I will revamp all of our rustdoc comments, write usage examples, update the website to use the new API, and write release notes.

**Comment by dtolnay** [comment]
I got through most of the rustdoc I wanted in https://github.com/serde-rs/serde/pull/719 and https://github.com/serde-rs/json/pull/213. JSON needs a bit more attention tomorrow, especially around https://github.com/serde-rs/json/issues/191.

I haven't even started on the website though. @oli-obk if you have time today can you work on translating all of the [example code](https://serde.rs/examples.html) and [this section](https://serde.rs/custom-serialization.html) to the 0.9 APIs? Make a PR with whatever you get through and I can continue in the morning.

**Comment by dtolnay** [comment]
serde 0.9.0 https://github.com/serde-rs/serde/releases/tag/v0.9.0

serde_json 0.9.0 https://github.com/serde-rs/json/releases/tag/v0.9.0
