### ISSUE TITLE
Implementing visitors for a binary format

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#672]
@jbaublitz I noticed your question in IRC and it looks like no one responded at the time:

> **\<jbaublitzzz>** I have a quick question about serde best practices. I've seen very different uses of serde for binary and string deserialization. I'm currently looking to implement binary serialization and deserialization with serde.
> **\<jbaublitzzz>** I need to use a std::io::Cursor to parse a byte stream. currently I'm struggling with the usage of visitors in this context.
> **\<jbaublitzzz>** it seems like to implement a Deserializer to do what I need, I would need to implement a Visitor for every primitive type I want to return.
> **\<jbaublitzzz>** is this the best way to do it in serde?

The main Serde traits are [`Serialize`](https://docs.serde.rs/serde/ser/trait.Serialize.html), [`Deserialize`](https://docs.serde.rs/serde/de/trait.Deserialize.html), [`Serializer`](https://docs.serde.rs/serde/ser/trait.Serializer.html), [`Deserializer`](https://docs.serde.rs/serde/de/trait.Deserializer.html). The first two are implemented by Serde for a bunch of primitive and standard library types like `u8` and `String` and `HashMap` and they are implemented by `#[derive(Serialize, Deserialize)]` for structs and enums in the user's program. Visitors are part of the Deserialize trait - the role of the Deserialize trait is to make an instance of the right Visitor and pass it to the Deserializer. This interaction is explained a bit more on [this page of the docs](https://serde.rs/impl-deserialize.html).

For implementing a format, your job is to implement Serializer and Deserializer. Also there are a few other traits that your Deserializer will be responsible for passing to the user's Visitor.

User / data structure implements:

- Serialize
- Deserialize
- Visitor
- EnumVisitor (this is dumb, 0.9 will have a better approach #521)

You / data format implements:

- Serializer
- Deserializer
- SeqVisitor
- MapVisitor
- VariantVisitor

Most formats will define one of each of these last 5 things. Occasionally it can be helpful to have more than one, for example JSON uses a different Deserializer for processing top-level data (which can be anything) vs map keys (which can only be strings) but that is mainly a performance optimization.

So the answer is **no** you are not responsible for implementing a Visitor for every primitive type you want to return. Those are already implemented by Serde.

There is basically one exception when data formats do implement a Visitor. This is for formats that provide a format-specific data type like [`serde_json::Value`](https://docs.serde.rs/serde_json/value/enum.Value.html). The main purpose of the `serde_json` crate is to provide a *data format* i.e. Serializer and Deserializer implementation, but it also provides a *data type* called Value which is able to represent any valid JSON content. Ordinarily the users of `serde_json` deserialize JSON into their own data types like structs, but they can also choose to deserialize JSON into a Value when they don't know what the data contains and can't map it to a struct. It is not required for data formats to provide a data type like this and most formats (especially binary ones) do not.

I hope this helps! As you can tell, there is a lot of Deserializer documentation left for me to write.

**Comment by jbaublitz** [comment]
Thank you for the explanation! I have two additional questions. One, when will the release come out including the enum deserialization update? The other question is where are the primitive visitors are implemented? I tried importing a visitor that looked promising but it appears that it's a private struct which leads me to believe it's for codegen. Is that correct?

**Comment by dtolnay** [comment]
The tracking issue for the release is #668. We are looking at hopefully the next week or two.

You should not need to import any visitors. If you have an API like `fn from_bytes<T: Deserialize>(bytes: &[u8]) -> Result<T, jbaublitz::Error>` and someone does `let x: u64 = jbaublitz::from_bytes(data)?;` then it will know to use the (private) visitor for u64. [Here](https://docs.rs/bincode/0.6.1/bincode/serde/fn.deserialize.html) is the corresponding function from Bincode as an example.

That function constructs a Deserializer and passes it to T's Deserialize implementation. The Deserialize function constructs a Visitor and passes it back to your Deserializer. Your Deserializer looks at the input data and calls the right Visitor method to create a value of type T.

**Comment by jbaublitz** [comment]
I guess my confusion is I have to implement `Deserialize` in one case in which I cannot derive it. In that case the visitor needs to be constructed and is there any way to use the visitors that have already been implemented by serde outside of codegen?

**Comment by dtolnay** [comment]
Can you explain a bit more about the use case or share your implementation so far? It sounds like you are implementing Deserialize for a type but want to reuse a Visitor from an existing Deserialize implementation. Do I have that right?

Something like this might work:

```rust
struct Even(u64);

impl Deserialize for Even {
    fn deserialize<D>(deserializer: &mut D) -> Result<Self, D::Error>
        where D: Deserializer
    {
        // reuse existing Visitor from the Deserialize implementation of u64
        let number = Deserialize::deserialize(deserializer)?;

        if number % 2 == 0 {
            Ok(Even(number))
        } else {
            Err(Error::custom(format!("{} is not even", number)))
        }
    }
}
```

**Comment by khuey** [comment]
I have a similar issue.  @dtolnay's example in the previous comment doesn't work in general because `Deserialize::deserialize` takes ownership of, not a mutable reference to, the `Deserializer`.  So you can only delegate to an existing visitor this way once.

**Comment by dtolnay** [comment]
@khuey can you explain your use case in more detail? Not being able to read multiple values from the Deserializer in the same Deserialize impl is by design.

**Comment by khuey** [comment]
I suppose one could use a temporary tuple for deserializing multiple members this way.

**Comment by inferiorhumanorgans** [comment]
@dtolnay Unsure if this is entirely related, but I'm working on deserializing JSON data ([Vega graphs](https://vega.github.io/vega/docs/specification/)) where a value may be an array or an object (signal reference or data reference) representing different object types.

Here's a valid example:

``` json
"scales" [
  {
    "domain": [1, 2, 3]
  },
  {
    "domain": {"data": "domain_data", "field": "some_field_name"}
  },
  {
    "domain": {"signal": "height / 3"}
  }
]
```

Which I'd like to represent with a Rust enum like so:
``` rust
struct DataRef {
  data: String,
  field: String, // Or potentially a Field struct representing the input/output pair
}

struct SignalRef {
  name: String
}

enum Domain {
  List(Vec<f64>),
  Data(DataRef),
  Signal(SignalRef),
}
```

My thought process was that the logical approach would be to have the Domain map visitor pass the value to an appropriate deserializer, but I'm not quite sure how to accomplish that.  An alternative is to have the deserializer try each possibility in order, but this is not doable by design (per your comment).

Thoughts?

**Comment by nugend** [comment]
I strongly feel like the overview in the first comment would be very welcome in book's Overview page. It gives a very nice and concise explanation of how the various parts of Serde fit together.
