### ISSUE TITLE
How to handle impossible enum

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#677]
```rust
#[derive(Deserialize)]
enum Impossible {}
```

Should this fail at compile time or generate a Deserialize implementation that always fails at runtime?

**Comment by oli-obk** [comment]
I think we need the impl, because we might have `Vec<Impossible>` or something similar that can be deserialized, but the `Deserialize` impl requires a `Deserialize` impl for the generic type. The same goes for serialization

**Comment by oli-obk** [comment]
alternatively we need to patch all `Vec`, `Option`, ... impls with specialization to allow for the case where we deserialize a `None::<NotDeserializable>`.

**Comment by dtolnay** [comment]
That makes sense. I added some tests of this case in #678.
