### ISSUE TITLE
Move serde into it's own organization

### ISSUE THREAD

**Issue by erickt** [serde-rs/serde#68]
@Byron / @oli-obk / @hugoduncan / @tomprogrammer / @kvark: FYI, if you haven't noticed, serde now has a new github organization. I want to be a little more formal about reviewing my patches with the rest of the serde community.

**Comment by Byron** [comment]
A great move ! This will definitely give it (even) more velocity !
Thank you for taking care !

**Comment by frewsxcv** [comment]
This can be closed, right?

**Comment by erickt** [comment]
Yep!

**Comment by oli-obk** [comment]
do you want serde (de-)serializer-repos in that orga or do you prefer the devs to put them in their own repos?

**Comment by erickt** [comment]
@oli-obk: I'd be happy to have them in serde.rs. Want one for xml? What would you like it called?

@Byron: want one for yaml?

**Comment by oli-obk** [comment]
Just `xml`? Since it'll already be inside the serde-rs orga it doesn't need any annotations like `rust` or `serde`.

**Comment by Byron** [comment]
@erickt Sorry for the late reply. It seems there is a repo for yaml already. Right now I don't know how you see the separation to be done,but I guess I can just look at the json implementation once it is there. In the meanwhile, I will keep working in my fork and communicate through the PR, until there is something usable.

**Comment by oli-obk** [comment]
@Byron: the xml-deserialization is already working as its own repo. Maybe that'll help set it up for yaml.

**Comment by Byron** [comment]
@oli-obk Thank you, I will do that ! I'd still have a lot of questions about how collaboration is supposed to work. Maybe a guide exists somewhere and I didn't find it. For reasons of lazyness, I'd just push to `serde-rs/yaml` directly, without setting up a PR to allow code-reviews. The latter, however, would be good to have, and I would love to get other eyes on the code at least once certain milestones are met. While writing this, I changed my mind and now believe a PR based workflow would be the way to go ... so let's do it that way :).

**Comment by oli-obk** [comment]
technically we should set up homu to get the `r+` abilities

**Comment by oli-obk** [comment]
i am still pushing directly, as it's so early in development, but if you think reviews are better, I can start doing PRs

**Comment by Byron** [comment]
I am not sure who will have time for reviews anyway, however, I just want to get used to that workflow, and if in doubt, will just merge my own PRs.

**Comment by oli-obk** [comment]
we can do mutual reviewing. Not sure how I can set github up to get notifications about PRs though

**Comment by frewsxcv** [comment]
Could just get added as members (not necessarily owners) to a team in the organization and whenever a review needs to happen, just ping the team

**Comment by Byron** [comment]
I agree, this could just work using the `@` syntax to reach out to individuals.

**Comment by oli-obk** [comment]
I put myself on the "watch" thingy next to "fork" and "star" for yaml, maybe it'll work :)
