### ISSUE TITLE
Get rid of ValueDeserializer in favor of implementing Deserializer directly on types

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#693]
I don't think ValueDeserializer is helpful as an abstraction. Nobody is going to write code that accepts `<T: ValueDeserializer>`. A lot of code currently looks like `T::deserialize(s.into_deserializer())` but we should just make it work with `T::deserialize(s)`.

This turned out really nicely in serde_json implementing Deserializer directly on Value: https://github.com/serde-rs/json/commit/7a9514714cb2a6277792402bee50ae6c3f68b30f.

**Comment by oli-obk** [comment]
right, I didn't want to change that, I accidentally wrote `impl Deserializer for Vec<u8>` until I remembered we have `ValueDeserializer`.

**Comment by dtolnay** [comment]
Oh the E type parameter is hard because we would want it to work for any E...

I guess the other two options are:

- providing `struct ValueDeserializer<T, E>(T, PhantomData<E>)` so you do `T::Deserialize(ValueDeserializer::new(s))`
- using a single Error type across all value deserializers

but both of those seem less good. Reopen if you have a better idea or happen to like one of those two!

**Comment by oli-obk** [comment]
I like the 2nd one. We might be able to `impl<E: de::Error> From<value::Error> for E` by using the general methods on `de::Error`.

**Comment by dtolnay** [comment]
Oh if we can do that, it would work as `T::deserialize(s)?` which is pretty nice. Good idea!

**Comment by oli-obk** [comment]
ah no, it can't work, because `value::Error` implements `de::Error` and `From<T>` is implemented for `T`.

**Comment by oli-obk** [comment]
let's ignore this for now ^^
