### ISSUE TITLE
De-duplicate the serializer traits

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#695]
Some of the traits appear to be redundant. For instance SerializeSeq and SerializeTuple are literally exactly the same trait, as are SerializeStruct and SerializeStructVariant.

All we really need are:

- SerializeSeq - serialize_element(T)
- SerializeMap - serialize_key(T) serialize_value(T)
- SerializeStruct - serialize_field(&str, T)

Currently the JSON serializer implements SerializeSeq and then implements SerializeTuple and SerializeTupleStruct to simply forward to SerializeSeq. Sharing the same trait would avoid having to write those forwarding impls.

But there is a tradeoff. The JSON serializer uses a single type `Compound<'a, W, F>` across all seven compound serializers, and it has different behavior for SerializeSeq vs SerializeTupleVariant. If we make those the same trait, JSON would need to implement that trait for two different types in order to preserve the two different behaviors - which involves code duplication and possibly more forwarding functions.

So the current approach with distinct but identical traits is optimized for using the same type but with different behaviors. If you want the same type with the same behavior, you write boilerplate to forward the calls. The de-duplicated approach would be optimized for using the same type with the same behavior. If you want the same type but with different behaviors, you would write boilerplate. Neither approach is strictly better and I think the current approach is the better of the two.

But there might be an even better way. Ideas @oli-obk?

**Comment by oli-obk** [comment]
I also prefer the current approach. JSON is a very simple format, and doesn't differentiate between tuples and sequences. Other formats requiring these differences will need to make runtime decisions if the traits are merged. If we merge these, we might just as well merge the `serialize_seq` and `serialize_tuple` methods, which I think is bad.

**Comment by dtolnay** [comment]
We could possibly provide forwarding implementations in Serde and serde_json could do:

```rust
type SerializeSeq = Compound<'a, W, F>;
type SerializeTuple = ForwardToSerializeSeq<Compound<'a, W, F>>;
type SerializeTupleStruct = ForwardToSerializeSeq<Compound<'a, W, F>>;

fn serialize_tuple(self, len: usize) -> Result<Self::SerializeTuple> {
    self.serialize_seq(Some(len)).map(Into::into)
}
```

**Comment by oli-obk** [comment]
oh... As long as they aren't automatic, we don't want to go back to arbitrary forwarding hell ^^

**Comment by dtolnay** [comment]
Can you explain what you mean? My suggestion would look something like:

```rust
pub struct ForwardToSerializeSeq<T>(T);
impl<T> SerializeTuple for ForwardToSerializeSeq<T> where T: SerializeSeq;
impl<T> SerializeTupleStruct for ForwardToSerializeSeq<T> where T: SerializeSeq;
impl<T> SerializeTupleVariant for ForwardToSerializeSeq<T> where T: SerializeSeq;
impl<T> From<T> for ForwardToSerializeSeq<T> where T: SerializeSeq;

pub struct ForwardToSerializeStruct<T>(T);
impl<T> SerializeStructVariant for ForwardToSerializeStruct<T> where T: SerializeStruct;
impl<T> From<T> for ForwardToSerializeStruct<T> where T: ForwardToSerializeStruct;
```

**Comment by oli-obk** [comment]
That's fine, what I meant was that we shouldn't automatically default to forwarding all methods of `SerializeTupleStruct` to `SerializeTuple` and offer the user the capability to overwrite that default. Your method is completely opt in, so that's fine.

**Comment by dtolnay** [comment]
I believe the code duplication from serializer traits has not been so bad in practice. We can revisit if people begin to complain.
