### ISSUE TITLE
Reconsider MapVisitor::missing_field

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#702]
Out of all the Serde deserializers on GitHub, there are exactly four distinct behaviors for missing_field:

- Unconditionally an error
- For options treat it as None, otherwise error
- Treat it as unit
- [Whatever serde_xml is doing](https://github.com/serde-rs/xml/blob/f9330b703c7405ea8f54e1adfa972cb869924e38/src/de/value.rs#L358-L382)

Ideally I would like to standardize on one of these (my preference is None/error) and remove the ability for deserializers to modify the behavior. This would improve consistency and predictability across the ecosystem.

@oli-obk can you explain the various cases that serde_xml needs to handle in missing_field and whether you can think of any alternative ways to accomplish this?

**Comment by oli-obk** [comment]
mwhaha, `serde_xml` should not be a benchmark of good `Deserializer` design. It's what you'd get if you wrote a test-suite and threw a neural network against it that gets encouraged to pass more tests.

What we do at the location you linked is to rename a field to `$value`, and in case a tag like `<tag>content</tag>` comes along, you end up triggering `missing_field` for the `$value` field and extract "content" to be the value of that field. One would think that a string-newtype or similar could also suffice, but we can also have `<tag attr="foo">content</tag>`, where we need a field named `attr`.

Mapping xml schemata to Rust types is a nightmare, the experiment is a failure in my opinion. It's not serde's fault, it's just that xml schemata have many weird things that basically only work with object oriented systems with inheritance.

**Comment by dtolnay** [comment]
What would serde_xml do if we take away missing_field?

**Comment by oli-obk** [comment]
Probably match on an error

**Comment by oli-obk** [comment]
And use a seed

**Comment by dtolnay** [comment]
Let's do that then. I think this would be a net benefit for every other use case except serde_xml. We replace the three different behaviors with one consistent approach and no longer need this awkwardly placed API. What do you think?

We would still need to settle which behavior to use:

- For options treat missing field as None, otherwise error
- Treat missing field as unit

In practice this matters most for collection types like Vec\<T>. The first one makes it an error, the second one makes it empty vec. I prefer the first approach and if you want the second behavior you can either put #[serde(default)] on the vec field or use Option\<Vec\<T>>.

In theory we could also unconditionally make missing field an error, and require #[serde(default)] on Option\<T> fields to make it None. That seems excessive to me. Option is already a special case in the Serializer and Deserializer traits and it seems pretty intuitive that if your field is optional and it isn't there then it is None.

**Comment by oli-obk** [comment]
> In theory we could also unconditionally make missing field an error, and require #[serde(default)] on Option<T> fields to make it None. That seems excessive to me. Option is already a special case in the Serializer and Deserializer traits and it seems pretty intuitive that if your field is optional and it isn't there then it is None.

I agree, let's make `Option` special and require `#[serde(default)]` for everything else. If we notice certain types getting excessive use of `#[serde(default)]`, we can revisit this.
