### ISSUE TITLE
Documenting serde types

### ISSUE THREAD

**Issue by radix** [serde-rs/serde#712]
Hi, I'm using Serde to define a web API that uses JSON, and I'm trying to figure out how to generate documentation for it. Have there been any thought about generating documentation that describes the serialization format that a type will have?

I realize that this would be specific to a particular serde backend (like JSON or YAML).

I'm not very familiar with item attributes, but maybe it would be possible to automatically add item attributes to structs / fields & enums / variants that describes their serialization format with a given backend, which a tool could then parse out?

**Comment by oli-obk** [comment]
related to #345 and #552. Once we have such an API, we could use it to allow backends to generate documentation.

**Comment by radix** [comment]
FWIW I think I would be satisfied with just #345, so you may close this if you want. I'm not sure what documentation would be generated other than the schema (and I really should have thought to search the issue tracker for "schema" before filing this bug).

**Comment by dtolnay** [comment]
Let's track this as part of the schema work. I dropped a link to this issue in that discussion.
