### ISSUE TITLE
Can't build serde-derive

### ISSUE THREAD

**Issue by johalun** [serde-rs/serde#714]
Getting lot's of these errors recent couple of days

add #![(feature(proc_macro)] to enable....

**Comment by dtolnay** [comment]
You need a newer compiler of either beta or nightly channel. You should be seeing one of these from `rustc --version`:

```
rustc 1.15.0-beta.5 (10893a9a3 2017-01-19)
rustc 1.16.0-nightly (9761b17d5 2017-01-21)
```

**Comment by johalun** [comment]
Thanks!
