### ISSUE TITLE
Remove usize and isize from Serializer, Deserializer, Visitor

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#718]
Why do we need usize and isize as types in our data model? Can we get away with just the specific bit width types? For the most part data formats just treat these as u64 and i64 right?

**Comment by oli-obk** [comment]
That would probably be better. Apparently we will never (for reasonable definitions of "never") get a `usize` that is bigger than 64 bits

**Comment by dtolnay** [comment]
@oli-obk how would you feel about squeezing this into 0.9?

One thing we still need to settle is the convention for deserializing enum variants by index, which currently uses usize. I guess `visit_u32`?
