### ISSUE TITLE
error: attribute must only have one argument

### ISSUE THREAD

**Issue by Silberling** [serde-rs/serde#732]
I am new to rust and trying to build the example from README.md.
I assume the example is correct, so there must be a problem somewhere and I can't figure it out.

    [package]
    name = "rust_playground_serde"
    version = "0.1.0"
    authors = ["User <user@localhost>"]

    [dependencies]
    serde_derive = "*"
    serde_json = "*"

    user@computer ~/RustPlayground/Serde> cargo build
        Updating registry `https://github.com/rust-lang/crates.io-index`
     Downloading serde_derive v0.9.4
     Downloading serde_json v0.9.2
     Downloading quote v0.3.12
     Downloading syn v0.11.4
     Downloading serde_codegen_internals v0.12.0
     Downloading unicode-xid v0.0.4
     Downloading dtoa v0.3.1
     Downloading itoa v0.2.1
       Compiling itoa v0.2.1
       Compiling serde v0.9.4
       Compiling dtoa v0.3.1
       Compiling num-traits v0.1.36
       Compiling quote v0.3.12
       Compiling unicode-xid v0.0.4
       Compiling syn v0.11.4
       Compiling serde_codegen_internals v0.12.0
       Compiling serde_json v0.9.2
       Compiling serde_derive v0.9.4
    error: attribute must only have one argument
      --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_derive-0.9.4/src/lib.rs:22:3
       |
    22 | #[proc_macro_derive(Serialize, attributes(serde))]
       |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    error: attribute must only have one argument
      --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_derive-0.9.4/src/lib.rs:31:3
       |
    31 | #[proc_macro_derive(Deserialize, attributes(serde))]
       |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    error: the `proc-macro` crate type is experimental
      |
      = help: add #![feature(proc_macro)] to the crate attributes to enable

    error: the `#[proc_macro_derive]` attribute is an experimental feature (see issue #35900)
      --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_derive-0.9.4/src/lib.rs:22:1
       |
    22 | #[proc_macro_derive(Serialize, attributes(serde))]
       | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    error: the `#[proc_macro_derive]` attribute is an experimental feature (see issue #35900)
      --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_derive-0.9.4/src/lib.rs:31:1
       |
    31 | #[proc_macro_derive(Deserialize, attributes(serde))]
       | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    error: aborting due to 2 previous errors

rustc 1.14.0

**Comment by dtolnay** [comment]
The example requires rustc 1.15.0 which is currently the beta channel. See [the book](https://doc.rust-lang.org/book/release-channels.html) for more about release channels. Rust 1.15.0 is going to be released this week on Thursday so unfortunately all of our examples are in flux right now as we prepare for that release.

For now you can use [`rustup`](https://rustup.rs/) to build the example using the beta compiler:

```
$ rustup install beta
$ cd rust_playground_serde && cargo +beta build
```

And when the stable 1.15.0 release comes out on Thursday you will be able to use that:

```
$ rustup update stable
$ cd rust_playground_serde && cargo build
```
