### ISSUE TITLE
Sending serialised struct over the wire.

### ISSUE THREAD

**Issue by glennpierce** [serde-rs/serde#734]
Hi

So I have some code that serialises a struct with a containing vec into a byte stream like

ie
let bytes = bincode::serde::serialize(&array, bincode::SizeLimit::Infinite).unwrap();

The idea is to sens this over a tcp socket.

The trouble is when trying to read from the socket I need to know the length of the stream ie

sock_ref.take(msg_len as u64).read(&mut recv_buf)

Does anyone know what the best approach would be ?
Should I use encoded_size and prepend that to the byte stream ?

Thanks

**Comment by dtolnay** [comment]
Bincode does not require you to know the size ahead of time. You should be able to use [`bincode::serde::deserialize_from`](http://tyoverby.com/bincode/bincode/serde/fn.deserialize_from.html) to read straight from the sock_ref without buffering into recv_buf.

```rust
#[macro_use]
extern crate serde_derive;

extern crate bincode;
use bincode::SizeLimit::Infinite;

#[derive(Debug, Serialize, Deserialize)]
struct S {
    vec: Vec<String>,
}

fn main() {
    let s1 = S { vec: vec!["a".to_owned(), "b".to_owned()] };
    let s2 = S { vec: vec!["c".to_owned(), "d".to_owned()] };

    let mut buf = Vec::new();
    bincode::serde::serialize_into(&mut buf, &s1, Infinite).unwrap();
    bincode::serde::serialize_into(&mut buf, &s2, Infinite).unwrap();
    let mut buf: &[u8] = &buf;

    let d1: S = bincode::serde::deserialize_from(&mut buf, Infinite).unwrap();
    println!("{:?}", d1);
    let d2: S = bincode::serde::deserialize_from(&mut buf, Infinite).unwrap();
    println!("{:?}", d2);
}
```

**Comment by glennpierce** [comment]
thanks. Seems to work fine apart from constantly getting ErrorKind::WouldBlock
but that is nothing to do with Serde.

My code for reference is

let sock_ref = <TcpStream as Read>::by_ref(&mut self.sock);

        match bincode::serde::deserialize_from(sock_ref, Infinite) {
        
            Ok(n) => {
                println!("CONN : we read {:?} bytes", n);

                Ok(Some(n))
            }
            Err(DeserializeError::IoError(e)) => {

                if e.kind() == ErrorKind::WouldBlock {
                    error!("CONN : read encountered WouldBlock");
                    Ok(None)
                } else {
                    error!("Failed to read buffer for token {:?}, error: {}", self.token, e);
                    Err(DeserializeError::IoError(e))
                }
            }
            Err(err) => {
                error!("unhandled error: {}", err);
                Err(err)
            } 
        }

**Comment by glennpierce** [comment]
Hmm any idea why the following fails.
The first definition of the array that I commented gets sent over the socket fine.
The second SensorValueArray struct fails to send though.
I get no other errors and the bytes print to console ok.

Thanks

        // let array = S { vec: vec!["a".to_owned(), "b".to_owned(), "a".to_owned(), "b".to_owned(),
        //                           "a".to_owned(), "b".to_owned(),"a".to_owned(), 
        //                           "b".to_owned(),"a".to_owned(), "b".to_owned(),"a".to_owned(), "b".to_owned(),
        //                           "b".to_owned(),"a".to_owned(), "b".to_owned(),"a".to_owned(), "b".to_owned(),
        //                           "b".to_owned(),"a".to_owned(), "b".to_owned(),"a".to_owned(), "b".to_owned(),
        //                           "b".to_owned(),"a".to_owned(), "b".to_owned(),"a".to_owned(), "b".to_owned()] };

        let array = SensorValueArray {
            id: 1,
            values: vec![
                SensorValue {
                    dt: NaiveDateTime::from_timestamp(1485682118, 0),
                    value: 526282.2826,
                },
                SensorValue {
                    dt: NaiveDateTime::from_timestamp(1485682118, 0),
                    value: 8262946352.6,
                },
            ],
        };

        let mut buf = Vec::new();
        bincode::serde::serialize_into(&mut buf, &array, Infinite).unwrap();
        println!("{:?}", buf);
        let mut buf: &[u8] = &buf;

        stream.write_all(buf).unwrap();

**Comment by dtolnay** [comment]
The code you pasted all looks fine. If you can share the whole crate I can try to help debug this.

Does it work if you write to the stream directly?

```rust
bincode::serde::serialize_into(&mut stream, &array, Infinite)
```

**Comment by glennpierce** [comment]
No 

Unfortunately that didn't help.

Interestingly if I have your struct like

#[derive(Debug, Serialize, Deserialize)]
struct S {
    test: u32,
    vec: Vec<String>,    
}

I don't receive anything on the server side. Changing the order of the field like below works.

#[derive(Debug, Serialize, Deserialize)]
struct S {
    vec: Vec<String>,
    test: u32,
}

I say works but on the server end the  deserialize_from call seems to only read
an array of zeros.

I have created a simplified test case at

https://github.com/glennpierce/socket_test


Thanks

**Comment by glennpierce** [comment]
Some progress. On the server I of course needed
pub fn readable(&mut self) -> DeserializeResult<Option<SensorValueArray>> {

not

pub fn readable(&mut self) -> DeserializeResult<Option<Vec<u8>>> {

**Comment by dtolnay** [comment]
I ran `cargo run --bin server` and `cargo run --bin client` and it seems to work perfectly. Sensor value arrays are sent by the client and received by the server as expected. It may be something outside of your code that is causing it to fail (firewall, antivirus etc).

**Comment by glennpierce** [comment]
I updated the code and it started working after I changed the readable function returning
DeserializeResult<Option<Vec<u8>>> to Option<SensorValueArray>

Thanks
