### ISSUE TITLE
Make some of the Content api public

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#741]
Follow-up to #739. After we get a chance to iterate on the implementation of the `untagged` and `tag` attributes, we can start to polish and expose pieces of the implementation because they are definitely useful in other use cases.

**Comment by oli-obk** [comment]
We can get rid of the `E` parameter: https://github.com/serde-rs/serde/commit/6277079152bb933b8ea2a3d6f3d1af5720dac31b

**Comment by dtolnay** [comment]
I think the remaining tasks before we can make this public are:

- Adjacently tagged enums #758
- Integer tags #745
- Error messages #773

Not all of these require obvious breaking changes to Content but I wouldn't want to limit our solution to any of these by committing to a flawed API.

**Comment by dtolnay** [comment]
One nuance here is that it is helpful to have slightly different Content enums when serializing vs when deserializing.

- [`ser::Content`](https://github.com/serde-rs/serde/blob/v0.9.9/serde/src/ser/content.rs#L90-L127)
- [`de::Content`](https://github.com/serde-rs/serde/blob/v0.9.9/serde/src/de/content.rs#L31-L58)

**Comment by dtolnay** [comment]
Let's continue to track this but from the opposite direction -- I filed https://github.com/arcnmx/serde-value/issues/16 to absorb serde-value into the public API of Serde when they are ready for it. I think it will be more productive to polish and iterate on serde-value publicly than to try to get our own implementation right on the first try.

**Comment by slinkydeveloper** [comment]
Hi, any updates on this?

**Comment by Sytten** [comment]
@dtolnay Has the stance changed on that? The currently private `Content` and `ContentRefDeserializer` are very useful. `serde-value` is not really a replacement since the deserializer takes an owned `Value` not a ref.
Is it something you are still looking to make public?

**Comment by dtolnay** [comment]
The fact that no one has made a better serde-value crate is some indication that the use case is not that important. Do you have insight into why that hasn't happened?

Regarding my stance, no change since https://github.com/serde-rs/serde/issues/741#issuecomment-325523577.

**Comment by Sytten** [comment]
Its really only useful for untagged enums so it is probably niche but when you hit the problem there is not good solution except using the private api which I have seen used around since its not really private and people are lazy.

**Comment by murl-digital** [comment]
This is probably a niche use case but I'm using serde_json's Value type to represent valid (but arbritrary) data to store drafts of documents that should eventually deserialize into a struct correctly. Using serde_json's value is kind of gross though, maybe I could spent some time making a more bespoke crate and merge it in?

**Comment by Sytten** [comment]
@murl-digital I would use that, the api is very useful when you have the niche case.

**Comment by lucatrv** [comment]
> The fact that no one has made a better serde-value crate is some indication that the use case is not that important. Do you have insight into why that hasn't happened?

This is still needed, please see issue https://github.com/serde-rs/serde/issues/2780 and new crate https://github.com/rushmorem/serde-content

**Comment by adityashah1212** [comment]
I have an use case for this where I am trying to find unused fields in a flattened struct with prefix. This combination is kind of impossible to do without manually deserializing a serde_value::Value::Map first and then manually sorting through the keys. I know that it is a necessary evil at the moment, but I would have preferred if this was directly possible using serde instead of using serde_value as a separate dependency.
