### ISSUE TITLE
Fancy untagged enum optimizations

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#748]
Consider this enum:

```rust
#[derive(Deserialize)]
#[serde(untagged)]
enum Data {
    Integer(u64),
    Pair(String, String),
}
```

Currently we buffer up the deserializer content, match it against Integer, and match it against Pair.

Theoretically we could turn this into an ordinary Visitor that knows which case it's in without buffering the input. The situation is a bit more complicated if someone has in their module `type u64 = (String, String)` but I think we can ignore that.

Another example:

```rust
#[derive(Deserialize)]
#[serde(untagged)]
enum Data {
    A { x: u8, y: String },
    B { x: u8, z: Box<Data> },
}
```

We can optimize the case where the keys are disjoint across all the variants, or keys with the same name have the same type across all the variants.

Unclear how we determine which patterns are worth optimizing for real use cases. Maybe we just leave these to handwritten Deserialize implementations.

**Comment by bennofs** [comment]
If we implement this, could we perhaps even replace the "internally tagged" enum variant with this + constant fields? So the user can just add an explicit `type = "foo"` constant field to each enum variant, and use the untagged representation, which should be equavilent with this optimization.

Also, I think that this optimization is quite important semantically for the following reason: It allows serde to work better for partly-self-describing formats. Currently, using the "internally tagged" variant requires that all values below that can be deserialized self-describing. With this optimization, in some cases, if a key is unique, you know it's type and can avoid relying on being self describing.

**Comment by dtolnay** [comment]
I would prefer to see a differently optimized Deserialize derive specific to untagged enum provided in a separate crate.

**Comment by roj1512** [comment]
And where is that crate?
