### ISSUE TITLE
How to (de)serialize a tuple struct from json named values instead of an array by serde?

### ISSUE THREAD

**Issue by vityafx** [serde-rs/serde#751]
Current `serde` serialization mechanism does not seem to provide a functionality of (de)serializing a tuple structure from a named values instead of an array. It would be easier to understand  by providing an example (below).

Let's say I have a json object:

    { "min": 2, "max": 15 }

How to  parse it to such tuple struct:

    #[derive(Serialize, Deserialize, Debug)]
    struct TeamSize(pub i64, pub i64);
    #[derive(Serialize, Deserialize, Debug)]
    struct Match {
        size: TeamSize,
    }

The generated (de)serialization mechanism expects the following:

    {"size": [2, 15]}

I've tried to use `serde` derives somehow but they does not work:

    #[derive(Serialize, Deserialize, Debug)]
    pub struct TeamSize(
        #[serde(rename = "min")]
        pub i64,
        #[serde(rename = "max")]
        pub i64
    );

How to parse it? Should I implement everything by myself?

CP: http://stackoverflow.com/questions/42051216/how-to-deserialize-a-tuple-struct-from-json-named-values-instead-of-an-array-b

**Comment by dtolnay** [comment]
As recommended by the StackOverflow answer, I would just adjust TeamSize to match the JSON representation.

If you really need to keep TeamSize as a tuple struct, you can use a separate private helper struct to implement Serialize and Deserialize for TeamSize:

```rust
#[macro_use]
extern crate serde_derive;

extern crate serde;
extern crate serde_json;

use serde::{Serialize, Serializer, Deserialize, Deserializer};

#[derive(Debug)]
pub struct TeamSize(pub i64, pub i64);

#[derive(Serialize, Deserialize, Debug)]
pub struct Match {
    pub size: TeamSize,
}

// private
#[derive(Serialize, Deserialize)]
struct TeamSizeHelper {
    min: i64,
    max: i64,
}

impl Serialize for TeamSize {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
        where S: Serializer
    {
        TeamSizeHelper { min: self.0, max: self.1 }.serialize(serializer)
    }
}

impl Deserialize for TeamSize {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
        where D: Deserializer
    {
        Deserialize::deserialize(deserializer)
            .map(|TeamSizeHelper { min, max }| TeamSize(min, max))
    }
}

fn main() {
    let j = r#" { "size": { "min": 2, "max": 15 } } "#;

    let m: Match = serde_json::from_str(j).unwrap();
    println!("{:?}", m);

    let j = serde_json::to_string(&m).unwrap();
    println!("{}", j);
}
```

**Comment by nalply** [comment]
Note that now you need a lifetime parameter for `Deserialize`, but other than that the trick with the private helper datastructure is genius.
