### ISSUE TITLE
Dynamically set the field name while serializing

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#766]
From IRC:

> **\<platatita>** Hi, I would like to know if I'm able to dynamically set the field name while serializing?
> **\<platatita>** I know that I've the field attribute "#[serde(rename = "name")]" but it sets the const name of the field 
> **\<sfackler>** platatita: how are you deriving the field name?
> **\<platatita>** I'm using the newest version of serde 0.9.7
> **\<platatita>** please have a look at the rust example https://is.gd/MrrtY5
> **\<platatita>** I try to serialize to json the structs
> **\<sarnold>** I'm pretty new to rust and newer still to serde but this feels like a chance to use two fields in a struct, field: Option<Point>, geopoint: Option<GeoPoint>
> **\<platatita>** The location struct is generic and the generic can by any other struct than these two which I mentioned
> **\<sfackler>** platatita: how would you get the field name from the type?
> ~ *platatita quit* ~

cc @platatita

**Comment by dtolnay** [comment]
@platatita from your example code, it seems like you want an enum not a type parameter P. You can read more about enums [here](https://doc.rust-lang.org/book/enums.html).

```rust
#[derive(Serialize)]
enum Location {
    #[serde(rename = "point")]
    Point {
        x: i64,
        y: i64,
    },
    #[serde(rename = "geo_point")]
    GeoPoint {
        lat: i64,
        lon: i64,
    },
}

fn main() {
    let location = Location::Point { x: 0, y: 0 };
    // serialized as `{"point": {"x": 0, "y": 0}}`
    let location = Location::GeoPoint { lat: 0, lon: 0 };
    // serialized as `{"geo_point": {"x": 0, "y": 0}}`
}
```

**Comment by dtolnay** [comment]
Updated requirements: Location actually has more fields https://is.gd/zrKV7h

**Comment by dtolnay** [comment]
Something like this might work - using a trait to set a name for the field.

```rust
#[macro_use]
extern crate serde_derive;

extern crate serde;
extern crate serde_json;

use serde::{Serialize, Serializer};

#[derive(Serialize, Debug, Clone)]
struct Point {
    x: i64,
    y: i64
}

#[derive(Serialize, Debug, Clone)]
struct GeoPoint {
    lan: i64,
    lon: i64
}

#[derive(Debug, Clone)]
struct Location<P> {
    name: String,
    address: String,
    field: P
}

trait LocationKey {
    fn location_key() -> &'static str;
}

impl LocationKey for Point {
    fn location_key() -> &'static str { "point" }
}

impl LocationKey for GeoPoint {
    fn location_key() -> &'static str { "geo_point" }
}

impl<P> Serialize for Location<P>
    where P: LocationKey + Serialize
{
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
        where S: Serializer
    {
        use serde::ser::SerializeMap;
        let mut map = serializer.serialize_map(Some(3))?;
        map.serialize_entry("name", &self.name)?;
        map.serialize_entry("address", &self.address)?;
        map.serialize_entry(P::location_key(), &self.field)?;
        map.end()
    }
}


fn main() {
    let location = Location { name: "some name".to_string(), address: "some address".to_string(), field: Point {x: 0, y: 0} };
    // {"name":"some name","address":"some address","point":{"x":0,"y":0}}
    println!("{}", serde_json::to_string(&location).unwrap());

    let location = Location { name: "some name".to_string(), address: "some address".to_string(), field: GeoPoint {lan: 0, lon: 0} };
    // {"name":"some name","address":"some address","geo_point":{"lan":0,"lon":0}}
    println!("{}", serde_json::to_string(&location).unwrap());
}
```

**Comment by platatita** [comment]
It is what I was looking for. Thx a lot for your help **dtolnay**

**Comment by phayes** [comment]
Would it be possible to re-open this ticket with a request to add this to the documentation?  Including a symmetrical example for deserializing as well?

This seems like a not-uncommon use-case (not super common either I admit). 

Even better would be a new attribute to automate this sort of things, but adding it to the documentation would be a great start.

**Comment by skrzepto** [comment]
I don't want to reopen this issue but I was curious how would you go in the other direction? For example Deserializing using generics.

For example

```
let s = '{"name":"some name","address":"some address","point":{"x":0,"y":0}}'
let loc: Result<Location<Point>, serde_json::error::Error> = serde_json::from_str(&s);
```
