### ISSUE TITLE
Allow deserialiser to start with default value of a struct 

### ISSUE THREAD

**Issue by Thomasdezeeuw** [serde-rs/serde#776]
I'm currently setting a bit of configuration code that reads a toml file, using serde and the [toml](https://github.com/alexcrichton/toml-rs) crate.

But I would like if not all the fields of the struct are required to be set in configuration, but instead default to some value. I'm currently doing it like so:

```rust
#[derive(Debug, PartialEq, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Config {
    #[serde(default = "default_option1")]
    pub option1: Vec<String>,

    #[serde(default = "default_option2")]
    pub option2: u64,
}

fn default_option1() -> Vec<String> { Vec::new() }
fn default_option2 () -> u64 { 1_000 }
```

But I would a way to always start with the default value, by using `std::default::Default` trait, and then start parsing and setting the values. Something like this:

```rust
#[derive(Debug, PartialEq, Deserialize)]
#[serde(deny_unknown_fields, default)] // note `default` here.
pub struct Config {
    pub option1: Vec<String>,
    pub option2: u64,
}

impl Default for Config {
    fn default() -> Config {
        Config {
            option1: Vec::new(),
            option2: 1_000,
        }
    }
}
```

Now the configuration default is in a single location and we don't need to use the functions that only return a single value in my case.

I'm looking forward to hearing other peoples ideas on how useful something like this would be.

**Comment by dtolnay** [comment]
Seems reasonable to me. Would you be interested in submitting a PR for this?

**Comment by Thomasdezeeuw** [comment]
Sure I'll give it a try.

**Comment by Thomasdezeeuw** [comment]
I've hit a bit of a problem. My first idea was to create an default value first and then loop over the input fields and update them if they're present. However I see that serde first gathers all the fields and then creates the struct if all of them are present.

I see two solution to the problem.

1. Try my original idea, this has the downside of change a lot of code in Serde (as far as I can tell).
2. Another alternative is to generate the struct's default value and then only take the field we're currently interested in. Something like this (in pseudo rust):

```rust
// field is missing
let value = {
    let default: Struct = Default::default();
    default.$field
};
```

This has the upside of changing less code. But (I think) the downside of needing to create an entire struct for a single field, I'm not sure if LLVM can optimize this.

**Comment by dtolnay** [comment]
Referring to https://serde.rs/deserialize-struct.html, the generated code currently behaves like:

```rust
let mut secs = None;
let mut nanos = None;
while let Some(key) = visitor.visit_key()? {
    /* get the values */
}
let secs = match secs {
    Some(secs) => secs,
    None => return Err(Error::missing_field("secs")),
};
let nanos = match nanos {
    Some(nanos) => nanos,
    None => return Err(Error::missing_field("nanos")),
};
Ok(Duration::new(secs, nanos))
```

I would expect the new behavior to look like:

```rust
let mut secs = None;
let mut nanos = None;
while let Some(key) = visitor.visit_key()? {
    /* get the values */
}
let default: Self = Default::default();
let secs = secs.unwrap_or(default.secs);
let nanos = nanos.unwrap_or(default.nanos);
Ok(Duration::new(secs, nanos))
```
