### ISSUE TITLE
Only executables and rlibs can be compiled with `-Z sanitizer`

### ISSUE THREAD

**Issue by brunoqc** [serde-rs/serde#779]
I don't seem able to run the sanitizer with the exemple from the README.md.

Not sure if you guys can change anything or if I should report it to https://github.com/japaric/rust-san

rustc 1.17.0-nightly (0e7727795 2017-02-19)

```
$ RUSTFLAGS="-Z sanitizer=thread" cargo run
   Compiling dtoa v0.4.1
   Compiling itoa v0.3.1
   Compiling quote v0.3.13
   Compiling unicode-xid v0.0.4
   Compiling serde v0.9.7
   Compiling num-traits v0.1.36
   Compiling synom v0.11.0
   Compiling syn v0.11.6
   Compiling serde_json v0.9.7
   Compiling serde_codegen_internals v0.13.0
   Compiling serde_derive v0.9.7
error: Only executables and rlibs can be compiled with `-Z sanitizer`

error: aborting due to previous error

error: Could not compile `serde_derive`.
```

**Comment by dtolnay** [comment]
Please report this against rust-san. I don't think there is anything we can do to address this.

**Comment by brunoqc** [comment]
I reported it. https://github.com/japaric/rust-san/issues/2

**Comment by brunoqc** [comment]
For the record it wasn't a bug. I had to use `--target x86_64-unknown-linux-gnu` like the README says.
