### ISSUE TITLE
attribute is only usable with crates of the `proc-macro` crate type

### ISSUE THREAD

**Issue by agaviria** [serde-rs/serde#784]
I'm getting issue trying to compile a simple serde_derive example.  I'm using latest nightly build:
`rustc 1.17.0-nightly (a17e5e294 2017-02-20)` and compiling with: 

```
  serde v0.9.8
  serde_json v0.9.8
  serde_derive v0.9.8
```

```
error: the `#[proc_macro_derive]` attribute is only usable with crates of the `proc-macro` crate type
 --> /Users/ag/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_derive-0.8.19/src/lib.rs:9:3
  |
9 | #[proc_macro_derive(Serialize, attributes(serde))]
  |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: the `#[proc_macro_derive]` attribute is only usable with crates of the `proc-macro` crate type
  --> /Users/ag/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_derive-0.8.19/src/lib.rs:17:3
   |
17 | #[proc_macro_derive(Deserialize, attributes(serde))]
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 2 previous errors

Build failed, waiting for other jobs to finish...
error: Could not compile `serde_derive`.
```

I tried adding and removing `#![feature(proc_macro)]` to see if this would have any relevance factor but it did not compile with either options.  I'm sure this is related to macros v1.1 but I'm not sure how to inspect this further.  Any guidance is well appreciated.

**Comment by dtolnay** [comment]
It looks like you may be using a really old version of Cargo. If you are using [rustup](https://rustup.rs/) for your compiler it should have been updating Cargo as well, but possibly you have an old Cargo binary somewhere in your $PATH that needs to be deleted.

You should be seeing:

```
$ cargo --version
  cargo 0.18.0-nightly (56083a3 2017-02-18)
```

**Comment by agaviria** [comment]
Hmm, you were right.  There was a cargo binary in `/usr/local/bin` I was convinced rustup was updating cargo but failed to do a quick `which cargo` cmd.  Anyhow, deleting this binary did the trick.  Thank you.
