### ISSUE TITLE
[Design] type-directed serialisation

### ISSUE THREAD

**Issue by cstorey** [serde-rs/serde#79]
Hi.

At the moment, the usage of the `de::Deserializer` trait seems to work under the assumption that the input syntactically discriminates between scalar, sequence-like and map-like values. 

I had a go at using serde to implement serialization for lisp-like s-expressions, which only have scalars and lists in the base syntax, and so because most of the visitors call into the `de::Deserializer#visit` method, I found that I was having to add explicit tags for whether a value was an integer, float, list, or a map. 

Given that we'll know the type of the value we're attempting to de-serialize at compile time, can you think of any particular reason why it might not be feasible to remove the `#visit` method, and just rely on types to direct what kind of syntactic construct we should expect?

Put another way, if we have a grammar with multiple potential start-rules, I'd like to be able to use the expected type to decide which start-rule to use.

**Comment by jsgf** [comment]
I'm interested in using serde for XDR, which basically has no syntax: the encoded form is an array of bytes, so decoding must be type-directed - the decoder must know the data shape up front.

(Related, XDR structures have no field names, but it does have a discriminated union that maps well to Rust's enums, but serde needs a way to specify the union discriminator tag values.)

**Comment by erickt** [comment]
`Deserializer`s actually do support type-driven deserialization, although as of right now it only has hints for compound types like `Option`s with `Deserializer::visit_option`, or `Map`s with `Deserializer::visit_map`. Those types will enter into the `Deserializer` using those methods, so you can use them to switch how the input stream is parsed. I do this in [serde::json::Deserializer](https://github.com/serde-rs/serde/blob/master/serde/src/json/de.rs#L450) to parse enums from JSON objects.

Do you have a need for hooks for primitive types like integers, floats or strings?

**Comment by cstorey** [comment]
That's fair; I wasn't sufficiently precise in describing the situation.

As a concrete example, the code at [spki-sexp](https://github.com/cstorey/spki-sexp.rs/blob/serde-terminus/src/lib.rs) might be useful for context. My representation for a vector or tuple would ideally just be `(v0 v1 v2)`, and that for a map would be `(k0 v0 k1 v1)`, so there's a syntactic ambiguity there. 

Also, I'd like to be able to represent integers and floats as just raw byte strings; hence you'd need to tell the deserializer what type of value to interpret it as. 

I can understand how the current design came to be; it does look like it was based with the assumption of a json-like syntax underneath (understandably, really).

**Comment by erickt** [comment]
Yes, JSON was the driving format. Methods like `Deserializer::visit_map` should be sufficient to disambiguate between vectors and maps. I'll add hooks for the primitives, that's a good reason why their necessary :)

**Comment by cstorey** [comment]
Okay, as a concrete example, there's the code that generates the `de::Visitor` instance for sequence-like types: [serde_codegen/src/de.rs:321](https://github.com/serde-rs/serde/blob/2c24be90d2cc56eff068ffa4b4efcb5c24789470/serde_codegen/src/de.rs#L321). To my mind, I think that rather than calling directly into the `de::Deserializer#visit` method, I think it'd be reasonable to call through `de::Deserialize::deserialize` to allow double-dispatch to work it's magic. 

Does that seem reasonable?

**Comment by erickt** [comment]
It's a little tricky because of all the visitors getting thrown around, but [serde_codegen/src/de.rs:321](https://github.com/serde-rs/serde/blob/2c24be90d2cc56eff068ffa4b4efcb5c24789470/serde_codegen/src/de.rs#L321) is actually calling the `SeqVisitor::visit` method, which is provided by the `Deserializer` and is consumed by the `Deserialize::visit_seq` method. The implementation of that method then needs to use `Deserialize::deserialize` to parse the value. For example, check out how the `serde::json::de::SeqVisitor ` [does it](https://github.com/serde-rs/serde/blob/master/serde/src/json/de.rs#L522).

**Comment by cstorey** [comment]
Okay, I guess I'm going to have to fiddle some more. Thanks.

**Comment by oli-obk** [comment]
This should be easier now with serde 0.5. The `Deserializer` has now loads of type specific functions: https://serde-rs.github.io/serde/serde/serde/de/trait.Deserializer.html

**Comment by erickt** [comment]
@cstorey: Have you had a chance to see if the type hints work for you?

**Comment by cstorey** [comment]
Thanks for the nudge. I've had a quick look, and it looks like I'll be able to take a similar tactic to the `bincode` crate then. I'm a little uncomfortable with having to trust that no-one will call the `#visit` method, but c'est la guerre.

**Comment by cstorey** [comment]
Okay, I've just plumbed that in and it seems to work. Thanks!
