### ISSUE TITLE
Remove serde_test::Token::EnumStart, rename EnumMap*

### ISSUE THREAD

**Issue by clarcharr** [serde-rs/serde#795]
Noted in #794.

`EnumStart` is only used by `deserialize`, which means that it can't be used in `assert_tokens`. Its use case is covered by the other `Enum*Start` tokens, and in fact, it's more confusing because it is essentially ignored.

Additionally, `Enum*` should be renamed to `Variant*` for consistency. I also propose that `EnumMap` be renamed to `StructVariant`.

**Comment by dtolnay** [comment]
I agree with all of that. The serde_test crate dates back to before we had established naming conventions within Serde for a lot of these things.

**Comment by clarcharr** [comment]
I'd be willing to offer a PR for this that can be merged on a breaking release. Not sure when that'd be.

**Comment by dtolnay** [comment]
Thanks, please open a PR but only including the changes to the Token enum. You don't need to fix the serde_test serializer and deserializer or the test suite to use the new names.

That way we can discuss and agree on an API now, then one of us can wrap up the rest of the change when we are ready for the next major release. I think that will be easier than writing the whole change now and dealing with merge conflicts.

**Comment by clarcharr** [comment]
Okay! Sounds good to me.

**Comment by dtolnay** [comment]
I changed my mind on EnumStart - it is important for testing how enums deserialize when the format represents the variant not as a string. For example bincode represents the variant as a u32.

Example from our test suite that could not be written without EnumStart: [`test_enum_out_of_range`](https://github.com/serde-rs/serde/blob/v0.9.12/test_suite/tests/test_de.rs#L1084-L1091)

```rust
test_enum_out_of_range<Enum> {
    &[
        Token::EnumStart("Enum"),
        Token::U32(4),
        Token::Unit,
    ],
    Error::Message("invalid value: integer `4`, expected variant index 0 <= i < 4"),
}
```

How about just improving support for EnumStart in assert_ser_tokens / assert_tokens?

**Comment by dtolnay** [comment]
Fixed in #845.

**Comment by clarcharr** [comment]
Sorry I got a bit late to this— I think it'd be best to serialise enums with multiple tokens so that `Enum` is used always, rather than making variants include names and not have the start header. I think it'd be cleaner and make it easier to understand the purpose of the token rather than duplicating the information over multiple token types.

**Comment by clarcharr** [comment]
Other than that :+1: to the changes and I'm cool with everything else.

**Comment by dtolnay** [comment]
Thanks @clarcharr! I filed #849 to follow up on your suggestion.
