### ISSUE TITLE
Bounds from serde(default) are too aggressive

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#799]
For example this struct:

```rust
#[derive(Deserialize)]
struct S<K, V> {
    #[serde(default)]
    map: HashMap<K, V>,
}
```

gives you:

```rust
impl<K, V> Deserialize for S<K, V>
    where K: Deserialize,
          V: Deserialize,
          K: Default,
          V: Default
```

Instead it should be:

```rust
impl<K, V> Deserialize for S<K, V>
    where K: Deserialize,
          V: Deserialize,
          HashMap<K, V>: Default
```

**Comment by TedDriggs** [comment]
I did some research on this and found that the standard derivations (such as `Clone`, etc.) deliberately _don't_ do this because it could expose a private item in the signature, or could leak details about a private field into the public signature. Would this be a sufficient workaround?

```serde
#[derive(Deserialize)]
struct S<K, V> {
    #[serde(default = "Default::default")]
    map: HashMap<K, V>,
}
```

**Comment by dtolnay** [comment]
Oh good call, I forgot about private types. We've had that problem in Serde before. I guess we'll stick to the workarounds - your approach with `default = "Default::default"` or with `bound = "..."`.
