### ISSUE TITLE
Implement Serialize/Deserialize for CStr

### ISSUE THREAD

**Issue by jonhoo** [serde-rs/serde#800]
`serde` currently ships with an `impl` of `Serialize` and `Deserialize` for [`str`](https://github.com/serde-rs/serde/blob/master/serde/src/ser/impls.rs#L80) and [`String`](https://github.com/serde-rs/serde/blob/master/serde/src/ser/impls.rs#L90), but not for the null-terminated C-like string types [`ffi::CStr`](https://doc.rust-lang.org/std/ffi/struct.CStr.html) and [`ffi::CString`](https://doc.rust-lang.org/std/ffi/struct.CString.html). Under the hood, these string implementations are very similar, and providing serialization implementations for the latter two shouldn't be too hard. Are there any particular reasons why `impl`s for these types are not provided?

**Comment by dtolnay** [comment]
No reason. Would you be able to send a PR adding these two impls?

**Comment by jonhoo** [comment]
@dtolnay I'll give it a shot. Should this be placed under its own flag, given that it's in `ffi`?

**Comment by dtolnay** [comment]
No, both types are in std so they should be behind the `std` feature.

One open question is how you intend to handle non-UTF8 strings.

**Comment by jonhoo** [comment]
I was thinking of serializing through `[u8]` rather than as strings, which should work fine, right?

**Comment by dtolnay** [comment]
Sure, that works.

**Comment by jonhoo** [comment]
@dtolnay patch in #801.
