### ISSUE TITLE
Docs for creating own serializing format

### ISSUE THREAD

**Issue by JuanPotato** [serde-rs/serde#802]
I'm not sure if I just haven't been looking in the right place, but i could not find any docs on creating my own serializing format. I'm trying to implement Telegram's (messaging service) api in Rust. I would like to use serde to more easily have this done. Should I just look at json and the other formats that have been written and just base it off them?

**Comment by oli-obk** [comment]
Unfortunately at this time we do not have any docs other than the API documentation

**Comment by dtolnay** [comment]
Not live yet, but this is now documented in [data-format.md](https://github.com/serde-rs/serde-rs.github.io/blob/0009ee2ed4e8083d0a450bb387bbbf17eadbc018/future/_src/data-format.md). It will go on the website when I release the next version of Serde.
