### ISSUE TITLE
[Feature] add NewSerializer/NewDeserializer traits

### ISSUE THREAD

**Issue by tikue** [serde-rs/serde#804]
This would allow programs to be generic over serialization strategy. For instance, an rpc library may want to allow a client/service pair to specify how types should be encoded on the wire.

**Comment by dtolnay** [comment]
Can you give an example of the code that you would like to be able to write using these traits?

**Comment by tikue** [comment]
So the problem is that `Serializer` and `Deserializer` are typically oneshots: you make a new one for each `Read` or `Write` stream. This would just be a trait that encodes that convention, a focal point that everyone could use. It'd essentially just be `From<Read>` / `From<Write>`:

```rust
trait NewSerializer {
    fn new_serializer<W>(write: W) -> Self
        where W: io::Write;
}

trait NewDeserializer {
    fn new_deserializer<R>(read: R) -> Self
        where R: io::Read;
}
```

Example code would be a `tokio_code::Codec` whose encode/decode impls are generic over these traits.

**Comment by dtolnay** [comment]
Thanks for the clarification. #644 is focusing on the same goal so let's continue the discussion there.

**Comment by tikue** [comment]
Cool, I did a small search before filing but didn't see that!
