### ISSUE TITLE
Help deserializing a struct

### ISSUE THREAD

**Issue by gbip** [serde-rs/serde#806]
Hello,
This is not really an issue, but a question for deserializing a struct.
I tried to follow the [wiki](https://serde.rs/deserialize-struct.html) but I can't find my way through it.
Here are the two structs 
``` rust
struct Foo {
    item1 : f32,
    item2:f32,
    object: Bar,
}

#[derive(Serialize,Deserialize)]
struct Bar {
     some_data : f64,
     more_data: f64,
}

#[derive(Serialize,Deserialize)]
struct MyObjects {
    objects : Vec<Foo>
}
```

The idea is to hide to the end user the fact that we have an abstraction on top of Bar.

This is how I serialize Foo (thanks to the people on IRC who helped me): 
``` rust
impl Serialize for Foo {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
        where S: Serializer
    {   
        self.object.serialize(serializer)
    }   
}
```

But I can't figure out how to Deserialize this struct. 
I tried implementing Deserialize, but I can"t find the right type of Visitor.
I am not sure if I should use a SeqVisitor for deserializing the object Field.
Moreover, do I also have to create an Enum for the fields since I only have one ?
Anyway, if you can help me I would be really grateful !

**Comment by oli-obk** [comment]
What should the values of `item1` and `item2` be after deserialization?

I think something like the following is what you want:

```rust
impl Deserialize for Foo {
    fn deserialize<D: Deserializer>(&self, deserializer: D) -> Result<D::Ok, D::Error> {
        Ok(Foo {
           item1: 42.3,
           item2: 3.141,
           object: Bar::deserialize(deserializer)?,
        })
    }
}
```

**Comment by gbip** [comment]
Thanks a lot for your answer, that was exactly what I was needing !

**Comment by oli-obk** [comment]
Great! Feel free to open another issue if you get stuck on anything else.
