### ISSUE TITLE
u32 as the discriminant type

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#809]
Continuing a discussion from #808 -

In a few places we treat u32 as a special case because is the only integer type that automatically derived enum variants can be deserialized from, [here](https://github.com/serde-rs/serde/blob/v0.9.11/serde_derive/src/de.rs#L1056). It is special in bincode and other deserialize-variants-by-index formats too, [here](https://github.com/TyOverby/bincode/blob/0ed8863bcb8080911e64aab7e956f64c8ebaae36/src/serde/reader.rs#L224). We say that Serde's data model represents variant indices as u32 and that any conversions are the responsibility of the user, for example `(my_u16 as u32).into_deserializer()`.

Is this the best approach?

**Comment by oli-obk** [comment]
It would be more explicit to add a visit_variant_index. But I'm not sure what the benefit of more explicitness would be.

**Comment by dtolnay** [comment]
This ties into #722 but in my opinion `deserialize_struct_field` fills this role. Maybe it could have a better name like `deserialize_discriminant` or maybe it could be two separate functions for struct field vs enum but let's have that discussion in #722.

I think from a broader perspective the role of Deserializer methods is to pass type information and the role of Visitor methods is to pass data.

"Struct field" or "discriminant" is type information so a dedicated Deserializer method makes sense. In contrast, "struct field" or "discriminant" is not data. "String" and "u32" are data.

Rather than introducing a Visitor method that is specific to variant index, I think it will suit us better to stick to the approach that a variant index is type information that can be fulfilled by a variety of data types depending on the format. We just need to document that string and u32 and [u8] are the variant index representations handled by derive(Deserialize).
