### ISSUE TITLE
Implement Deserialize for Box<CStr>

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#810]
This is waiting on a stable [`CString::into_boxed_c_str`](https://doc.rust-lang.org/nightly/std/ffi/struct.CString.html#method.into_boxed_c_str): https://github.com/rust-lang/rust/issues/40380

**Comment by jonhoo** [comment]
@dtolnay would you want this under an `unstable` flag when it first lands in `nightly`, or should we hold off all the way until `stable`?
