### ISSUE TITLE
[Feature Request] Add new field attribute "skip_serializing_default"

### ISSUE THREAD

**Issue by kestred** [serde-rs/serde#818]
A new field attribute "skip_serializing_default" would be another helpful control for serialization.   This would cause serde to skip serializing the field if its value is equal to `Default::default()`.

To demonstrate where this might be used, you might have this now:
```
fn is_zero(n: i64) {
   return n == 0;
}

#[derive(Serialize])
pub struct Params {
    id: Uuid,
    #[serde(skip_serializing_if = "Option::is_none")] value: Option<SomeObject>,
    #[serde(skip_serializing_if = "is_zero")] repetitions: i64,
}
```

And with the feature:

```
#[derive(Serialize])
pub struct Params {
    id: Uuid,
    #[serde(skip_serializing_default)] value: Option<SomeObject>,
    #[serde(skip_serializing_default)] repetitions: i64,
}
```

**Comment by dtolnay** [comment]
How do you feel about that idea in comparison to this?

```rust
#[derive(Serialize)]
pub struct Params {
    id: Uuid,

    #[serde(skip_serializing_if = "default")]
    value: Option<SomeObject>,

    #[serde(skip_serializing_if = "default")]
    repetitions: i64,
}

fn default<T: Default + PartialEq>(t: &T) -> bool {
    *t == Default::default()
}
```

One thing I don't like about `skip_serializing_default` is that it seems easy but hides potentially expensive operations which tends to be frowned upon in Rust.

```rust
// Requires a memory allocation, tens of thousands of instructions
#[serde(skip_serializing_default)]
map: BTreeMap<K, V>,

// Literally one machine instruction
#[serde(skip_serializing_if = "BTreeMap::is_empty")]
map: BTreeMap<K, V>,
```

**Comment by kestred** [comment]
Thanks, that solution does work pretty well.  
I didn't think of it for my own lack of experience with rust traits.

👍

**Comment by pickfire** [comment]
Would it be good to provide `skip_serializing_if_default`? Writing out the function manually works too but people have to do it themselves, I saw a case for `bool` on this.

https://github.com/GREsau/okapi/blob/master/okapi/src/openapi3.rs#L506-L508
```rust

#[derive(Debug, Clone, PartialEq, Deserialize, Serialize, Default)]
#[cfg_attr(feature = "derive_json_schema", derive(JsonSchema))]
#[serde(default, rename_all = "camelCase")]
pub struct Encoding {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub content_type: Option<String>,
    #[serde(skip_serializing_if = "Map::is_empty")]
    pub headers: Map<String, RefOr<Header>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub style: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub explode: Option<bool>,
    #[serde(skip_serializing_if = "is_false")]
    pub allow_reserved: bool,
    #[serde(flatten)]
    pub extensions: Object,
}

fn is_false(b: impl std::borrow::Borrow<bool>) -> bool {
    !b.borrow()
}
```

**Comment by hillu** [comment]
> ```rust
>     #[serde(skip_serializing_if = "is_false")]
>     pub allow_reserved: bool,
> ```

You can use `std::ops::Not::not` for `bool` values. Not sure if this is any easier to understand, though. ;-)

**Comment by jberryman** [comment]
> One thing I don't like about skip_serializing_default is that it seems easy but hides potentially expensive operations

#2762 seems like a good suggestion in that respect. The main thing I'm interested in is functionality where serialization/deserialization round trip is correct by construction

**Comment by 1Dragoon** [comment]
Would be nice if something like this was built-in:

```rust
fn is_default<T: Default + PartialEq>(value: &T) -> bool {
    *value == Default::default()
}
```
