### ISSUE TITLE
Implementations for OsStr/ing

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#823]

**Comment by Diggsey** [comment]
It's unclear whether this should be provided at all, given that `OsString` differs by platform, so there's no way to ensure that round-trips (eg. windows -> linux -> windows) is lossless.

If this is going to be added, I think it should tag the encoded string with the platform, and refuse to decode a windows OsString into a linux OsString or vice-versa, given that any data encoded this way will not be portable.
