### ISSUE TITLE
Maximum integer value from a tree of structures

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#828]
From IRC:

> **\<alteous>** I would like to obtain a maximum integer value from a tree of structures. The context is these values are offsets into arrays, and I want to check that they are all valid ahead of time. The integer values are wrapped in Index<T> types.
> **\<alteous>** Here's an example of what I'd like to achieve https://gist.github.com/alteous/3986ace4719903933277aa5fba161763

@alteous

**Comment by dtolnay** [comment]
Here is one possible approach.

```rust
#[derive(Clone, Debug, Serialize)]
pub struct Root {
    foos: Vec<Foo>,
    bars: Vec<Bar>,
    bazs: Vec<Baz>,
    #[serde(skip_serializing)]
    foo_max: Index<Foo>,
}

impl Deserialize for Root {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
        where D: Deserializer
    {
        #[derive(Deserialize)]
        struct RootHelper {
            foos: Vec<Foo>,
            bars: Vec<Bar>,
            bazs: Vec<Baz>,
        }
        RootHelper::deserialize(deserializer).map(|helper| {
            let foo_max = helper.bazs
                .iter()
                .map(|baz| baz.foo)
                .max()
                .unwrap_or(Index(0, PhantomData));
            Root {
                foos: helper.foos,
                bars: helper.bars,
                bazs: helper.bazs,
                foo_max: foo_max,
            }
        })
    }
}
```

**Comment by alteous** [comment]
Hi, thanks for your reply. Whilst the above technically solves the problem I described it's not the solution I was looking for. The [real data structure](https://github.com/alteous/gltf/blob/incoming/src/v2/mod.rs#L65) is more complex. I would like to avoid is writing code that checks every index by hand since it's tedious and error prone.

Is there possible any other way? I thought about writing a custom `Serializer` that would walk the tree after an initial deserialization. The serializer wouldn't output any data but it would error if an index was found to be out of range. Pseudo-code of what I'm trying to describe:

```rust
let root = serde_json::from_str(...);
let serializer = CustomSerializer {
    accessor_max: root.accessors.len(),
    // etc.
};
match CustomSerializer::serialize(&root) {
    Ok(()) => { /* all indices are valid */ },
    Err(err) => { /* index out of range */ },
}
```

**Comment by dtolnay** [comment]
That would work! Change the Serialize impl for Index to:

```rust
impl Serialize for Index<Accessor> {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
        where S: Serializer
    {
        // JSON serializes this as just the inner value.
        serializer.serialize_newtype_struct("Index<Accessor>", &self.value())
    }
}
```

And have the serialize_newtype_struct method of the custom Serializer match that to a max value for that dimension:

```rust
fn serialize_newtype_struct<T>(self, name: &'static str, v: &T) -> Result<()>
    where T: ?Sized + Serialize
{
    match self.lengths.get(name) {
        Some(max) if max <= v.serialize(AsU32)? => {
            /* error, out of bounds */
        }
        None if name.starts_with("Index") => {
            /* error, missing max for this dimension */
        }
        _ => {
            Ok(())
        }
    }
}
```

Where AsU32 is another custom serializer with just a serialize_u32 method that gives you the u32 value.

**Comment by alteous** [comment]
#### Update

I had a go at writing code for the above, but I found the implementation of `Serialize` to be too 'involved'. I got as far as being able to print out all the field names of the root tree, but going further, the rabbit hole went too deep to be a feasible solution.

In case you're interested, I ended up going for a [manual check](https://github.com/alteous/gltf/blob/incoming/src/v2/root.rs#L273) but in a [more maintainable way](https://github.com/alteous/gltf/blob/incoming/src/v2/accessor.rs#L180).

Thanks for your excellent support!
