### ISSUE TITLE
Audit type conversions

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#836]
The standard I would like to set is that if Serde successfully deserializes some input into a particular struct, you can be confident that the input matches what your struct says it should look like.

Currently there are conversions that I think violate this, for example deserializing strings and collections from unit:

```rust
#[derive(Deserialize)]
struct Bad {
    s: String
}

serde_json::from_str::<Bad>("{\"s\":null}").unwrap();
```

To me, null in the input means you should have used Option\<String> or a deserialize_with function that treats null as default.

Let's go through and critically evaluate all of the type conversions that are being done and eliminate these confusing ones.

**Comment by dtolnay** [comment]
Fixed in #839.

**Comment by mmstick** [comment]
Is there a way to enable this kind of version for a type?

**Comment by mmstick** [comment]
It's a common convention with a JSON:API, where clients must be able to treat either a lack of or a null as being the same thing.
