### ISSUE TITLE
#[derive(Deserialize)] source map contains nonexistent files

### ISSUE THREAD

**Issue by alexcrichton** [serde-rs/serde#85]
The source map generated from usage of `#[derive(Deserialize)]` causes `.d` files emitted by the compiler to contain nonexistent files that look like:

```
/home/alex/code/example/home/alex/code/example/target/debug/libexample.rlib: src/lib.rs <quote\ expansion <quote\ expansion <quote\ expansion <quote\ expansion

/home/alex/code/example/target/debug/example.d: src/lib.rs <quote\ expansion <quote\ expansion <quote\ expansion <quote\ expansion
```

(e.g. `<quote expansion`). Unfortunately this causes Cargo to think that `<quote expansion` is an input file, and because it never exists Cargo will always rebuild a library using `#[derive(Deserialize)]`.

I think this may [originally come from `quasi`](https://github.com/erickt/rust-quasi/blob/d9ec71215002076dd0102698b22f78fb8f748e71/quasi/src/lib.rs#L126), but I'm not sure if it's because of `quasi` or something in the middle?

**Comment by dtolnay** [comment]
Closing because the steps in https://github.com/rust-lang/cargo/issues/1600 no longer cause the crate to rebuild repeatedly. Please reopen if there is anything we still need to fix.
