### ISSUE TITLE
Replace ::util::encode_utf8 with char::encode_utf8

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#851]
[This function](https://github.com/serde-rs/serde/blob/v0.9.13/serde/src/de/mod.rs#L1019) should be using [`char::encode_utf8`](https://doc.rust-lang.org/std/primitive.char.html#method.encode_utf8) instead. It requires Rust >=1.15.0.

**Comment by abhijeetbhagat** [comment]
I can work on this.

**Comment by abhijeetbhagat** [comment]
I want to make a small note. 
After checking `char::encode_utf8`'s source, i found that it is calling `unsafe fn from_utf8_unchecked_mut`. Whereas, serde's original `utf8::encode` doesn't do anything unsafe.

**Comment by dtolnay** [comment]
Tagging as <kbd>breaking change</kbd> because this would require bumping our minimum supported Rust version from 1.13 to 1.15.

**Comment by dtolnay** [comment]
Closing as <kbd>wishlist for 2.0</kbd>.
