### ISSUE TITLE
"can't find crate for _serde" when deriving

### ISSUE THREAD

**Issue by torkleyy** [serde-rs/serde#856]
If I only include `serde_derive` in my `Cargo.toml`, I'll get an

```
error[E0463]: can't find crate for `_serde`
 --> src/main.rs:4:10
  |
4 | #[derive(Serialize)]
  |          ^^^^^^^^^ can't find crate

error: aborting due to previous error
```

This is the source code:

```rust
#[macro_use]
extern crate serde_derive;

#[derive(Serialize)]
struct Foo;

fn main() {

}
```

Adding `serde` to my dependencies fixes this.

Is this a known issue?

**Comment by dtolnay** [comment]
Thanks for the report! Yes, adding serde to Cargo.toml is one of the setup steps in https://serde.rs/codegen.html.

I pushed 2c49f9aad33009b9f468ce51388852fa0ae31dac to add `extern crate serde` to the example code even though it is not required, to hopefully remind people.

**Comment by torkleyy** [comment]
@dtolnay OK, I thought so. The reason I mention this is because together with [`toml-rs`](https://github.com/alexcrichton/toml-rs), this causes `cargo check` to panic. I'm not quite sure why it does that, but the following project causes an ICE:

### tree

```
├── Cargo.toml
└── src
    └── lib.rs
```

### Cargo.toml

```toml
[package]
name = "issue-lib"
version = "0.1.0"

[dependencies]
serde_derive = "0.9"
toml = "0.3"
```

### lib.rs

```rust
#[macro_use]
extern crate serde_derive;
extern crate toml;

#[derive(Deserialize)]
pub struct Foo {
}
```

I would create an issue in the Rust repo for that, but it's not really a minimal example because of its dependencies.

**Comment by dtolnay** [comment]
Looks like that bug is fixed as of rustc 1.17.0-beta.3 so you don't need to file an issue.

**Comment by ishitatsuyuki** [comment]
Hey, sorry for bumping. I have enabled `unused_extern_crates` by default in rust-lang/rust#42588, and stale `extern crate` will trigger a warning. Can you remove that and try to document it in word instead?

**Comment by dtolnay** [comment]
Thanks @ishitatsuyuki, I filed https://github.com/serde-rs/serde/issues/1026 and https://github.com/serde-rs/json/issues/350 and https://github.com/serde-rs/serde-rs.github.io/issues/62 to follow up.

**Comment by GildedHonour** [comment]
I don't understand, how to fix it?

**Comment by ishitatsuyuki** [comment]
@GildedHonour read the entire thread before bumping. Basically, you need serde as a dependency in your Cargo.toml.

**Comment by kardeiz** [comment]
I just encountered this error&mdash;

My use case is slightly different. I have a project set up as a Cargo workspace, and I am thinking about setting up an internal `common` crate to handle external dependencies shared by multiple internal crates. `serde` and `serde_derive` are some of those crates I'd like to share.

With the `proc_macro` feature, I can easily put the `Deserialize`/`Serialize` macros in scope wherever I need them. However, if I do so outside the `common` crate, I get the error in the issue title.

I haven't looked into the internal workings of these macros at all, but I'm guessing they are looking for `::serde` (or maybe `$crate::serde`) in scope. However, in my case `serde` will be at `::common::serde`. Is there any way I can work around this?

**Comment by ishitatsuyuki** [comment]
@kardeiz No, it only needs a cargo dependency. `extern crate` is done internally with an alias (`_serde`).

**Comment by elichai** [comment]
Hey, This doesn't work with package renaming 
Doing `serde_std = { package = "serde", version = "1.0", features = ["derive"], optional = true }`
Results in ``` error[E0463]: can't find crate for `_serde` ``` for `#[derive(Deserialize)]

**Comment by Felabs1** [comment]
how could we use it in web assembly

**Comment by Venryx** [comment]
Just wanted to mention that there is a workaround someone found here: https://github.com/serde-rs/serde/issues/1465#issuecomment-800686252
```rust
use common::serde::{self, Deserialize, Serialize}

#[derive(Copy, Clone, Debug, Deserialize, Serialize)]
#[serde(crate = "self::serde")] // must be below the derive attribute
struct Vertex {
    position: [u32; 3],
}
```
