### ISSUE TITLE
AppVeyor build is flaky

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#862]
I have seen a failure like this several times:

```
Build started
git clone -q https://github.com/serde-rs/serde.git C:\projects\serde
git fetch -q origin +refs/pull/853/merge:
git checkout -qf FETCH_HEAD
Running Install scripts
appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
Error downloading remote file: One or more errors occurred.
Inner Exception: The request was aborted: Could not create SSL/TLS secure channel.
Command exited with code 2
```

**Comment by oli-obk** [comment]
[appveyor docs say:](https://www.appveyor.com/docs/how-to/download-file/)

> this most probably means that build worker and server could not agree on SSL protocol, because server does not support modern protocol with highest security. If you understand this security risk and trust that server, you can relax SSL client settings in build PowerShell session by the following statement called before Start-FileDownload

```
[Net.ServicePointManager]::SecurityProtocol = 'Ssl3, Tls, Tls11, Tls12'
```

Which is weird, b/c it works most of the time.

**Comment by oli-obk** [comment]
[stackoverflow says](http://stackoverflow.com/questions/2859790/the-request-was-aborted-could-not-create-ssl-tls-secure-channel) it could also be the installed .net frameworks fault.
