### ISSUE TITLE
Lift values out of nested JSON

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#868]
From IRC:

> **\<bazz>** is there any way to "flatten" nested json?  that is, i have some json like {"foo": "bar", "a": {"b": {"c": "d"}}} and i want to have  a struct where "c" is lifted, so it would have struct foo { foo: String, #[serde(someflattenannotationlike="a.b")] c: String }

**Comment by dtolnay** [comment]
Adding an attribute for this is tracked in #119 but here is one possible workaround:

```rust
#[macro_use]
extern crate serde_derive;

extern crate serde;
extern crate serde_json;

use serde::{Deserialize, Deserializer};

#[derive(Deserialize, Debug)]
struct Bazz {
    foo: String,
    #[serde(rename = "a", deserialize_with = "nested_a_b_c")]
    c: String,
}

fn nested_a_b_c<D>(deserializer: D) -> Result<String, D::Error>
    where D: Deserializer
{
    #[derive(Deserialize)]
    struct A {
        b: B,
    }
    #[derive(Deserialize)]
    struct B {
        c: String,
    }
    A::deserialize(deserializer).map(|a| a.b.c)
}

fn main() {
    let j = "{\"foo\":\"bar\",\"a\":{\"b\":{\"c\":\"d\"}}}";
    println!("{:?}", serde_json::from_str::<Bazz>(j).unwrap());
}
```

**Comment by brigand** [comment]
In case anyone else stumbles upon this, I had to add appropriate liftimes for this to work.

```rust
fn extract_object_string<'de, D>(deserializer: D) -> Result<String, D::Error>
where
    D: serde::de::Deserializer<'de>,
{
    #[derive(Deserialize)]
    struct Container {
        object: String,
    }
    Container::deserialize(deserializer).map(|a| a.object)
}
```

And it can be made generic over the output type:

```rust
fn extract_object_generic<'de, D, T>(deserializer: D) -> Result<T, D::Error>
where
    D: serde::de::Deserializer<'de>,
    T: Deserialize<'de>,
{
    #[derive(Deserialize)]
    struct Container<T> {
        object: T,
    }
    Container::deserialize(deserializer).map(|a| a.object)
}
```

**Comment by utkarshgupta137** [comment]
> Adding an attribute for this is tracked in #119 but here is one possible workaround:
> 
> ```rust
> #[macro_use]
> extern crate serde_derive;
> 
> extern crate serde;
> extern crate serde_json;
> 
> use serde::{Deserialize, Deserializer};
> 
> #[derive(Deserialize, Debug)]
> struct Bazz {
>     foo: String,
>     #[serde(rename = "a", deserialize_with = "nested_a_b_c")]
>     c: String,
> }
> 
> fn nested_a_b_c<D>(deserializer: D) -> Result<String, D::Error>
>     where D: Deserializer
> {
>     #[derive(Deserialize)]
>     struct A {
>         b: B,
>     }
>     #[derive(Deserialize)]
>     struct B {
>         c: String,
>     }
>     A::deserialize(deserializer).map(|a| a.b.c)
> }
> 
> fn main() {
>     let j = "{\"foo\":\"bar\",\"a\":{\"b\":{\"c\":\"d\"}}}";
>     println!("{:?}", serde_json::from_str::<Bazz>(j).unwrap());
> }
> ```

The flatten attribute is for doing the inverse operation of this. Is there a way/open issue for reverse flattening (as described in #2115) other than using a From struct. I need to do this for multiple fields too.
