### ISSUE TITLE
Simplify process for writing custom Deserialize

### ISSUE THREAD

**Issue by beamspease** [serde-rs/serde#870]
It's somewhat difficult to memorize all the steps needed to write a custom deserialize function. It would make it much easier if there were an "easy" macro for types that need a "simple" deserializer from one type, provides a default "expecting", etc.

**Comment by dtolnay** [comment]
Seems reasonable. Could you give an example of a type that you think would be simple enough to handle this way?

**Comment by beamspease** [comment]
Here's a pattern that seems to crop up whenever I pull in a type from another library that doesn't implement serialization for Serde.

I would envision something like this being generated by:
```serialization_wrap!(KernelVersion, semver::Version, str, "Kernel Version (eg 4.10.10)")```

This would require a little bit of per-type specialization in the macro and of course would only work for types that implemented proper conversion macros.

Not 100% sure, but I think you might be able to get rid of the third parameter, but then again that might be something that you want to force the programmer to explicitly specify.

I could also see a less C-ish variant:
```serialization_wrap!(KernelVersion(semver::Version) = "Kernel Version (eg 4.10.10)".parse())```

```
#[derive(Debug)]
struct KernelVersion(semver::Version);

impl core::ops::Deref for KernelVersion {
    type Target = semver::Version;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

struct KernelVersionVisitor;
impl serde::de::Visitor for KernelVersionVisitor {
    type Value = KernelVersion;

    fn expecting(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.write_str("Kernel Version (eg 4.10.10)")
    }
    fn visit_str<E>(self, value: &str) -> core::result::Result<Self::Value, E>
        where E: serde::de::Error
    {
        Ok(KernelVersion(value.parse().map_err(E::custom)?))
    }
}
impl serde::Deserialize for KernelVersion {
    fn deserialize<D: serde::Deserializer>(deserializer: D)
                                           -> core::result::Result<Self, D::Error> {
        deserializer.deserialize_str(KernelVersionVisitor)
    }
}
impl serde::Serialize for KernelVersion {
    fn serialize<S: serde::Serializer>(&self,
                                       serializer: S)
                                       -> core::result::Result<S::Ok, S::Error> {
        serializer.serialize_str(self.0.to_string().as_str())
    }
}

```

**Comment by clarcharr** [comment]
Perhaps a `#[derive(Deserialize)] #[serde(with_visitor = "KernelVersionVisitor")]` would be nice?

**Comment by beamspease** [comment]
Yeah, that sounds helpful and it goes well with the existing serde options. Although you'd still have to write out the whole visitor and the serializer?

**Comment by Xion** [comment]
For the deserialization case at least, I think the combination of:
```rust
#[serde(deserialize_from = "str")]  // defaults to "any"
#[serde(visitor = "KernelVersionVisitor", expecting = "Kernel Version (eg 4.10.10)")]
struct KernelVersion(semver::Version);
```

would solve all the cases where `Deserialize` is just doing a passthrough to the visitor via some `deserialize_foo`. The visitor could then even be implemented as a simple function.

The serialization is, I think, adequately served by `#[serde(serialize_with = "...")]`. The problem is of course that Rust doesn't allow attributes on newtype/tuple struct fields. Serde could have a workaround for that, e.g. `#[serde(_field = 0, serialize_with = "...")]`.

**Comment by dtolnay** [comment]
> The problem is of course that Rust doesn't allow attributes on newtype/tuple struct fields.

It does.

**Comment by pickfire** [comment]
@beamspease Is this still valid?

**Comment by dtolnay** [comment]
I would be interested in this being explored outside the serde codebase.
