### ISSUE TITLE
Avro support

### ISSUE THREAD

**Issue by jadbox** [serde-rs/serde#887]
It would be amazing to add Avro as a default de/serializer. I noticed there's a basic implementation for Serde Avro under the rq project as shown below.

source: https://github.com/dflemstr/rq/tree/master/serde-avro

rq's PR: https://github.com/dflemstr/rq/pull/113

**Comment by dtolnay** [comment]
Thanks for the suggestion! Right now *all* Serde data formats are provided by external crates like serde-avro. The only flagship format maintained by the Serde team is JSON, but really the only meaning to that is the repo lives under the serde-rs org. I'm happy with the rq folks continuing to own serde-avro.

**Comment by dflemstr** [comment]
Hey, I am the "`rq` folks" and I'm happy to keep `serde-avro` in the `rq` repo for now. Feel free to contribute PRs even if they don't touch `rq`!

**Comment by dtolnay** [comment]
Perfect!

**Comment by jadbox** [comment]
@dflemstr first, thank you so much for creating the Avro implementation for Serde. Would you mind perhaps moving serde-avro to its own repo for clarity and ease of discovery?
