### ISSUE TITLE
Avoid a string copy when deserializing parsed types

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#896]
[Here.](https://github.com/serde-rs/serde/blob/v1.0.0/serde/src/de/impls.rs#L873) To avoid allocating in formats that support \&str.

cc @vorner

**Comment by Marwes** [comment]
Unfortunately Cow can't be used for that (at least not directly) as it only deserializes into its owned form https://github.com/serde-rs/serde/blob/d7ccef0cac8b3703eee47edee19f6bce0109af27/serde/src/de/impls.rs#L1125-L1137 . Would required specialization and a breaking change to fix it :/

**Comment by dtolnay** [comment]
Fixed in 485a64aaf95c6f0737ef4961258d8e8bd4dbd385.
