### ISSUE TITLE
Showcase performance

### ISSUE THREAD

**Issue by ivegotasthma** [serde-rs/serde#897]
Hello,

It would be useful to have a benchmark in the `README` of the performance of the framework for some micro examples.

**Comment by dtolnay** [comment]
Thanks! Any suggestions for what micro examples to consider?

**Comment by ivegotasthma** [comment]
I found this for checking [{con,per}formance](https://github.com/miloyip/nativejson-benchmark/tree/master/data) for different C/C++ frameworks. It's possible to take out the json and run it against serde. I could work on it but I'm new to Rust and Serde.

**Comment by dtolnay** [comment]
I have an implementation of that benchmark in https://github.com/serde-rs/json-benchmark. Currently Serde is 4 to 8 times faster than rustc-serialize and up to twice as fast as the fastest C / C++ library according to those benchmarks.

Over the next few days I will be updating that repo to Serde 1.0 and zero-copy deserialization which I expect will be a nice speedup.

**Comment by ivegotasthma** [comment]
Awesome, thanks for the quick replies! Would you mind putting this somewhere visible to the newbies? :)

**Comment by dtolnay** [comment]
Yep, I'll take care of that when it's up to date.

**Comment by jonathanstrong** [comment]
another newbie here: it would also be great to have information about the relative performance of the various formats supported.
