### ISSUE TITLE
Docs out of sync with source?

### ISSUE THREAD

**Issue by SkylerLipthay** [serde-rs/serde#91]
Compare [the docs](http://serde-rs.github.io/serde/serde/ser/trait.SeqVisitor.html#tymethod.visit) for `SeqVisitor::visit` with [the corresponding source code](http://serde-rs.github.io/serde/src/serde/ser/mod.rs.html#185). The return types are different: `Result<Option<()>, S>` and `Result<Option<()>, S::Error>` respectively. Is this a rustdoc problem?

**Comment by Byron** [comment]
Thanks for posting. 
To me it seems like a workflow problem, one that is evident in the same way with [hyper](https://github.com/hyperium/hyper) as well.

Currently whenever something is pushed to master, the [docs will be generated by travis](https://github.com/serde-rs/serde/blob/master/.travis.yml#L21). However, a new release on crates.io is not necessarily happening at the same time.

A possible solution could be to work in a branch which prepares the upcoming release, which is merged into master when ready, and which triggers a publish to crates.io automatically.

**Comment by tomprogrammer** [comment]
Aside from the inconsistencies due to the workflow, this specific problem is a bug in stable rustdoc. It's fixed in beta which fixes many more problems in rustdoc.

**Comment by Byron** [comment]
Thanks for the clarification ! It seems I saw just what I wanted to see :).

**Comment by SkylerLipthay** [comment]
Thanks to both of you for the insight!
