### ISSUE TITLE
untagged enums with struct variants to not seem to honor struct field attributes.

### ISSUE THREAD

**Issue by softprops** [serde-rs/serde#910]
[untagged enums](https://serde.rs/enum-representations.html) with struct variants to not seem to honor struct field attributes.

```rust
#[derive(Debug, Deserialize, Serialize, PartialEq)]
#[serde(untagged)]
pub enum ObjOrRef {
   Object {
    pub name: String,
 },
  Ref {
   #[serde(rename="$ref")]
    pub ref_path: String
  }
}
```

If I try to deserialize a json object with a `$ref` key, deserialization fails ( I expected the rename to catch this ) but instead if I deserialize a json object with `ref_path` key, deserialization works.

I'm not sure field level attributes are supported for enums or not so this may not be a bug if they never where. If they aren't consider this a feature request, I had the expectation that it would work. 

I ran into this while working on a enum based solution for https://github.com/softprops/openapi/issues/4

**Comment by dtolnay** [comment]
Can you share the whole code that didn't work? I was not able to reproduce this with the following code.

```rust
#[macro_use]
extern crate serde_derive;

extern crate serde;
extern crate serde_json;

#[derive(Serialize, Deserialize, Debug)]
#[serde(untagged)]
pub enum ObjOrRef {
    Object {
        name: String,
    },
    Ref {
        #[serde(rename = "$ref")]
        ref_path: String
    }
}

fn main() {
    let a = "{\"name\":\"a\"}";
    println!("{:?}", serde_json::from_str::<ObjOrRef>(a).unwrap());

    let b = "{\"$ref\":\"b\"}";
    println!("{:?}", serde_json::from_str::<ObjOrRef>(b).unwrap());

    let c = ObjOrRef::Object { name: "c".to_owned() };
    println!("{}", serde_json::to_string(&c).unwrap());

    let d = ObjOrRef::Ref { ref_path: "d".to_owned() };
    println!("{}", serde_json::to_string(&d).unwrap());
}
```

**Comment by softprops** [comment]
I may have posted this too early, Ill try again tonight.

**Comment by softprops** [comment]
Yea this was my bad. Sry about that. In parting the enum flexibility in serde is amazing!
