### ISSUE TITLE
hashset: duplicate entries are silently discarded when deserializing

### ISSUE THREAD

**Issue by lucab** [serde-rs/serde#913]
When working with an hashset, it looks like serde is currently deserializing non-unique entries simply by silently discarding all but the last occurence. I was a bit surpised as I discovered this when writing tests around supposedly malformed inputs (with duplicate elements), which were instead accepted by serde.

This probably also applies to other types of sets and maps. It may even be working as intended, but I think it may lead to unexpected surprises.

As an example, I was going through:
```
#[test]
fn test_hashset() {
    #[derive(Serialize, Deserialize, Debug, PartialEq, Eq, Hash)]
    struct Entry {
        id: u32,
        val: String,
    }
    let jsonin = r#"[{"id":1, "val":"a"}, {"id":1, "val":"a"}]"#;
    std::collections::HashSet<Entry> = serde_json::from_str(jsonin).unwrap();
}
```

This naive case will just result in the set having a single entry instead of the original two, which I find already a bit strange as I would have expected some "duplicate key" error. However, a similar example with a custom implementation of `Eq` and `Hash` (e.g. only keyed on `id`) will result in actual values being discarded without the consumer being aware of it.

Is this semantics on purpose? If so, is there is a way of opting-out in order to get a stricter deserializer? In general, would you consider changing this behavior to early-fail instead of keep-going?

**Comment by dtolnay** [comment]
See the discussion in #916.
