### ISSUE TITLE
Limited zero-copy deserialization of sequences

### ISSUE THREAD

**Issue by bluss** [serde-rs/serde#915]
A question / discussion of zero-copy deserialization. I've only just begun exploring it, and the ease of porting means that I got pretty far IMO before running into some questions.

The current status of ndarray is that all arrays can be serialized (Think like Vec and shared/mut slices), and only owned arrays (Think like Vec) can be deserialized.

The naive way forward would be to not alter the way the arrays are serialized but implement Deserialize for `ArrayView<'a, T, D>` where `T` is a plain old data element type, for example f64. This would involve reparsing a `&'a [u8]` as `&'a [f64]` if it is possible.

This doesn't directly work. Using bincode. We can request a `&[u8]` of the correct lifetime for the array data, but we get a sequence of 60 bytes if we serialized an array of 60 f64; so it's reusing the sequence length the wrong way. Not suprising since the unmodified serialization is putting in a sequence of 60 f64's.

How do we cover this use case? There are definite challenges; misaligned data can not be deserialized this way, for example. With all the fields preceding the data being `usize` fields, alignment should often not be a real problem..

**Comment by bluss** [comment]
cc @TyOverby A thought for you; zero-copy deserialization could mean that bincode could benefit from the option of inserting padding in the stream :fearful:

**Comment by dtolnay** [comment]
Maybe something along these lines?

```rust
#[macro_use]
extern crate serde_derive;

extern crate serde;
extern crate bincode;
extern crate pod;

#[derive(Serialize, Deserialize)]
struct Array<'a> {
    #[serde(borrow, with = "floats")]
    data: &'a [f64],
}

mod floats {
    use serde::{de, Serializer, Deserialize, Deserializer};
    use pod::Pod;

    pub fn serialize<S>(data: &[f64], serializer: S) -> Result<S::Ok, S::Error>
        where S: Serializer
    {
        let bytes = Pod::map_slice(data).unwrap();
        serializer.serialize_bytes(bytes)
    }

    pub fn deserialize<'de, D>(deserializer: D) -> Result<&'de [f64], D::Error>
        where D: Deserializer<'de>
    {
        let bytes = <&[u8]>::deserialize(deserializer)?;
        Pod::map_slice(bytes).ok_or_else(|| de::Error::custom("not a multiple of 4 bytes"))
    }
}
```

**Comment by bluss** [comment]
That sounds interesting. Maybe something like that can be made usable with ndarray.

I think it does not incorporate the ideas of graceful degradation and not changing the serialization code. The original idea was to keep the general serialization and implement some specific cases for zero-copy deserialization.

Imagine if you had `Vec<T>` original serialization impl, and wanted to implement a special case deserializer for `&[f64]` that could eat that same representation.

**Comment by dtolnay** [comment]
Yeah we don't have that right now. One middle ground would be defining helpers that provide the compact representation.

```rust
struct Bluss<'a> {
    #[serde(with = "ndarray::compact")]
    array: ArrayView<'a, T, D>,
}
```

**Comment by bluss** [comment]
The representation is already compact (contiguous), the problem would naively seem to be to get a byte slice not of the size that the sequence size in the stream says, but a byte slice of length (sequence size in the stream) * (element size); alternatively simply a byte slice of custom size, since it's already known from the header serialization.

**Comment by dtolnay** [comment]
The borrowing feature supports `str` and `[u8]` because those can be portably supported across practically all formats. Other than `Pod` casts like in https://github.com/serde-rs/serde/issues/915#issuecomment-299645292, any other use cases will likely stick to serde 0.9-style serialization or use a more specialized serialization library.

**Comment by sffc** [comment]
The solution in https://github.com/serde-rs/serde/issues/915#issuecomment-299645292 doesn't seem to have great answers for:

1. Whether the data is properly aligned
2. Endianness of the data

On (1), the implementation of `Pod::map_slice(bytes)` returns `None` not only if the slice is the wrong length, but also if the slice is misaligned.  In order for this to work, Bincode must need a way to know whether to ensure that byte arrays are properly aligned in memory layout.

On (2), it seems on first glance that `Pod::map_slice(bytes)` assumes the data is in the same endianness as the machine it is running on, which isn't necessarily true.

How else can we achieve zero-copy deserialization for anything other than `&str` and `&[u8]`?

CC @Manishearth
