### ISSUE TITLE
rename_all needs documentation

### ISSUE THREAD

**Issue by anderejd** [serde-rs/serde#917]
Found this in a closed issue but not in the documentation:

#[serde(rename_all = "snake_case")]
#[serde(rename_all = "kebab-case")]
#[serde(rename_all = "SNAKE_CASE")]
#[serde(rename_all = "camelCase")]
#[serde(rename_all = "PascalCase")]

Btw, thanks all for this awesome library! :)

**Comment by oli-obk** [comment]
We also need some tests for it

**Comment by dtolnay** [comment]
This is documented under both [container attributes](https://serde.rs/container-attrs.html) and [variant attributes](https://serde.rs/variant-attrs.html) and thoroughly tested in test_suite/tests/test_macros.rs. What am I missing?

**Comment by oli-obk** [comment]
I had the field attributes page open all day -.-

**Comment by anderejd** [comment]
Ah there it is! Not sure where I was looking, probably did a search for "serde rename_all". Sorry for the noise.
