### ISSUE TITLE
Report the field name whose deserialization triggered an error

### ISSUE THREAD

**Issue by oli-obk** [serde-rs/serde#919]
Currently when you deserialize `foo = 5` with toml into a struct with a field `foo: String`, you get an error along the lines of

> invalid type: integer `5`, expected a string

Since this error bubbles up through the field deserialization code I wonder if we can inject the field name into the error without slowing down the success path

Formats to implement this in:

- [x] Yaml
- [ ] Json https://github.com/serde-rs/json/issues/173
- [ ] Xml
- [ ] Toml

**Comment by dtolnay** [comment]
I am skeptical that this could be done nicely in core Serde but individual formats can implement this usually pretty easily. For example YAML has errors that give you not just the field name but the full path to the error: https://github.com/dtolnay/serde-yaml/pull/43.

**Comment by oli-obk** [comment]
I'll do some impls and see what common parts we can extract into serde.

**Comment by spease** [comment]
I've also run into this quite a bit. Most recently with the serde_ini library.

**Comment by dtolnay** [comment]
Closing as something that will need to be addressed in individual data formats. I would be interested in seeing someone write a Deserializer adapter library (similar to [serde-ignored](https://github.com/dtolnay/serde-ignored)) that adds field names or paths into error messages.

**Comment by Turbo87** [comment]
for anyone finding this issue in the future: the solution to the above comment lives at https://github.com/dtolnay/path-to-error 😉
