### ISSUE TITLE
Misleading "not found in this scope" error

### ISSUE THREAD

**Issue by emk** [serde-rs/serde#923]
I'm loving the new `serde`!

This is a bit of an unfortunate error message, and it's probably `rustc`'s fault, but I thought I would report it:

```
/// A parsed version of our configuration file.
#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct Config {
    /// Configuration for each notifier.
    notifiers: HashMap<String, NotifierConfig>,
}

# No definition of NotifierConfig.
```

Here, the `error[E0412]:` is correct, but the brightly colored "not found in this scope" below it points to the wrong thing.

```
error[E0412]: cannot find type `NotifierConfig` in this scope
 --> src/config.rs:6:35
  |
6 | #[derive(Clone, Debug, Serialize, Deserialize)]
  |                                   ^^^^^^^^^^^ not found in this scope
```

The fix, of course, is to implement `NotifierConfig`. I know you can't do much about this error, but I thought you might like to know that there was a minor ergonomic issue.

**Comment by dtolnay** [comment]
Thanks! This is a limitation of Macros 1.1 and will be fixed by https://github.com/rust-lang/rust/pull/40939.

**Comment by ZelphirKaltstahl** [comment]
This can also happen, when one forgets to add the following in the main module of the application:

    // In order to use the Serialize and Deserialize macros in the model,
    // we need to declare in the main module, that we are using them.
    #[macro_use]
    extern crate serde_derive;
