### ISSUE TITLE
json::from_value expected Value found &Value

### ISSUE THREAD

**Issue by linuxaged** [serde-rs/serde#93]
When I try to deserialize an array to vector:

    let data: Value = json::from_str(&s).unwrap();
    let meshes = data.find("meshes").unwrap();
    let mesh_array = meshes.as_array().unwrap();
    let mesh = mesh_array[0].as_object().unwrap();

    let vertices: Vec<f64> = (json::from_value (mesh.get("vertices").unwrap()) ).unwrap();
    

get the error:

	src/main.rs:17:49: 17:78 error: mismatched types:
	 expected `serde::json::value::Value`,
	    found `&serde::json::value::Value`
	(expected enum `serde::json::value::Value`,
	    found &-ptr) [E0308]
	src/main.rs:17     let vertices: Vec<f64> = (json::from_value (mesh.get("vertices").unwrap()) ).unwrap();
	                                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~

unwrap().clone() works here, but it is very consuming right?
is there a pass-by-ref version json::from_value, how to deal with this?

**Comment by erickt** [comment]
There isn't a pass-by-ref because I want to retain the option to move strings out of the maps without copies. Do you need to deserialize into a Value? If not you could instead deserialize into a 

```rust
#[derive(Deserialize)]
struct Mesh {...}

#[derive(Deserialize)]
struct Object {
   Meshes: Vec<Mesh>,
}
```

**Comment by linuxaged** [comment]
The reason I do deserializing by parsing fields one by one is serde not supporting [defaults for missing struct fields](https://github.com/serde-rs/serde/issues/90) or [ignore unkown fields](https://github.com/serde-rs/serde/issues/44)
