### ISSUE TITLE
Warn when using only one of skip_serializing and skip_deserializing

### ISSUE THREAD

**Issue by spikefoo** [serde-rs/serde#931]
I used the `skip_serializing` attribute for a field, but forgot to add `skip_deserializing` too. After serializing my data to a binary format (with `bincode`), I tried to deserialize it but got an error which took a long time to track down.

```
/* Example code */
#[derive(Serialize, Deserialize)]
pub struct Data {
    #[serde(skip_serializing)] // forgot skip_deserializing
    foo: u32,
    //...
}
```

If `Serialize` and `Deserialize` are both derived, then it never makes sense to use only one of `skip_serializing` and `skip_deserializing` -- I expect a derived serializer to always be compatible with the derived deserializer.

Here are some ways to prevent this:

  - Warn when both `Serialize` and `Deserialize` and derived but only one of `skip_serializing` and `skip_deserializing` is used.
  - Make `skip_serializing` imply `skip_deserializing` and vice versa.
  - Replace `skip_serializing` and `skip_deserializing` with a single attribute that means both.
  - (As a last resort: in the documentation for `skip_serializing`, add the warning "You may want to use `skip_deserializing` too.", and vice versa.)

This issue also applies to:

  - The `skip_serializing` and `skip_deserializing` variant attributes.
  - The `serialize_with` and `deserialize_with` field attributes.

What do you think?

**Comment by dtolnay** [comment]
From some quick github searches it looks like having one but not both of `skip_serializing` and `skip_deserializing` on a type that derives both `Serialize` and `Deserialize` is fairly uncommon but there are some legitimate use cases. I would be on board with adding a single attribute that means both, and improving the documentation. Would you be interested in tackling this with a PR? It would probably look a lot like #765.

Having one but not both of `serialize_with` and `deserialize_with` on a type that derives both `Serialize` and `Deserialize` is more common. Here is a sample of some:

- [fac-rs](https://github.com/Arnavion/fac-rs/blob/51b34261aa9f21ef4c926bed8302feab84619235/src/config.rs#L6)
- [rusoto](https://github.com/rusoto/rusoto/blob/8dbe7ef0022e926f43fe5d2965babcce63b530ca/service_crategen/src/cargo.rs#L10)
- [rustc-perf](https://github.com/rust-lang-nursery/rustc-perf/blob/ffb2326fe3b8ec05d3da14e6cdb7150024761110/src/server.rs#L283)
- [rustiful](https://github.com/blakepettersson/rustiful/blob/3ddfac5db399fe5e58e220d8a14417579d74dcdb/rustiful-derive/src/json.rs#L164)
- [mastodon-rs](https://github.com/tinaun/mastodon-rs/blob/9b034358527ce3ccfa230b4fe8b05f7f94184fda/src/entities.rs#L86)
- [ganbare](https://github.com/golddranks/ganbare/blob/79a849e1f1eda8266b70d6b5b118d66ceeecb169/ganbare_backend/src/models.rs#L307)
