### ISSUE TITLE
Automatically deserialize template type

### ISSUE THREAD

**Issue by debris** [serde-rs/serde#943]
I have two data structures: `Foo` and `Bar`.

```rust
#[derive(Deserialize, Serialize)]
struct Foo {
	foo: u8,
}

#[derive(Deserialize)]
struct Bar<F: Deserialize> {
	foo: F,
}
```

The code above was working perfectly fine with `serde 0.9`. After migration to `1.0` it broke and I had to hack it to make it work

```rust
#[derive(Deserialize, Serialize)]
struct Foo {
	foo: u8,
}

#[derive(Deserialize, Serialize)]
struct Bar<F: DeserializeOwned> {
	#[serde(deserialize_with = "Deserialize::deserialize")]
	foo: F,
}
```

Imo, calling `#[serde(deserialize_with = "")]` is completely redundant and introduces unnecessary noice. It would be nice to automatically add it to template properties.

**Comment by dtolnay** [comment]
The inference issue is a Rust bug: https://github.com/rust-lang/rust/issues/41617. Separately, you should not have any trait bound on the `F` type parameter. See https://github.com/Manishearth/rust-clippy/issues/1689.

```rust
#[derive(Deserialize, Serialize)]
struct Foo {
    foo: u8,
}

#[derive(Deserialize, Serialize)]
struct Bar<F> {
    foo: F,
}
```

**Comment by debris** [comment]
thanks!
