### ISSUE TITLE
tuple_variant behaves differently than a simple seq

### ISSUE THREAD

**Issue by chpio** [serde-rs/serde#945]
A seq calls `SeqAccess::next_element` until no value is returned, but a `tuple_variant` calls it just the number of times it expects a value. Without pulling all values from the seq, without calling it a final time, thus not consuming the end marker.

Why does it behave differently than a "simple" seq?

**Comment by oli-obk** [comment]
Your format might not know the number of elements, because there's no need to encode the number, since the number is passed  to the format via the deserialize_tuple method.

**Comment by chpio** [comment]
yeah, but now i have to save it (in some kind of stack structure).

**Comment by oli-obk** [comment]
> yeah, but now i have to save it (in some kind of stack structure).

Not sure I understand. Are you implementing your own format? If so, maybe you can do it like json? [serde-json simply does the cleanup after the visit_seq call](https://github.com/serde-rs/json/blob/master/src/de.rs#L223)

**Comment by chpio** [comment]
ahh, yeah thank you. I impled it by counting the elements and stopping after the expected len, but your solution is better.
