### ISSUE TITLE
Serializer trait self by value

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#946]
From IRC:

> **\<theotherphil>** Basic API design question: why does the serde Serializer trait takes self arguments instead of &mut self? The JSON serializer example in the docs then implements Serializer for &'a mut TheSerializerStruct. Is this because this approach is strictly more general in theory, more general in an important way in practise, or strictly required for some reason (lifetimes?)

**Comment by dtolnay** [comment]
@theotherphil it prevents you from being able to write an incorrect Serialize implementation. See [here](https://github.com/serde-rs/serde/releases/tag/v0.9.0) for the full explanation.

```rust
impl Serialize for S {
    // Serde API from before version 0.9
    fn serialize<S>(&self, serializer: &mut S) -> Result<(), S::Error>
        where S: Serializer
    {
        serializer.serialize_str("first")?;

        // This needs to be forbidden by the type system. Most data formats would
        // generate syntactically invalid output if any implementation does this.
        serializer.serialize_str("another")?;

        Ok(())
    }
}
```

**Comment by theotherphil** [comment]
Do you automatically track all mentions of serde on IRC or did someone just bring this to your attention? 

Regardless, thanks very much for answering this!

**Comment by dtolnay** [comment]
Here is what happens when the type system doesn't catch when you write a bad impl, as with rustc-serialize https://github.com/rust-lang/rust/issues/42374.
