### ISSUE TITLE
Add index attribute

### ISSUE THREAD

**Issue by vitiral** [serde-rs/serde#951]
For no_std cases it would be nice to override the `variant_index`. 

Microcontroller APIs will want to be able to group the varians by their index ID, so being able to hard code it is important

**Comment by dtolnay** [comment]
I would prefer to see this provided by a different crate with derive macros specific to this use case (or to microcontroller APIs generally). Something like:

```rust
#[derive(SerializeIndex, DeserializeIndex)]
enum E {
    A = 2,
    B = 4,
    C = 6,
}
```
