### ISSUE TITLE
MessagePack support

### ISSUE THREAD

**Issue by 3Hren** [serde-rs/serde#96]
Does anyone need MessagePack support?

I can implement it in https://github.com/3Hren/msgpack-rust as an option.

It's not an issue actually, but it **may** generate issues if I start to working with it :)

**Comment by erickt** [comment]
That would be wonderful! If you haven't starting working on it yet, I think I have a partially implemented version I started and didn't finish months ago.

**Comment by dswd** [comment]
I am working on that. It seems to work pretty well except for enums which are very complicated as each variant can have a different type. How should I publish the code?
Should I make a separate crate or should I create a pull request?
BTW: I also have some macros which allow to serialize structs to tuples and maps without using a compiler plugin.

**Comment by 3Hren** [comment]
Actually I've already have `rustc_serialize` support: https://github.com/3Hren/msgpack-rust/blob/master/src/decode.rs#L1754.
Migrating from it to `serde` doesn't seems like a big problem.

The real challenge - is to how implement zero-copy deserialization into a non-owning structs, which contains `&str` or `&[T]` for example. Does `serde` allows to do that somehow?

PR is ok if only `serde` plans to be the **main** serialization/deserialization library (and `rustc_serialize` is going to be dead, right?).

**Comment by dswd** [comment]
My main problem with rmp, mpack and msgpack was that neither of them allowed me to serialize [u8] to msgpack bin. Instead all rustc-serialize based serializers serialize [u8] as a list of single u8 which is very inefficient as half of those bytes require two bytes to serialize.

**Comment by 3Hren** [comment]
Wrong: https://github.com/3Hren/msgpack-rust/blob/master/src/encode.rs#L634

**Comment by dswd** [comment]
Yes, you are right. However I did not figure out any way to use that with rustc-serialize.

**Comment by 3Hren** [comment]
With `rustc_serialize` - you're right, it's impossible. Does `serde` allows to encode `&[u8]` directly?

**Comment by dswd** [comment]
Not exactly but there is a wrapper type `Bytes` which serializes to bin. I don't think such a wrapper type would be possible with `rustc_serialize` as it does not expose any way to serialize binary data through its API.

**Comment by erickt** [comment]
@3Hren and @dswd: I've also hacked up msgpack support in https://github.com/3Hren/msgpack-rust/pull/26.

**Comment by erickt** [comment]
This has landed in rmp!

**Comment by dswd** [comment]
I don't see how this improves on the `&[u8]` issue. As far as I can see rmp still does not support it. There is no way to serialize something to binary data and you get a type mismatch error if you try to deserialize it.

**Comment by 3Hren** [comment]
Does this helps: https://github.com/3Hren/msgpack-rust/commit/380a68be68c7468c4f53e240fe149a557ee31357

**Comment by 3Hren** [comment]
And this should help with serialization: https://github.com/3Hren/msgpack-rust/commit/6c1f7c18fc036e746c787441450f209aec86cba0
