### ISSUE TITLE
Pass field index to SerializeStruct::serialize_field

### ISSUE THREAD

**Issue by dtolnay** [serde-rs/serde#960]
Similar to how `Serializer::serialize_*_variant` receives both the index and name of the variant. This would enable CBOR to deserialize correctly from a packed representation (integer keys) with fields that are conditionally skipped - https://github.com/pyfisch/cbor/issues/37.

**Comment by sfackler** [comment]
Possible approach:

```rust
pub trait SerializeStruct {
    type Ok;
    type Error: Error;
    fn serialize_field<T: ?Sized>(
        &mut self, 
        key: &'static str, 
        value: &T
    ) -> Result<(), Self::Error>
    where
        T: Serialize;

    fn serialize_indexed_field<T: ?Sized>(
        &mut self,
        key: &'static str,
        key_index: u32,
        value: &T
    ) -> Result<(), Self::Error>
    where
        T: Serialize
    {
        self.serialize_field(key, value)
    }

    fn end(self) -> Result<Self::Ok, Self::Error>;
}
```

Serializers that care about packed encodings would override both methods and everything else could ignore serialize_indexed_field. serde_derive would call into serialize_indexed_field, assuming it can force a bump of serde along side it which seems reasonable.

**Comment by dtolnay** [comment]
A different approach:

```rust
// SerializeStruct
fn skip_field(&mut self, key: &'static str) -> Result<(), Self::Error> {
    Ok(())
}

// Serialize
if $skip_serializing(&self.x) {
    s.skip_field("x")?;
} else {
    s.serialize_field("x", &self.x)?;
}
```

- No longer exposes the possibility of serializing fields out of numerical order, as in https://github.com/serde-rs/serde/pull/961#issuecomment-310588663.
- Bincode and friends can return an error on skipped fields with zero overhead when there are no skipped fields.
- Serializers that require a field index don't need to awkwardly override both `serialize_field` and `serialize_indexed_field`.
- Serializers receive the name of skipped fields for better error messages.

Thoughts?

**Comment by sfackler** [comment]
That sounds like a good approach - not having to deal with both `serialize_field` and `serialize_indexed_field` is nice.
