### ISSUE TITLE
Compiler error E0283

### ISSUE THREAD

**Issue by heartsucker** [serde-rs/serde#967]
I have a struct that is trying to derive `Deserialize` and I'm getting this error.

```
error[E0283]: type annotations required: cannot resolve `V: serde::Deserialize<'de>`
  --> src/session.rs:20:28
   |
20 | #[derive(Clone, Serialize, Deserialize, Eq, PartialEq)]
   |                            ^^^^^^^^^^^
   |
   = note: required by `serde::Deserialize`
```

I don't see how to give the derive macro more information. Am I a missing something?

**Comment by oli-obk** [comment]
Can you show your struct definition? Is your struct generic?

**Comment by dtolnay** [comment]
This sounds like https://github.com/Manishearth/rust-clippy/issues/1689. Get rid of the trait bounds on your struct.

```diff
- struct Heartsucker<T: Deserialize> { /* ... */ }
+ struct Heartsucker<T> { /* ... */ }
```

As a general rule, structs should not have trait bounds.

**Comment by heartsucker** [comment]
Ah, that fixed it. Was that always the behavior?

**Comment by dtolnay** [comment]
This was always the behavior but it is a Rust bug so it may be solved in the future. https://github.com/rust-lang/rust/issues/41617
