### ISSUE TITLE
How to deserialize few fields into a subobject?

### ISSUE THREAD

**Issue by vityafx** [serde-rs/serde#969]
Let's pretend I have an object:

```json
{
    "field1": "text1",
    "field2": "text2",
    "fieldX": 15
}
```

Is there a way to parse it into the following structure?

```rust
struct S {
    fields: Fields,
    fieldX: u64,
}

struct Fields {
    field1: String,
    field2: String,
}
```

**Comment by oli-obk** [comment]
Unfortunately there's no way to do that with an attribute yet.

This feature is tracked in https://github.com/serde-rs/serde/issues/119 (flattening fields).

**Comment by vityafx** [comment]
@oli-obk okay, thanks!
