### ISSUE TITLE
Resolving 'warning: unnecessary lifetime parameter `'de`'?

### ISSUE THREAD

**Issue by expenses** [serde-rs/serde#974]
Hi, I'm new to Serde, so sorry if this is actually pretty obvious. The following code:

    #[macro_use]
    extern crate serde_derive;

    #[derive(Serialize, Deserialize)]
    pub enum ItemType {
        Scrap,
        Weapon,
        Skeleton
    }

    #[derive(Serialize, Deserialize)]
    pub struct Item {
        pub tag: ItemType,
        pub image: &'static str
    }

    fn main() {
        Item { tag: ItemType::Weapon, image: "Machine Gun" };
    }

gives me a warning:

    warning: unnecessary lifetime parameter `'de`
      --> src/main.rs:11:21
       |
    11 | #[derive(Serialize, Deserialize)]
       |                     ^^^^^^^^^^^
       |
       = help: you can use the 'static` lifetime directly, in place of `'de`

Is it possible to avoid this error, and if so, what should I be doing differently?

**Comment by oli-obk** [comment]
You can change your struct to

```rust
pub struct Item<'a> {
    pub tag: ItemType,
    pub image: &'a str,
}
```

in order to make it more general. Limiting it to `'static` will make the deserialize impl nearly impossible to use.

**Comment by dtolnay** [comment]
I filed #975 to improve the generated code.
