### ISSUE TITLE
Allow deserializing rustc-serialize enums

### ISSUE THREAD

**Issue by jethrogb** [serde-rs/serde#977]
Rustc-serialize serialized enums have quite a special encoding and it's hard to deserialize them with serde right now. It would be nice if there was an enum tagging option (e.g. `#[serde(rustc_serialize_tagged)]`) that provides rustc-serialize compatibility.

The rustc-serialize enum format is as follows:
* Unit variants get encoded as a string
* Tuple and struct variants get encoded as a map with two fields: `variant` and `fields`.
  * `variant` contains the variant name as a string.
  * `fields` contains the variant data as a tuple, regardless of whether it's a struct or tuple variant.
  * Note: this is not the same as serde's adjacently-tagged encoding. Serde encodes 1-tuples as the value directly instead of as a tuple.

Currently to decode with serde you have to write this:
```rust
/// Decoder for
///
/// ```
/// enum Test {
///     A,
///     B(u8),
///     C(u8, u8),
///     D{a: u8},
///     E{a: u8, b: u8},
/// }
/// ```

#[derive(Deserialize)]
enum TestUnits {
    A,
}

#[derive(Deserialize)]
#[serde(tag="variant", content="fields")]
enum TestTuples {
    B((u8,)),
    C(u8, u8),
    D((u8,)),
    E(u8, u8),
}

#[derive(Deserialize)]
#[serde(untagged)]
enum TestRustc {
    Unit(TestUnits),
    Tuple(TestTuples),
}
```
You can deserialize a `TestRustc` and convert it to a `Test` with `match`.

**Comment by dtolnay** [comment]
Can you say more about your use case for this? Are there reasons to prefer this representation in a future where rustc-serialize is long forgotten? Are you planning to use this in a Serde-based server that needs to receive requests from a rustc-serialize-based client? Or to migrate some data previously saved by rustc-serialize to Serde? Something else...?

**Comment by jethrogb** [comment]
> Are there reasons to prefer this representation

None that I'm aware of. The representation is pretty arbitrary.

This feature would be only for the two backwards-compatibility reasons you mentioned.

**Comment by dtolnay** [comment]
Cool. In the first case, the server having `#[derive(Deserialize)]` enums and the client having `#[derive(RustcEncodable)]` copy of the same enums sounds like a nightmare and I am not interested in encouraging that. The rustc-serialize derives are deprecated anyway.

In the second case, you would write `#[derive(RustcDecodable, Serialize)]`, parse the old data with rustc-serialize, and write it back out with Serde. That should not require Serde to handle rustc-serialize's arbitrary representation.
