### ISSUE TITLE
De/serialize enum as array

### ISSUE THREAD

**Issue by tailhook** [serde-rs/serde#979]
Hi, I think one representation for enum is missing. E.g. if we have some enum like this:
```
enum State {
  Initializing,
  Reading(usize),
  Writing(usize, usize),
  Done,
}
```
The short and nice representation would be (showing json):
```
["Initializing"]
["Reading", 1234]
["Writing", 3, 1234]
["Done"]
```
Or even:
```
"Initializing"
["Reading", 1234]
["Writing", 3, 1234]
"Done"
```
This works well for unit variants and tuple variants. And is more compact than other representations. I think this is useful for representing state machines as in the example above.

What do you think?

**Comment by dtolnay** [comment]
Seems reasonable. Do you know of any existing serialization libraries in other languages that support this style, or JSON APIs that use this style?

**Comment by tailhook** [comment]
From the top of my head WAMP protocol fits the "JSON APIs" category:
```
[HELLO, Realm|uri, Details|dict]
[WELCOME, Session|id, Details|dict]
```
 http://wamp-proto.org/static/rfc/draft-oberstet-hybi-crossbar-wamp.html#session-lifecycle

**Comment by tailhook** [comment]
Technically WAMP also uses numeric IDs as the first item which might be a good option too.

**Comment by RReverser** [comment]
I had the same issue with parsing html5lib-tests (https://github.com/html5lib/html5lib-tests/blob/master/tokenizer/test1.test#L246), had to implement manually.

**Comment by tailhook** [comment]
I'll try implementing this issue if no one is working on it. I'm not familiar with internals of serde though, so I'm not sure that I'll have enough time for the implementation.

Any preliminary hints? Objections?

**Comment by dtolnay** [comment]
This doesn't necessarily need to involve changing serde internals. [Here is a small shim](https://play.rust-lang.org/?gist=7d0d1347993426106f9ce60c48974442) that you could drop into a crate to make this work.

**Comment by tailhook** [comment]
@dtolnay, nice hack. I might use it somewhere. Still, it's a bit unfortunate that it has to be in `serde(with)` (i.e. can't be applied for the structure itself).

Just to be clear: are you opposed to get it into a serde? Or do you think this is a waste of time? Or PR is also okay?

**Comment by dtolnay** [comment]
I would prefer to design an approach that allows the logic here to live outside of Serde (like in that playground link) but still be used for type's Deserialize implementation. https://github.com/serde-rs/serde/pull/1111#issuecomment-349386342 is a very similar situation so cc @Marwes. Essentially we want a concise way to derive the serialize/deserialize code for the type as usual, but then use some other implementation as *the* Serialize/Deserialize impl for the type.

**Comment by Marwes** [comment]
So with https://github.com/serde-rs/serde/pull/1111#issuecomment-349386342 it should be possible to remove the wrapper and do this instead (+ the serializer/deserializer wrappers)

```rust

#[derive(Serialize, Deserialize, Debug)]
#[serde(freestanding_serialize = "serialize_state")]
#[serde(freestanding_deserialize = "deserialize_state")]
enum State {
    Initializing,
    Reading(usize),
    Writing(usize, usize),
    Done,
}

impl Serialize for State {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serialize_state(EnumAsArray(serializer))
    }
}

impl Deserialize for State {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error> {
        deserialize_state(EnumAsArray(deserializer))
    }
}
```
https://play.rust-lang.org/?gist=e51b0de2f0e798934c9d6cc0772f10b6&version=stable

**Comment by tailhook** [comment]
@dtolnay, @Marwes take a look at #1118. That solution is better than `freestanding_serialize` because it allows encapsulating implementation into a module/crate. In your solution, you still need to write a one-line implementation for each structure.

**Comment by dtolnay** [comment]
Closing in favor of #1118.
