### ISSUE TITLE
Unable to change ownership of Values within serde_json::Map

### ISSUE THREAD

**Issue by CT075** [serde-rs/serde#985]
I'm currently working on an application that needs to load json with a structure like

    { "unknown_name" : { "obj" : "with_fixed_fields" },
      "other_unknown_name" : { "obj" : "same_fields" },
      ...
    }

Note that the structure of the inner data is known at compile-time but the keys in the containing structure are not. 

My thought was to parse the json into a `serde_json::Value`, extract the Value::Object, then iterate over (k,v) pairs using `Map.iter()` or `Map.iter_mut()` to populate a separate `HashMap<String, FixedObject>`. However, it seems that I can only pass the inner Values by reference (which means that the fixed struct can't take ownership of the inner fields). I've been working around this by manually cloning the inner values to the created struct and letting the original Value fall out of scope, but that seems like the wrong approach. I think an equivalent to [std::collections::HashMap::drain](https://doc.rust-lang.org/std/collections/hash_map/struct.HashMap.html#method.drain) might be a useful thing to have.

**Comment by dtolnay** [comment]
You can deserialize directly into `HashMap<String, FixedObject>`.

**Comment by CT075** [comment]
Would I need to implement a custom deserializer to add "defaults" to fields?

**Comment by dtolnay** [comment]
Not necessarily. Would something like this work?

```rust
#[macro_use]
extern crate serde_derive;

extern crate serde;
extern crate serde_json;

use std::collections::HashMap;

#[derive(Deserialize, Debug)]
struct FixedObject {
    obj: String,
}

fn main() {
    let j = r#"
      { "unknown_name" : { "obj" : "with_fixed_fields" },
        "other_unknown_name" : { "obj" : "same_fields" }
      } "#;

    let mut map: HashMap<String, FixedObject> = serde_json::from_str(j).unwrap();

    // Apply defaults
    map.entry("username".to_owned())
        .or_insert(FixedObject { obj: "CT075".to_owned() });
    map.entry("other_unknown_name".to_owned())
        .or_insert(FixedObject { obj: "~~~".to_owned() });

    println!("{:#?}", map);
}
```

**Comment by CT075** [comment]
I'm not sure; I think I'm misunderstanding the pattern. The inner object should always have fixed fields, but the given JSON may have them omitted (with missing values filled with defaults)

**Comment by dtolnay** [comment]
Oh for the inner struct it works the same as always. Refer to https://serde.rs/attr-default.html. Those attributes are not disrupted by being inside of a HashMap, if that's what you were concerned about.

**Comment by CT075** [comment]
Aha, okay. Thanks!
