### ISSUE TITLE
Do not serialize fixed-size arrays like tuples

### ISSUE THREAD

**Issue by torkleyy** [serde-rs/serde#989]
I'm building a new format, and I'd like tuples to be `(a, b, c)` and arrays `[a, b, c]`. Now, it is very confusing that serializing `&[i32]` gives me `[1, 2, 3]`, but `&[i32; 3]` gives me `(1, 2, 3)`.

How would I solve that?

**Comment by ahmedcharles** [comment]
Disclaimer: I'm not on the serde team or anything.

When looking at the docs for the [data model](https://serde.rs/data-model.html), the only difference between sequences and tuples are that tuples are fixed size and sequences are variable.

In your format, there seems to be no difference between fixed and variable length lists, so this would seem to boil down to a cosmetic issue.

**Comment by dtolnay** [comment]
From Serde's perspective `(i32, i32, i32)` and `[i32; 3]` are the same type. Both are a collection of three i32 where deserialization will know ahead of time that there are three elements (unlike a Vec\<i32\> for example, where the length is determined by looking at the serialized data).

You can override how a type is serialized using `serialize_with`. Maybe you could provide a helper like this along with your new format.

```rust
mod torkleyy {
    use serde::{Serialize, Serializer};

    pub fn array<T, S>(arr: T, serializer: S) -> Result<S::Ok, S::Error>
        where T: IntoIterator,
              T::Item: Serialize,
              S: Serializer
    {
        serializer.collect_seq(arr)
    }
}

#[derive(Serialize)]
struct S {
    // Ordinarily this would be serialized as a tuple, but serialize it as a Serde seq.
    #[serde(serialize_with = "torkleyy::array")]
    arr: [i32; 3],
}
```

**Comment by torkleyy** [comment]
I see. Thank you!
