### ISSUE TITLE
Deserialize complex structure with dynamic defaults

### ISSUE THREAD

**Issue by CT075** [serde-rs/serde#992]
I have a structure similar to the following:

```rust
pub struct Data {
    a: i32,
    b: bool,
    c: String
}

pub enum Obj {
    A(Vec<u8>),
    B(Data)
}
```

and I would like to deserialize to objects of type `Obj`. I thought I would do this using Visitor, which has been working -- however, I'm not sure how i'd implement dynamic defaults for the fields in Data. These defaults would be unknown until runtime -- that is, if I passed in `{ "a":1, "c":"lol" }` with a default of `{ a:2, b: false, c: "kek" }`, I would get `B({ a:1, b:false, c:"lol"})`. I can currently think of two ways to do this:

1. Create and implement a trait requiring [field]Default methods that is passed around as a type bound -- that is, Obj becomes Obj<P:Defaults> (this seems like a terrible idea).

2. Keep a global/static "defaults" struct singleton that gets modified before calling deserialize (this seems like a "better" idea, as I don't need threads or anything, but I've read that using global mutable state in Rust is frowned upon).

**Comment by dtolnay** [comment]
Check out [`DeserializeSeed`](https://docs.serde.rs/serde/de/trait.DeserializeSeed.html). You would make some type to hold the runtime defaults and implement DeserializeSeed on that type with Value=Obj.

**Comment by CT075** [comment]
Ah, thanks!

**Comment by BusyJay** [comment]
Can serde also take [`Default`](https://doc.rust-lang.org/std/default/trait.Default.html) trait into consideration? It's redundant to implement default value several times.

**Comment by dtolnay** [comment]
Yes, the following would use `Default`'s value for any missing field.

```rust
#[derive(Deserialize)]
#[serde(default)]
struct BusyJay {
    a: i32,
    b: bool,
    c: String,
}

impl Default for BusyJay {
    /* ... */
}
```

**Comment by BusyJay** [comment]
Thx for the explanation. I did miss the container attributes. :)
