### ISSUE TITLE
Using `with` on inner type parameters

### ISSUE THREAD

**Issue by lawliet89** [serde-rs/serde#993]
Consider the [`Url`](https://docs.rs/url/1.5.1/url/struct.Url.html) struct where the serde implementation is provided by a separate crate [`url_serde`](https://docs.rs/url_serde/0.2.0/url_serde/).

If my struct contains a ` Url` to be (de)serialized, I can do:

```rust
#[derive(Serialize, Deserialize)]
struct MyStruct {
    #[serde(with = "url_serde")]
    url: Url,
}
```

But if my struct contains something else like `HashMap<Url>`, I will have to define a new [wrapper type](https://github.com/lawliet89/rocket_cors/blob/87e41454937189000be541f405c3244faf823b95/src/headers.rs#L60-L65) around `Url` before I can include `HashMap<Url>` in my struct AFAIK.

Is it even possible for serde to support the `with` attribute for this inner `Url` type?

**Comment by dtolnay** [comment]
This is not supported but we are tracking it in #723. It needs more design work.

**Comment by lawliet89** [comment]
Thanks. I guess I wasn't using the right keywords to search.
