### ISSUE TITLE
Serde_state: Enums not supported?

### ISSUE THREAD

**Issue by MageSlayer** [serde-rs/serde#997]
Hi

I am trying to serialize my enum using serde_state.
Unfortunate it fails to compile. See below
```
#[derive(Debug, Clone, SerializeState, DeserializeState)]
#[serde(serialize_state = "*mut Arena")]
#[serde(deserialize_state = "*mut Arena")]
pub enum AST {
    Any,
    Bool { value: bool },
    Name { value: ASTName },

    #[serde(seed)]
    Symbol {
        value: ASTSym
    },

```
it just gives:

```
   --> src/parse/ast.rs:382:40
    |
382 | #[derive(Debug, Clone, SerializeState, DeserializeState)]
    |                                        ^^^^^^^^^^^^^^^^
    |
    = help: message: unknown serde variant attribute `seed`
```

Are enums supported by serde_state at all?
Or maybe I am missing something?

Tested using Rust nightly + serde_state v0.3.0

**Comment by dtolnay** [comment]
@Marwes

**Comment by Marwes** [comment]
@MageSlayer You need to replace `serde (seed)` with `serde(state)`.  I fixed that in 0.3 after noticing that I missed it in an earlier search and replace.

**Comment by Marwes** [comment]
Also, you need to mark each field instead of each variant as the attribute is not applied recursively (though that may be nice to have, I think some other attributes work like that)

**Comment by MageSlayer** [comment]
Aha, looks like it works now with "serde(state)".
Yeap, I missed that in 0.3.0 it was changed.
Thanks.
