### ISSUE TITLE
Provide a way to "finalize" deserializaton

### ISSUE THREAD

**Issue by RReverser** [serde-rs/serde#998]
Sometimes, you can describe the structure almost perfectly in struct with just `derive(Deserialize)`, but just need some extra steps to "finalize" it depending on some fields etc..

When you are deserializing struct directly, it's possible to just add extra method for that, but when it's part of other `derive(Deserialize)` items, it becomes less convenient, and you have to reimplement `Deserialize` completely or write `deserialize_with` everywhere.

It would be nice if serde would provide such hook for "finalization" in the core.

**Comment by dtolnay** [comment]
Thanks! We are tracking this in #642.

**Comment by RReverser** [comment]
Oh, sorry, missed it.
