### ISSUE TITLE
Remote types and containers

### ISSUE THREAD

**Issue by arcnmx** [serde-rs/serde#999]
Say I have the following remote types:

```rust
mod remote {
    pub struct Seconds(u64);

    pub struct Duration {
        pub secs: Option<Seconds>,
    }
}

#[derive(Deserialize)]
#[serde(remote = "remote::Seconds")]
struct SecondsDef(u64);

#[derive(Deserialize)]
#[serde(remote = "remote::Duration")]
struct DurationDef {
    #[serde(with = "SecondsDef")]
    secs: Option<remote::Seconds>,
}
```

Is it possible to arrange the remote deserialize to deal with this? It gets worse with my use case, having multiple levels of nesting and things like `Option<Vec<etc>>`...

**Comment by dtolnay** [comment]
Not currently. We are tracking this in #723. I would love your thoughts on a design!

**Comment by arcnmx** [comment]
Ah thanks for the link! I was only searching for the "remote" keyword. I'd need to think about the approach but a short inline attribute like `map!(SecondsDef)` would certainly be convenient. I suppose `with` and its path concat slightly complicates that vs `serialize_with`?
